### ISSUE TITLE
Center all global errors

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1009]
We'll want to find a good way to vertically center the global error placards on the page (and other places such as modals). 

![screen shot 2018-10-19 at 9 12 44 pm](https://user-images.githubusercontent.com/522079/47249790-ee131680-d3e5-11e8-998f-1f0fadd812ab.png)

**Comment by benhaynes** [comment]
Resurrected!

![Resurrected!](https://media.giphy.com/media/XL1vWjpss1sU8/giphy.gif)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
