### ISSUE TITLE
Gray-out favicon when not authenticated

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1013]
We have the accent (blue) favicon for the App... but we should show a "lighter-gray" color version when the App is _not_ authenticated.

## Gray Favicons:

[gray-favicons.zip](https://github.com/directus/app/files/2497742/gray-favicons.zip)

## Looks like this

![android-chrome-192x192](https://user-images.githubusercontent.com/522079/47250444-fcb1fb80-d3ee-11e8-9e21-bf75b2e98968.png)

**Comment by benhaynes** [comment]
Resurrected!

![Resurrected!](https://media.giphy.com/media/XL1vWjpss1sU8/giphy.gif)

**Comment by benhaynes** [comment]
WTF stalebot... keep this open!

**Comment by gagandeepp** [comment]
is this open?

**Comment by benhaynes** [comment]
Hey @gagandeepp – it is! Are you interested in contributing? 😄

**Comment by gagandeepp** [comment]
yes

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by benhaynes** [comment]
Awesome! We'd love to get a PR for this...

Feel free to reach out here or on our [Slack](https://slack.getdirectus.com/) if you have any questions regarding implementation! And thanks!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
