### ISSUE TITLE
Focus in alert input

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1015]
When you open an alert with an input (eg: Create Bookmark) it should focus in the input.

**Comment by harshil1712** [comment]
Hey, I would like to take this one

**Comment by benhaynes** [comment]
Hey @harshil1712 – you actually adjusted ALL inputs with that change... which definitely won't work for this fix. My mistake... I should have spent more time reviewing things.

**Comment by harshil1712** [comment]
@benhaynes sorry I thought that was it. So do we just need to have focus for the create bookmark input?

**Comment by rijkvanzanten** [comment]
The ideal solution would be to add autofocus to whatever input is first in any modal. In terms of the `prompt` component, we know what this component is. 

The `prompt.vue` component (which is used for all "alerts" with a text input) has the two possible inputs (a textarea and a regular input) defined in it, which can both be given the autofocus prop:

https://github.com/directus/app/blob/9a3dc478794d55645f9dadd34a672da599ced498/src/components/modals/prompt.vue#L4-L16

While your solution technically achieves the same effect, it has the downside of giving every single input autofocus by default, which will cause issues when there are more than one inputs rendered at the same time 🙂
