### ISSUE TITLE
Add the option to choose "mine" permission in Role page

### ISSUE THREAD

**Issue by Marcnuth** [directus/app#1019]
The web page does not provide the option to choose "mine" permission, please support it.

**Comment by Marcnuth** [comment]
The latest release already has this feature.  And only some fields exists the "mine" permission will show.

For anyone who may encounter this problem, please check the official documents on how to design your table:

https://docs.directus.io/app/admin-guide/permissions.html#Accountability

**Comment by benhaynes** [comment]
Glad you found it @Marcnuth! I think this might warrant an in-app tooltip pointing to the Docs to avoid confusion in the future.
