### ISSUE TITLE
Trying to access php version logged as non-admin

### ISSUE THREAD

**Issue by WellingGuzman** [directus/app#1021]
The devtools logs a _silent_ error trying to access `php_version`.

<img width="490" src="https://user-images.githubusercontent.com/1531291/47272064-fe460580-d54d-11e8-9c3a-d89c8d298a75.png">

I don't see any reason for non-admin users to know this information. At the moment only admin can read this information.

Reference:
https://github.com/directus/app/blob/c734d2eb67abbe435e3e9d755590c1fa4e5e1766/src/store/modules/server-info/actions.js#L11

**Comment by rijkvanzanten** [comment]
Good catch. It's tries retrieving everything in case we'd ever need it. It's not being used and can be safely removed.
