### ISSUE TITLE
Editing Collection: name is empty

### ISSUE THREAD

**Issue by WellingGuzman** [directus/app#1023]
Editing an existing collection the `collection` field (_the name of the collection_) is empty.

<img width="278" src="https://user-images.githubusercontent.com/1531291/47272279-6e09bf80-d551-11e8-9e4c-e29e5afd343f.png">

**Comment by benhaynes** [comment]
I can not reproduce this, and I don't have the key icon on that field. @WellingGuzman did you change this collection field to a primary key interface locally or in 2.0.2?

![screen shot 2018-10-22 at 11 07 44 am](https://user-images.githubusercontent.com/522079/47300593-dc4e9080-d5ea-11e8-88ac-010e4e49f9f9.png)

**Comment by WellingGuzman** [comment]
I get this using the latest from `build` and I didn't change anything related to `directus_collections` or `interface` name.

I will try again and confirm if it still happens.

**Comment by rijkvanzanten** [comment]
Tried it with a fresh install, and on the live demos. Seems to be working fine..
