### ISSUE TITLE
Settings: Empty Collections Styling

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1025]
Since updating the alert placard style it now appears incorrectly on the Settings Collection page when there are no collections:

![screen shot 2018-10-22 at 11 05 34 am](https://user-images.githubusercontent.com/522079/47300880-934b0c00-d5eb-11e8-834e-0dbc93cdc68f.png)

The table-header should be hidden or above the placard (directly below the system-header).

**Comment by harshil1712** [comment]
Can I take this one?

**Comment by benhaynes** [comment]
Definitely! Thank you!
