### ISSUE TITLE
SLUG Read Only, and/or exclude from Detail

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1028]
When a SLUG data type is selected, and based on another unique field, it doesn't need to be editable, or even shown in the App?

Choosing ReadOnly, or "Not in Detail" for a slug data type disables the generation of the slug value - it shouldn't!

Please allow a slug to be readonly, or excluded from the detail view, and still be generated based off the value of another field.

A slug could be generated by a filters hook, but that is more work.

**Comment by rijkvanzanten** [comment]
> A slug could be generated by a filters hook, but that is more work.

The slug interface should probably slugify the value on the server side, instead of the client side. This will allow it to work without having a "physical" counterpart in the app. 

Interfaces support their own hooks, which should be used to make this happen

**Comment by PurpleEdge2214** [comment]
Server side is a good addition to slug functionality, but you also want to allow a user to specify a slug, if they want to? Maybe it just needs some validation, App side and server side, to protect the App and Users from making invalid slugs?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
