### ISSUE TITLE
Many-to-one with only one item

### ISSUE THREAD

**Issue by danyright** [directus/app#1033]
## Description of the Bug
When creating a many-to-one relationship and there is **only one** item in the related collection, when you try to select it from the drop-down list, it doesn't actually select it.

For instance 'Articles' collection to 'Categories' collection (many to one), and there is only one 'Category' element created, the select (drop-down) list in the 'new Article' form contains only one element but it cannot be chosen.

## Steps to Reproduce
Steps to reproduce the behaviour:
1. Create a new collection called 'Categories', with one text input field: 'Name'
2. Create a new collection called 'Articles', with one text input field ('Name') and one many-to-one field ('Category') related to the 'categories' collection.
3. Create a new item in the 'Categories' collection.
4. Create a new item in the 'Articles' collection - when trying to select the category created in step 3 from the drop-down list, even though you click on it, it doesn't get selected and is not saved as selected.

## Expected Behaviour
You should be able to select the item from the drop-down list (many-to-one), even though there is only one in the list.
_This works as expected as soon as you have more than one item in the drop-down list._

## Screenshots
No screenshot at this point.

## Additional Context
No JavaScript error has been noticed in the Developer Tools console linked to this.

## Technical Details
- Device: Laptop
- OS: Arch Linux, kernel 4.18
- Browser: Firefox, Firefox developer edition, Vivaldi
- Directus App: 7.0.2
- Directus API: 2.0.2

**Comment by benhaynes** [comment]
Nice work-around @jreid06 ... we'll get a proper fix in tomorrow's release! It seems like it should stage the first/main/single value if there's no placeholder.

**Comment by rijkvanzanten** [comment]
> add some text in the "placeholder" field under the "Options" tab. You will then be able to select an item from the dropdown. This solved the issue for me @danyright

This is actually the fix! I've added a default value for the placeholder (Choose one...) so there's always some sort of placeholder. Without a placeholder, the browser <select> element automatically selects whatever the first item is in the select.
