### ISSUE TITLE
Item Listing: Highlight previous item

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1035]
From directus created by [WellingGuzman](https://github.com/WellingGuzman) : directus/directus#1979  

## Version Info
  - Directus version and branch: 6.4.4

## Expected Behavior
When you save a item and should take you back to the listing table and highlight the item row that was recently saved for couple of seconds. (aka flash the row)

## Actual Behavior

Doing nothing.

## Steps to Reproduce
 1. Go to any table listing
 2. Click on a item
 3. Save that item
 4. Nothing happens

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
