### ISSUE TITLE
Creating new User with exsiting users email overrides original user

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1036]
From directus created by [Geo719](https://github.com/Geo719) : directus/directus#1983  

## Version Info
  Latest Docker Image

## Expected Behavior
Creating a new user should be indipendent of any email used.

## Actual Behavior
Creating new User with exsiting users email overrides original user

## Steps to Reproduce
 1. Have Admin (A) user with email XYZ
 2. Create new (admin) user (B), also with email adress XYZ
 3. User data (A) will be updated with user data (B)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
