### ISSUE TITLE
Display translated column content in translated table

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1038]
From directus created by [mrleblanc101](https://github.com/mrleblanc101) : directus/directus#2136  

## Version Info
  - Directus version: 6.4.0
  - PHP version: 7.1
  - MySQL version: 5.7.21
  - Web server: nginx
  - OS name and version: macOS 10.13.4

If I follow the medium tutorial to setup translation in the official documentation, everything work.
The problem is that my main table only display the number of translation, not the column content in the admin using the default language (the one set in the settings for exemple).
Instead of seeing "Title: Project title" and "Body: Project body..." column, I see "Translation: 2" which is not very usefull since i have no way of knowing which item is which ! The ugly solution i found is having a "title" in my "projects" table and another "title" in my "projects_translation" table too, one which is translated, one which is not.

## Schema Dump, Logs, or Screenshots
![capture d ecran 2018-04-25 a 14 43 16](https://user-images.githubusercontent.com/17392251/39266274-8e3d9e58-4897-11e8-9e29-cd2ed849fd22.png)
![capture d ecran 2018-04-25 a 14 43 10](https://user-images.githubusercontent.com/17392251/39266275-8e48e5ba-4897-11e8-8b13-5dc9779fabb1.png)

**Comment by benhaynes** [comment]
@rijkvanzanten – what are your thoughts on allowing "child" (related) fields to be displayed on the item browse page?

**Comment by rijkvanzanten** [comment]
_child_ related fields? What do you mean? 

The way we do it for M2M/O2M is to only display them in a little list on hover. Displaying (a lot of) child content in the limited amount of space on the listing view is impossible layout-wise

**Comment by benhaynes** [comment]
Nevermind... brain issues. M2M needs a list, so that doesn't work. And single relationals (eg: dropdowns) show up as normal columns I think.

**Comment by rijkvanzanten** [comment]
Yeah!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
