### ISSUE TITLE
Interface: QR Code

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1039]
It would be nice to have an interface that displays a QR code (detail and browse). I imagine this as an `ALIAS` field that maps to another field to pull in a value (eg: the primary key field).

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by edenprojectde** [comment]
Maybe this is a completely different Feature Request in the API for later but i like the idea and wanted to add some spice:

If the QR Code could have a mask, the QR Code could easily be integrated on any page:
http://target.website.org/_/{table}:{id}
or {request_origin}/item/{id}
whereby the request_origin would be the location from where the API was called. OR the Deault Link of the App in the Config.

The QR Code could also be generated as an SVG later on, containing the compiled link.
This would make it possible to integrate it extremely easily and dynamically on shop pages, articles [...].

**Comment by rijkvanzanten** [comment]
You'd like to generate QR Codes to a link in the Directus app directly?

**Comment by edenprojectde** [comment]
The QR Code should be callable via an API Request, pointing to the compiled link. And the Result should be an SVG or alike to be shown on the Page where the API is being used. So.. it's probably a feature Request for the API in the first place.

The idea is this:
Have a Shop for example, and you have https://shop.org/26/this-is-my-article
The field in the App has the mask {request_origin}/{id}
The QR Code generated would have this Link when called from the API: https://shop.org/26
The Frontend can then fetch the Blogentry. (And also correct the Link to https://shop.org/26/this-is-my-article)

Title, Image and QR Code can then together be combined for Print and other Media.
This can also be used for Printed Blogs, or Download Links in Print&Media.
