### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1048]
To round-out our helpful community documents, we should add Contributing Guidelines and Pull Request Template files:

https://github.com/directus/app/community

**Comment by danyright** [comment]
Absolutely, I was about to ask about this ;-)
Thanks!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
