### ISSUE TITLE
Need a way to disable view options

### ISSUE THREAD

**Issue by benhaynes** [directus/app#105]
Once you set a field in the Listing View options, there's no way to turn it off. We need a "Disabled" option:

![screen shot 2018-04-05 at 6 06 00 pm](https://user-images.githubusercontent.com/522079/38394607-274321b8-38fd-11e8-9dd7-643b1aca9ac7.png)

**Comment by rijkvanzanten** [comment]
Moved to https://github.com/directus/extensions/issues/8
