### ISSUE TITLE
App homepage direct link to settings/collections - Simple Enhancement

### ISSUE THREAD

**Issue by PurpleEdge2214** [directus/app#1053]
# Feature Request
On the App home page can we please have a direct link to settings/collections.

## What problem does this feature solve?
When developing a new set of collections it is very frustrating to have to click on ...

Admin Users/Admin Settings/Collections & Fields

...to be able to edit the structure of a Collection after we've clicked on the name of one of the collections in the App's left column. I can't see an easy way to get back to the collection design editor?

## How do you think this should be implemented?
The list of Collections in the left column has a heading "Collections" - please make it a link to ...

settings/collections

...so the page myurl/admin/#/collections/categories ...opens.

## Would you be willing to work on this?
At this stage I wouldn't know where to start, but it looks like an easy enhancement?l
![directus_link_to_admin_ _settings_collections](https://user-images.githubusercontent.com/12757841/47626092-74192500-db7d-11e8-999e-4a83fb025d56.jpg)

**Comment by rijkvanzanten** [comment]
I wouldn't mind adding a little cog icon next to the "collections" in the sidebar nav for logged in admin users. Sounds like a solid little enhancement. Although, once you're done setting up the first time, the icon would become virtually useless right? 

@benhaynes thoughts?

**Comment by PurpleEdge2214** [comment]
@rijkvanzanten After the database and rules are established I still see no harm in having the link. 

Perhaps it should only ever be visible to users with permissions to modify the database and rules. i.e. never visible to content providers - if the App is ever used for providing content?

**Comment by rijkvanzanten** [comment]
> Perhaps it should only ever be visible to users with permissions to modify the database and rules. i.e. never visible to content providers - if the App is ever used for providing content?

Definitely! And yes, I'd even go as far as to say that content creation is the main usecase of the directus app 🙂

**Comment by PurpleEdge2214** [comment]
>  I'd even go as far as to say that content creation is the main usecase of the directus app 

Wow, that surprises me, I thought the App was for database design and specifying validation for the data submitted via the API! The API is the only means of submitting and retrieving data from the database and I thought the purpose of the App was to ensure good data in and out of the API.

**Comment by rijkvanzanten** [comment]
Nope 🙂 We designed a whole permissions and workflow system so you can setup users with specific access to certain collections to help them manage the "safe to edit by non-admin users" content

**Comment by rijkvanzanten** [comment]
Ref:

The nav menu is added in the sidebar here:

https://github.com/directus/app/blob/790d221059ef9e84ca29b77e9e7fc6f98b73799b/src/components/sidebars/nav-sidebar/nav-sidebar.vue#L17

Right now, the title is being rendered inside of a nested component in the sidebar (not the most useful):

https://github.com/directus/app/blob/790d221059ef9e84ca29b77e9e7fc6f98b73799b/src/components/sidebars/nav-sidebar/nav-menu.vue#L3-L5

The sidebar can use some optimization / refactoring love, so be warned that it's not the cleanest code to work in.

**Comment by PurpleEdge2214** [comment]
Thanks for that @rijkvanzanten ! And, I think I'm starting to get my head around what a "Headless CMS" is, I was overlooking the CMS side of it completely and thinking of Directus purely as a REST server designer.

**Comment by benhaynes** [comment]
I'm adding _API Designer_ to our marketing material... 😉

**Comment by PurpleEdge2214** [comment]
You're just messin' with my head now! <g>
