### ISSUE TITLE
Default status, locale and timezone are wrapped in quotes

### ISSUE THREAD

**Issue by WellingGuzman** [directus/app#1054]
# Bug Report

## Steps to Reproduce

1. Go to Users Directory
2. Click on `+` to create a new user
3. Fill names, email, and passwords
4. Click save
5. user's `locale` and `timezone` are sent wrapped in single quotes

```
{
  "status": "'draft'",
  "timezone": "'America/New_York'",
  "locale": "'en-US'",
  "email_notifications": "1",
  "first_name": "John",
  "last_name": "Doe",
  "email": "user@example.com",
  "password": "secret"
}
```

## Expected Behavior

`status`, `timezone` and `locale` should be sent without the quotes.

## Actual Behavior

`status`, `timezone` and `locale` are sent with the quotes.

**Comment by benhaynes** [comment]
It looks like an escaping issue – the slashes also look incorrect:

`'America\/New_York'` -> `America/New_York`

**Comment by WellingGuzman** [comment]
I pretty printed it the payload and it escaped the timezone value. I updated the example with the exact value on the HTTP Request payload (removing the escape).

**Comment by WellingGuzman** [comment]
This also happens with the default of status field.

This revealed a bug on the API: https://github.com/directus/api/issues/538

**Comment by rijkvanzanten** [comment]
It does not?

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/9141017/47935615-5ddad400-deb1-11e8-937d-117822be81fc.png">

**Comment by benhaynes** [comment]
Can we get clarity on this @WellingGuzman?

You're both saying conflicting things...

**Comment by WellingGuzman** [comment]
It's working in the latest version now, it was fixed already, because it happened when the `status`, `locale` and `timezone` field in the app didn't have a default value selected.
