### ISSUE TITLE
one-to-many Dropdown Template

### ISSUE THREAD

**Issue by davutkara** [directus/app#1063]
# Feature Request

There is no dropdown template for one-to-many relation. But many-to-one and many-to-many have dropdown template. Can you add the option?

Thank you.

## What problem does this feature solve?

One-to-many relation, dropdown template

**Comment by benhaynes** [comment]
Hey @davutkara – the reason for this is because a O2M needs to select _many_ items and a dropdown only is capable of selecting _one_. So a dropdown will never work for a O2M. 

Perhaps you meant a different type of input? I'll close this as it's `invalid`... I'll re-open if you can clarify.
