### ISSUE TITLE
Foreign Keys

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1067]
Hi, 
I imported our pre-existing schema in directus. Some table have foreign keys. 
I'd like to display label (from the foreign table) instead of the foreign key present in the actual table I am visualising. 
Is this possible ? if yes, how can I do this ?

Thanks,

**Comment by benhaynes** [comment]
Yes, this is possible. You would setup a relational interface (O2M or M2O). Then you can set which fields are visible instead of just showing the key. We'll try to add more detail to this setup in the Docs.

https://docs.directus.io/app/admin/relationships.html#one-to-many

**Comment by carolin-skiply** [comment]
Thanks.
I got it working or almost.

I have several foreign keys in my table. So when I set one of my foreign keys : it works as you explained. When I edited one of my item : a dropdown is displayed as desired. 
But soon as I defined another one, when I go back to the list of items : both fields are frozen. The dropdown isn't working anymore even for the 1st foreign key (which was working at first).

Any idea ?

**Comment by carolin-skiply** [comment]
Another thing :
Dropdown template is respected in the main form but not in popup :(
![image](https://user-images.githubusercontent.com/34483024/48063728-3728e000-e1c6-11e8-8ba4-3f9a30fa56cd.png)

Am I doing something wrong ?

**Comment by benhaynes** [comment]
Hmm, that's odd... I'll re-open this and we'll take a look asap.

**Comment by benhaynes** [comment]
Hey @carolin-skiply – this is working as expected on our side. We can not reproduce your issue... can you please attach a schema (database file), browser console errors you're seeing, or more clear steps to reproduce your issue?

Thanks!

**Comment by carolin-skiply** [comment]
Hi @benhaynes,

So I have 3 tables A, B and C in A. I have 2 foreign keys : one for B.id and the other one for C.id.

In my case : A = so_boitier, B = so_question and C = so_client.

In the Admin settings > Collections, I set A.question_id as follow :
![image](https://user-images.githubusercontent.com/34483024/48186765-52682c80-e339-11e8-9db1-457ae245bd13.png)
![image](https://user-images.githubusercontent.com/34483024/48186781-5c8a2b00-e339-11e8-9f40-dfd92269c5a5.png)

and A.client_id as follow :
![image](https://user-images.githubusercontent.com/34483024/48186823-788dcc80-e339-11e8-9f56-8cd02f045a2e.png)
![image](https://user-images.githubusercontent.com/34483024/48186852-893e4280-e339-11e8-907e-e8cd874e0e72.png)

When I go back to my list of item and edit one :
I can see the field Question ID but the dropdown isn't working.
![image](https://user-images.githubusercontent.com/34483024/48186916-b8ed4a80-e339-11e8-975f-d3fc51009bbe.png)

For client ID, It's working as desired :
![image](https://user-images.githubusercontent.com/34483024/48186958-e33f0800-e339-11e8-9834-0ef2bb1d47ca.png)

As my setting is similar for both, I don't understand what I am doing wrong :(

Here is the database :
1-directus_fields
![image](https://user-images.githubusercontent.com/34483024/48187030-26997680-e33a-11e8-82aa-475ec15b7e79.png)

2-directus_relations
![image](https://user-images.githubusercontent.com/34483024/48187259-d53db700-e33a-11e8-8633-7ad29c468fb8.png)

Do you need more infos ?

**Comment by carolin-skiply** [comment]
On the created form : no dropdown for question_id and client_id as well

**Comment by benhaynes** [comment]
@carolin-skiply — I think this is because you have the "Listing View Preferences" empty.

I think the best thing to do here is to use the "Dropdown Template" for the modal too.

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/app/issues/1254
