### ISSUE TITLE
Capitalization issues on Create Field

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1069]
`M2o` should be `M2O`
`Mysql Datatype` should be `MySQL DataType`

![screen shot 2018-11-05 at 3 00 28 pm](https://user-images.githubusercontent.com/522079/48023372-9d9cf800-e10b-11e8-9e6c-3878e211b494.png)

**Comment by rijkvanzanten** [comment]
Reinstalling your `node_modules` should do the trick. 

`MySQL` is in the title formatter since about a month ago

https://github.com/directus/format-title/blob/d28c3d066a407ae37e57436a95e522ea672f9d67/src/special-case.js#L20
