### ISSUE TITLE
Simplify M2M Options

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1073]
Do we need the `Visible Columns` option? Can we move `Display Template` to the top?

I'm hoping we can make this work with only Display Template and remove the more confusing Visible Columns.

![relation](https://user-images.githubusercontent.com/522079/48036234-5e839c80-e135-11e8-932a-c4ff9f8a5bc7.png)

**Comment by dsivokhin** [comment]
Hello @benhaynes, whether something is planned with the type of the field "Translation". There is not enough, for example, the parameter "Default language" and the choice of the column in which the name of the language are store


![default](https://user-images.githubusercontent.com/4669992/48050089-f030ef80-e1b1-11e8-99b0-6a91d2137b2e.png)

**Comment by benhaynes** [comment]
Hey @dsivokhin –  the `translations` interface is actually a O2M field type, but I agree with cleaning up all of these interface options.

I am working on some docs for this interface today, but if I remember correctly the **Default Language** comes from the field's default value (not an option). Either way, relational interfaces (including this one) will be the priority this week.

**Comment by benhaynes** [comment]
@dsivokhin – here are some Docs on setting up the translation interface... https://docs.directus.io/app/admin/relationships.html#translations

There are still a few small bugs, but we'll get those resolved asap.

**Comment by dsivokhin** [comment]
@benhaynes Thank you very much, oh, sorry for the offtopic, I mean the default language, that when you open an edited item in the collection, this language in the selector will open automatically, as in Directus 6. 
And I don’t understand when I need to use field type `lang – Specific to translation interfaces, this stores the language key`. There is no information in the relationship translation document for this.

![default](https://user-images.githubusercontent.com/4669992/48120312-de6b4d00-e282-11e8-9a69-683991d54b0a.png)

**Comment by rijkvanzanten** [comment]
The idea here is that there are three tables involved:

```
languages
code
name

articles
id 
featured_image < same in every language 

articles_translations
id
article_id < for what item are these translations
language < saves code from the languages table, so we can search by language and render the nice name
title < actual content being translated
body
```

This language dropdown you showed is supposed to list all the languages in the provided languages table. Does that clear things up a little bit @dsivokhin?

**Comment by benhaynes** [comment]
I think the docks I wrote cover the basic setup, Rijk. but he wants to know how to set which language shows by default in the drop-down.

Also I'm not familiar with where the `lang` field type is used... @WellingGuzman ?

**Comment by dsivokhin** [comment]
Hi @rijkvanzanten, thans, how it works I understand. @benhaynes correctly wrote what I wanted to know.

In directus 6 there was an option in setting up the `Translation interface` - `Default language`. When editing item switch language shows by default.

Without type `lang` it's work, how this type works ?
![default](https://user-images.githubusercontent.com/4669992/48131728-2483d900-e2a2-11e8-96a7-e052b7962338.png)

**Comment by benhaynes** [comment]
The comments here got off topic, but I would still like to simplify the M2M options.

**Comment by theharshin** [comment]
Also it needs more clarification on when and which field will be used.

**Visible Columns**
If there are more that 10 results, a modal with tabular interface is used.

**Display Template**
If results are less than 10, a dropdown will be rendered and display template will be used.

**Comment by rijkvanzanten** [comment]
@theharshin You're right that it needs more clarification, as your explanation isn't correct 😬 

*Visible Columns* is used to render the preview table on the edit view, *Display Template* is used to format the values on the listing views in the popover.

**Comment by benhaynes** [comment]
I agree that it would be great to use the info pane interface for setting up _Visible Fields_.

@theharshin — The dropdown is on the M2O (while this ticket is about M2M). Similar options though!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
