### ISSUE TITLE
Can't save file in interface

### ISSUE THREAD

**Issue by vospascal** [directus/app#1079]
# Bug Report
Got an error: "Call to a member function getType() on null" on the bottom right of the screen

problem is in v7.0.5 not in prev installed version (v7.0.2 or v7.0.3) not sure

## Steps to Reproduce

Collection with a field file cant be saved when a file is picked ... without an selection it got no problem..

in console

`
class: "Error"
code: null
file:"/directus/src/core/Directus/Application/CoreServicesProvider.php"
line: 564
message: "Call to a member function getType() on null"
`

## Expected Behavior
being able to save a file like an image

## Actual Behavior
not beening able to getting an error "Call to a member function getType() on null"

## Technical Details

- Device: Desktop
- OS: MacOS 10.13.6, 
- Browser:  Chrome 70
- Directus App: eg: 7.0.5
- Directus API: eg: 2.0.5

**Comment by vospascal** [comment]
![screen shot 2018-11-06 at 19 27 58](https://user-images.githubusercontent.com/6942179/48085321-301bc500-e1fa-11e8-93f2-c24119e87494.png)

**Comment by benhaynes** [comment]
Hi @vospascal — haven't heard from you in a month or so. I'll close this since we haven't been able to replicate the issue. Let us know if you're still experiencing it.

**Comment by vospascal** [comment]
Sorry been bizzy, not been an issue after fresh install thnx and keep up te Great work!
