### ISSUE TITLE
SSO Endpoint 

### ISSUE THREAD

**Issue by ar-cf** [directus/app#1081]
# Bug Report

The endpoint used for the SSO access token is incorrect - it's set to /auth/access_token when it should be /auth/sso/access_token

(https://github.com/directus/api/issues/146 is the API project issue)

(Incidentally, I'm also being affected by https://github.com/vuejs/vue-router/issues/2125 simultaneously with this, but that's an aside)

## Steps to Reproduce

1. Install and setup directus with SSO auth (I'm using Google)
2. Try to SSO auth
3. POST to /auth/access_token never occurs due to vuejs issue, but if you manually trigger it..
4. ...it 404s.

## Expected Behavior

SSO Login

## Actual Behavior

Sitting at login screen

## Technical Details

- Device: Desktop
- OS: MacOS 10.13.6
- Browser: Firefox 63.0
- Directus App: Latest bundled with directus/directus
- Directus API: Latest bundled with directus/directus
- Install Method: cloned `master` branch of directus/directus

**Comment by rijkvanzanten** [comment]
I've confirmed this to be working using `history` mode in the app's config settings. Unfortunately, due to the VueJS bug you mentioned above, the app doesn't "see" the query string, and thus doesn't know it should try authenticating using SSO....

I'm gonna try implementing a workaround, but I'm afraid we'll have to wait for the vue-router team for a proper solution :(

**Comment by rijkvanzanten** [comment]
Found a solution! Instead of reading the query params using vue-router, we're now reading them using `URLSearchParams` 😄

**Comment by paulbloomfield-uk** [comment]
That's not a very good solution:
1. Cross-browser support?
2. It still leaves the # after the query string for the rest of the session.

This means you can't properly use the Vuejs router with query strings! For others to refer, the workaround is:
```javascript
const query = (new URLSearchParams(window.location.search.substring(1)));
    if (query.has('code') && query.has('state')) {
```
