### ISSUE TITLE
App doesn't Allow for Nested Modals

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1083]
When opening the "create Element" view of a many to many connection, an the target event also having a one to many or many to many connection, clicking on the field to select one lets the view jump to a differend filed.

You can try it yourself in the online demo trough editing a member and at the bottom, adding a favorite and then trying to set the test select box at the bottom.

![grafik](https://user-images.githubusercontent.com/22577866/48091900-58f88600-e20b-11e8-9d58-06b9d382d0e6.png)

**Comment by srjrol** [comment]
I thought this was already an open issue here:  https://github.com/directus/app/issues/283

I think this could be a solution:   https://vuejsexamples.com/vue-modals-with-a-single-component/

**Comment by benhaynes** [comment]
Unique form fields is one problem to solve, but once that's solved this ticket is specifically for allowing multiple modals.

**Comment by ceruulean** [comment]
Hey, would you have any pointers on which file populates the modal? I noticed there's a portal component and it all modal elements are sent to it, but I don't know how 'Create Item' triggers a modal.

**Comment by rijkvanzanten** [comment]
The difficult part of modals is the placement in the DOM. We had some styling conflicts when the modals were rendered inside the component they were being called from. We opted to use [portals](https://github.com/LinusBorg/portal-vue) to make sure the modal is rendered at the very end of the DOM, which [negates any styling / markup conflicts](https://linusborg.github.io/portal-vue/#/guide?id=working-around-position-fixed-issues). However, this comes with a major problem (which we didn't realize would work this way initially): portals can only hold one thing at a time. We've considered adding a fixed amount of other portals so we could use portal no2 when portal no1 was already "taken", but this wouldn't necessarily solve the problem but instead add a new arbitrary limit. Instead, we could re-work the general markup so the original positioning issue doesn't exist anymore, and keep track of what modals are opened to make sure they're stacking in the right order, but that's quite the undertaking to implement (correctly).

**Comment by cesasol** [comment]
Buefy solves the the multiple modals problem very simply, creates a new Vue instance (Check the programatic usage at https://buefy.github.io/documentation/modal) and the [source](https://github.com/buefy/buefy/blob/dev/src/components/modal/index.js#L6) I think this is better than portals for modals, since a modal should just be a modal and don't do anything else than open/close and self destroy after if needed

**Comment by rijkvanzanten** [comment]
We're moving to a design where editing relational items isn't going to be in a modal anymore (we also want to prevent nested modals from a design perspective, as they're not the most user friendly either). This is going to take a little bit to implement though

Ref https://github.com/directus/app/issues/1236
