### ISSUE TITLE
adding avatar when creating a user

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1087]
When creating a new User and then adding an Icon to it results in an error, and the "no cloud" icon being missplaced. Im not sure but it definetly could be because its the Directus example page which has no storage added to it, the image Interface not working 100% yet or a "real" bug when uploading.

![grafik](https://user-images.githubusercontent.com/22577866/48094456-8563d080-e212-11e8-8131-566dca69556d.png)

**Comment by benhaynes** [comment]
Thanks @shealavington – I'm not seeing it either. @Nitwel I assume you didn't edit the CSS... what browser/version/os are you using?

**Comment by Nitwel** [comment]
Nope, no changes what so ever. Firefox latest.

**Comment by Nitwel** [comment]
btw, I have a simular bug with the lock icon at the start of the page:
![grafik](https://user-images.githubusercontent.com/22577866/48103277-b5b96800-e22e-11e8-855f-d8ef6e1839f8.png)

In Firefox again, in Chrome it looks normal.

**Comment by Nitwel** [comment]
I dont know realy why, but it seems that firefox does not render things which are "left/right: 0, pos: absoulute and margin: 0 auto" not centered compared to chrome. A work arround would be to display it as table or inline-table which centers it again, but does not have an affect on chrome displaying.

Btw, dont even bother trying to open directus in edge, its like trying to read a book with white font-color. XD

**Comment by shealavington** [comment]
I can confirm I do get the error on firefox. 

This can be fixed on Firefox by adding the two CSS properties to each element that's not working with L/R/ABSOLUTE/AUTO. (I've not tested to see what this does on chrome, I can have a further look tonight, unless someone else wants to make a PR sooner and check the effects of different browsers.)

Tested on Firefox: Adding the following properties fixes the off-centre issue with: Icon on login & Icon on upload.

`left: 50%;` and `transform: translateX(-50%) translateY(-50%);`

**Comment by benhaynes** [comment]
I like the idea of translate, but one issue it has is making things blurry when the centered item is an odd pixel dimension. Still better than not having things aligned at all though. More importantly, does anyone know my Firefox isn't respecting those position rules? They seem to be very basic.

**Comment by benhaynes** [comment]
`text-align: center` solves this, but I really would like to know why `margin: 0 auto` isn't working in FireFox. If anyone find more elements that are not aligned in FireFox let me know and I'll fix.
