### ISSUE TITLE
Don't allow 'has related entries' filter on non O2M fields

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1089]
When filtering for items, using the "has (no) related entries", the server does not return no results, but an error:
![grafik](https://user-images.githubusercontent.com/22577866/48095293-afb68d80-e214-11e8-9c3d-749e1df53bf5.png)

Directus: example page

**Comment by benhaynes** [comment]
@WellingGuzman this seems like it might be an API issue... thoughts?

**Comment by WellingGuzman** [comment]
Yes, this seems an API error. I am going to take a look at this one.

**Comment by WellingGuzman** [comment]
I will add a better error message on the API side, but the app shouldn't list filter related to `x2m`. For example "has related items" must only works for One to Many.

**Comment by WellingGuzman** [comment]
Either there's a bug with the `all` and `has` filter (https://github.com/directus/api/issues/576).

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/app/pull/1470
