### ISSUE TITLE
Deleting a sorted field causes Server Error

### ISSUE THREAD

**Issue by Xentropics** [directus/app#1090]
# Bug Report

## Steps to Reproduce

1. Sort collection (e.g. Mycollection) by a specific field (e.g. Myfield)
2. Go to Admin settings > Collections & Fields > Mycollection
3. Delete Myfield, confirm
4. Go back to Mycollection (click on it in list on left side)

## Expected Behavior

Show list of collection items, clear sorting

## Actual Behavior

Shows (persistently):

Server Error
Something is wrong with this instance’s server or database.

## Other Context & Screenshots

n/a

## Technical Details

This also happened in version 6. Now I was using the demo of version 7 (stable). Don't think it's a client-side issue (so maybe this is the wrong repo?). Seems that the database query still contains an 'order by' statement for the deleted field.

**Comment by rijkvanzanten** [comment]
> Don't think it's a client-side issue (so maybe this is the wrong repo?)

It _kinda_ is. The app saves the last way you viewed the content to the DB, so everything looks the same like you left it when you reopen the platform. However, that also means that this query will break when the schema changed in a 'breaking' way in the meantime. 

I think the cleanest way of fixing this would be to build a check in the app that goes over the query and removes non existing fields. That way, everything should be 99% how you left it, except for the fact that the sort is back to the default.

**Comment by rijkvanzanten** [comment]
This has been fixed in todays release (v7.0.9)
