### ISSUE TITLE
Sorting by array

### ISSUE THREAD

**Issue by srjrol** [directus/app#1092]
# Bug Report

## Steps to Reproduce

1. Go to collection table view
2. Sort by a field of type array (eg. many-to-many)
4. See error "database or instance is corrupt..." when trying to view table again.  
## Expected Behavior
Do not allow user to sort by fields of the array type.
## Actual Behavior
Unable to view collection items any longer and you must change the sort back to a compatible field through the database directly.

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch]

**Comment by srjrol** [comment]
I think an improved expected behavior could be that the column is sorted by the displayed field in the array if possible.  I'm uncertain if its possible to display field(s) for arrays instead of the item count but this would be a great feature if so.  This would allow collections based on m2m fields to function properly.  As you can see in the image, it is not really possible to determine what the items are with only counts for the fields displayed.

![image](https://user-images.githubusercontent.com/34398302/48145199-f5587200-e277-11e8-8dab-6aed9578093b.png)

**Comment by benhaynes** [comment]
We can only sort by actual content for O2M (in progress: https://github.com/directus/api/issues/539) but we can't sort on M2M values since there are multiple. So we sort on count instead.

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/api/issues/539

**Comment by srjrol** [comment]
> We can only sort by actual content for O2M (in progress: [directus/api#539](https://github.com/directus/api/issues/539)) but we can't sort on M2M values since there are multiple. So we sort on count instead.

Would it be possible to add another option to define which field(s) to use for sorting in the m2m field?  Similar to what is being done for the visible columns or display template?

**Comment by rijkvanzanten** [comment]
@srjrol I'm hoping we can get https://github.com/directus/api/issues/209 to work 😄
