### ISSUE TITLE
Non-blocking info sidebar

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1093]
Currently the Info Sidebar (the right one) opens a blocker over the page content when open. This makes it difficult to see (or interact with) content and activity/comments at the same time. It also marginalizes the Comments/Activity... so they are seen/used less. This is a very useful section of info, and as we improve its features we want to allow users to discover/use/see it more.

Our content forms max out at 620px, plus 200px for the nav sidebar, plus 350px for the info sidebar... is 1170px. At this size and above, the info sidebar could default to open without losing screen real-estate. I propose we remove the smoke and have the info sidebar auto-open (on Item Detail) when the viewport is over 1170px wide.

**Comment by benhaynes** [comment]
Yeah, that's how it worked in version 6 and I'd like to do something similar. But I believe that Rijk had said there was some sizing issue with that in version 7.

Will look into it once all of these bugs are resolved

**Comment by ceruulean** [comment]
Hey, I was able to implement the auto-display infobox and disable the blocker when the viewport is over 1235px (main content is 680px, sidebar is 360px, nav is 180px, padding is 20px, so really 1240px but I wanted some leeway)

I'm not sure what the content pushing would look like, since I have not used v6. Selecting 'Comments' already sorts comments from activity, so I don't see a need to do anything there? Is it just visual flavor when transitioning through the tabs?

**Comment by rijkvanzanten** [comment]
@ceruulean I think @benhaynes means that instead of opening the info sidebar on top of the content, the content gets "pushed" in a little bit to make room for the sidebar. That being said, I'm totally in favor of showing it at all times if your screen real estate allows it. @benhaynes thoughts?

**Comment by rijkvanzanten** [comment]
@benhaynes The main problem we had with the "push" was performance. Transitioning the push is near impossible to do, since there are like 40 reflows and draws happening in the browser in the transition time ~300ms. This will jank up even high-end computers.

**Comment by benhaynes** [comment]
We can "pop" the sidebar in instead of transitioning it (maybe that helps?).

Yeah, all I really care about is showing the sidebar when the real-estate allows for it. Useful features in there that shouldn't be hidden if there's room to show them!

**Comment by benhaynes** [comment]
@ceruulean — did you have a PR for this or just got it working locally?

**Comment by Nitwel** [comment]
Another idea would be, to open it in a seperate tab or window of the browser, in this way, the sidebar is 100% seperated. But personaly, this seems a bit odd, doing it this way.

**Comment by benhaynes** [comment]
Hmm, an interesting idea (similar to browser's dev tool window options), but I think we want to keep it all in one window so it's a true "sidebar".

**Comment by Nitwel** [comment]
### Here a totaly differend way of implementing it:
![grafik](https://user-images.githubusercontent.com/22577866/49238311-6ff05980-f400-11e8-802d-794dbb0a2584.png)

**Comment by benhaynes** [comment]
Ahh, on the _Browse_ page... right. I think this could be a new "Layout"  extension. It seems similar to the accordion Layout I designed.

![directus 7 accordion view](https://user-images.githubusercontent.com/522079/49238555-a7dea900-f3ce-11e8-8f14-3c201214daae.png)

**Comment by Nitwel** [comment]
### Like this:
![tempsnip](https://user-images.githubusercontent.com/22577866/49239218-7384e000-f402-11e8-95ce-922f92570fb5.png)

You could also make it, that you can edit data directly there because:
- quick for making small changes to data
- you can quickly switch between fields
- removes the need to go to another depth

**Comment by ceruulean** [comment]
I submitted a PR for the initial request, but I'm not sure how I feel about it. I think it's nicer to have the infobar active at all times until the user presses the button toggle, otherwise the transition is distracting. Could try to have the initial load the infobar without animations?

**Comment by benhaynes** [comment]
1. I think we can remove animations on initial load, and maybe even when toggling if the "reflow" is too complex.

2. I'm fine showing the info sidebar on the Browse page too (if the browser is wide enough). The problem is what is "wide-enough" for that page? The Detail page form has a max width, so it's easy to calculate, but the Browse page could have many/wide columns so it's harder to tell when there's _enough_ room.

3. We could track a global $store variable for if the info sidebar is open or not. And if the user hasn't explicitly set it then we decide based on viewport width. @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
> We could track a global $store variable

We already have that! `this.$store.state.sidebars.info` is a boolean that reflects the active state of the sidebar

**Comment by rijkvanzanten** [comment]
Ah! Yes that was merged. Thanks again @ceruulean :)
