### ISSUE TITLE
Settings > Collections > Collection: Expects ID field

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1097]
It seems like this page is looking for an `id` column specifically, instead of just any primary key field.

![screen shot 2018-11-06 at 9 40 09 am](https://user-images.githubusercontent.com/522079/48071341-1a7daf80-e1a8-11e8-95fd-b2363f4bbc6b.png)

**Comment by rijkvanzanten** [comment]
Can you be more specific? I don't know what _this page_ is or what steps to take to reproduce this. AFAIK, the app isn't hard coded anywhere to use a field by the name `id`, but it could be because it saved the collection presets, which would make this issue a duplicate

**Comment by benhaynes** [comment]
This page == the one in the issue title: `Settings > Collections > Collection`

1. Create a collection with a primary key **not** named `id` (eg: `idx`)
2. Go to: Settings > Collections > Collection
3. See error

![screen shot 2018-11-07 at 10 45 07 am](https://user-images.githubusercontent.com/522079/48142150-39e50d00-e27a-11e8-9bac-a773af862cb3.png)

**Comment by benhaynes** [comment]
Culprit:

https://github.com/directus/app/blob/master/src/routes/settings/fields.vue#L232
