### ISSUE TITLE
Collection column sizes

### ISSUE THREAD

**Issue by srjrol** [directus/app#1103]
# Bug Report

## Steps to Reproduce

1. Go to 'collection table'
2. Click between column headers to resize a column
3. When resizing the column the width sometimes gets set to an extreme value of -1000+ or 1000+ and I have to change it manually in the database to fix.

4. When the column size gets set to an extreme value you can no longer see the heading.

## Expected Behavior

Column sizes should have a min/max value so they do not get to this point where they can't be fixed through the GUI.

## Actual Behavior
![image](https://user-images.githubusercontent.com/34398302/48225882-be5f8a80-e363-11e8-8307-2fddb8fe1c2b.png)

{"tabular":{"spacing":"compact","widths":{"status":-330,"name":-281,"version":-661,"edition":-1954,"description":485,"type":200}}}

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch]

**Comment by srjrol** [comment]
Here it is produced on the demo website.

![image](https://user-images.githubusercontent.com/34398302/48226195-b6ecb100-e364-11e8-8184-a2918a368b0e.png)

**Comment by rijkvanzanten** [comment]
Hi @srjrol! On what browser / os is this happening?

**Comment by srjrol** [comment]
I am using Windows 10 with latest Google Chrome browser.

**Comment by rijkvanzanten** [comment]
@srjrol The width values are being sent by the browser and subsequently saved by the API. Therefore, if the browser messes up the values, the API saves the wrong sizes 🙂

**Comment by benhaynes** [comment]
I can not reproduce this on Chrome 71 (Mac). As long as I don't let go of the click the columns always stay accurate... and I was really flinging things around. Either this is specific to Windows (other browsers) or it's been fixed.

@rijkvanzanten Do you like the idea of having a min/max column width before sending values to the DB?

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/app/issues/581#issuecomment-453662617

**Comment by benhaynes** [comment]
Actually I'm moving this to #581 and saying this is an enhancement not a bug.
