### ISSUE TITLE
Create items during m2o selection

### ISSUE THREAD

**Issue by srjrol** [directus/app#1104]
# Feature Request

In the modal that appears when selecting a m2o item, it would be great if we could have the same options that are available in the collection table view (sort,create).

## What problem does this feature solve?

Less collections need to be visible if their items can be created through other collections.

**Comment by benhaynes** [comment]
Duplicate of: https://github.com/directus/app/issues/760

Also, I added it to the 7.0.15 board since this should be pretty quick and is important for the reason you stated: *some Collections don't need to be in the main nav if they are only accessed through relationships.*
