### ISSUE TITLE
Add ability to upload .gif as logo 

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1105]
So it uses that animation as loading state as well

**Comment by shealavington** [comment]
https://jsfiddle.net/Shealavington/wqojp4ec/

Fiddle **concept** using Javascript, provide a GIF, it will take the first frame, use that for the "still" then swap it for the GIF when it needs animating.

Or the simple approach is to have two image uploads, a "Still" and an "Animated" which could swap between the two at the different states?..

**Comment by benhaynes** [comment]
Ohh, I like this. Do we think that many users will have a custom animated gif to use? I could see this being a big filesize hit too if they don't know how to optimize them.

Perhaps it's better to keep the custom logo as a static file (ideally SVG) and have an option for an "unbranded spinner" that fades-in over the custom logo during activity?

**Comment by benhaynes** [comment]
I don't think this passes our [80/20 rule](https://docs.directus.io/getting-started/contributing.html#_80-20-rule). I'll close this and we can keep discussing custom logos.

Ref:
https://github.com/directus/api/issues/624
https://github.com/directus/app/issues/777
