### ISSUE TITLE
List View Preferences

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1108]
# Bug Report
In enter the following preferences :
`{
    "viewType": "tabular",
    "viewQuery": {
        "fields": [
            "id",
            "group_name"
        ]
    },
    "filters": [
        {
            "field": "A.client_id",
            "operator": "equals",
            "value": "B.client_id"
        }
    ]
}`

## Steps to Reproduce

1. Go to 'Settings > Collections & Fields > Collection A'
2. Click on the foreign key M2O that you want to add preferences (in my case A.group_id)
3. Go to 'Options' tab and enter the preferences.
4. Go to the items list of Collection A and select one
5. Nothing is displayed in the popup for group_id and the following error appears in the console : 
`TypeError: e.fields.split is not a function`
`TypeError: this.viewQuery.fields.split is not a function`

## Expected Behavior
Showing a list following the preferences (in my case : B.id and B.group_name, filter on A.client_id==B.client_id)

## Actual Behavior
popup empty

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/34483024/48272003-ec190200-e43d-11e8-9ff7-3a79b7ddb30d.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus App: 7.0.0

**Comment by rijkvanzanten** [comment]
Hey @carolin-skiply! Can you maybe share a database dump of your exact setup? It's a bit hard to debug without being able to reproduce your exact setup

**Comment by rijkvanzanten** [comment]
Also, could you update to the latest version in order to make sure this hasn't been fixed in the meantime? 😄

**Comment by dougludlow** [comment]
I'm seeing this as well.

**Comment by carolin-skiply** [comment]
@rijkvanzanten I pull the last version of directus (today). I still have the issue.

Here is my schema :
Table A (or Table Device) has the following fields : id, client_id, device_name, group_id (=B.id)
Table B (or Table Group) has the following fields : id, client_id, group_name
Table Client has the following fields : id, name, other infos.

Any idea ?

**Comment by MartinN3** [comment]
Guys this one sux

**Comment by benhaynes** [comment]
I've bumped this up to a `high priority` in our bug triage board so we'll be working on this one next (tomorrow).
