### ISSUE TITLE
Display m2o field in m2m selection

### ISSUE THREAD

**Issue by srjrol** [directus/app#1109]
# Bug Report

## Steps to Reproduce

1. Create a collection with a m2m field and another collection with m2o field(s).
2. In the related collection set the the options to display columns containing a m2o field(s).
3. Create an item using the m2m field and observe that you cannot see the m2o fields (blank) in the columns for the table view when selecting items.
4. After selecting an item, the IDs used to related the collections are displayed instead of the actual field value or nothing at all.

## Expected Behavior

Display selected m2m field values in the columns.

## Actual Behavior
![m2o-listed-for-m2m](https://user-images.githubusercontent.com/34398302/48278402-fe317b00-e412-11e8-990e-6bc498009cd3.gif)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch]

**Comment by rijkvanzanten** [comment]
I'm thinking this should be thought of from a higher perspective. It should ideally use the interfaces that were used in the original fields to display the values. This would mean that the m2o fields will display their values based on the settings configured and that other fields will be displayed properly as well (eg color as a swatch etc)
