### ISSUE TITLE
Multi-Select Field error when saving (This value should be of type array)

### ISSUE THREAD

**Issue by srjrol** [directus/app#1112]
# Bug Report

## Steps to Reproduce

1. Create a new collection called 'test'.  Create a new Multi-Select field called 'Default Multi Select'.
2. Do not edit any advanced schema options.
3. Use the default example for a multi-select.

{
    "value1": "Option 1",
    "value2": "Option 2",
    "value3": "Option 3",
    "value4": "Option 4",
    "value5": "Option 5"
}

4. Save and try to save the multi-select field in the new collection with either 1 or multiple items and you receive an error 'default_multi_select: This value should be of type array.'

## Expected Behavior

Multi-Select field should allow single or multiple selections to be saved.

## Actual Behavior

![error](https://user-images.githubusercontent.com/34398302/48294248-b75e7800-e448-11e8-8b92-8853040891b5.gif)

Error message: This value should be of type array

## Other Context & Screenshots

The database field type shos array so I don't understand the reason for this error.

**Comment by srjrol** [comment]
possibly related? https://github.com/directus/app/issues/990

**Comment by rijkvanzanten** [comment]
@srjrol I think it's the exact same problem just in a different interface 🤦🏻‍♂️
