### ISSUE TITLE
Google SSO Fatal Error

### ISSUE THREAD

**Issue by srjrol** [directus/app#1113]
# Bug Report

## Steps to Reproduce

1. Configured Google account (same email as Directus administrator) project with OAuth credentials and updated api.config with 'client_secret', 'client_id', and 'hosted_domain'.
2. I see the Google icon appear for SSO login and I click it. 
3. Login with my account (same email as Directus administrator).

## Expected Behavior

Login to Directus with matching Google email account.

## Actual Behavior
I am redirected to this error at the URL after authenticating with Google.

`http://DOMAIN.COM/public/_/auth/sso/google/callback?state=f90e77afcdcf9817ea0b82cad1e70201&code=4%2FkgCRFtn9XKHV5Xhu9MuxfrXmE6nQTkRjQiZaeehfpvpVOvhJmdXRk6IjtaCBqTNyBhBvR7nOhepW1RshRZ3eB-8&scope=openid+email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.me+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email#
`
> Warning: include(/home/user/public_html/directus/vendor/composer/../monolog/monolog/src/Monolog/ResettableInterface.php): failed to open stream: No such file or directory in /home/user/public_html/directus/vendor/composer/ClassLoader.php on line 444
> 
> Warning: include(/home/user/public_html/directus/vendor/composer/../monolog/monolog/src/Monolog/ResettableInterface.php): failed to open stream: No such file or directory in /home/user/public_html/directus/vendor/composer/ClassLoader.php on line 444
> 
> Warning: include(): Failed opening '/home/x/public_html/directus/vendor/composer/../monolog/monolog/src/Monolog/ResettableInterface.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/user/public_html/directus/vendor/composer/ClassLoader.php on line 444
> 
> Fatal error: Interface 'Monolog\ResettableInterface' not found in /home/user/public_html/directus/vendor/monolog/monolog/src/Monolog/Logger.php on line 28
> 

## Other Context & Screenshots

https://docs.directus.io/api/contributor/sso-login-flow.html

I think this error is occuring around step 4/5.

![image](https://user-images.githubusercontent.com/34398302/48314590-365ec800-e591-11e8-8050-dae72431b6f7.png)
![image](https://user-images.githubusercontent.com/34398302/48314635-c0a72c00-e591-11e8-913c-9f91c632ee90.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus 7.0.6

- Install Method: [eg: cloned `master` branch]

**Comment by rijkvanzanten** [comment]
Hey @srjrol! The error message reminds me of https://github.com/directus/directus/issues/2242 which has been fixed in 7.0.7. Can you try if that solved this for you as well?

**Comment by rijkvanzanten** [comment]
Your setup looks right and the bug you mentioned has been fixed in 7.0.7. I've just tried Google SSO myself and it seems to be working correctly, so I'm considering this fixed 😄
