### ISSUE TITLE
Logo field interface appears as text instead of file

### ISSUE THREAD

**Issue by srjrol** [directus/app#1114]
# Bug Report

## Steps to Reproduce

1. Go to Global Settings > Logo field.
2. Observe that it is a text field instead of a file interface.

## Expected Behavior

Add supported image type to logo file interface field.

## Actual Behavior

The text field appears.

## Other Context & Screenshots

I tried adding a same sized png image to the file library and pointed the logo field to its ID but the image still would not load to replace the logo.  It was replaced with a broken image link.

![image](https://user-images.githubusercontent.com/34398302/48485823-7dda9380-e7df-11e8-9277-32dc63dc74c2.png)

![image](https://user-images.githubusercontent.com/34398302/48485829-80d58400-e7df-11e8-9d30-2fe4c47079eb.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: latest Chrome
- Directus : 7.0.5/6

**Comment by srjrol** [comment]
It would also be great if you can add a description to this field which mentions supported file type(s) and sizes.

**Comment by rijkvanzanten** [comment]
@srjrol This page is supposed to use the "regular" interfaces. This would show the file interface instead, which in turn also shows that information 😄

**Comment by srjrol** [comment]
If I understand you correctly, you are saying it will appear like this when corrected:

![image](https://user-images.githubusercontent.com/34398302/48494147-da937980-e7f2-11e8-90b9-beb457a5131e.png)

This is great since it does already show the size limit.  I think a helpful addition would be to add a Note to the field which explains the supported file type and size, like so:

![image](https://user-images.githubusercontent.com/34398302/48494241-13cbe980-e7f3-11e8-96b9-19df0202cb56.png)
