### ISSUE TITLE
Installing using docker-compose goes straight to login dialog

### ISSUE THREAD

**Issue by mohc** [directus/app#1117]
# Bug Report

## Steps to Reproduce

1. clone the directus repository
2. docker-compose build
3. docker-compose up
4. Navigate to localhost:8080/admin

## Expected Behavior
Installation dialog displayed

## Actual Behavior
Login dialog displayed

## Resolution
1. docker exec -it api-php-apache /bin/bash
2. chown -R www-data:www-data .
3. Navigate to localhost:8080/admin

The installation dialog is now shown

Also the user guide should give instructions regarding default installation parameters:
eg. 
- database name: directus
- database user: root
- database password: root
- database host: api-mysql

## Technical Details

- Device: docker
- OS: unbuntu 18.04
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.6]
- Install Method: cloned master branch then docker-compose

**Comment by rijkvanzanten** [comment]
Hey @mohc! Thanks for pointing this out 😄 

@WoLfulus is steering an effort to create a "proper" directus docker setup over on https://github.com/directus/docker. The docker-compose inside this repo will be replaced by that, as soon as it's up and running.

**Comment by rijkvanzanten** [comment]
We removed the docker files from the main repos in favor of the new 
https://github.com/directus/docker repo. Please try that instead.
