### ISSUE TITLE
Unable to sort by "products" field because it is an alias.

### ISSUE THREAD

**Issue by jajacobs** [directus/app#1119]
# Bug Report

## Steps to Reproduce

1. Go to collection
2. Click to sort columns

## Expected Behavior
Column sorted

## Actual Behavior
Error screen

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/8701133/48623157-47d41580-e97f-11e8-8813-87e39f6e2556.png)

![image](https://user-images.githubusercontent.com/8701133/48623084-18250d80-e97f-11e8-9675-2887f2a555f5.png)

## Technical Details

- Device: Desktop
- OS: Windows 10.1803
- Browser: Chrome 70.0.3538.102 (Official Build) (64-bit)
- Directus App: 7.0.7
- Directus API: 2.0.7
- Install Method: cloned `build` branch

**Comment by rijkvanzanten** [comment]
Ref #1092

**Comment by rijkvanzanten** [comment]
We disabled the ability to sort on a relational value in 7.0.8
