### ISSUE TITLE
Hide default value field on field setup for O2M / translation

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1124]
They're alias types which means that there are no associated mysql columns. The default value is saved in the mysql column => default value is ignored.

**Comment by benhaynes** [comment]
Seems like an easy conditional... maybe we could add this in for this week @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
It's one of _those_ things. We are going to refactor the field setup modal flow quite heavily (eg split it up in separate files to clean up the individual steps) at which point this is very easy to "just" throw in there as well.
