### ISSUE TITLE
Anyone else than the initial admin cannot log in

### ISSUE THREAD

**Issue by lasiru** [directus/app#1125]
# Bug Report

<details>
<summary>Stack trace:</summary>
<pre>
#0 /home/hawasaadmmin/public_html/upload/src/core/Directus/Authentication/Provider.php(115): Directus\Authentication\Provider->findUserWithCredentials('upload@test.com', 'upload123')
#1 /home/hawasaadmmin/public_html/upload/src/core/Directus/Services/AuthService.php(47): Directus\Authentication\Provider->login(Array)
#2 /home/hawasaadmmin/public_html/upload/src/endpoints/Auth.php(49): Directus\Services\AuthService->loginWithCredentials('upload@test.com', 'upload123')
#3 [internal function]: Directus\Api\Routes\Auth->authenticate(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#4 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#5 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#6 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#7 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#8 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\TableGatewayMiddleware), Array)
#9 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#10 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#11 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#12 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#13 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#14 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#15 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#16 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\IpRateLimitMiddleware), Array)
#17 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#18 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#19 /home/hawasaadmmin/public_html/upload/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#20 [internal function]: RKA\Middleware\IpAddress->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#21 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(RKA\Middleware\IpAddress), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#23 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#24 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#25 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#26 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\CorsMiddleware), Array)
#27 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#28 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#29 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#30 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#31 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\ResponseCacheMiddleware), Array)
#32 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#33 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#34 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#35 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#36 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#37 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Application.php(161): Slim\App->run(false)
#38 /home/hawasaadmmin/public_html/upload/public/index.php(5): Directus\Application\Application->run()
#39 {main} [] []
</pre>
</details>

## Steps to Reproduce

1. Go to login screen
2. Enter credentials
3. Click log in

## Expected Behavior
Login to directus app 

## Actual Behavior
Gives and error username or password is wrong

## Other Context & Screenshots
I'm new to this so please be kind enough to guide me through the technical details if possible.

![annotation 2018-11-17 140828](https://user-images.githubusercontent.com/45118389/48659116-46374a00-ea72-11e8-9c92-540d22f5080e.jpg)

**Comment by lasiru** [comment]
Okay I realized that you can't give administrator privileges to two people.

**Comment by rijkvanzanten** [comment]
@lasiru Could you maybe share a SQL dump of your database? Either here if there's no public data in there or [on Slack](https://slack.getdirectus.com) if you want to keep it private.

I just tried this on https://directus.app, and everything seems to be working as expected..

I'd love to figure out what's causing this, as it sounds like a big problem!

**Comment by verbman** [comment]
I've just seen this issue and I also had this behavior which was what lead me to filing this issue here:
https://github.com/directus/api/issues/593

Interestingly I'm back here because I've updated to the latest release, I've reversed the edit I made (detailed in the above issue) and now I can't log in as administrator.
