### ISSUE TITLE
Date field default to current date

### ISSUE THREAD

**Issue by dur41d** [directus/app#1127]
# Feature Request

I would like to be able to default the date field to current date `now()` so that I can save time when I'm editing the field.

## What problem does this feature solve?

I have a blog where article created date is mostly the current date and I want to default it to the current date.

## How do you think this should be implemented?

Not sure. Maybe in the default template` {{now}}`

## Would you be willing to work on this?

Yes. (some guidance is welcome)

**Comment by benhaynes** [comment]
Hey @dur41d – you can use the `datetime_updated` interface to accomplish this!

https://docs.directus.io/app/admin/permissions.html#accountability

**Comment by benhaynes** [comment]
Also, we have this ticket: https://github.com/directus/api/issues/313

**Comment by dur41d** [comment]
The accountability is a different thing because it's the created date. What I want is that when the user creates a new item the date field shows the current date but the user can change it before hitting save.

The ticket is about the api and it's different too.

**Comment by rijkvanzanten** [comment]
In order to achieve this, wed have to stage the value in the created hook of the input.vue component of the date time interface. This should only be done if the option is activated , so we need to add the option in meta.json as well

**Comment by c-ciobanu** [comment]
These are my ideas on how to solve this but I'm not sure.
Is [this](https://github.com/directus/api/blob/master/extensions/core/interfaces/datetime/input.vue) the file where the created hook should be placed or one in the app repo?
I should add a "defaultValue" parameter inside options in [meta.json](https://github.com/directus/api/blob/master/extensions/core/interfaces/datetime/meta.json).
The check if this option is activated where it's done, api or app repo?

**Comment by rijkvanzanten** [comment]
> Is this the file where the created hook should be placed

Yep! That's it. In the `created()` method of that component you'll fire `this.$emit("input")` to set the value on load. That will allow the user to either hit save immediately using that value to save, or to edit it if needed.

**Comment by rijkvanzanten** [comment]
Setting the default value is already possible using the regular app as of right now, however, it doesn't provide this specific use case (as the current date is not a static value). We should add a "default to current datetime" option to that meta.json

**Comment by rijkvanzanten** [comment]
After it's added to the meta.json file, you can check `this.options.whateverNameYouChooseInThePreviousStep` in the created() method in order to see if you should set the value or not

**Comment by c-ciobanu** [comment]
Thank you @rijkvanzanten! When i'll finish to setup the api repo I'll make a pr.

**Comment by theharshin** [comment]
@rijkvanzanten Do we need any more enhancements in this or should consider it as closed? 🤔

**Comment by rijkvanzanten** [comment]
Ah good catch @theharshin, this was indeed closed by #647.
