### ISSUE TITLE
Mutliple file interface

### ISSUE THREAD

**Issue by dur41d** [directus/app#1128]
# Feature Request

I would like to a multiple file upload interface.

## What problem does this feature solve?

I have a blog that has a gallery and I would like to enable the users to upload multiple pictures.

## How do you think this should be implemented?

Similar to v6 multiple file interface.

## Would you be willing to work on this?

Sure.

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/app/issues/956
