### ISSUE TITLE
Cannot upload files larger than 4mb

### ISSUE THREAD

**Issue by lasiru** [directus/app#1130]
# Bug Report
[2018-11-18 05:00:05] api[_].ERROR: Directus\Validator\Exception\InvalidRequestException: file: This value should not be blank. in /home/hawasaadmmin/public_html/upload/src/core/Directus/Services/AbstractService.php:188
Stack trace:
#0 /home/hawasaadmmin/public_html/upload/src/core/Directus/Services/AbstractService.php(120): Directus\Services\AbstractService->throwErrorIfAny(Array)
#1 /home/hawasaadmmin/public_html/upload/src/core/Directus/Services/AbstractService.php(373): Directus\Services\AbstractService->validate(Array, Array)
#2 /home/hawasaadmmin/public_html/upload/src/core/Directus/Services/ItemsService.php(26): Directus\Services\AbstractService->validatePayload('daily_scope', NULL, Array, Array)
#3 /home/hawasaadmmin/public_html/upload/src/endpoints/Items.php(69): Directus\Services\ItemsService->createItem('daily_scope', Array, Array)
#4 [internal function]: Directus\Api\Routes\Items->create(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#5 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#6 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#7 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#8 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#9 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\UserRateLimitMiddleware), Array)
#10 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#11 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#12 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(80): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#13 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#14 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\AuthenticationMiddleware), Array)
#15 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#16 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#17 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#18 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#19 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\TableGatewayMiddleware), Array)
#20 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#21 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#22 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#23 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#24 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#25 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#26 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#27 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\IpRateLimitMiddleware), Array)
#28 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#29 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#30 /home/hawasaadmmin/public_html/upload/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#31 [internal function]: RKA\Middleware\IpAddress->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#32 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(RKA\Middleware\IpAddress), Array)
#33 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#34 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#35 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#36 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#37 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\CorsMiddleware), Array)
#38 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#39 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#40 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#41 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#42 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\ResponseCacheMiddleware), Array)
#43 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#44 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#45 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#46 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#47 /home/hawasaadmmin/public_html/upload/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#48 /home/hawasaadmmin/public_html/upload/src/core/Directus/Application/Application.php(161): Slim\App->run(false)
#49 /home/hawasaadmmin/public_html/upload/public/index.php(5): Directus\Application\Application->run()
#50 {main} [] []
## Steps to Reproduce

1. Go to Collections
2. Select Collection
3. Add Entry
4. Upload File Larger than 4mb

## Expected Behavior
Upload should complete and be able to add the entry

## Actual Behavior
Error: file: This value should not be blank

## Other Context & Screenshots

![annotation 2018-11-18 152959](https://user-images.githubusercontent.com/45118389/48670994-99c79780-eb47-11e8-8f77-399cbbd7885e.jpg)
![annotation 2018-11-18 153050](https://user-images.githubusercontent.com/45118389/48670995-9cc28800-eb47-11e8-85d0-7caca9175489.jpg)

I tried this with jpgs as well
my php settings are set at 75mb north.
please feel free to point out something that I might be doing wrong.

Thank you.

## Technical Details

- Device: [Desktop]
- OS: [ Cent OS7, Windows 10.1803]
- Browser: [Chrome 70.0.3538.102]
- Directus App: [eg: 7.0.8]
- Directus API: [eg: 2.0.0]
- Install Method: [cloned directus suit]

**Comment by honzabilek4** [comment]
`php.ini` is always a first place to go while having problems with file upload limit. Moreover, processing large jpg files usually requires a way larger amount of memory available on server.

**Comment by cesasol** [comment]
Could be a nicer way to tell the user that the file is to large? A "This file is to large" message?

**Comment by benhaynes** [comment]
I agree. Don't we get the max file size from the API, @rijkvanzanten ? We can check file size before the upload even starts I think, and throw a friendly error telling them they need to update their server settings.

**Comment by rijkvanzanten** [comment]
Yeah absolutely. The app know the max upload size so shouldn't even attempt uploading a file that's larger than that size

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/app/issues/1201
