### ISSUE TITLE
Global Settings: Color select not woring

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1132]
As seen on the picture, selecting a color and the saving is not possible and results in a crash.

![grafik](https://user-images.githubusercontent.com/22577866/48676688-8548c680-eb6a-11e8-8d49-3b6b32cbb209.png)

## Error:

<details>
  <summary>Full error</summary>
<pre>
[2018-11-18 13:37:46] api[_].ERROR: Directus\Validator\Exception\InvalidRequestException: scope: This value should not be blank. in /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Services/AbstractService.php:188
Stack trace:
#0 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Services/AbstractService.php(120): Directus\Services\AbstractService->throwErrorIfAny(Array)
#1 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Services/AbstractService.php(373): Directus\Services\AbstractService->validate(Array, Array)
#2 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Services/ItemsService.php(26): Directus\Services\AbstractService->validatePayload('directus_settin...', NULL, Array, Array)
#3 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Services/SettingsService.php(30): Directus\Services\ItemsService->createItem('directus_settin...', Array, Array)
#4 /data/web/1/000/114/698/451251/htdocs/api/src/endpoints/Settings.php(46): Directus\Services\SettingsService->create(Array, Array)
#5 [internal function]: Directus\Api\Routes\Settings->create(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#6 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#7 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#8 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#9 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#10 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\UserRateLimitMiddleware), Array)
#11 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#12 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#13 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(80): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#14 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#15 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\AuthenticationMiddleware), Array)
#16 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#17 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#18 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#19 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#20 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\TableGatewayMiddleware), Array)
#21 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#22 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#23 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#24 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#25 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#26 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#27 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#28 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\IpRateLimitMiddleware), Array)
#29 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#30 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#31 /data/web/1/000/114/698/451251/htdocs/api/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#32 [internal function]: RKA\Middleware\IpAddress->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#33 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(RKA\Middleware\IpAddress), Array)
#34 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#35 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#36 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#37 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#38 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\CorsMiddleware), Array)
#39 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#40 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#41 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#42 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#43 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\ResponseCacheMiddleware), Array)
#44 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#45 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#46 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#47 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#48 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#49 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Application.php(161): Slim\App->run(false)
#50 /data/web/1/000/114/698/451251/htdocs/api/public/index.php(5): Directus\Application\Application->run()
#51 {main} [] []
</pre>
</details>

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/api/issues/594

**Comment by benhaynes** [comment]
This will be fixed as soon as directus/api#594 is completed by @WellingGuzman. I'll close this as a duplicate so it's not lost in the shuffle.
