### ISSUE TITLE
File Upload not showing / working

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1133]
In the Global and User Settings, the file upload field is not showing.

![grafik](https://user-images.githubusercontent.com/22577866/48676754-6ac31d00-eb6b-11e8-8041-7f0430369c0a.png)

Directus 2.0.8

**Comment by benhaynes** [comment]
Thanks @Nitwel — we'll take a look in the next few days!

**Comment by rijkvanzanten** [comment]
@Nitwel could you try running the [update endpoint](
https://docs.directus.io/api/reference.html#update)? If I’m not mistaken, I’ve fixed this in the database seeder recently

**Comment by Nitwel** [comment]
@rijkvanzanten now nothing works anymore as said in #1134 :/

**Comment by rijkvanzanten** [comment]
The original issue (image field) has been fixed. We'll keep #1134 open to discuss the other issue
