### ISSUE TITLE
Cloudinary Field Type

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/app#1138]
# Feature Request
Adding a field type to upload images / videos to a - in the settings configured - cloundinary account, saving the link in the database field.
Maybe fetching a preview image to display alongside the data.

## What problem does this feature solve?
Loading the images directly from the directus storage often requires further processing to be used on a website (cropping, etc.). I know there is this resize tool, but cloudinary specializes in this.
This would allow to use all the great cloudinary features for the consumers of the directus data.

## How do you think this should be implemented?
Cloudinary offers a good api for this https://cloudinary.com/documentation/image_upload_api_reference
I think this would require a new field type for directus, but don't know if just this is sufficient.

Or maybe this needs to be a storage adapter?

## Would you be willing to work on this?
I would be willing to help but doubt to be able to do this on my own.

**Comment by rijkvanzanten** [comment]
Great idea 😄 

@WellingGuzman Is this something we can turn into a storage adapter?

**Comment by honzabilek4** [comment]
Hey, 
I was already planning to write the storage adapter on our own, since we're going to need this feature in the near future. Unfortunately I'm being pretty busy to do it right now, it is on our todo list. 😉

**Comment by honzabilek4** [comment]
First I was thinking about an upload interface for images/videos, however Cloudinary supports all types of files to be uploaded, so it would also be possible to transform it into a storage adapter. This would allow to manage them directly from Directus. But the question is, do users want to upload all data there, when it's a service specialized for handling images? Maybe a simple upload interface would do, users can manage them in their cloudinary account then.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
