### ISSUE TITLE
directus 7 installer

### ISSUE THREAD

**Issue by gnh1201** [directus/app#1144]
Hello. I am directus 6 user.
I tried installing Directus 7 on my new server, but I could not find any installers.
I tried the installation method (https://docs.directus.io/install.html) but I did not see the installer.
Only the login page was visible.

Can I get a good guide?

**Comment by gnh1201** [comment]
I am confused with the installation guide for directus 7. '/ admin' did not help.
I had to choose directus-6-legacy. I wish there was a kind guide.

**Comment by Nitwel** [comment]
You can find the lastest versions of the app & api here:
app: https://github.com/directus/app/releases
api: https://github.com/directus/api/releases

#### Steps to success:
1. unzip the files
2. edit both configs under "api/config/api_example.php" & "app/config_example.js"
3. remove "_example" from both files
4. you shuld be good to go

More detail of the api configuration here:
https://docs.directus.io/api/admin/configure-manually.html

**Comment by gnh1201** [comment]
> You can find the lastest versions of the app & api here:
> app: https://github.com/directus/app/releases
> api: https://github.com/directus/api/releases
> #### Steps to success:
> 
>     1. unzip the files
> 
>     2. edit both configs under "api/config/api_example.php" & "app/config_example.js"
> 
>     3. remove "_example" from both files
> 
>     4. update the tables in the database by importing "api/src/schema.sql"
> 
>     5. you shuld be good to go
> 
> 
> More detail of the api configuration here:
> https://docs.directus.io/api/admin/configure-manually.html

Great! It works!
