### ISSUE TITLE
Error on hard reload (Server Error with multiple API configs)

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1145]
# Bug Report
yes (production env)
## Steps to Reproduce

Having 2 api projects:
- `api/configs/config.php` (default)
- `api/configs/config.second.php`

## Reproduce

1. Go to `/admin` and Login to Admin UI (hard reload works)
2. Change  from default to the second API after Login ( ... Logout + new Login)
3. hit CMD + Shift + R (Chrome) to hard reload after login (hard reload don't works)

Have a look to the dev console networks, is it correct to reload from https://api.domain.ch/_/ instead of https://api.domain.ch/second/ ? Or do i am missing sth in my directus-app? some project specific settings?

## Expected Behavior
no error, hard reload Admin UI of not default API as well
## Actual Behavior

Server Error ... see below, I assume its a Vuex Store issue and the auth_token get lost or maybe the api base project url is not correctly assigned to the req.

## Other Context & Screenshots
```
Failed to load resource: the server responded with a status of 401 ()
hydrate.js:56 Objectcode: 101message: "Invalid Authentication Token"__ob__: Ae {value: {…}, dep: le, vmCount: 0}get code: ƒ ()set code: ƒ (t)get message: ƒ ()set message: ƒ (t)__proto__: Object
Promise.all.then.then.then.then.then.catch.e @ hydrate.js:56
vue-router.esm.js:1897 TypeError: Cannot read property 'fields' of undefined
    at md (item.vue:188)
    at beforeRouteEnter (item.vue:837)
    at vue-router.esm.js:2095
    at p (vue-router.esm.js:1935)
    at r (vue-router.esm.js:1709)
    at Me (vue-router.esm.js:1717)
    at vue-router.esm.js:1971
    at r (vue-router.esm.js:1706)
    at vue-router.esm.js:1710
    at vue-router.esm.js:1956
a @ vue-router.esm.js:1897
```

Network Console:

![image](https://user-images.githubusercontent.com/15183757/49000396-b53f2d80-f159-11e8-92c3-c20c8b1ddec6.png)

Maybe a way that could help: https://github.com/potato4d/nuxt-client-init-module

## Technical Details

- Device: [Desktop]
- OS: [MacOS Mojave]
- Browser: [Chrome new]
- Directus App: [7.0.9]
- Directus API: [2.0.9]
- Install Method: [cloned `master` branch]

**Comment by honzabilek4** [comment]
Hi @dev7ch,
what PHP server are you using and what is your configuration?

**Comment by dev7ch** [comment]
Hoi @honzabilek4 

on prod:

```sh
PHP 7.1.24 (cli) (built: Nov  9 2018 03:50:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.4, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.1.24, Copyright (c) 1999-2018, by Zend Technologies
```

locally:

```
PHP 7.1.19 (cli) (built: Aug 17 2018 18:03:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by dev7ch** [comment]
Apache + Mysql

**Comment by dev7ch** [comment]
@honzabilek4 yes, tried it but didn`t solved.

it doesn^t seem to work for the second api project, i just copied the `api.php` and renamed it `api.second.php`

https://github.com/directus/api/blob/master/config/api_sample.php

**Comment by honzabilek4** [comment]
I think this is too abstract to solve. 
Can you share more information with us? (ie. the exact api.php configurations, .htaccess file, response/request headers )
I'll try to help.
You can also reach me on slack https://rangerstudio.slack.com as @Jan Bílek

**Comment by benhaynes** [comment]
@rijkvanzanten — this might be related (or the same as) the multiple projects issue I was having.

**Comment by dev7ch** [comment]
@honzabilek4 thanks you very much, i am going to have a closer look soon and might reach you out at the channel.

**Comment by dev7ch** [comment]
More Information:

https://api.dev7.ch and https://app.dev7.ch are the prod test domains.

1 i  as much as default as possible (your general configs, .htaccess, etc)
2 pong and the sending of ping works well (but is only communication wirh the default api to, correct?)
3 i have the same adminuser for both data bases (maybe conflict here?)
4 For me it looks like the value for project id from the vuex store is getting lost or overwritten

**Comment by dev7ch** [comment]
i assume here is the rabbit ;)
https://github.com/directus/app/blob/master/src/store/modules/auth/index.js#L8

**Comment by honzabilek4** [comment]
Hey @dev7ch , 
I was able to reproduce your issue! 
On page reload, the env variable uses the underscore by default and thus it queries the default environment while already being logged to a different one.

**Comment by honzabilek4** [comment]
The solution is to read the environment name from already stored JWT token payload and commit it to the store before any other requests are made. I believe that the right place to do it is here :
https://github.com/directus/app/blob/master/src/api.js#L11

**Comment by honzabilek4** [comment]
Check out my pull request. This should resolve the problem.

**Comment by dev7ch** [comment]
@honzabilek4 thx for update, i played a bit as well an realized the following:
![image](https://user-images.githubusercontent.com/15183757/49079722-ad5ab880-f241-11e8-8dba-835e6e7554e0.png)

- i seems the project id is stored correctly in payloads
- the token is pulled (maybe wrongly) from the `api/configs/api.second.php`

**Comment by dev7ch** [comment]
so the project id should be correct.

but do I need to fill this token in `api.second.php` ?

**Comment by honzabilek4** [comment]
Nope, the problem is that the SDK didn't have te correct configuration, so it was requesting incorrect urls. Again, check out my pull request (`environment-fix` branch) which resolves the issue.

**Comment by dev7ch** [comment]
thx, i am on it

**Comment by dev7ch** [comment]
@honzabilek4 i tested your branch / PR, it`s working 👍 
Thank you for fixing so fast!!!

**Comment by jan** [comment]
@honzabilek4 that's not how you think `@` mentions work on GitHub. ;-)

**Comment by dev7ch** [comment]
sth else funny while review this thread `Promise.all.then.then.then.then.then.catch.e @ hydrate.js:56` never saw a line like this before ;) ... yes mentions, maybe my usage it`s related to my mail notification settings ..

**Comment by rijkvanzanten** [comment]
@dev7ch that does look intimidating 😂 

The code itself is more readable IMO if you chain a bunch of .thens instead of doing everything in one 🤔

**Comment by dev7ch** [comment]
i think in general it smart and let you create clean and clear structured code, but sometime a new proisise/resovle nested inside for side task might be a good focus the main tasks ... just thoughts;)
