### ISSUE TITLE
Translated Collections can't get translated images

### ISSUE THREAD

**Issue by alvarocabanas** [directus/app#1148]
# Bug Report
When creating a collection with translations and adding images to the translations collection, I found that directus, when editing an item, calls the endpoint like this : /itemsitems/articles/2?fields=title,translations.*

## Steps to Reproduce

3. Scroll down to '...'

## Expected Behavior

It should call it with double depth `/items/articles/2?fields=title,translations.*.*` because it can't access the image data in the translation and it crashes.

It should show all the data and let the user edit it.

## Actual Behavior

The javascript fails with an error of calling .split in null, the image is not shown and it's not editable.

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Install Method: [eg: cloned `master` branch]

**Comment by benhaynes** [comment]
If we can't support a dynamic n-levels through the interface options (`*.*.*.*`) then I guess we should enforce a limit. Three levels deep should suffice if we need to set one.

Parent (1)
* Translation (2)
    * Image (3)
