### ISSUE TITLE
Issues with WYSIWYG fields when creating, editing or duplicating

### ISSUE THREAD

**Issue by sebj54** [directus/app#1149]
# Bug Report: Creation

## Steps to Reproduce

1. Go to Settings → Collections
2. Create a `test` table
3. Create a WYSIWYG field, leave all options to default (except name of course)
4. Hit save

## Expected Behavior

The field should have been created.

## Actual Behavior

An error occurs.

## Other Context & Screenshots

Error shown in the console: 
```json
{
  "code": null,
  "message": "SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'test' (max = 21845); use BLOB or TEXT instead",
  "class": "PDOException",
  "file": "C:\\wamp64\\www\\directus\\vendor\\zendframework\\zend-db\\src\\Adapter\\Driver\\Pdo\\Connection.php",
  "line": 379
}
```

# Bug Report: Edition

## Steps to Reproduce

First we need to create the field. The workaround is to manually change field type to `TEXT`.

1. Create test WYSIWIG field with workaround
2. Edit field (ie: type `test` as a comment)
3. Edit again (ie: add something to your previous comment)
4. Hit save

## Expected Behavior

Field should be saved!

## Actual Behavior

Sometimes it is buggy at the first edit, sometimes only at the second. I noticed the field `type` has changed (sometimes it changes from TEXT to MEDIUMTEXT or LONGTEXT).

## Other Context & Screenshots

Errors shown in the console (several tests):

```json
{
  "code": null,
  "message": "SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'test' (max = 21845); use BLOB or TEXT instead",
  "class": "PDOException",
  "file": "C:\\wamp64\\www\\directus\\vendor\\zendframework\\zend-db\\src\\Adapter\\Driver\\Pdo\\Connection.php",
  "line": 379
}

{
  "code": null,
  "message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(16777215) COMMENT 'abc'' at line 2",
  "class": "PDOException",
  "file": "C:\\wamp64\\www\\directus\\vendor\\zendframework\\zend-db\\src\\Adapter\\Driver\\Pdo\\Connection.php",
  "line": 379
}

{
  "code": null,
  "message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(4294967295) COMMENT 'hey'' at line 2",
  "class": "PDOException",
  "file": "C:\\wamp64\\www\\directus\\vendor\\zendframework\\zend-db\\src\\Adapter\\Driver\\Pdo\\Connection.php",
  "line": 379
}
```

# Bug Report: Duplication

## Steps to Reproduce

1. Create a second table `test_again`
2. Go back to the `test` table, edit it.
3. Click duplicate on the WYSIWIG test field
4. Choose `test_again` table and what you want as a field name
5. Hit Create

## Expected Behavior

Field should be duplicated

## Actual Behavior

An error is shown in the console

## Other Context & Screenshots

```json
{
  "code": 403,
  "message": "field \"test\" does not support length",
  "class": "Directus\\Database\\Exception\\FieldLengthNotSupportedException",
  "file": "C:\\wamp64\\www\\directus\\src\\core\\Directus\\Services\\TablesService.php",
  "line": 1210
}
```

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Firefox 63.0.3
- Directus App: 7.0.9
- Directus API: latest? (updated with the Directus bundle)
- Install Method: cloned `master` branch

Thanks in advance 👍

**Comment by hellmaca** [comment]
I am also having this same issue. When changing the length setting to 20,000 I get a different error. Posting it here in case it is helpful.

{  
class: "PDOException"  
code: null  
file: "/Applications/MAMP/htdocs/dp-cms/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php"  
line: 379  
message: "SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"  
}

**Comment by rijkvanzanten** [comment]
While we're working on making this the default, you can change the datatype to `TEXT` as a workaround.
