### ISSUE TITLE
Login to other than predefined URL doesn't work

### ISSUE THREAD

**Issue by honzabilek4** [directus/app#1152]
On a login form page, while "Other" project is selected and custom api address is entered, the application doesn't correctly resolve the API URL. Therefore, you cannot login into Directus instance using this option.

![screenshot 2018-11-28 at 14 37 12](https://user-images.githubusercontent.com/7890555/49156357-7ce84c80-f31d-11e8-9ecf-4becb0a27575.png)
![screenshot 2018-11-28 at 14 55 01](https://user-images.githubusercontent.com/7890555/49156419-a2755600-f31d-11e8-809d-838effd7f2e1.png)

- Directus App: [7.0.9]
- Directus API: [2.0.9]

**Comment by rijkvanzanten** [comment]
Does it use the sessionStorage saved project as per your previous pull request?

**Comment by honzabilek4** [comment]
Hi @rijkvanzanten,
I don't think it has something to do with the storage at all. The problem is in the `login.vue` component.
When selected other the state of the component looks like following:
![screenshot 2018-11-28 at 23 51 48](https://user-images.githubusercontent.com/7890555/49187754-daee5180-f368-11e8-83e6-6d6ac8459fc7.png)
However when using some predefined project, the state looks like this:
![screenshot 2018-11-28 at 23 52 13](https://user-images.githubusercontent.com/7890555/49187737-cad67200-f368-11e8-8fd1-b9cfba479921.png)

The `selectedUrl` property is then used in credentials object for logging in, but has the value `"other"`:
![screenshot 2018-11-28 at 23 56 51](https://user-images.githubusercontent.com/7890555/49187941-5ea83e00-f369-11e8-8b86-a38950e7c501.png)

There's pretty much going on in this component, so I might need a little more time to understand the relationship between its data properties.

**Comment by honzabilek4** [comment]
I think the solution here is fairly simple after all.
The `this.url` property should be sent in the credentials object instead of `this.selectedUrl`.
