### ISSUE TITLE
Filter thanks to created_by field - nothing show when limiting the fields to display

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1157]
# Bug Report
When I limit the Readable Fields Fields, nothing show up in the interface of my 'Member' user.

## Steps to Reproduce

1. Added a User interface ("User Created" Field Type) named created_by to Collection
2. Created a few items within Collection with the Admin User
3. Added a new role called "Member"
4. Went to Settings > Permissions
5. Clicked on the READ/UPDATE for the Collection
6. See options for Mine/Role – set to "Mine"
7. Created a new user with Member role
8. Logged in as that User (Member Role)
9. Did not see any of the Admin's items
10. Created a new item... and confirmed it set the Created By to User/Member
11. Go back to Settings > Permission and limit the readable fields with your Admin User
12. Connect with your Member User and look at your Collection
13. Nothing appears

## Expected Behavior
Listing all the items with the readable fields (hide the others)

## Actual Behavior
Nothing is displayed

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus App: 7.0.x
- Install Method: cloned `master` branch

**Comment by carolin-skiply** [comment]
Apparently this behaviour occures only when unchecking the primary key in the readable fields for my collection.

**Comment by rijkvanzanten** [comment]
@carolin-skiply This is to be expected. If the user can't read the primary key, there's no way for the app to know what page to open / what values to fetch from the API.

**Comment by rijkvanzanten** [comment]
@benhaynes It does mean that you can't hide the primary key field for specific user groups. You can make the whole interface hidden, but that will also hide it for other user groups. The best I can do from the app side right now is remove the primary key field from the readable field picker in permissions.

**Comment by benhaynes** [comment]
Hmm, yeah. Everyone needs READ permission for the collection's primary key. I think we should disable the PK field in the READ column blacklist (keeping it in WRITE). 

This is another instance that illustrates the differences between READ and VIEW. But we can find a more elegant solution to this in the future if needed.
