### ISSUE TITLE
Allow image editing during the upload process

### ISSUE THREAD

**Issue by dur41d** [directus/app#1165]
# Feature Request

Widget that allows basic image editing (crop, resize) would be helpful and streamlines the content publishing process. This should be available during the upload process. Something similar to the upload widget in upload care: 

https://uploadcare.com/docs/file_uploads/widget/

This is a nice to have. 

## What problem does this feature solve?

Basic image editing within the admin interface.

## How do you think this should be implemented?

An upload widget in the admin interface.

## Would you be willing to work on this?

Sure.

**Comment by benhaynes** [comment]
Have you tried the built-in feature available on the File Detail page?
