### ISSUE TITLE
Can't save negative number with Integer Field Type

### ISSUE THREAD

**Issue by alrick** [directus/app#1166]
# Bug Report

## Steps to Reproduce
1. Add a numeric field (Field Type : Integer, MySQL Datatype INT)
2. Go to Collection > Item
3. Add a new item and set a negative value for the previously mentioned field
4. Save

## Expected Behavior
The negative value is correctly saved and displayed.

## Actual Behavior
The item is saved but the value is set to 0.

## Other Context & Screenshots

If I manually change to signed in my database, it's working, but how can I do this within the Directus App ?

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.1,
- Browser: Firefox 63.0.3
- Directus App: 7.0.8
- Install Method: Git clone directus suite

**Comment by benhaynes** [comment]
The issue here seems to be that the column is set to `unsigned` in the database. 

@rijkvanzanten and @WellingGuzman — do we have an option for this at the field level? How should we handle this? The easiest way is to have all numeric fields be signed and therefore allow positive or negative... however this would cut the length in half. 

Thoughts?

**Comment by rijkvanzanten** [comment]
I _think_ the API already allows to set `signed` to true or false when creating a field. 

We should add one of these for `signed` when you're selecting a mysql data type

<img width="532" alt="image" src="https://user-images.githubusercontent.com/9141017/49464991-64b77800-f7ca-11e8-95a0-6d01ba2eb692.png">

**Comment by rijkvanzanten** [comment]
Not sure if this is a "bug" or technically an enhancement, seeing that it's not necessarily broken not yet implemented. Oh well, I'll try to get it implemented for this weeks release either way 💪

**Comment by alrick** [comment]
@rijkvanzanten I think it's a bug in the way that it's set to unsigned when creating a numeric field with the app. At the moment there is no way to create a numeric field that allow negative values without manually setting to signed in the database, not sure about that.
