### ISSUE TITLE
User defined image size presets.

### ISSUE THREAD

**Issue by dur41d** [directus/app#1169]
# Feature Request

Currently, the file detail page offers several preset image sizes. I will be nice if the admin can add to this list custom sizes to fit to a specific template. 

To give an example, I have a website template that uses 281x206 images and it will help me if can add this size to make it easier for the content publisher to create the right images for the website.

## What problem does this feature solve?

Creating correct image size for a custom template.

## How do you think this should be implemented?

The configuration in the global admin interface to add custom sized to the list.

## Would you be willing to work on this?

Sure.

![image](https://user-images.githubusercontent.com/1318592/49457580-0fbf3600-f7b9-11e8-8234-b870d3b86f31.png)

**Comment by benhaynes** [comment]
I like it!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
