### ISSUE TITLE
Deploy app/api with docker under different base url path prefix

### ISSUE THREAD

**Issue by kmaris** [directus/app#1172]
# Bug Report

I am trying to deploy the api and app in separate docker containers on the same host. I'd like /directus/ to serve the javascript app (this works) and would like to host the api under /directus-api/ (this deployment also works and I can interact just fine with a request to /directus-api/users?access_token=...).

I built the docker container for the app as per the directions here: https://docs.directus.io/app/admin/install.html#installation with `docker build . -t directus`. Running the container with `docker run -d -e "API_URL=http://myhostname.internal.org/directus-api/"...` did not work and it couldn't find the api. I looked at the entrypoint script and you seem to reference API_ENDPOINT, so I tried adding that too: `docker run -d -e 'API_URL=http://myhostname.internal.org/directus-api/' -e 'API_ENDPOINT="directus=http://myhostname.internal.org/directus-api/"'`

The parsing done in entrypoint.sh produces an api entry of api:{ "": "directus"} which seemed broken to me, manually adding the api url as the key for directus fixes the config issue, but the deployment is still broken.

## Steps to Reproduce

Host the app and api under the same hostname and different base url's. The js app seems to get confused sending /server/ping requests to /server/ping instead of /directus-api/server/ping and refuses to let logins happen.

## Expected Behavior

The app talks to the api...

## Actual Behavior

The app does not see the api.

## Other Context & Screenshots

Since the default nginx configuration in the docker container only serves from /, I set the load balancer to strip the /directus/ part of the path from app urls. That seems to work fine and assets load. It seems to me that the ping needs to take the hostname and path prefix/base url/router base url/api endpoint/api url/whatever into accout and currently it does not. Trying to allow other api's by specifying a url manually does not work (path prefix is ignored).

Sidenote: I needed to hide the actual hostname but this is all going over port 80 so paths are the real culprit here. I have tried several api variations in the config object with both _ and directus-api names to no avail.

Happy to provide other deployment details if they would help. Here's config.js:

    /* eslint-disable */

    (function directusConfig() {
      const config = {
        // The API URLs the user can connect to using this instance of the application.
        // Object values are used as project name in the app
        // Don't forget to add the API environment!
        api: {
          "http://myhostname.internal.org/directus-api/": "directus" // manual change
        // original line at container runtime: "": "directus"
        },

        // Allow the user to connect to any API by entering a URL in a text field
        //   instead of selecting from a dropdown
        allowOtherAPI: false,

        // Controls the way the application routes. By default, routing is done using
        //   hashes (#) to ensure the app works without any server url rewrites.
        //
        // If you're using the application and have the correct URL rewrites in place
        //   (everything to /index.html), you can change this to "history" to make
        //   the urls in the app a little prettier
        routerMode: "hash", // hash | history

        // When using history mode, the application will make all the routes "pretty"
        // by using absolute paths. If you are serving the application from a folder
        // like /admin, this will cause the routes to be wrong (eg /collection instead
        // of /admin/collections). To combat this, set the routerBaseUrl to the path
        // you're serving the application from
        routerBaseUrl: "/directus"
      };

      window.__DirectusConfig__ = config;
    })();

And the environment in the docker container:

    HOSTNAME=7540c6b91ebb
    SHLVL=1
    HOME=/root
    API_ENDPOINT=directus=http://myhostname.internal.org/directus-api/
    ROUTER_BASE_URL=/directus/
    NGINX_VERSION=1.14.1
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ALLOW_OTHER_API=false
    PWD=/
    API_URL=http://myhostname.internal.org/directus-api/
    ROUTER_MODE=hash

## Technical Details

- Device: Desktop
- OS: MacOS 10.13.6
- Browser: Firefox Quantum 63.0.3 (64-bit)
- Directus App: master branch 9cd09ba8b6ef9f9eca66a06f02f5ced77dea80a6
- Directus API: 7.0.8
- Install Method: app: cloned, docker build, docker run. api: cloned tag, docker build, docker run

**Comment by rijkvanzanten** [comment]
@kmaris a new docker setup is in the works over at the directus/docker repo (and the #docker
channel on Slack). It's most likely going to replace this one completely.

**Comment by kmaris** [comment]
Thanks @rijkvanzanten.

I've managed to fix the /server/ping and login issue by adding this code to /etc/nginx/conf.d/default.conf and running `nginx -s reload` from the container:

    location /server/ping {
        return 200 'pong';
    }

The app still doesn't seem to want to play nice with an api instance hosted under the same hostname. I've got two rules at the load balancer: anything starting with /directus goes to the app container (with /directus stripped). The other rule is any requests to /_/ go to the api. The routing works, but the app is still making requests like this:

    http://server.example/interfaces
    http://server.example/collections
    http://server.example/pages

These requests are resulting in 404's since those rules are not defined. I'm under the impression the paths should be /_/interfaces, /_/collections, /_/pages and so on.

**Comment by rijkvanzanten** [comment]
@kmaris Certain routes are actually server wide. `/interfaces` is correct, so is `/server/ping` or even `/`. The scoped endpoints (eg `/_/items`) are specific to the project you're working in.

**Comment by kmaris** [comment]
So is it a matter of serving /index.html for /interfaces, /collections, and so on?

**Comment by rijkvanzanten** [comment]
Not really, no. The extensions are served from those endpoints, so those endpoints have to be routed to the API itself as well. If you take a peek at the source code of the API, you can see that there are static files in the public folder on those specific paths (so they're statically served). When using the combined build, the app will be (statically) served in `/admin`, with the API taking up everything else in `/`.

**Comment by kmaris** [comment]
My PHP chops are quite rusty, so I'll just ask for clarification here. Is there a way to set absolute url paths like /collections, /interfaces to be under any base-url paths like /directus/collections/... , /directus/interfaces/... etc? At least as far as app functionality is concerned, /server/ping is fine for now.

**Comment by kmaris** [comment]
Thanks for the help @rijkvanzanten I've worked past our problem for now and addressed some other issues in the directus/api repo.
