### ISSUE TITLE
Option to disable viewing other user's profiles

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1173]
You cant set the read permissions to that they can only see their profile but not others.
![grafik](https://user-images.githubusercontent.com/22577866/49544340-e5659980-f8da-11e8-920d-a5071ababfdc.png)

...although the option is set in other tables, you cant cange it there either.
![grafik](https://user-images.githubusercontent.com/22577866/49544460-2bbaf880-f8db-11e8-9755-f923cbe1d120.png)

This does not only apply to the read-perms. but also to create, update and delete.

Directus: example page

**Comment by benhaynes** [comment]
Hey @Nitwel — this would have to be a new App feature, not a permissions update. The App needs access to read all users so it can properly show accountability throughout the system so we can't turn it off. READ is different from VIEW in this case.

I'll update this ticket to be a feature request for disabling user detail pages.

**Comment by Nitwel** [comment]
Well, I remembered there was the option to set that you can set read, edit or delete permissions to only to once, you created, independend of which table you want to set these permissions.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
