### ISSUE TITLE
Can't save as copy if using divider field

### ISSUE THREAD

**Issue by alrick** [directus/app#1176]
# Bug Report

## Steps to Reproduce

1. Add a divider to a collection, let's call the field 'divider' for simplicity
2. Open an item
3. Make some changes
4. Click the 3 dots above the save button and chose "Save as copy".

## Expected Behavior

A copy of the item is saved.

## Actual Behavior
An error appears, regarding the divider.

> Failed generating the SQL query. Statement could not be executed (42S22 - 1054 - Unknown column 'divider' in 'field list')

## Technical Details

- Device: Desktop
- OS: MacOS
- Browser: Firefox, Chrome
- Directus App: 7.0.8
- Install Method: Git clone directus suite

**Comment by ondrakoupil** [comment]
I confirm this really happens. If the collection contains a divider field, an exception is raised:
`Failed generating the SQL query. in /Users/OK/PHP/zelen/backend/src/core/Directus/Database/TableGateway/BaseTableGateway.php:806`

If the collection does not contain a divider field, a copy is created successfully.

Directus 7.0.13, MacOS High Sierra, PHP 7.1.1, Chrome, installed as git clone.
