### ISSUE TITLE
Created & Modified dates aren't localised

### ISSUE THREAD

**Issue by KnowHowHere** [directus/app#1179]
# Bug Report

## Steps to Reproduce

1. Create a collection with a DateTime Created field
2. On the Options tab, choose "localized"
3. Under Options -> Advanced choose "Save as UTC"
4. Add date_created to the tabular view

## Expected Behaviour
Dates should be localised to the timezone configured for the current user in their profile.

## Actual Behaviour
Dates are displayed in UTC

## Technical Details
- Web Server time is UTC
- DB Server time is UTC
- Directus Suite: v7.0.10
- Install Method: [eg: cloned `master` branch]

**Comment by rijkvanzanten** [comment]
The `datetime_created` interface doesn't have a Save as UTC option

**Comment by KnowHowHere** [comment]
Hi there, thanks for looking into this, although I'm not sure I understand the resolution.  Firstly, while perhaps it wasn't intended there is a "Save as UTC" option at the bottom of the options tab for date_created/modified, but I'm not actually sure that has anything to do with the issue.

<img width="567" alt="saveasutc" src="https://user-images.githubusercontent.com/36661236/51063299-77855e00-164e-11e9-8156-609e8ff6b846.png">

All my date time fields (date_created, date_modified and other regular datetime fields directly populated) show their localised date on the details page for an item, but the record lists show UTC.

<img width="628" alt="list" src="https://user-images.githubusercontent.com/36661236/51063315-94219600-164e-11e9-8513-e3f773282d0f.png">
<img width="627" alt="details" src="https://user-images.githubusercontent.com/36661236/51063314-9388ff80-164e-11e9-9791-c617ca01ddac.png">


Are you suggesting this is to be expected?

**Comment by KnowHowHere** [comment]
API Rev 585be6d 2018-12-29 03:42:59 +0000
App Rev 53cb7a2 2018-12-29 03:50:47 +0000

Yes, regular datetime interface, using Chrome (as there seem to be a number UI components that only work in chrome)

<img width="650" alt="datetime" src="https://user-images.githubusercontent.com/36661236/51064100-1cee0100-1652-11e9-97ae-5a99d35f4dbd.png">

I'm not sure that the save as UTC setting is the issue though.  Everything is localised correctly in the details page, it's just the listing page that's showing UTC for me.
