### ISSUE TITLE
Width of fields in translation view

### ISSUE THREAD

**Issue by Kinzi** [directus/app#1180]
# Bug Report
CSS bug for the width of fields in a translation view

## Steps to Reproduce

1. Set up a simple `post` type table with a `translation` field
2. Add Textarea, WYSIWYG to translation table (the one that populates the translation view in `post`)
3. Go to post single view
4. See the textarea and WYSIWYG wider than translation frame

(also see screenshots below)

## Expected Behavior
Frames are limited by outer frame

## Actual Behavior
frames overlap

## Other Context & Screenshots
From playing around in the browser it seems that all that needs to be done is to set:
```
.v-form .col-4 {
    max-width: 100%;
    flex-basis: var(--width-x-large);
}
```
instead of 
```
.v-form .col-4 {
    max-width: var(--width-x-large);
    flex-basis: var(--width-x-large);
}
```

![bildschirmfoto 2018-12-07 um 11 33 32](https://user-images.githubusercontent.com/6689405/49639889-c9fea980-fa14-11e8-8fe2-de9b1aefec60.png)

![bildschirmfoto 2018-12-07 um 11 33 15](https://user-images.githubusercontent.com/6689405/49639890-ca974000-fa14-11e8-8940-3d7241b0a4c3.png)

## Technical Details

- Browser: Chrome / Firefox

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/app/pull/1222
