### ISSUE TITLE
WYSIWYG image upload to S3

### ISSUE THREAD

**Issue by Kinzi** [directus/app#1181]
# Feature Request

It would be great if the Advanced WYSIWYG would store uploaded folder to the connected storage adapter rather than converting them to Base64.

## What problem does this feature solve?

More flexibility and better SEO options when creating the frontend for the content. Allows to use the edit functionality.

## How do you think this should be implemented?

This looks like a good start: https://codepen.io/jackmu95/pen/EgBKZr

## Would you be willing to work on this?

I probably can if you point me to in the right direction on how I can plug into the current upload functionality.

**Comment by benhaynes** [comment]
I agree, this is a great idea!

@rijkvanzanten @WellingGuzman – any pointers on how/where this would happen?

**Comment by rijkvanzanten** [comment]
Hmm it could either directly go to S3 (circumventing directus_files completely) or upload the file to /files and have our regular storage adapters take care of it from there. The second had my preference

**Comment by benhaynes** [comment]
Definitely should use Directus files and our official endpoints, that way it will work with any storage adapter. It also be really nice if you could select existing directus user files too.

**Comment by rijkvanzanten** [comment]
Based on that original example in the provided codepen, uploading to the /files should be relatively trivial to achieve. Selecting from the library is a little more involved though

**Comment by benhaynes** [comment]
Awesome! What info would you need @Kinzi ? We can certainly point you in the right direction, and a PR for this would be absolutely amazing!

**Comment by Kinzi** [comment]
Thanks for looking into this @benhaynes and @rijkvanzanten. 

I do understand the codepen example and I'm pretty sure I can make the upload work if you could point me to some code example or existing code of the storage adapter upload function so I can figure out how to use it in this case.

About selecting from existing files: love it as well! 

I'm really not familiar with quilljs but maybe a first solution could be a custom (2nd) button in the toolbar that opens a modal much like the file field one and then just inserts the `<img>` into the model of the selected image. I've no idea if this would work but happy to explore it while looking into the above.

**Comment by benhaynes** [comment]
Awesome! I'm not sure if this is more front-end or back-end, but I'll have @WellingGuzman point out where this code is to get you started!

**Comment by Kinzi** [comment]
Thanks @WellingGuzman!

Originally I was wondering if there is a way to use the apps methods for this instead of talking directly to the API. So for example in the files interface - from what I gather - to save an upload all the interface does is emitting some global/store function with the file data:

```
 saveUpload(fileInfo) {
      this.$emit("input", fileInfo.data);
    }
```

Would this also be a road to take or would it be better to talk to the api directly.

**Comment by Kinzi** [comment]
OK so after digging into this a little deeper that codepen is misleading - it's not that straight forward :)

However there is this Plugin which looks quite good: https://github.com/fxmontigny/quill-image-upload

With this we could do an optional upload like this:

```
      let uploadURL = ''
      if (this.options.uploadFiles) uploadURL = 'http://directusapi:8888/_/files';
      this.editor = new Quill(this.$refs.editor, {
        theme: "snow",
        modules: {
          toolbar: this.options.toolbarOptions,
          imageUpload: {
              url: uploadURL, // server url. If the url is empty then the base64 returns
              method: 'POST', // change query method, default 'POST'
              name: 'image', // custom form name
              withCredentials: false, // withCredentials
              headers: {
                Authorization: 'Bearer Aw3s0m3T0k3n'
              }, // add custom headers, example { token: 'your-token'}
              csrf: { token: 'token', hash: '' }, // add custom CSRF
              customUploader: null, // add custom uploader
              // personalize successful callback and call next function to insert new url to the editor
              callbackOK: (serverResponse, next) => {
                // pass image url to editor
                next(serverResponse.data.data.full_url);
              },
              // personalize failed callback
              callbackKO: serverError => {
                alert(serverError);
              },
              // optional
              // add callback when a image have been chosen
              checkBeforeSend: (file, next) => {
                next(file); // go back to component and send to the server
              }
            }
          }
      });
```

Is there some global var for `project-url` and some better way to plug Authentication dynamically?

**Comment by Kinzi** [comment]
Ha found it:

```
this.$store.state.auth.url
this.$store.state.auth.token
```

**Comment by Kinzi** [comment]
Alright here you go: https://github.com/directus/api/pull/649

(upload only)

**Comment by Kinzi** [comment]
Now also with the option to select existing images: directus/api#649

**Comment by benhaynes** [comment]
Wow! You work fast @Kinzi!! ⚡️

**Comment by rijkvanzanten** [comment]
This is fixed by 
https://github.com/directus/api/pull/649
