### ISSUE TITLE
File Library Missing Pagination

### ISSUE THREAD

**Issue by anahit42** [directus/app#1186]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus API version (Or commit hash): 6.4.9
  - Web server: (Ex. Apache, nginx or IIS?) ngnix
  - OS name and version: Ubuntu 16.04

## Expected Behavior

Currently our file library shows files with limit set in directus settings.

But on scrolling it doesn't load more files as in other tables scrolles.

## Steps to Reproduce
 1. login to CMS
 2.  go to file library
 3. have more files than query per page limit and scroll to get more

**Comment by rijkvanzanten** [comment]
This has been fixed in 
https://github.com/directus/api/commit/0a63c33ba9ae8bab77b2fd039fe44d84bd6f2adb

**Comment by Pujan789556** [comment]
Is this update is also in directus suite (directus/directus). I updated to version v7.0.17 and didn't found this specific update

**Comment by benhaynes** [comment]
Hey @Pujan789556 — this will be in 7.0.18 which will be released tomorrow or Monday. It is on `master` though if you want to pull from there.
