### ISSUE TITLE
Link list->detail only working when ID column visible

### ISSUE THREAD

**Issue by Kinzi** [directus/app#1188]
# Bug Report
It seems that with the latest version of the app the link from the list view to the detail view is only working if the ID column is visible in the list. 

ID column hidden in list view created this link:
`http://directusapp:8888/#/collections/mycollection/undefined`
ID column visible creates the proper link:
`http://directusapp:8888/#/collections/mycollection/407`

## Steps to Reproduce

1. Fetch latest app and api and npm install // build
2. go to list view of collection
3. hide ID column
4. click on list item

## Expected Behavior

show detail view of that item

## Actual Behavior

Page Not Found

**Comment by benhaynes** [comment]
Thanks @Kinzi — we'll look into this ASAP...

**Comment by benhaynes** [comment]
🚨**Critical Bug** 🚨
We've elevated this to a `critical` issue, but our team has very little working hours this week. We're currently debating on rolling-back to the previous version.

If anyone in the community has time to look into this we'd appreciate it!
