### ISSUE TITLE
Changing fields with m2o relationship in Table view removes values for those fields

### ISSUE THREAD

**Issue by xmath279** [directus/app#1189]
# Bug Report

## Steps to Reproduce

1. Set up collections with a Many-To-One relationship and a value in "Dropdown Template"
2. Go to the collection to see data
3. Add or reorder fields in the collection list view

## Expected Behavior
Properly reorder and add fields with proper values in the relationship fields.

## Actual Behavior
Fields are properly reordered and/or added, but values from relationship fields are lost. Also, when clicking to get details of a row, the URL is improperly set with "undefined" as identifier. For instance: `/collections/episodes/undefined`

## Other Context & Screenshots

Going back and forth from Cards to Table makes the relationship field columns flicker with the correct values only to be back to blank again after a second.

## Technical Details

- Device: Desktop
- OS: macOS 10.14.1
- Browser: Chrome 70
- Directus App: Latest Docker version (directus/app 7.0.11)
- Directus API: Latest Docker version (directus/api 2.0.11)
- Install Method: docker-compose with same settings as the single-api example file
https://github.com/directus/docker/tree/master/examples/single-api

**Comment by rijkvanzanten** [comment]
> Also, when clicking to get details of a row, the URL is improperly set with "undefined" as identifier. For instance: /collections/episodes/undefined

Rel: https://github.com/directus/app/issues/1188

**Comment by benhaynes** [comment]
Just to add to this issue: it seems to be present in the demo: https://directus.app/#/collections/screens

**Comment by xmath279** [comment]
Did some more digging, works on 2.0.10 & 7.0.10

**Comment by rijkvanzanten** [comment]
@xmath279 @benhaynes I feel like issue that's causing #1188 is also the cause of this

**Comment by benhaynes** [comment]
Seems likely, yeah

**Comment by rijkvanzanten** [comment]
This appears to be working correctly in the latest version. Please let me know if you still encounter this issue and we'll investigate further.
