### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by milgron** [directus/app#1190]
# Bug Report

## Steps to Reproduce

1. Go to LOGIN PAGE.
2. After type the credentials, login fails. 

## Expected Behavior

Login ahah

## Actual Behavior
error msg: 'Unknown error. Try again later'

## Other Context & Screenshots

Password recovery doesn't work too..

**Comment by rijkvanzanten** [comment]
@milgron What server are you using? How did you install the API? What else do we need to know in order to reproduce your setup?

**Comment by milgron** [comment]
> @milgron What server are you using? How did you install the API? What else do we need to know in order to reproduce your setup?

Hi there! I´m on a LAMP instance on Google Cloud. 
Apache: 2.4.18
Ubuntu: 16.04.1
PHP: 7.2.12-1
MySQL: 5.7.24

I've installed the API cloning the Github repo.

**Comment by rijkvanzanten** [comment]
> I've installed the API cloning the Github repo.

The [directus/directus](https://github.com/directus/directus) repo or the [API repo](https://github.com/directus/api) directly?

**Comment by milgron** [comment]
The [directus/directus](https://github.com/directus/directus)

**Comment by milgron** [comment]
> > I've installed the API cloning the Github repo.
> 
> The [directus/directus](https://github.com/directus/directus) repo or the [API repo](https://github.com/directus/api) directly?

The directus/directus

**Comment by rijkvanzanten** [comment]
Did you enable `mod_rewrite` and do you have `php_curl` installed?

If so, are there any errors in the `/logs/` folder?

**Comment by milgron** [comment]
> Did you enable `mod_rewrite` and do you have `php_curl` installed?
> 
> If so, are there any errors in the `/logs/` folder?

[2018-12-10 08:48:32] api[].ERROR: Directus\Authentication\Exception\UserNotAuthenticatedException: User not authenticated in /var/www/directus.decirkel.co/html/src/core/Directus/Application/Http/Middleware/AuthenticatedMiddleware.php:21
Stack trace:
#0 [internal function]: Directus\Application\Http\Middleware\AuthenticatedMiddleware->__invoke
#1 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#2 [internal function]: Slim\DeferredCallable->__invoke
#3 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#4 /var/www/directus.decirkel.co/html/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(80): Slim\Route->Slim\{closure}
#5 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#6 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#7 [internal function]: Slim\DeferredCallable->__invoke
#8 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#9 /var/www/directus.decirkel.co/html/src/core/Directus/Application/Http/Middleware/AuthenticationIgnoreOriginMiddleware.php(19): Slim\Route->Slim\{closure}
#10 [internal function]: Directus\Application\Http\Middleware\AuthenticationIgnoreOriginMiddleware->__invoke
#11 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#14 /var/www/directus.decirkel.co/html/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#15 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#16 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#19 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#20 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#21 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/App.php(515): Slim\Route->run
#22 /var/www/directus.decirkel.co/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#23 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#24 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#25 [internal function]: Slim\DeferredCallable->__invoke
#26 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#27 /var/www/directus.decirkel.co/html/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}
#28 [internal function]: RKA\Middleware\IpAddress->__invoke
#29 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/directus.decirkel.co/html/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#33 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#34 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#35 [internal function]: Slim\DeferredCallable->__invoke
#36 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#37 /var/www/directus.decirkel.co/html/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#38 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#39 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#40 [internal function]: Slim\DeferredCallable->__invoke
#41 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#42 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#43 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack
#44 /var/www/directus.decirkel.co/html/vendor/slim/slim/Slim/App.php(314): Slim\App->process
#45 /var/www/directus.decirkel.co/html/src/core/Directus/Application/Application.php(161): Slim\App->run
#46 /var/www/directus.decirkel.co/html/public/index.php(5): Directus\Application\Application->run [] []
