### ISSUE TITLE
Set static token on profile page

### ISSUE THREAD

**Issue by joshuaavalon** [directus/app#1192]
# Feature Request

## What problem does this feature solve?
There is [static token](https://docs.directus.io/api/reference.html#static-tokens) but it is not possible to change unless access api ourself.

## How do you think this should be implemented?
Add a field on profile page

## Would you be willing to work on this?
I am no familiar with the code base.

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman — do we want to add this to the user detail page but **only for admins**?

**Comment by rijkvanzanten** [comment]
> but only for admins?

We currently don't have an admin-only permission. I think the best thing we can do is add a field_blacklist in the default permissions for new roles for directus_users. @WellingGuzman where are those default permissions for new roles managed in the API?

**Comment by benhaynes** [comment]
True. I guess it's a bit hacky to hardcode this into the App.

**Comment by rijkvanzanten** [comment]
@benhaynes yeah doesn't feel right. It would work just fine, but it's non-standard and unexpected to work that way for a single interface.

**Comment by benhaynes** [comment]
Yeah — agree.

**Comment by WellingGuzman** [comment]
This "feature" used to be on the default permission, I think it was only visible to admin (blacklisted to everyone by default).

Here is where set the default permission: https://github.com/directus/api/blob/master/src/core/Directus/Application/CoreServicesProvider.php#L219.

Here are the default permissions for new roles: https://github.com/directus/api/blob/master/src/core/Directus/Util/Installation/InstallerUtils.php#L386

**Comment by benhaynes** [comment]
@rijkvanzanten do we want this or should it be database only? Cloud had a solution through the dashboard.

**Comment by rijkvanzanten** [comment]
I'm still not sure. If we make it a field open to all users, it's very easy for non-experienced users to open up a major security flaw by setting an unsafe token. That being said, for developers it's a bit annoying to have to rely on direct database connection to set it up....

Maybe if we add the token field to the read field blacklist for non-admin group by default, we can activate the field for admin users only.

**Comment by benhaynes** [comment]
Maybe a better solution is to have a settings panel for generating and resetting tokens just like we have in Cloud. That would make it admin only and ensure that its consolidated in one place. Thoughts?

**Comment by rijkvanzanten** [comment]
I like that, it also makes sure that no tokens exist "on accident" 👍

**Comment by benhaynes** [comment]
Created a new ticket for properly managing theses.
