### ISSUE TITLE
Default Listing View Preferences for M20 don't work

### ISSUE THREAD

**Issue by ransoing** [directus/app#1195]
# Bug Report

## Steps to Reproduce

While editing the settings for a many-to-one field, in the "Options" tab (see the screenshot below to see what I mean)...
![listing-view](https://user-images.githubusercontent.com/8118810/49893965-f7c76200-fe09-11e8-8460-641428e447ee.png)
...if you click the "fill with template" icon in the Listing View Preferences input area, it gives the following example:

```
{
    "viewType": "tabular",
    "viewQuery": {
        "fields": [
            "id",
            "name"
        ]
    },
    "filters": [
        {
            "field": "name",
            "operator": "contains",
            "value": "hi"
        }
    ]
}
```

After editing that JSON to use the appropriate "fields" values, when editing or adding an item that uses that M2O relation, upon clicking the M2O field, the modal shows an empty list of items, and the app throws a js error:
![m2o-error](https://user-images.githubusercontent.com/8118810/49894266-c4d19e00-fe0a-11e8-9cbc-67b8ca6bf090.png)

The error `this.viewQuery.fields.split is not a function` hints that it expects the `fields` object to be a string, not an array. And indeed, if I change the json in the listing view preferences to be formatted like `"fields": "id,name"`, then everything works properly.

## Expected Behavior
The format of the default Listing View Preferences JSON should work properly.

## Actual Behavior
The app throws errors because it expects the format of the "fields" object in the JSON to be a string rather than an array.

## Technical Details

- Device: Chrome latest on Mac
- Directus App: next.directus.app
- Directus API: Directus Stable demo

**Comment by benhaynes** [comment]
This one seems pretty important, no? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
If the example value of a single interface doesn't work? I mean it's inconvenient and should obv be solved, but compared to some of the other issues it's not high priority..

**Comment by benhaynes** [comment]
True — just seems like this is the way 98% of users will setup the interface... and if it errors out with that value then the whole interface is broken. Anyway, we can keep it as low!

**Comment by ransoing** [comment]
If it's really just a matter of changing the example value, then it should take less time to fix it than to read through this thread

**Comment by rijkvanzanten** [comment]
Yeah! Looks like it

**Comment by MartinN3** [comment]
Is this resolved yet? What is the solution? Sorry i just cant find follow up ticket or pull request or solution. Thanks

**Comment by benhaynes** [comment]
Hey @MartinN3 — this ticket was a duplicate of https://github.com/directus/app/issues/1108 ... you can track the progress over there.
