### ISSUE TITLE
Google SSO - GAE - ERR CONNECTION TIME OUT

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1199]
Hi,

I installed my directus instance on a Google AppEngine Flex. Everything works perfectly !
Then, I followed [this tutorial](https://medium.com/directus/3rd-party-authentication-2da642576dcd) to set up the Google SSO. 

1st issue : the image is not displayed properly
![image](https://user-images.githubusercontent.com/34483024/49997151-1dcb3e80-ff91-11e8-9282-0a41048987cf.png)

2nd issue : when I go throught the process, sign on works but my callback_url return this error : **ERR_CONNECTION_TIMED_OUT**.

The callback is https://my-domain.com:8080/_/auth/sso/google/callback
The callback is on the port 8080 : is this mandatory ? If not how can I change it ?

I tried the callback without :8080 and here is what I got :
![image](https://user-images.githubusercontent.com/34483024/50004107-545f8400-ffa6-11e8-82a3-1d27cb4a4885.png)

Any idea to fix this ?

**Comment by carolin-skiply** [comment]
Hi there, 
I reach google support and here is there answer :
> I can confirm that app engine doesn't listen on port 8080. ... The correct way to do this is to explicitly configure the redirect url inside of the app.

Again is there a way to use the url without port ? can I change it somewhere ? is there another way to do this ?
Please help,

**Comment by rijkvanzanten** [comment]
How do you run the application? Do you use any custom server or even the dev mode? 

I don't know where the 8080 port comes from, as it's non standard

**Comment by carolin-skiply** [comment]
I have another question : If I am not wrong you are using Google+ API for Single Sign In. Are you aware that [the service will be shut down Google+ on March 7, 2019](https://developers.google.com/+/web/api/rest/) ?

Are you working on another solution ?

**Comment by benhaynes** [comment]
Good question @carolin-skiply! @WellingGuzman are we using this API for our Google SSO? Since they're shutting down Google+ we should plan to upgrade to a new API asap.

**Comment by WellingGuzman** [comment]
> @rijkvanzanten I install Directus on an Google App Engine (Flex env) with is using a docker to run it.
> I did not change any mode (after downloading directus from git) so it's probably in dev mode ?
> 
> I don't know why but that's the url that Google gave me when I did not set the redirect_url.
> ![image](https://user-images.githubusercontent.com/34483024/50287359-c9c5cb80-0462-11e9-9864-9c364e8240e8.png)
> I tried to set other url (without the port) but does not work :(

@carolin-skiply did you this url properly? It seems the url you are adding is not the same as the redirect url.

> Good question @carolin-skiply! @WellingGuzman are we using this API for our Google SSO? Since they're shutting down Google+ we should plan to upgrade to a new API asap.

By default it uses the Google+ API, if you want to use the openID Connect API you should enable [`use_oidc_mode` in your api configuration](https://github.com/directus/docs/blob/ad3d1423242d369940c7e54f0185b04550648f9d/advanced/api/configuration.md#google).

Eventually this `use_oidc_mode` will be default to `true` (or actually remove the option to always use OpenID Connect.

**Comment by benhaynes** [comment]
> By default it uses the Google+ API, if you want to use the openID Connect API you should enable use_oidc_mode in your api configuration.
> Eventually this use_oidc_mode will be default to true (or actually remove the option to always use OpenID Connect.

Gotcha. So do we need to do anything now to make our Google SSO work when Google+ is shut down? Can we make sure that all of our Docs and example code is having people use OpenID?

**Comment by WellingGuzman** [comment]
Definitely we must check the docs. Also new installations uses `use_oidc_mode` by default now.

**Comment by WellingGuzman** [comment]
The docs configuration makes reference to the `use_oidc_mode`, and there's not example of using it, but there's explanation in both docs and api example configuration.

Ref: https://github.com/directus/docs/blob/ad3d1423242d369940c7e54f0185b04550648f9d/advanced/api/configuration.md#google

**Comment by carolin-skiply** [comment]
Happy New Year !

Thanks guys. I am going to try to the openID solution. I'll let you know how it works.

**Comment by carolin-skiply** [comment]
@WellingGuzman Hi ! I've enable use_oidc_mode to true as you suggested. 
I still have the initial issue which is : directus redicts me to an url using the port 8080. This port can not be use within the docker appEngine that I use. Is there anyway that I can remove this port ?

When this url (with the port) is set in google API , I got an ERR_CONNECTION_TIMED_OUT error.

**Comment by WellingGuzman** [comment]
Happy new year @carolin-skiply.

It seems you have to change the port 8080 to something else, in your web server. I don't fully understand the situation, but if you want to change the port you are welcome to in your own webserver.
