### ISSUE TITLE
Front-end hooks

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#120]
Add custom events that are dispatched on the root directus app that allow developers to extent the platform with whatever JS they want.

**Comment by rijkvanzanten** [comment]
Vuex mutation-types.js style for regular JS events. Checkout filepond for inspiration on how to dispatch these custom events

**Comment by benhaynes** [comment]
This should be able to hook into Google Analytics for SPA tracking.

**Comment by rijkvanzanten** [comment]
The other way around! You can hook Google Analytics into Directus 😉

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Nice to have in the future

**Comment by rijkvanzanten** [comment]
You can already include google analytics through the normal custom script inclusion, and no one has requested this in the almost-year it has been up. I'm considering this not worth it 80/20.
