### ISSUE TITLE
Warn users if exceeding max file size before upload

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1201]
We know the max upload size (from the API) and should give a friendly warning _before_ the upload begins. The warning should also explain _why_ the upload won't work: `Your server is not configured to handle uploads of this size.`

**Comment by c-ciobanu** [comment]
It's fine if i do this one?

**Comment by rijkvanzanten** [comment]
Absolutely! The max file size can be access through `this.$store.serverInfo.maxUploadSize`:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/9141017/50178574-ee8b3900-02d2-11e9-8216-ae07c21b8476.png">

**Comment by c-ciobanu** [comment]
Thanks, the upload component is the only one involved right?

**Comment by rijkvanzanten** [comment]
Yeah, that one is re-used in the file extensions as well. Adding this functionality to the main upload component should make it work everywhere :)

**Comment by c-ciobanu** [comment]
@rijkvanzanten I was looking for a warning toast but I only found the error one, it already exist or should i create a warning event with 
![screenshot from 2018-12-18 21-19-47](https://user-images.githubusercontent.com/33382714/50180719-ad168000-030a-11e9-8fa5-e46f2e581a52.png)
