### ISSUE TITLE
@mentions and #refs in comments

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1202]
The API will handle actual activity/mentions, but the App doesn't need to wait for that to get these links working. Basically we should have a _helper_ dropdown appear when you type `@` that autocompletes Directus users and then enters the markdown link for them.

We should also have the same thing for `#` to reference items in the CMS. We should discuss how this "compound" autocomplete would work. We could have two stages, where users select the collection then the item, or they type an item title and it lists any matches across all collections.

Ideally we should also support pasting links to items in and re-formatting them into markdown links.

Lastly, _how_ will this display? I like how GitHub works, but am not sure if we can reproduce that.

**Comment by rijkvanzanten** [comment]
> We should also have the same thing for # to reference items in the CMS. We should discuss how this "compound" autocomplete would work. We could have two stages, where users select the collection then the item, or they type an item title and it lists any matches across all collections.

Like this?:

```
Hey @benhaynes! Thanks for updating this, but I'm pretty sure we're already mentioning this in #movies/15. Could you verify?
```

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
