### ISSUE TITLE
Loading edit view of a collection item with radio field does not load radio field values

### ISSUE THREAD

**Issue by rw3iss** [directus/app#1206]
# Bug Report

## Steps to Reproduce
Make a collection with a radio field and some radio options.
Add new items in the collection, selecting one of the radio options.
Reload the edit item view, and notice none of the radio buttons are selected, however, if you look at the collection list view, with the radio column visible, you can see the value in this column.

## Expected Behavior
Should show the selected radio option on the item edit page.

## Actual Behavior
Does not select the selected value on the edit page.

## Technical Details

- Device: Macbook Air
- OS: Mac osx high sierra
- Browser: Chrome 70.0.3538.110
- Directus App: 7.0.9
- Directus API: 2.0.9
- Install Method: Installed api and app separately through cloned master branches.

![screen shot 2018-12-18 at 15 03 31](https://user-images.githubusercontent.com/372120/50179866-1c25b180-02d6-11e9-83fe-a316519564a0.png)
![screen shot 2018-12-18 at 15 03 26](https://user-images.githubusercontent.com/372120/50179870-20ea6580-02d6-11e9-82ce-ecd23bc48597.png)

No console error is produced during these operations.
The item edit view can detect the value: if you select the already-selected value (but not being shown as such), you can see the item edit Save checkbox does not become enabled, but if you choose a different value, it does... so just some little quirk with the UI it seems.

**Comment by rijkvanzanten** [comment]
Could you share what options you used to setup this field? I just tried on a fresh installation and it seems to be working as expected for me.

**Comment by rw3iss** [comment]
I updated Directus last week and just checked on where it wasn't working before, but it seems to be working now. I think we can close this. Thanks.
