### ISSUE TITLE
M2M: No data in popover

### ISSUE THREAD

**Issue by rjwismar** [directus/app#1210]
# Bug Report

## Steps to Reproduce

1. Create a M2M field
2. Display the field in the listview
3. Mouseover the counter
4. See a popover with the correct length of items but without any data

## Expected Behavior

Should display the title or name of the item

## Actual Behavior

Shows the correct length but no data in in the popover

## Other Context & Screenshots

![image1](http://api.ssb-festival.de/screen5.png)

## Technical Details

- Device: Desktop
- OS: MacOS 12
- Browser: Chrome
- Directus App: 7.0.12
- Directus API: 2.0.x
- Install Method: cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
Did you fill out the `template` option?

<img width="680" alt="image" src="https://user-images.githubusercontent.com/9141017/51050526-16eb1800-159f-11e9-8d04-28126c21e6bd.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/9141017/51050520-118dcd80-159f-11e9-9cbb-57c964068057.png">

**Comment by rijkvanzanten** [comment]
I've confirmed this to be working. I also tweaked the interface to only show the dropdown if the template option has a value in it.

**Comment by rjwismar** [comment]
Hi, 

yes I filled this out but I didn't see anything again.

My schematic is:

helpers -> id, forename, ...
helpers_join-> id,  join_id = helpers_id, kind_id = helpers_kind_id
helpers_kind -> id, title, ...

In the options I enter this:

Visible Columns
```
title
```

Listing View Preferences =
```
{
    "viewOptions": {
        "fields": [
            "title"
        ]
    }
}
```

Display Template
```
{{ helpers_kind.title }}
```

**Comment by rijkvanzanten** [comment]
Try using `{{ kind_id.title }}` for the template. It uses the junction table field name as of right now.

**Comment by rjwismar** [comment]
THX,

this will work thank you.
