### ISSUE TITLE
Add automatic relationships

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1215]
Right now, you have the ability to setup the relationship exactly how you want it. However, in real use, you'd often want it to "just work". I don't want to be bothered with having to setup a junction `articles_images` collection just to add a `files` interface to my `articles` collection for example. The Directus app has enough information to create these junction tables automatically, which should make the setup of relational (M2M / files) interface way easier.

**Comment by ceruulean** [comment]
![image](https://user-images.githubusercontent.com/41603229/51724239-0d8f9000-2022-11e9-98cc-480c5af1ddf9.png)
Would something like this work? Don't mind the placeholder text...

**Comment by benhaynes** [comment]
Good idea @ceruulean!

I wonder if it would be cleaner to have a toggle _next to_ "Junction Collection" (with a label saying: `Auto-Generate`) and when that's enabled it converts the dropdowns into text inputs with automatically generated collection/field names (that can be changed).

![directus 8 new relationship](https://user-images.githubusercontent.com/522079/52023497-4d93be80-24cb-11e9-8127-dc19b64db790.png)

_(This mockup uses the new 7.1 design system)_

**Comment by ceruulean** [comment]
@benhaynes @rijkvanzanten 
![image](https://user-images.githubusercontent.com/41603229/52105736-7b553200-25b5-11e9-9ebd-ee6290162e3c.png)
1. Checkbox versus toggle, yay or nay?

2. At first I thought placeholders for suggestions was good, but on second thought if I'm feeling really lazy or want to save more time, having the names automatically filled would save time. Just check and go!

3. I had trouble getting a background color for the middle column, because it's a grid system... any ideas? I thought about creating a separate element just to have background color but that seems cheesy.

**Comment by rijkvanzanten** [comment]
I'm wondering if we should even display the different boxes and fields if the junction is created automatically :thinking:

Alternatively, the drop downs for the junction could change to inputs so you can modify the names of the fields if you want

**Comment by benhaynes** [comment]
Haha, oh @rijkvanzanten... 😴 

> and when that's enabled it converts the dropdowns into text inputs with automatically generated collection/field names (that can be changed).

**Comment by benhaynes** [comment]
Hey @ceruulean — this is awesome!

1. I like the checkbox!
2. We should add our default values as placeholder **and** the default value. That way they can be lazy and just go with it... or change it. But if they change it and want to see our recommendations again they are there as placeholder.
3. Don't worry about that background color for the middle column, I was just trying to find a way to better group those three columns. Let's ignore it for now.

This is really looking great, thank you so much!

**Comment by rijkvanzanten** [comment]
This was closed in #1296
