### ISSUE TITLE
Code interface saves string instead of object

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1216]
Which results in a string being saved to the DB, which in turn results in other interfaces that rely on objects being returned for their options breaking, like this checkbox:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/9141017/50386481-5071e700-06b5-11e9-8b62-cfb850130fb1.png">

**Comment by rijkvanzanten** [comment]
Okay this is pretty critical actually, it messes the permissions up as well, as it too tries using the value as object, but instead ends up with a string:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/9141017/50386849-3b995180-06bd-11e9-824d-89cd4049d83c.png">

**Comment by rijkvanzanten** [comment]
Also, I'm pretty sure the API is supposed to cast this to an object when the JSON type is being used 🤔

**Comment by KKAries** [comment]
Still have such issue when using checkbox interface and modified json value. I am using the latest api. If the json value is modified in options, the display is messed up.
