### ISSUE TITLE
Strange bug with M2M fields editions

### ISSUE THREAD

**Issue by sebj54** [directus/app#1223]
# Bug Report

I have a table with several M2M fields. After the 7.0.13 update (from 7.0.9), I cannot edit some M2M fields while I can edit the majority of them.

## Steps to Reproduce

⚠ I'm really not sure what is causing the bug, I tried to recreate M2M fields but it had no effect. See the video below showing my M2M fields and the bug itself.

## Expected Behavior

M2M fields should:
 - display the correct fields in _tabularView_
 - not throw an error when selecting a record

## Actual Behavior

For some fields, no field value shown in _tabularView_ and selecting a value has no effect (except showing an error).

## Other Context & Screenshots

Main table: `inspirations`
Buggy M2M field: `saisons` (with `inspirations_saisons` table)
Not buggy M2M field: `durees` (with `inspirations_durees` table)

🎦 https://drive.google.com/file/d/1vnX_xbwYIMHRZc-3FoEwSzEEdMbys92W/preview

## Technical Details

- Device: Desktop
- OS: Windows 10 latest
- Browser: Firefox latest
- Directus App: 7.0.13
- Directus API: 2.0.13
- Install Method: cloned `master` branch of `directus/directus`

**Comment by sebj54** [comment]
Hi :)

After a long time trying to fix this, I finally figured it out (and there are 2 different bugs at least).

First of all, I noticed there were many relations defined in DB for a single relation:

```sql
SELECT * FROM `directus_relations` WHERE `collection_many` LIKE '%saisons%' OR `collection_one` LIKE '%saisons%' ;
```

![image](https://user-images.githubusercontent.com/5880435/50481166-5da61300-09e0-11e9-9cdf-affcb259988b.png)

To fix this bug for this field, I removed the `saisons` M2M field in `inspirations` and removed every relation with `inspirations_saison` table. 
I assume that all these relations are remains of my tests with M2M relations. I created this field many times to test the relations. **Maybe the app does not remove relations when a relational field is removed.**

Second bug, this time on another relation:

![image](https://user-images.githubusercontent.com/5880435/50481338-38fe6b00-09e1-11e9-8d38-c63e9475107f.png)

The problem this time, is that the field on the junction table has the same name as the field on main table (or secondary table's name).

To fix this, I had to change this field's name:

![image](https://user-images.githubusercontent.com/5880435/50481427-b5914980-09e1-11e9-9d1a-af4a70e66c63.png)

Before that, I did like I did for `saisons` relation: remove every relation with `inspirations_pays` also.

**Comment by benhaynes** [comment]
Thank you for all the info @sebj54! We'll take a look at this next week when the @rijkvanzanten is back from the holidays.

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/app/issues/1045

**Comment by rijkvanzanten** [comment]
I'm pretty sure this should fix it: https://github.com/directus/api/issues/586

**Comment by rijkvanzanten** [comment]
I marked it wontfix as there isn't anything to fix in the application to make this work. I'll leave it open for a bit 'til api/#586 has been fixed and we've confirmed this to be working 👍

**Comment by Lapsus** [comment]
I have a similar problem with m2m relations. 
When i create them manually, it works. When i create the relation ship by sending data to relations and collections api, the m2m shows in the admin screen for the collection but i can not edit it. 

I compared database entries in directus_fields and directus_relations for the manually created m2m and the one created via api. The data looks identical, but the one created via api can not be edited.

The following shows up in the console.
<img width="1085" alt="Bildschirmfoto 2019-04-04 um 15 52 26" src="https://user-images.githubusercontent.com/799809/55561046-c55fae80-56f1-11e9-9e38-18462a4912d0.png">

I hope this helps to narrow the problem down.
