### ISSUE TITLE
Layout: Map

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1226]
This could even be a Core layout. Here is a rough design, but it's pretty straight-forward. Here are some thoughts/questions:

* How would we handle filtering/limiting items? Would we limit to X (page count) within the map bounds?
    * How would we show the user if there are _more_ items than are shown (more than page limit)?
    * Would we use the actual Filter system for this? It would be nice to have a shortcut to filter based on location.
    * Within lat/lon bounds
    * Radius/distance from lat/lon point
* What types of location fields would this work with?
    * Geocoded address?
    * Separate lat/lon fields?
    * Combined lat/lon field?
    * Relational locations? (eg: lat/lon in related data)
* We would use the same OSS map as the Map interface, right?
* Hover pane would be configured in the layout options... much like the Card view.
* Clicking would take you into the Item Detail, right?

![directus 7 map view](https://user-images.githubusercontent.com/522079/50564897-16c55f80-0cf7-11e9-950e-fc0faf5b24a9.png)

**Comment by Nitwel** [comment]
Hey, I designed an more advanced layout, with a Location navigation.

![web 1920 1](https://user-images.githubusercontent.com/22577866/51130888-71e66e80-182e-11e9-8fa5-4177fed47bd6.png)

![web 1920 2](https://user-images.githubusercontent.com/22577866/51130895-77dc4f80-182e-11e9-89df-87eea96e73be.png)

This should help manage locations, which are long distance apart.
The icon next to it should center the map to the given location.
Thoughts @benhaynes ?

**Comment by benhaynes** [comment]
This is amazing @Nitwel!! You work fast! ⚡️ 

* What does the "Pin" icon do on the top-right?
* Clicking the icon in the location list takes you to that location?
* How does this filter items? Does it only render the items in the map viewport bounds?
* Maybe we add the ability to map a _secondary_ field text (below the title) too?

Looks great so far!

**Comment by Nitwel** [comment]
> What does the "Pin" icon do on the top-right?

Toggles the side view

> Clicking the icon in the location list takes you to that location?

Yep

> How does this filter items? Does it only render the items in the map viewport bounds?

Doesnt this leaflet do by itself?

> Maybe we add the ability to map a secondary field text (below the title) too?

Sure we can ^^ :P

**Comment by rijkvanzanten** [comment]
Could we use the already existing info sidebar to show those? Or is that counter intuitive?

What @benhaynes probably meant by "what does it render" is the fact that the api will by default return the first 200 or so items, this could also mean that items that should be in the viewed lat long don't get returned.

> Schoolkids life :P

I know right 💪

**Comment by Nitwel** [comment]
> the api will by default return the first 200 or so items

Good to know XD. So I guess the Calendar should Include lazy loading too?
If yes, It would be good to know how to get e.g. date specific items.

**Comment by rijkvanzanten** [comment]
Yeah. The current implementation works by allowing the layouts to set the viewQuery after it has been loaded as an event. That allows the tabular one to change the sort order for example. While it technically works, I'm not a 100% happy with the syntax / internal API yet..

**Comment by Nitwel** [comment]
So should I implement it like on the image, or do you want to have something changed? @benhaynes

**Comment by benhaynes** [comment]
My thoughts:

* I think the main thing to focus on is how we're loading data (I believe you and Rijk had a conversation about that on Slack). If that needs an App refactor first then I think what you have here is the best we can do _for now_. 
* In my opinion we should only fetch the items that are in the map viewport. That way if there are 5,000 items but only 100 in your lat/lon map bounds then you would still see everything.
* For the "double sidebar", this will be fixed in 7.1 (coming out in a few weeks) since our right info sidebar will allow for multiple components. In the meantime we can leave it, or move the "Locations" into the main Info Sidebar.
* Similar to calendar, it would be nice to allow each location to have its own color... or a global setting to change which icon to use as a marker.

**Comment by Nitwel** [comment]
> I think the main thing to focus on is how we're loading data (I believe you and Rijk had a conversation about that on Slack). If that needs an App refactor first then I think what you have here is the best we can do for now.

👍

>In my opinion we should only fetch the items that are in the map viewport. That way if there are 5,000 items but only 100 in your lat/lon map bounds then you would still see everything.

Definetly

 > For the "double sidebar", this will be fixed in 7.1 (coming out in a few weeks) since our right info sidebar will allow for multiple components. In the meantime we can leave it, or move the "Locations" into the main Info Sidebar.

Could also be done but a problem I see is that it might be confusing to see all locations there.

> Similar to calendar, it would be nice to allow each location to have its own color... or a global setting to change which icon to use as a marker.

Definetly will add that ^^

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
