### ISSUE TITLE
Layout: Diagram

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1227]
### The concept
The layout/idea would display data in relation to dates numbers or so on.
Ideas to it:
- supporting not only interfaces with numbers but also time or such. (The more the better)
- the abitily to change between multiple diagram types like: bar chart, area chart or cake chart
- more to add...

### Heres a first inspiration of it:
![layout chart](https://user-images.githubusercontent.com/22577866/50573413-bd7f2e00-0dd3-11e9-8045-10be08bb7947.png)

**Comment by benhaynes** [comment]
Yes! 💯

This would be such an easy one to create (in its basic form). I had a similar mockup from before (see below) and was thinking of starting with these options:

* `type` (`line`)
* `y-axis` (accepts `number` fields)
    * I was thinking that it'd be nice to have "functions" for these, so you could do a SUM, COUNT, MAX, MIN, AVG, etc of datasets. But that is more complex.
* `x-axis` (accepts `datetime` or `date` fields)
    * I can't think of a good use-case for a non-date X axis but we should support others anyway

That is the simplest MVP I can think of... then we can extend things form there. Like:

* Color
* Multiple datasets
* More chart types
* Maybe a JSON field for pasting in styling options for whatever the library uses

![directus 7 chart](https://user-images.githubusercontent.com/522079/50574002-dde7c200-0dac-11e9-8577-9592cb0c71d7.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
