### ISSUE TITLE
Add raw-html support to advanced WYSIWYG

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1230]
# Feature Request

In order to be able to edit the content in an advanced way, the user should be able to edit the raw HTML content of the field.

## What problem does this feature solve?

Advanced users should be able to edit the HTML to be able to add custom markup and attributes.

## How do you think this should be implemented?

There should be an additional button available on the toolbar:

The authors of QuillJS decided to basically ignore this feature: https://github.com/quilljs/quill/issues/128. However, someone hacked together a solution that seems to work https://codepen.io/anon/pen/ZyEjrQ

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/app/issues/1234

**Comment by Szymon-dziewonski** [comment]
does anyone thought about bring this feature to WYSIWYG? It's shame there is no source mode inside quill, actually this is pretty basic editor without many options, such as 

- font-size dropdown, 
- change between creating multiple lines of same selector 
`<p>first line</p><p>second line</p>`
to 
`<p>first line<br/>second line</p>` 
- add button with custom element e.g. `<my-custom-selector></...>`
- for directus itself some global settings for configuration advances WYSIWYG

Cheers

**Comment by benhaynes** [comment]
Hey @Szymon-dziewonski — we are almost done with a new WYSIWYG editor that has this feature. It should be included in the next release. 😄

**Comment by cdwmhcc** [comment]
> Hey @Szymon-dziewonski — we are almost done with a new WYSIWYG editor that has this feature. It should be included in the next release. 😄

Expectation, editors are hard to use now

**Comment by bskimball** [comment]
Did this happen yet?

**Comment by benhaynes** [comment]
The new WYSIWYG is on hold during our feature freeze while we close bugs.

**Comment by bskimball** [comment]
Cool. Thanks for the response. The CMS is awesome btw (I just started testing it out)
