### ISSUE TITLE
Translation do not show saved input to edit

### ISSUE THREAD

**Issue by creazy231** [directus/app#1231]
# Bug Report

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/13473174/50695146-1f41d100-103c-11e9-8836-9ffe461f2ef8.png)
![image](https://user-images.githubusercontent.com/13473174/50695170-341e6480-103c-11e9-8a2f-febe076f556e.png)
![image](https://user-images.githubusercontent.com/13473174/50695190-47313480-103c-11e9-8166-64e202f6b694.png)
![image](https://user-images.githubusercontent.com/13473174/50695520-37662000-103d-11e9-9065-bd4fddb657f9.png)
![image](https://user-images.githubusercontent.com/13473174/50695545-464cd280-103d-11e9-9195-1ed9d5b6713d.png)

Set up the project like you can see on the screenshots.

## Expected Behavior
Be able to save and **edit** text like usually.

## Actual Behavior
I'm able to save the text but when I want to edit the text I saved, the saved text doesn't show up. I can just add new Text.

## Other Context & Screenshots
The documentation about how to implement translations isn't clear.
If the problem causes I've done mistakes, a step by step guide would be awesome.

## Technical Details

- Device: Desktop
- OS: MacOS
- Web Server: MAMPP
- PHP Version: 7.2.10
- Database: MySQL
- Install Method: master manually config

**Comment by rijkvanzanten** [comment]
@WellingGuzman I think something goes wrong when the type of primary key is a string. It seems that the API stops returning nested values when the type of the primary key field is string.

**Comment by honzabilek4** [comment]
Hi, I'm facing the same issue. With the translations not working. I suspect the app behaviour, because calling the api directly updates the translations correctly. Let me investigate this issue further.

**Comment by honzabilek4** [comment]
Generally, there's multiple issues with this interface.
- Pressing `cmd+s` clears the translation fields, so they're empty after the save.
- the **PATCH** request after update contains the same field multiple times but on different nesting levels. Personally I believe that this is the source of the issue.
I've tried to send some direct requests to the API using Postman only. This is an example of the request body which is being sent from the app:
```json
{
    "translations": [
        {
            "id": 1,
            "dictionary_id": {
                "id": 1,
                "api_name": "back",
                "translations": [
                    {
                        "id": 1,
                        "dictionary_id": 1,
                        "language_code": "en",
                        "label": "back"
                    },
                    {
                        "id": 2,
                        "dictionary_id": 1,
                        "language_code": "cs",
                        "label": "zpět"
                    }
                ]
            },
            "language_code": "en",
            "label": "back >"
        },
        {
            "id": 2,
            "dictionary_id": {
                "id": 1,
                "api_name": "back",
                "translations": [
                    {
                        "id": 1,
                        "dictionary_id": 1,
                        "language_code": "en",
                        "label": "back"
                    },
                    {
                        "id": 2,
                        "dictionary_id": 1,
                        "language_code": "cs",
                        "label": "zpět"
                    }
                ]
            },
            "language_code": "cs",
            "label": "zpět >"
        }
    ]
}
```
 - There are two languages `cs` and `en`, where cs is primary. In this request i've edited `zpět` to `zpět>` and `back` to `back>`. As a result only the cs version is being updated. 
- Editing only the en version does not have any effect.

Getting rid of the `dictionary_id` the **PATCH** requests work as expected:
```json
{
    "translations": [
        {
            "id": 1,
            "language_code": "en",
            "label": "back >"
        },
        {
            "id": 2,
            "language_code": "cs",
            "label": "zpět >"
        }
    ]
}
```
I'm willing help with this, though I think we need to agree on some solution first.
