### ISSUE TITLE
Discuss changing out Quill.js

### ISSUE THREAD

**Issue by devninjajeremy** [directus/app#1234]
Is it me or does it seem like the WYSIWYG functionality has gone backwards? Moving to the QuillJS plugin I think was a mistake. Im on the latest version and I've been pulling my hair out for a few days because I absolutely have to have a table option in the wysiwyg. My Client requires it. The older version that they were running was fine. But i've been implementing the new version 7 api and everything is running so much better, they like it much better but the table issue is almost a deal breaker. Is there anyway we can add the ability to have tables in the editor and a code view like it use to have? The code view now requires you to stay in code view. The older one you could view the source, write some custom html and go back to the default view and see the changes. The client loved that. I dunno why functionality would go backwards. Am i just missing something here?

**Comment by sneakersgames** [comment]
May I suggest [Froala](https://github.com/froala/wysiwyg-editor)? Has a VueJS extension too.

**Comment by benhaynes** [comment]
Thanks @sneakersgames — we've looked into Froala in the past but it has a paid license. We need a library that is open-source —and allows us to use it within our OSS version and Cloud SaaS.

**Comment by shealavington** [comment]
If the core editor is changed, I also suggest keeping Quill available as an extension, then there's choices for what editor is used, as all editors would have the same output. :smile:  :+1:

**Comment by paulagnivo** [comment]
When the JSON config is changed while inserting a WYSIWYG field, the interface produces some kind of runtime error. I am unable to find a way to insert images in the editor.

**Comment by benhaynes** [comment]
That sounds like a different bug, @paulagnivo. Maybe open a new ticket for this so we can track/resolve it?

**Comment by Joshua-Sherer-Bose** [comment]
> I absolutely have to have a table option in the wysiwyg. My Client requires it.

FWIW we've been developing on 6.4 for the same reason and are looking forward to migrating to 7 when possible.

> If you have a recommendation for a better open-source WYSIWYG library we'll certainly take a look!

A markdown editor / preview like this, especially with diagram / chart rendering, emoji / icon integration would be amazing.
http://mdp.tylingsoft.com/

**Comment by devninjajeremy** [comment]
https://summernote.org/

**Comment by benhaynes** [comment]
Thanks @Joshua-Sherer-Bose  and @devninjajeremy — I think the best way to move forward with this would be to have 2 Core WYSIWYG editors (inline/advanced) and build as many _extension_ WYSIWYG interfaces as possible (for each recommended library). That way we can have premium, proprietary, and large (dependencies+filesize) options available without having to compromise the Core platform.

We only have a small group of Core/Contributor devs, so extensions often get put on the back-burner — but I'll consider sponsoring a few contractors to get this expedited. That is, unless someone here wants to [try their hand at a PR](https://docs.directus.io/extensions/interfaces.html). 😉

**Comment by benhaynes** [comment]
Some options... (feel free to add more)

* https://www.tiny.cloud/docs/integrations/vue/
* https://www.froala.com/wysiwyg-editor/pricing (we could potentially invest in buying a license for this)
* https://alex-d.github.io/Trumbowyg/

**Comment by ceruulean** [comment]
What do you think about Trumbowyg? It seems the best but it has a jQuery dependency (yet another library). Author said he is working on removing it: https://github.com/Alex-D/Trumbowyg/issues/875

Could wait until the rewrite is done?

**Comment by benhaynes** [comment]
I think that's a good option @ceruulean — and we'd be willing to wait/donate. I think the main thing is that we need to be able to upload files to Directus and then use that link (not just base64) but I think that is a plugin already. 

Since these are all existing libraries (and therefore easy to turn into interfaces), I think the best thing to do is to create them all in Directus and then have the community vote on which should be in Core versus remain extensions.

**Comment by dbrw** [comment]
How about tiptap?
https://tiptap.scrumpy.io/

**Comment by benhaynes** [comment]
Thanks @dbrw — the more options the better!

**Comment by Nitwel** [comment]
Running in simular issues at the moment. Not that extreme but the access to a table would be realy helpfull for me.

**Comment by rijkvanzanten** [comment]
So we all agree that the two features (that are missing now) that are an absolute must have are 

Tables & Editing the HTML output

**Comment by benhaynes** [comment]
Correct. We should have a FULL editor that has everything, including those two options. And then a more lightweight editor (like Medium) that is more properly named/labeled so people understand how it works. 

After that, I still think we should create extensions for ALL OTHER WYSIWYG libraries. That way people have as many options as possible — but they don't busy up the core codebase.

**Would anyone here be up to creating some quick extensions for the other editors mentioned here?**

**Comment by benhaynes** [comment]
Oh, and anything in the Core codebase needs to have the proper OSS license 😉

**Comment by statler** [comment]
Why not CKEditor5? It is a bitch to set up properly (custom editors and plugins everywhere) but is great when you do.

The table plugin works OK, but the font plugin sux if you need to read externally created HTML (it ignores it)

**Comment by benhaynes** [comment]
Seems like another good one. As I mentioned before, while our internal team is a bit busy at the moment, we would accept any and all WYSIWYG editors. We'll choose the 1-2 of the best for in Core and will offer all others as extension interfaces that anyone can use.

**Comment by dev7ch** [comment]
https://github.com/summernote/summernote ... by including the word "super simple" i just giot this from the web

**Comment by dev7ch** [comment]
http://prosemirror.net/

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/53444423-67fb8200-3a0e-11e9-85f6-e50329cd2feb.png)

i tested a quick implementation of https://tiptap.scrumpy.io/ (with is build on http://prosemirror.net/) but i saw that the whole editor is inside a `<p>` tag ... is this on purpose?

coz i think it leads into invalid html markup

**Comment by dev7ch** [comment]
@rijkvanzanten and @benhaynes here you can see a basic implementation

https://github.com/dev7ch/api/tree/wysiwig-replace

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/53495224-c9b7fc80-3a9f-11e9-8892-871811996026.png)

**Comment by gitlabisbetterthangithub** [comment]
@dev7ch Will your replacement have similar features to TinyMCE. I mainly need the ability to do image borders, pull quotes and add html snippets/templates that the user can choose.

**Comment by dev7ch** [comment]
i think all the features could rebuild and implemented.

https://prosemirror.net/

@gitlabisbetterthangithub what do youo mean with "...and add html snippets/templates"

**Comment by ceruulean** [comment]
Probably "view raw HTML" option? Since that is the must have for QuillJS replacement

**Comment by dev7ch** [comment]
yes, you can switch between raw html and editor.
you cold test it locally `git clone -b wysiwig-replace git@github.com:dev7ch/api.git`

**Comment by gitlabisbetterthangithub** [comment]
@dev7ch The ability to view and edit the raw HTML generated by the editor would be nice but I am referring to actual templates that the user can insert.

Most of the editors suggested here have this functionality, either builtin or as a plugin.

See https://www.tiny.cloud/docs/plugins/template/#makingtemplates and https://www.tiny.cloud/docs/plugins/template/#makingsnippets

A demo of templates in Trumbowyg
https://alex-d.github.io/Trumbowyg/demos/#plugins-template

Froala Editor
https://www.froala.com/wysiwyg-editor/examples/insert-html

Would this be possible in your editor? ProseMirror list it as a feature

**Comment by gitlabisbetterthangithub** [comment]
> Some options... (feel free to add more)
> 
> * https://www.tiny.cloud/docs/integrations/vue/
> * https://www.froala.com/wysiwyg-editor/pricing (we could potentially invest in buying a license for this)
> * https://alex-d.github.io/Trumbowyg/

@benhaynes Froala Editor FAQ says it can't be used in open source projects. I assume it means that you can't buy a license for the open source project. But I would imagine that you could purchase a license and use it in Directus Cloud.

It also looks like Froala requires jQuery but they are in progress at removing it.

**Comment by benhaynes** [comment]
Hey @gitlabisbetterthangithub — that is true, we could probably use Froala in Cloud if it was a significantly better editor. We could build it as a none-core extension first to try out.

**Comment by dev7ch** [comment]
Thabks for explabation.. Yes froala looks nice, but from dev side i would avoid usieing nit OSS, i haven't used much wysiwyg editor.. But i assume the ablitity to add templates could be implemented to tip tap with less effort... Technically its just get the courser position and paste an predefined html template... As usual not tested:)... But itsbsically the same what is happening if you add a table (if i got u right)

**Comment by felskov** [comment]
@benhaynes Just thought I'd chime in... I've used Froala on multiple occasions, and it's certainly one of the nicest editors I've worked with. As a developer, I've been happy with their support, and my clients have been more than happy with the editor itself.

I think that considering how important the editor is to Directus, it might be worth it to invest in a license, although I realised that you might have other concerns about implementing a proprietary editor.

**Comment by rijkvanzanten** [comment]
> I think that considering how important the editor is to Directus, it might be worth it to invest in a license, although I realised that you might have other concerns about implementing a proprietary editor.

We're not allowed to include the editor in an open source project:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/9141017/55632841-1969a200-5789-11e9-8aa5-d7e22f49931c.png">

**Comment by felskov** [comment]
@rijkvanzanten I reached out to Froala, asking about the reasons why they're enforcing this. What they're saying is that they have no problem with their editor being used in open source projects, but they don't want to create a single license with a wildcard activation key.

> Indeed, we don't allow usage of an editor license in Open Source because we are trying to prevent piracy, and this would basically mean making a wildcard activation key public.

But it would be possible to create an interface that uses the Froala editor, but requires administrators to upload their own license key to activate the editor. I realise that this might not be a core feature, but perhaps a plugin could be created, allowing people who aren't satisfied with Quill.js (and who are willing to purchase a license) to create fields using the Froala editor instead?

> The alternative to this is to have an integration / plugin made for Froala and Directus - no license required for Directus. This way, people that have a Froala Editor license will be able to use our editor in Directus.
>
> We don't have anyone familiar with Directus on our team, but this is the approach we have with other CMSs as well. Do you think it's something that can be done for Directus?

**Comment by dev7ch** [comment]
A custom extension could be done where user purchase a license but i hardly guess froala only have a nice surface. Actually i stopped reading about this editor as i saw "jQuery" and not open source

**Comment by felskov** [comment]
@dev7ch There probably is... :-)

I agree that jQuery is a con when using Froala, but it's still one of the nicest editors that I've worked with (and the one that my clients' tend to be happiest working with). In my eyes it's a bit more than just a nice surface, they've tried hard to make the whole experience of creating content quite pleasant.

Anyway - my biggest issue with Quill.js is the missing table support (which is crucial to a lot of websites I'm building), and also it'd be nice with a code view / editor. Those features could be provided by a number of open sourced editors that's probably more suited for Directus in general.

Still, I'd love to see a Froala plugin down the line :-)

**Comment by dev7ch** [comment]
Yes, love is a "thing" what we need in live :) ... maybe to start developing a custom Directus extension ;)

i had an other quick look to there GitHub page and saw FontAwesome is a decency as well which would overhaul imo the core as well.

- regarding the table support I think tiptap editor works nice (e.g. https://tiptap.scrumpy.io/tables)
- as Froala touches the heart of many I think it would be a great example to showcase how to develop a custom extension

**Comment by dev7ch** [comment]
Yes, love is a "thing" what we need in life :) ...

i had an other quick look to there GitHub page and saw FontAwesome is a decency as well which would overhaul imo the core as well.

- regarding the table support I think tiptap editor works nice

**Comment by felskov** [comment]
@dev7ch I've already read up on the docs, and I might create a custom interface that uses Froala. Is there any place to publish the plugin in case it's something I move forwards with, in case others would like to use that editor as well?

We could technically disable use of the FontAwesome plugin in the Froala editor, if it's a major inconvenience to the rest of the Directus core. At least it's not an important feature to me :-)

**Comment by dev7ch** [comment]
cool ! actually I think @benhaynes or @rijkvanzanten could answer where finally to put this in public, but for beginning I think simply your git repo works fine.

here is a Directus demo of tip tap https://wysiwyg-replacement--blissful-curie-6231b9.netlify.com/

**Comment by benhaynes** [comment]
Hey @felskov — I have no problem with Froala, and we'll likely build a "premium" custom extension for it. But, @dev7ch is working on a PR (see above) that should solve most WYSIWYG issues and _is_ open-source friendly. 

I would say if anyone wants/needs a custom Froala interface in the next few months it would be a community endeavor. @rijkvanzanten can confirm, but I believe that each custom (not in core) extension will be its own GitHub repo. We'll tweak the structure and naming convention later, but any PRs should be self-contained for now.

**Comment by rijkvanzanten** [comment]
@felskov Thanks for reaching out to them 🙂 While the editor looks great, it's not the greatest UI to require the user to buy a license before they can use the editor, so we won't be using it as _the_ core WYSIWYG editor. That being said, it can totally be a custom extension with an option to add your license key.

I actually just published an extension toolkit that should make it a little bit easier to get started with your own custom interface 😄 It's a bit rough still, but if you'd like to give it a shot, you can checkout [the extension toolkit](https://github.com/directus/extension-toolkit).

> as Froala touches the heart of many I think it would be a great example to showcase how to develop a custom extension

Yes!


For now, I think we're moving forward with making TipTap the core (full) WYSIWYG and having Froala as a custom extension that people can download and use separately. Seeing that the Froala one is not going to be in core and it's only for a limited amount of users, I don't think I can justify the time investment at this point... (I only have so many hours a week) Would you like to take that up @felskov?? I can set you up with a repo in the Directus organization 🙂

**Comment by dbrw** [comment]
I hope I heard about https://github.com/codex-team/editor.js earlier than I suggesting tip tap.

At least I will put the link here so we can also have more options in future.

**Comment by dev7ch** [comment]
@dbrw yes a saw this editor as well and it looks like a promising concept and very clean code repo.
But i assume some must-haves (e.g. table) are currently in beta.

**Comment by benhaynes** [comment]
@dbrw — I like the agnostic approach of saving as JSON! I would be very interested in having this editor in Directus (maybe an extension). We can look into adding it, but it would be faster to have this be developed by the community (we're swamped with a large refactor right now).

**Comment by dev7ch** [comment]
tip tap is offering this options as well as far I see on the demo https://tiptap.scrumpy.io/export

**Comment by emendo-web** [comment]
Hello everyone,

We have just discovered your software. We really appreciate the Directus approach and the quality of the dev. We think to use it for our customers (App and websites).
Today, we work with rails and vuejs to create a similar env than directus.

Our customers like to create various content (link with select choice of collections items, pdf files to download, videos, table, images gallery, ...). 
Is this plan with the advanced wysiwyg field ? 

We also use Tiptap for our vuejs project. Great plugin ! His modular approach is interesting to extend functionalities. May you let a open door to extend your tiptap implementation ? (like custom pages or hook)

Regards,
Deniz

**Comment by benhaynes** [comment]
Thank you!

I believe most, if not all, of those features are planned for the advanced WYSIWYG editor.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dur41d** [comment]
It's not clear what's the outcome of marking this issue as **Done**.

**Comment by rijkvanzanten** [comment]
@dur41d It means that Quill.js was changed out for a better alternative (TinyMCE)

**Comment by dev7ch** [comment]
yes, Quill was sadly not replaced by vue js tiptap editor (which was the idea, plan here before), the outcome for us was to use a fork of directus. If anyone is interested here it a repo with the tip tap integration https://github.com/dev7ch/app/tree/prod-v8

**Comment by benhaynes** [comment]
@dev7ch — why a fork? Why not just make a TipTap Interface extension so it's more modular, and allows you to stay on the main repo? 😕

**Comment by dev7ch** [comment]
@benhaynes well, actually, we use tip tap with directus since about one year and we hoped it will go to the core.

I did not have time to rewrite this as an extension...

what time do you think is needed for you to build  an extension from the working tiptap directus integration?

I am still open to do it but i am kinda overloaded unti mid of 2020 probably ... 

Did you tried to make an extension from it? if not do you have an good example extension?

**Comment by dev7ch** [comment]
and yes, as this editor is kind of advanced and contains a lot of code an extension would be best way to go imo too

**Comment by benhaynes** [comment]
We decided to go with TinyMCE because we only want _one_ core WYSIWYG to avoid confusion... and it is had advanced options we required. TipTap was missing some of the power-user features we needed included.

As for Core vs Extension... I believe the only difference is which directory it's stored in (and that Core interfaces ship with the Suite). So no refactor is needed. @rijkvanzanten correct me if I'm wrong.

**Comment by rijkvanzanten** [comment]
That's correct

**Comment by dev7ch** [comment]
ok, proposal:
- please create a repo as you desire a proper extension, best starting from your https://github.com/directus/extension-toolkit 
- just put the tiptap editor inside (if its working would be nice)
- share this repo with me on slack and tell me what the " some of the power-user features" are
- I will fix and finalize everything so everybody can use it with directus additionally easy
- i can promise maintaining it

**Comment by rijkvanzanten** [comment]
The steps sound good, but I don't know what you mean by

 > as you desire a proper extension

I don't desire anything 🤷‍♂ 

All we're saying above is that it's unnecessary to maintain a fork of Directus just to have a custom interface, as that's what custom interface extensions are for.

We chose to go with TinyMCE over TipTap for the core interface as it's a more robust and full featured alternative, with nearly no maintenance overhead compared to TipTap. If you want to offer others the ability to use TipTap, that's totally cool, but I don't have the resources or desire to set it up right now, seeing that TinyMCE offers everything that TipTap does and more.

**Comment by dev7ch** [comment]
> I don't desire anything 🤷‍♂ 
i thought if ts close to copy and paste as said above you could just give me a good starting point with less effort
