### ISSUE TITLE
Checkbox interface bad output

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1235]
Still have such issue when using checkbox interface and modified json value. I am using the latest api. If the json value is modified in options, the display is messed up. I checked the database and find that the json value seems to be escaped when save to database. The value in the database looks like:

{"choices":"{\n "value1": "vvv",\n "value2": "Option 2",\n "value3": "Option 3"\n}","wrap":true,"formatting":true}

By the way, I am using the docker running Directus.

Ref: https://github.com/directus/app/issues/1216

@KKAries

**Comment by rijkvanzanten** [comment]
I don't have this same issue on `master`

<img width="620" alt="image" src="https://user-images.githubusercontent.com/9141017/50858763-57f4e980-135f-11e9-835c-d69f07162692.png">

On what version of the API are you?

**Comment by KKAries** [comment]
I am using the latest docker image of directus/api. I thinks it is 2.0.13. The output is good when I use the build branch on Git but it is messed when I use the docker image of api and app.

**Comment by benhaynes** [comment]
Any chance this is a Docker specific issue @WoLfulus ?

**Comment by KKAries** [comment]
Using new docker image 2.0.15 seems work properly.
