### ISSUE TITLE
Save notification shows template

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1238]
Saving an item gives a notification with a templating string:

![screen shot 2019-01-09 at 9 08 10 pm](https://user-images.githubusercontent.com/522079/50973894-06ac3d80-14b8-11e9-9f3e-7ef59eaa5d61.png)

This was on `7.0.10`... maybe it's been fixed? I was on @nitwel calendar instance, I'll confirm on a new one but didn't want to forget.

**Comment by Nitwel** [comment]
I think I still use v7.0.10 so /close I guess XD

**Comment by rijkvanzanten** [comment]
Pretty sure this isn't an issue (anymore) in the latest version 😄 

<img width="331" alt="image" src="https://user-images.githubusercontent.com/9141017/51047594-ea330280-1596-11e9-8ba2-1103a898e8ba.png">

**Comment by rijkvanzanten** [comment]
Also make sure to use `this.$tc("item_saved")` instead of `this.$t("item_saved")` @Nitwel 🙂

**Comment by Nitwel** [comment]
I know that $t accesses translations but what does $tc do? 😁

**Comment by rijkvanzanten** [comment]
`$tc` is for translations that have a count. You can use `this.$tc("item_saved", { count: 5 })` and it will return "5 Items Saved"

**Comment by rijkvanzanten** [comment]
https://kazupon.github.io/vue-i18n/guide/pluralization.html

**Comment by Nitwel** [comment]
Ah, ok. Good to know. ^^
