### ISSUE TITLE
Multiple Toggle Items, toggles only first item

### ISSUE THREAD

**Issue by DeHekOnline** [directus/app#1239]
# Bug Report

## Steps to Reproduce

While having multiple toggle icons in a collection. When you try to toggle the second icon, the first item toggles.

**Comment by rijkvanzanten** [comment]
On what browser is this? I just tried this on the live demo and it seems to work as expected for me.

**Comment by shealavington** [comment]
What version of the app is this? This may be the issue where if you have two values of the same, it toggled the first item in the dom as there was no item scoping, which I believe was fixed?..

Ref: https://github.com/directus/app/issues/1219
