### ISSUE TITLE
Missing CSS Files for Extensions — 404

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1242]
## Extensions Missing CSS File Throw 404

Each interface is split up into an `interface.js` file and an `interface.css` file. However, extensions without a `<style>` tag don't have a `interface.css` file generated which causes the 404 in the browser. One potential solution is to give all extensions an _empty_ CSS file.

While we are working on a topical fix for this (to clean up the console), it is not an issue and should not be reported.

### Example
```
load-extension.js:41 GET ..../extensions/core/listings/tabular/listing.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/primary-key/readonly.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/text-input/readonly.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/numeric/readonly.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/sort/readonly.css 404 ()
```

**Comment by Nitwel** [comment]
Would it not be better to just check if the file exists and when not, igonre it?

**Comment by benhaynes** [comment]
I think that's the problem, that Aoo fetches these from the API and doesn't know which are missing. Is that right @rijkvanzanten?

**Comment by benhaynes** [comment]
Maybe `meta.json` could have a flag for `no-css`?

**Comment by rijkvanzanten** [comment]
@benhaynes hmm that's technically possible, but is also super annoying to maintain... I'm thinking of working on the build chain for the interfaces so it will bundle the CSS in the JS as well, so we only have to request 1 file. It will speed up loading a little bit cause we half the amount of requests and it won't error out if there's no CSS.

**Comment by benhaynes** [comment]
Oh, I like that too! Would the bundled CSS still be editable in the file (like Vue's single file components) or is it more of a minified build/dist file that isn't edited directly?

**Comment by rijkvanzanten** [comment]
The source code doesn't change, this is just the output file

**Comment by dev7ch** [comment]
This case was explored a bit by me and did some test locally, I tried a few different approaches, but didn't found a nice one, e.g.

- test via xhr request if file exists (but its more a workaround than a proper solution, whith `Access-Control-Allow-Origin` in api configs)
- try it with axios a few minutes
- i didn't try out to catch the public api response (just an idea)

I think its the issue ( as said before) that the browser console always display a 404 if there is one, 
Even when i was able to catch the error, the console error persists (yes, you could suppress it by force override console output, but it is not nice).

I think a proper solution would be a chaining mechanism as @rijkvanzanten mentioned, 
- e.g. where you build (or precompile) an array with all existing styles urls or one styles file.

I am not sure if i see correct, but is main the Goals to keep the field admin styles editable from api @benhaynes ?

**Comment by dev7ch** [comment]
maybe useful https://stackoverflow.com/questions/19076652/check-if-a-file-exists-async

**Comment by benhaynes** [comment]
Thanks @dev7ch — this is super insightful. I defer to @rijkvanzanten on the ultimate goal from a dev perspective. However we get a lot of bug tickets raised regarding the 404s so my main concern is people not thinking the platform is broken when looking at the console. :)

@rijkvanzanten — care to elaborate?

**Comment by rijkvanzanten** [comment]
> that the browser console always display a 404 if there is one

This is the issue.

The two links you shared are cool, but not something that would be applicable to the directus application I'm afraid. 

> e.g. where you build (or precompile) an array with all existing styles urls or one styles file.

This could work, but it would require the app to do pretty extensive checks before we're able to fetch the files. 

I still think the easiest fix would be to compile both the CSS and JS into one .js file by swapping out  the Prettier setup to a Webpack based one, as Prettier currently doesn't support bundling the styles into the output bundle.

**Comment by dev7ch** [comment]
@benhaynes  and @rijkvanzanten a created a small hacky workaround with some issue but i seems like there have been elimated a lot of errors by check via xhr the status of the requested remote style file.

;)

**Comment by dev7ch** [comment]
Maybe this can be a art time solution for you if you like it.

Due if I'm going to use Directus in the next time more and my dev console is almost always open is just needed to find a workaround to get rid of red logs 😄 

Cheers and thank you for making such cool Open Source Project 🎉

**Comment by benhaynes** [comment]
Thanks again @dev7ch — we'll be going through this asap... our Cloud build has been takin a while so it's slowing down Core development. We really appreciate all this help though!
