### ISSUE TITLE
UX improvement - Change icon for deleting an item

### ISSUE THREAD

**Issue by ondrakoupil** [directus/app#1243]
# Feature Request
Two of my app's users accidentally deleted an item by mistaking the red button with cross icon in top right corner when editing an item - they expected that button to mean "close without saving" and not "delete this item". There is a confirm dialog, which is however visually very similar to the dialog "do you want to leave without saving", so they just clicked the confirm button. I literally watched them over their shoulder - they didn't even stop to think what the button does.
So I suggest to change that "cross" icon to a "trash can" icon, which gives better idea about what the button means.
I understand two users are not a big testing audience, however it revealed a potential problem.

## What problem does this feature solve?
It is just an UX improvement. It may save many unintentional mistakes for inexperienced directus users.

## How do you think this should be implemented?
Icon for deleting should be distinguishable at first sight. I suggest using a "trash can" shape (material icons code "delete") instead of cross (material icons code "close"). Cross has generally wider use, not only for deleting.

## Would you be willing to work on this?
Somehow yes, however this is so trivial task that I believe the work required for me (as a directus newbie) to dive into the project and understand the code would be much greater than for a developer who already has the required experience.

**Comment by shealavington** [comment]
I concur, multiple times myself and colleagues have also have forgotten that it's a delete button, thankfully without deleting the content due to the popup.

Looking at the app as a content manager rather than a database, I would expect a "Save" and "Close" button as the primary actions and a delete button without a colour and a little recessed, so it's still available, but not "promoted" as an action.

Perhaps this is a #1236 (7.1) enhancement @benhaynes? :smiley:

**Comment by benhaynes** [comment]
Thanks for the feedback! I have updated the 7.1 design to use the trash can icon to clarify this. The Material Design icon set also has three icons for trash, so we'll have the added benefit of showing when it's soft vs hard delete. The new design also has a clearer "back" button.

Thoughts on if this new design seems like it would solve your team's issues?

![directus 8 detail](https://user-images.githubusercontent.com/522079/51045747-58c19180-1592-11e9-80f4-022243002f98.png)

**Comment by rijkvanzanten** [comment]
For now, this should clear things up a little 😄 

<img width="210" alt="image" src="https://user-images.githubusercontent.com/9141017/51046722-d38bac00-1594-11e9-9494-f255bb530040.png">

**Comment by benhaynes** [comment]
Good point @shealavington — I'll look into a new placement. We have a pretty strict design system that has all action buttons in one place, and the "back" arrow makes the most sense near the breadcrumb and other navigation items. Still, let me see what I can do!
