### ISSUE TITLE
Add new "app_url" option to Installation

### ISSUE THREAD

**Issue by wellingguzman** [directus/app#1248]
There's a new option named `app_url` used to determine what's the Application URL.

Implemented here: https://github.com/directus/api/commit/784f8f3774ef884fa3ed2155d78652f7104157ba fixing this issue: https://github.com/directus/api/issues/609.

**Comment by gagandeepp** [comment]
Hi @WellingGuzman Why this is still open?? It has still been fixed by this  directus/api#609.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
