### ISSUE TITLE
Navigation Override Option to Customize Sidebar

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#125]

**Comment by rijkvanzanten** [comment]
DIdn't know I would say this, but it should be a little more WordPress menu creator style

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/app/issues/456

**Comment by benhaynes** [comment]
I'm fine with JSOn for now, but here are the things we want to support:

* Shorthand for keeping dynamic sections (Collections, Pages, etc)
* Linking to other internal pages (such as specific Item Detail)
* Grouping (uses standard sidebar headers/labels)
* External/custom links
* Maaaaaybe nesting (I'm not sure about this one)

So, the example below has custom collections listed in a custom order, then has a _second_ group of other collections. There are also links to individual Item Details and external links. The Bookmarks have a `true` value, so those load the default values... but the order has been reversed (bookmarks _before_ extensions).

```
{
    "Collections": {
        "Z. Collection Name": "/collections/collection-name",
        "X. Collection Name": "/collections/collection-name",
        "Y. Collection Name": "/collections/collection-name",
        "Specific Item Name": "/collections/collection-name/123",
        "External Link": "https://example.com"
    },
    "Another Group": {
        "A. Collection Name": "/collections/collection-name",
        "B. Collection Name": "/collections/collection-name",
        "C. Collection Name": "/collections/collection-name"
    },
    "Bookmarks": true,
    "Extensions": true
}
```

**Comment by rijkvanzanten** [comment]
Lets use `$bookmarks` instead of "Bookmarks", otherwise there's no way to tell what are the system groups vs the user group names, and lets use it as value instead of title, so you can override the group names as well 🙂 

```json
{
    "Collections": {
        "Z. Collection Name": "/collections/collection-name",
        "X. Collection Name": "/collections/collection-name",
        "Y. Collection Name": "/collections/collection-name",
        "Specific Item Name": "/collections/collection-name/123",
        "External Link": "https://example.com"
    },
    "Another Group": {
        "A. Collection Name": "/collections/collection-name",
        "B. Collection Name": "/collections/collection-name",
        "C. Collection Name": "/collections/collection-name"
    },
    "Favorites": "$bookmarks",
    "X-tension": "$extensions"
}
```

**Comment by andreekeberg** [comment]
Sorry, maybe it's just that I don't understand, but is there a way right now to reorder collections in the sidebar? Where would edit a JSON structure in that case? Or is this just how you would like this future feature to work when it's released?

**Comment by benhaynes** [comment]
This is just how it _will_ work... we'd love to work on this, but have a huge amount of work to do so it's still on the backburner. If anyone wants to take on a PR that'd be awesome!

**Comment by benhaynes** [comment]
Things to consider in the new structure: 

1. Will we label grouped nav items?
1. Will we allow nested items? How deep?
1. Will we allow collapse/expand of grouped or nested items?
1. We can remove `extensions: true` since that will be a different module

**Comment by luxlogica** [comment]
It seems from this thread that there are NO plans to make it possible to reorder sidebar items in v7, and that we should wait until v8. Is this correct?

IMHO, there will *always* be more pressing issues, that should take priority - but that doesn't mean that issues like this should be pushed aside. This is not a 'minor inconvenience': this is a BASIC feature of any system-building tool (being able to control the presentation of the interface we're building) and not having such essential functionality makes Directus look hacked and unpolished (which it's NOT). 

The fact is, that users are 'working around' this in several ways — e.g., by starting names with numbers (so they can arbitrarily place items in specific places when created later on). That doesn't mean that this is one of the 'lesser wanted' features, but rather, that people are learning to "live with it" (which is not a good thing). 

Perhaps what is hindering the implementation is the fact that there is a long list of 'wanted' features attached to it: grouping, nesting, arbitrary label overrides, even total re-formatting of the interface. All of those features are 'nice', but they're 'extras': what is needed urgently atm is SIMPLE REORDERING. If we could just have that, it would already be a 1000% improvement. Everything else would be icing on the cake.

So Directus Gods, please if at all possible, reconsider adding this at some point to v7 - many of us would be very, very grateful.

**Comment by rijkvanzanten** [comment]
> It seems from this thread that there are NO plans to make it possible to reorder sidebar items in v7, and that we should wait until v8. Is this correct?

Nope, not necessarily. @benhaynes just pointed out how it would / could / should work in the design changes (see https://github.com/directus/app/issues/1236).

> IMHO, there will always be more pressing issues, that should take priority - but that doesn't mean that issues like this should be pushed aside

So if the more pressing things take priority, how can I prevent issues like this from being pushed aside?  Seeing it's a free and open source project that doesn't cost (and therefore doesn't make) any money, there's only so much I can do with the time I have..

Anyway, how should this simple reordering work in your opinion? Couple of thoughts:
* Should we add a column to the directus_collections table that holds the sort order for the collections  (being global for every user). 
* Should we add a menu column to directus_roles, so you can set the menu for individual roles?

The first is the easiest to implement, but might not be flexible enough? The second option is sorta specced out above, but is "fixed" (eg it doesn't automatically add newly created collections) (is that even a problem)?

I'd love to hear your thoughts. Especially seeing that planning out a feature like this is 80% of the effort to get it done 😄

**Comment by luxlogica** [comment]
@rijkvanzanten Option 1 - the simplest, global option - would already be a big improvement, and most welcome. Anything beyond that would just be 'extra icing on the cake'.

**Comment by theharshin** [comment]
I was looking for this feature and landed on this. This is indeed an important feature and I'll look into this. 👀

**Comment by benhaynes** [comment]
I think it makes the most sense to add the global option first so that the feature exists (and this is a bit easier) and then to eventually add an override at the Role level as a progressive enhancement.

**Comment by rijkvanzanten** [comment]
@benhaynes I slightly tweaked that JSON structure to make it more "JSON"

```json
[
    {
    	"title": "collections",
        "links": [
            {
            	"name": "Directus",
                "link": "https://directus.io"
            }
        ]
    },
    {
    	"title": "B00kmarks",
        "include": "bookmarks"
    }
]
```
