### ISSUE TITLE
List View Preferences - Filter on a dynamic value

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1252]
# Bug Report
I have 2 tables A and B. A has a ref of B. Both have a ref to my table client. 
I try to filter my dropdown of B in order to show only the item of B where B.client_id=A.client_id. I got a Server Error result

## Steps to Reproduce

1. Go to table A, and set B_id to M2O
2. set the relation as A.B_id = B.id
3. In List View Preferences, I did :
```
{
    "viewType": "tabular",
    "viewQuery": {
        "fields": [
            "id",
            "group_name",
            "client_id"
        ]
    },
    "filters": [
        {
            "field": "A.client_id",
            "operator": "eq",
            "value": "B.client_id"
        }
    ]
}
```
4. See error : Server Error / no result shows
![image](https://user-images.githubusercontent.com/34483024/51119489-4904b000-1813-11e9-9606-39a9f07ef315.png)

## Expected Behavior
A list with all the item in B where B.client_id=A.client_id

## Actual Behavior
Server Error

## Technical Details

- Device: Desktop
- OS: Windows
- Browser: Chrome
- Directus App: 7.0.14
- Install Method: cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
