### ISSUE TITLE
Drag and drop to re-order "Files" interface

### ISSUE THREAD

**Issue by computerwizjared** [directus/app#1253]
# Feature Request
Add drag and drop to re-order files in a M2M "Files" relationship, like in Directus 6:
![directus](https://user-images.githubusercontent.com/2905521/51124983-370c1880-17e5-11e9-8104-6a0d3b76c96d.gif)

## What problem does this feature solve?
Our marketing team likes being able to re-order the images as needed, and we used to be able to do it within the collection, however now we are not able to. When calling the API of the collection, it should return the M2M objects in the specified order.

## How do you think this should be implemented?
The same way as Directus 6.

## Would you be willing to work on this?
I could help test it if needed.

**Comment by benhaynes** [comment]
💯 — this is an important feature of the `files` interface. My thinking is that this should automatically enable if the junction collection has a `sort` field type.

**Comment by computerwizjared** [comment]
@benhaynes our current workaround is to set the sort manually in the junction collection behind the scenes, but not a great end user experience. We also seem to have to sort on the frontend manually; the M2M results are not consistently returned in the same order as the "sort" column in the junction collection.

**Comment by rijkvanzanten** [comment]
I remember there was an enhancement issue to support dot syntax in the sort parameter. Not 100% sure if it made it in yet though. `?sort=sort` should sort the results by the sort column

**Comment by benhaynes** [comment]
Regardless, I think supporting drag and drop _within_ the interface should be the priority/fix.

This ties into https://github.com/directus/app/issues/122 — basically, as soon as we have a good solution for dragging and dropping files/folders/tiles then we can get this one in there.

I also just realized that our general M2M interface doesn't allow for reordering 😬 ... so we'll get one that in too!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
