### ISSUE TITLE
Improve Item Browse for Relational Modals

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1254]
### 7.0.x (now)
To simplify the creation of relational fields, we should only use the "Template String" for both the interface _and the modal_. 

### 7.1.x
The ideal way to handle this would be to allow for a _full_ modal with all the same power as the Core browse component:

* Change Layout
* Filter
* Search
* Sort
* Reorder
* Change Columns

**Comment by rijkvanzanten** [comment]
Ironically, it's the other way around. Currently it's re-using the full layouts in the modals, but this has proven to be less than ideal (too heavy / not properly optimized for modal usage). In a later version, we'll move to a tighter setup that's easier to configure too
