### ISSUE TITLE
Add date-fns to vue main component

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1257]
Make `date-fns` accessable again.
@rijkvanzanten

**Comment by rijkvanzanten** [comment]
You can access dateFns in extensions in `this.$helpers.dateFns`

**Comment by benhaynes** [comment]
@rijkvanzanten ... Is this somewhere in the docs?

**Comment by rijkvanzanten** [comment]
yes https://docs.directus.io/advanced/app/helpers.html
