### ISSUE TITLE
The auto-refresh of the grids should be configurable

### ISSUE THREAD

**Issue by Guisardo** [directus/app#1258]
# Feature Request
Currently the data grids have an auto-refresh every 5 minutes. That 5 minutes is hardcoded at the sdk:
https://github.com/directus/sdk-js/blob/master/src/index.js#L427
That interval should be part of the configuration.

## What problem does this feature solve?
Different users and different data require different interval of refresh. Currently the only alternative is to do a browser refresh, but that is very impractical, it takes time and losses the filters.
Although, in an ideal scenario websockets should be implemented to populated the data....

## How do you think this should be implemented?
It could be global, a user and a table based and the javascript should choose the lower interval defined that applies for the grid that is about to display.

## Would you be willing to work on this?
Sure, I'll love to help but currently I don't have much free time to do it.

**Comment by rijkvanzanten** [comment]
This refresh is only for the authentication token, which has a expiry date of now + 5 minutes coming from the API. It doesn't have anything to do with or users. 

> Currently the only alternative is to do a browser refresh, but that is very impractical, it takes time and losses the filters.

I think something else is going on in your particular use case. This refresh isn't for data and has nothing to do with data fetching or filters.

> Although, in an ideal scenario websockets should be implemented to populated the data....

With a PHP API, websockets are unfortunately out of the question for the time being.


Please let me know if I'm misunderstanding what you're saying 🙂

**Comment by Guisardo** [comment]
Hi @rijkvanzanten ,
When the data of a collection gets updated outside the app, ether by the api or directly at the db, it takes 5 minutes to the app to display the update or a browser refresh. From debugging the code I notice that the grid is autoupdated after calling the /refresh endpoint.
Reducing the interval of the line mentioned abobe directly reduces the time it takes the changes of data to be self reflected at the app without any browser refresh. I though that that was a feature in it self not just a coincidence.
We can recreate the feature request to implement a method to auto-refresh the items of the collections grid without a browser reload.

On the other hand, be aware that there are many implementations of websockets in php:
http://socketo.me/
https://github.com/ghedipunk/PHP-Websockets
I thing it would be really nice to add websockets at the api for use cases like this one.
Best

**Comment by rijkvanzanten** [comment]
The `/refresh` endpoint is used to refresh the authentication token and _will not_ reload any data. We have been thinking about support real-time data in https://github.com/directus/app/issues/611, but this is not currently implemented in the application.

Websocket servers need a constant running server, which means that you need to have CLI access to the server in order to run them. As of right now, we still support shared hosts where you don't have server access..
