### ISSUE TITLE
Layout: Relationship diagram

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1259]
# Feature Request
![layout](https://user-images.githubusercontent.com/22577866/51379278-566db300-1b0f-11e9-8689-ea70de37f9f9.png)

### What problem does this feature solve?
It allows you to manage datasets with relations like pages on a homepage.

### How do you think this should be implemented?
Via programming 😄 

### Would you be willing to work on this?
What, me? Definetly not, never ever! (WARNING! Sarcasm)

What do you think of it? Would it be usefull enough for 80/20 Rule?

**Comment by rijkvanzanten** [comment]
How would this save data in the database? Are those rectangles individual items, with the lines being the relationships?

**Comment by Nitwel** [comment]
You could make it so it accepts a o2m or m2m and transforms this information into these items with connections. The user then can arrage them according to a already predefined structure or move them individualy as he likes.

**Comment by benhaynes** [comment]
This could be a page/module visualization of the relationships, or it could be an interface (within Settings) that allows users to actually define/setup the relationships. To do the latter we would need to incorporate the field names in as well.

I could see expanding this a bit to have an entity–relationship model (EER) visualization/configuration tool like this:

![ou13w](https://user-images.githubusercontent.com/522079/51429165-ed9f3d00-1bd9-11e9-81b7-7eee50261cc2.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
