### ISSUE TITLE
Give proper error when exceeding database value length

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1260]
When editing an item in the App and your interface value's length exceeds the allowed database column length, the user should get an error:

```
The value you are saving is X long, but this field only supports up to Y. Please reduce your value's length or contact an administrator to increase the field size.
```

This should be done globally, not in each interface.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
