### ISSUE TITLE
Sort descending

### ISSUE THREAD

**Issue by dur41d** [directus/app#1261]
# Feature Request

Make the sort field show items in descending order.

## What problem does this feature solve?

I have blog articles that I would like to show in descending order (latest first). However I would like also to control the sort order manually. That's why I'm using a sort field for my collection. However the admin interface shows the items only in ascending order when using the sort field that means that my latest article will be at the end which is a problem when I have hundreds for articles. 

## How do you think this should be implemented?

The sort icon show allow ascending and descending order just like other fields.

**Comment by ceruulean** [comment]
I think this is already in the app?
![image](https://user-images.githubusercontent.com/41603229/52818446-6fb14300-306c-11e9-82a8-662e6abd00bf.png)

**Comment by rijkvanzanten** [comment]
I think he's referring to the manual sort button in the top left of the listing view @ceruulean. While regular columns can be sorted asc and desc, the manual sort button only supports asc sorting

**Comment by ceruulean** [comment]
Ooo ok, how about clicking on "Sort" field stays in Manual mode?

**Comment by dur41d** [comment]
When choosing the manual sort the items are sorted by the sort field and ascending order only and there is no way to make it sort in descending order.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
