### ISSUE TITLE
Sort field default

### ISSUE THREAD

**Issue by dur41d** [directus/app#1262]
# Feature Request

Sort field should have a default of last or order + 1 or (auto increment).

## What problem does this feature solve?

Right now the default for sort field is NULL which makes the field null for all items until the user chooses to order the fields and then all the order are initialized. This is non-intuitive behavior. It makes more sense to make the default of the order field to be auto increment. 

## How do you think this should be implemented?

Make the default for the sort field to be auto increment and the API should create the field in the database with auto increment. The user should be able to choose other defaults including null if he wishes to.

**Comment by benhaynes** [comment]
Wow, somehow I never thought of using auto-increment for this field type. I can't think of any reason why this wouldn't work to keep new items sorted at the bottom.

@WellingGuzman ?

**Comment by rijkvanzanten** [comment]
That's smart! I think the application can already send an auto_increment flag to the API in order to activate auto_increment. I want to add that to the field options so you can use it for any INT field. The primary-key and sort interfaces can than have that that enabled by default :)

**Comment by fnicastri** [comment]
Probably using auto increment could lead to some holes in the sort column.
Why not implement it with a sub query using the MAX function?
Something like:
INSERT INTO table ( sort,field1,...fieldN) 
SELECT 1 + (SELECT MAX(sort) FROM table), 'value1',...'valueN';

**Comment by benhaynes** [comment]
@fnicastri — wouldn't that have the same issue? Given the following dataset:

```
1: Apple
2: Banana
3: Pear
4: Orange
6: Pineapple
7: Grapes
8: Kiwi
```

Wouldn't both options (autoincrement and max) ignore sort `5` and create `9` next?

**Comment by benhaynes** [comment]
Ahh, I see what you're saying. Ideally we would compact the sort values, yes (though it shouldn't make a difference). Also, we _could_ reset the SQL auto-increment after compacting which would have the same effect.

The only benefit I see to auto-increment is that it works out of the box... so it would still function if you added items directly to the DB. This is inline with the "Directus is a database wrapper... so you can also work directly in the DB if you want".

**Comment by fnicastri** [comment]
it should works, yes.
Honestly, I would prefer to compact the column to not have holes, this is what I usually do in my projects.
It's not very intuitive for the user to see in the order column something like:

sort | column 1 | column 2
------------ | ------------- | ------------
|1  | value1 | value2 |
|3  | value1 | value2 |
|8  | value1 | value2 |
|14| value1 | value2 |

**Comment by dur41d** [comment]
Maintaining an exact order of numbers is like making sure that all files on
the hard disk are in contiguous blocks. It's costly to implement, error
prone and brings back no value.

**Comment by fnicastri** [comment]
Costly, yes,
error-prone? maybe
no value? I'm sorry but I have to disagree. You should look at it from a UX point of view.
A sort column full of holes is highly counterintuitive for the end user.
I would never accept to present it to a customer...
Right now I'm developing a little website and I'm using Directus as a backend.

Directus is a very promising project but is full of bugs (oh man the app...) and oversights like this one.
I have no problems in resolving this specific issue, a little procedure in the DB and my sort column will be always "beautiful" but, IMO, this sort of things sends the wrong message to the end users, a sense of sloppiness, not enough care of the details. Just my two cents.

**Comment by benhaynes** [comment]
I would love to see all of our sort values stay continuous, and without gaps. And while we should aim for perfection, perfection is the enemy of _good_.

Luckily our App doesn't allow reordering across tens-of-thousands of items when these `UPDATES` might cause bigger problems. The only way to keep the data "pretty" means updating all items in between two swapped sort value changes.

When we have time to devote to this optimization I'm sure we can find a good way of updating large numbers of item's sort values when re-ordering such that they close the gaps.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
