### ISSUE TITLE
Filter out '/' from slug and other invalid characters

### ISSUE THREAD

**Issue by dur41d** [directus/app#1263]
# Feature Request

Remove '/' from slug as it interferes with the URL.

## What problem does this feature solve?

If the title has '/' the generated slug has '/' as well which cases an invalid url.

## How do you think this should be implemented?

Remove '/' for the generated slug and other invalid charachters like '? : . ' others?

**Comment by rijkvanzanten** [comment]
Is this when creating the slug via the API or the application?

**Comment by dur41d** [comment]
Via the app
