### ISSUE TITLE
Make status interfaces required by default

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1264]

**Comment by shealavington** [comment]
Odd, even though this is not "required" in my schema, upon trying to save (without selecting any status), it's throwing a console error saying it can't be blank?.. :thinking: 

`{code: 4, message: "status: This value should not be blank."}`

**Comment by rijkvanzanten** [comment]
I think @wellingguzman might've implemented the requirement of this fieldtype into the API. Welling?

**Comment by benhaynes** [comment]
That sounds familiar — mostly because `NULL` status means workflow permissions can't work properly.

**Comment by benhaynes** [comment]
If that's the case, the App should select and disable the required checkbox for status interfaces.
