### ISSUE TITLE
Can't Install - 400 bad request

### ISSUE THREAD

**Issue by awdriggs** [directus/app#1265]
## Version Info
  - Directus API version (Or commit hash):
  - PHP version: 7.2.10-0ubuntu0.18.04.1
  - MySQL version: 5.7.24-0ubuntu0.18.04.1
  - Web server: Apache
  - OS name and version: Ubuntu 16.04 on Digital Ocean

## Expected Behavior
successful installation and redirction to login page

## Actual Behavior
Nothing happens, when save button is pressed there is a brief spinning icon then nothing happens.

## Steps to Reproduce
 1. I setup an Ubuntu server on digital ocean
 2. Followed this tutorial to install...https://medium.com/directus/installing-directus-7-on-lamp-defc9c5b63e1
 3. Changed apache root directory to directus/public following this installation guide https://docs.directus.io/getting-started/installation.html#setup
4. Setup mysql database called directus
5. Changed password for mysql root user
6. Went to the /admin page to click install

## Schema Dump, Logs, or Screenshots
<img width="1097" alt="screen shot 2019-01-20 at 1 06 42 pm" src="https://user-images.githubusercontent.com/1815808/51443337-979fc780-1cb5-11e9-979d-48b9528884a4.png">

**Comment by awdriggs** [comment]
I tried again with a totally fresh install and got the exact same outcome...

again following this tutorial https://medium.com/directus/installing-directus-7-on-lamp-defc9c5b63e1

I did the digital ocean one click lamp app, running ubuntu 18.04. I did all the commands from the root user.

here is what my apache conf file looks like...
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/directus/public

	<Directory /var/www/>
    	   Options Indexes FollowSymLinks MultiViews
    	   AllowOverride All
    	   Order allow,deny
    	   allow from all
	</Directory>	
	
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>
```

Is that the correct document root for apache?

I setup the db following these commands...
https://docs.directus.io/guides/database.html#creating-a-database

So same errors.
Any ideas where the problem could be?

**Comment by rijkvanzanten** [comment]
Hey @awdriggs! It should be throwing a notification with the actual error that went wrong now. I hope that helps debug what's going wrong. Seeing it's a 400 error, I'm guessing it's an issue with the database credentials.

**Comment by hajarrashidi** [comment]
Is there anyway to debug. Because i got the same issue

**Comment by benhaynes** [comment]
https://docs.directus.io/getting-started/setup-checklist.html
