### ISSUE TITLE
02M pointing to itself not working

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1268]
# Bug Report

O2M relation does not work when using it on the same table:

![grafik](https://user-images.githubusercontent.com/22577866/51562227-9aebac80-1e89-11e9-804b-501ab677193a.png)

## Steps to reproduce

1. create a new 02M field pointing to the id (used as parent) of the same table.
2. create a new item with the "parent" of NULL
3. the item wont show up / creating a new item shows this:
![grafik](https://user-images.githubusercontent.com/22577866/51562599-8c51c500-1e8a-11e9-9d95-5f585965f1eb.png)

Note that this could be because the 02M field does not expect to have 0 entrys / a NULL pointer as a parent.
Here is what is in the database:
![grafik](https://user-images.githubusercontent.com/22577866/51562933-49442180-1e8b-11e9-82a0-f7d15c23d7e3.png)

## Expected behavior 

The 02M dropdown should show all other possible items within this table.

## Technical Details

- Directus App: 7.0.15
- Directus API: 2.0.14
- Install Method: selfbuild version from app/master

**Comment by benhaynes** [comment]
I thought we had a ticket for this but I wasn't able to find it.

**Comment by Nitwel** [comment]
Hmm, is this fixed cause its working in version 7.0.15!?

**Comment by rijkvanzanten** [comment]
If it's working I guess it's fixed 😂 

I haven't looked at this one in particular, but another issue could've been the same that caused this symptom.

**Comment by Nitwel** [comment]
Well done! 😄👍
