### ISSUE TITLE
Search field for tables in modal dialogs (M2M, M2O...)

### ISSUE THREAD

**Issue by ondrakoupil** [directus/app#1269]
# Feature Request

Interfaces that use modal dialog with table (M2M, M2O...) are quite hard-to-use if the other collection has a lot of items to choose from. What would really help is a small search field that could filter the rows and help the user find the one he is looking for.

## What problem does this feature solve?

Let's use the official directus demo as example. In collection "Showtimes", if I wanted to add another showtime, selecting a movie is difficult because there is more than 900 movies to choose from. I can sort them by ID, name etc., however this is often not enough. Also, the interface loads only 50 first rows, so you can't use Ctrl+F in browser unless you scroll all the way down.

The only workaround I discovered is setting viewQuery.limit in interface options to a very high number (1000) and then use Ctrl+F to find the desired row. Quite a clumsy solution. Also the App sends API request with fields=*.*.* (not only those defined in viewQuery.fields) so that all the properties of items are downloaded even if they are not supposed to be displayed. If a collection have many fields, this is quite inefficient and makes it even more clumsy solution.

It is not necessary to use full-scale filter interface. Simple text field that filters all visible columns would be more than enough.

## How do you think this should be implemented?

Add small text input field somewhere in modal header that would serve as pseudo-fulltext filter and enable the user to narrow data shown in the table. Also, it is already possible to hardcode "filters" into interface's options that add filter=XXX param to API request. The search field could use the same mechanism, only without need to hardcode the filter value into options - the value would be provided by the user.

## Would you be willing to work on this?
This is far beyond my vue.js skills, sorry... However I could ask my client who needs this feature to give some financial donation to the directus project.

**Comment by benhaynes** [comment]
Hey @ondrakoupil — I 100% agree! I opened the same request last week: https://github.com/directus/app/issues/1254

Basically I want all listing modals to use the same "item browse" component as used on the main item listing. That would give us search (server-side), as well as all of the other features (sort, layouts, etc).

I'll close this as a duplicate, but it will be referenced in the other ticket so your insight isn't lost!

Thank you very much for taking the time to describe this issue in such great detail! 😄
