### ISSUE TITLE
Missing French translations

### ISSUE THREAD

**Issue by sebj54** [directus/app#1271]
Hi!

I knew I forgot something when I checked translations recently 😅

I just created a translation field and I saw the following modal:

![image](https://user-images.githubusercontent.com/5880435/51698501-afa37e00-200a-11e9-849f-aaa97c59ea92.png)

It seems that there are several missing translations (almost everything is in English and there is also a buggy call to vue-i18n if I'm right). 

How can I find all missing French translations? I know that vue-i18n displays a warning in the console when it uses the fallback language but I'll probably miss some if I have to check every view of the app 😁

Maybe by checking keys of the English file against French one?

Thanks for your help ✌

PS: Maybe this will be easier with Crowdin like discussed in #793?
PS2: I also offer my help for any future translation adding! When you'll add some texts in English, you can notify me and I'll do my best to translate them quick

**Comment by rijkvanzanten** [comment]
Hey Seb! Right now the translations for interfaces and its options are all contained within the interfaces themselves. I'm moving them to the app translations so this is a little bit easier to manage in v7.1 (that I'm working on rn). 

If you want, you can translate the individual interface options in the `meta.json` files of said interfaces 

https://github.com/directus/api/blob/c6b1ed8c1e9031a657e442fffe4c84847e12c842/extensions/core/interfaces/many-to-many/meta.json#L44-L56

If you do, I'll make sure to move them over to their new home 😄

**Comment by benhaynes** [comment]
I know it doesn't necessarily help with extension translations, but I would love to get the _CrowdIn_ setup completed (I believe it's pretty close!). That will help with standardizing these translations immensely.

**Comment by sebj54** [comment]
> Hey Seb! Right now the translations for interfaces and its options are all contained within the interfaces themselves. I'm moving them to the app translations so this is a little bit easier to manage in v7.1 (that I'm working on rn).

This seems huge! I didn't think there were so many translations 😮
Let me know when you've moved all these translations, I'll check the 7.1 branch and I'll update them when they will be in a single file so you won't have to do it twice!

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/app/issues/1517
