### ISSUE TITLE
Allow Read-Only code blocks to scroll

### ISSUE THREAD

**Issue by KnowHowHere** [directus/app#1273]
# Feature Request

## What problem does this feature solve?
Currently if you have a code interface set to readonly and the content is longer than the lines defined, the "inactive" class prevents you from scrolling.

## How do you think this should be implemented?
Suggest that you don't apply the inactive class and rely on setting codemirror's readOnly attribute.

## Would you be willing to work on this?
Sure:
```
--- a/extensions/core/interfaces/code/input.vue
+++ b/extensions/core/interfaces/code/input.vue
@@ -1,5 +1,5 @@
 <template>
-  <div :class="{ inactive: readonly }" class="interface-code">
+  <div class="interface-code">
     <codemirror
       ref="codemirrorEl"
       :options="cmOptions"
```
The change is pretty trivial, let me know if you'd like a pull request.

**Comment by rijkvanzanten** [comment]
A PR would be great. Thanks @KnowHowHere!

**Comment by assmith** [comment]
No problem, here it is  (contributed by alter ego) https://github.com/directus/api/pull/731

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/api/pull/731#merged-event
