### ISSUE TITLE
Display issue when adding relational collections

### ISSUE THREAD

**Issue by RyanPrice-King** [directus/app#1274]
# Bug Report

## Steps to Reproduce

1.    When we create the collection, we can add in the data, but as soon as we start creating relations in other collections, we have a problem wherein the fields turn/appear blank in both collections, but the information is still there in the initial record. If you open the initial collection, we can't see what's there unless editing each record manually. 
2.    Additionally, something which may be related. When we do remove collections, the tables are not deleted. So, if we create the same database it just uses the data from those tables which remain when they should be removed. For instance, We currently only have "country_a" and "country_data_a" collections, but the previous collections still appear in  the DB after being deleted.  

## Expected Behavior
To see all column data properly
## Actual Behavior
Hidden filed data as soon as we create a relational collection.
## Other Context & Screenshots
**We can PM a video to you on request.**

Here is the table:  mysql> select* from directus_relations;
+----+------------------------------+---------------+----------------------+-----------+----------------+
| id | collection_many              | field_many    | collection_one       | field_one | junction_field |
+----+------------------------------+---------------+----------------------+-----------+----------------+
|  1 | directus_activity            | action_by     | directus_users       | NULL      | NULL           |
|  2 | directus_activity_seen       | user          | directus_users       | NULL      | NULL           |
|  3 | directus_activity_seen       | activity      | directus_activity    | NULL      | NULL           |
|  4 | directus_collections_presets | user          | directus_users       | NULL      | NULL           |
|  5 | directus_collections_presets | group         | directus_groups      | NULL      | NULL           |
|  6 | directus_files               | uploaded_by   | directus_users       | NULL      | NULL           |
|  7 | directus_files               | folder        | directus_folders     | NULL      | NULL           |
|  8 | directus_folders             | parent_folder | directus_folders     | NULL      | NULL           |
|  9 | directus_permissions         | group         | directus_groups      | NULL      | NULL           |
| 10 | directus_revisions           | activity      | directus_activity    | NULL      | NULL           |
| 11 | directus_user_roles          | user          | directus_users       | roles     | role           |
| 12 | directus_user_roles          | role          | directus_roles       | users     | user           |
| 13 | directus_users               | avatar        | directus_files       | NULL      | NULL           |
| 14 | directus_fields              | collection    | directus_collections | fields    | NULL           |
| 15 | country_info                 | iso           | countries            | NULL      | NULL           |
| 16 | country_info                 | country_iso   | countries            | NULL      | NULL           |
| 17 | country_info                 | country       | countries            | NULL      | NULL           |
| 18 | country_data_2               | country       | countries_2          | NULL      | NULL           |
| 19 | country_data_2               | iso_code      | countries_2          | NULL      | NULL           |
| 20 | country_data_a               | country_a     | country_a            | NULL      | NULL           |
| 21 | country_data_a               | iso_code_a    | country_a            | NULL      | NULL           |
+----+------------------------------+---------------+----------------------+-----------+----------------+
## Technical Details

- Device: Desktop
- OS: Windows and Ubuntu
- Browser: Any
- Directus App: 7.0.15
- Directus API: 2.0.15
- Install Method: Separate API and APP installations fresh to newest version and clean reinstall of DB

**Comment by rijkvanzanten** [comment]
> When we do remove collections, the tables are not deleted

@WellingGuzman 🔔 

@RyanPrice-King Could you send a database dump of a setup where this is happening? I've never heard or seen of this behavior before. If you like, you can send it privately on https://slack.getdirectus.com

**Comment by RyanPrice-King** [comment]
Yes this appears to be working now Thank-you :)

**Comment by benhaynes** [comment]
Great! @rijkvanzanten — we good to close this one?

**Comment by rijkvanzanten** [comment]
Yeah! @WellingGuzman found the issue over on the API side and fixed it :)

Lemme find the API ticket

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/api/issues/730
