### ISSUE TITLE
"Save as Copy" does not copy many-to-many relationships

### ISSUE THREAD

**Issue by KnowHowHere** [directus/app#1276]
# Bug Report

## Steps to Reproduce

1. Create a collection with a many-to-many relationship
2. Create an item and add 1 or more related items
3. Save item
4. Return to item, edit it and "Save as Copy"

## Expected Behavior
Copy should include m2m relationships

## Actual Behavior
No m2m relationships are present in the copy

## Technical Details

- Device: Desktop
- OS: OS X
- Web Server: NGINX
- PHP Version: 7.3
- Database: MariaDB
- Install Method: cloned `master` branch [c6b1ed8]

**Comment by KnowHowHere** [comment]
Apologies for posting to the wrong project, please find attached a simple db to test with.  It's the same db as attached to https://github.com/directus/api/issues/724 but it might help demonstrate/debug this issue too.  This issue occurs regardless of your role.

Regular user
username: contributor@example.com
password: secret

Admin user
username: admin@example.com
password: secret

[directus_example.sql.gz](https://github.com/directus/app/files/2799877/directus_example.sql.gz)

**Comment by benhaynes** [comment]
Hey @KnowHowHere — it's easy to forget that relationships go both ways (and I'm not doling out love advice), and that can be quite tricky in some situations.

### Example when you don't want to duplicate relations:

Assume you have collections of `authors` and `books`. Each book is assigned to an author via a **M2O** — or, seen the opposite way, each author is related to their books via a **O2M**. Therefore, if you duplicate an author with 100 books, you would also be duplicating their 100 books (since a book can only be related to one author).

**Comment by benhaynes** [comment]
And to answer your actual question, you could see what `item.create` offers you from the [action hooks](https://docs.directus.io/extensions/hooks.html#action-hooks). There might be some sort of flag that this is a copy — or, if not, you could request that a flag (or new hook) be made for this.

Hope that helps!

**Comment by KnowHowHere** [comment]
Thanks @benhaynes, there's nothing I've seen in the item.create payload that indicates a copy, now that I've seen where @rijkvanzanten is removing fields during a copy I might be able to deduce one from the absence of a field.

**Comment by KnowHowHere** [comment]
I realise you'd like to park this for a while until it can be given more consideration, but just one more note in case anyone bumps into this and comes across this issue.  The current solution means you can't duplicate an item that has a "required" many-to-many field, as removing the field value at the point of copy as in commit #44be1f2 causes the new item to fail due to the required constraint.

**Comment by benhaynes** [comment]
That was actually the main reason we decided to wait on this (required relational fields with their data stripped).

The proper fix will be to add a modal on duplicate that asks what you want to do with the relational data: Remove, Duplicate, etc

**Comment by rijkvanzanten** [comment]
I'm converting this from a bug to a feature request, as the OP is not necessarily a bug, but a choice that was made while designing the platform. Like @benhaynes mentioned above, ideally the interface can render some sort of modal that lets the user pick what to do with the relationships.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
