### ISSUE TITLE
Incorrect data when switching between projects

### ISSUE THREAD

**Issue by honzabilek4** [directus/app#1278]
# Bug Report
When you login to a different project on the same app instance in the same browser window, you still see cached data from the latest project (collections, user name, etc.), even though you should already see the new project. Reloading the window helps to fetch the correct data.

## Steps to Reproduce

1. Login to some Directus project
2. Logout
3. Select a different project with different collections, so you can see the difference and login again
4. In the side menu, you should now see collections from the first project.
5. Reload the window and the new collections appear/old collections disappear

## Technical Details
- Directus App: [eg: 7.0.15]
- Directus API: [eg: 2.0.15]

**Comment by bjnsn** [comment]
Seeing this also (in 7.0.15).

**Comment by christianrr** [comment]
Problem still occurs in 7.6 both on Chrome and Edge.

**Comment by benhaynes** [comment]
Let's review this and make sure it[s properly resolved.

**Comment by christianrr** [comment]
![collection1](https://user-images.githubusercontent.com/10274479/60819402-d102bb80-a19f-11e9-9b8b-2a7e76a0c498.png)

--> switch project in sidebar

![collection2](https://user-images.githubusercontent.com/10274479/60819403-d102bb80-a19f-11e9-8a42-5210679f517e.png)

Second project (second image) should contain "Veranstaltungen" collection only.

**Comment by rijkvanzanten** [comment]
@christianrr Could you share some more information on your setup? It seems to work on my end in 7.8.0

**Comment by christianrr** [comment]
still happens in the latest version. Most of the time switching to another project is working in the first place, however tables get mixed up when switching back to the original project.

Setup:

Device: [Virtual Server]
OS: [Ubuntu 18.04]
Web Server: [Apache 2.4.29]
PHP Version: [7.2.19]
Database: [5.7.27]
API Version: [2.3.1]
APP Version: [7.8.0]

**Comment by christianrr** [comment]
Some more info on the project config:

I have four projects in the instance (the main one "_" and three sub projects). Error appears when switching from the main project to one of the sub-projects...

api: {
      "../_/": "Event Console",
	  "../event1/": "Event 1",
	  "../event2/": "Event 2", 
	  "../event3/": "Event 3"
    },
