### ISSUE TITLE
O2M allow unset

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1279]
## Feature Request

It would be realy nice if it would be possible on any x2x connections to set it to NULL, so there would be no relation set.

**Comment by Nitwel** [comment]
You cant save a o2m connection, when you have nothing selected even tho the 02m connection isnt set to required.

![grafik](https://user-images.githubusercontent.com/22577866/51849456-0c12e000-2320-11e9-909e-854dd1130696.png)

**Comment by Nitwel** [comment]
Ok, you can do it by just closing the popup which updated the field even tho the save button is grayed out.
XD

**Comment by rijkvanzanten** [comment]
On that note, we should probably rename `save` to `done` and have it enabled at all times.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
