### ISSUE TITLE
The default value of checkbox interface does not working properly

### ISSUE THREAD

**Issue by KKAries** [directus/app#1281]
# Bug Report

## Steps to Reproduce

1. Create a new checkbox field to a collection.
2. Set the choices and the default value for the checkbox.
3. Go to create a new item of the collection and see that the default choice is not checked.

## Expected Behavior
The default checkbox is checked by default when create a new item.
## Actual Behavior
Not checked by default. Also after select a choice and saved, see that value in the collection items view or database and you will find it have some strange value like ",x,x,x,value"
## Other Context & Screenshots

APP 7.0.15 and API 2.0.15

**Comment by KKAries** [comment]
It seems that still have issue with the latest 7.0.16 build. I tried to create a checkbox with default value - no issues. However, when I edit the default value of an existed checkbox field there will be a SQL error `"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT 'value3'' at line 2"` in the console.

**Comment by rijkvanzanten** [comment]
@KKAries that sounds like a different problem :thinking: Mind opening a new issue on the directus/api repo?

**Comment by KKAries** [comment]
@rijkvanzanten Sure, I'll open a new one.
