### ISSUE TITLE
Can't "Save as Copy" items that have a relationships (o2m, m2o, m2m) as non-admin user

### ISSUE THREAD

**Issue by KnowHowHere** [directus/app#1286]
# Bug Report

## Steps to Reproduce

1. Create a collection with a relationship (one-to-many or many-to-many)
2. Create a new item as a _non-admin_ user
3. Revisit item, make an edit and choose "Save as Copy"
4. See error:
  Updating item from "directus_users" collection was denied
5. Allow update Full permission to directus_users for role
6. See error:
  Updating item from "directus_user_roles" collection was denied
7. Allow update Full permission to directus_user_roles for role
8. See error:
  You are not allowed to create, update or delete roles
9. Comment out lines 591 - 593 of CoreServiceProvider.php
```
  // if (!$acl->isAdmin()) {
  //       throw new ForbiddenException('You are not allowed to create, update or delete roles');
  // }
```
10. Copy saved

## Expected Behaviour
Should be able to copy items without Directus trying to write to the user or user roles table

## Actual Behaviour
It appears that the API tries to rewrite/reset the full directus_users and directus_users_roles records for the current user with their current values. i.e no changes, just rewriting all fields with their current values.

## Technical Details

- Device: Desktop
- OS: OS X
- Web Server: NGINX
- PHP Version:7.3
- Database: MariaDB
- Install Method: cloned `master` branch [c6b1ed8]

**Comment by rijkvanzanten** [comment]
@WellingGuzman It is kinda strange that the duplicate is actually created. I think it's because the actual creation of the new row of the original collection is successful, but the API errors out during the (wrong) update in directus_roles. Can we undo that original duplicate if that's the case?
