### ISSUE TITLE
Issue in Display for Many to One interface

### ISSUE THREAD

**Issue by RyanPrice-King** [directus/app#1288]
# Bug Report

## Steps to Reproduce

1. Create a new collection with various text inputs.
2. Create One-2-Many.
3. Setup the relation as illustrated in the screen grabs.
4. Create new.
5. Choose select from existing.
6. Select multiple then add them.

To link in multiple selections, and display them correctly.

## Actual Behavior

Only links one and does not display them correctly.

## Technical Details

- Device: Desktop
- OS: Windows and Ubuntu
- Web Server: Apache/2.4.6
- PHP Version: 7.3.1
- Database: MySQL 5.6.10
- Install Method: Docker for APP and Git clone API repo
Both API and APP are 0.16

**Comment by rijkvanzanten** [comment]
The O2M interface has been reworked a couple times between jan 29 and now. Currently, the display component renders like this

![image](https://user-images.githubusercontent.com/9141017/60300906-084eae00-98fe-11e9-9bbe-550546afb521.png)

So I believe the OP has been solved in the past
