### ISSUE TITLE
CTA when no Collections/Fields/Items

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1291]
When looking at a new install you'll see "No Collections". We should show a call-to-action button (for admins only) that links to Settings for creating a new collection.

The same should exist for new items in empty collections, but this would not have the "admin only" conditional.

I can provide a design!

**Comment by dev7ch** [comment]
This is a very good input imh.
I would like to help and its a good issue to get closer to your application.

The desired Design would be helpful.

**Comment by benhaynes** [comment]
This is following the upcoming 7.1 design system, but here's a mock!

![screen shot 2019-02-13 at 7 51 04 pm](https://user-images.githubusercontent.com/522079/52754507-c5ccaa80-2fc8-11e9-923f-ae4031c51ee8.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
