### ISSUE TITLE
Full-Screen Page — Toggle

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1292]
**Version 7.1**

To avoid screen real-estate issues in 7.1, we should add a "Full Screen" toggle for the page. This would show the page section edge-to-edge, temporarily hiding the module, nav, and info sidebars. This would allow for global distraction-free mode and give more space for browsing data.

You could access this at _any time_ through the keyboard shortcut (eg: `ctrl-tab`), or with a dedicated button (as needed).

**Comment by ceruulean** [comment]
Would the toggle button be customizable? (Imagine setting it to F11 for fullscreen goodness, although some people might not want it on F11)

**Comment by benhaynes** [comment]
Hmm, I suppose it could be customizable... though I think we'd want to have these be the same everywhere. It seems like the best (initial) option would be to use a [cross-platform meta key](https://vuejs.org/v2/guide/events.html#System-Modifier-Keys) and choose a key combination that won't interfere with system/browser functions. 

Ideally we should plan out any/all Directus keyboard shortcuts at once so that they all fit well together.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
