### ISSUE TITLE
Error when using Files field

### ISSUE THREAD

**Issue by sajsemegaloma** [directus/app#1294]
# Bug Report

## Steps to Reproduce

1. Under Collections & Fields add a 'Files' type field to a collection (default settings)
2. Go to that collection and add an item, if you try to add a file to the Files field you will get an error in the console (see Error 1 below)
3. You can still save the item, but if you click on any of the items on the listing (regardless if you tried to add an item or not) you will get another error in the console (see Error 2 below)

## Expected Behavior

Should be able to add files

## Actual Behavior

Can't add files, or even access items that have it in the schema.  Note that the 'File' field works just fine.

Perhaps it's something with my environment, but I have no idea what to look for.

## Other Context & Screenshots

https://ibb.co/k2k7zGc

## Technical Details

- Device: PC
- OS: Windows 8.1
- Browser: tested in current versions of Firefox, Firefox DE and Chrome, happens in all of them
- Directus App: Current (installed yesterday)
- Directus API: Same
- Install Method: cloned master via git
- Hosted on Cloudways (Digital Ocean)
- PHP  7.0, MySQL 5.5

ERROR 1==============================

TypeError: "Invalid attempt to spread non-iterable instance"

    o input.js:6 u input.js:6 saveUpload input.js:6 t2VueJS
    save upload.vue:144 

vue.runtime.esm.js:1832

    et4VueJS
    save upload.vue:144 

ERROR 2==============================

TypeError: "tc.getters.o2m(...) is null"

    pd item.vue:198 pd item.vue:193 beforeRouteEnter item.vue:876 Ge vue-router.esm.js:2095 p vue-router.esm.js:1935 r vue-router.esm.js:1709 De vue-router.esm.js:1717 confirmTransition vue-router.esm.js:1971 r vue-router.esm.js:1706 r vue-router.esm.js:1710 p vue-router.esm.js:1956 e vue-router.esm.js:1784 p vue-router.esm.js:1935 r vue-router.esm.js:1709 r vue-router.esm.js:1713 r vue-router.esm.js:1710 p vue-router.esm.js:1956 56d7 router.js:254 p vue-router.esm.js:1935 r vue-router.esm.js:1709 r vue-router.esm.js:1713 De vue-router.esm.js:1717 confirmTransition vue-router.esm.js:1964 transitionTo vue-router.esm.js:1866 push vue-router.esm.js:2267 push vue-router.esm.js:2529 click table.vue:15 t2VueJS

vue-router.esm.js:1897

​

**Comment by FRSgit** [comment]
Well, getting the same with newest build under Win10 Opera.

Also, when when clicking "existing" (files) I get:
![image](https://user-images.githubusercontent.com/10456649/55838465-d743b600-5b24-11e9-800d-16e649de66d3.png)

I think that's pretty important bug, it prevents me completely from using the files component

**Comment by rijkvanzanten** [comment]
This has been fixed in https://github.com/directus/app/pull/1881
