### ISSUE TITLE
Ability to edit and delete comments

### ISSUE THREAD

**Issue by magikstm** [directus/app#1302]
# Feature Request

I would like to have the possibility to edit and delete a comment added on a collection item.

## What problem does this feature solve?

Make comment usage more friendly for users.

## How do you think this should be implemented?

I don't know the project enough to comment.

## Would you be willing to work on this?

I don't know the project enough at the moment.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
