### ISSUE TITLE
More Min/Max Options for Date Interface

### ISSUE THREAD

**Issue by Mozz4rt** [directus/app#1305]
# Feature Request
I'd love to see some rules within the admin field configuration.

For example, in dates there's already the minimum and max date. But i think some things could be improved in them, for example having the "Minimum Date" field referring to another date field (use case: from, to periods of time) or maybe referring to the current date (2 months from now, today).

Another example could be a toggle field alternating the display of 2 other fields.

## What problem does this feature solve?
It would make things a bit more bulletproof on the user-side

## How do you think this should be implemented?
I'm guessing within each extension/field package there could come the rules for it, making the rules specific.

## Would you be willing to work on this?
Don't know vue very well but i could give it a try

**Comment by benhaynes** [comment]
Thanks @Mozz4rt — always appreciate some new feature requests!

I love "global-izing" features like this, but it seems that this specific request would be better as a date interface option... or, if it doesn't pass our 80/20 rule then maybe a custom date interface.

The main thing here is how do we present these min/max options to the admin without overloading them with inputs. Here's one way to do it (I think this option would have to be built as a custom interface):

* Dropdown to choose Min (would be same for Max)
    * Date (shows calendar input below)
    * Field Value (shows field dropdown below)
    * Formula (shows input with format instructions below)

### Conditional Interfaces
There is already a ticket for this one... and it's on the roadmap for 7.1.
https://github.com/directus/app/issues/763

**Comment by rijkvanzanten** [comment]
Closing this in favor of #763
