### ISSUE TITLE
Error Message "Couldn´t reach API" when API is available

### ISSUE THREAD

**Issue by toak** [directus/app#1307]
# Bug Report

When I want to login in the app, the error message "Couldn´t reach API" shows up, even though the API responds to https://directus-api.toak.de/server/ping with "{"error":{"error":3,"message":"Unauthorized request"}}"

## Steps to Reproduce

1. Go to 'login page'
2. See error in the developer page

## Expected Behavior
The login page shows no API error

## Actual Behavior
Couldn´t reach API

## Technical Details

- Device: MacBook
- OS: MacOS 10.14.2
- Browser: Chrome 71.0.3578.98
- Directus App: 7.0.17
- Directus API: 2.0.17

**Comment by benhaynes** [comment]
Hey @toak — we are aware of this issue and version `7.0.17` was un-published minutes after release. You can use `7.0.16` without issue though.

https://github.com/directus/app/releases

**Comment by toak** [comment]
Thanks, it worked!

**Comment by benhaynes** [comment]
Of course! Apologies for the "fake" release. 😄
