### ISSUE TITLE
Save & Add new — Doesn't clear WYSIWYG

### ISSUE THREAD

**Issue by shealavington** [directus/app#1309]
# Bug Report

## Steps to Reproduce

1. Go to edit an item with a WYSIWYG
2. enter content into the WYSIWYG
3. Click Save & Add New
4. Notice how all fields except WYSIWYG get cleared.

## Expected Behavior
1. WYSIWYG Gets cleared.

## Actual Behavior
1. Doesn't clear.

## Technical Details
- Install Method: cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
`wysiwyg` seems to work fine, Im assuming this is in relation to the Advanced wysiwyg
