### ISSUE TITLE
Field One 2 Many behaviours

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1310]
# Bug Report

## Steps to Reproduce

1. Create a collection (e.g. navigation with some fields like label and slug) and add some items
2. Create a Singel collection with a One2Many relation to the collection from above
3. Try selection multiple fields from collection 1.) ... and click save
OR
4. Try adding new field inside of the single collection ... and click save

## Expected Behavior

- Selected items should persists
- make multiple selections as it is possible in your online demo

## Actual Behavior
- The collection seems to be cleared to one field only
![kapture 2019-02-07 at 12 40 52](https://user-images.githubusercontent.com/15183757/52409429-c0a5c200-2ad5-11e9-88c4-3e0c181db69f.gif)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS Mojave]
- Browser: [Chrome]
- Directus App: [latest dev]
- Directus API: [latest dev]
- Install Method: [local dev environment]

**Comment by dev7ch** [comment]
seems to be a duplicate of https://github.com/directus/app/issues/1288

**Comment by benhaynes** [comment]
I'll wait for @rijkvanzanten to confirm, but I think you're right.

We'll get this resolved asap!
