### ISSUE TITLE
Reuse "Browse Items" Component for Modal Selection

### ISSUE THREAD

**Issue by mdbarr73** [directus/app#1312]
# Bug Report

Choose existing files has no way to filter/search. Directus 6 gave you the full file library view so you could find files easily.

## Steps to Reproduce

1. Edit any item with a one-to-many file relationship
2. Click on 'Existing'
3. View appears with files populated, but there's no way to filter/search

## Expected Behavior

Directus 6 gave an option to filter/search. Directus 7 is limiting to 50, so it's hit-or-miss if you have more than 50 files.

## Actual Behavior

No filter options, only 50 files are shown.

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome 71.0.3578.98
- Directus App: 7.0.15
- Directus API: 2.0.15
- Install Method: Docker/AWS Fargate

**Comment by benhaynes** [comment]
The plan here is to refactor the "Select Item(s) Modal" to use the standard "Browse Items" component. This means that this modal will have access to _all_ of the features of the browse page, including:

* Searching
* Filtering
* Pagination

The input (filter/search) should either live in the modal header or in a sub-header.

Also, this change leads the way to eventually supporting:

* Changing Fields
* Reordering Fields
* Changing Layouts

**Comment by benhaynes** [comment]
This is related to a few other tickets — let's plan on looking into each of these during this component refactor:

https://github.com/directus/app/issues/1254
https://github.com/directus/app/issues/1288
https://github.com/directus/app/issues/1075
https://github.com/directus/app/issues/1073
https://github.com/directus/app/issues/760
https://github.com/directus/app/issues/681
https://github.com/directus/app/issues/582

**Comment by rijkvanzanten** [comment]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/9141017/52495652-63764300-2b9f-11e9-959b-99eb7f3e1ff1.png">

The file modal has been updated to support sorting and searching. The pagination has also been fixed.

**Comment by rijkvanzanten** [comment]
Closed in 
https://github.com/directus/api/commit/4036a82df4397f4cabfcc7d4ebfd14fa5395971f and 
https://github.com/directus/api/commit/0a63c33ba9ae8bab77b2fd039fe44d84bd6f2adb

**Comment by computerwizjared** [comment]
Hey @rijkvanzanten, this is fabulous, thank you! Two minor issues we found- on the "Choose One" screen on 1080p or smaller resolutions, we're seeing two scrollbars:
![image](https://user-images.githubusercontent.com/2905521/52506016-d50bbc80-2bb2-11e9-8611-c96ea5271906.png)
The other issue is when I select a file, then click "Cancel", it doesn't actually cancel because the file is applied on selection.

If you'd like me to create separate bugs for these, I definitely can do that. Thank you!

**Comment by rijkvanzanten** [comment]
@computerwizjared Windows scrollbars are going to be the end of me 🙃 

Time to get the hands dirty:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/9141017/52507250-f4a8e200-2bbe-11e9-990f-bdd583d0edc6.png">

**Comment by rijkvanzanten** [comment]
Okay @computerwizjared those two points should be fixed now :)

**Comment by computerwizjared** [comment]
Hey @rijkvanzanten thanks for your help- we are also seeing that when files are being saved in a M2M Files collection, they don't actually save. We can click "Done" when adding the files, but then we click "Save" on the item and it takes us back to the list. Returning to the item shows that the files were never added. Any idea what's up with that, or was that fixed more recently? Thanks!

**Comment by rijkvanzanten** [comment]
Hmm doesn't sound familiar. Could you open a new ticket so it doesn't get lost in the comments here? Thanks 🙂

**Comment by computerwizjared** [comment]
@rijkvanzanten Nevermind, it was a config issue! Thank you though!
