### ISSUE TITLE
Title Formatter Not Working

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1317]
Field titles don't seem to be using the Format Title function:

![screen shot 2019-02-08 at 10 13 07 am](https://user-images.githubusercontent.com/522079/52486825-28b5e000-2b8a-11e9-9eeb-1dbe88cb4db1.png)

![screen shot 2019-02-08 at 10 13 34 am](https://user-images.githubusercontent.com/522079/52486849-39feec80-2b8a-11e9-96c2-b0ff28938b56.png)

https://github.com/directus/format-title/blob/master/src/acronyms.js#L70

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/format-title/issues/7
