### ISSUE TITLE
Clean-up error reporting in console

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1318]
Trying to add Link and Image buttons (which should be in the default anyway) and I'm getting errors:

![screen shot 2019-02-08 at 10 32 28 am](https://user-images.githubusercontent.com/522079/52487973-db873d80-2b8c-11e9-87ce-f9306c0c7b2c.png)

**Comment by rijkvanzanten** [comment]
These are development mode warnings and don't show up in production environments. They are harmless to the functionality of the application.

**Comment by benhaynes** [comment]
We should not have so many "errors" in the console that you can't see/find real errors.

**Comment by rijkvanzanten** [comment]
This is an ongoing goal that doesn't need it's own ticket.
