### ISSUE TITLE
Saving empty wisiwyg field saves "<p><br></p>" to the database

### ISSUE THREAD

**Issue by AlexisWalravens** [directus/app#1322]
# Bug Report

## Steps to Reproduce

1. Go to a collection with a wisiwyg field.
2. Create a new record and write something in the wisiwyg field.
3. Save the record
4. Empty the wisiwyg field
5. Save the record again

## Expected Behavior
Saving a empty wisiwyg field should save `""` or `NULL` to the database.

## Actual Behavior
Saving a empty wisiwyg field in a record that had already something saved for this field, saves `<p><br></p>` to the database.

## Other Context & Screenshots

It's an actual issue because in my vue app, when I get the data I want `v-if="data.myWisiwygSavedField"` to not display it if it's empty, but as it saved to `<p><br></p>` it's never empty. I could check if the value isn't `<p><br></p>` but it's not very clean...

## Technical Details

- Directus App: 7.0.17
- Directus API: 2.0.17

**Comment by Jonesus** [comment]
Seems to be an issue with MediumEditor which the wysiwyg uses, there's been a PR hanging around for a while there
https://github.com/yabwe/medium-editor/pull/1351

**Comment by rijkvanzanten** [comment]
Thanks for pointing that out @Jonesus.

We could add a 'dirty' filter in between that basically says 

```js
if (this.value === "<p><br></p>") return null
```

but that might cause some other unforeseen issues.

It's preferred to wait for that Medium editor issue to be fixed, but seeing that that PR has been there for almost 2 years, I'm not too convinced that will happen..

Thoughts @AlexisWalravens ?

**Comment by benhaynes** [comment]
I think that "dirty" check could be added either way to help avoid this issue (stopgap). Hopefully Medium fixes their code, but doesn't seem likely to happen soon.

**Comment by rijkvanzanten** [comment]
Just for the record, the website Medium is not involved in the development of the popular medium-editor plugin that's made by yabwe. 

https://github.com/yabwe/medium-editor

**Comment by AlexisWalravens** [comment]
I agree with all of you for the 'dirty filter', but you should also keep an eye on the medium-editor's issue in case the fix comes one day.
