### ISSUE TITLE
Use custom input for dates / times

### ISSUE THREAD

**Issue by samvasko** [directus/app#1327]
# Feature Request
Safari and IE [do not have a native](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility) input type="date".  so no UI is shown in those browsers

## What problem does this feature solve?
Lack of date input UI in some browsers.

## How do you think this should be implemented?
Directus could provide a [polyfill](https://www.npmjs.com/package/date-input-polyfill) for this UI element or implement a custom date-picker for all problems.

## Would you be willing to work on this?
Possibly.

**Comment by benhaynes** [comment]
Hey @samvasko — thanks for the request! Have you tried the `calendar` interface? It's a custom date interface that should work across all browsers/OS. Still, I do agree that our other "input style" date interface should work everywhere.

@rijkvanzanten — thoughts on this? We also had the idea of using "masked" inputs for core interfaces.

**Comment by samvasko** [comment]
Thanks! The calendar works great!
The input is also used in many places in the admin interface where a calendar would not be suitable (or usable)

**Comment by benhaynes** [comment]
Ahh, quite true! We'll need to get the input style fixed either way.

**Comment by rijkvanzanten** [comment]
I was hoping the browser support would improve a little quicker :/ Apparently not!

We can either use a "full fledged" date picker like https://mariomka.github.io/vue-datetime/

<img width="833" alt="image" src="https://user-images.githubusercontent.com/9141017/52666013-0bab4500-2edb-11e9-9034-b9227186a4d4.png">

Or mask the input using something like https://vuejs-tips.github.io/vue-the-mask/

<img width="407" alt="image" src="https://user-images.githubusercontent.com/9141017/52666046-1e257e80-2edb-11e9-9223-0cc9a88798d8.png">

That being said, the second would be a bit hard to use as we would have to support multiple date time formats for the different locales (something the browser native one does out of the box, except for the aforementioned browsers ofc).

**Comment by benhaynes** [comment]
That `vue-datetime` is just a modal with a calendar interface... so all it does is add an extra click to an interface we already have. The only advantage I see is that it can show the "base" input in a smaller space... but we could add that as an option to ours. This one also seems a bit buggy, and wasn't great UX for date+time (time was hidden until you choose a date). I also worry about modal inception since this is another custom modal that will open when a user might already _be_ in a modal.

It's a bit absurd that Safari + IE don't support this yet, but I guess timezones/etc are complicated.

My recommendation would be to use multiple inputs for this interface and "combine" them into a hidden input. Then we can just explicitly define each input and combine in any format.

```
[February]  [03]  [1972] @ [16] : [04]
```

Thoughts on either of these approaches?

**Comment by samvasko** [comment]
> It's a bit absurd that Safari + IE don't support this yet, but I guess timezones/etc are complicated.

Frustratingly its only safari desktop that does not support it. 😅

**Comment by rijkvanzanten** [comment]
@benhaynes I think instead of having 5 inputs with some formatting, I think we should have an interface option for what format to use, we can create a dropdown with the 10 most common ones

```
mm/dd/yyyy hh:mm
mm-dd-yyyy hh:mm
dd/mm/yyyy hh:mm
dd-mm-yyyy hh:mm
yyyy-mm-ddThh:mmZ
```

**Comment by rijkvanzanten** [comment]
_TIL GitHub put a "Close Issue" button at the exact spot the "full info" button used to be in projects 🤦‍♂️_

**Comment by rijkvanzanten** [comment]
I think I'm going to consider this an enhancement rather than a bug. I know it's user unfriendly on Safari desktop, but it's not plain broken.

To improve the UI on desktops that don't support the specced elements sounds more like an enhancement to me 🙂

**Comment by benhaynes** [comment]
I like that dropdown format option idea! And yes, `enhancement` works for me...

_TIL you can italicize emoji 🤓_
