### ISSUE TITLE
Settings: Token Management Section (API Keys)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1330]
We need a good way to generate, delete, and refresh user's API keys. These static tokens are stored in `directus_users.token`, but are too much of a security risk to have managed by the users themselves. Instead, only admins should be able to manage them so we should generate a section/pane within Settings for this.

Design mockup inbound!

This supersedes: https://github.com/directus/app/issues/1192

**Comment by benhaynes** [comment]
I was thinking something like this, with the row options:

* (Re)Generate Key
* Delete Key
* View User

![screen shot 2019-02-13 at 7 44 48 pm](https://user-images.githubusercontent.com/522079/52754294-fb24c880-2fc7-11e9-8dab-fbbf7e88f3b9.png)

**Comment by Nitwel** [comment]
Hmm, maybe go at this "issue" from another way.
The main issue I have with the way, access tokens are handled at the moment, is that I dont realy see any good use for them. The only reason when you would need such thing is when you want to give users temporary access to directus to allow them to create a post for example. 

So my suggestion here builds up on the idea of an extra section as mentiont in your comments, but the main change I would make is that static tokens are not assigned to users that are using the app active but when you create a new token for a period of time, directus will generate a new user which you use to login and you, as the admin, can allow or deny access for any table for that specific user.

And please correct me if there are use cases to assign a static token for users but I realy dont see any. 😄
(looking at the 80/20 rule)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
I think we should decouple access tokens from specific users, or create a 'temp' user for an access token under the hood.

**Comment by nassan** [comment]
What is the plan regarding tokens. Are you guys going to keep it as needing to manually insert the token to the db?

**Comment by rijkvanzanten** [comment]
See posts above for the current plan. This is all a proposed feature request so this isn't finalized yet. Any recommendations or thoughts on this feature are very welcome

**Comment by justrealmilk** [comment]
I love this. I was about to create an issue for it. 

I'm starting to create users just for specific API access roles but I don't think a web site needs an avatar or first/last name 😂

**Comment by benhaynes** [comment]
I agree that _functionally_ users and tokens could be separated. Perhaps it makes sense to have a new collection with a reduced set of the same fields so we can merge users and tokens together for auth purposes.

**`directus_tokens`**
* `id`
* `status`
* `token`
* `role` (or a M2M junction, see below)
* `description`
_"Created On" and "Created By" would be stored in `directus_activity` and `directus_revisions`._

The main thing we'd need to decide is: will tokens use a M2M relationship with `roles` (like Users) so that they can have "combined" ACL in the future. Or, will each token be assigned to a single role defined in a M2O?

Alternatively, we could have a CSV of tokens on the `directus_roles` collection, but perhaps this is a bit messier since the tokens can't be read/managed as easily through SQL?
