### ISSUE TITLE
Ability to set order of items in M2O Dropdown

### ISSUE THREAD

**Issue by sajsemegaloma** [directus/app#1333]
# Feature Request

So unless I'm missing something obvious there doesn't seem to be a way to choose on what criteria the dropdown options are ordered when a dropdown is created for a m2o and other relational fields. Right now it just seems to put them in the order in which they're added to the database, which maybe makes sense for some cases, but most often you need these to sort alphabetically. I've searched and searched and can't seem to find any mention of a way to do it.

**Comment by rijkvanzanten** [comment]
The o2m / m2m can be re-sorted by the user by clicking on the table headers, just like the regular item lists. That being said, I think it's beneficial to add a `sort` option for the M2O dropdown

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
