### ISSUE TITLE
Rename WYSIWYG interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1334]
It seems to be a constant source of confusion. Our `wysiwyg` is a Medium-style select-to-tweak system, which shows up as a textarea. Most people expect to see a wysiwyg with the editor bar at the top (like our advanced-wysiwyg). 

We should consider renaming `wysiwyg` -> `wysiwyg-inline` and `wysiwyg-full` -> `wysiwyg`.

The only problem with this is that it's technically a breaking change..?

**Comment by benhaynes** [comment]
That would be a good solution, since there's a ticket hating on Quill we could "scope" all WYSIWYG interfaces with their library: `wysiwyg-medium`, `wysiwyg-quill`, `wysiwyg-tinymce`, etc. That way we can add/swap as needed and it should also help show the differences.

**Comment by dev7ch** [comment]
Just some thoughts: why implemeting two different wysiwyg editors?

Could it not be better to depend on one full featuring library (e.g. ProseMirror, TipTap)  and build the two different behaviors of the editor on top of that?

https://tiptap.scrumpy.io/menu-bubble

**Comment by rijkvanzanten** [comment]
@dev7ch I agree. We should have one system supported `wysiwyg` (the tiptap one). We can keep the quill one in a separate repo if needed.

**Comment by shealavington** [comment]
:+1:  Another in agreement here, one full-function WYSIWYG in the core-interfaces makes sense.

Other WYSIWYG interfaces could eventually become part of the Directus Marketplace for if you want something different—but for now as Rijk said, potentially in another repository

**Comment by rijkvanzanten** [comment]
What about the medium inline editor though? @shealavington @dev7ch

**Comment by dev7ch** [comment]
What are the key features of the medium editor? what do users love about it? (didn´t use it)

**Comment by rijkvanzanten** [comment]
It's a less intrusive / intimidating editing experience

![image](https://user-images.githubusercontent.com/9141017/56810296-e94f7500-6803-11e9-99a7-408b2588c2bf.png)

**Comment by dev7ch** [comment]
it looks pretty much like this example to me https://tiptap.scrumpy.io/menu-bubble except from the full screen option

**Comment by rijkvanzanten** [comment]
True! Would be nice if we could get rid of the medium one then 🙂

**Comment by benhaynes** [comment]
I like it!

Let's plan on focusing our attention on this one WYSIWYG interface then and deprecating the Medium Editor — perhaps adding it to the custom interface repo so people can still use it if they want to.

The "full screen" button on the Medium editor was added by me, and isn't part of the library. So no problem there. All we need to make sure of is that you can easily turn on the "inline" (bubble) mode for the new TipTap editor.

**Comment by dev7ch** [comment]
in the referenced PR above it is solved in  2 interfaces wich same the same code base

**1 motherinterface:**

`wysiwyg-full` - containing all Directus specific components and plugin (e.g. toolbar, images)

*** X child interfaces ***
e.g. `wysiwyg` - contains the specific `input.vue` which reuse the components from `wysiwyg-full`

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Nitwel** [comment]
What about renaming the "WYSIWYG" Editor to simply "text-editor" or such, it would make things even more clear.

**Comment by benhaynes** [comment]
When I hear "text editor" I think of a code editor. I feel like having one (core) interface called `wysiwyg` would be clear — no?
