### ISSUE TITLE
Notes should wrap so that the descriptions don't get cut off

### ISSUE THREAD

**Issue by PostPollux** [directus/app#1336]
# Feature Request
Notes are currently just cut off, if they are too long. I think they should wrap by default.

## What problem does this feature solve?
I don't see any benefit in cutting this of. I want my client to understand what he has to put into this field so he feels comfortable in filling out the form. Sometimes on line for explanation is just too short. I think it doesn't harm to wrap the text here, because if you don't like long texts, you can just write short ones. But if you need long ones, it's a problem right now.

## How do you think this should be implemented?

I'm not exactly sure but looking at the code it looks like only the "Notes" fiels are using the "small" class.
So it should work by just removing these three lines from the "small" selector in the "src/components/form/field.vue" file:

   white-space: nowrap;
   overflow: hidden;
   text-overflow: ellipsis;

## Would you be willing to work on this?
Maybe. I think it's super easy to fix if I'm correct with my assumption above. My problem is that I have never worked with vue and frontend webdevelompment in general and it seems that I first have to build this app after changing some code and then test/deploy. Is there somewhere a documentation about how to build this directus app?

# Before and after screenshots:
<img width="1770" alt="before" src="https://user-images.githubusercontent.com/9008901/52784491-9748e100-3055-11e9-882e-4c7a2af01641.PNG">

<img width="1790" alt="after" src="https://user-images.githubusercontent.com/9008901/52784500-a0d24900-3055-11e9-97bd-114bd4d8a67d.PNG">

Versions I'm using inside Docker:
Api: 2.0.17
App: 7.0.17

**Comment by rijkvanzanten** [comment]
You can clone the repo, run `npm install` to install the dependencies and run `npm run dev` to work on it 🙂 

I think you're right about the proposed change.

For reference; those lines are here: https://github.com/directus/app/blob/ef4967ba61f40749f641a4f256c64741f95ac472/src/components/form/field.vue#L193-L195

**Comment by PostPollux** [comment]
Ok, I have changed it, built the app and testet it. Everything worked as expected. Was actually pretty easy.
But now I'm a bit confused with making the pullrequest.
Under "Contributing" you say: "Submit all pull-requests to the development branch of our api and app repositories."
Well, there ist no "development" branch in this repository. Do you mean the master branch? Why are there almost no merge commits in this repository? Are the pullrequests always rebased?

**Comment by rijkvanzanten** [comment]
Master branch is fine! We squash merge PRs.

**Comment by rijkvanzanten** [comment]
@PostPollux Thanks for the PR :)

Where did you find the reference to the development branch?

I fixed this one instance but was wondering if you came across it anywhere else

https://github.com/directus/docs/commit/9d9164ada9a1d71dad4233a840d8f709464ef6d3

**Comment by PostPollux** [comment]
@rijkvanzanten Well, it's directly in the README.md at line 91 of this repository
