### ISSUE TITLE
Option to stay logged in

### ISSUE THREAD

**Issue by jorauch** [directus/app#1342]
# Feature Request
I would like to have an optional "stay logged in" option on the login form.

## What problem does this feature solve?
I do not have to enter my password every time I close my browser window.

## How do you think this should be implemented?
- a parameter in the settings
- a checkbox on the login form
- with a cookie 🍪

## Would you be willing to work on this?
Sure, but I'm a project manager and not a programmer.

**Comment by benhaynes** [comment]
Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
As of right now, tokens that keep you authenticated you expire in 5 minutes. We could potentially make the timeout of the token an option, so you can keep authenticated.

However, that would mean that the token has to be valid for days, which might be a security risk 🤔

**Comment by benhaynes** [comment]
Is it possible to have this time (currently hardcoded to 5m) be dynamic based on a config/setting? We can have a _huge_ warning about how this is a big security issue... but let admins do what they want.

**Comment by samvasko** [comment]
Is it a bigger than being logged into github?

**Comment by benhaynes** [comment]
I believe this token is different than being logged in to the SSO provider... right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
I think @samvasko meant staying logged in to GitHub vs staying logged in to Directus. If GitHub can keep you logged in safely, so should Directus.

I don't know enough about the specifics of how GitHub implemented their auth, but we've always played it on the safe side with auth for Directus.

We could extend the expiration time of the token to days or even weeks, but I just don't know what the security implications are of that. I'd rather keep it overkill secure and play it safe than potentially open up a security risk....

**Comment by rijkvanzanten** [comment]
Based [on this SO response](https://security.stackexchange.com/a/120227/185021), this is what we think we should do:

* Increase the expiration time from 5 minutes to 15 minutes so the app has to refresh a little less often
* Allow refreshing the token _after_ it has expired
* Only allow refreshing up 'til 7 days after the token has expired

An active token _does not_ get checked with the database again. If the encrypted payload verifies the servers encryption it's accepted and you're authenticated as the user. The refresh will read the user from the database fresh, which gives the API a chance to kick you out if your status has changed.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
