### ISSUE TITLE
Warn user if length doesn't match interface requirements

### ISSUE THREAD

**Issue by surfmuggle** [directus/app#1346]
# Bug Report

## Steps to Reproduce

1. Go to the demo site https://directus.app/
2. Click on 'sign in'
3. Move mouse down and move over 'admin user'
4. In the menu that open click on 'admin settings'
5. On the page https://directus.app/#/settings click on 'collections and field'
6. Create a new collection by clicking on '+' in the top-left-corner
7. Create a new collection by entering a name 
8. Click on new field and add a WYSIWYG field under options for 'MySQL Datatype' pick 'varchar'
9. click next and then save
10. try to find the created field

## Expected Behavior
A new WYSWYG field is added

## Actual Behavior
No field is added to the collection
## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Firefox 65.0.1. 64 bit
- Web Server: this test was done on your demo instance
- PHP Version: unknown
- Database: unknown
- Install Method: not installed i was using the demo

**Comment by benhaynes** [comment]
What are you thinking @rijkvanzanten ? It seems the best thing is to allow the admin to do whatever, but warn them with a notification if their interface/lengths don't match.

**Comment by rijkvanzanten** [comment]
> with a notification if their interface/lengths don't match

The max length is based on all the other lengths of columns int the same row, so it's incredibly hard to calculate the max length that is remaining. A safer option would be to set a upper limit for VARCHAR to something sensible. Eg if you use over 30k characters in a VARCHAR, a TEXT would be a better fit.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
