### ISSUE TITLE
Tabular Listing Styling

### ISSUE THREAD

**Issue by benhaynes** [directus/app#135]
A few things:

* [x] Currently, the sorted column header moves down 1-2px when activated (probably due to the icon). Let's fix
* [x] I'm seeing `fields-undefined` in front of column names
* [x] the dashes should be removed from column names
* [x] If a column header is too long, it should ellipses and show full on hover (not wrap)
* [x] If you make a column less wide than the header allows, data becomes misaligned (should be fixed by previous item)
* [x] Checkboxes should have hover style and use "pointer" cursor
* [x] Checkboxes (or leftmost item cell) should align with breadcrumb perfectly (see below)
* [x] Darken the vertical "resize" line you are directly over on hover

![screen shot 2018-04-13 at 10 38 42 am](https://user-images.githubusercontent.com/522079/38741234-79fa9502-3f07-11e8-8c6f-e7debf542f1b.png)

![screen shot 2018-04-13 at 10 42 51 am](https://user-images.githubusercontent.com/522079/38741238-7cf943de-3f07-11e8-8330-9c7702eddfc0.png)

**Comment by rijkvanzanten** [comment]
- [ ] Change row-height to 40px (ex border)
