### ISSUE TITLE
Add multi language support to the collection table view 

### ISSUE THREAD

**Issue by yarick2000** [directus/app#1351]
# Feature Request
Please add support for multi language  to the collection table view
## What problem does this feature solve?
Will allow to quickly identify problems with translated data
## How do you think this should be implemented?
By adding combo with available languages on top of the screen (in case if there are translatable fields for the currently opened collection and table currently showing those fields). When user switching between languages all the fields that have translations for the selected language will update their values with the related ones from translaltions table. 
![image](https://user-images.githubusercontent.com/13006578/53121549-746d6f80-3522-11e9-8da2-7bc59318c3d2.png)

## Would you be willing to work on this?
I don't have required skills for that right now.

**Comment by benhaynes** [comment]
It seems like this would be best accomplished with a custom layout... something like `multilingual-tabular`

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
