### ISSUE TITLE
Show list of languages for existing translations when user hovers over the translations field in the table view

### ISSUE THREAD

**Issue by yarick2000** [directus/app#1352]
# Feature Request
Show list of languages for existing translations when user hovers over the translations field in the table view
## What problem does this feature solve?
Will give more specific information about translated data to translators
## How do you think this should be implemented?
![image](https://user-images.githubusercontent.com/13006578/53122753-64a35a80-3525-11e9-997e-0cac7240b386.png)

## Would you be willing to work on this?
I don't have required skills for that right now

**Comment by benhaynes** [comment]
I think we're already showing this dropdown for the main O2M interface... so this should be easy to implement.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
We can enhance it even more by showing languages and how much has been entered for them:

![image](https://user-images.githubusercontent.com/9141017/70834908-8bd75b00-1dc9-11ea-99a0-508fe3da7564.png)
