### ISSUE TITLE
Overview of a custom collections lacks column (Name, Title)

### ISSUE THREAD

**Issue by surfmuggle** [directus/app#1353]
# Bug Report

## Steps to Reproduce

1. Go to demo site and log in
2. Open https://directus.app/#/settings/collections 
3. Create a new collection with the name 'manufacturer'
4. add a 'text input' field and set the name to  'name' or 'title'
5. save the collection 
6. Go to the collection https://directus.app/#/collections/manufacturer and click the Button 'New'
7. create an entry and enter strings into the field you created (either name or title) save it
8.  Go back to the collection overview https://directus.app/#/collections/manufacturer 

## Expected Behavior
The column name or title should appear in the list

## Actual Behavior
Regardless if you picked name or title or both field the overview only contains other fields.

## Technical Details

- Device: Desktop
- OS: Windows Server 2016
- Browser: Firefox 65.0.1
- Directus App: from the demo site
- Directus API: demo site
- Install Method: none

**Comment by rijkvanzanten** [comment]
This seems to be working on my end...

Can you share a dump of the database so I can reproduce the exact environment?

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/9141017/53753936-80d9bc80-3e80-11e9-8b40-21eee1e6b124.png">

**Comment by surfmuggle** [comment]
I was unaware that new fields have to be selected to be displayed 
![directus_collection_manufacturer_select_fields_and_set_order](https://user-images.githubusercontent.com/1271555/54643045-4c781a00-4a96-11e9-9a65-e7dc182ad7ad.png)

I was now able to show the field "Name" of the new collection "Manufacturer". This issue can be closed. 
I was confused because i did not expect that i had to select which fields should be displayed.
