### ISSUE TITLE
Simple Confirmations/Modals

### ISSUE THREAD

**Issue by benhaynes** [directus/app#136]
For simple modals, we should have an option to use a "simple" version instead. Let's emulate the previous style in 6.x:

![screen shot 2018-04-13 at 10 51 32 am](https://user-images.githubusercontent.com/522079/38741779-babbc33a-3f08-11e8-8d98-9304332fb4a1.png)

Simple Modal Changes:
* No header
* Less width
* No border on footer

Global changes:
* Buttons should have a minimum width
* "Cancel" should be a lighter gray than normal text

**Comment by rijkvanzanten** [comment]
Closed in #222
