### ISSUE TITLE
Default dropdown template format is misleading

### ISSUE THREAD

**Issue by jmeyo** [directus/app#1364]
# Feature Request
When using many to one relation, the dropdown options by default placeholder should show the ID 

## What problem does this feature solve?
If you don't pay attention, the dropdown will just show empty options without names on them.Showing the ID would at least show that there is data and it could help the newcomers to understand they should map this dropdown fields with the correct attributes.

## How do you think this should be implemented?
The default placeholder for now shows {{title}} - {{author}}, which most probably map to nothing, so showing the related ID by default would be better.

## Would you be willing to work on this?
I am still a bit new here and short on time at the moment, but I could have a look somehow

**Comment by shealavington** [comment]
:+1: 
Sounds like a good idea; Instead of doing this at the field setup and having `{{ id }}` as a default template, this should be done on rendering the record. This means that if there's no field template to render, it should display the  `ID` field by default leaving the placeholder in place to explain that you can customise the template however you need.

**Comment by benhaynes** [comment]
This is a little more complex since the admin can use any name for the primary key... not just `id` (for example they might have something weird like `cust_id`).

Ideally this looks for the PK field and shows that instead of hardcoding `id`.

**Comment by shealavington** [comment]
Touché Ben. 

Thinking about it more broadly, as there can only be one primary key per collection, I believe we could do a collection lookup for the type: primary_key field then use that field name as the default. 

Good early spot though 😉👍

**Comment by rijkvanzanten** [comment]
I think the application already calculates what the primary key is, but I might be mistaken

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
