### ISSUE TITLE
Adjusting size of the field to the left hides name of the field. Not able to revert this.

### ISSUE THREAD

**Issue by andriipol** [directus/app#1365]
# Bug Report

## Steps to Reproduce

1. Go to a collection
2. Adjust the size of the field to the left
3. See the empty field name. After this not able to adjust the size of the field and name of the field is empty
![bug_directus_fields_adj](https://user-images.githubusercontent.com/12764733/53483383-0bd64380-3a8a-11e9-9524-fc54c3416f4c.png)

## Expected Behavior
to see the name of the field and able to adjust
## Actual Behavior
 There is the empty field name. After this not able to adjust the size of the field and name of the field is empty
## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch of `directus/directus`]

**Comment by benhaynes** [comment]
I don't have a problem with the field name being hidden, I actually think it's useful if you want to hide it or it's really long and needs to be truncated. BUT, users should _always_ be able to re-expand it. I think we should toggle to a simple "lightest-gray" icon (like a dot) if the column width goes below 20px (or something like that). That way there's something in the header to click for sorting, and you always have enough room to drag it wider again.

**Comment by andriipol** [comment]
I've found, if you adjust to the left too much, the size of that column is less than 0  in 'directus_collection_presets' table. As a result, I'm not able to adjust it back or see the name of the filed.
The only solution to fix the size in DB. 
![image](https://user-images.githubusercontent.com/12764733/53500317-c37f4b80-3ab2-11e9-8c30-d32f3d939932.png)

**Comment by benhaynes** [comment]
That's weird — seems like an easy fix though. We just need to add a conditional to the App, something like:

```
width = (width < 20) ? 20 : width;
```
