### ISSUE TITLE
Comma displayed with single checkbox item

### ISSUE THREAD

**Issue by srjrol** [directus/app#1367]
# Bug Report

## Steps to Reproduce

1. Create a collection 'test'
2. Create a field of type 'checkboxes' and use the following JSON for the 'choices' setting in the options tab:
`{
"a": "a",
"b": "b",
"c": "c"
}`
3. DO NOT 'wrap the saved value in a delimiter (improves searchability)' 
Side note about this option:  when I check it, I can no longer see the choices I have selected using the checkboxes when viewing the collection containing the field in its table view.  

4. Choose to show display text or not, the issue here persists either way.
5. Save the new field.
6. Create a new item in the collection and choose one choice. 
7. Notice in the table view of the 'test' collection there is a comma before the single choice that was selected.  

## Expected Behavior

A comma should only preceed the second or more choice.  No comma should be displayed for a single choice.

## Actual Behavior

In the table view of a collection, when a single choice is made with a checkboxes field type, there is a comma displayed.

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/34398302/53598443-5cbd6900-3b6a-11e9-8c69-ac1172ec6a33.png)
![image](https://user-images.githubusercontent.com/34398302/53598449-5fb85980-3b6a-11e9-8b00-f0ad70503505.png)
![image](https://user-images.githubusercontent.com/34398302/53598452-61821d00-3b6a-11e9-8f19-ff00c64c6781.png)
![image](https://user-images.githubusercontent.com/34398302/53598454-634be080-3b6a-11e9-857a-7d28042babb7.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Latest Chrome
- Directus 7.0.18
- Install Method: Cloned `master` branch of `directus/directus`

**Comment by UnderscoreDesign** [comment]
This is not fixed. It still occurs in 7.1.0. The commas are being written to the database. And, I experience the extra commas when I make multiple checkbox entries as well as a single entry. I don't experience it if I create a new item and save it before I try to enter any checkbox data. Then I can open it again, enter the checkbox data, and save it again.. and no extra commas appear.

**Comment by rijkvanzanten** [comment]
Do you have the "wrap" option turned on @UnderscoreDesign?

**Comment by UnderscoreDesign** [comment]
No, the wrap is not on. 

Kent
