### ISSUE TITLE
Unable to open new page/tab from generated links

### ISSUE THREAD

**Issue by srjrol** [directus/app#1369]
# Bug Report

## Steps to Reproduce

1. Login to app
2. Open a link to another page  in a new tab or window.

## Expected Behavior
New page/tab is opened and the contents are shown.

## Actual Behavior
New page/tab opens a blank page or 404 error.  (unless using a second login/session).

The URL used for a new tab/page is missing the #.  If I try to visit the URL with # manually it doesn't load in a new window/tab either.  In my instance I get the same blank page, on the demo it takes me back to login screen.

https://directus.app/#/collections/kiosks
https://directus.app/collections/kiosks

## Other Context & Screenshots

![no_new_tab_or_windows](https://user-images.githubusercontent.com/34398302/53647929-377d3900-3c04-11e9-9668-a845bc5381b7.gif)

Shea [9:04 AM]
Looks like a bug Sean, if you could open an issue on the /directus/api GitHub repo, that'd be great. 
— Though I thought that the vue-router (`<router-link>`) took care of putting the hash in based on its configuration
## Technical Details

- Device: Desktop
- OS: Windows 10 64bit
- Browser: Chrome (latest)
- Directus App: 7.0.18
- Directus API: 7.0.18
- Install Method: cloned `master` branch of `directus/directus'

**Comment by samvasko** [comment]
This can be fixed with following patch. 
I am not sure why the code was there beforehand. So this might introduce some other problem. Maybe someone else can vouch in.

Additionally, this does not really solve anything as you get redirected to login screen and you don't get redirected to the link you clicked once you logged in. So 🤷‍♂️ 

```patch
diff --git a/src/components/sidebars/nav-sidebar/nav-menu.vue b/src/components/sidebars/nav-sidebar/nav-menu.vue
index 341cbe5..22cb3a9 100644
--- a/src/components/sidebars/nav-sidebar/nav-menu.vue
+++ b/src/components/sidebars/nav-sidebar/nav-menu.vue
@@ -4,14 +4,7 @@
     <nav :class="{ 'no-border': noBorder }">
       <ul>
         <li v-for="{ path, name, icon, color } in links" :key="path">
-          <component
-            :is="path.startsWith('http') ? 'a' : 'router-link'"
-            :to="path"
-            :href="path"
-            target="__blank"
-            rel="noopener noreferrer"
-            :class="color || null"
-          >
+          <router-link :to="path" :class="color || null">
             <i v-if="icon" class="material-icons icon">{{ icon }}</i>
             <svg v-else class="icon" viewBox="0 0 17 18">
               <path
@@ -20,7 +13,7 @@
               />
             </svg>
             {{ name }}
-          </component>
+          </router-link>
         </li>
       </ul>
     </nav>
```

**Comment by rijkvanzanten** [comment]
The original code was there because there were plans to add a navigation override option that would allow you to add links to external sources as well. These external sources would have to be rendered as an `<a>` tag.

**Comment by srjrol** [comment]
Should this be a feature request now?  I thought the fix would be to have a page/tab open with the link you click, not a redirect to the homepage which is what I am seeing after updating to 7.0.19.  

As samvasko said:
> this does not really solve anything as you get redirected to login screen and you don't get redirected to the link you clicked once you logged in.

**Comment by benhaynes** [comment]
Hmm, it should pass the `ref` or page... @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
It's because we're using session storage to keep track of the user logged in status. A new tab will be considered to be a new session in most browsers.

It's either this, or we won't be able to be logged into two projects at the same time (which is the reason we switched to sessionStorage)
