### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by benhaynes** [directus/app#137]
We should have the logo/rabbit run when things are processing (we can define levels/scope for loading). I think we should just emulate/copy the previous 6.x functionality since that sprite worked reasonably well.

If the instance is using a custom logo, then the rabbit fades in/out over that logo when loading (similar to 6.x).

**Comment by rijkvanzanten** [comment]
The loading indicator is going to be interesting.

I think I will have to keep a global “queue” of active loading processes.
Cause it needs to run if something is doing something.
But it only needs to stop if everything is done.
But we don’t want it to run every 5 seconds when we check for latency.
So there is a difference there too.

**Comment by benhaynes** [comment]
The Vue progress indicator (#331) doesn't feel right – maybe because the logo area is already blue. The timing also seems off and sometimes the page fully loads and it still shows progress for 20s+. 

To keep things simple, we should plan on the running rabbit being the main/only global loading indicator. It's indeterminate, but we could always add a `3/4 Tasks` or something in there to add more context.

**Comment by rijkvanzanten** [comment]
The progressbar has been removed in the meantime
