### ISSUE TITLE
Show Versions and Change-log in Settings

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1370]
@shealavington pointed out that we can use the GitHub API (publicly) to pull in the live versions to see if someone needs to upgrade. A useful pane for Settings!

Ref: https://github.com/directus/directus/issues/2296

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
