### ISSUE TITLE
m2o on primary key of type string stored but not displayed

### ISSUE THREAD

**Issue by foxable** [directus/app#1372]
# Bug Report

## Steps to Reproduce

1. Create a Collection with a primary key field of type string and add at least on item to it
2. Create a second Collection with a m2o field of the same type referencing the primary key
3. Add a new item to the second Collection which references an item from the first collection

## Expected Behavior
The referenced item is displayed both in the table view of the second collection and the form view when editing an item.

## Actual Behavior
The displayed value is `--` in the table and the dropdown in the form view shows the placeholder.

## Other Context & Screenshots
The actual value is correctly stored in the database. This seems to be a display issue only.

**Comment by shealavington** [comment]
Hmm — I'm not sure where this issue stands, or how to proceed with fixing this.

It seems it's now difficult to set the PK of a collection to a string. You can set the `Field Type` to "String", however, it would cause issues as it's still set to "Auto-Increment" in the database, therefore, you can't change the `MySQL Datatype` to anything string-based through the app (tinytext) as it'll throw an error, rendering string based PK's in the app, virtually impossible currently...

The only way I can see this happening now, is if you create a custom table with a string PK, then started "managing" it.

**Comment by benhaynes** [comment]
I think this is an issue when creating the schema directly in the database. That said, we should probably allow configuring your PK during Collection creation since it can't be changed after.

**Comment by rijkvanzanten** [comment]
Right now the application doesn't support creation of string type primary keys.. I'll close this issue until https://github.com/directus/app/issues/1929 is implemented.
