### ISSUE TITLE
Form field incorrectly rendered when adding a translation field

### ISSUE THREAD

**Issue by agseco** [directus/app#1376]
# Bug Report

## Steps to Reproduce

1. Add a new _Translation_ field to a collection
2. Complete the field details until you get to the _Options_ field
3. In the _Options_ field, there is a form field that is not properly rendered

## Expected Behavior

It should show the actual form field text (not sure which it should be since I'm new to Directus).

## Actual Behavior

It shows the template variables instead.

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/7592823/53944905-a5bc7280-40c0-11e9-8d28-353d9fae24a2.png)

I have reproduced it both locally and using the online demo.

## Technical Details

- Device: Desktop
- OS: MacOS 10.13.6
- Browser: Version 72.0.3626.121 (Official Build) (64-bit)
- Directus App: 7.0.18 (local) / 7.0.17 (online demo)
- Directus API: Unknown
- Install Method: Docker/Online demo

**Comment by dev7ch** [comment]
@benhaynes this is fixed and  merged ;)

**Comment by agseco** [comment]
Alright, then it will be fine in a new release. Thanks for the prompt reply! :)
