### ISSUE TITLE
Export table view to CSV

### ISSUE THREAD

**Issue by srjrol** [directus/app#1377]
# Feature Request
I find the information I can view through the tables useful but it doesn't appear I can export it outside of the database which would be useful.  Export table view with displayed values to CSV.
## What problem does this feature solve?
If exporting from database directly, it only shows the relationship not the actual values.
## How do you think this should be implemented?
Additional option in the INFO section of the table view.
## Would you be willing to work on this?
Willing but unfortunately incapable with my current understanding.

**Comment by srjrol** [comment]
#711

**Comment by llmuculusll** [comment]
+1
