### ISSUE TITLE
Selecting existing files is broken in modal editor

### ISSUE THREAD

**Issue by thathoff** [directus/app#1378]
# Bug Report

Selecting existing files inside the overlay editor from a one to many relation field does not work. Editing the same field from the Collection view works. 

## Steps to Reproduce

1. Create a Collection (Collection1) with a file field
1. Create another Collection (Collection2) with a one to many relation to Collection1
1. Create an item in Collection2 and create a linked item of Collection1
1. Save the item
1. Edit the item
1. Try to add an existing image to Collection1 item inside the “Edit Item” modal view
1. The item cannot be selected. Using the regular edit view of Collection1 item and updating the picture there works. Uploading a new picture works, too.

## Expected Behavior

The picture can be selected

## Actual Behavior

No picture can be selected

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.3
- Browser: Chrome 72.0.3626.119]
- Directus App: 7.0.18
- Directus API: 2.0.18
- Install Method: cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
This is fixed in https://github.com/directus/app/pull/1804
