### ISSUE TITLE
Filter: Add "X" when there's a query or filters

### ISSUE THREAD

**Issue by benhaynes** [directus/app#138]
Similar to v6.x – whenever there are filters/query active, there should be an "X" to the right of the input that clears all. The "X" should hover red. Also, icons in the input should be a lighter gray.

![screen shot 2018-04-13 at 10 59 34 am](https://user-images.githubusercontent.com/522079/38742155-c88e1c8c-3f09-11e8-816f-0bdcd3584201.png)

**Comment by rijkvanzanten** [comment]
> Also, icons in the input should be a lighter gray.

The contrast between the icon and the search field is already a bit tight as is.. I won't decrease the contrast the important filter buttons even further
