### ISSUE TITLE
Details/Summary title are incorrect in modal

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1384]
The way we have the details/summary designed, it blocks the border with a background color... however this color is either white or light-gray based on where it's used. Maybe this isn't an issue in the upcoming design though... so we can add this to `refactor`.

![Screen Shot 2018-12-19 at 1 39 53 PM](https://user-images.githubusercontent.com/522079/54215251-02070400-44be-11e9-83a1-68e658319e1f.png)

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/58212719-c8245c00-7cbd-11e9-9f52-21ce9e8e2841.png)

This was taken care of in the design update
