### ISSUE TITLE
Check for active relationships before deleting items

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1385]
# Feature Request

When an item is being related to from another item, we should show a warning before submitting a delete request.

## What problem does this feature solve?

Right now, you can delete an item regardless of it being used somewhere else, which might break your project that's relying on this data.

## How do you think this should be implemented?

Right before the application is about to send the delete request, we should verify if the item is used relationally somewhere so the user has a chance to abort the deletion of the item.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
We should be able to find active relationships from the front-end by combining the info we have in the store about relationships from a field + doing some fetches to the api with filters trying to read if there's rows

**Comment by cbix** [comment]
There is already a _Delete mode_ setting for O2M fields, but this (very confusingly) only applies to "deselecting" related items.
I would propose to solve this issue by providing 3 delete mode options that apply both to deselecting a related item and deleting the root item:

1. Delete related item
2. Nullify relationship
3. Refuse deletion

![Screenshot from 2020-09-03 16-30-36](https://user-images.githubusercontent.com/1295945/92128773-05552480-ee03-11ea-8bfc-3f7c2a1c303f.png)

Our project has a `user` collection and a `device` collection, with a 1:n relation. Currently I have to make 3 separate API requests when deleting a user:

1. GET items/user/:id?fields=devices.*, then process the nested results
2. PATCH items/user/:id `{ device: [{ id: ..., $delete:true }, { id: ..., $delete:true }] } `
3. DELETE items/user/:id

I know the current delete mode is only used in the frontend which makes the right requests when deselecting items, but maybe you could consider providing an option to use a deep deletion mode. Of course it could be dangerous if you have a lot of relations and suddenly your whole collection gets emptied or there are huge circular relations so I agree that this is not trivial to implement.
