### ISSUE TITLE
Clicking "Manage" collection requires refresh

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1386]
When clicking "manage" on a collection that was added directly to the database, it doesn't do anything. But then when you refresh the page it shows the correct button change.

**Comment by Nitwel** [comment]
Well, it works for me perfectly fine but I experienced this issue in older versions too.
The only thing that is a bit "confusing" is the time it takes until it updates:


![GIF](https://user-images.githubusercontent.com/22577866/54438898-f6bf0d00-4737-11e9-9128-c587726e5efd.gif)

**Comment by benhaynes** [comment]
That's odd, I just tested again and it's still not working for me:

1. Open `/settings/collections`
2. Go to database (using Sequel Pro)
3. Add new table (called `test`, it auto adds an `id` PK column)
4. Refresh Directus (and you can see the new `test` collection
5. Click "Manage" (nothing changes)
6. Refresh page and the change is seen

I do see some stuff happening in the browser network tab, but I get no Directus notification or change until I refresh. I'm using my private beta project in Directus Cloud if that makes a difference.

**Comment by rijkvanzanten** [comment]
I can confirm that this is working as expected in 7.0.19. We'll debug the cloud api separately
