### ISSUE TITLE
M2M Interface needs drag/drop sort

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1388]
This was in v6 and I'm really surprised we missed it. If the junction collection has a `sort` field then we need to allow for dragging and dropping items into a manual new order.

**Comment by amandahaven** [comment]
Is there any other way to organize M2M elements currently?

**Comment by benhaynes** [comment]
Surprisingly, no. @rijkvanzanten since we have the code for drag-and-drop, would we be able to fit M2M reorder in soon? Any idea on how long it would take?

**Comment by benhaynes** [comment]
@amandahaven — As a workaround, you can add a `Number` field and save `1`, `2`, `3`... in it for manual ordering. That way when we add support for the `sort` interface things will just work.

**Comment by brocgailit** [comment]
@rijkvanzanten — Noticing you added and removed this from the **In progress**.  Is this something that's still being worked on and/or do we have an ETA?
@benhaynes — As far as implemenation, You're suggesting using a  `Number` field in the junction table, correct?  Should this have a specific name such as '`sort`'?  (I haven't looked too much into the code base to know if you have a naming convention for this.)

**Comment by rijkvanzanten** [comment]
@brocgailit It took more time to implement than I'd imagined, so it didn't make the cut for that release. It's on the list of priority features, but I can't promise any ETA.

This will rely on there being a `sort` type field in the junction collection. You can name this field whatever you like, as long as it's of the `sort` type.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by polgiron** [comment]
hey guys any update on this please? thank you!

<img width="671" alt="Screen Shot 2019-09-25 at 15 05 29" src="https://user-images.githubusercontent.com/8901804/65603429-f1276700-dfa5-11e9-806a-076bc747c298.png">

there is still no way to re-order a many-to-many field :(

**Comment by benhaynes** [comment]
No official update, but our team will be back into feature requests (like this) within the next 3 weeks... so we'll finally be able to get these added in.

**Comment by kieranwt94** [comment]
Hey is there any update on this one? Thanks

**Comment by MrParano1d** [comment]
Any updates? Here you're saying, that you added it: https://github.com/directus/app/pull/1500 but I don't see the feature in version 8.8.1

**Comment by benhaynes** [comment]
You need to add a sort column to the junction table, did you try that?
