### ISSUE TITLE
Optional Layout Footer

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1390]
Not sure if it should be global or specific to a layout (table or spreadsheet) but a fixed footer option on the browse page would be nice for calculating `sum`, `avg`, `min`, and `max` of number/date/time types. Could also have char-count for string (not sure how easily SQL can return that though) and other functions.

My only concern is if this would work within pagination or for the entire dataset.

**Comment by theharshin** [comment]
I would also recommend adding configurable support for pagination. 
We can add an overview kind of cards on top of the table which will represent an entire dataset, while in the footer it will be related to only shown datasets.

**Comment by benhaynes** [comment]
Ahh, good point. It's powerful to have this footer info with filter. eg: filter data and see the sum of a column. We could have the dataset total as an option and when on display it like this:

![Screen Shot 2019-03-14 at 10 18 47 AM](https://user-images.githubusercontent.com/522079/54364096-99955f80-4642-11e9-842b-ecd59522aad7.png)

And the values could have a tooltip explaining they are `Filtered Sum` or `Total Sum`.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
