### ISSUE TITLE
Individual collection Read View

### ISSUE THREAD

**Issue by RabiCodie** [directus/app#1391]
# Feature Request

## What problem does this feature solve?
This solve the issue of having one main view to view a specific resource of w collection - e.g a company page which could be the main view and has components related to it like tasks - events - notes etc 
## How do you think this should be implemented?
adding a signe resource view as read
## Would you be willing to work on this?
have not used Vue js before so not sure if can assist but with some instructions i would be more than happy to help and assist.

**Comment by benhaynes** [comment]
Hey @RabiCodie — are you saying that you would want a Collection that only has _one_ item? Like an "About Page"? If so, we actually have that — it's called a Single Collection:

https://docs.directus.io/guides/collections.html#single
