### ISSUE TITLE
Grids and Layouting (for Frontend)

### ISSUE THREAD

**Issue by realpasha** [directus/app#1392]
# Feature Request
It would be cool if we could give the authors more creative freedom with a special layoutable component in Directus.
A good example would be Cockpit with its Layout-Field  (https://twitter.com/getcockpit/status/898848619020914688).

**Example:**
As a user, you can create the following structure in Cockpit using the layout field:
![gh_issue_cockpit_layoutfield](https://user-images.githubusercontent.com/42383071/54358858-9eb5d700-4661-11e9-800a-2c1826cfa4f8.png)
To generate the following output (e.g. rendered with Gatsby):
![gh_issue_layout_example](https://user-images.githubusercontent.com/42383071/54358911-c016c300-4661-11e9-800e-23ad57a57fc7.png)
A user could independently insert another button or an additional image without the need of changing attributes of the model.

<details>
  <summary>Cockpit provides the following JSON via the REST API (click to view JSON)</summary>
  <p>

```json
"content": [
	{
		"component": "grid",
		"settings": {
			"id": "",
			"class": "",
			"style": ""
		},
		"columns": [
			{
				"settings": {
					"id": "",
					"class": "",
					"style": ""
				},
				"children": [
					{
						"component": "image",
						"settings": {
							"id": "",
							"class": "",
							"style": "",
							"image": {
								"path": "any-image-url"
							},
							"width": null,
							"height": null
						}
					},
					{
						"component": "text",
						"settings": {
							"id": "",
							"class": "",
							"style": "",
							"text": "<h3><strong>Beautiful Place</strong></h3>\n<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>"
						}
					},
					{
						"component": "button",
						"settings": {
							"id": "",
							"class": "",
							"style": "",
							"text": "Read More",
							"url": "any-link"
						}
					}
				]
			},
			{
				// column 2
			},
			{
				// column 3
			}
		]
	}
]
```

</p>
</details>

This feature was initially requested by @marcobiedermann (see #773 ) - but it was misunderstood and led to a different improvement of directus.

## What problem does this feature solve?
If Directus is used as headlessCMS for a website (e.g. generated with Gatsby), the structure of content is specified by the self-defined data structures (collections).
The only possibility to "design" (for a content author) is the WYSIWYG editor.
A layout component gives a content author the opportunity to take influence on the content structure.

## How do you think this should be implemented?
Since this is the biggest challenge, implementation needs to be discussed in more detail.
There are two possible solutions that I can imagine so far:
### Using (o2m) relations
An extended o2m field type is required. Additional Collections for Grid, Button, ... are also necessary.
- The user interface of Directus has to be optimized for nested O2M relations. For this purpose, dialogs might have to be used.
- A mixed o2m interface must be provided in which whitelisted collections can be added dynamically.
- In order to make dynamic grid layouts possible, further concepts must be defined.
This variant provides the best possible separation of structure and content, but is very complex.
### storing the layout information as JSON (similar to Cockpit's Layout-Field)
Similar to Cockpit, a new field type is added. This allows you to easily create a layout.
Future migrations can be a problem, as the JSON configurations can become huge and messy. In addition, the content is not separated from the layout.
## Would you be willing to work on this?
At the moment I am not yet familiar with the development of Directus.
If the conceptual questions are completely clarified, I would like to take care of it.
However, I won't come to it in the foreseeable future.

**Comment by rijkvanzanten** [comment]
Initial thoughts on implementation:

* This will be an interface that saves a JSON object (see example output)
* Each "component" eg `image`, `text`, or `button` should ideally re-use directus interfaces.
* These components can be chosen and setup during the interface setup of the layout interface 1)

1) I was thinking the user would be able to select and configure the interfaces they want to use as components in this layout builder. As an admin you'll be able to setup a layout builder that only has images and text, or images, text, maps, relational data, etc, etc.

**Comment by benhaynes** [comment]
Makes sense, I like it! I'm curious how the dynamic architecture (user adding an image field to column 3) differs from content entry (user uploading an image to column 3). With several columns I could see these interfaces getting small for content entry (unless they each open as a modal for actual entry).

Like Rijk said, the admin side seems like it's just whitelisting/blacklisting interfaces and maybe max/min row/column count.

**Comment by realpasha** [comment]
How should we handle multilanguage?
It would be very helpful if the structure could be defined once; only the strings for the additional languages have to be customized then.

**Comment by philleepflorence** [comment]
Not sure if this helps, but below is a schema I use for content blocks like the feature requested or for form elements et al. This allows me to create numerous contents within different pages without creating specific interfaces within Directus:

```
CREATE TABLE `app_contents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sort` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(1) DEFAULT '1',
  `public` TINYINT(1) DEFAULT NULL COMMENT 'Make content public (for use in browser scripts) - by default all are private,',
  `application` VARCHAR(20) DEFAULT 'app' COMMENT 'Application to which content or content belongs: www, app, platform...',
  `name` VARCHAR(100) DEFAULT NULL COMMENT 'Name of content',
  `slug` VARCHAR(50) DEFAULT NULL COMMENT 'This is how the content is found, URL safe representation of the name of the content',
  `value` TEXT COMMENT 'Text or HTML to display',
  `section` VARCHAR(100) DEFAULT NULL COMMENT 'Select section in app where to display content',
  `category` VARCHAR(50) DEFAULT NULL COMMENT 'Additional category describing where in the page section content will be displayed',
  `privilege` TINYINT(1) DEFAULT '1' COMMENT 'User Privilege assigned to the content - useful for dynamic form contents.',
  `icon` INT(11) DEFAULT NULL COMMENT 'Icon value to display - if icon is present icon can be displayed in place of text value',
  `image` INT(11) DEFAULT NULL COMMENT 'Image to display - if image is present image can be displayed in place of text value',
  `page` INT(11) DEFAULT NULL COMMENT 'Page in which content belongs',
  `analytics` INT(11) DEFAULT NULL COMMENT 'Settings, contents, and options for Google Analytics and Events Tracking.',
  `input_type` VARCHAR(25) DEFAULT NULL COMMENT 'The different input types for the <input> element.',
  `form_type` VARCHAR(100) DEFAULT NULL COMMENT 'Type of form element to display.',
  `validation` VARCHAR(100) DEFAULT NULL COMMENT 'Validation Rules for the Form content. See: https://www.npmjs.com/package/validator',
  `attributes` VARCHAR(250) DEFAULT NULL COMMENT 'HTML Tag Attributes - Be sure to enter valid HTML attributes!',
  `source` VARCHAR(100) DEFAULT NULL COMMENT 'Path to source. E.g. listing.square_footage for Listings Square Footage from external API Data',
  `format` VARCHAR(100) DEFAULT NULL COMMENT 'Additional format to apply to content - if applicable',
  `url` VARCHAR(150) DEFAULT NULL COMMENT 'Internal or External URL Path of content - To use Page URL, enter true',
  `color` INT(11) DEFAULT NULL COMMENT 'Color of content or Content',
  `show_html` TINYINT(4) DEFAULT NULL COMMENT 'Display content as HTML or TEXT. If TEXT, HTML tags will be removed.',
  `hint` VARCHAR(250) DEFAULT NULL COMMENT 'Hint to display when user clicks, focuses, or hovers element. Useful for Form contents.',
  `section_options` VARCHAR(1) DEFAULT NULL COMMENT 'Additional options',
  `section_basic` VARCHAR(1) DEFAULT NULL COMMENT 'Basic Information',
  PRIMARY KEY (`id`),
  UNIQUE KEY `NAME` (`name`,`section`,`category`,`page`),
  KEY `APP` (`application`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
```

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
