### ISSUE TITLE
o2m field issues (creating,updating,deleting)

### ISSUE THREAD

**Issue by srjrol** [directus/app#1395]
# Bug Report
Having issues with the o2m field/interface when trying to create,update or delete items.

## Steps to Reproduce

**Creating**
1.  Create o2m field.
![image](https://user-images.githubusercontent.com/34398302/54464674-9b941700-4745-11e9-922f-4ac7c524abb2.png)
2.  Add 2 or more items.
3.  Save.

**Updating**
_Probably related to the issues creating.  I can't update to more than a single item._

1. Add a single item to the o2m field and save.
2. Re-open the o2m field and add more items.
3. Save.

**Deleting**
1.  Add multiple items to o2m field
2.  Try to delete a single item before saving.

## Expected Behavior

**Updating** the o2m field a single to multiple items should append additional items to the field.

**Deleting** items from o2m field should be possible on a per-item basis prior to saving the collection item.

**Creating** should allow multiple items as part of the o2m relationship.

## Actual Behavior

When trying to **create** only a single item is saved.

When trying to **update** notice that only the last item selected is saved and overrides the single item instead of appending to it.

When trying to **delete** a single item, all items are removed.

## Other Context & Screenshots
**Creating**
![one-to-many-create-error](https://user-images.githubusercontent.com/34398302/54461554-e5c3cb00-473a-11e9-9ccb-c848d9531f6c.gif)
**Updating**
![one-to-many-update-error](https://user-images.githubusercontent.com/34398302/54461560-e9efe880-473a-11e9-9723-9fafc1645207.gif)
**Deleting**
![one-to-many-delete-error](https://user-images.githubusercontent.com/34398302/54461567-efe5c980-473a-11e9-9424-b8181508234b.gif)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Latest Chrome
- Directus App: [eg: 7.0.19]
- Directus API: [eg: 7.0.19]
- Install Method: Cloned `master` branch of `directus/directus`

**Comment by maubambu** [comment]
Experiencing the same issue

**Comment by srjrol** [comment]
Phillip Weston also reported a similar problem when creating a new item during the addition of an item to o2m relationship.

![error](https://user-images.githubusercontent.com/34398302/54464977-f11cf380-4746-11e9-8285-ff7690cc9e9c.png)

**Comment by rijkvanzanten** [comment]
Why did you close this @srjrol? Wasn't it an issue after all?

**Comment by srjrol** [comment]
We discovered we were not creating the o2m relationship correctly.  We did not realize that a m2o relationship in the opposite direction is required for it to work.  It's possible what Phillip Weston reported on slack is still a problem.
