### ISSUE TITLE
Don't show popup when 0 items to preview

### ISSUE THREAD

**Issue by srjrol** [directus/app#1397]
# Bug Report

## Steps to Reproduce

1.  Create a o2m field within a collection.
2.  Add 0 items to the o2m field.
3.  View the collection with o2m field in table view.

## Expected Behavior

No hover popup for o2m field when no items have been chosen.

## Actual Behavior

"empty" popup appears when hovering over "No items" in the table.

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/34398302/54480242-1156bc00-47f4-11e9-9f44-a9807a31c884.png)

## Technical Details

- Device: Desktop
- OS: Win 10
- Browser: Latest chrome
- Directus App: 7.0.19
- Directus API: 7.0.19
- Install Method: Cloned `master` branch of `directus/directus'

**Comment by benhaynes** [comment]
Good eye @srjrol — we'll get this fixed...

**Comment by srjrol** [comment]
Another enhancement along these lines could be to render a single item in place of the "one item" text.  In my situation, I have many relationships with just a single item and a few with multiple.

**Comment by srjrol** [comment]
It also doesn't look like these hover popups are able to render anything for m2m collection items so maybe they should also be disabled for those and just display the # of items.
