### ISSUE TITLE
Duplicated collections

### ISSUE THREAD

**Issue by Mozz4rt** [directus/app#1398]
# Bug Report
I've set up all my collections and after refreshing the page some of them appeared duplicated on the admin. I tried going to the collections settings and deleting the duplicates but it turns out it deleted both of them each. After a deep breath and a cup of water i discovered that it happens because of collections created with capital letters in the name (a better description is shown below).

## Steps to Reproduce

1. Go to "Admin Settings" -> "Collections & fields" -> "New"
3. Create collection with "Test" (with capital T or any letter).
4. Refresh after creating the collection (the fields doesn't matter).
5. See both collections on the "Collections" sidebar. 

## Expected Behavior
Just one collection and also in the "Create Collection" an auto-fix to this (or maybe a filter on the API side).
## Actual Behavior
Duplicate Collections that are unable to fix unless you delete them and start over :(
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/20441537/54498551-3bd17380-48df-11e9-846c-00467f5df3c4.png)

After setting thing up, if you hover on each of them you can see that one link has the capital letter and the other doesn't. 

## Technical Details

- Device: Desktop PC
- OS: Windows 10 Pro
- Browser: Chrome 72.0.3626.121 64bit
- Directus App: 7.0.19
- Directus API: 2.0.19
- Install Method: Download zip and extract.

**Comment by rijkvanzanten** [comment]
We had a problem before where people where trying to use pre-existing mysql tables with camelCase names. In order to fix that, we've opened up the collection creation to allow for uppercase (and thus camelCase) names as well. Apparently, somewhere in that flow either the app or api still expects / converts the collection name to be lowercase.

**Comment by rijkvanzanten** [comment]
Hey @Mozz4rt! I don't see this problem on my side.. Not on my local copy nor [the live demo](https://next.directus.app).

Can you share some more specifics on the environment you're seeing this on? I don't know how to reproduce this further..

**Comment by dev7ch** [comment]
this sounds like a camel case issue.

e.g. if one collection is renamed or somehow the DB name is changed the Admin UI doesn`t seem to respect a camelCase naming.

So then this could be overwritten, maybe having a look at the delete or update methods would

**Comment by rijkvanzanten** [comment]
That could be, yeah. Directus didn't use to support casing in database names before, so everything was build with lowercase names in mind. With all these issues popping up, and seemingly low benefit of having cases in names, should we revert the casing change and go back to only allowing lowercase names?

**Comment by dev7ch** [comment]
mmh, actually I think would be great to leave the DB casing untouched.

image to use Directus a a drop in extension for large databases it could not so nice if a collection which you decide to manage gets corrupted be the casing on updated.

Coz currently you can start managing any casing of DB table names in Directus, but forcing the casing would be decrease the flexibility hard imo.

**Comment by benhaynes** [comment]
I think we need to resolve the case issues, since a big part of Directus is mirroring the database. This includes managing existing databases and being able to make edits directly in the database through a client (not only the Directus App). It shouldn't be that difficult to keep all schema names as-is and use our formatter for presentation only.

**Comment by Mozz4rt** [comment]
Hello! Sorry for the late response.. Weekdays are harsh for me. @rijkvanzanten here is a step-to-step to what i did and also all the system info i could gather.
1. Got the 7.19 version directus suite .zip and extracted it into a new folder.
2. Installed into a fresh database
3. Go to settings -> Collections & fields -> New Collection
4. Insert the name with camel case or any uppercase letter (as said by dev7ch)
![image](https://user-images.githubusercontent.com/20441537/54882141-649cc000-4e2d-11e9-894e-66a3fc708a19.png)
5. Refresh the page
6. See the duplicate databases
![image](https://user-images.githubusercontent.com/20441537/54882151-8bf38d00-4e2d-11e9-8644-ff3023794b2d.png)

Well.. from the fact that if you delete either of the databases you delete both of them at once, i'm guessing that the problem here is with the app.

Using WAMP 64 v3.1.7
Apache 2.4.37 Port 80- PHP 7.2.14
MySQL 5.7.24 Port 3306
MariaDB 10.3.12 Port 3307
PHP 5.6.40 for CLI (Command-Line Interface)
Windows 10.0.17763 build 17763
Google Chrome v73.0.3683.86 64 bit

Also, here are the files..
[directus-master.zip](https://github.com/directus/app/files/3000553/directus-master.zip)
[directus.sql.zip](https://github.com/directus/app/files/3000554/directus.sql.zip)

**Comment by rijkvanzanten** [comment]
Ahh I see. Thanks 👍 

We've seen a lot of issues regarding the uppercasing in collection names, so we have decided to revert this functionality in the app for the time being until we figure out how to enable it without things breaking left and right..
