### ISSUE TITLE
Relation field not showing data with 3 levels join

### ISSUE THREAD

**Issue by Mozz4rt** [directus/app#1399]
# Bug Report
On the details page of a collection item with a M2O relationship, after i create the item and check it it shows all the other joins except the one from the one assigned to it. 
In other words, if i am at Collection1 and have a M2O field to Collection2 (let's call it RelField) that has a Dropdown Template of `{{field1}} - 
{{Collection3.field}}`. After creating an item in this collection and filling up "RelField" it shows up "field1 - " on the details page (notice the blank space in the join) but shows up normal in every other option in the select (all the other choices show up just fine) and in the browse page. 

## Steps to Reproduce
1. Create `Collection1` with field Name (Text).
2. Create `Collection2` with a M2O relationship with `Collection1`.
3. Create `Collection3` with a M2O relationship with `Collection2` and a Dropdown Template that joins information from `Collection1`.
3. Create one item with a random name in `Collection1`.
4. Create one item in `Collection2` that relates to the item created in step 3.
5. Create one item in `Collection3` that relates to the item created in step 4.
6. Enter description page of the item created in step 5.
7. Click the Dropdown and see that all items have correct info except the one that is assigned to the item created in step 6 (wich is blank). 

## Expected Behavior
Show info from the Collection1 that is assigned to the selected option to the current item.
## Actual Behavior
Showing up a blank space where the info from Collection1 should be.
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/20441537/54499053-24e15000-48e4-11e9-84b5-73dfaae1c5b1.png)
It's in portuguese, "Horario" means "Schedule". "Selecionar Atividade" means "Select Activity" 
The first one (that has the blank value after the time) is the one assigned to the current item.

## Technical Details

- Device: Desktop PC
- OS: Windows 10 Pro
- Browser: Chrome 72.0.3626.121 64bit
- Directus App: 7.0.19
- Directus API: 2.0.19
- Install Method: Download zip and extract.

**Comment by Mozz4rt** [comment]
Another big question that i've been asking myself for weeks related to showing up info is how to work with the "Listing View Preferences". There is no reference to that in the docs or anywhere i've searched.. Tried to mine the code from the App repo but had little success.. If any lead programmers could at least show me a direction where the code related to that would be i'd be very grateful, happy and willing to contribute to the docs.

**Comment by rijkvanzanten** [comment]
The idea of the listing view preferences is that you could use the object syntax of the directus_collection_presets collection in order to pre-configure certain filter and view options for the M2O.

I feel like the issue you mention for the dropdown specifically is very similar to #1402 correct?

**Comment by Mozz4rt** [comment]
Thanks for the reply! Nope.  It's tricky to show you but it's exactly what i've described. 

In the screenshot, the first one have a m2o to another collection that have a m2o to `directus_users`. The value that is assigned to the "Horarios" field is not showing the `directus_users` data while the rest of the options (that weren't selected) are showing it up just fine. 

For example, if i choose the last item as the current item for the select, it's `directus_users` data won't show up and the rest will show up.

(note that i am not using the user field because it does not support field joins via the dropdown template, it's a normal m2o)

**Comment by urvashithakar** [comment]
`fetchItems()` method of input.vue[interfaces/many-to-one/input.vue] returns items [with full nested object] and while updating collection item; it also stores the selected object of PK [without nested object] in items by doing another API call. So the items have two data with the same id and it overrides the dropdown menu options. This is the cause of displaying the blank item which is mentioned in the above screenshot.

So if we stop calling API for selected PK we can solve these issue.
@rijkvanzanten Let me know your thoughts.

**Comment by rijkvanzanten** [comment]
It's hard to make any educated response without investigating further. There's a lot of things riding on this data, so stopping the fetching of nested data might result in 5 other things breaking.

**Comment by urvashithakar** [comment]
Maybe there is confusion here or I explained it in the wrong way. Let me explain it again.

![Screenshot 2019-10-25 at 11 10 48 AM](https://user-images.githubusercontent.com/50007336/67545824-31e6dd00-f718-11e9-8346-64f6b898c7b8.png)

This issue is specifically for the updation of the item.

On the `created` method; APP will fetch all items of the related collection with nested data and then again one other API call was made for fetching the data of selected items; which is not required.

Cause of this second API call (Selected item fetching); the options were getting overwrite.
