### ISSUE TITLE
Time field error on 24h chrome

### ISSUE THREAD

**Issue by Mozz4rt** [directus/app#1400]
# Bug Report
Portuguese-BR browsers use the 24h clock on the time field. If you have your CHROME browser set to that language and try filling up a time field with any date that have 0 seconds it sets the node value to hh:mm instead of hh:mm:ss. IE.: set "10:00:00" and get it's input value it prints "10:00". This wasn't a bug before but after 7.0.15 there was the date validation.. Firefox works normal also, I didn't test on other browsers

## Steps to Reproduce

1. Set your Chorme lang to PT-BR
2. Set any time fields to 10:00:00
3. See SQL error on the bottom right.

## Expected Behavior
Normal update and save of the item.
## Actual Behavior
Error related to the time format.
## Technical Details

- Device: Desktop PC
- OS: Windows 10 Pro
- Browser: Chrome 72.0.3626.121 64bit
- Directus App: 7.0.19
- Directus API: 2.0.19
- Install Method: Download zip and extract.

**Comment by benhaynes** [comment]
Thanks for reporting this @Mozz4rt! We're on it...

**Comment by rijkvanzanten** [comment]
Ref: this is not specific to the portugese language
