### ISSUE TITLE
Autocomplete on Dropdown Template

### ISSUE THREAD

**Issue by Mozz4rt** [directus/app#1401]
# Feature Request
It would be nice to have an auto-complete within the Dropdown Template of M2O fields.
## What problem does this feature solve?
Helps making relationships become a lot easier. You don't have to write down or open another tab to see what are the possible fields for the other collections.
## How do you think this should be implemented?
I'm guessing that you could fetch the collections object asynchronously after setting up the related collection. After that you could just do it like the IDEs. There could be even a validation possibly.
## Would you be willing to work on this?
Whenever i get time, definitely.

**Comment by rijkvanzanten** [comment]
Would this replace the current dropdown, or would autocomplete be implemented in the search field in the modal that shows up?

I think the first right?

I do like that idea, as it also negates the need for the overlay modal to show the items.

**Comment by benhaynes** [comment]
I love this idea — would definitely simplify the whole selection process. 👍

**Comment by srjrol** [comment]
This enhancement would also solve the current issue with m2o modal.  https://github.com/directus/app/issues/1375

**Comment by srjrol** [comment]
I found this today, might be helpful but I don't have enough understanding to implement it myself.
https://github.com/RomainSimon/vue-simple-search-dropdown

**Comment by shealavington** [comment]
Funnily enough, I just started browsing the issues and I think my latest PR might cover this.

The issue with having an auto-complete drop-down is that you can only really select one column as your template, and can't then customize your template. For example if I have a `slug`, I might set my template to `example.com/{{slug}}`, however, a drop-down would only allow you to do `{{slug}}` by selecting one column.

This was something I actually started working on last year but never finished it, so earlier I put the finishing touches on to get it done haha. Have a look at: https://github.com/directus/app/pull/1451 and let me know your thoughts / if this works for you 😄

**Comment by srjrol** [comment]
@shealavington 

> The issue with having an auto-complete drop-down is that you can only really select one column as your template, and can't then customize your template. For example if I have a `slug`, I might set my template to `example.com/{{slug}}`, however, a drop-down would only allow you to do `{{slug}}` by selecting one column.

The current m2o dropdown allows me to format with multiple fields ```{{field1}} {{field2}}``` and have those displayed for the selected item.  

Do you mean that you can't display a related collection field?  ```{{collection.field1}}``` 
If so, maybe that could be possible after extension https://github.com/directus/app/issues/1402 is completed:

**Comment by shealavington** [comment]
I meant in terms of the template editor 😛 a select field wouldn't work in the template editor, maybe I misunderstood haha — That resource looks like a good idea for quicky filtering the drop-down items at item level 🙌🏻

**Comment by benhaynes** [comment]
If I'm understanding the original issue, it seems like your PR would solve this ticket @shealavington

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by andgar2010** [comment]
> I found [this](https://romainsimon.github.io/vue-simple-search-dropdown/) today, might be helpful but I don't have enough understanding to implement it myself.
> https://github.com/RomainSimon/vue-simple-search-dropdown

Other example https://github.com/godbasin/vue-select2
