### ISSUE TITLE
Search & Filters not returning correct results

### ISSUE THREAD

**Issue by srjrol** [directus/app#1404]
# Bug Report

## Steps to Reproduce
**Global Search**
1. Go to https://directus.app
2. Click on Screens collection.
3. Try global search for "14"
4. See incorrect search results.

**Filtered by Theater field**
1. Go to https://directus.app
2. Click on Screens collection.
3. Try a filtered search by for Theater CONTAINS with a value of "14".
4. See incorrect search results.

## Expected Behavior

**Global search** should only show items which contain fields with a value of "14".  

I see some screen items where it's possible a match is found between fields which I am not sure is intentional.  For example,  Cinema 21 with Number=4 and Seats=160, maybe it sees the 1 in Seats and 4 in Number fields separately?

**Filtered by Theater field** should only return items which contain a value of "14" in the Theater field.

## Actual Behavior
Global search for "14" returning mixed results:
![image](https://user-images.githubusercontent.com/34398302/54538827-fbb3d480-4962-11e9-87a2-a68d89f81948.png)

Filtered by Theater field for "14" returns El Paso 16, Imatra Theater, Corona Screens, and other incorrect results.
![image](https://user-images.githubusercontent.com/34398302/54539103-8bf21980-4963-11e9-8fe6-1786a8bb682c.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Latest Chrome
- Directus App: 7.0.19
- Directus API: 7.0.19
- Install Method: Cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
What happens if you use `equals` instead of `contains`? 🤔 

I can imagine that "contains" `14` will also include `1140` `314` and `3914`

**Comment by benhaynes** [comment]
@srjrol — I imagine it's private, but a schema of this filtered data would be really helpful when debugging.

**Comment by rijkvanzanten** [comment]
@benhaynes he's using the demo schema in the screenshots

**Comment by srjrol** [comment]
@benhaynes and @rijkvanzanten This is all from the directus public demo website.

**Comment by benhaynes** [comment]
Hahaha, of course! Sorry... jetlag!

**Comment by srjrol** [comment]
It may be worth checking that searches are not executed until the table is fully loaded.  I've noticed I need to wait before starting to type the search or it will not filter the correct result unless I modify the search after the load by adding another character.

This is much more noticable with larger tables, where I was seeing very long load times (~20+seconds for thousands of o2m with hundreds of relationships).  Not sure if that sort of load time would be expected but it's what I experienced on the demo website.

**Comment by rijkvanzanten** [comment]
> Try a filtered search by for Theater CONTAINS with a value of "14".

Searching on a relational field right now searches through all the fields, so `theater contains 14` will return theaters with `14` in the name (like `Jacksonville 14`), but also theaters with 14 in any other field, like theater with ID `1148`. This is expected behavior.

I think I'm converting this to a feature request to support searching in relational nested fields from the application filters, instead of searching "globally" through the whole related item (which is causing the non-expected output.

@directus/api-team could you verify that the `filter` parameter works with the dot-notation? EG `?filter[theater.name][contains]=14`

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
