### ISSUE TITLE
Metadata and Tags don't save for files

### ISSUE THREAD

**Issue by dur41d** [directus/app#1407]
# Bug Report

Tags and Metadata are not saved for a file.

## Steps to Reproduce

1. Go to File Library
2. Click on a File 
3. Edit Tags and Metadata
4. See that the save button is still disabled
1. Edit location and the save button is enable
1. Save and click on the file again and see that your changes are not saved.

**Comment by rijkvanzanten** [comment]
This seems to be working as expected for me...

One thing that caught my eye is that the code editor used for `metadata` is set to JSON mode, which will only stage the value when valid JSON is entered.

**Comment by benhaynes** [comment]
Does it outline the interface in red when JSON is invalid or have some indicator?

**Comment by rijkvanzanten** [comment]
Seems to be working fine for me still. Please let me know if it's (still) happening to you and we can reopen.

**Comment by DimaGashko** [comment]
Just watch the video. There's definitely something broken

https://drive.google.com/file/d/1sIsomVsDKe89KOZZVPMPQRTgvCZHOwst/view

**Comment by verdeandrea** [comment]
Same issue here
