### ISSUE TITLE
Files interface not working

### ISSUE THREAD

**Issue by dur41d** [directus/app#1408]
# Bug Report

The 'Files' interface is not working when clicking 'Add new' or 'Add Existing' buttons. The console is showing javascript errors.

## Steps to Reproduce

1. Create a collection with a 'Files' field.
2. Go to the details page of the collection
3. Click 'Add new' or 'Add existing' buttons of the field.
4. Observe that nothing happens and that the console shows javascript errors.

## Expected Behavior
I'm not sure.. I've never used the 'Files' field before.

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/1318592/54581042-35c3bb80-49e1-11e9-839c-13a535c2d702.png)

## Technical Details

- OS: Windows 10
- Browser: Chrome (latest)
- Directus App: 7.0.19
- Directus API:  2.0.19
- Install Method: cloned `build` branches of `directus/app` and `directus/api`

**Comment by rijkvanzanten** [comment]
Hey @dur41d! If possible, can you share a database dump (either here or on [Slack](https://slack.directus.io) so I can reproduce the exact setup? Based on the error, it looks like something went wrong in the relationship, so I'm wondering if it's specific to the current state of your DB

**Comment by harikt** [comment]
Yes, I have the same issue.

![Screenshot from 2019-04-19 11-20-12](https://user-images.githubusercontent.com/120454/56409383-72136180-6296-11e9-9d59-374337fa1900.png)

Database dump attached : 

[directus.sql.gz](https://github.com/directus/app/files/3097143/directus.sql.gz)

**Comment by rijkvanzanten** [comment]
@harikt Your DB doesn't have a junction table setup to store the IDs of movies / files. Adding that fixes the issue. 

[directus.sql.zip](https://github.com/directus/app/files/3104683/directus.sql.zip)


@dur41d I'd love to get access / have a copy of your setup. It's all working as expected on my end, so I'm guessing it's a configuration issue 🙂

**Comment by dur41d** [comment]
@rijkvanzanten I'll is working good for me now. I shared my setup with you before via slack. I suggest to close this issue now and re-open it if it happens again.

**Comment by harikt** [comment]
@rijkvanzanten thank you. I will look into it.
