### ISSUE TITLE
Toggle display issue within modal

### ISSUE THREAD

**Issue by srjrol** [directus/app#1417]
# Bug Report
I am seeing issues the toggle interface disaplyed through modals.  The value are updated and saved correctly but the changes don't appear correctly within the modal.

## Steps to Reproduce

1. Create a new item containg 2 toggle interface fields through o2m or m2m field.
2. In one toggle interface set the display option to checkbox.
3. Create a new item through the modal interface.

## Expected Behavior
Toggle fields should update and display the changes.

## Actual Behavior
The togle icon changes but the associated text does not update correctly.
The checkbox border changes color but no checkmark is displayed in the box.
## Other Context & Screenshots
![toggle_issue](https://user-images.githubusercontent.com/34398302/54786622-57968b80-4bf7-11e9-8e59-6a70752152a8.gif)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser:  Chrome
- Directus App: 7.0.19
- Directus API: 7.0.19
- Install Method: Cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
Hey @srjrol! Could you share a database dump of this exact setup? I tried recreating it but everything seems to be working as expected on my end..

**Comment by rijkvanzanten** [comment]
![Screen Recording 2019-03-22 at 5 24 16 PM](https://user-images.githubusercontent.com/9141017/54853887-7bc19d80-4cc7-11e9-807f-26f9e2258733.gif)

**Comment by srjrol** [comment]
Not sure what happened but it's working for me now as well... perhaps a browser/cache issue of sorts.

**Comment by brocgailit** [comment]
This is happening on current release for me.

I can't share a database dump for this project, but the display of toggles, addition of repeaters, files, etc. don't update.  The value does get updated on save, however.

**Comment by rijkvanzanten** [comment]
@brocgailit Just noticed that too! https://github.com/directus/app/commit/517072a9088c7474fcc033c3019f5c80a92d8fc0 should take care of that. I'm releasing a patch tomorrow as there have been a couple of important fixes in the api as well 👍

**Comment by brocgailit** [comment]
It appears the values aren't actually being staged until 'Saving' so the staged value never gets sent back to the input and is bound to its original value.

@rijkvanzanten what are your thoughts on computed getters and setters on the inputs with a `created` hook to initialize the input value?

Another related issue here is that without staging, when re-opening a modal item (O2M, M2M) the values appear to be 'reverted'.  I haven't used it too much beyond Tab implementation, but can we use Vue's `<keep-alive>` to maintain component state in this situation?

**Comment by rijkvanzanten** [comment]
The values were actually passed up, but weren't passed down correctly. https://github.com/directus/app/commit/517072a9088c7474fcc033c3019f5c80a92d8fc0 fixes that 👍 

I would love to spend some time rethinking some of the core data flows in well specced documents / RFCs to simplify the codebase and prevent bugs like these, but until Directus will generate some revenue (through Cloud) and it's stable enough where I can leave it alone for a little while that'll have to wait..
