### ISSUE TITLE
Status selector doesn't show when creating new via related item

### ISSUE THREAD

**Issue by RedactedProfile** [directus/app#1418]
# Bug Report

The modal window when clicking "New Item" from a relationship field doesn't show the radio selector for status

![image](https://user-images.githubusercontent.com/1039911/54851730-1ad69d00-4ca8-11e9-8717-9cd33f16a69c.png)

## Steps to Reproduce

1. Create Collection 
2. Create another collection
3. Update first collection with a Many To One pointing to the 2nd collection 
4. Go to add an item to the first collection
5. Find the relationship field and click "New Item"
6. Observe as per the image above that the Status selector doesn't show up

## Expected Behavior

The status selector shows up just as if you were creating a new item for the 2nd collection
![image](https://user-images.githubusercontent.com/1039911/54852072-03e47a80-4ca9-11e9-8282-c29ff5f791d4.png)

## Actual Behavior

Status chooser fails to initialize with no errors 

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: FireFox 66.0 &  Chrome 72.0.3626.121
- Directus App: 7.0.19
- Directus API: 7.0.19
- Install Method: Softaculous

**Comment by biancajemsten** [comment]
I'm having this issue as well when creating collections via the API with status fields. 
Is there a solution to this yet?

**Comment by rijkvanzanten** [comment]
What does the request look like when you make a request?

The application uses the exact same API endpoints, so it's most likely due to the way you're creating collections 🙂 

Also, feel free to join us over [on Slack](https://slack.directus.io). It might be easier / faster to debug this there

**Comment by biancajemsten** [comment]
@rijkvanzanten thank you! I was able to debug it by looking at the network requests in the APP 😄
