### ISSUE TITLE
Activity Icon Interface throws error

### ISSUE THREAD

**Issue by henrikwirth** [directus/app#1419]
# Bug Report

When trying to add a new Field to a Collection and choosing Action Icon I get an error thrown.

## Steps to Reproduce

Happening at the official directus.app

1. Go to Collections
2. Click on one Collection to edit
3. Click on New Field
4. Click on Activity Icon (Others)

## Expected Behavior
That you get to the settings of that field and are able to add it.

## Actual Behavior
Following error gets thrown in the console:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at u.tabs (field-setup.vue:865)
    at tr.get (vue.runtime.esm.js:4444)
    at tr.evaluate (vue.runtime.esm.js:4549)
    at u.tabs (vue.runtime.esm.js:4801)
    at u.gu (field-setup.vue?ca3f:1)
    at u.e._render (vue.runtime.esm.js:3535)
    at u.r (vue.runtime.esm.js:4041)
    at tr.get (vue.runtime.esm.js:4444)
    at tr.run (vue.runtime.esm.js:4519)
```

Nothing else happens. Afterwards it is not possible to select other Interfaces. This error message appears when trying to click on another FieldType

```Trouble processing request. Try again after refreshing the page.```

## Technical Details

- Device: Desktop
- OS: MacOS 10.14
- Browser: Chrome 73.0.3683.86
- Directus App: Stable/Latest v7.0.19
- Directus API: [eg: 2.0.0]
- Install Method: directus.app

**Comment by rijkvanzanten** [comment]
How / where are you trying to use this interface? As far as I know, it's added to show little icons on the `/activity` page, but doesn't serve a purpose for regular collections.
