### ISSUE TITLE
"File Preview" interface not showing or initialising 

### ISSUE THREAD

**Issue by RedactedProfile** [directus/app#1425]
# Bug Report

## Steps to Reproduce

1. Add "File Preview" to Collection
2. Go to create or edit an item in that collection

## Expected Behavior

The field should show with a title of the field, a browse button, and an image preview placeholder

## Actual Behavior

Nothing shows up

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/1039911/55027804-5c768900-4fc3-11e9-9e7f-817c11c52258.png)

## Technical Details

- Device: Desktop and Mobile
- OS: Windows 10, Ubuntu, Android
- Browser: Firefox 66.0, Chrome 73.0.3683.86, Chrome for Android 
- Directus App: 7.0.19
- Directus API: 7.0.19
- Install Method: https://docs.directus.io/advanced/app/standalone.html#using-git

**Comment by rijkvanzanten** [comment]
> The field should show with a title of the field, a browse button, and an image preview placeholder

I think you're looking for the `file` interface, not the `file preview` interface. 

Ref> https://github.com/directus/app/issues/1229

**Comment by RedactedProfile** [comment]
Not necessarily, I'm looking for the one that has the "Image Editor" and
shows a proper preview of the uploaded image, which I don't seem to get
with the standard File interface

**Comment by creazy231** [comment]
exactly what I was asking for in my OP.
In addition here is a screenshot of the error which may causes there is no file preview / image edit box:
![image](https://user-images.githubusercontent.com/13473174/56047434-ab534b00-5d45-11e9-9afb-536c49a1ae0f.png)
![image](https://user-images.githubusercontent.com/13473174/56047495-cde56400-5d45-11e9-8592-59c0f76dfeaa.png)

**Comment by benhaynes** [comment]
Just as an update, we'll be merging these two interfaces into one that has the benefits of both. :)

**Comment by creazy231** [comment]
Awesome news 👌🏻
Is there any ETA?

**Comment by rijkvanzanten** [comment]
No, but keep an eye on https://github.com/directus/app/issues/1229#issuecomment-481470371 😄 I believe someone started working on a PR for this 🙂
