### ISSUE TITLE
Allow column structures to be managed without selecting an interface

### ISSUE THREAD

**Issue by shealavington** [directus/app#1427]
# Feature Request

An issue that's I've faced at work, is that after importing tables, the schema can't be modified from Directus unless you select an interface.

By default, Directus should read the existing structure of each column and allow direct modifications of the column `type` without needing to select an interface.

## What problem does this feature solve?
Importing tables from an existing database could be managed all within directus without needing to check the actual database to see it's current type and information.

## How do you think this should be implemented?
Read the structure of each column on app load, and allow it to be directly modified in the "schema" tab, without the need to select an interface.

## Would you be willing to work on this?
If I get the chance, indeed, but I don't have time currently, throwing the idea out for future reference or unless someone else wants something to work on :joy:

**Comment by shealavington** [comment]
ALSO:
Not sure if this is another feature, but it's in the same scope:

When updating modifying an existing columns/fields, there could be a checkbox just above the "Advanced" options that says:
- [ ] Keep existing column structure

This means, if I select WYSIWYG, it won't change the structure to "Varchar 2000" as it currently does, but would keep it at my pre-defined "Varchar 10,000"

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
