### ISSUE TITLE
How to implement field chooser type functionality for adding predefined fields

### ISSUE THREAD

**Issue by justrealmilk** [directus/app#1429]
I'm migrating a site from using Cockpit, another cms, and it provides a "[repeater](https://getcockpit.com/documentation/reference/fieldtypes)" field type which allows you to specify sets of fields, which can be selected by the user.

Essentially, you can define different modules for say a modular portfolio page i.e. image, text, image set, video

What would be the best approach to replicating this functionality?

**Comment by benhaynes** [comment]
We're on it — but our team is super busy at the moment, so it might take a bit to finish/review/merge.

Duplicate of: https://github.com/directus/app/issues/1205
Pull Request (WIP): https://github.com/directus/api/pull/799
