### ISSUE TITLE
WYSIWYG: newline after bold text moves cursor to the top

### ISSUE THREAD

**Issue by alfredoreduarte** [directus/app#1431]
# Bug Report

## Steps to Reproduce

1. Go to the online demo and try to create a new movie
2. Use the "synopsys" editor
3. Type a bold line, then try to enter a new line

## Expected Behavior

Create a new line

## Actual Behavior

Cursor goes to the top of the field

## Other Context & Screenshots

![image](https://media.giphy.com/media/nmDj9kWGEL2LJQY1Gp/giphy.gif)

## Technical Details

- Device: Desktop
- OS: MacOS 10.13.6
- Web Server: Online demo

**Comment by varevarao** [comment]
This issue seems to be on [this line](https://github.com/directus/app/blob/master/src/interfaces/wysiwyg-full/input.vue#L54):
```
watch: {
    value(newVal) {
      if (newVal !== this.editor.root.innerHTML) {
        // This is where the problem occurs, setting the contents moves the cursor to the top
        this.editor.setContents(this.editor.clipboard.convert(this.value));
      }
    }
  },
```

Can someone explain what edge case is covered by this block? The editing works fine, and the value is correctly referenced without the watch function. If I comment the code in the block above, the behaviour is as expected.

**Comment by varevarao** [comment]
The code doesn't usually enter the block above, as the `value` prop and `editor.root.innerHtml` are always in sync. This is why the cursor doesn't get reset with each edit.
It looks like the difference comes up **when a style is continued on a new line**:
- the `value` prop assumes we entered a new line
- quill's editor attempts to place a span with the cursor on the next line without abandoning the style
```
value <p>A</p><p><strong>B</strong></p><p><br></p>
editor html <p>A</p><p><strong>B</strong></p><p><strong><span class="ql-cursor">﻿</span></strong></p>
```
![Screenshot 2019-06-01 at 8 16 46 PM](https://user-images.githubusercontent.com/3070869/58750008-4648e580-84aa-11e9-8d30-205f020b0353.png)
