### ISSUE TITLE
Slug not updating with mirrored field if set as "Read only"

### ISSUE THREAD

**Issue by ninjabachelor** [directus/app#1435]
# Bug Report

## Steps to Reproduce

1. Create a Slug field
2. Set it to "Read only" and connect it to a "Mirrored field"

## Expected Behavior
The Slug should update according to the mirrored field.

## Actual Behavior
Slu is not updating.

## Other Context
This behaviour worked in Directus 6. Has that changed by design in version 7 or is it a bug? Thanks!

## Technical Details

- Device: any
- OS: any
- Browser: any
- Directus App: 7.1.0
- Directus API: 2.0.20
- Install Method: download release `190325A` of Directus

**Comment by rijkvanzanten** [comment]
The app blocked interfaces that were set to readonly from staging new values. However, this doesn't work for all interfaces (see OP problem).

I'll allow interfaces to stage values even when they're in readonly mode, seeing that readonly mode should block user interaction, but not value changes per se (as is the case with the slug interface).
