### ISSUE TITLE
Add interface for setting default browse view

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1439]
If `directus_collection_presets.title` (where bookmarks are stored) is `NULL` then it's just the _default_ Browse view. So you can create a bookmark, remove the user ID (it is global if `user` or `role` are `NULL`) and then delete the `title`.

We should add a dedicated interface (similar to Create Bookmark) for setting the Collection's default view preset for Role or Global. I think this button should exist within the Settings > Collections > Detail page.

**Comment by rijkvanzanten** [comment]
This has been added in #1436

**Comment by benhaynes** [comment]
This is actually different — user/role/global bookmarks are (slightly) different than view defaults.

I imagine this feature being a button at the bottom of the Info Sidebar of the Item Browse page that says "Set as Global Default". Only Admins would see this.

That way an admin could go through the system and setup each browse page with good options, and then save it as the default for all other users.

@rijkvanzanten 🔔

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by edenprojectde** [comment]
Wanted to write down the exact same feature. This would come in **really** handy.

There also should be an option to forcefully remove User defined Settings so an updated View will be used even if they had own settings. (If the Interface develops more features, these could get into a blind spot for Endusers)
And most probably a button on the User-end to "Update" their View voluntarily. Even tough i think this is maybe a bit too much for normal Endusers. Maybe it would be a good solution to not let the Endusers have this feature at all; to change the view settings at all.

Maybe it would be a nice to have to disable view changes in certain Groups?

**Comment by rijkvanzanten** [comment]
> Maybe it would be a good solution to not let the Endusers have this feature at all; to change the view settings at all.

I think we can base this on write permissions to directus_collection_presets. That would disable changing the settings of a view / prevent the user from creating bookmarks.
