### ISSUE TITLE
Having issues with the one to many field in latest v7 build.

### ISSUE THREAD

**Issue by Pixel5urfer** [directus/app#1443]
**Fresh install.**

- On creating a "one to many" field the drop down titles don't show. Using template {{title}}
- On creation the first item is selected by default.
- Then on selection of two items it deletes one item from the linked collection and duplicates another.
- It has also in other cases changed the title of the linked collection to JSON or deleted/multiplied entries in the linked table.

Link to a video of the behavior below. 
https://1drv.ms/v/s!ArzUAClrxMG1y231GuSAsH0rpXrG

Thanks!

**Comment by shealavington** [comment]
From what I saw, you related page_id to module_id, both primary keys?..

**Comment by benhaynes** [comment]
I also reviewed the video... thank you for taking the time to post that, it makes debugging _much_easier!

I agree with Shea that you forgot to update the related field (the right dropdowns under `relation`) and left it pointing to the primary key. Instead, it needs a dedicated field for storing the relational id. I'll close this since it's a config issue.

**Comment by Pixel5urfer** [comment]
Thanks guys! Apologies, it was obviously down to me not understanding the way this works, I didn't realise that a specific field is required. I assumed any relationship data would be stored in a separate table so a specific column wouldn't be required. That explains why my fields sometimes contained JSON after update. Would an improvement to this be that the dropdown would have some validation to make sure the field you select is not the primary Id and that the field is a valid type?

**Comment by rijkvanzanten** [comment]
@Pixel5urfer Good idea 🙂 

https://github.com/directus/app/issues/1458

**Comment by shealavington** [comment]
I was actually thinking of an idea of having a "Relationship Wizard" interface, it would ask questions and help people through the process and suggest options for setting up relationships.

(Unfortunately the relationship Wizard won't work for real life, which sucks! 😂😋)
