### ISSUE TITLE
Unable to batch edit item status field

### ISSUE THREAD

**Issue by srjrol** [directus/app#1445]
# Bug Report

## Steps to Reproduce

1. Create a collection with a status field.
2. Create multiple items in the collection.
3. Select multiple items and batch edit them.

## Expected Behavior
Ability to set the status field for multiple items.
## Actual Behavior
The status options do not appear after toggling the field to edit.
## Other Context & Screenshots
![status](https://user-images.githubusercontent.com/34398302/55434609-96183880-555d-11e9-8c91-5f8680679380.gif)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus: 190325A
- Install Method: Cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
Can you confirm this is still happening for you @srjrol?

It seems to work as expected on my end

<img width="613" alt="image" src="https://user-images.githubusercontent.com/9141017/56518836-79dd3b00-650e-11e9-8366-d8e7c1407d32.png">

**Comment by srjrol** [comment]
I updated from 190325A to 190419A but I still see this problem.  I tried testing on the demo website but those status fields are having other problems currently.

**Comment by rijkvanzanten** [comment]
This turned out to be a configuration issue. The default value for the status field was set to a status that didn't exist in the system.
