### ISSUE TITLE
Improve ux when changing project

### ISSUE THREAD

**Issue by felskov** [directus/app#1448]
# Feature Request

I've used the DigitalOcean one click installer, and configured two projects (api.php, api.project2.php), and added the following configuration to config.js:

```js
    api: {
      "../_/": "Project 1",
      "../project2/": "Project 2",
    },
```

This works beautifully, letting me select active project on sign in. While signed in, I'm able to change active project by toggling a dropdown, but the way this dropdown works isn't completely intuitive.

1) It doesn't auto-select the currently active project. If I've signed into Project 2, then the currently selected value upon expand will be Project 1. This is very counter intuitive to me and the people I've demonstrated the admin app to.

2) This is probably because of no. 1 above, but when selecting the already active project I'm still being brought back to the sign-in page. If user selects the active project, it should be a noop, allowing him to continue working within this project.

3) After having changed project in the dropdown, you're being redirected to the sign in area. But the project you selected in the dropdown isn't remembered here. Let's say I signed in to Project 1, but then used the dropdown to select Project 2. Once brought to the sign in page, Project 1 will be selected because it's the default project.

## What problem does this feature solve?

It'll improve user experience for organisations with many content editors who doesn't have a background in web development. Many of our people will be very confused by the current behaviour :-)

## How do you think this should be implemented?

I haven't looked into the source code, but I think it should be relatively straight forwards to implement auto-selection of the active project, and to remember the selection upon redirection to the sign in page.

## Would you be willing to work on this?

Sure, but I'm not quite familiar with the code behind Directus - so I might need some guidance before being able to help out :-)

**Comment by benhaynes** [comment]
Yes, these changes are much needed — and I agree this Project Switcher UX is not very friendly right now. Thanks @felskov — we'll see what we can do (unless someone has time for a PR!)

**Comment by dev7ch** [comment]
@felskov what you are discribing might be related to the version of the one click installer,
this should work on https://directus.app/#/login (admin@example, password) or i am getting you wrong?

**Comment by felskov** [comment]
@dev7ch You're right, it works on on  https://directus.app/#/login

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
