### ISSUE TITLE
Shared bookmarks

### ISSUE THREAD

**Issue by felskov** [directus/app#1449]
# Feature Request

I'm not sure if this is already implemented, but it would be great if admins could create bookmarks and share them with specific roles. For instance we have an approver role, where it would make sense to add book marks to certain collections where items have a status = draft. Instead of each approver having to create this bookmark themself, it would be nice to just have an admin pre-create it for them.

## What problem does this feature solve?

It'll make it easier for to create shortcuts to frequently used filters, and share them amongst all user, instead of each user having his own set of bookmarks.

## How do you think this should be implemented?

I don't know, but upon inspecting the database I did see that there already is a "role" column on the collection_presets table. Perhaps what's missing is simply to implement this feature in the frontend?

## Would you be willing to work on this?

Sure, but at the current point I wouldn't know where to start - so I'll need some guidance if I'm to be of any help :-)

**Comment by rijkvanzanten** [comment]
> Perhaps what's missing is simply to implement this feature in the frontend?

Yes! Bookmarks can already be set for a user role or global for everyone. @honzabilek4 is actually finishing up a PR for the GUI for this 😄 

https://github.com/directus/app/pull/1436

**Comment by felskov** [comment]
Ugh, how did I miss this... :-)

Thank you for your response.

**Comment by mvhirsch** [comment]
Since #1436 is merged and released with v7.3.0, I think this can be closed @rijkvanzanten ?
