### ISSUE TITLE
Save options text/background

### ISSUE THREAD

**Issue by srjrol** [directus/app#1450]
# Bug Report

## Steps to Reproduce

1. Edit existing item and choose the '...' more options instead of save.

## Expected Behavior
Text is different color than the background.
## Actual Behavior
Text and background are same color.
## Other Context & Screenshots
![save_options](https://user-images.githubusercontent.com/34398302/55576140-31ccb480-56d6-11e9-881a-b82a6af555db.gif)

"I think it's because the font color of that element is white, rendering the font white in the dropdowns in your particular browser / OS" -Rijk
## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)

- Directus: 190325A
- Install Method: cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
Much better 🙂 

<img width="186" alt="image" src="https://user-images.githubusercontent.com/9141017/55637684-a3b70380-5793-11e9-8910-3a61e2f594cb.png">
