### ISSUE TITLE
Make it possible to cancel Many-to-One modal window

### ISSUE THREAD

**Issue by felskov** [directus/app#1452]
# Feature Request

Once the user has opened a Many-to-One modal window, he cannot close the window without saving his changes. It should be possible to close the modal without saving changes.

## What problem does this feature solve?

Users will expect to be able to close a modal without committing their changes. This currently isn't the case for Directus.

## How do you think this should be implemented?

Add a close button, similar to the one in the modals when managing fields on collections.

## Would you be willing to work on this?

I would - I've briefly looked into the source code, and it seems pretty intuitive. I haven't worked with Vue.js before, but seems like it should be pretty straight forwards to learn. If I fork the repo and try to implement the feature, is there any way to reach out to you guys if I'm having any questions?

**Comment by felskov** [comment]
Also, is it even something you'd be willing to consider merging if I manage to implement and create a pull request? :-)

**Comment by srjrol** [comment]
@felskov There is a bug report for this here https://github.com/directus/app/issues/1375

**Comment by benhaynes** [comment]
Hey @felskov — thank you for reporting this (your description is better written than mine!). This ticket has been referenced to the original so I'll close this one and clean up mine.

As @srjrol mentioned, Slack is definitely the best way to reach out to the core team or extended community.

And if you have time to create a PR @rijkvanzanten will review and we'll most certainly get it merged! Thanks for asking!!
