### ISSUE TITLE
Cannot click save in Many-to-One modal if no items are selected

### ISSUE THREAD

**Issue by felskov** [directus/app#1454]
# Bug Report

I've created a collection with a Many-to-One relation that's *not* marked as required. I've forced the interface to open a modal when users click the field (by setting threshold to 0). Once users have opened the modal, they are forced to select an item before being able to click "Save". This should only be the case if the field is marked as required.

This issue is extra annoying because users also cannot close the dropdown (see #1452), which means that if they accidentally click the field for an item that shouldn't have any relation they're stuck.

## Steps to Reproduce

1. Create a collection with a Many-to-One relation that's not required
2. Force the interface to use the modal by setting threshold to 0
3. Create a new item in the collection, and click the relation field to open the modal
4. The save button will be disabled until you've selected an item

## Expected Behavior

The save button should only be disabled until an item has been selected, if the relation field has been marked as required.

## Actual Behavior

See steps to reproduce (save button is disabled).

## Other Context & Screenshots

<img width="690" alt="Screenshot 2019-04-05 at 09 56 22" src="https://user-images.githubusercontent.com/1436954/55612789-5897f300-5789-11e9-9039-c0b468723320.png">
<img width="694" alt="Screenshot 2019-04-05 at 09 56 14" src="https://user-images.githubusercontent.com/1436954/55612791-5897f300-5789-11e9-869e-41a858f1fd11.png">

## Technical Details

- Device: Desktop
- OS:  MacOS 10.14.4
- Browser: Chrome 73.0.3683.86
- Directus App: 7.0.18
- Directus API: Not sure - using directus/api:latest docker image (pulled yesterday)
- Install Method: Using official directus docker images

**Comment by benhaynes** [comment]
Thanks @felskov — we're on it!

**Comment by felskov** [comment]
@benhaynes Awesome, let me know if I can help in any way :-)

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/app/pull/1520

**Comment by rijkvanzanten** [comment]
@shealavington this was closed in https://github.com/directus/app/pull/1520 right?

**Comment by shealavington** [comment]
Unfortunately not, this was never truly finished as the idea changed after I made a change, so I revered and the PR was just styling in the end. I didn't get round to getting back to this.

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/app/pull/1677
