### ISSUE TITLE
pasted images in full wysiwyg not only dont save, but cuts off all content after the first pasted image

### ISSUE THREAD

**Issue by RedactedProfile** [directus/app#1459]
# Bug Report

## Steps to Reproduce

1. Have a Collection with a "Full WYSIWYG" interface
2. Create new entry in collection 
3. find any image online and "Copy" it to your system clipboard.  
4. With the WYSIWYG field, Ctrl+V to paste the image in. It will show up just fine. 
5. Add text above and below the pasted image
6. Save the entry 
7. Go to edit the entry

## Expected Behavior

When I go to edit my entry, I should be able to see everything I had input.

## Actual Behavior

The WYSIWYG editor not only doesn't show the pasted images, but all content after the first pasted image is truncated. 

## Other Context & Screenshots

Before Save
![image](https://user-images.githubusercontent.com/1039911/55646752-d90e2200-5790-11e9-9bf6-605e9fe89ebd.png)

After Save
![image](https://user-images.githubusercontent.com/1039911/55646783-eaefc500-5790-11e9-9d0b-c6697dab76c0.png)

## Technical Details

- Device: Desktop
- OS: Ubuntu 18.04
- Browser: Firefox 66.02
- Directus App: 7.0.19
- Directus API: 7.0.19
- Install Method: zip download + upload to file system

**Comment by benhaynes** [comment]
Thanks for reporting this — it might not be an issue soon as we're upgrading to a new-and-improved WYSIWYG editor for core. But still, we'll take a look!

https://github.com/directus/app/pull/1441

**Comment by RedactedProfile** [comment]
Thank you so much @benhaynes

**Comment by urvashithakar** [comment]
Hello @RedactedProfile,
I am not able to replicate this issue in Directus App Latest version. Can you update it to latest version and try again?

**Comment by bjgajjar** [comment]
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.
