### ISSUE TITLE
Clicking alert smoke should always "cancel"

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1460]
1. Go to item detail
2. Edit item
3. Try to navigate away (see "are you sure" confirmation)
4. Click "smoke"

At this point it should "cancel" the action, but since the secondary action is "leave"... it leaves.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
