### ISSUE TITLE
2nd level related table getting overwritten

### ISSUE THREAD

**Issue by Kinzi** [directus/app#1462]
# Bug Report

Changes on a 2nd level related table cause saving of "root" table in background. This overwrites the password field (I assume hashing the hash again).

## Steps to Reproduce

Let me try to explain better:

1. Set up
I have the following collections and relations:
`Merchant <-- O2M --> Products <-- 02M --> Prices `
The Merchant has the standard hashed password field. Price - Merchant have *no* direct relation

2. Use case causing the error
I am in the products view and open the O2M Modal to edit a price, close the modal and save the product.

3. Error
The change causes the related Merchant to be saved. (as can be seen in it's activity log) After this the hashed value of the password is changed. I assume because the initial hash is hashed again.

More Info:
This does not happen if I make changes only to the product, nor if I make changes to the price directly (without coming from the Products Modal).

I assume it's actually two bugs: O2M modal not saving correctly (this is super buggy anyways https://github.com/directus/app/issues/1412) and the hashed password being rehashed.

## Expected Behavior

Related merchant is not saved at all or at least a hashed password does not get overwritten.

## Actual Behavior

Related merchant is saved and password hash changed.

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch of `directus/directus`]

**Comment by Kinzi** [comment]
As a quick fix should anybody else run into this:

1. Comment out the update hashing in core/interfaces/password/hooks.php (line 33)

2. Write a filter hook for this:

```return [
    'filters' => [
        'item.update.operators:before' => function (\Directus\Hook\Payload $payload) {
            $hashManager = new Directus\Hash\HashManager;

            $password = $payload->get('password');
            // If PW already hashed remove from $payload else hash and overwrite $payload
            if (substr($password, 0, 4) == '$2y$') $payload->remove('password');
            else {
                $hashedString = $hashManager->hash($password, ['hasher' => 'core']);
                $payload->set('password', $hashedString);
            }

            return $payload;
        }
    ]
];```

**Comment by rijkvanzanten** [comment]
The main problem we have to solve first is the deeply nested clones of the parent item, that's preventing updating the M2M now. It's also the cause for many of the O2M bugs floating around.

Lets say you're editing the parent (`movies/15`), this file has a many to one to `posters`. `posters` has a O2M back to movies showing what movies have this poster. When editing this parent item, the app keeps track of the full object of `movies/15`. Currently, the application fetches and uses the main item + 3 levels deep of relations. This allows the app to preview things like the O2M table values, or the image preview in a nested modal relationship. Now here's the problem:

When making a change in the parent item, the nested child can contain it's own copy of the parent item:

```
movies/15
  poster (m2o)
    movies-that-have-this-poster (o2m)
      movies/11
      movies/15 <<<<<<<<<<
      movies/21
```

When making changes, the parent item is being updated, but the nested subchild isn't (as that's technically the value for the related o2m). Once the user hits save, the above object is send to the API causing *two* updates. One for the parent changes (first) and then a recursive save for the relational ones (second).

The only way to fix this reliably in the application is to make a split between saved values from the database and edits on top of that. That way we can only submit the actual changes to the API, but still leave the original values for previewing of data.

**Comment by rijkvanzanten** [comment]
This was fixed in O2M in https://github.com/directus/app/pull/1677

**Comment by Kinzi** [comment]
@rijkvanzanten yes seems to be solved. Thanks! :)
