### ISSUE TITLE
Image viewer

### ISSUE THREAD

**Issue by alrick** [directus/app#1463]
# Feature Request

## What problem does this feature solve?
Add the ability to view an image in full size (or higher size) from the admin.
I use Directus at an university and students often have read-only access. It would be really useful for them to be able to see the pictures in full size without using "right-click > view image".

## How do you think this should be implemented?
With an image viewer à la lightbox (with ability to see the full-size original image) or at least being able to click on the image to open the full-size image on a new tab.

## Would you be willing to work on this?
Not at the moment but I could in the future if it's yet not implemented.

**Comment by rijkvanzanten** [comment]
We're actually discussing this over on https://github.com/directus/app/issues/1229 😄
