### ISSUE TITLE
Add min/max to M2M and O2M Interfaces

### ISSUE THREAD

**Issue by zeusstl** [directus/app#1464]
# Feature Request
Add a min/max rows option for M2M and O2M interfaces.

## What problem does this feature solve?
- The most obvious use case is for O2O relationships. Currently, you can enforce a O2O by making the relational field in the remote table a unique field. This still leaves the add buttons active, so the ux is incorrect and confusing. 
Discussed a bit here: https://github.com/directus/directus/issues/1285
- You can require a certain amount of rows and limit how many rows are permitted.

## How do you think this should be implemented?
- It could be implemented by hiding the add buttons in the ui once the max has been reached.
- It could additionally be enforced further in the code.

## Would you be willing to work on this?
I'd be willing to give input and help in some way, but not sure I'm qualified or could ramp up fast enough.

**Comment by benhaynes** [comment]
Thanks @zeusstl — quite a useful option!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
