### ISSUE TITLE
Search Filters for O2M or M2M field types cause a server error

### ISSUE THREAD

**Issue by srjrol** [directus/app#1475]
# Bug Report

## Steps to Reproduce

1. Open the table view of a collection containing a One-to-Many or Many-to-Many field.
2. Add a field filter for the O2M or M2M field type.
3. Perform a search.
4. See ```Server Error - Something is wrong with this instance’s server or database.```
5. Clear the field filter to fix the server error.
## Expected Behavior
Search should be possible on displayed columns for the related items or the option to filter from these fields types should not be allowed.
## Actual Behavior
Server Error.
## Other Context & Screenshots
![x2m_search_server_error](https://user-images.githubusercontent.com/34398302/55918429-b7f66880-5bb8-11e9-874f-c46d81c5f685.gif)

## Technical Details

Device: Desktop
OS: Windows 10
Browser: Chrome
Directus: 190325A
Install Method: Cloned master branch of directus/directus

**Comment by shealavington** [comment]
Was wondering if this was fixed already? I can't see the `favorites` M2M in my available filters...

![image](https://user-images.githubusercontent.com/16869302/56855618-0db16b80-6942-11e9-9c1b-5f762df66477.png)

**Comment by rijkvanzanten** [comment]
You're right @shealavington 

Closed in https://github.com/directus/app/pull/1446
