### ISSUE TITLE
Login might fail under some specific circumstances

### ISSUE THREAD

**Issue by okayawright** [directus/app#1476]
# Bug Report

Under specific circumstances, one cannot login anymore on the APP after a first failed login.

## Steps to Reproduce

1. Create a user **A** who can login on the APP (for example, make him an "Administrator")
2. Create a user **B** who's not allowed to login (for exemple, give him no role)
3. Try to login with user **A**: everything's fine. That is expected.
The method *getExtensions()* returns the correct list of extensions to load. See screenshot.
![Capture](https://user-images.githubusercontent.com/1095407/55962850-fe5bce00-5c71-11e9-9a81-9bf995d19409.JPG)
3. Try to login on the APP with your user **B**, a generic error will occur. That is expected (except that the error is generic and so users don't understand what has just happened)
The method *getExtensions()*  returns a list of 'undefined' extensions
See screenshot.
![Capture2](https://user-images.githubusercontent.com/1095407/55962994-40850f80-5c72-11e9-8476-a13640250e00.JPG)
4. Don't refresh/reload your page and click on the link 'login to another instance'
5. Now try to login with your user **A** again on the same project, an error occurs and that is not expected. 
See screenshot.
![Capture4](https://user-images.githubusercontent.com/1095407/55963116-7de99d00-5c72-11e9-9092-05fb975090a2.JPG)
The source of the error looks like because *getExtensions()* still returns a list of 'undefined' extensions and not the correct list of valid extensions.
See screenshot.
![Capture3](https://user-images.githubusercontent.com/1095407/55963160-9659b780-5c72-11e9-908f-e281ec835650.JPG)

## Expected Behavior
Users with proper rights should be able to login to the APP all the time

## Actual Behavior
After a specific case of failed login, the user cannot login anymore with his other accounts.

## Technical Details
Latest Chrome and Firefox. Directus Master branch.

**Comment by okayawright** [comment]
It looks like I can fix this problem on my end by making sure I do not feed the extension cache with empty extensions, but an expert should take a look and see what are the possible side-effects or fix the root cause:

```diff
diff --git a/src/store/modules/extensions/actions.js b/src/store/modules/extensions/actions.js
index 59761ba..f32007f 100644
--- a/src/store/modules/extensions/actions.js
+++ b/src/store/modules/extensions/actions.js
@@ -84,7 +84,9 @@ function readCoreExtensions(type) {
     if (moduleCache[fileName] === metaDefinition) return;

     // Update the module cache, so we don't re-require files that we already have
-    moduleCache[fileName] = metaDefinition;
+    if (typeof metaDefinition !== "undefined") {
+      moduleCache[fileName] = metaDefinition;
+    }

     const extensionId = fileName
       .replace(/^\.\//, "") // remove the ./ from the beginning
```

**Comment by okayawright** [comment]
Disabling the extensions cache for hot reload apparently solves the problem, an expert should take a look at this

```diff
λ git diff  338671f1aa6e569fef677684d1f400ba20e74a09 8d0767b58c9f05fe84657d00b0b0aad40c57f5b0
diff --git a/src/store/modules/extensions/actions.js b/src/store/modules/extensions/actions.js
index 59761ba..f6de629 100644
--- a/src/store/modules/extensions/actions.js
+++ b/src/store/modules/extensions/actions.js
@@ -1,4 +1,4 @@
-/* global require, module */
+/* global require */

 import { forEach, mapKeys, isObject, mapValues } from "lodash";
 import api from "../../../api";
@@ -6,9 +6,6 @@ import { i18n } from "../../../lang/";

 import * as mutationTypes from "../../mutation-types";

-// Used to make hot reload a bit more efficient
-const moduleCache = {};
-
 /**
  * Recursively loop over object values and replace each string value that starts with $t: with it's
  *   translation as managed by vue-i18n
@@ -68,24 +65,11 @@ function readCoreExtensions(type) {
       break;
   }

-  if (module.hot) {
-    module.hot.accept(requireContext.id, () => {
-      readCoreExtensions(type);
-    });
-  }
-
   return requireContext.keys().map(readMeta);

   function readMeta(fileName) {
     const metaDefinition = requireContext(fileName);

-    // Skip the module during hot reload if it refers to the same module definition
-    // as the one we have cached
-    if (moduleCache[fileName] === metaDefinition) return;
-
-    // Update the module cache, so we don't re-require files that we already have
-    moduleCache[fileName] = metaDefinition;
-
     const extensionId = fileName
       .replace(/^\.\//, "") // remove the ./ from the beginning
       .replace(/\.\w+$/, "") // remove the extension from the end
```

**Comment by rijkvanzanten** [comment]
Good catch! Thanks for the great documentation on what's causing it and how to solve it too. That change looks good to me. Can you open a PR for that commit? 🙂
