### ISSUE TITLE
Support display template for relational fields in card component

### ISSUE THREAD

**Issue by srjrol** [directus/app#1479]
# Bug Report

## Steps to Reproduce

1. Go to User Directory section.
2. Click the INFO button and change the title or subtitle to 'Role' field.
3. Notice the Role field is displayed as ```[object]``` instead of the Role 'Name' ```Administrator```.
4. Change the body to 'Role' field.
5. Notice the full contents of the object are displayed instead of the Role 'Name'.

## Expected Behavior
The Role field should display the 'Name' field of the Role instead of the object.
## Actual Behavior
Object is displayed instead of 'Name' field.
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/34398302/56049172-81326680-5d0e-11e9-910b-cb81a1718333.png)
![image](https://user-images.githubusercontent.com/34398302/56049178-87c0de00-5d0e-11e9-946b-09272e76be6a.png)
![image](https://user-images.githubusercontent.com/34398302/56049192-8d1e2880-5d0e-11e9-9c9d-26b6d20a1869.png)

Here is the HTML that was generated for title,subtitle,body sections of a card.
```
<div data-v-477c7be9="" class="main">
<h2 data-v-477c7be9="" class="title has-tooltip">[object Object]</h2>
<p data-v-477c7be9="" class="subtitle style-4">[object Object]</p>
<p data-v-477c7be9="" class="content">[
  {
    "id": 1,
    "user": {
      "id": 1,
      "status": "active",
      "first_name": "Admin",
      "last_name": "User",
      "email": "admin@example.com",
      "email_notifications": true,
      "avatar": null,
      "company": null,
      "title": null,
      "locale": "en-US",
      "high_contrast_mode": false,
      "locale_options": null,
      "timezone": "America/New_York",
      "last_access_on": "2019-04-12T15:31:09+00:00",
      "last_page": "/collections/about/1",
      "token": "demo",
      "external_id": null
    },
    "role": {
      "id": 1,
      "external_id": null,
      "name": "Administrator",
      "description": "Admins have access to all managed data within the system by default",
      "ip_whitelist": null,
      "nav_blacklist": null
    }
  }
]</p></div>
```
## Technical Details
-Device: Desktop
-OS: Windows 10
-Browser: Chrome
-Directus: 190325A
-Install Method: Cloned master branch of directus/directus

**Comment by rijkvanzanten** [comment]
The card component currently renders whatever the value is coming from the API. We could hardcode an exception for the role field in directus users to show the name of it, but I'd prefer having an option that allows you to add a display template (similar to the relational interfaces) that will control how to show the objects

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
