### ISSUE TITLE
Directus Users formatted incorrectly

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1488]
When you toggle "Show Directus System Collections" in the settings, all remove the "directus_" except for Directus Users... which is at the end and written out.

![Screen Shot 2019-04-13 at 8 31 40 PM](https://user-images.githubusercontent.com/522079/56086751-4c680180-5e2b-11e9-9abc-755692fee4e3.png)

**Comment by rijkvanzanten** [comment]
🧐
