### ISSUE TITLE
Empty listing cells

### ISSUE THREAD

**Issue by benhaynes** [directus/app#149]
We should add a placeholder for empty listing page cells (for `NULL` or `""`). I think this should match 6.x, which wrapped `--` with a span to style it as gray:

`<span class="null">--</span>`
_class name is up for discussion!_

**Comment by rijkvanzanten** [comment]
Do we want to allow each interface to choose it's `null` display value or want to force a system one (where applicable)?

If we have it on the interface level:
+ Each interface can show something that makes sense for the interface; a markdown interface can render the markdown logo on empty input

If we have it on the listing level:
+ Each empty value looks the same (visual consistency)

**Comment by benhaynes** [comment]
Yeah, I wasn't sure which is better. Ideally I'd like to have the `--` as the default, but allow that to be overridden by interfaces that need/want to display empty data in a specific way.

**Comment by rijkvanzanten** [comment]
Implemented in #165
