### ISSUE TITLE
404 error for tabular/layout.css

### ISSUE THREAD

**Issue by thepurpleblob** [directus/app#1491]
# Bug Report

## Steps to Reproduce

1. create an instance of a collection
2. save it

## Expected Behavior

Save seems to work fine

## Actual Behavior

console shows...

GET http://................/extensions/core/layouts/tabular/layout.css net::ERR_ABORTED 404 (Not Found)

**Comment by rijkvanzanten** [comment]
This is a duplicate of #1242
