### ISSUE TITLE
Settings should honor form/field layout

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1492]
Setting `directus_fields` for system fields does not change the Settings pages:

* Collection: `directus_collections`
* Field: `note`
* Width: `4`

This should make the note field of `/settings/collections/kiosks` be full-width... but it doesn't. The same applies to all other fields in Settings... they should work the same way as any other custom schema/data.

Perhaps this isn't a bug... but I can't figure out how/where to adjust the page layouts for Settings. Sooooo...

**Comment by rijkvanzanten** [comment]
Setting the values to `half` / `full` / `fill` seems to work for me
