### ISSUE TITLE
All interfaces should be responsive within their container

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1493]
We should ensure that all interfaces work within our new two-column form layout. Each layout should be optimized for `300px` and `632px` (the standard sizes), but should also work at the in-between sizes for full responsiveness when the viewport doesn't allow for a full 632px wide form.

632px can be considered the "soft" max width, but we will likely have a "full-width" option — since there are certain interfaces that would likely take advantage of that (eg: map, permissions, etc).

Ref: https://github.com/directus/app/issues/879

**Comment by rijkvanzanten** [comment]
The interfaces should be responsive now. We should open new bug issues for the individual ones that aren't.
