### ISSUE TITLE
Required field stars not reported properly

### ISSUE THREAD

**Issue by YvanDaSilva** [directus/app#1494]
# Bug Report

Hi, the latest change to stars for required fields is reporting all fields as being required.

## Steps to Reproduce

1. Go to settings, collections & fields
2. Select any collection and watch the fields

## Expected Behavior
Only required fields are reported as required including the primary key.

## Actual Behavior
Everything is being reported as required.

## Other Context & Screenshots

The condition was already wrong before the latest changes.
Please see the following line

https://github.com/directus/app/blob/24831025edbaa24f33ea169102d5230e17f5d131/src/routes/settings/fields.vue#L53

I would advise to replace the condition with a vue method as follows 

Condition:
`                  v-if="required(field)"`
New method:
`  methods: {
    required(field) {
      return field && 
        (field.required === '1' || field.required === true) || 
        field.primary_key
    },
`

## Technical Details

- Device: Desktop
- OS: Linux
- Browser: Chrome
- Directus App: master
- Directus API: master
- Install Method: cloned master for both.

**Comment by rijkvanzanten** [comment]
This has been changed to an optional flag with the appropriate check:

https://github.com/directus/app/blob/597b16683207d0b95a23d496d832471b2b7a4850/src/routes/settings/fields.vue#L43
