### ISSUE TITLE
Cannot soft delete a collection anymore if the "status" field has been deleted

### ISSUE THREAD

**Issue by okayawright** [directus/app#1496]
If you try to delete a collection that has lost its **status** field then an error will occur

# Bug Report

## Steps to Reproduce

1. Create a collection with a **primary key** and a **status** field
2. Modify the collection and remove the **status** field
3. Do not refresh or reload the application and try to delete the collection

## Expected Behavior

The collection is deleted

## Actual Behavior

An error occurs

## Other Context & Screenshots

Apparently, the application tries to *soft delete* (change the state of the collection to hide it from sight) thinking the **status** is still present but fails

## Technical Details
Latest master

**Comment by rijkvanzanten** [comment]
Closed in #1497
