### ISSUE TITLE
Dynamic Contextual Times

### ISSUE THREAD

**Issue by benhaynes** [directus/app#150]
All contextual times should auto-update on an interval and have the exact time on hover. eg:

`<span class="contextual-time" title="April 13th, 2018 @ 3:14:01p EST">3 minutes ago</span>`

After X period of time (perhaps every minute?), this should update (to "4 minutes ago", etc).

**Comment by benhaynes** [comment]
Haha, no, because I don't see any in the app yet. Let's make sure the datetime interface is used in the demo so we can see it working... then we can close this.

**Comment by rijkvanzanten** [comment]
Gotcha. There is a global `<timeago>` element, so this should already be in there 😉

**Comment by benhaynes** [comment]
All the more reason for a basic demo schema we can test with. :)

**Comment by rijkvanzanten** [comment]
This is already implemented as expected.
