### ISSUE TITLE
Mirror multiple fields

### ISSUE THREAD

**Issue by smth** [directus/app#1506]
# Feature Request

Have the option to mirror more than one field for auto-generated slugs.

## What problem does this feature solve?

Slugs being limited to either something unique or something readable. You could get the best of both worlds, combining, for example, two fields of `title` and `date`.

## How do you think this should be implemented?

From a user point of view, using the existing pattern of `{{ field-name }}` probably makes sense. So you could do `{{ field-name }}-{{ field-name }}`

## Would you be willing to work on this?

Yes, though its not really my area of expertise.

**Comment by benhaynes** [comment]
I believe @shealavington was working on a "template generator" interface for more easily setting up the `{{ field-name }}` string. That, plus a little refactor on the slug interface should get this working. 

Our core team is pretty busy on stability/bugs/refactor/redesign at the moment... but we could offer guidance/review to anyone wanting to take this on.

**Comment by shealavington** [comment]
I believe you're correct Ben.  

I currently have a pull-request outstanding for the new "suggest" interface. The PR has already updated the slug interface to allow for "click to add field", however, as far as I'm aware, it doesn't currently support multiple fields, therefore, it would need that re-factor to allow the mirror to follow a template. (https://github.com/directus/app/pull/1451)

**Comment by rijkvanzanten** [comment]
I think the API might do the actual slugging, the application just provides a preview. Not 100% sure though

**Comment by shealavington** [comment]
From what I remember, the `slug` interface has a watcher in Vue, that mirrors another field, then forces it to lowercase and submits as a string. 🤔👍

**Comment by rijkvanzanten** [comment]
I remember that the slug interface used to have a hook that would slug the value. I it was moved into a datatype together with the hash

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
