### ISSUE TITLE
Rating/Stars interface not visually correct

### ISSUE THREAD

**Issue by shealavington** [directus/app#1508]
# Bug Report

- Create a field with the "rating" interface 
- Change the interface option to display clickable stars instead of numbers
- Attempt to fill click the rating upon editing an item,

- It seems to update the correct value...
- However, there doesn't seem to be a "clicked" state for showing what rating was selected, just shows as empty.

_On that note, on the Demo, the Movies field "rating" is currently set to "Dropdown" this could and should demonstrate this rating interface as stars_ :)

**Comment by srjrol** [comment]
I think this is a duplicate of https://github.com/directus/app/issues/1465

**Comment by shealavington** [comment]
> I think this is a duplicate of #1465

Ah, good call @srjrol, My bad! 

@benhaynes Maybe the original above could have the "good first issue" tag, though I'm tempted to fix this sometime 😂
