### ISSUE TITLE
Can't get the files/images url/path

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1513]
# Bug Report

No image url/path can be found in the data acquired through API

```json
{
    "id": 1,
    "title": "WebStorm 2019 for mac(JavaScript多功能集成开发环境) v2019.1.1",
    "short_title": "WebStorm 2019",
    "slug": "webstorm-2019-for-macjavascript", 
    "icon": 11, //this is a file field
    "files": 6, //this is a file field
    "tags": ["mac-webstorm", "webstorm"]
}
```

## Steps to Reproduce

1.  Go to [http://pertim.top/_/items/mac](http://pertim.top/_/items/mac)
2. See error

## Expected Behavior

```json
{
    "id": 1,
    "title": "WebStorm 2019 for mac(JavaScript多功能集成开发环境) v2019.1.1",
    "short_title": "WebStorm 2019",
    "slug": "webstorm-2019-for-macjavascript", 
    "icon": [
        {
            "full_url":"xxxxxxx/xxxxxx/xxxxx.png",
            "title":"xxxxx",
            "xxxxx":"xxxxx"
        }
    ], 
    "files": [
        {
            "full_url":"xxxxxxx/xxxxxx/xxxxx.png",
            "title":"xxxxx",
            "xxxxx":"xxxxx"
        }
    ], 
    "tags": ["mac-webstorm", "webstorm"]
}
```

## Actual Behavior

Only file ID was returned, and no other data was included.

## Other Context & Screenshots

![image1](https://github.com/cdwmhcc/yeti/blob/master/Xnip2019-04-18_23-58-26.png?raw=true)
![image2](https://github.com/cdwmhcc/yeti/blob/master/Xnip2019-04-18_23-59-00.png?raw=true)

## Technical Details

- Device: [Desktop]
- OS: [macOS 10.13 High Sierra, CentOS Linux 7.6.1810]
- Browser: [ Chrome 73.0.3683.103 x64]
- Directus App: [ 7.1.0]
- Directus API: [2.0.20]
- Install Method: [cloned `master`  branch]
- Web Server: [Nginx 1.8.1]
- PHP Version: [7.2.13]
- Database: [MySQL 5.6.37]

**Comment by cdwmhcc** [comment]
There is another question:
How to settings upload multiple files?

@benhaynes  @WoLfulus @netmee @syslogic

**Comment by benhaynes** [comment]
Try using the `fields` parameter to return the relational file info. That is how you fetch deeper data (instead of just the primary key). :)

https://docs.directus.io/api/reference.html#fields

**Comment by benhaynes** [comment]
For multiple files you would use the `files` interface... although it's new and there might be some issues with it.

https://github.com/directus/app/tree/master/src/interfaces/files

**Comment by cdwmhcc** [comment]
> Try using the `fields` parameter to return the relational file info. That is how you fetch deeper data (instead of just the primary key). :)
> 
> https://docs.directus.io/api/reference.html#fields

[http://pertim.top/_/items/mac?fields=icon.](http://pertim.top/_/items/mac?fields=icon.)


``` json
{"data":[{"icon":{"id":11}}],"public":true}
```

**Comment by cdwmhcc** [comment]
@benhaynes

**Comment by benhaynes** [comment]
Hey @cdwmhcc — no need to mention everyone in each comment, we pay attention to all tickets. 

You requested the field but didn't add a wildcard to fetch deeper:

`http://d.pertim.top/_/items/mac?fields=id,title,icon.*,files`

Or

`http://d.pertim.top/_/items/mac?fields=*.*`

**Comment by cdwmhcc** [comment]
> Hey @cdwmhcc — no need to mention everyone in each comment, we pay attention to all tickets.
> 
> You requested the field but didn't add a wildcard to fetch deeper:
> 
> `http://d.pertim.top/_/items/mac?fields=id,title,icon.*,files`
> 
> Or
> 
> `http://d.pertim.top/_/items/mac?fields=*.*`

`http://d.pertim.top/_/items/mac?fields=id,title,icon.*,files`
Or
`http://d.pertim.top/_/items/mac?fields=*.*`
When opened, it shows：

![image](https://user-images.githubusercontent.com/8030134/56423402-7bc0b780-62de-11e9-8a56-d1365575c596.png)


The above solution does not display other field information of the picture. If I want to show how to set up the following picture, my admin link:

http://d.pertim.top/admin/#/login 
mobanbox@gmail.com
123456

![image](https://user-images.githubusercontent.com/8030134/56423211-ac542180-62dd-11e9-86c1-d5fae95bdb91.png)

## I want to show this in the red box of the picture, not just an ID.


Thank you very much!!!

**Comment by benhaynes** [comment]
Sorry, this is a configuration issue (not a bug). If you need help setting up then you can talk to our community on https://directus.chat

**Comment by cdwmhcc** [comment]
> Sorry, this is a configuration issue (not a bug). If you need help setting up then you can talk to our community on https://directus.chat

My problem has been solved, thank you

**Comment by adamjgrant** [comment]
Can we please post here what the configuration issue was? As far as I can tell, an out of the box implementation of directus would lead a user down this path and it's not clear from the docs how to resolve.

**Comment by adamjgrant** [comment]
PSA: I believe one needs to go to Roles & Permissions, then open up the system permissions, then allow for view access to "files" accordingly. In my case, I allowed public role access to view files.

**Comment by rijkvanzanten** [comment]
@adamjgrant By default everything is hidden for the public role (or any other created non-admin role)

**Comment by rijkvanzanten** [comment]
The confusion here comes from the fact that making the `image` interface field in the "main" collection isn't enough to return files as the role needs permission to read the actual files too. Only giving the user permission to read the field that holds the primary key, but not the files collection itself will result in the API only returning the file ID, not the file data. (when using the `fields` parameter)

**Comment by jomuji** [comment]
@rijkvanzanten did you find a workarround for this?

**Comment by MrSunshyne** [comment]
@jomuji You need to "check" the "Show system collections to see the Files collection. Then Allow it for public. 
I wonder if allowing public read permission to all files creates a security problem..
