### ISSUE TITLE
Latest design issues I've found.

### ISSUE THREAD

**Issue by shealavington** [directus/app#1515]
# Bug Report

1) Text needs some padding from the ege
2) Text is going under the icon.
![image](https://user-images.githubusercontent.com/16869302/56419344-ce27b700-6291-11e9-91e3-8d7ed2faf435.png)

1) Could we get some kind of a hover-state on the add button? Before the word "New" appeared, but it's not as clear now, unless you rely on the `cursor: pointer` showing up.
![image](https://user-images.githubusercontent.com/16869302/56419483-48583b80-6292-11e9-9edd-9e9877da9209.png)

1) Global colour doesn't seem to be used anymore.
![image](https://user-images.githubusercontent.com/16869302/56419792-70946a00-6293-11e9-8db2-745e5fdc19e1.png)

1) Options button with delete option seems rather long...
![image](https://user-images.githubusercontent.com/16869302/56419871-ad606100-6293-11e9-8d03-5029b2a9e8d4.png)

**Comment by rijkvanzanten** [comment]
Re: 3

I've re-used the existing label text in a tooltip:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/9141017/56431525-fadecd00-6297-11e9-98b8-79512fd7e772.png">


@benhaynes thoughts on that? I'm not too sure about the look 🤔

**Comment by rijkvanzanten** [comment]
We've reduced the amount of times that the accent color is used tremendously. It's now only used for things that require accents, like the active bookmark icon.

**Comment by shealavington** [comment]
_( I'm personally not keen on the tooltip there 😂 )_

I feel like before, the accent was used as less of an accent, but more as a "Branding" mark for projects?.. 
Perhaps now it's been removed from too much?..

It now feels very "DirectusCMS" rather than "My custom backend", I already miss the splash of colour behind the Logo-Section, and it all feels rather dark now. 👀 

Maybe it should be open to more discussion from others, about how much and what it should be used on.

**Comment by rijkvanzanten** [comment]
The colors have been discussed in https://github.com/directus/app/issues/1236. 

> It now feels very "DirectusCMS" rather than "My custom backend", I already miss the splash of ~colour~ color behind the Logo-Section, and it all feels rather dark now. 👀

I agree!

In the final design from #1236, we'll have more accurately defined colors (eg "module-fg", "module-bg", "page-fg", "page-bg") etc which allows full theming of the system. Right now all the colors are "hardcoded" (they're still variables, but they're called "light-gray" etc). Once we have all those correct variables in place, we can open up theming Slack-style

**Comment by shealavington** [comment]
> In the final design from #1236, we'll have more accurately defined ~colors~ colours

Awesome, that sounds good!

> Right now all the ~colors~ colours are "hardcoded". Once we have all those correct variables in place, we can open up theming Slack-style

Ah, yeah I follow what you mean, sounds like a good idea!

**Comment by benhaynes** [comment]
A few points:

1. Rijk is right, anyone looking to totally change the look can do so easily with SCSS/CSS/Variables. 
2. These will be editable in the theming (when it's done)
3. The splash behind the logo will be working today, and is a _new_ `brand` variable (different from accent).
4. The reason for this change is not to be more "Directus", but because apparently 90% of all brands use **red** and that messes up our UX (red for save is a no-no). I have uncommitted code that makes the save button `success` (green) on hover, but am not sure if that's the right move yet. Maybe!

**Comment by rijkvanzanten** [comment]
Better @shealavington?? 😉 

<img width="889" alt="image" src="https://user-images.githubusercontent.com/9141017/56434060-13071a00-62a1-11e9-965b-ab08e5ce181c.png">
