### ISSUE TITLE
New Group Styling

### ISSUE THREAD

**Issue by benhaynes** [directus/app#152]
```
border: 1px solid var(--lighter-gray);
border-radius: 3px;
padding:20px;
```

And then adjusting the group header (summary) to be full width and properly spaced.

![screen shot 2018-04-16 at 12 19 53 pm](https://user-images.githubusercontent.com/522079/38822127-8689249e-4170-11e8-9672-e26f69516ad3.png)

**Comment by rijkvanzanten** [comment]
Note that this will also update the group styling on the settings pane.

**Comment by benhaynes** [comment]
No problem. Though it would be nice if we had two options for `GROUP` interfaces... "section break", and "grouped fields". Both have good use cases and serve slightly different purposes.
