### ISSUE TITLE
Color palette width

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1523]
Im not realy sure why this happens and also could't fix it but heres the problem:

The witdh of the button (column) doesn't match up with the others when selected even tho there is enough space and no need for having a larger width.

![grafik](https://user-images.githubusercontent.com/22577866/56447517-0c13f200-6309-11e9-9dc4-410ec35e8dab.png)

**Comment by shealavington** [comment]
![image](https://user-images.githubusercontent.com/16869302/56855104-089bee80-6939-11e9-961f-081acf41e7a5.png)

Is this a specific browser issue @Nitwel — I'm not quite sure what I'm actually looking for here.

**Comment by Nitwel** [comment]
When you select a color, the column of the color increases in width even if the column is large enough.

**Comment by shealavington** [comment]
Oh I see haha—Like this?

![image](https://user-images.githubusercontent.com/16869302/56855150-130ab800-693a-11e9-9101-dee0e3acaeba.png)

**Comment by Nitwel** [comment]
Yep 👍

**Comment by shealavington** [comment]
Going to look at it now 👍
