### ISSUE TITLE
Can't Login - Directus (190419A)

### ISSUE THREAD

**Issue by Mu9tafa-Online** [directus/app#1524]
## Steps to Reproduce

1. Install Directus (190419A)
2. Try to login
3. Error on login page

## Expected Behavior
Login Successfully 
## Actual Behavior
I can't login after fresh installation
Message: Server Error / Something is wrong with this instance’s server or database.
## Other Context & Screenshots

[https://imgur.com/oqtFoEn](url)

## Technical Details

- Device: Desktop
- OS:  Windows 10.1809
- Browser: [chrome, opera] => Latest
- Directus (190419A)
- Install Method: fresh installation of Directus (190419A)

**Comment by Nitwel** [comment]
Can you give more detail, how you installed directus. From which branch, did you use the directus suite and so on.

**Comment by Mu9tafa-Online** [comment]
> Can you give more detail, how you installed directus. From which branch, did you use the directus suite and so on.

Yes I Installed Directus Suite / i explain above : Directus (v190419A)

**Comment by rijkvanzanten** [comment]
How? On what server stack? What do we need to know about the environment in order to reproduce this? Apache / Nginx / Caddy? PHP version? Etc

**Comment by Mu9tafa-Online** [comment]
> How? On what server stack? What do we need to know about the environment in order to reproduce this? Apache / Nginx / Caddy? PHP version?

[Laragon ](https://laragon.org)=> Apache , PHP 7.1.15

**Comment by shealavington** [comment]
This might sound silly, but did you actually go through the install process—you do have a database setup?.. 

I occasionally see people getting that error because they think everything's been setup, but they never actually saw an "install" screen of the app, therefore couldn't login as there wasn't a database.

**Comment by Mu9tafa-Online** [comment]
It is working on the new version (7.3)
