### ISSUE TITLE
🐰 Community Review: New UX for public pages (login, install, reset password)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1525]
Updated to match the vertical pane layout in the App. Would love the community's feedback!

# Sign In
Shown with optional (future) Register button, optional SSO options, and while in-progress. Also shown using the brand color/logo to tailor the login experience (could include images here later). The text that updates (eg: `fetching data`, etc) would move to the light-gray text at the bottom of the pane.

![Directus 8 – Login Register](https://user-images.githubusercontent.com/522079/56464609-74bba700-63bb-11e9-9f3a-880813342282.png)

![Directus 8 – Login Project](https://user-images.githubusercontent.com/522079/56464611-78e7c480-63bb-11e9-9ce0-c4a09bee9127.png)

![Directus 8 – Login In-Progress](https://user-images.githubusercontent.com/522079/56464612-7be2b500-63bb-11e9-9038-ea74427e9fd4.png)

## Reset Password

![Directus 8 – Reset Password](https://user-images.githubusercontent.com/522079/56464617-89983a80-63bb-11e9-88b2-aba9e83aeaa9.png)

# Create Project
Shows what you see when the selected API has no configured projects. Then walks through the setup steps and lets you sign in once complete. We could have a visibility toggle on the admin password shown in the last mock.

![Directus 8 – Install Requirements](https://user-images.githubusercontent.com/522079/56464624-a16fbe80-63bb-11e9-899a-02aa104c95a6.png)

![Directus 8 – Install Project](https://user-images.githubusercontent.com/522079/56464627-a7659f80-63bb-11e9-8796-5ae097a1e1ad.png)

![Directus 8 – Install Database](https://user-images.githubusercontent.com/522079/56511522-cc146100-64fa-11e9-956a-32395b777e01.png)

![Directus 8 – Install Wrapping Up](https://user-images.githubusercontent.com/522079/56464630-b8161580-63bb-11e9-8380-da3598f58612.png)

![Directus 8 – Install All Set](https://user-images.githubusercontent.com/522079/56511541-da627d00-64fa-11e9-928f-62f7e0de8de4.png)

**Comment by shealavington** [comment]
❤️ I love it! 

One: Could we get some kind of a "description" on the install page that reminds people, a database needs to exist, the app won't create the database, it'll just populate one, even in an information tooltip or something.

Two: I'm not too keen on one bit of the last screen, the section mentioning "Your details", could they go inside disabled inputs or something? The styling doesn't feel right as plain text.

**Comment by rijkvanzanten** [comment]
> I'm not too keen on one bit of the last screen, the section mentioning "Your details", could they go inside disabled inputs or something? The styling doesn't feel right as plain text.

Agreed! Do we even need to show that at all? I know it's all optics, but it doesn't feel secure to see your password out there in plain text. Also, you just entered those values minutes ago so you should know them.

**Comment by benhaynes** [comment]
Thanks @shealavington!! We'll circle back and update this again when we allow for different schema options on install (eg: `blank`, `existing`, `demo`, etc)

![Directus 8 – Install Database](https://user-images.githubusercontent.com/522079/56511477-af782900-64fa-11e9-8e76-7183e85dba0e.png)

**Comment by Nitwel** [comment]
And it could be animated really nice too:
![GIF](https://user-images.githubusercontent.com/22577866/56527923-b597f500-654e-11e9-8fb4-516921bb1dc6.gif)

**Comment by benhaynes** [comment]
Yeah! I was actually thinking that the white part of Sign-In expands to the right to fill the page (since the App background is white), and then the App Module/Nav bars slide in from the left. This would keep all the movement in the same direction for loading, which might be nice.

I'm sure @rijkvanzanten already has his brain juices bubbling on this one... he wanted to start in on it as soon as he saw the updated design! 😄

**Comment by theharshin** [comment]
This is not related to public pages but I think the icons in the sidebar are too dark and catchy. Those can be a little lighter? Also, the `icon` and `label` are not vertically aligned. I used `display:flex` & `align-items:center` to fix that.

Also the margin between `icon` and `label` does not follow the UI guidelines of **Spacing** 😉 

Before:
![image](https://user-images.githubusercontent.com/7118937/56786484-c24e6e80-6816-11e9-9f30-d5c0d072e409.png)

After:
![image](https://user-images.githubusercontent.com/7118937/56786882-1dcd2c00-6818-11e9-962e-250c00809328.png)

**Comment by benhaynes** [comment]
Thanks @theharshin! I've been trying to increase contrast in the new version because we've had a bunch of users complain about our grays being too "low-contrast". But This works for me.

As for spacing and alignment... I'm always on board with cleaning up and standardizing things! Is there a PR for this?

**Comment by rijkvanzanten** [comment]
> does not follow the UI guidelines of Spacing

What guidelines?

**Comment by benhaynes** [comment]
Presumably: https://material.io/design/iconography/#icon-treatments

**Comment by rijkvanzanten** [comment]
I think he's talking about the margin between the icon and the text

**Comment by Nitwel** [comment]
Yep, your brain doesn't know directly what goes with what when the spacing is the same vertical as horrizontal. 👍

**Comment by benhaynes** [comment]
Yeah, I didn't see a spacing section, but usually those guidelines talk about min/max/ideal spacing between an icon and other icons/text.

Either way, I'm a fan of this change — so let's PR it! 😄

**Comment by theharshin** [comment]
@rijkvanzanten @benhaynes The point @Nitwel made is right in terms of UI. Also, the Directus Style Guide says that spacing should be in increments of 10. For lower values than 10, it should be even. I don't know if we should apply this in only larger components or layouts but the spacing is `15px`, an odd value 😄
https://docs.directus.io/guides/style-guide.html#spacing

**Comment by fl034** [comment]
I love the current login UX :).
We live in times where screens are getting wider and wider, so I'd prefer a centered login and setup.

**Comment by benhaynes** [comment]
@theharshin — Sounds good. Directus is moving to a 4px/8px spacing unit... so 20px seems like the magic number.

@fl034 — Noted! I like the current design too, there were a few reasons for this proposed change:

* Standardize the design system (we're shifting to columns everywhere)
* Give ourselves a bit more room for the install form
* Have a good place for custom branding (for users)
* Differentiate between Core and Cloud logins

**Comment by fl034** [comment]
Seems like you've really thought this through :)
Alright then I won't complain when I have to turn my head a few times to the left 😋

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
