### ISSUE TITLE
Issues with form layout

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1526]
I'm seeing some phantom rows/columns with the new form layout grid. Notice the third row is empty and the last column is empty... yet both still occupy space on the form.

![Screen Shot 2019-04-21 at 2 22 47 PM](https://user-images.githubusercontent.com/522079/56474014-67e19680-6441-11e9-9979-4798ecd313b9.png)

**Comment by rijkvanzanten** [comment]
The extra column is expected behavior, that's the difference between "full" and "fill"

**Comment by rijkvanzanten** [comment]
I've added a full-width mode for the edit form that disabled the third column and forces the two columns to fill the width of the container (in this case the modal)
