### ISSUE TITLE
Fix calendar interface width

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1530]
Make it only show 7 days across

**Comment by Nitwel** [comment]
Could you provide an image?
Somehow the interface isnt responding to month changes also, so the arrow buttons do nothing.

**Comment by rijkvanzanten** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/9141017/56514944-a8561880-6504-11e9-9c89-396df95b11db.png">

See how it says "sun mon tue wed the fri sat", but then shows 15 days? 🙂

**Comment by Nitwel** [comment]
Already on this or can I fix it?

**Comment by rijkvanzanten** [comment]
I'm on it! Thanks though 🙂 

People can go crazy: 

<img width="1827" alt="image" src="https://user-images.githubusercontent.com/9141017/56518518-b2c8e000-650d-11e9-9f15-32aedb2197bf.png">
