### ISSUE TITLE
Vue.click not triggering on components

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1532]
In the calendar layout, the @click listener is used on the v-icon component. This is an issue because the listener wont call. To fix it, there are 2 options:

1. Use the @click.native method instead of just click.
2. Add the click listener to the component itself and then emit the click event.

**Comment by rijkvanzanten** [comment]
This is expected behavior for nested vue components. @click.native should be used for nested components. That being said, for a11y reasons we should go with option 3:

3. Wrap the icon in a <button> component and add the click event to that

**Comment by Nitwel** [comment]
Im confused, isn't option 3 the same as option 2?

**Comment by rijkvanzanten** [comment]
I thought you meant adding `@click="$emit('click')"` to the `<v-icon>` component, I'm saying we should wrap the `<v-icon` use in the calendar with a `<button>`

**Comment by Nitwel** [comment]
Ah, makes more sense now. 👍

**Comment by Nitwel** [comment]
I can do a PR if you want?

**Comment by rijkvanzanten** [comment]
Sounds good! Thanks 🙂
