### ISSUE TITLE
File Interface - Select from Device Does Not Load Dialog

### ISSUE THREAD

**Issue by srjrol** [directus/app#1536]
# Bug Report

## Steps to Reproduce

1. Go to `File` field.
2. Click on `Select from device` icon.
3. Notice no browse for file dialog appears.

## Expected Behavior
Browse dialog should appear to browse for a file from the computer.
## Actual Behavior
Nothing appears to happen.
## Other Context & Screenshots
This was working until the latest release.  I am still able to drop files to upload them but I prefer this method.  Tested on https://directus.app (stable/latest) and https://next.directus.app (stable/latest) as well as my own instance.

![image](https://user-images.githubusercontent.com/34398302/56539143-a0a96a80-652a-11e9-8a70-b49c43a22246.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome / Firefox
- Directus: 190422A
- Install Method: Cloned `master` branch of `directus/directus`

**Comment by justrealmilk** [comment]
Mine is also dead. New File and Existing still work though

**Comment by Nitwel** [comment]
Is the same issue as in #1532. I'll create a PR and it should be fixed.
