### ISSUE TITLE
Cannot upload any images to the App

### ISSUE THREAD

**Issue by yarick2000** [directus/app#1541]
# Bug Report

## Steps to Reproduce

1. Go to File Library
2. Click on '+' button
3. Open the select the file and drag and drop it to drop area

## Expected Behavior
File is uploaded
## Actual Behavior
The error is shown - {filename} can't be uploaded. Your server is not configured to handle uploads of this size.
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/13006578/56611260-59c97c80-65df-11e9-9aae-4eca0149491d.png)

It seems like in the app in store/modules/server-info/actions.js instead of calling projectInfo() method from JS SDK the serverInfo() method has been called. That causing to situation when instead of getting information from /{project}/ API route the app trying to call the root route:
![image](https://user-images.githubusercontent.com/13006578/56611540-060b6300-65e0-11e9-917c-731102d95307.png)
This is causing the error and so default values are used in this case, but they missing max_upload_size information.
And so when I'm trying to upload any image I'm getting error because this property is not set.
I see that in **pgsql** branch this call is already fixed, but not in master branch. Could you please fix it in master as well? This is pretty critical issue, I think.

## Technical Details

- Device: [Desktop, ]
- OS: [Windows 10.1803]
- Browser: [Chrome 73.0.3683.103]
- Directus App: [eg: 7.3.0]
- Directus API: [eg: 2.0.22]
- Install Method: [separate App and API build branches]

**Comment by benhaynes** [comment]
@rijkvanzanten any thoughts on this one?

**Comment by rijkvanzanten** [comment]
🤷🏻‍♂️

I think it's a configuration problem on the server stack..

Also, re the serverinfo v projectinfo, the / endpoint returns the max upload size as well. 

https://next.demo-api.directus.app/_/?access_token=demo

**Comment by yarick2000** [comment]
Oh, I've forgot to mention that this is NGINX setup.
I've made a fix for root location and so now the error in network tab is gone and request to /files route happens:
`        location / {
                if ($request_method = OPTIONS ) {
                        add_header Access-Control-Allow-Origin *;
                        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, HEAD";
                        add_header Access-Control-Allow-Headers "Access-Control-Allow-Headers, Content-Type, Authorization";
                        add_header Access-Control-Allow-Credentials "true";
                        add_header Content-Length 0;
                        add_header Content-Type text/html;
                        return 200;
                }

                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                try_files $uri $uri/ /index.php$args;
        }`
However I still cannot upload file, getting 502 error:
Request URL: http://api.directus.com:8080/casino/files
Request Method: POST
Status Code: 502 Bad Gateway
Remote Address: 192.168.0.2:8080
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept: application/json, text/plain, */*
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTU2MTQ5NTgxLCJ0eXBlIjoiYXV0aCIsImtleSI6Ijc4MzMzODMzLTg2ZDctNDYwNC1iM2Q3LWRhMDgwNmM5NTkxMCIsInByb2plY3QiOiJjYXNpbm8ifQ.Hls3AXV62FuFQKJVfwvfe-FoJbA6r4jheYA8DAvWd9E
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryfwaxTegN4WR670Nu
Origin: http://app.directus.com:8080
Referer: http://app.directus.com:8080/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
------WebKitFormBoundaryfwaxTegN4WR670Nu
Content-Disposition: form-data; name="data"; filename="cat.jpg"
Content-Type: image/jpeg

**Comment by yarick2000** [comment]
Ok, I've fixed the issue by editing /etc/php/7.3/fpm/pool.d/www.conf.
I've modified the following line from this:
;listen.mode = 0660
To this:
listen.mode = 0666
The issue can be closed
