### ISSUE TITLE
Stars interface. [bug][good first issue]

### ISSUE THREAD

**Issue by shealavington** [directus/app#1543]
# Bug Report

## Steps to Reproduce

Click on an item with "X Stars"

## Expected Behavior

Preload the stars field with the amount of stars currently selected.

## Actual Behavior

Displays 0 stars selected by default.

## Other Context & Screenshots

Changing the stars does work, it just doesn't load the right default in. :sob: 

![Selection_063](https://user-images.githubusercontent.com/16869302/56646726-08210080-6678-11e9-830f-2f863580237b.png)
![Selection_062](https://user-images.githubusercontent.com/16869302/56646727-09522d80-6678-11e9-86cf-86d71d91621e.png)

## Technical Details

- Directus App: 7.0.3

**Comment by benhaynes** [comment]
Thanks @dev7ch!! 😄
