### ISSUE TITLE
All custom form elements should emit regular event

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#155]
In a lot of elements, like `<v-input>` it just emits the value of the input, not the whole input event itself, which makes it impossible for specialized interfaces, like tags, to listen to things like `event.key`

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
I want to redo all the input form components to a more standardize structure including this change

**Comment by rijkvanzanten** [comment]
These types of optimizations are an ongoing effort and don't need to be tracked individually
