### ISSUE TITLE
Redirect after Login

### ISSUE THREAD

**Issue by mvhirsch** [directus/app#1555]
# Bug Report

Hi,

I'm just wondering, since this seems to work, but I don't think it's implemented correctly.
Being logged out of my private installed Directus App, a redirect to a specific collection/item would be awesome, since we're in charge of sharing deeplinks very often.

## Steps to Reproduce

1. Browse any Website which contains the link to your Directus App and click on the link (either opening a new tab or keep the current one) https://directus.example.com/#/collections/products/1704
2. Login with your credentials

## Expected Behavior

Being redirected to collections "products" and item with id "1704".

## Actual Behavior

Got user's directory (I think I've left it there).

## Other Context & Screenshots

It seems to be implemented, though!
Using other steps, shows that there is something, that should be enhance to fulfill a seemless behaviour:

1. Go to https://directus.example.com
2. Update the URL in your browser, adding a path: https://directus.example.com/#/collections/products/1704 (after pressing enter, Directus adds a "redirect" query parameter.
3. Login with your credentials

This effectively redirects me to my item.
But sending the above link to one of my colleagues, they just click on the URL an won't be redirected correctly.

Is  there something, I can do to help getting this fixed?

## Technical Details

- Device: Desktop
- OS: MacOS and Linux (both reproduceable)
- Browser: Chrome and Firefox (both reproduceable)
- Directus App: 7.0.18 (Docker)
- Directus API: 2.0.18
- Install Method: Docker

**Comment by shealavington** [comment]
>I don't think it's implemented correctly.

That said, I think I'd call this an enhancement for now @benhaynes.
After logging in, you can re-visit the link in the same authenticated tab, and the link would work. 

---

Current Implementation:
* Visit link (`/collections/products/1704`)
* _User is not authenticated_
* Get redirected to `/login`
* Successfully authenticate user (login)
* _Returns the user to their last used page(`/users`)_
* User can visit link in the same authed tab (`/collections/products/1704`)
* _User should see the item if they have the correct permissions_

The enhancement would be:
* Visit link (`https://directus.example.com/#/collections/products/1704`)
* _User is not authenticated_
* Get redirected to `/login`
* _Store the route (`/collections/products/1704`)_
* Successfully authenticate user (login)
* _**IF** a route was stored, goto the route (`/collections/products/1704`)_
* _**ELSE** return the user to their last used page_

**Comment by benhaynes** [comment]
True, it _could_ be considered an enhancement. However since we already have broken code for this in the App and it tried to use a `redirect` (or some other name) query param... I'd say it is technically broken. :fire:

**Comment by rijkvanzanten** [comment]
Yeah I agree with @benhaynes here. @shealavington your enhanced flow is exactly what it's supposed to do 😁

**Comment by shealavington** [comment]
Understandable—Sounds good, I'll probably jump on this one sometime this week. :wink:

**Comment by benhaynes** [comment]
Just noticed that `directus_users.last_page` is not being updated either. We need to get all the page redirection stuff working... it doesn't block functionality, but I'd say it's a `medium` priority issue.

**Comment by shealavington** [comment]
Is this now fixed @rijkvanzanten, based on that commit?

**Comment by rijkvanzanten** [comment]
It does fix the tracking of the last page, but I haven't tested if it fixes this exact issue too though. (I think it _should_)

**Comment by rijkvanzanten** [comment]
Just double checked it; https://github.com/directus/app/commit/9f83826b69541212865872c9fdea59e6fcbac3ef fixes it on my end 🙂
