### ISSUE TITLE
Share authentication across multiple tabs

### ISSUE THREAD

**Issue by mvhirsch** [directus/app#1556]
# Feature Request

Hi,

I've installed Directus via Docker in our own cloud, managing our data across the company.
That said, a fundamental element is missing: re-using the same authentication across multiple tabs.

I've [read about sessionStorage and using multiple projects](https://github.com/directus/app/issues/1369#issuecomment-472436976), sure. But using Directus within Docker allows us to manage multiple subdomains (each per project), setting up a immersive experience using different customized project urls. That said, a very important thing is missing: re-using the same authentication for this particular project.

## What problem does this feature solve?

It reduces negative pain and the need for re-login after every shared link, that was send over any communication transport (email, chat, github-issues, ... you name it). 
Sharing deeplinks between colleagues is (in my opinion) a fundamental thing in being extremely useful and fast while working with any toolset.

## How do you think this should be implemented?

Since this was already discussed and I know, that maintaining a project like Directus, supporting multiple projects, I know you should be able to switch between different projects any time, this should not be the goal while using different (sub)-domains. Especially while using Docker, which allows you to easily set up different Apps (each for a project and it's own subdomain).

I think, this could be implemented as a configuration switch: either you're using a multi-project App, or not. Using a multi-project App setup won't change anything in behaviour, but the later might be able to re-share the authentication information via LocalStorage Events across multiple tabs [as described in this article](https://blog.guya.net/2015/06/12/sharing-sessionstorage-between-tabs-for-secure-multi-tab-authentication/).

## Would you be willing to work on this?

Yes. We successfully implemented the above mentioned authentication behaviour in another private project. It's super simple and effective.
The only thing I need, is some direction on where to begin (since I'm not familiar with Vue.js).

**Comment by rijkvanzanten** [comment]
The only way we can accurately fix this is by storing multiple API access tokens for multiple projects at the same time, which would allow you to switch back and forth between projects without having to re-login. Combined with using localStorage instead of sessionStorage should fix this.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
