### ISSUE TITLE
WYSIWYG: bold style for titles not saved correctly

### ISSUE THREAD

**Issue by ninjabachelor** [directus/app#1557]
# Bug Report

## Steps to Reproduce

1. Create a Wysiwyg field
2. Set a text to be a title (H2, H3 or H4).

## Expected Behavior
The title should not be set bold by default. But, if that is the expected behaviour, the title should have the correct markup in the database. E.g. `<h2><b>New title</b></h2>`.

## Actual Behavior
Title is set bold as default, but in the database the markup is incorrect. E.g. `<h2>New title</h2>`.

## Other Context & Screenshots
![wysiwyg](https://user-images.githubusercontent.com/3736582/56822283-e2028880-6850-11e9-932f-33ab933a7cf6.jpg)

## Technical Details

- Device: any
- OS: any
- Browser: any
- Directus App: 7.3.0
- Directus API: 2.0.22
- Install Method: download release `190422A` of Directus

**Comment by benhaynes** [comment]
Thanks @ninjabachelor! We've been discussing merging both WYSIWYG editors into one since the upcoming TipTap-based interface supports the "inline" style too. So hopefully this won't be an issue once the new editor is merged in!

Ref: https://github.com/directus/app/issues/1334

**Comment by urvashithakar** [comment]
Hello @ninjabachelor,
Agree with @benhaynes. It might not be an issue once the new WYSIWYG editor is merged !

**Comment by rijkvanzanten** [comment]
This has been resolved in the new editor
