### ISSUE TITLE
Toggle interface shows wrong default value through modal

### ISSUE THREAD

**Issue by srjrol** [directus/app#1558]
# Bug Report

## Steps to Reproduce

1. Create a toggle field for the `Movie` collection with a default value of 0.
2. Open a Member item and add a new `Movie` item through the M2M field.
3. Notice the wrong default `1` is set for the toggle field.
4. Visit the `Movie` collection directly and notice the toggle field has the correct default value of `0`.

## Expected Behavior
Same toggle default should be used when adding a new item to the collection directly or through another collection via the modal interface.
## Actual Behavior
The default value of `0` is used when adding a new item to the collection directly.
The Default value of `1` is used when adding a new item to the collection using M2M interface modal.
## Other Context & Screenshots
![toggle_default_modal](https://user-images.githubusercontent.com/34398302/56822752-a26b7a80-6817-11e9-99ea-3ce594eb03d2.gif)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus: 190422A
- Install Method: Cloned `master` branch of `directus/directus

**Comment by Nitwel** [comment]
Hmm, i remember that I had simular issues at some time that interfaces wheren't initialized properly and showing the wrong default state. But I havent checked this in a while.

**Comment by benhaynes** [comment]
We'll take a look, but it'd be great to confirm this is an code issue (and not a specific build/config problem).
