### ISSUE TITLE
public testing App [suggestion]

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1561]
Simular to the example app we already have but instead of showcasing directus, the DB is setup in the way that all interfaces are present and in all their configuration forms.

Why you may ask?
This should make testing changes to directus much easier. When something gets broken, you directly see it and dont have to setup a testing area first. For example the star bug I had in FireFox would be found much earlyer because you dont have to go though each interface and create it and then test all configurations but see it directly when you login to the sandbox app.

In general it should help find bugs much easier. ^^

**Comment by rijkvanzanten** [comment]
For the interfaces themselves, you should be able to use the interfaces section in settings for this purpose too 😄

**Comment by Nitwel** [comment]
Hmm, right...
