### ISSUE TITLE
Add link/URL to File interface

### ISSUE THREAD

**Issue by stefanke** [directus/app#1567]
# Feature Request
Possibility to click on icon or extra link of an uploaded file to open/view the file in a new browser window.

## What problem does this feature solve?
We often need to upload pdf-files and those files only show an icon in the file field. 
Showing a link would enable us to view the pdf in a new browser window.

## How do you think this should be implemented?
Maybe add an option in field/interface "file" to display the full link to the uploaded file (i.e. http://directus_server.com/uploads/_/originals/filename.pdf).
In the file library this is already implemented: 
<img width="548" alt="FileLink" src="https://user-images.githubusercontent.com/15725888/56866945-c1b50400-69df-11e9-8e26-232f3c849074.png">

Maybe there is an easier solution? We also tried to edit the view options in the interface-options  by guessing the name for filenames, but they do not change the text/subtitle at all (even when we remove everything). We could not find any documentation about those fields...

{
    "title": "filename",
    "subtitle": "type",
    "content": "description",
    "src": "data"
}

## Would you be willing to work on this?
Unfortunately we can only help with testing.

**Comment by benhaynes** [comment]
You're right that this exists on the File Detail page already — but I'm a little confused as to where you would like this icon/URL added to. The File listing (cards)? An interface? Somewhere else?

**Comment by stefanke** [comment]
Sorry for the confusion and thanks for your quick reply! 

I think the best position for the icon/URL is on the edit page (above or below the file-box) because this is where we insert/upload the documents. I understand the concept that directus is a headless cms, and that we should do this via a frontend. But with all the great elements already there, it totally fits our needs for an internal database as it is - apart from the fact that we can not view our uploaded (pdf)-file.

<img width="1050" alt="EditingItmes" src="https://user-images.githubusercontent.com/15725888/56890250-3b4d0080-6a79-11e9-9833-dea3f59229d2.png">

**Comment by benhaynes** [comment]
Gotcha! I like this idea, and we're planning on refactoring the File interface soon too, so we'll include this in the update.

Depending on what the new design looks like, we could add `Open File` in the "..." contextual menu.

**Comment by stefanke** [comment]
Great! Looking forward to the update, and thanks for your help.

**Comment by dev7ch** [comment]
on refactoring, it might be worth to think about to allow directly update or change the url value where it is displayed

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by yagobski** [comment]
> Gotcha! I like this idea, and we're planning on refactoring the File interface soon too, so we'll include this in the update.
> 
> Depending on what the new design looks like, we could add `Open File` in the "..." contextual menu.

Any progress on this because there is no solution to download the added files

**Comment by rijkvanzanten** [comment]
@yagobski the file detail page has the link already (as mentioned above) and the file interface itself just got a download button in https://github.com/directus/app/pull/2141

**Comment by yagobski** [comment]
Thanks for the update.

Le ven. 31 janv. 2020 à 20:33, Rijk van Zanten <notifications@github.com> a
écrit :
