### ISSUE TITLE
Connect to Jekyll

### ISSUE THREAD

**Issue by bernardomed** [directus/app#1568]
# Feature Request
Please provide a connection plugin to Jekyll.

## What problem does this feature solve?
Make Jekyll work with Directus

## How do you think this should be implemented?
Creating a plugin to connect them.

## Would you be willing to work on this?
If I knew how to code on Ruby, I would.

**Comment by shealavington** [comment]
I'm going to add my personal opinion to this:

I find it frustrating that you've offered a suggestion without offering any solution. What's the reasoning for this feature, and how will this benefit Directus, and Directus users? This seems like an unjustified personal request.

On that note, I don't see how this would be implemented at-all... Directus simply wraps an API layer around a database, from what I read about Jekyll, it's a static site generator, so it'd depend on your integration, _would it not_?

**Comment by rijkvanzanten** [comment]
Hey @bernardomed! Thanks for the suggestion. @shealavington is right here, afaik there's nothing that we can provide specifically to "enable" Jekyll integration. From a quick Google search, there seem to be a couple Jekyll plugins that provide fetching data from an API source, like this one: https://github.com/18F/jekyll-get. 

I also recommend taking a look at Eleventy (11ty). It's _very_ similar to Jekyll, but is a bit more modern and easy to use. It also supports data fetching from external sources natively 😄 

https://www.11ty.io/docs/data-js/
