### ISSUE TITLE
Add "status mapping" interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1570]
@theharshin posted a great mock for this (ClickUp) that would make visualizing and setting up the status mapping much easier.

![](https://user-images.githubusercontent.com/7118937/56890031-ec619400-6a95-11e9-86f1-c5b84ac958c6.png)

**Comment by Nitwel** [comment]
Hmm, this will be a rough one. I think to implement such display we would need a whole new interface that allows such because how the settings of a field work at the moment, there is no easy way of doing it. The Interface would need to work using an json format and interpret it into a list. I'm not sure yet how this interface would acually function but I think I got an Idea. It tecnically would use the same structure as 
the status interface:

```
{
    "published": {
        "name": "Published",
        "text_color": "white",
        "background_color": "accent",
        "browse_subdued": false,
        "browse_badge": true,
        "soft_delete": false,
        "published": true
    },
    "draft": {
        "name": "Draft",
        "text_color": "white",
        "background_color": "blue-grey-200",
        "browse_subdued": true,
        "browse_badge": true,
        "soft_delete": false,
        "published": false
    },
    "deleted": {
        "name": "Deleted",
        "text_color": "white",
        "background_color": "red",
        "browse_subdued": true,
        "browse_badge": true,
        "soft_delete": true,
        "published": false
    }
}
```

The benefit tho would be that this could be used in many sections where there is a JSON field at the moment like in other fields setting. The only thing that will be more difficult is to set a status as a `done/closed` but I'll propably will figure it out.

**Comment by benhaynes** [comment]
Thanks @Nitwel! I'll put together an actual design for this. I think this would probably be a _specific_ interface just for setting up status (probably not used in other places), that way we can tailor it exactly to what we need here.

**Comment by Nitwel** [comment]
The interface could tecnically be used in the button group interface or the dropdown interface too

**Comment by benhaynes** [comment]
OK, so here is a first mock of this interface. I've used the "repeater" field design which is for inline relational data... but this one is for JSON. Some things I'm not happy with yet:

* We should use the _full_ color picker instead of the palette, but it's a lot larger. Alternatively we could use a text input for typing hex, but that's more annoying... or create a new interface that is a dropdown of all the MD colors.
* It'd be nice to have a preview of the status (with the foreground/background colors). Maybe this could go where the title is?
* This design would work for a specific Status Mapping interface... but it'd be nice to figure out how this could be a non-system interface too and work for any JSON. The problem is: _how would we setup fields for this?_ It's a lot easier when these fields are hardcoded.
* Because this is an interface that contains other interfaces, we'd need to figure out the width situation. Right now, the container items are 630px (the standard "full" width), but that means that the internal fields must be smaller than the standard 300px/630px while still maintaining the grid gap between. No perfect way to solve this unless it was more of an accordion split with only horizontal lines (not in full boxes). 

![Screen Shot 2019-05-15 at 7 53 45 PM](https://user-images.githubusercontent.com/522079/57816929-2e076580-774b-11e9-9d03-e713b3dd17da.png)

**Comment by Nitwel** [comment]
What about storing the type of interface in the config of the interface?

**Comment by benhaynes** [comment]
That works, but to be fully functional we would need to setup/store _all_ of the field info: `field_type`, `mysql_datatype`, `length`, `validation`, `required`, `default`, `unique`, as well as all the interface _options_ for the nested interfaces!

So even if we find a good way to store this setup info, I think we need to somehow re-use the "New Field" modal for new _nested_ fields.

Creating a "static" Status Mapping interface avoids this since all are hard-coded... but someday we should figure out how to make dynamic.

Does all that make sense? Haha, I know it's pretty meta/complex!

**Comment by Nitwel** [comment]
My Ideas are really messing with my head because its a bit recusive but I figure out a way how to do it that that some day, there wont be any json configs for the user anymore.

![](https://media3.giphy.com/media/l0HlTPnnfzRsf4f2U/giphy.gif?cid=790b76115cdd5da7666635353611ee1b&rid=giphy.gif)

**Comment by Nitwel** [comment]
Already getting somewhere:
![Screenshot_2019-05-16 Editing Item Status](https://user-images.githubusercontent.com/22577866/57887625-3be2e680-7830-11e9-8e8a-a01ad7456c7d.png)

But Im having trouble with an error which i cant figure out:
```
[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }":
"Error: [vuex] do not mutate vuex store state outside mutation handlers."
```
I pushed a first commit here: https://github.com/Nitwel/app/tree/statusMapping and I hope you could help me there @rijkvanzanten

**Comment by benhaynes** [comment]
Whoa, so fast! 👍👍

This is already looking awesome @Nitwel... I wish I knew about the error enough to help. As far as I know this is caused by trying to directly change a value in the store instead of sending it to a "mutation handler". 

Rijk is off this week, so the next time he'll be able to review this in Monday... but at least I don't think this is a Directus-specific error, so there's a good chance we can figure it out without him. :)

**Comment by Nitwel** [comment]
I drew down the data flow of a field and the issue occurs when the data stored in the filed gets changed.
Technically there is no difference to an ordinary interface but something must cause this error.

Hope this helps understanding the structure of the setup better.
![20190517_023602a](https://user-images.githubusercontent.com/22577866/57895648-0ef0fc80-784d-11e9-988b-d6c3dbcdf26f.jpg)

**Comment by benhaynes** [comment]
Thank you @Nitwel!!! I think Rijk will have an answer for this on Monday... especially with such a clear view of what's happening! :)

**Comment by rijkvanzanten** [comment]
> The Interface would need to work using an json format and interpret it into a list.

`Object.values()` 

```
[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }":
"Error: [vuex] do not mutate vuex store state outside mutation handlers."
```

This often happens when you accidentally modify a value that originated from the store. Eg, 

```js
let object = this.$store.state.object;
object.value = object.value + 1;
```
now it'll complain because you're modifying the store directly.

@Nitwel while it kinda works, that data flow has turned out to be pretty difficult to manage. I'd love to go straight from any interface—store..

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Nitwel** [comment]
![Screenshot_2019-05-20 Settings Editing Item Test(1)](https://user-images.githubusercontent.com/22577866/58053165-018e8780-7b57-11e9-86a5-dba1e17c1a89.png)
🎉 🎉 

Already working really nice but still much customability to do. I'll create a PR and add some notes what is still to do.

**Comment by benhaynes** [comment]
Thank you!! Things really look like the are cruising along nicely. 😄 

I like having the color in the header... so I updated the Sketch mockup a bit:

![Screen Shot 2019-05-21 at 2 58 48 PM](https://user-images.githubusercontent.com/522079/58123242-612d7700-7bd9-11e9-9648-bc74a22ec4fb.png)

That color palette seems a little dated, so we should probably update that to be more like this mock too. I'll try to find time for that this week unless you get there first!

Can't wait to check out this PR!

**Comment by Nitwel** [comment]
The issue with coloring the text of the header is that I use the v-ext-display to make it 100% customizeable. At the moment you have for each field the option to show it in the header and in the example above I had set this for the title and color field.

**Comment by benhaynes** [comment]
Ahh, that makes sense. For a minute I though that this was a specific `status mapping` interface... but I forgot that we can basically use it for _any_ JSON options! :)

Let's just try to get the other styling updated and I guess this will be in a good place to review!

**Comment by Nitwel** [comment]
The interface now also supports the dropdown and simular interfaces.
![Screenshot_2019-05-22 Settings Editing Item Test](https://user-images.githubusercontent.com/22577866/58196194-0fb0e500-7cca-11e9-8239-434e2849862e.png)
