### ISSUE TITLE
Use Tags Interface for IP Whitelist field (Settings)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1574]
Instead of a huge textarea for a CSV, we should use the `tags` interface so each IP is more easily added/deleted (and the interface is smaller).

Ideally we can have a regex (either using the existing field validation regex, or a new interface option) so that we can confirm the format before adding it. This would be a good addition to the tags interface too, since it would allow more control over what format tags could be entered.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
ref: https://github.com/directus/app/pull/1721
