### ISSUE TITLE
Nav Override Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1575]
This is a mock design for a dedicated system interface to control the Navigation Override. @rijkvanzanten you have a `collections` include, but we should also allow for individual collections to be added (as seen here) so that they can be reordered (non-alphabetical) or differently colored.

You are also using groups, while this uses dividers — we'll want to look into the best way to accomplish this. I like groups because they allow us to collapse (in the future)... but dividers are easier to setup since it keeps things linear. 

![Directus 8 – Settings Role](https://user-images.githubusercontent.com/522079/56985604-b506ec00-6b56-11e9-9031-f42c5c2b1e54.png)

Ref: https://github.com/directus/app/issues/125

```
[
    {
    	"title": "Collections",
        "include": "collections"
    },
    {
    	"title": "Style Guide",
        "links": [
            {
            	"name": "Directus",
                "path": "https://example.com/style-guide",
                "icon": "link",
                "target": "__blank",
                "color": "green"
            }
        ]
    },
    {
    	"title": "Favorites",
        "include": "bookmarks"
    }
]
```

**Comment by rijkvanzanten** [comment]
A group can still work in this linear setup though. A group is nothing more than the selection of rows between two dividers

**Comment by rijkvanzanten** [comment]
Also, links can go to internal pages as well:

```
           {
            	"name": "Directus",
                "path": "/collections/movies",
                "icon": "link",
                "color": "green"
            }
```

**Comment by benhaynes** [comment]
That's exactly what I was thinking — it's a system interface so we can decide how it processes and saves the JSON. 

One thing that some people might find annoying is that the icons will be saved on the collection detail page, not the nav override. I think it might be a little confusing to have both.

Also, would want to add away in the JSON to allow for coloring the includes and changing their icons.

**Comment by ceruulean** [comment]
Maybe for now the icon can just get the name of the one already set in collections?

**Comment by ceruulean** [comment]
You want the below setting to make everything green?
`           {
            	"title": "Section Title",
                "includes": "collections",
                "color": "green"
            }`

Also would "target" be for an "Open in new window?" option? (i don't think iframes are very common but still has use cases like opening the youtube source page)

**Comment by benhaynes** [comment]
Yes, that would turn the whole collections area green. If you wanted individual collections to be different colors you would need to add them individually.

Yes, the Target key would be for opening in a new tab or the same page.

I believe the drag handles and three contextural menus are already consistent across the system. But if you see any examples where they're not let me know and we'll fix it.

**Comment by herrbomm** [comment]
I love that! I would also be nice to choose between "divider" or a "headline" to name the groups. 
I accidently opened a request/issue regarding that today. Haven't found/seen this post here.

**Comment by benhaynes** [comment]
Hey @herrbomm — great idea! I like the idea that dividers could also have an optional name... I'll need to come up with a design for how this would look.

**Comment by herrbomm** [comment]
> Hey @herrbomm — great idea! I like the idea that dividers could also have an optional name... I'll need to come up with a design for how this would look.

Well, for me it would be "**either**" a divider (=> h-line) "**or**" a section-name (text).

**Comment by ceruulean** [comment]
There could be a button "New Section" and you have the optional Title field to fill out, otherwise dividers will automatically appear between sections.

**Comment by herrbomm** [comment]
> There could be a button "New Section" and you have the optional Title field to fill out, otherwise dividers will automatically appear between sections.

That follows my intention/idea ;)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Nitwel** [comment]
> That's exactly what I was thinking — it's a system interface so we can decide how it processes and saves the JSON.

To do this we could use the repeater interface and make it into an internal component (but still have it as an interface) because the interface 💯% supports your given structure above the only thing that could be added is that the interface supports multiple templates for fields depending on which item you want to create.
