### ISSUE TITLE
Is it possible to open directly file (or get a link) without going to File Folder?

### ISSUE THREAD

**Issue by andriipol** [directus/app#1577]
# Feature Request
Is it possible to open directly a file (or get a link) without going to File Folder?
Thanks in advance.

![image](https://user-images.githubusercontent.com/12764733/57148667-c5c39600-6dd2-11e9-836f-b3b3964715e7.png)

**Comment by benhaynes** [comment]
I think it might be risky to have the main title open the raw file since the default action is to open the File Detail page. But I agree that there should be an easier way to access this link.

I believe it should be added to the card's contextual menu (three dots on right) as: `Open Original File`

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
