### ISSUE TITLE
Clean up antialiasing on image corners

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1579]
I had a fix for these ugly corners, but it was causing a different issue with the File interface and was removed. We need a solution to keep our rounded image borders looking clean!

Ref: https://github.com/directus/app/commit/1b889506789e1c21a0740e3e1ae6863bbe153986

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/57157283-4c19b100-6dae-11e9-8dd4-30f4d2f0fd0c.png)

what ugly corners. this is most likely a very specific issue between the combination of browser, os, and monitor.

**Comment by benhaynes** [comment]
Feel free to mark this as #ocd — but here is with and without the image background color. It's more noticeable on lighter images (in Chrome at least) and seems to be the background color of the card peeking out.

![Screen Shot 2019-05-03 at 3 04 53 PM](https://user-images.githubusercontent.com/522079/57159821-fb598680-6db4-11e9-8242-24d7f4a8dd11.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
