### ISSUE TITLE
Many to many error 'Cannot read property 'type' of undefined'

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1585]
# Bug Report

![image](https://github.com/cdwmhcc/public/blob/master/2019-05-06%2005.13.47.gif?raw=true)

## Steps to Reproduce

01、Create a Collection named `categories`.
02、Add field `name`, `alias`, chooise interface text input
03、Add new field `parent categories`, interface `many to one`, Relation > Related Collection  `categories`,Options > Dropdown Template `{{alias}} - {{name}}`.
04、Then enter Collection`categories` to create categories `A`, `B`,creat categories `A1`,select parent categories `A`
05、Create a Collection named `Blog`.
06、Add new field `title`, `slug`, `content`,Add new field 'category' ,interface  `Many to many`,Relation > Related Collection  `categories`, Click Auto-Generate,Options > Visible Columns `categories.name`. Display Template `{{categories.name}} - {{categories.alias}}`
07、Then go to Blog and add new content,Select Category by Existing 
![image](https://user-images.githubusercontent.com/8030134/57200715-ab9bda80-6fc1-11e9-8ed0-5bf91aa00d0a.png)

## Expected Behavior

Let me choose the category

## Actual Behavior

![image](https://user-images.githubusercontent.com/8030134/57200747-fb7aa180-6fc1-11e9-9e0f-413955c9ea73.png)

## Technical Details

- Device: [Desktop]
- OS: [macOS 10.13, macOS 10.14]
- Browser: [ Chrome 73.0.3683.103 x64]
- Directus App: [ 7.3.1]
- Directus API: [2.0.23]
- Install Method: [cloned `master`  branch]
- Web Server: [Nginx 1.8.1]
- PHP Version: [7.2.13]
- Database: [MySQL 5.7.2]

**Comment by henrikwirth** [comment]
How does your junction table look like? Because when you use autocreate, it generates something like `categories_id` and `blog_id`. Therefore your Display Template should be `{{categories_id.name}} - {{categories_id.alias}}`

And i think for Visible Columns `name` would be enough. But I am not sure.
