### ISSUE TITLE
Status doesnt get set on translations

### ISSUE THREAD

**Issue by herrbomm** [directus/app#1588]
# Bug Report
I cant set a "Status" in the translations-item when creating the primary item. So the items get saved without a status and therefore are not visible in the list. I first have to manually put in a status in the database for the items to be seen. 

## Expected Behavior
Being able to set the status on every language inside the primary item. 

## Actual Behavior
No status-bar visible when creating the item and no status is set initially.

**Comment by rijkvanzanten** [comment]
Does the field label show up? Are there any errors in the devtools?

**Comment by herrbomm** [comment]
### When entering the translation initially, the form looks like this:

![Bildschirmfoto 2019-05-06 um 17 00 37](https://user-images.githubusercontent.com/50315804/57234372-b9347d00-7020-11e9-9a39-943d49a2c07f.png)



### After manually changing the status directly in the DB to "published" the form looks like this:

![Bildschirmfoto 2019-05-06 um 17 00 05](https://user-images.githubusercontent.com/50315804/57234434-dff2b380-7020-11e9-9f93-2d85b89540f2.png)
