### ISSUE TITLE
font-size for quill WYSIWYG

### ISSUE THREAD

**Issue by Szymon-dziewonski** [directus/app#1590]
# Feature Request
I was looking for custom drop down based on json configuration for quilljs.
This is possible with quilljs itself by using ` [{ 'size': ['small', false, 'large', 'huge'] }],` [quilljs docs](https://quilljs.com/docs/modules/toolbar/), but unfortunately it is cut off after advanced WYSIWYG configuration save. Of course it will create inline code, maybe there might be possibility to create custom dropdown where user could wrap his text with element with class '.small-container' etc.

## What problem does this feature solve?
Allows user to create html with different styling inside editor, not just different heading, bold, underline etc

## How do you think this should be implemented?
Just allow setting from quilljs docs inside advanced WYSIWYG component configuration

## Would you be willing to work on this?
I'm pretty new with directus so I don't think I'm capable person for this task atm, I'll try to help community at the beginning (already found few bugs)

**Comment by benhaynes** [comment]
Hey @Szymon-dziewonski — we are almost done with a new WYSIWYG editor that should be included in the next release. Not sure if this will still be an issue or not...

**Comment by Szymon-dziewonski** [comment]
@benhaynes Thank you for quick response, may I know what editor you talking about, will it be something different than quill ?

**Comment by benhaynes** [comment]
Based on TipTap:

https://github.com/directus/app/pull/1441

**Comment by Szymon-dziewonski** [comment]
Thank you :)

**Comment by dev7ch** [comment]
the new editor now as an options added to wrapping a `p` by a `span`.

this span can hold html attributes `classes` and `styles`, that how you can apply styles and classes in the upcoming ( very soon hopefully) editor

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
