### ISSUE TITLE
Recommendations for File Manager

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1593]
# Feature Request

![image](https://user-images.githubusercontent.com/8030134/57255097-88d2fa00-7085-11e9-9325-7bf392ef3b29.png)

![image](https://user-images.githubusercontent.com/8030134/57255584-cf752400-7086-11e9-97ac-b7755dd05f96.png)

## What problem does this feature solve?
Manage my files intuitively
1. You can create folders manually
2. Uploaded files automatically create folders by date
3. File type filtering
4. Automatic acquisition of image color values
```
data:[
    {
         title:'xxxxxxx',
         photo:{
             data: xxxx,
             colors:['#ffffff','#f3f3f3','#f2f7f8','#f4f2f4','#f8f8f8']
         }
    }
]
```
5. Filtration by Picture Color

**Comment by benhaynes** [comment]
Hey @cdwmhcc — we appreciate all the attention, but please:

1. Browse through our existing ticket first to make sure your request/bug doesn't already exist.
  * Ref: https://github.com/directus/app/issues/228
2. Add all feature requests as _individual_ issues so we can discus/track them separately

I'll give you some time to create tickets for _each_ of these then we'll close this one.

**Comment by cdwmhcc** [comment]
> 嘿@cdwmhcc - 我们感谢所有的关注，但请：
> 
> 1. 首先浏览我们现有的票证，以确保您的请求/错误尚不存在。参考：[＃228](https://github.com/directus/app/issues/228)
> 2. 将所有功能请求添加为_单个_问题，以便我们可以_单独_讨论/跟踪它们
> 
> 我会给你一些时间为这些中的_每一个_创建门票，然后我们将关闭这个。

I'll take some time to sort it out. It takes me some time to write an English question. I'm ready to go to bed.
In the future, I will avoid multiple issues in an issues
