### ISSUE TITLE
Interface: Divider - Required is set when field gets edited

### ISSUE THREAD

**Issue by henrikwirth** [directus/app#1594]
# Bug Report

## Steps to Reproduce

1. Add the Divider Field to a Collection
2. Edit the Divider Field and Save
3. Try to create an item of this Collection
4. See error: `divider: This value should not be blank.` 

Clearly the required flag is saved to 1 (true) after editing the divider. Could this be a problem with all interfaces, that do not show the required field?

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/10786260/57255163-632cfd00-7053-11e9-8d6a-c57fe2049715.png)

## Technical Details

- Device: Desktop
- OS: MacOS 10.14
- Browser: Chrome 73.0.3683.103
- Directus App: next.directus.app

**Comment by fnicastri** [comment]
The divider component has the required prop set to true.
Can't find where this prop come from, any hints?

**Comment by rijkvanzanten** [comment]
When creating a new field, the default value for required is `true`. I'm assuming that the required state of this interface in this instance comes from that default value for `required`

**Comment by benhaynes** [comment]
Could we override this with the `recommended` object in `meta.json`?

**Comment by rijkvanzanten** [comment]
That's exactly how @henrikwirth fixed it in https://github.com/directus/app/pull/1595 😄

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/app/pull/1595
