### ISSUE TITLE
WYSIWYG or Advanced WYSIWYG to have a option to format in Markdown

### ISSUE THREAD

**Issue by chintohere** [directus/app#1597]
# Feature Request

WYSIWYG or Advanced WYSIWYG to have a option to format in Markdown. e.g. CKEditor
https://ckeditor.com/cke4/addon/markdown

## What problem does this feature solve?

Allowing content editor to format content in non-web related technologies so that content can be consumed in other devices as well.

## How do you think this should be implemented?

Should be a feature of the WYSIWYG library we use.

## Would you be willing to work on this?
Happy to

**Comment by benhaynes** [comment]
💯

We have a new wysiwyg in the works thanks to @dev7ch ... it uses TipTap which I believe supports this. Silvan, could we include an interface option for how data is saved (html, markdown, JSON, whatever)?

Ref: https://github.com/directus/app/pull/1441

**Comment by dev7ch** [comment]
currently the new editor saves data as:
- html
or
- json

but there cool thing with tip tap is, that you can just enter markdown and it saved it as **html** or **json**

regarding there full markdown feature there is an open at tip tap repo https://github.com/scrumpy/tiptap/issues/66

Another options would be to open a markdown editor in a new textarea ( as its done with the raw view mode currently)

> that content can be consumed in other devices as we

is this solved with json format?

**Comment by benhaynes** [comment]
Thanks @dev7ch — I've up-voted that TipTap issue (and anyone else interested in MD support should too). In the meantime, JSON seems like a decent agnostic workaround!

**Comment by dev7ch** [comment]
Just some. tought:
- what tip tap is doing very well is to ensure a clean input is gonna be saved in the DB
- currently we also use a 2nd editor (and text area) for the. raw mode
- there is currently a Markdown editor on directs platform available

... to be continued, out of battery, have to save ;)

**Comment by dev7ch** [comment]
Sorry may i dont understand tgis discussion not correctly.

Do you think a wysiwyg editor should also allow saving as markdown or is this a job for a markdown editor?

**Comment by chintohere** [comment]
Thanks for your time everyone. 

I agree with @benhaynes  that formatting in a markdown editor should be minimal. Markdown is best for minimal formatting of the text. In a headless CMS we should not be aiming to support full fledged article writing anyway.

A WYSIWYG editor saving a picked flavour of Markdown should be good enough as the API consumers would be aware of the flavour supported.  

>  and so having a WYSIWYG is not really critical. 

But not having a WYSIWYG for markdown does limit the appeal of the system to content editors who are usual audience the CMS systems are targeted after the rollout.
🤷‍♂

**Comment by benhaynes** [comment]
I'd say it'd be a nice perk to have our main WYSIWYG editor save in markdown, but it's just as good to have a dedicated markdown interface (which we have, but it's a bit basic). I'd say we should plan on shifting this conversation to finding/creating a good dedicated editor for markdown.

Let's aggregate any potential libraries here, and when we have a bit more time we'll get this built (unless someone wants to donate their time to a PR!). 😄

**Comment by chintohere** [comment]
Agree. @benhaynes . We will look into the available markdown editors and will comeback with a PR if we have a good fit.

**Comment by benhaynes** [comment]
I've taken some time to clean up the `markdown` interface by adding a side-by-side and tabbed preview mode. I think this is the appropriate direction, unless someone has thoughts around a _new_ wysiwyg editor library that (cleanly) outputs markdown.

Ref: https://github.com/directus/app/pull/1611

Since we're moving to TipTap for our main (Core) wysiwyg editor, and it doesn't (yet) support markdown... I'll close this. Until we have a really good option to include in Core, let's focus on the dedicated markdown interface.

**Comment by dev7ch** [comment]
Good, actually i found a workaround by useing showdown.js in the new editor.
To save the output in Markdown and also load the Markdown from Database and transform back to html.

I am unsure yet about performance and the "really good".

A solution for tables could be not to transform to markdown (it wont be seen by the user, only 8n raw view)

**Comment by dev7ch** [comment]
That way you could use the wyswig toolbar to create markdown

**Comment by chintohere** [comment]
Great @dev7ch . You could also give us an option to disable tables in the toolbar to keep it simple. Are the new changes coming in the next release?

**Comment by dev7ch** [comment]
all toolbar options are going to be selectable and sortable.

but I think it would make sense to threat the md saving/reading via wyswig editor as a separated feature instead of implementing it quickly to the first release of the new editor based on the great, clean input via the awesome Tip Tap.

I created a branch `wysiwyg-md` its in early stage 
https://github.com/dev7ch/app/blob/wysiwyg-md/src/interfaces/wysiwyg-full/input.vue

About the release I am unsure, I hope the editor is going to be reviewed und merged soon as possible.

**Comment by benhaynes** [comment]
@dev7ch — would you say that the WYSIWYG editor is ready for a final review/merge? We _might_ be releasing EOD today... but it depends on how quickly we can finish some other client work.

If you think that the interface is good to go we might have time to review it... otherwise I'd say we can check it out for the next release.

Also, since you have a possible solution for wysiwyg with markdown, I'll re-open this ticket!

**Comment by dev7ch** [comment]
I would say yes but would be happy if this https://github.com/directus/app/pull/1584 could be reviewed/merged before, due the sorting of the editor toolbar is quite important imo.

After this is in master I think its just a quick double check and finializing (about 2 - 3 hour for me).

I would suggest EOD today if possible https://github.com/directus/app/pull/1584 and editor next release.

**Comment by benhaynes** [comment]
Sounds good! I don't think we're going to have any time today, and then Rijk is off for the rest of the week... but after that he's full-time!

We'll see what we can do, but I'm not even sure we'll be doing the release today.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dev7ch** [comment]
@chintohere the MD format options (including saving and converting) is included to the new editor and probably will be available in the first release

**Comment by dev7ch** [comment]
in the new editor PR there is now an option to save as Markdown String in DB.

your are also able to use the editor toolbar to input Markdown (bidirectional Markdown/HTML) but some features like table, images with css classes and are not working (but its easy for admins to trim this by options for enduser)

The raw mode shows and let edit you the markdown.

How ever, the clear list from @philippkuehn is correct (100% integration = infinite pain ;)) and also its a bit feature overkill imo.

So i would consider this as experimental.

@philippkuehn did you also tried or had a look at showdown.js as you looked into a tiptap MD ectension?

**Comment by philippkuehn** [comment]
@dev7ch In my tests for tiptap I've used `markdown-it` because it was used in `prosemirror-markdown`. Personally, I haven't tested showdown.js yet but have had good experiences with remark (It's part of [unified](https://unified.js.org/)).

**Comment by rijkvanzanten** [comment]
Remark and the unified ecosystem are awesome ✨, h/t to @wooorm

**Comment by wooorm** [comment]
Hah, thanks @rijkvanzanten!

I’m just brought into this discussion and I glossed over it, but yeah! unified does have a bunch of things to transform to markdown that may be of interest. E.g., [hast-util-to-mdast](https://github.com/syntax-tree/hast-util-to-mdast), if you have an HTML string. Or even [hast-util-from-dom](https://github.com/syntax-tree/hast-util-from-dom) first if you have a DOM tree.

Anyway, more info on our website, https://unified.js.org, that @philippkuehn linked!

Side P.S. contentful started doing something with rich text based on mdast (unified’s markdown syntax tree): https://github.com/contentful/rich-text. And John (author of MDX) is working on blocks: https://github.com/blocks/blocks
