### ISSUE TITLE
Files Interface Bug

### ISSUE THREAD

**Issue by benydc** [directus/app#1599]
# Bug Report

## Steps to Reproduce

1. Create a collection
2. Add files interface in that collection and auto-generate junction collection
3. Add 2 existing files using selection and save
4. Add another existing file using selection and save
5. Previouse files/junctions have been duplicated

## Expected Behavior
Create junction only for the newly selected file and not for all files

## Actual Behavior
Creates junction for all selected files again and again

## Other Context & Screenshots

video:
https://streamable.com/t3ytg

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.4
- Web Server: Official Docker Image
- PHP Version: Official Docker Image
- Database: Official Docker Image
- Install Method: Official Docker Image

**Comment by Kinzi** [comment]
duplicate https://github.com/directus/app/issues/1573
