### ISSUE TITLE
Add "Save and Leave" button to "You have unsaved changes" message.

### ISSUE THREAD

**Issue by Lapsus** [directus/app#1600]
# Feature Request
The "you have unsaved changes" message has a "discard changes" and a "keep editing" button. But if you want to save and leave you can not. You have to "keep editing" and "save" and then leave. Which is confusing and annoying for the user.

## What problem does this feature solve?
You currently have to decide to "discard" or "stay". If you stay you have to save and switch to another collection again. which is a duplication of the click that produced the "unsaved changes" message, which is sufficent if you left by accident. But if you wanted to leave and just forgot to save it "feels" annoying.

## How do you think this should be implemented?
I think a third button "save and leave" is needed. This leaved "discard changes", "stay" (you left accidently), and "save and leave" (oh, yes save please and then take me to ...) 

## Would you be willing to work on this?
Unfortunately i dont know vue and dont have time to learn it at the moment.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
