### ISSUE TITLE
Save button as part of the form

### ISSUE THREAD

**Issue by Lapsus** [directus/app#1601]
# Feature Request
User that dont with little web skills usually expect a forms action button at the bottom of a form. This is a web practice for centuries now. Of course modern applications or responsive and mobile forms have the action buttons fixed in the header and so does the App.

## What problem does this feature solve?
Enables lesser skilled user to use the App more easily and more intuitively.

## How do you think this should be implemented?
Ben suggested adding a interface `Button` That could be mapped to an event/action. That way one could add a "submit" Button at the bottom of the form.

## Would you be willing to work on this?
Unfortunately i dont know vue and dont have time to learn it at the moment.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
