### ISSUE TITLE
"Link" Interface

### ISSUE THREAD

**Issue by Lapsus** [directus/app#1603]
# Feature Request
I would like an interface that can be added to a collection that produces a link or button to open the item in another browser window with a url.

On the interface options you define the url prefix for example "https://somedomain.com/preview/?{{id}}". {{id}} is replaced with the items id so that the link can be used as preview url.

## What problem does this feature solve?
Usually you manage data in the app that is used somewhere else. But how do you create a preview link? You could use a slug or other the id to create a preview link.

## How do you think this should be implemented?
This could be a core interface maybe?

## Would you be willing to work on this?
Unfortunately i dont know vue and dont have time to learn it at the moment.

**Comment by benhaynes** [comment]
;)

https://github.com/directus/app/tree/master/src/interfaces/preview
