### ISSUE TITLE
Adding storybook.js for isolated component testing

### ISSUE THREAD

**Issue by henrikwirth** [directus/app#1605]
# Feature Request

### What is storybook?
> Storybook is a user interface development environment and playground for UI components. The tool enables developers to create components independently and showcase components interactively in an isolated development environment.

![image](https://user-images.githubusercontent.com/10786260/57470378-f9963400-7288-11e9-97a0-2a3764a0dd91.png)

## What problem does this feature solve?
It makes it possible to test components, interfaces, layouts etc. isolated from other content. Also it can serve as a showcase of what components there are and how they work. Also, how they might look like in different conditions (different background, with or without main.scss ...) I think there is many ways, how you could use it. It would be up to our creativity.

There is also plenty of addons, that tackle different problems. Check it our here: https://storybook.js.org/addons/

## How do you think this should be implemented?
I already setup a working implementation on a branch which I will link through a pull-request. The main task will be to decide, what components and layouts should be showcased and under what conditions should they be implemented.

It would be great to somehow have a pipeline, that builds the static version and serves it somewhere. Could be also interesting to introduce some versioning to it and therefore see the development of things.

I would love to leave the rest for discussion :)

## Would you be willing to work on this?
Indeed

**Comment by benhaynes** [comment]
Interesting! Any idea how well our components would work within a platform like this @rijkvanzanten?

**Comment by henrikwirth** [comment]
@benhaynes feel free to check out my example. Not perfect, but i guess it shows, that it can be used ...
just `npm i` and `npm run storybook`

https://github.com/henrikwirth/app/tree/feature/introduce-storybook

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
