### ISSUE TITLE
Creating links to internal content within WYSIWYG

### ISSUE THREAD

**Issue by herrbomm** [directus/app#1607]
# Feature Request
Creating links to internal content and files within WYSIWYG.

## What problem does this feature solve?
Often content-creators face the problem to link to interal content (collection-items, singletons, files as links ...) within the WYSIWYG. If those are absolute we will run into problems when i.e. switching to another the domain. So at least it needs to be relative. 

Also the link should be aware of its type (collection, singleton or file) and automatically stay in the language the user is currently accessing the page.

## How do you think this should be implemented?
I guess just by having an icon in the toolbar of the WYSIWYG would do the trick. Similar to the solution in cockpit CMS
<img width="981" alt="Bildschirmfoto 2019-05-10 um 08 24 23" src="https://user-images.githubusercontent.com/50315804/57507426-0d7c7d00-72ff-11e9-8ffc-f4a0c68ceb80.png">

=> Filter by collection type and then having the same filter-mechanism as used in the lists. Language should be taken from the current language the user is accessing the page. 

## Would you be willing to work on this?
Sorry, that im not good enough at coding to implement this 😔

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
