### ISSUE TITLE
Creating groups for the links on the left - is it possible?

### ISSUE THREAD

**Issue by herrbomm** [directus/app#1608]
Hi there, 

the title says it all: Is it possible to create "groups" of collections on the left so we can create "widget-", "content-", "page-"groups or whatever? Or maybe customize all links shown on the left by drag and drop plus creating groups of links and name them?

This would help to organize the backend for non-technical customers. 

Regards,
Fab

**Comment by henrikwirth** [comment]
Similar to this? https://github.com/directus/app/issues/1575

**Comment by herrbomm** [comment]
> Similar to this? #1575

Kinda yes! Haven't seen that. 
But it would also be helpful having the possibility to create headlines for the groups.

**Comment by henrikwirth** [comment]
I would suggest closing this issue here and help to improve the other.

**Comment by herrbomm** [comment]
Yeah, i already posted my idea over there.
