### ISSUE TITLE
Can't save time value

### ISSUE THREAD

**Issue by amo42** [directus/app#1612]
I'm using the latests docker images from docker hub for API and App. And try to save/store/update a value from the Web UI

I've got a simple collection with a "time" field. Saving the value "10:00:00" results in the error

`my_time: This value is not a valid time.`

Setting the same field to "10:00:01" just works perfectly. I'm not sure if it's app oder api related.  So it's may related to https://github.com/directus/api/issues/782

**Comment by Nitwel** [comment]
Could you tell which version of directus you are using? You can see this when overing over `Powered by Directus ` text at the bottom of your login page.

Also are there some other time related fields in the collection?

**Comment by rijkvanzanten** [comment]
This is working fine on my end. 

> I'm using the latests docker images from docker hub for API and App

The docker images use an older version of the app, so I'm assuming this was fixed in the meantime.
