### ISSUE TITLE
Canno unset M2O relationship

### ISSUE THREAD

**Issue by jedikcz** [directus/app#1613]
Hi, I've found out that it's impossible to unset once set M2O field (which is not required) in the app.

Basically:
1. Create two collections - `menu_item` and `page`.
2. In `menu_item`, add not required M2O field linked to `page` collection.
3. Create new `page` .
4. Create new `menu_item` and set `page` field with newly created page from previous step.
5. Try to edit your new `menu_item` and see that you are now unable to unset the `page` field. The placeholder option is disabled (See attachement).

It is possible to do it via API call `PATCH` `/items/_menu_item/4` `{page: null}` but not via app.

![b1](https://user-images.githubusercontent.com/45359017/57609291-dc09e880-756e-11e9-80e8-4a3a0b1f1edf.png)

**Comment by theharshin** [comment]
Hey @jedikcz, now you can reset values of the all fields by clicking on little arrow beside label.
![image](https://user-images.githubusercontent.com/7118937/62795531-98366900-baf4-11e9-9578-1e96632648d0.png)

I'm closing this ticket for now. You can let me know if this doesn't work for you.

**Comment by rijkvanzanten** [comment]
I'm considering this a feature request to add that to the M2O interface seeing that the original problem can be dealt with with the solution provided above
