### ISSUE TITLE
Labels not clickable in field update modal

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1618]
I'm adding this as a bug because there is a hover event on the label...

Clicking on these labels (field update modal) should toggle the toggle...

![Screen Shot 2019-05-13 at 1 20 32 PM](https://user-images.githubusercontent.com/522079/57641066-07e29980-7582-11e9-9a78-a92eea875ca8.png)

**Comment by nstCactus** [comment]
I wanted to fix this but it seems to be a little more complex than what it seems.

My idea was to listen to the `@focus` event of the input element. This works fine for mouse-based interaction but it breaks keyboard nav: when you tab to the field, it toggles it straight away.

We can mitigate this by setting a `tabindex="-1"` attribute on the label but we'd have to do this everywhere the `v-toggle` component is used as the `<label>` isn't part of the component.

If you have any ideas on how to best solve this, I can try implementing it.

**Comment by rijkvanzanten** [comment]
@nstCactus I think it might be because the label isn't connected to the underlying checkbox properly. Maybe the ID in the checkbox is different from the `for` in the label of the value?

**Comment by rijkvanzanten** [comment]
The default ID for those two is set to `""`, maybe they're not being passed an ID which in turn doesn't "connect" the label to the checkbox?

**Comment by nstCactus** [comment]
Got it!

`v-model="value"` should be used instead of the combination of `@change` & `:checked="value"`.

The reason is that the `checked` attribute only sets the initial value of the checkbox. `v-model` on the other hand manages the `<input>` element state both initial & at runtime:

> v-model internally uses different properties and emits different events for different input elements:
>  * checkboxes and radiobuttons use checked property and change event;
> …

https://vuejs.org/v2/guide/forms.html#Checkbox

I'll make a PR in the next hours.
