### ISSUE TITLE
"Sort" should be hidden on detail and browse

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1619]
When you create a new collection it has the option to add a `sort` field. When this is selected, the field should be "Hidden on Detail" and "Hidden on Browse" by default since it's mostly only seen as drag handles.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
I submitted a PR for this, which is working. However the App is not honoring the `hidden on browse` flag... so I'll open a bug report.
