### ISSUE TITLE
Add support for the Jalali calendar

### ISSUE THREAD

**Issue by sadibak** [directus/app#1621]
Jalali calendar
https://en.m.wikipedia.org/wiki/Jalali_calendar

**Comment by rijkvanzanten** [comment]
Jalali calendar what?

Implement it as a layout? Support it in datetime? Could you provide some more information?

**Comment by sadibak** [comment]
thanks for your respond.

see this link
https://github.com/morilog/jalali/blob/master/README.md

**Comment by sadibak** [comment]
you develop button in setting for choose calendar like choose language

**Comment by benhaynes** [comment]
Thanks @sadibak — I'll leave this open for a bit to see if we get some 👍 from the community (we only add things into core if it's used by 80%+ of our community). This could always be added as an extension though!

We'll probably circle back and look into this when we get into RTL later this year.

**Comment by llmuculusll** [comment]
That would be great if you add this feature. +1

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
