### ISSUE TITLE
Files interface fails after file deletion

### ISSUE THREAD

**Issue by UnderscoreDesign** [directus/app#1625]
# Bug Report

## Steps to Reproduce

1. Go to admin settings/collections and fields.
2. Select a collection.
3. Click Add Field button.
4. Select and setup Files interface.
5. On collection item page add new files via Files interface.
6. Go to media library and delete one of the files that was just added.
7. Go back to collection item page where files interface no longer functions.

TypeError: null is not an object (evaluating 'i[t.relatedPrimaryKeyField.field]')

## Expected Behavior
Files deleted via media library but attached to an items page should simply not show up on the collection item's page. Or a broken link appears in its place. Or a warning prior to deletion that the file being deleted is in use. At minimum, files interface should continue to function.

## Actual Behavior
Files interface stops functioning for that field with console error TypeError: null is not an object (evaluating 'i[t.relatedPrimaryKeyField.field]').

## Other Context & Screenshots
![Screen Shot 2019-05-13 at 2 54 20 PM](https://user-images.githubusercontent.com/5007586/57651220-55ff9900-7592-11e9-984b-54d8bfa48530.png)

## Technical Details

- Device: Mac mini, MacBook Pro
- OS: MacOS 10.14.4
- Apache 2.4.29
- MySQL Server 5.7.23
- PHP 7.2

**Comment by rijkvanzanten** [comment]
Add the `fields=*.*` parameter to fetch all values 2 levels deep.

**Comment by UnderscoreDesign** [comment]
Thanks! Is there a way to simply add an array of file ids into a first level field? Why do I need the join tables?

**Comment by rijkvanzanten** [comment]
The files interface is a many to many interface. The root level doesn't contain any values. You can retrieve the IDs of the files by using `fields=gallery.*` or fetch the image objects for each with `fields=gallery.*.*`

**Comment by benhaynes** [comment]
I actually don't mind the idea of a CSV files interface. @rijkvanzanten thoughts?

**Comment by rijkvanzanten** [comment]
We won't be able to populate the records in the api though, so the fields parameter won't work for that one. I think that will cause a lot of confusion

**Comment by benhaynes** [comment]
It seems like a fairly common use-case, so I'd say we should look into _how_ it might be possible. Not sure how we would do this, but we could have the ability to send additional data with the form save, send things async before save, add a new relational CSV field type, or something else I'm not thinking of.

Regardless, I've been in situations where legacy databases I inherited used a CSV of FKs... so it's not crazy to think of real-world examples.

**Comment by UnderscoreDesign** [comment]
@rijkvanzanten The 'file' interface saves the file id to the first-level field and works with the fields parameter. Seems less confusing to me to have the 'files' interface work the same way with a csv list of file ids. And a bonus, the files get request  /_/files/1,2,3,4 would be a breeze.

**Comment by rijkvanzanten** [comment]
That's because the `file` interface is a many to one to `directus_files`, a `files` interface is a one-to-many to a junction table, followed by a many-to-one to `directus_files`. A CSV can't be used relationally yet, as it's holding multiple primary keys which doesn't join in sql. @benhaynes if we want to make this possible using just a CSV, we should add a many-to-many CSV type that will save the primary keys to a CSV and use that.

**Comment by benhaynes** [comment]
Exactly. Let's discuss this [over here](https://github.com/directus/api/issues/954) and then we can circle back once that's implemented in the API.

**Comment by rijkvanzanten** [comment]
This is fixed in https://github.com/directus/app/pull/1881
