### ISSUE TITLE
Problems with thumbnails in jpg

### ISSUE THREAD

**Issue by anderson-scherer** [directus/app#1628]
Good night. I have a peculiar problem. When I upload an image of the jpg type to the server, the image is loaded, but the thumbnails, in this case three (200x200, 480x480 and 600x600) are not generated, however when the upload is of a PNG image, the image is uploaded. process happens normally. The strangest of all does not generate registry error on the server. Could you help me with this question?

**Comment by shealavington** [comment]
Do you have the `GD` and `IMAGICK` PHP extensions?

**Comment by rijkvanzanten** [comment]
Thumbnails aren't generated on upload, there generated the first time the image is requested

**Comment by benhaynes** [comment]
Hey @anderson-scherer — we can re-open this if you have time to provide a bit more info. Or just let us know if things worked out! :)

**Comment by anderson-scherer** [comment]
@benhaynes  Server error. I made some adjustments that made the thumbnails were created. But I could not identify the problem, the server did not register an event, before publishing the final version I will do a review and notice here if the problem votes happen.

**Comment by anderson-scherer** [comment]
> Do you have the `GD` and `IMAGICK` PHP extensions?

Yes, it is installed.

**Comment by shealavington** [comment]
Could you reiterate what the issue is? 
Have you checked the logs?
Do you get any browser errors?

...
