### ISSUE TITLE
Clicking "Unmanage" shows the spinner—before the button is clicked.

### ISSUE THREAD

**Issue by shealavington** [directus/app#1632]
**This one's my bad—I'm terribly sorry!** :sob: ( I will fix if / when I'm free )

When you click `Unmanage` on a collection, I added a spinner to the modal's button, so that it shows an action is happening (prevents users repeatedly click it if it's slow).

After the modal closes, the state of the spinner doesn't reset, therefore, if you proceed to `Unmanage` a second collection... Without clicking anything once the modal comes up, you see the spinner by default where it was never reset from the previous action. (image)

This fix should be as simple as resetting the state of the loader on the callback of the item being unmanaged/failing, therefore, resetting the loader for the next unmanaged collection.

![Selection_090](https://user-images.githubusercontent.com/16869302/57792250-71a3a480-7736-11e9-926a-3ed3bc02ce90.png)

**Comment by benhaynes** [comment]
Haha, self-reporting... no worries, this is far from our worst bug! 😄
