### ISSUE TITLE
Settings > Manage All (Collections / Fields)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1634]
# Feature Request

Adding a button to the `Settings > Collections & Fields` that allows you to "manage" all Collections and/or Fields in one go. As of now, you need to click manage for each collection/field... even for a normal-sized site that could be _hundreds_ of individual clicks that process asynchronously. It's tedious.

## What problem does this feature solve?

If you are installing Directus on top of an existing database and it has a handful of tables, each with a bunch of fields, this will make things _much_ easier.

## How do you think this should be implemented?

* A "Manage All Collections" button on `Settings > Collections & Fields`
* A "Manage All Fields" button on `Settings > Collections & Fields > [Collection]`

## Would you be willing to work on this?

I can mock up a design.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
