### ISSUE TITLE
Incorrect z-index on scrolling items on O2M field modal

### ISSUE THREAD

**Issue by cesasol** [directus/app#1645]
When scrolling on the O2M modal field the listing and the header goes over the search box, I can tell this is a z-index issue but I have no idea where might be located.

Using latest v7.3.1of app and installed by cloning the directus repository
Browser: Firefox nightly (also on firefox 67)

![Screenshot_20190520_203800](https://user-images.githubusercontent.com/3846473/58062334-92596900-7b3f-11e9-8e4f-a681e375595b.jpg)

**Comment by shealavington** [comment]
_(Note: this may be browser specific as I don't see the issue on chrome)_ 

This seems like a `position: sticky` issue as that top bar shouldn't move.  A good place to start looking is probably the following files:
```
/src/interfaces/one-to-many/input.vue
/src/interfaces/many-to-one/input.vue
/src/interfaces/many-to-many/input.vue
```

**Comment by benhaynes** [comment]
Fixed! There is still a weird issue with the search and table header when you scroll to a certain point... 

@rijkvanzanten @shealavington — any idea what causes that?

**Comment by shealavington** [comment]
`.modal-container .body[data-v-88846b60]` will need `overflow: hidden;`, currently set to auto. :)

**Comment by rijkvanzanten** [comment]
We can't disable scrolling for the modal completely though, that would break the other uses of it 🤔

**Comment by shealavington** [comment]
Indeed. Is there a way we can use scoped CSS from a parent component (o2m/m2o/m2m) to have it trickle into the child component (modal), or would that be bad practice?

**Comment by rijkvanzanten** [comment]
That kinda smells.. 💩

**Comment by benhaynes** [comment]
Correct me if I'm wrong, but the new dedicated item select modal @rijkvanzanten is working on now should resolve this.
