### ISSUE TITLE
Ongoing Optimization Discussion

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1648]
This is not a single request, but instead this ticket will be used to discuss general advancements of the App codebase — specifically for our upcoming/ongoing refactor.

### Combine All Browse/Listing Pages (ref: https://github.com/directus/app/issues/636)
Right now we have dedicated components for File Library, Activity, etc. Ideally all of our internal pages should use the standard approach and take advantage of the full power of our Layouts.

### Optimize Layouts for Modals
As of now, layouts do not fit/work well within modals. While it would be easier to make a general "select items" modal, long-term we want to re-use all layouts for selecting items in a modal. We'll want to make sure that each layout is responsive for the smaller area, that selecting items works consistently across layouts, and that things like filtering and reordering are possible.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
> Right now we have dedicated components for File Library, Activity, etc. Ideally all of our internal pages should use the standard approach and take advantage of the full power of our Layouts.

The activity page isn't a separate component at the moment. The file library is a 80% duplicate of the regular browse page, with some edits that are custom for files (most notably the new item modal flow).

Merging everything into the same component will cause a lot of confusing exception. I think having separate small wrapper for the system pages (/users, /activity, /files) is easier to maintain in the long run (they would still use the regular `layout`s though)

**Comment by benhaynes** [comment]
My main concern is being able to re-use all our core (and any custom) layouts within modals and for system collections. So that works!
