### ISSUE TITLE
Collection & field translation does not work as expected

### ISSUE THREAD

**Issue by christianrr** [directus/app#1650]
### Steps to Reproduce
Added translations in directus_collections.translation and directus_fields.translation using phpMyAdmin

### Expected Behavior
Translated collection and field names should show up in the interface when using a locale in the user's profile

### Actual Behavior
Collection name gets translated (most of the time ,sometimes switches back to default name - not reproducable), however field names always show the default column name and never get translated

**Comment by benhaynes** [comment]
This should be a Feature Request — but since we already have those columns in the database I feel like it makes sense to call this a Bug. @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
No I don't agree. We also have a column for groups, and we have a collection for folders, both of which haven't been (officially) implemented yet.

Translations of fields is an upcoming feature with an open request, making this a duplicate.

**Comment by rijkvanzanten** [comment]
Ref #422
