### ISSUE TITLE
Scrolled when navigating to Item Detail

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1651]
When I go from Item Browse to Item Detail I am often (always?) started scrolled halfway down the page. Not sure why, but we should always reset the scroll to the top of the page when navigating.

**Comment by shealavington** [comment]
Oddly I have noticed this before too.

**Comment by rijkvanzanten** [comment]
> Oddly I have noticed this before too.

Yet you chose to hold your peace instead of speaking out ಠ_ಠ :*

**Comment by benhaynes** [comment]
Hmm, still happening for me

**Comment by rijkvanzanten** [comment]
Pt2 closed in https://github.com/directus/app/pull/1662
