### ISSUE TITLE
Password not encrypted after changing it

### ISSUE THREAD

**Issue by Htbaa** [directus/app#1656]
Hi,

I just installed Directus App and API. Added a new project, deployed schema.sql to the new database. After changing the password of the default admin user I can no longer login. Inspecting the database the password is saved unencrypted, causing login to fail.

This was on Directus 7.4.0.

**Comment by rijkvanzanten** [comment]
Hoi @Htbaa! What kind of server stack is this on? Does it meet all the requirements of Directus?

This is obviously not supposed to happen (and it doesn't on my end)

**Comment by Htbaa** [comment]
Hoi @rijkvanzanten, ook Nederlander?

Back to English :-). I'm running a Ubuntu 18.04 server with stock packages (PHP 7.2, MySQL 5.7) and all required PHP extensions have been installed and activated.

**Comment by Htbaa** [comment]
I'm seeing replies from Stephen Thirlwall on this issue appear in my inbox, but they're not added to the conversation here?

Anyway, to recap my steps:

- I cloned the directus repository (master).
- Ran the installer from /admin.
- Used the script in the bin directory to create a new configuration for another project.
- Deployed the schema.sql (mysql mydb < schema.sql).
- Logged into the app, went to profile and change password.
- Logged out. Tried to login again but it was refused. Inspected database and there was my password stored as plaintext.

**Comment by rijkvanzanten** [comment]
Ja!

I've transfered this issue to the API repo, but apparently GitHub is having some trouble moving over the comments.

Do you mind copy / pasting over these comments manually to https://github.com/directus/api/issues/970?

**Comment by 7jp** [comment]
I had the same issue - password is not encrypted in db after editing user profile. Updating database from "Admin Settings" menu helps.

**Comment by nassan** [comment]
This is still happening as of `190627A`, commit hash `56404f6a68bd9b1cfb76829b1428b3a9d5ed64a9`.

The user created by the initial app installation is indeed properly hashed in the mysql db. However manual db inspection reveals that the other users, which were created via the admin interface are not hashed. And they result in a generic `500` error when using them to try to login to the admin.

**Comment by rijkvanzanten** [comment]
Is your database up to date as per @7jp's recommendation @nassan?

**Comment by nassan** [comment]
@rijkvanzanten It is up to date. I ran that "database update" from the admin. Did not appear to change anything.
