### ISSUE TITLE
Rework v-field-setup

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1675]
As you already pointed out some time, the v-field-setup needs to be rethought any possibly redesigned and thats what this issue should be for.

I myself thought that maybe we can split the current v-field setup into much smaller peaces because it makes managin them individually much easier and as far as I heard you want to define the group of an interface in the config which means more programming/rewriting anyways.

To sepeate these I think the best way is to create a component for each page so we would have 3 components in the end. 

# New Components

## v-interfaces 
The first component would give a list of each interface and when an interface is selected it would emit the name of the selected interface. This would be super nice because this would allow us to use the first page also in the "interfaces" interface for example.

![Screenshot_2019-05-24 Settings Editing Item Timeline(3)](https://user-images.githubusercontent.com/22577866/58316496-f7e57800-7e13-11e9-855f-52eaf0157cc8.png)

## v-schema
The second component would give this static view of fields and maybe would return a json object with all the data or also possible returns the changed value for each field like the v-form does at the moment.

![Screenshot_2019-05-24 Settings Editing Item Timeline(1)](https://user-images.githubusercontent.com/22577866/58316528-05026700-7e14-11e9-83a7-2221487cd7f3.png)

## v-options
The last component would mostly be simular to the v-form anyways and would just manage the dataflow between the technical side of the old v-field-setup and the v-form.

![Screenshot_2019-05-24 Settings Editing Item Timeline(2)](https://user-images.githubusercontent.com/22577866/58316751-8e199e00-7e14-11e9-8a38-53a0730edc9e.png)

<hr>

It would also be possible to have the last 2 interfaces as one because these would most likely be just 2 forms which manage the changed data from the interfaces but dont need much new to programm to function.

What do you think about these changes?
I hope we can come up with a design that is the most scaleable and usable for directus. ^^

And yes, I definetly would like to help rewrite this component. 👍

**Comment by rijkvanzanten** [comment]
I absolutely agree.

Don't forget some interfaces also have the 'relationship' tab 🙂 

These tabs are unique to the field setup flow though, so we might want to structure them in a nested folder:

```
field-setup
  field-setup.vue
  options.vue
  scheme.vue
  interfaces.vue
  relationship.vue
```

**Comment by benhaynes** [comment]
Love it. We definitely needs to start breaking up the large behemoth components and cleaning up as we go.

One thing that will happen is removing the `Field Width` from Interface Options tab:
* Makes that tab ONLY about the interface options
* Allows you to edit width even when there are no options (right now you can't)
* Would have a dedicated `Form Layout` interface that is more visual for field width, sort, and gaps

As for design, how do we see things changing or becoming more intuitive/simple? I'd love to mock a new modal up, but want to hear feedback on the current design first.

**Comment by rijkvanzanten** [comment]
We should re-imagine the list of interfaces to be more concise. We have quite a long list of interfaces now, making the big boxes a bit hard to use. Once all the interfaces have been moved into that live storybook, we could add links out to the centralized docs for a preview.

The schema and relationship tab work pretty well I think.

The interface options could be improved by putting some fields side by side. This should be done by adding `width` options to the options in the meta.json files.

**Comment by benhaynes** [comment]
We can remove the second line of text below the interface tiles. Switching to a list view will make things much longer, so I still think the tiles is most efficient.

Having the search filter (with initial focus) that instantly reduces the list will help a lot. People will type 2-3 letters of what they are looking for and then click.

Also, making the card layout navigable with `tab` and arrow keys would help a lot! :)

Right now these are ordered by "popularity", but maybe alphabetical is better for searching/scanning?

**Comment by Nitwel** [comment]
I'm also definetly into helping out updating all the components and interfaces and adding proper documentation to all of these. 👍

**Comment by rijkvanzanten** [comment]
What do we think about the interfaces being grouped? It helps when you're browsing, but hinders if you already know what interface you're looking for..

**Comment by rijkvanzanten** [comment]
I do think the interfaces should be alphabetically sorted within each group

**Comment by Nitwel** [comment]
Yep, I also think the best way is to keep these interfaces grouped and add a search function which then lists all items in a list and not in these boxes anymore.

**Comment by benhaynes** [comment]
I'm 50/50 on the groups. It kinda helps, but things would be a lot more simple without them. Not sure how much they are used (or would be used once we have search).

Removing the grouping saves a lot of space making it easier to browse the list. But there are also duplicates in there that would make things shorter too.

I wonder how important/obvious it is to have something like `slider` within a `numeric` group.

Alternatively, we could use the gray text below the title for the group and remove the accordions.

**Comment by Nitwel** [comment]
And what about aliases which will be added to each meta.json when we define the group in there too?
This would help making a good search.

**Comment by rijkvanzanten** [comment]
Like key words, that would be helpful I suppose

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
