### ISSUE TITLE
Config file in cache after change

### ISSUE THREAD

**Issue by miloshavlicek** [directus/app#1685]
**Steps to reproduce:**
A)
1. Go to sign in page
2. Edit configuration config.js file and add/edit e.g. new API endpoint, save the file on a server.
3. Go to sign in page again
4. Settings are unchanged because of browser caches xxx.xxx/config.js file

B) The same issue occurs when you use a CDN (e.g. Cloudflare). Config file is cached on the CDN.

**Workaround:**
A) User have to click CTRL + F5
B) Admin has to invalidate file on CDN and user have to click CTRL + F5.

**Environment:**
Browser: Google Chrome 75.0.3770.38 64-bit
Directus version: 7.0.18

**Comment by rijkvanzanten** [comment]
Tricky one. The only real fix would be to invalide the configuration file on every load, as the app has no way to know if it changed or not. That would be a shame as the configuration file would rarely ever change (if ever) in regular use.. 

Any thoughts on that @miloshavlicek?

**Comment by miloshavlicek** [comment]
I agree with you @rijkvanzanten that loading the script on each load is not the right way, however for a regular user it is not comfortable and common to click ctrl + f5 if something doesn't work.

Maybe implementing PWA service worker could be the way to invalidate updated config file. I'll try to think about it a little.

**Comment by rijkvanzanten** [comment]
That would still invalidate the file only on second load though 🤔 

1. app load:
2. app uses cached config
3. service worker downloads new config / invalidates old
4. app is still on old config

The user will only have the invalided config on reload..

**Comment by miloshavlicek** [comment]
It's a little bit easier for a regular user than need to hard reload (with cache clear).

**Comment by samvasko** [comment]
Asset fingerprinting could work well but some build step would have to be involved...


Other than that, having a sensible expire time would probably be a good first step.

**Comment by rijkvanzanten** [comment]
I'd rather prevent hack a buildstep for the config file as it is expected to be edited by the user in any environment of all development skill levels.

The expire time would be set on the server right? 🤔

**Comment by samvasko** [comment]
Yes, there is also ETag. But the request for it would likely be as fast as a request for the actual file.

**Comment by rijkvanzanten** [comment]
I don't think this is something we can fix from our end. Adding in a cache buster in the build step won't help the OP, as it will only change the has whenever a new version of Directus is released, and not when the config file is updated. The cache headers are being controlled by whatever webserver you use to serve the directus app.

We can continue the discussion here if anyone has a bright idea to solve the original problem
