### ISSUE TITLE
Collections grouping

### ISSUE THREAD

**Issue by miloshavlicek** [directus/app#1686]
# Feature Request

## What problem does this feature solve?
In case, the number of collections increases to tens, the list in the left menu becomes more and more confusing.

## How do you think this should be implemented?
It could be nice to be able to group related collections and create a submenu for these grouped collections.
E.g. Career > Jobs, Jobseekers, Branches..., Eshop > Items, Categories, Carts..., Events > Events, Tickets, Event categories..., Users...

## Would you be willing to work on this?
I'm not sure if I am able to implement it completely, but I can help.

**Comment by rijkvanzanten** [comment]
Heya! Have you tried out the navy override option for roles? You can choose what to display in the nav sidebar and how to display it. You can group the collections however you want too. (Or hide some of them completely if that's applicable to your setup)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
Since the override offers more features than the "normal" one, perhaps we should offer a way to _globally_ configure the navbar too. That way you can customize it but not have to keep each group up to date.
