### ISSUE TITLE
Save as Copy: error if there is a mandatory Many-to-one field

### ISSUE THREAD

**Issue by ninjabachelor** [directus/app#1695]
# Bug Report

## Steps to Reproduce

1. Create a collection with a Many-to-one required field.
2. Try to "Save as copy" a content of this collection.

## Expected Behavior
Content is copied to new object.

## Actual Behavior
The copy is blocked, even if the field has a correct value. If the field is set as not mandatory, save as copy is working fine.

## Other Context & Screenshots
![save-as-copy](https://user-images.githubusercontent.com/3736582/58648197-7a38d500-8309-11e9-9864-552763d7b056.png)

## Technical Details

- Device: any
- OS: any
- Browser: any
- Directus App: 7.4.0
- Directus API: 2.1.0
- Install Method: download release `190521A` of Directus

**Comment by bjgajjar** [comment]
@rijkvanzanten 

Currently, we delete the fields that shouldn't / can't be duplicated. Below is the list of that type.

- alias
- datetime_created
- datetime_updated
- user_created
- user_updated
- o2m
- m2o

So I think we should remove `M2O` from here to resolve this error. Kindly provide your thoughts here :)

**Comment by rijkvanzanten** [comment]
> Currently, we delete the fields that shouldn't / can't be duplicated. Below is the list of that type.

Isn't that the problem though? The field is empty in the copy because it gets deleted, which in turn causes the API to error out because of the `required` check. 🤔

**Comment by bjgajjar** [comment]
> Isn't that the problem though?

Yes.

But I am not aware of the reason behind this condition. That's why I was asking you; before removing `M2O` from this condition, that is this necessary?

**Comment by benhaynes** [comment]
`m2o` _should_ be duplicated. If you have `book.author` (M2O) and duplicate the book, I would want the author to still be there.

When duplicating, these values should be set fresh:
* `datetime_created`
* `datetime_updated`
* `user_created`
* `user_updated`

`o2m` Can't be duplicated, so this should be stripped.

**Comment by bjgajjar** [comment]
@benhaynes Agree with you here. Just want the confirmation from @rijkvanzanten / You.

Thanks will send the PR.

**Comment by bjgajjar** [comment]
Fixed in #1977
