### ISSUE TITLE
Removing `status` field from collection breaks CMS

### ISSUE THREAD

**Issue by freder** [directus/app#1698]
# Bug Report

## Steps to Reproduce

- create new role
- create new user for that role
- create new collection
- create new entry
- delete `status` field on collection
- site is broken for user with custom role (but not for the admin user)
- adding the `status` field back "fixes" it

## Actual Behavior
![Screenshot 2019-05-31 at 11 02 30](https://user-images.githubusercontent.com/724844/58694794-28895c80-8394-11e9-8aec-4f8bb0e11b5b.png)
(also after logging out and in again)

## Other Context & Screenshots
![Screenshot 2019-05-31 at 11 19 27](https://user-images.githubusercontent.com/724844/58695565-042e7f80-8396-11e9-89f4-f658de1075ef.png)

## Technical Details

docker: `directus/api:latest` + `directus/app:latest`

**Comment by theharshin** [comment]
Hi @freder, The issue seems to be solved now with recent updates as I'm not able to reproduce the issue. Can you update to latest build and try again?

PS: Right now the `hydrate.js` does not contain any operation/variable named `published`. So there is definitely an update which fixed the issue.

**Comment by rijkvanzanten** [comment]
@theharshin The issue here is that the API still contains permissions settings for the status field, which now doesn't exist anymore. The app will try to apply those status permissions based on the non-existing status field which is probably the cause of this issue

**Comment by theharshin** [comment]
Looks like the error is not reproducible in latest build. @freder feel free to reopen if the issue reoccurs.
