### ISSUE TITLE
Slider fails on 0-value with negative minimum

### ISSUE THREAD

**Issue by git-solatis** [directus/app#1702]
If using a 'Slider' inteface with a negative minimum and a positive maximum it is not possible to select / to store the '0'-value.

**Steps to reproduce**

1. add a Slider interface to any collection
2. select a negative minimum (for example '-100') and a positive maximum (for example '100') within the options
3. try to select the '0'-value

**Corresponding code**

The problen relies within _app/src/interfaces/slider/input.vue_ at line 22:

`if (!this.value) return this.options.minimum;`

Changing this for example to:

`if (!this.value && (this.value !== 0 || this.options.minimum > 0)) return this.options.minimum;`

would fix the problem. I've tested the sollution with an custom interface.

![sliderFailsWithNegativeMinimun](https://user-images.githubusercontent.com/9914381/58733700-8ac67980-83f5-11e9-90cf-8eb277610aee.png)

I can also create an pull-request but never done so before so you might guide me where to start?

Regards,
Jan

**Comment by rijkvanzanten** [comment]
Heya! Thanks for letting us know.

For a fix that simple, you should be able to edit it directly on GitHub by hitting the pencil icon in the top right of this page https://github.com/directus/app/blob/master/src/interfaces/slider/input.vue, modifying the file, and hitting save. That should open a pull request right away 🙂 

Alternatively, you can fork the repo, clone your fork to your local machine, make the change, commit the changes, push it up to your clone, and open a pull request from github. For a change this small I'd recommend the first option. 

Thanks in advance ❤️

**Comment by git-solatis** [comment]
Created a pull-request: https://github.com/directus/app/pull/1703

(Is it possible on GitHub to assign issues and corresponding pull-requests to each other?)
