### ISSUE TITLE
Minor issue with notification button in activity info sidebar

### ISSUE THREAD

**Issue by 24js** [directus/app#1707]
Here is a recording of current behavior pretty much self-explanatory,

![notification](https://user-images.githubusercontent.com/4061327/58752296-b747c780-84c1-11e9-9764-85bee598400e.gif)

**Comment by benhaynes** [comment]
Thanks @24js!! This seems easy to fix, sorry we missed it!

**Comment by shealavington** [comment]
I'm pretty sure I fixed this already, can you please ensure you're on the latest version...

**Comment by rijkvanzanten** [comment]
I'm not seeing this on the live demo as well

**Comment by benhaynes** [comment]
I'm seeing this locally on `master`

![Screen Shot 2019-06-03 at 11 17 38 AM](https://user-images.githubusercontent.com/522079/58813237-50c1c700-85f1-11e9-99ec-721152afbe9d.png)

**Comment by shealavington** [comment]
That's actually really weird... 

I've just checked the demo, modified an item loads of times to see if I could replicate it, and oddly, I could, which is weird considering my code seems to be merged to fix that issue.

If I copy my CSS and paste it in the DevTools, it works, is my fix somehow missing? lol :man_shrugging:

**Comment by 24js** [comment]
@shealavington I checked directus.app and I chose DIrectus latest on the left side menu, Still has this issue

**Comment by benhaynes** [comment]
Still seeing this... seems easy enough to fix!

**Comment by rijkvanzanten** [comment]
@shealavington You only fixed it on the item listing page, not the item detail page 😉
