### ISSUE TITLE
WYSIWYG Full: value displayed in tabular view not ideal when the value contains paragraphs

### ISSUE THREAD

**Issue by nstCactus** [directus/app#1715]
The new WYSIWYG Full interface stores the value in the database as a single line of HTML.
When this value is displayed in tabular view, its HTML tags are stripped. They should be replaced by a space character instead to avoid glueing together the last word of a paragraph to the first word of the next (see the screenshot below).

A quick way to fix this would be to change [display.vue:13](https://github.com/directus/app/blob/c9477f9bccd0be5ab0a5afaaed5f197992edff4d/src/interfaces/wysiwyg-full/display.vue#L13) to replace HTML tags with a space character instead of an empty string (by default multiple whitespace are displayed as a single space character).

<img width="500" alt="Screenshot 2019-06-05 13 19 38" src="https://user-images.githubusercontent.com/353843/58952861-2872cd80-8795-11e9-902a-ae752c669645.png">

**Comment by gitlabisbetterthangithub** [comment]
I'd like to have a go at resolving this issue. I'll make a pull request soon.

**Comment by benhaynes** [comment]
That'd be awesome @gitlabisbetterthangithub! Thank you! 😄 

Also, I'd like to mention that we have a new WYSIWYG editor that will be released in the next week or two. But we'll likely keep this one around too, so it'll be good to have this fixed.

**Comment by nstCactus** [comment]
The soon-to-be-released WYSIWYG editor seems to be affected as well (if I'm not mistaken and the corresponding PR is #1441): https://github.com/directus/app/blob/214906eea6bed10a7ec086d21b722a62a79270cf/src/interfaces/wysiwyg-full/display.vue#L13

**Comment by gitlabisbetterthangithub** [comment]
Resolved in #1717 but not for the new WYSIWYG.

@benhaynes I've been following the development of the new WYSIWYG editor and it looks very promising. I was going to ask the question as to when it would be available but it looks like you've answered that. Thank you. Hopefully the new editor will allow me to continue development of my app.

**Comment by benhaynes** [comment]
Thank you for the PR @gitlabisbetterthangithub! We'll apply this to the new editor as well.

The new editor is under review, it needs about a days worth of work still but we won't have time to finish it up for this release (today or tomorrow). It should be in the next one though!

**Comment by gitlabisbetterthangithub** [comment]
@benhaynes I'd like to also have a go at pulling in #1441, making the change and submitting a new pull request if that's okay with you?

**Comment by benhaynes** [comment]
That'd be great! 👍

**Comment by gitlabisbetterthangithub** [comment]
All done in #1718 :)

**Comment by rijkvanzanten** [comment]
Thanks @gitlabisbetterthangithub 🙂
