### ISSUE TITLE
Not honoring "hidden browse" flag

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1720]
I created a new collection, and `sort` gets `directus_fields.hidden_browse` == `true`... but it is still showing up in the default tabular column list.

![Screen Shot 2019-06-05 at 3 28 10 PM](https://user-images.githubusercontent.com/522079/58984244-8bb92b80-87a6-11e9-89b3-a85424e5df59.png)

**Comment by rijkvanzanten** [comment]
Does it show up in the field selection in the info sidebar?

**Comment by benhaynes** [comment]
Yeah

**Comment by rijkvanzanten** [comment]
That's a good sign at least ^^

It means that the app does use the hidden on browse flag except it doesn't take it into account when creating the fallback selection

**Comment by theharshin** [comment]
When looping, there is no condition set for hiding the columns for `hidden_browse`.
A little clarification required on: `hidden_browse`
- Is it useful only for initially hiding the field. User can later see by turning it on from info sidebar.
- It will completely hide the field and users won't see it anywhere. Not in listing and not in info sidebar.

I've done the table layout part. Just need to clarify the info sidebar listing.

**Comment by rijkvanzanten** [comment]
@theharshin Option 2, we should filter it out one level above the tabular layout though. We should implement it once and make it work for every layout
