### ISSUE TITLE
Support "Soft Delete"

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#173]
If the collection has the status mapping setup through a status type interface, deleting an item should no longer send a DELETE request to the api, but instead send a PATCH to set the status to the deleted value in status mapping

**Comment by rijkvanzanten** [comment]
And double check interfaces usage & accent color option

**Comment by bkd705** [comment]
Would this require a front-end consuming the API to send a PATCH as well, or would this just be from the `app`?

I'm a bit new here so take this with a grain of salt:

But would it make sense to still use a DELETE request to the API? Similar to how Laravel has their soft deletes setup [here](https://laravel.com/docs/5.6/eloquent#soft-deleting).

This would allow a front-end to stay agnostic to whether or not soft deletes are happening. For example, say you have some content that does soft delete and others that do, from a API consumer perspective, it may be more complex to keep track of which ones you send a PATCH to delete and which ones you send a DELETE to delete.

**Comment by benhaynes** [comment]
I tend to agree with @bkd705. If we do this your way Rijk then it's an App feature... not a Directus feature (including API). Anyone can `UPDATE` a status column, but we want to treat this as a _true_ delete... that is recoverable.

Because of that, I would argue that `DELETE` and `SOFT-DELETE` should be handled the same way. Thoughts?

cc: @WellingGuzman

**Comment by rijkvanzanten** [comment]
Fair point! But that also means that we have to add some sort of param to make it “hard delete”

**Comment by benhaynes** [comment]
Correct, Laravel uses: `$flight->forceDelete();`

But as far as the API is concerned, both soft and hard delete would be the same... making data inaccessible.

**Comment by rijkvanzanten** [comment]
Exactly.. Also, I know it's bikeshedding over semantics, but sending a `DELETE` HTTP request would be wrong if it doesn't delete a record...

**Comment by benhaynes** [comment]
Definitely just semantics, I think in this case it is arguable both ways. Without getting philosophical: When is an item truly deleted?

* What if the App and API both treat it as deleted? (with a field flag, as is the case here)
* What if you move it to a different "trash" table/collection?
* What if it's really deleted but you have failsafe database clones?
* What if it's really deleted but you have offsite SQL backups?

I argue that if it's inaccessible, for all intents and purposes it's deleted.

**Comment by rijkvanzanten** [comment]
> I argue that if it's inaccessible, for all intents and purposes it's deleted.

Agreed, _but_ admins can still retrieve / use them

**Comment by benhaynes** [comment]
Still, my arguments above still apply. An admin could access backups, clones, or a separate "trash" table... but I think we're talking from the perspective of any and all _users_ (not admins). Absolutely no users can see deleted items.

**Comment by benhaynes** [comment]
What's the status of Delete vs Soft-Delete? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
No news. The app deletes items and doesn't support soft delete (yet)

**Comment by benhaynes** [comment]
@rijkvanzanten — this is our new TOP priority. This needs to be completed asap.

**Comment by ericcanadas** [comment]
Any News ? 
Is there a way to recover an item that has been soft-deleted ?

**Comment by benhaynes** [comment]
He's, this has been added in v9

**Comment by ericcanadas** [comment]
ok thanks.
Have you an idea of the deployment date in directus cloud?

**Comment by benhaynes** [comment]
It's in RC now, production within a month

**Comment by ericcanadas** [comment]
Ok ! And Today there is no way (even hidden or by API) to recover a soft-deleted document ?

**Comment by benhaynes** [comment]
Yes, you can in v8 via the API or directly in the database.

**Comment by ericcanadas** [comment]
OK but how ? I have't found in doc and i have't access to database if I use Directus Cloud ??

**Comment by benhaynes** [comment]
Apologies, but GitHub issues isn't for support — you'll have to research things a bit more of chat with the community:

https://docs.directus.io/api/items.html#update-an-item
https://directus.chat/
