### ISSUE TITLE
Using repeater with MAP interface not working

### ISSUE THREAD

**Issue by matoware** [directus/app#1737]
Hey there,

i discovered an issue with the new repeater and the MAP interface: Entering the first item works fine. But if adding another, the MAP doesn't show up. Therefore its impossible to add more than one POI. The database shows the values like this (for the first and the sceond item): 

**[{"MAP":{"lat":40.7127281,"lng":-74.0060152}},{"MAP":null}]**

The interface for the second item looks like this: 

<img width="702" alt="Bildschirmfoto 2019-06-10 um 13 19 39" src="https://user-images.githubusercontent.com/50927932/59192837-11acec00-8b84-11e9-96c2-81a014aac15c.png">

Anyone experience the same issue?

Regards,
Fab

**Comment by nwabeen** [comment]
Sorry but this issue still exist in 8.8.0.
