### ISSUE TITLE
Missing cancel button in M2M Relation in "select existing"

### ISSUE THREAD

**Issue by onlinelessons** [directus/app#1740]
I have a M2M Relation. If I click on "select existing" there is no cancel button in the following modal:

![image](https://user-images.githubusercontent.com/47600858/59262148-f6eb7d80-8c3e-11e9-8e70-02286ef3b098.png)

**Comment by benhaynes** [comment]
Thanks @onlinelessons — we've fixed this for O2M and M2O... next up is M2M! :)
