### ISSUE TITLE
Tooltip has link but can't be hovered over

### ISSUE THREAD

**Issue by shealavington** [directus/app#1741]
The tooltip when managing a collection has a link inside, however, you can't hover over this tooltip to click the link haha, moving the mouse to click the link hides the tooltip :joy:

![Selection_005](https://user-images.githubusercontent.com/16869302/59266730-3ff00180-8c40-11e9-913d-36645f08e7cc.png)

**Comment by benhaynes** [comment]
Oh, good catch!!

@rijkvanzanten does our tooltip allow for custom events? Could we have _click_ toggle it open so it's clickable?

**Comment by rijkvanzanten** [comment]
We can make it open on click, but that's hiding it away even more. I'd rather add a delay for when it closes again. I don't think it closes when you are already hovering the tooltip, so adding a 750ms delay when moving the mouse should give the user some time to move the mouse to on the tooltip.

**Comment by samvasko** [comment]
There is also this more complex but amazing [solution](https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown).

**Comment by rijkvanzanten** [comment]
Wow that's clever @samvasko. Maybe we should open up a feature requests at the v-tooltip repo to implement this 😋
