### ISSUE TITLE
SSO - Last Activity Page

### ISSUE THREAD

**Issue by aswincoolsaet** [directus/app#1742]
When you have SSO Enabled ( or maybe even without ) 
/login  should never be in your  "last_page"  visited user profile field. 

It took me a few hours to figure out why my SSO didn't work anymore.

After a succesfull login your see a http query:
me?fields=last_page   -->    {"data":{"last_page":"\/login"}}

which caused the "app"  to show the login page => I never was able to go to the app, because I got stuck on the login page. 

how to reproduce?
put /login   in the database as the last loggedin page => you have your issue.

how to solve?
- or make sure it never reaches the DB. '/login'
- or if '/login' is detected from client side . bypass to go to the dashboard

**Comment by aswincoolsaet** [comment]
I solved it by:

    public function updateLastPage($id, $lastPage, array $params = [])
    {

		if( $lastPage == "/login" ) { $lastPage = "/collections";  } /*  --> THIS LINE */
        $data = [
            'last_page' => $lastPage,
            'last_access_on' => DateTimeUtils::now()->toString()
        ];

        $this->createTableGateway($this->collection, false)->update($data, [
            'id' => $this->getUserId($id)
        ]);

        return $this->find($this->getUserId($id), $params);
    }

**Comment by benhaynes** [comment]
Thanks @aswincoolsaet!! 

Would it be possible to open a PR with this change? We'd love to have it fixed for everyone! 😄

**Comment by rijkvanzanten** [comment]
That seems like a very hardcoded fix specifically targeting the strings `/login` and `/collections`. Instead of filtering this in the API, the application should ignore the redirect if the path is `/login` on login

**Comment by theharshin** [comment]
App will never push the "/login" or "/logout" as `last_page` but still I've added checks while tracking and after login to avoid this paths.
