### ISSUE TITLE
Zero as ID / PK

### ISSUE THREAD

**Issue by aswincoolsaet** [directus/app#1744]
Sometimes external Data starts with ID 0 
this creates serveral issues within Directus. 

when inserting through the API: 
-> directus ( or mysql )  makes it  as a incremental so the ID is not zero after inserted. 
 
solution; 

https://codippa.com/how-to-insert-0-in-auto-increment-column-in-mysql/
SET sql_mode=’NO_AUTO_VALUE_ON_ZERO’;

NO_AUTO_VALUE_ON_ZERO affects handling of AUTO_INCREMENT columns. Normally, you generate the next sequence number for the column by inserting either NULL or 0 into it. NO_AUTO_VALUE_ON_ZERO suppresses this behavior for 0 so that only NULL generates the next sequence number.

you can change the value through phpmyadmin and from there on everything works fine. 

--------------------------------------------

Ok all good; the value is zero now after manually editing the database. 

in a relationship field;  
he doesn't list the value , he just shows "- ()" in the culumn overview.
while others have the actual "CustomerName" .
--- image 1:
![image1](https://user-images.githubusercontent.com/44744970/59293223-0d192e00-8c7f-11e9-82d9-69244e9c238b.PNG)

------------------------------
When you edit the "item" 
he does show it in the dropdown but still says "select one"

Look at the image:
* Billing 2 Account  has  an item with ID 0 ( still saying select one ) but shows the "name" on the right
* . Account  has an item with a non-zero value.  and just shows the name as defined. 

--- image 2
![image2](https://user-images.githubusercontent.com/44744970/59293222-0d192e00-8c7f-11e9-9c51-220852db687a.PNG)

through the API to GET the items is all good;

    "data": [
        {
            "modified_by": 2,
            "modified_on": "2019-06-11 17:18:05",
            "domain_name": ".......com",
            "billing_2_account": 0,
            "registrar": "xxxxx",
            "xxxxx_account": 29683493,
            "startup_fee": false,
            "startup_fee_cost": 60,
            "start_billing_date": null
        },

**Comment by benhaynes** [comment]
We can take a look into this, but I feel that it might not be within our [80/20 rule](https://docs.directus.io/getting-started/contributing.html#_80-20-rule). Either way, it would be a nice thing to support if it doesn't add too much complexity to the core codebase.

Thanks @aswincoolsaet

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by aswincoolsaet** [comment]
Hey Ben,

I think it's a bug. Because you say "add item with ID 0" 
which is just adding a parameter to the mysql connection and all is good.  ( nothing needs to be edited even in the core )

Secondly ; 
in the GUI  the value is not "null"  but 0   which is a difference, hence it's a GUI  buy. 
basicly it means the code should
if ( $value )   ==> should be  ==>   if ( $value == null )

**Comment by benhaynes** [comment]
Ahh, good point. We should differentiate between `0` and `null` when sending values from the App.

**Comment by rijkvanzanten** [comment]
The application does differentiate between these two. I think it's the API that's treating it as the same 🤔

**Comment by benhaynes** [comment]
@bjgajjar — can you confirm? If so, we'll transfer this to the API repo

**Comment by rijkvanzanten** [comment]
@directus/api-team can we revisit this?

**Comment by bjgajjar** [comment]
@rijkvanzanten I'll check it and update you on this ASAP :)

**Comment by bjgajjar** [comment]
Fixed in #1974
