### ISSUE TITLE
Firefox error on M2O 

### ISSUE THREAD

**Issue by mebenhoehta** [directus/app#1745]
This is reproducible on https://directus.app/  app 7.5 and api 2.1.0
when loading 
https://directus.app/#/collections/sales/182942 on Firefox 60.6.3
I get an error "There was a problem loading the many-to-one extension."
 and the member is  not displayed:
![image](https://user-images.githubusercontent.com/48298451/59317316-a7bc5000-8d05-11e9-842c-8985c867b025.png)

On Chrome it looks OK:
![image](https://user-images.githubusercontent.com/48298451/59317334-c4588800-8d05-11e9-9174-10278f9155e6.png)

(locally I found it with API 2.1.1 and based on the error message, I assume it is an APP and not API problem)

**Comment by Derilka** [comment]
have the same issue with local installation - also on firefox - cannot test in other browsers
firefox trace does not output anything suspicious on the nework trace

**Comment by Derilka** [comment]
duplicate to Broken Many-To-One field #1747

**Comment by benhaynes** [comment]
Yeah, seems like it. I'll close this as a duplicate... let's keep the conversation going over there.
