### ISSUE TITLE
File(s) modal looks broken when nothing loads

### ISSUE THREAD

**Issue by shealavington** [directus/app#1746]
I'd probably consider this a bug, but also an optimisation, when the files modal loads, if your server isn't fast enough to return the data, it feels broken. It's only after 25 seconds (when my server responded) that I realized it was just being slow.

**Could do with a loading icon to show it's doing something (loading).**
![Selection_008](https://user-images.githubusercontent.com/16869302/59335586-c8c87500-8cf4-11e9-8599-3b5ce1306ae6.png)

~*On that note, there also seems to be a search bar padding issue that I'm sure I fixed... That's now broken again (too close to the edge), this seems to be the second issue now that I'm sure I've fixed, that seems broken again.*~

**Comment by benhaynes** [comment]
This should get fixed when we switch the M2M over to the new modal... we'll make sure this master-modal has a loader.

**Comment by rijkvanzanten** [comment]
This is `files` though, not the many to many. Different interfaces.

I think you might've fixed another one Shea

**Comment by shealavington** [comment]
Ah, true haha, I did all of the relational ones, not the files. Touche.
