### ISSUE TITLE
Broken Many-To-One field

### ISSUE THREAD

**Issue by visualcookie** [directus/app#1747]
# Bug Report

## Steps to Reproduce

1. Go to `Collections -> Posts`
2. Click on `New field -> Many-To-One`
3. Add a name, e.g. `category`
4. Set `Related collection` to `Categories`
5. Add `{{name}}` to `Dropdown template`
6. Hit `save`
7. Click on `Posts -> "+" Icon`
8. See error: `There was a problem loading the many-to-one extension.`

## Expected Behavior

The newly created category field should have the categories which exist in the `Categories` collection, which can then be selected.

## Actual Behavior

Instead, the field is not a select field and there's nothing to choose from.

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/1857554/59352065-14444880-8d20-11e9-8205-d6b9fb38ac25.png)

![image](https://user-images.githubusercontent.com/1857554/59352090-21f9ce00-8d20-11e9-99cc-6f98d7ce602e.png)

## Technical Details

- Device: MacBook Pro
- OS: MacOS
- Web Server: Heroku/Apache
- PHP Version: Heroku/Latest
- Database: JawsDB (MySQL)
- Install Method: ZIP Download

**Comment by benhaynes** [comment]
Hey @visualcookie — were you using FireFox?

**Comment by shealavington** [comment]
I believe I had the same issue on firefox not long ago, and it persisted after multiple refreshes.

**Comment by visualcookie** [comment]
@benhaynes Yeah, I'm a Firefox Poweruser 😆 
@rijkvanzanten Yep, does persist after refresh.

**Comment by lcdss** [comment]
The same is happening with me and the bug can even be reproduced in the demo app: https://directus.app/#/collections/kiosks/+

**Comment by lcdss** [comment]
The same is happening with me on `Firefox Developer Edition` and the bug can even be reproduced in the demo app: https://directus.app/#/collections/kiosks/+
Using the `Chromium` works with no problem.

**Comment by lcdss** [comment]
The same is happening with me on `Firefox Developer Edition` and the bug can even be reproduced in the demo app: https://directus.app/#/collections/kiosks/+
Using the `Chromium` works with no problem.

![201906141560497933_8SQCGQRd](https://user-images.githubusercontent.com/6903590/59492173-c4b86680-8e5e-11e9-85db-578d22806566.png)

**Comment by stalinkay** [comment]
@benhaynes This issue also affects Safari.
