### ISSUE TITLE
Unable to add a new field to translation collection

### ISSUE THREAD

**Issue by stalinkay** [directus/app#1753]
I created a docker image based on your docker build repo. The container appears to work just fine except for when I'm trying to add a new field to an existing translation collection. I tried to run the sql query in adminer and it produces the following error. Something to do with the `hidden_detail` field. 

```
INSERT INTO `directus_fields` (`collection`, `field`, `type`, `interface`, `required`, `sort`, `note`, `hidden_detail`, `hidden_browse`, `options`, `readonly`, `validation`, `width`) VALUES ('resort_translations', 'rate', 'string', 'text-input', '1', NULL, NULL, '', '', '{\\\"trim\\\":true,\\\"showCharacterCount\\\":true,\\\"formatValue\\\":false,\\\"width\\\":\\\"auto\\\"}', '', NULL, 'full')
Error in query (1366): Incorrect integer value: '' for column 'hidden_detail' at row 1
```

app: 7.5.0
api: 2.1.1

[201906131400.nwr.sql.gz](https://github.com/directus/app/files/3286486/201906131400.nwr.sql.gz)

**Comment by stalinkay** [comment]
After further testing, it appears that the field gets created setting up managing is failing. It seems to work after manually clicking the `Manage` button

```
"error": {
        "code": 9,
        "message": "Failed generating the SQL query.",
        "query": "SELECT NULL AS Expression1, `resort_translations`.`resort` AS `resort`, `resort_translations`.`language` AS `language`, `resort_translations`.`brief_description` AS `brief_description`, `resort_translations`.`extend_description` AS `extend_description`, `resort_translations`.`rate` AS `rate` FROM `resort_translations` ORDER BY `resort_translations`. ASC LIMIT 50 OFFSET 0"
    }
```

**Comment by stalinkay** [comment]
@benhaynes I have attached a database that should allow you to reproduce the issue. Setting up translations seems to be breaking everything.

**Comment by stalinkay** [comment]
It seems that translations only work when the default primary key is not deleted from the translation collection. In other words, a primary key plus two foreign keys are required.

**Comment by itsmerhp** [comment]
Hello @stalinkay 
I have checked SQL dump you have shared and found that it is not working due to the removal of the primary key, each collection must have a primary key.
Please add primary key in translations table and it will work fine.

**Comment by stalinkay** [comment]
Hi, @itsmerhp thanks for the reply. I found this out the hard way, I assumed that I could mess with the primary keys and foreign keys at will. I'll close this.
