### ISSUE TITLE
Version 7.5.0 doesn't work on Firefox

### ISSUE THREAD

**Issue by okayawright** [directus/app#1757]
Hello

Commit 043cfd029ae522374c91633600154ce5ab7af483 brings a new file *get-fields-from-template.js* which apparently breaks compatibility with Firefox on home builds.

This [regular expression](https://github.com/directus/app/blob/b52554dd856695dd050905ac75ef93901f73b8a4/src/helpers/get-fields-from-template.js#L11) features a lookbehind and a lookahead, something that [Firefox doesn't handle yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665).
While apparently this version of Directus still works with Chrome, I think the regular expression should be rewritten so that other modern browsers can still use Directus.

I don't how https://directus.app/ (which states that it is version 7.5.0) is transpiled but it looks like it circumvented that problem. I believe Babel is hopeless with regexp so I'm puzzled how the demo can work out-of-the-box with Firefox. What are your build settings?

FYI tested with Firefox 67.0.2

**Comment by Nitwel** [comment]
Well, I can use Directus, without any problem using Firefox in the latest version.
Could you add these informations:
Where does this error occur?
Whats the error message?
Where are you running Directus? (Localhost / Webserver)

And if you got even more details, please add them too.

**Comment by okayawright** [comment]
Local build (that's the thing)
![81368168116](https://user-images.githubusercontent.com/1095407/59495041-cbf76880-8e8e-11e9-97ef-db6689f92d11.jpg)
If you confirm that you got it working with Firefox then it's a problem on my end, the way I built it probably, but on the other hand I see no babel regexp plugin on the stock builder and that expression is confirmed not to be interpretable by Firefox as-is; so I'm interested in taking a peek at your setting files if possible.

Here's my package.json:
```json
{
  "name": "directus",
  "version": "7.5.0",
  "private": true,
  "description": "Directus is an Open-Source Headless CMS & API for Managing Custom Databases",
  "author": "Rijk van Zanten <rijk@rngr.org>",
  "scripts": {
    "build": "vue-cli-service build --no-unsafe-inline",
    "test": "vue-cli-service lint",
    "dev": "vue-cli-service serve",
    "fix": "prettier --write \"src/**/*.{js,vue}\"",
    "storybook:build": "vue-cli-service storybook:build -c ./.storybook -s ./public",
    "storybook:dev": "vue-cli-service storybook:serve -p 6006 -c ./.storybook -s ./public"
  },
  "dependencies": {
    "@directus/extension-toolkit": "0.3.0",
    "@directus/format-title": "^2.3.1",
    "@directus/sdk-js": "^5.3.1",
    "@rijk/jwt-payload": "^1.0.1",
    "axios": "^0.19.0",
    "body-scroll-lock": "^2.6.1",
    "codemirror": "^5.47.0",
    "convert-range": "^1.1.0",
    "core-js": "^2.6.9",
    "cropperjs": "^1.5.1",
    "date-fns": "^2.0.0-alpha.31",
    "dateformat": "^3.0.3",
    "flatpickr": "^4.6.1",
    "hex-rgb": "^4.1.0",
    "idlejs": "^2.0.1",
    "jsonlint-mod": "^1.7.4",
    "leaflet": "^1.5.1",
    "lodash": "^4.17.11",
    "marked": "^0.6.2",
    "medium-editor": "^5.23.3",
    "micromustache": "^5.4.0",
    "mousetrap": "^1.6.3",
    "portal-vue": "^2.1.5",
    "quill": "^1.3.6",
    "quill-image-upload": "^0.1.3",
    "shortid": "^2.2.14",
    "slug": "^1.1.0",
    "snarkdown": "^1.2.2",
    "v-tooltip": "^2.0.2",
    "vue": "^2.6.10",
    "vue-codemirror": "^4.0.6",
    "vue-flatpickr-component": "^8.1.2",
    "vue-i18n": "^8.11.2",
    "vue-meta": "^1.6.0",
    "vue-router": "^3.0.6",
    "vue-simple-spinner": "^1.2.8",
    "vue-the-mask": "^0.11.1",
    "vue-timeago": "^5.1.2",
    "vuedraggable": "^2.21.0",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/runtime-corejs2": "^7.3.1",
    "@storybook/addon-a11y": "^5.1.1",
    "@storybook/addon-actions": "^5.1.1",
    "@storybook/addon-backgrounds": "^5.1.1",
    "@storybook/addon-centered": "^5.1.1",
    "@storybook/addon-knobs": "^5.1.1",
    "@storybook/addon-links": "^5.1.1",
    "@storybook/addon-viewport": "^5.1.1",
    "@storybook/vue": "^5.1.1",
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "@vue/eslint-config-prettier": "^4.0.1",
    "babel-eslint": "^10.0.1",
    "cross-env": "^5.2.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.2.2",
    "html-loader": "^0.5.5",
    "lint-staged": "^8.2.0",
    "markdown-loader": "^5.0.0",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-preset-env": "^6.5.0",
    "prettier": "^1.17.1",
    "sass": "^1.20.3",
    "sass-loader": "^7.1.0",
    "storybook-readme": "^5.0.3",
    "vue-cli-plugin-storybook": "^0.6.1",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^4.29.6"
  },
  "contributors": [
    "Ben Haynes <ben@rngr.org>"
  ],
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,vue}": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}
```

I'll report back after resetting everything to the stock settings from the git repository

**Comment by shealavington** [comment]
From the screenshot, I see a blank-screen.

Have you made sure you have a config.js file? 
I usually have an issue when the config.js file is missing on a fresh copy and the screen goes blank.

**Comment by okayawright** [comment]
The culprit is really that regexp, if I fix it and only touch this line then the appliction loads up perfectly

**Comment by okayawright** [comment]
I think I figured it out.

My build setup is a bit different than the one provided on the git repository.
I use corejs 2 as polyfills by default with babel, the stock setup doesn't. If I disable corejs:

i.e.
I switch my **babel.config.js file** from
```json
/* global module */
module.exports = {
  presets: ["@vue/app"],
  plugins: [
    [
      "@babel/plugin-transform-runtime",
      {
        corejs: 2
      }
    ]
  ]
};
```
to
```
module.exports = {
  presets: ["@vue/app"]
};
```
 then it works with Firefox. I'll close this issue and reopen it on the corejs bug tracker instead.

Thanks for the help and sorry for the inconvenience
