### ISSUE TITLE
Remove support for history routing mode

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1759]
It doesn't work combined with using the app in a relative path. Fixing that would add way too much overhead to make it worth it. Ref #1748.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dasch8** [comment]
I think this could be fixed by using a document base URL (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base). I added the tag manually to `index.html` and it seems to work fine.

**Comment by benhaynes** [comment]
Thanks @dasch8 — we're actually making some big changes to how the App/API are structured... so maybe this won't be an issue after the next release. Any thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
@dasch8 We'd have to set the same base in build time to make sure assets like images and script.js / style.css are loaded correctly too, which would break support for running the suite in a folder.

Combining history mode with relative URLs for the static assets doesn't work
