### ISSUE TITLE
File (Filed type) not working after selecting and saving collection

### ISSUE THREAD

**Issue by chz** [directus/app#1767]
Seems to be File (Core Interface) not working. I cant save Singleton or etc. Error: Internal Server Error

Reproduce: 
1) Go to https://directus.app/#/collections/about
2) Add File Object
3) Go to https://directus.app/#/collections/about/1
4) Select image and hit save. (Internal server error)

PS: Sorry for my english :/

**Comment by shealavington** [comment]
This has been fixed ready for the next release.

Ref: https://github.com/directus/api/issues/1015

**Comment by chz** [comment]
Thanks @shealavington

**Comment by chz** [comment]
@shealavington Manually fixed file
