### ISSUE TITLE
O2M

### ISSUE THREAD

**Issue by hendrikkiedrowski** [directus/app#1776]
# Bug Report

## Steps to Reproduce

1. Install latest version of Directus Suite.
2. Create two collections. (Parent and child)
3. Create Fields in collections. Especially the ParentID field in the child collection. Afterwards create the O2M connection in the Parent collection. using the before created field. 
4. See the Relation not working in parent Collection.   

I tried this way on several Systems with several DB distributiuons. But the Error seems to stay redundant. 
Several versions ago the Error was slightly different. I could create the Relationship but could not get the Fields from the API. The Json nearly complete except the referred Table items. 

Error Log from directus Log folder: https://pastebin.com/xA0ijkKb
## Expected Behavior
Able to create children and also select already existing ones to add to parent. 
See children in API output JSON object. 
## Actual Behavior
Creation of children from parent not possible. Selection of existing also not possible. 

### Database schemes: 
+ Child https://imgur.com/v5Bm06t
+ Parent https://imgur.com/ebtJpco
### UI- Views
+ List of pre-created child https://imgur.com/Y0ewM4a
+ Missing Interface for O2M https://imgur.com/kBA5RWa

## Technical Details

- Device: [Desktop, Server]
- OS: [MacOS 10.14.5, Linux Debian Stretch]
- Web Server: [MAMP 5.3, NGINX]
- PHP Version: [7.2.19, 7.1.23,]
- Database: [MySQL 5.7.26]
- Install Method: [cloned `master` branch, zip file install]

**Comment by brocgailit** [comment]
This seems to be an issue with required fields in the referenced collection. If I recall correctly, the recent O2M update is staging by ID now without full child to check against. @rijkvanzanten can you confirm this?

**Comment by rijkvanzanten** [comment]
Any issues in the devtools? What options did you set for the o2m?

@brocgailit you're right
