### ISSUE TITLE
Translations with M2M relation do not get saved

### ISSUE THREAD

**Issue by janholas** [directus/app#1778]
# Bug Report

When having a collection that has translations relation and that translation relation is having M2M relation, any fields in the translation relation do not get saved on update if there is any M2M relation item selected. If the M2M relation interface is empty (no item selected), it gets saved OK

## Steps to Reproduce

1. Create 5 collections with the following or similar schema: 
https://dbdiagram.io/d/5cff47acfff7633dfc8e2536
Translation interface is used and done by the guide in docs

2. Create a new blog item, fill in the fields (title, translated title, translated content), create a new tag and save. Go back to edit item end edit translated content, press save

## Expected Behavior

Updated fields in translated content get saved

## Actual Behavior
Updated fields in translated content do not get saved, no error is thrown (success response with original data)

## Other Context & Screenshots

Here are the screenshots of the request and response on the PATCH call, highlighted is the updated field in request and then in response there is still the original data (note that there are more fields in this setup than provided schema but essentially it's the same) 
 
https://i.imgur.com/99AwAe8.png
https://i.imgur.com/5r6OQhH.png

## Technical Details 
- API 2.1.1, APP 7.5.0
- Device: Desktop
- OS: Alpine 3.8
- Web Server: nginx 1.14.2
- PHP Version: 7.2.18
- Database: 5.7.26
- Install Method: docker (updated to pull newest versions)

**Comment by bpanne** [comment]
Same problem here with different structure. 

collection **page** has m2m to collection **content**
when editing **content** through a **page**, changes are gone when pressing save button.

directly editing in the **content** collection works properly.

**Comment by rijkvanzanten** [comment]
@bpanne Is that also when using the translations interface?

**Comment by blackfox00** [comment]
@itsmerhp will you create PR with the fix?

**Comment by blackfox00** [comment]
can we please rise priority on this? there is no feasible workaround and this bug makes editing items impossible in many scenarios

**Comment by benhaynes** [comment]
Hey @blackfox00 — our lead App developer has been on a client project for the past few months, but as of today is back on the project. We can't prioritize this any higher, but we will have more time now to start working on this.

**Comment by edenprojectde** [comment]
Well run into the same issue i think, can't make WYSIWYG in a Translation table because of this.

The content is getting saved though. It just won't show up after reopening the Entry after saving it.

**Comment by edenprojectde** [comment]
I could solve this by bruteforcing it into the field like this:

input.vue in the translation interface
```JavaScript
   created() {
    console.log(this.relation.field_many.field);
    console.log(this);
    console.log("Translation field created:", this.value);
    this.value.forEach((v,i)=>{
        // Loop over all field_many-translation values in database via the field_many duh
        Object.keys(v[this.relation.field_many.field][this.id.split("-")[1]][i]).forEach((v2)=>{
          console.log("Key:"+v2);
          // Take the values from the o2m field
          console.log("AVal:",v[this.relation.field_many.field][this.id.split("-")[1]][i][v2]);
          // Look at value BEFORE change
          console.log("BVal:",v[v2]);

          // Check that we dont override the field_many in our value
          if(v2!=this.relation.field_many.field)
          v[v2]= v[this.relation.field_many.field][this.id.split("-")[1]][i][v2] // Overwrite all Values to we get no null fields anymore
        })
    });
    console.log("Translation field created 2:", this.value);
    this.fetchLanguages();
  },
```
Probably the wrong way to go about it but it works for the time being.
As you can see the true value is inside the value[field_many]; i took this and just looped over all values to insert them into the original value object. (In which my WYSIWYG stays null)
