### ISSUE TITLE
Layout: Tree View (hierarchy)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1781]
If you have deeply nested (or self-nested) items, it would be nice to have a layout that let's you more efficiently browse, see, explore those items by expanding each item and seeing the children. In this way you could have a nice tree-view that async loads relational content.

I can build a design for this if someone's interested in taking it on!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Nitwel** [comment]
On it!

**Comment by Sennik** [comment]
Where did this request go? I cannot find in the feature request page...

**Comment by benhaynes** [comment]
Over here... https://github.com/directus/next/discussions/417
