### ISSUE TITLE
Optional M2O dropdown input should include a "None" option.

### ISSUE THREAD

**Issue by brocgailit** [directus/app#1786]
# Feature Request

## What problem does this feature solve?
Optional M2O should have a 'None' option (or ability to clear value) since it is not required.

## How do you think this should be implemented?
Add `None` option to interface when field is optional.

## Would you be willing to work on this?
Yes.

**Comment by benhaynes** [comment]
Technically you can use the new Field Label Context menu to clear the value... but this should be clear in the interface itself! 👍

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by brocgailit** [comment]
@benhaynes It's so fresh I forget its there!  I think this could be more clear for sure, but definitely not high-priority.
