### ISSUE TITLE
Couldn't reach API while API is reachable

### ISSUE THREAD

**Issue by Mathlit** [directus/app#1793]
# Bug report
After setting up the Directus app and the API on their own subdomains on a personal website, I can't seem to make the app connect to the API. When checking the network traffic, the app appears to try and call  `https://server/ping`, instead of the intended `https://api.domain.com/server/ping` (which returns the expected "pong")

## Steps to Reproduce
Using the Directus-provided installation instructions, install both the app and API, each on a different subdomain in the same domain. Configure the app to use the API's endpoint, and open up the app. In this case, the app's location is `https://admin.domain.com/` and the API's location is `https://api.domain.com/`.

Set up the API endpoint as such in `config.js`:
```
api: {
  "https://api.domain.com/": "API endpoint"
},
```

## Expected Behavior
The app being able to connect to the API, by calling the correct URL.

## Actual Behavior
When starting the app, it shows trying to ping the API endpoint, only to return the error message "Couldn't reach API". Enabling entering a different API endpoint and entering the API's endpoint in the text input, gives the same result.

## Other Context & Screenshots
I've tried omitting `https://` and `https:` from the API endpoint, and no different results. Checking the browser's developer console showed the app connecting to `https://server/ping`.

For what it's worth, while I haven't properly configured the API yet, browsing to `/server/ping` on my browser returns "pong", so I'm assuming the API's not to blame here.

This happened by cloning the `build` branch from 24th of july, but also with the downloadable release v7.6.0.

## Technical Details
- API: 2.2.0
- APP: 7.6.0
- OS: Debian 9
- Web server: Apache
- PHP: 7.3
- Install method: Git, manual release

**Comment by Tony001stark** [comment]
Try it in laravel 
Route::get("https://api.domain.com/": "API endpoint", function (){

});

**Comment by rijkvanzanten** [comment]
You're missing the project in the API url. Try

```
api: {
  "https://api.domain.com/_/": "API endpoint"
},
```

**Comment by Mathlit** [comment]
I see. I completely missed that the project was actually needed in the endpoint. Thank you!
