### ISSUE TITLE
Repeater field incompatible with default status value

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1794]
Not sure if this is an issue in the default values of the status interface, or the config of the repeater in the options for the status interface, but this doesn't seem right:

![Screen Recording 2019-06-26 at 4 44 18 PM](https://user-images.githubusercontent.com/9141017/60213871-62823d00-9832-11e9-88e2-13f4e4ddccc5.gif)

@Nitwel thoughts?

**Comment by Nitwel** [comment]
The interface works fine, I think its an issue of how the default is set.

**Comment by rijkvanzanten** [comment]
The problem here is the fact that the repeaters uses a _field_ for the _key_, instead of relying on just the key alone. In the case of the status mapping, the repeater is looking for the `value` field, that doesn't exist. Once this value field is filled out everything works as expected.

**Comment by rijkvanzanten** [comment]
The app doesn't add this field when creating a new collection though
