### ISSUE TITLE
Edit button has "delete" label in files interface

### ISSUE THREAD

**Issue by Lapsus** [directus/app#1795]
# Edit button has wrong label in files interface

As you can see in the screen shots the delete and the edit button both have the same label. 
![Bildschirmfoto 2019-06-27 um 08 43 19](https://user-images.githubusercontent.com/799809/60243634-f4348d80-98b8-11e9-81af-74675d50a40e.png)

![](https://gitlab.dirk-benkert.de/sunbooking/projektmanagement/uploads/7de838401121117398433c9716a037c4/Beschreibung_l%C3%B6schen.jpg)

Unfortunately i dont know how to fix this myself.

In addition, if you upload multiple files and without saving the collection try to edit them, the title gets changed for all these files. Maybe you could disable the edit button for as long as the files are not persisted to the database?

**Comment by rijkvanzanten** [comment]
Is this in the latest version?

![image](https://user-images.githubusercontent.com/9141017/60297577-827b3480-98f6-11e9-8a84-e48d363d3dd8.png)

I just checked this local and on the nightly demo but I'm not seeing it there

**Comment by Lapsus** [comment]
@rijkvanzanten 
I just updated and you are right in the current build version the label is correct.
Im closing the issue.
