### ISSUE TITLE
One to many does not work

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1798]
Bug Report

## Steps to Reproduce
1、Creat collection ` blog `,fileds: `title`,'content', 'image' and add some entries
2、Creat collection ` special`,fileds: `title`,'description', 'image'
3、collection ` special` add filed `blog` (one to many),
options:
Visible Columns: image,title
Display Template: {{title}} - {{content}}
4、Add an entry to the collection ` special`  ,At this point, you will find that the system automatically adds a blog by default！！！ Click `Select Existing Button` under the blog field
5、Select and click done,See it
6、Click delete icon after selected entry, See it
7、Click Save Button，See it

## Expected Behavior
Items of the target collection ` special`  can be selected and save

## Actual Behavior
https://streamable.com/dz0ed

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/8030134/60357545-78485b80-9a06-11e9-86e2-306bbd6a34b5.png)
![image](https://user-images.githubusercontent.com/8030134/60357605-afb70800-9a06-11e9-98fd-f467e38a4da1.png)

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.1]
- APP Version: [7.6.1]
- Install Method: [cloned `master` branch]

**Comment by cdwmhcc** [comment]
@benhaynes This problem has been going on for several months. Why not fix it?

**Comment by benhaynes** [comment]
Many problem have been waiting for a while. The reason is that this is free and open source software and our developers don't have infinite time to work on bugs. If someone wants to "sponsor" the resolution, then we can expedite... but most of the remaining issues are larger and require a refactor that takes time.

The other option is for the community to submit PRs for these. :)

**Comment by cdwmhcc** [comment]
> Many problem have been waiting for a while. The reason is that this is free and open source software and our developers don't have infinite time to work on bugs. If someone wants to "sponsor" the resolution, then we can expedite... but most of the remaining issues are larger and require a refactor that takes time.
> 
> The other option is for the community to submit PRs for these. :)

I can pay to fix this major BUG

**Comment by benhaynes** [comment]
That's very exciting, thank you @cdwmhcc!

@rijkvanzanten — any estimates on how long this bug would take to resolve?

**Comment by cdwmhcc** [comment]
> That's very exciting, thank you @cdwmhcc!
> 
> @rijkvanzanten — any estimates on how long this bug would take to resolve?

@benhaynes 
https://github.com/directus/app/tree/o2m

He's fixing it. 🔢

**Comment by rijkvanzanten** [comment]
@cdwmhcc could you try if this PR fixes it for you? https://github.com/directus/app/pull/1804

**Comment by cdwmhcc** [comment]
> @cdwmhcc could you try if this PR fixes it for you? #1804

I tried it many days ago. It can be displayed or selected properly, but after saving, the data becomes empty.

**Comment by rijkvanzanten** [comment]
I believe this is fixed in https://github.com/directus/api/issues/1072

**Comment by cdwmhcc** [comment]
> I believe this is fixed in [directus/api#1072](https://github.com/directus/api/issues/1072)

Are you sure?

**Comment by rijkvanzanten** [comment]
No, that's why I say I _believe_ this is fixed 😁 I still have to test it out and confirm it

**Comment by cdwmhcc** [comment]
> No, that's why I say I _believe_ this is fixed 😁 I still have to test it out and confirm it

Yesterday, after the API project team submitted this fix, I tested git pull, but it still didn't work.

**Comment by cdwmhcc** [comment]
> No, that's why I say I _believe_ this is fixed 😁 I still have to test it out and confirm it

![image](https://user-images.githubusercontent.com/8030134/61136366-1869ae80-a4f6-11e9-8745-915e1912d94f.png)

https://github.com/directus/app/tree/o2m

**Comment by rijkvanzanten** [comment]
Is this while using that O2M PR?

**Comment by cdwmhcc** [comment]
> Is this while using that O2M PR?

Yes,Using O2M PR to test one-to-many

**Comment by cdwmhcc** [comment]
> Is this while using that O2M PR?

Watch this video

https://streamable.com/qtsfo

**Comment by cdwmhcc** [comment]
https://github.com/directus/app/tree/o2m

This branch has been deleted
Has this problem been solved?

@rijkvanzanten

**Comment by rijkvanzanten** [comment]
It was merged in https://github.com/directus/app/pull/1804

**Comment by cdwmhcc** [comment]
> It was merged in #1804

Has this problem been solved?
The latest version I used, it still doesn't work. :sob:

**Comment by cdwmhcc** [comment]
@rijkvanzanten 

https://streamable.com/8hniq

It doesn't work, but the issue is closed.

**Comment by shealavington** [comment]
I'm wondering if you have your setup wrong, would you be able to show your field setup?

**Comment by cdwmhcc** [comment]
> I'm wondering if you have your setup wrong, would you be able to show your field setup?

Slack

**Comment by shealavington** [comment]
![image](https://user-images.githubusercontent.com/16869302/61638223-e17f5f80-ac90-11e9-8d30-eb3f677423db.png)

This is essentially an O2O Relationship... You should ideally have another field in your `soft` collection that this should relate to.

This is a user setup problem, not a Directus issue.

**Comment by cdwmhcc** [comment]
https://streamable.com/lzl9g

**Comment by cdwmhcc** [comment]
@rijkvanzanten 

https://streamable.com/lzl9g

soft: id | title | category (Numeric)
categories: id | name | softs(one to many)

![image](https://user-images.githubusercontent.com/8030134/61645481-42cb2100-acd9-11e9-9bff-ef837c072f02.png)

I set it up according to the steps in the document.
Still not working
I'm sorry

**Comment by molcik** [comment]
any update on this?

**Comment by benhaynes** [comment]
This issue was fixed/closed... if you're still experiencing it please make sure you're on the latest version. If you still are having the issue we can re-open this if you provide new info on how to replicate (ideally on the demo).
