### ISSUE TITLE
Picture display is incomplete

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1799]
# Feature Request
Picture display is incomplete, request to return to the original version

## What problem does this feature solve?
Solve the problem of incomplete picture display

## How do you think this should be implemented?
Back to the previous version

## Would you be willing to work on this?
It shouldn't need me.

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/8030134/60360881-5acbbf80-9a0f-11e9-931f-390b51cbfe80.png)

**Comment by benhaynes** [comment]
Let's not close this one, I don't want it to get lost and agree it should be resolved sooner than other Feature Requests.
