### ISSUE TITLE
Login attempts with invalid email addresses show "Unknown error"

### ISSUE THREAD

**Issue by pgl** [directus/app#1801]
When trying to log in with an invalid email address, the app shows "unknown error":

![image](https://user-images.githubusercontent.com/1181139/60419683-26f6c280-9be6-11e9-8058-5d9eb6292b8e.png)

I'm not sure if this is an app or API issue, really, because the API returns "422 (Unprocessable Entity)":

```
Request URL: http://directus.local/_/auth/authenticate
Request Method: POST
Status Code: 422 Unprocessable Entity
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade
```

The API does log it properly, though:

```
[2019-07-01 09:51:48] api[_].ERROR: Directus\Validator\Exception\InvalidRequestException: email: This value is not a valid email address. in /path/to/directus/directus/src/core/Directus/Services/AbstractService.php:188
```

I guess the API needs to pass back the error somehow.

**Comment by rijkvanzanten** [comment]
I've changed the type of the input field to email, so the browser will prevent the user from submitting the form with an invalid email address. I've also opened a new feature request to differentiate between error `4` (wrong payload) and a potential new `109` error when the user logs in with an invalid email
