### ISSUE TITLE
Add a cancel button to the collection item editor screen

### ISSUE THREAD

**Issue by chintohere** [directus/app#1806]
# Feature Request
Add a close button on edit screen for a collection item.
This discards the changes and closes the item being edited. 
![close_button](https://user-images.githubusercontent.com/1925271/60521251-43037c80-9d2a-11e9-8bb4-616615a40246.png)

## What problem does this feature solve?
This was one of the features requested by content editors as this was common pattern they are used when editing pages in a CMS. This is like a caption button

## How do you think this should be implemented?
A button with [X] or an appropriate icon with an alt text of 'Cancel' should work well here.

## Would you be willing to work on this?
Yes, once we have agreement on feature specifics.

**Comment by benhaynes** [comment]
We actually have this. There's a left arrow just beside the bread crumb that does affectively just that. if you feel like that is not obvious enough we can discuss further, but I'll close this since it's essentially already there. Vona no stand on the towel on the beach
