### ISSUE TITLE
Auth token doesn't auto-refresh.

### ISSUE THREAD

**Issue by jesusmdy** [directus/app#1807]
Hey there! i am using Directus from a local copy, and when i have certain time working on it the system doesn't respond anymore, then, i refresh te page and it show me a "Server error", when i check the console, it puts me an error like `Server error, login into another new instance`.
Sometimes i am uploading a file then the system do that and it shows me an popup like "Token expired" that's what i say that is a token error. i took a time to check the documentation to try to solve that by myself and i found a "static token", should that help me with that problem?

**Comment by rijkvanzanten** [comment]
> i refresh te page

The directus app or your own project?

Have you any custom rules in place regarding the usage of sessionStorage in the browser?

**Comment by jesusmdy** [comment]
On the Directus local project copy on my computer.
All i have edited is the Styles. Nothing else.

**Comment by rijkvanzanten** [comment]
Do you have any aggressive adblockers or anything other plugin that might prevent sessionStorage from working properly?

**Comment by rijkvanzanten** [comment]
I can't reproduce this problem. Let me know if there's any more info we can use to reproduce this and we can reopen.

**Comment by andgar2010** [comment]
Hello@rijkvanzanten. same problem of @jesusmdy, I tested in Directus 8.2 on Droplet of DigitalOcean with client REST insomnia 7.0.6 Win10.

![Insomnia_NQnNx7B64v](https://user-images.githubusercontent.com/19521054/71602529-ca3d7b80-2b26-11ea-8d0a-26f1f0f61e59.png)

![Insomnia_P2EWQxUL8i](https://user-images.githubusercontent.com/19521054/71602464-7f236880-2b26-11ea-879c-05289ed6cf06.png)

**Comment by rijkvanzanten** [comment]
@andgar2010 it looks like you're trying to refresh the JWT token using the static token as a value. The static token provided is not a valid JWT which results in the API crashing. This is to be expected.

The refresh endpoint can be used to retrieve a new JWT based on a JWT that's about to expire.

@benhaynes @bjgajjar we could/should open a new feature request to have the API return a 400 when the user provided a non-valid JWT.

**Comment by andgar2010** [comment]
I have reviewed the last instructions by request to renew jwt through header authorization jwt, but I still get an error on this screen.
![Failed JWT renew](https://user-images.githubusercontent.com/19521054/71648073-8cc72280-2ccd-11ea-860a-19a36d421b19.png)

**Comment by benhaynes** [comment]
The more info is returned by the API errors the better!

**Comment by rijkvanzanten** [comment]
@andgar2010 I think you're misunderstanding what the refresh endpoint does. If you authenticate into the API using the JWT mode, the API will return a JWT on login. This JWT has a relatively short lifespan (20 minutes). When this token is about to expire, you can get a new one by POSTing it to the refresh endpoint. You can recognize a JWT, because it always follows the format `xxx.xxx.xxx` (two dots).

From the screenshot you provide, it looks like you're not POSTing the token you want to refresh in the body:

```
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZW50IjoiUmlqayB3YXMgaGVyZSIsImV4cCI6MTUxNjIzOTAyMn0.REF714QSMmNj47qT_Y1Go2Me6Q8kq7ukQxk_V02BRzc"
}
```

**Comment by andgar2010** [comment]
> @andgar2010 If you authenticate into the API using the JWT mode, the API will return a JWT on login. This JWT has a relatively short lifespan (20 minutes). When this token is about to expire, you can get a new one by POSTing it to the refresh endpoint. You can recognize a JWT, because it always follows the format `xxx.xxx.xxx` (two dots).
> 
> From the screenshot you provide, it looks like you're not POSTing the token you want to refresh in the body:
> 
> ```
> {
>   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZW50IjoiUmlqayB3YXMgaGVyZSIsImV4cCI6MTUxNjIzOTAyMn0.REF714QSMmNj47qT_Y1Go2Me6Q8kq7ukQxk_V02BRzc"
> }
> ```

Thank you for your explanation and clarification.  😉
can be placed in the documentation?

**Comment by rijkvanzanten** [comment]
Yeah! Can you open an issue on the directus/docs repo or submit a PR? 😄
