### ISSUE TITLE
You should be able to change the "display name" of a collection

### ISSUE THREAD

**Issue by weaversam8** [directus/app#1808]
# Feature Request

It would be nice if you could change the "display name" of a collection. This means you could have a collection called `task` that displayed as "Things to Do" in the sidebar.

## What problem does this feature solve?

Users seek the ability to customize the system.

## How do you think this should be implemented?

I'm not an expert on Directus, I haven't used it but for a few hours, but I'm sure there's a system table that stores the configuration data for each collection. You could simply add a new field for display name on that table.

## Would you be willing to work on this?

I would enjoy working on it but am concerned that I don't currently have the time.

**Comment by rijkvanzanten** [comment]
There's an open feature request for adding the ability to translate the collection (and field) names. 

Closed in favor of https://github.com/directus/app/issues/422
