### ISSUE TITLE
Cannot create Many-to-Many field in collection

### ISSUE THREAD

**Issue by avshelin** [directus/app#1809]
Hi,

I have just upgraded directus (7.3) (app+api) to the latest release (7.6.1), and ran the database upgrade script. Everything seemed to be fine, however when trying to add a many-to-many field, the app would not even allow me to select the many-to-many type.

OS: macOS 10.14.5
Browser: Version 12.1.1 (14607.2.6.1.1)
Directus App: 7.6.1
Install Method: manual, via cpanel file manager
Web Server: godaddy shared hosting
PHP Version: 7.1
Database: MySQL 5.6.43-cll-lve

Screenshot of browser error log: https://yadi.sk/d/i-HxbD_0iu3smg

Thanks for the great app and hope you can help me sort this out.

Anton

**Comment by avshelin** [comment]
UPDATE:

Apparently this bug is related to a particular collection. I have tried creating a many-to-many field in a several different collections and it works. No luck with the original collection though.

**Comment by avshelin** [comment]
UPDATE:

Got the same problem with the same collection when trying to add Files (multiple, M2M) interface.

**Comment by avshelin** [comment]
UPDATE:

I reverted back to my pre-upgrade backups (database + app), and found out that the issue with many-to-many was present in 7.3.0 as well.

**Comment by gustavossilva** [comment]
Check if there is a relation in directus_relations table with your bugged table. If exists try to remove that relation.

**Comment by avshelin** [comment]
gustavossilva, thanks for your suggestion. I have found some relations with older deleted tables to my buggy table. Deleted the ones I did not recognize, and problem was fixed :)

Thanks a lot!

**Comment by gustavossilva** [comment]
Good to know that it worked! This happen when you delete some M2M relation, i think Version 7.5 fixed this issue (i didn't test yet).

**Comment by benhaynes** [comment]
Thank you for helping @gustavossilva! 😄 

I'll close this since it seems to be resolved — we can re-open otherwise.
