### ISSUE TITLE
change required to false on field creation

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1811]
# Feature Request
If creating a new field its currently required by default.
imo it slows down the creation of collections and new fields  very much if all fields are required by default.

## What problem does this feature solve?

Get back the creation speed of new collection as it was a few month before.

Or why have you changed it?

## How do you think this should be implemented?

Adding new field to collection *not required*

## Would you be willing to work on this?

Yes, if approved i can fix it

**Comment by shealavington** [comment]
Might be best to have a server toggle as it's different for everyone.
`Field creation options — { Required: Bool }`

**Comment by benhaynes** [comment]
This seems like another Twitter poll. 😉 I agree with what you're saying, but when creating a form it also seems as though most data should be required and you choose what is optional. It will really depend on your situation.

I'll leave this open for a bit for better visibility... hopefully we can find out which way we want to go since it's an easy change to make.

Alternatively, we _could_ make this a global setting for the default, but that seems like overkill for this.

**Comment by dev7ch** [comment]
ok, yes depends on situation. 

but if i look into `/settings/interfaces/` there is a checkbox to define the required state (plz see pic below).

![image](https://user-images.githubusercontent.com/15183757/60594102-7f73be80-9da4-11e9-8e1d-08133d133b9b.png)


So the current setting (required = true) is an inconsistency, 
if you really want your new field required, then you can set in the `/settings/interfaces`

I would definatlety vote for *required = false* open default, because otherwise your `/settings/interfaces` not make sense.

I hope you understand and see the problem 🙏

**Comment by benhaynes** [comment]
`settings/interfaces` is just a page for testing/viewing/experimenting with interfaces, it doesn't set/change anything in the system. That said, we can update that page to reflect what we choose for the default.

Also, here is the community vote for field's required/optional default... maybe this will help us. And so you know, I voted _optional_ too! 😉 

https://twitter.com/directus/status/1147134730321760257

**Comment by dev7ch** [comment]
oh ok sorry.

mmh i would think if there are options to set the interface settings, it would make sense to use it as default.

Thank you for clarification.
