### ISSUE TITLE
Enable Note field input to be visible on :hover and/or :focus

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1812]
# Feature Request
If links can't be placed and clicked in anchor description in a short description on field input it's almost a bug assume

## What problem does this feature solve?

make the "note" tooltip of the field input usable

## How do you think this should be implemented?
in CSS or JS, simple
## Would you be willing to work on this?

Yes, if approved

**Comment by benhaynes** [comment]
I thought we had a ticket for this, but I can't find it... so I guess we don't. Yes, since notes support links we need to make sure they stay visible/clickable on focus (not just hover).

**Comment by dev7ch** [comment]
i think o found the ticket https://github.com/directus/app/issues/1741
