### ISSUE TITLE
Adding Sortable option to Collections overview

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1813]
# Feature Request

make Collections in Collections Settings sortable.

## What problem does this feature solve?

Sorting of Admin Main nav and rerangeing collections according to importance  

## How do you think this should be implemented?

As its done for checkboxes or the repeater field

## Would you be willing to work on this?

Yes if approved

**Comment by benhaynes** [comment]
If this is only used to re-order items in the navigation, why not just use the Navigation Override feature? This would let you put them into any order, adds the ability to Group them, and adds custom/external link support too.

**Comment by dev7ch** [comment]
Oh, yes probably missed sth. thanks for the fast reply.

It is possible to Override specific NavItem (Collection Name)?

When i was looking into the docs i understood, that i could only rerange Bookmarks or Collection (which are the parent Items)

I am missing sth?

**Comment by benhaynes** [comment]
Hmm, it looks like you can choose any name... so yes:

https://docs.directus.io/guides/roles.html#example

**Comment by benhaynes** [comment]
You can individually add the collections to re-order them... or use the `include collections` helper to add them all in at once (alphabetical).

**Comment by dev7ch** [comment]
ahh ok yes, sorry fo not double check the docs
