### ISSUE TITLE
Translated name of a collection does not appear in page title element

### ISSUE THREAD

**Issue by weaversam8** [directus/app#1814]
If you're using [Internationalization to do schema translations](https://docs.directus.io/guides/i18n.html#schema-translations), the new name for a collection appears displayed on the page and on the sidebar, but not in the HTML page `<title>` element, so the normal name still appears on the title of the window or tab.

![page title](https://user-images.githubusercontent.com/2546219/60596363-db275300-9d76-11e9-8b2a-fd1e43964459.png)

![tab title](https://user-images.githubusercontent.com/2546219/60596398-ee3a2300-9d76-11e9-861a-967df6ee3eea.png)

**Comment by rijkvanzanten** [comment]
This hasn't been implemented yet (feature request https://github.com/directus/app/issues/422). Not sure why it's in the docs.

**Comment by rijkvanzanten** [comment]
Removed it in https://github.com/directus/docs/commit/aa7d429bd8d964d3017fc48af1426cbd7fe6e377#diff-b9af00d27e5c8232b87cc4371a553df2
