### ISSUE TITLE
File doesn't load enough items

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1815]
Bug Report

`/#/files`

At 3840 * 2160 resolution, you can't scroll more loads
Not only at this resolution, but if the current screen can display 50 pieces in full, it can't scroll to display more.

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.1]
- APP Version: [7.6.1]
- Install Method: [cloned `master` branch]

**Comment by benhaynes** [comment]
Increasing the initial item fetch count should solve this, too @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Yeah 👍
