### ISSUE TITLE
Recommended removal of rolling loads

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1816]
# Feature Request

![image](https://user-images.githubusercontent.com/8030134/60619806-09a33d80-9e0c-11e9-8a41-4a2e6fca933a.png)

1、Add Pagination
2、DESC and ASC save to the database or cache
3、Remove the redundant scrollbars in the figure above

## What problem does this feature solve?

1、At present, I need to find a batch of pictures, which can only be found by scrolling and wasting a lot of time. Add paging can help me quickly find the pictures I need.Rolling load is no longer a good solution at the moment. I admit that it can be used in some scenarios, but in more scenarios it has a lot of bad experience problems.
2、DESC and ASC are not saved to the database or local cache, each reload requires a re-selection, bad experience
3、I don't know why there are two scrollbars, which sometimes lead to incomplete picture display.

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Screen resolution: [3840 * 2160]
- Browser: [Chrome 75.0.3770.100 x64]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.1]
- APP Version: [7.6.1]
- Install Method: [cloned `master` branch]

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
