### ISSUE TITLE
Unable to add translations inside a repeater interface field

### ISSUE THREAD

**Issue by lluishi93** [directus/app#1818]
Hi @benhaynes,

I'm having troubles while putting a translation interface field inside a repeater interface field. It shows me an error saying that the interface hasn't been configured correctly. I think it is because the translation language field, but IDK which field I've to point to at that point. I'll leave some screenshots below.

![image](https://user-images.githubusercontent.com/14786440/60717362-dce14a00-9f21-11e9-84e9-cb5bb2d54220.png)

![image](https://user-images.githubusercontent.com/14786440/60717368-e1a5fe00-9f21-11e9-9cd6-281331b9a710.png)

TY and BR

**Comment by rijkvanzanten** [comment]
The language field is the field in the related collection that holds the current language of the translation.

For example:

```
articles
--------
id
featured_image


article_translations
--------------------
id
article_id
language_id [translation language field]


languages   [languages collection]
---------
id          [languages primary key field]
name        [languages name field]
```

**Comment by lluishi93** [comment]
@rijkvanzanten Thanks. I knew that, and it works like a charm outside of the repeater interface. However, once I try to put translations inside a repeater interface, I get the message you see above in the screenshot.

**Comment by rijkvanzanten** [comment]
Ah I see, my bad 👍

**Comment by stalinkay** [comment]
@rijkvanzanten I think this affects other relationships as well, I have tried it with m2o and I get the same message as above.

**Comment by rijkvanzanten** [comment]
The JSON-based repeater does not support relational interfaces. The commit above removes support for setting up relational fields in the repeater interface. While this is not a complete fix for the problem, it does prevent it from happening in the future. Meanwhile, we'll be focussing our efforts on creating a new relationship-based repeater field that has full support for all interfaces Directus has to offer.

**Comment by prikr** [comment]
> The JSON-based repeater does not support relational interfaces. The commit above removes support for setting up relational fields in the repeater interface. While this is not a complete fix for the problem, it does prevent it from happening in the future. Meanwhile, we'll be focussing our efforts on creating a new relationship-based repeater field that has full support for all interfaces Directus has to offer.

Is there any update on this?

**Comment by rijkvanzanten** [comment]
@prikr 9.0.0 will launch with a relational repeater 👍

**Comment by prikr** [comment]
> @prikr 9.0.0 will launch with a relational repeater 👍

Nice! Looking forward to it. Can u say anything about when it will be released?

**Comment by rijkvanzanten** [comment]
Binnenkort! The alpha is already launched on NPM / GitHub: https://github.com/directus/next

Once the last missing pieces are finished, it'll move to beta and RCs soon after 👍

**Comment by Fusseldieb** [comment]
> @prikr 9.0.0 will launch with a relational repeater 👍

Oh wow! Totally looking forward to it 😃
