### ISSUE TITLE
How to add button with action in directus export one collection data on top position?

### ISSUE THREAD

**Issue by avneesh30** [directus/app#1820]
I need a button on direct-us admin UI. on collection top position with an action call for an export data

**Comment by benhaynes** [comment]
Hey @avneesh30 — in the future please be sure to fill out the entire "Feature Request" form so we have as much info as possible.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
