### ISSUE TITLE
First item of One to Many is hidden until second item is added or parent is saved

### ISSUE THREAD

**Issue by mebenhoehta** [directus/app#1825]
# Bug Report

## Steps to Reproduce

1. Create two collections in a parent / child relationship with the parent managing the relation ship (one to many).
2. Add a new item to the parent 
3. Add the first child => it wont be displayed in the list
4. Add a second child to the parent => both children are displayed

This was reproduced on https://www.directus.app  on version API 2.2.1 / APP 7.6.1

## Expected Behavior

the first child added is displayed

## Actual Behavior

The first item is not displayed, when the parent is saved, the child is correctly saved and displayed when the parent is re-opened.

The first child is also displayed when a second child is added (both children are then being displayed)

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/48298451/60791159-6608b300-a1a6-11e9-8a5c-0307709dc3a7.png)

![image](https://user-images.githubusercontent.com/48298451/60791210-7ae54680-a1a6-11e9-9fd7-ff439021afa1.png)

![screenie](https://user-images.githubusercontent.com/48298451/60793304-c4d02b80-a1aa-11e9-98e3-d4d4bd12a4d7.gif)

## Technical Details
browser : FF 60.7.2esr (64-bit) , as well as Chrome 74.0.3729.169

sorry about the crappy screen recording, but the demo site was just reinitialised afterwards :-)

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/pull/1804
