### ISSUE TITLE
M2M relation keeps coming back after delete

### ISSUE THREAD

**Issue by iidroj** [directus/app#1827]
We have a collection "concept" and this collection has a M2M relation with itself. 
![afbeelding](https://user-images.githubusercontent.com/43352430/60802405-16f85900-a179-11e9-8750-0aac4d6097de.png)
When we try to delete a relation of a concept with another concept, sometimes it says it has saved the changes succesfully, but the relation still exists and if you enter the detail screen of the concept item, the relation has reappeared. However this doesn't always happen and some relations can be removed while others can not. 
If we manually remove the relation in the concept_concept collection, the relation is always removed as expected. When we add the same relation again, we have no problem removing it again the normal way.

**Comment by rijkvanzanten** [comment]
Ik snap niet helemaal wat je precies bedoelt @iidroj. Is dit een bug in de M2M interface zelf? Kun je een dump sturen van je database? Kan ook op Slack: [https://directus.chat](https://directus.chat)

**Comment by iidroj** [comment]
in directus (7.0.18) die draait in een docker container hebben wij een collectie die een M2M relatie heeft met zich zelf zoals je op de foto kan zien. deze hebben we ook in de tegenovergestelde richting omdat we anders in de details niet alles konden zien maar dit hebben we in een andere issue al aangegeven. Als we een link willen verwijderen lijkt dit op het eerste zicht wel te lukken in het wijzigingsscherm maar wanneer je het item opslaat komt de relatie er terug bij te staan, ook al krijg je de melding item opgeslagen. de enige manier om deze definitief te verwijderen is door in de tussen tabel de effectieve link te verwijderen. 
de database dump mag dit persoonlijk verstuurd worden op Slack deze willen wij namelijk niet zomaar openlijk prijs geven.

**Comment by rijkvanzanten** [comment]
Ah helder. Kun je checken of het probleem zich ook nog voordoet in de laatste versie? Directus zelf zit al op 7.6.2 intussen 🙂

**Comment by iidroj** [comment]
Als wij op DockerHub kijken dan sta dat de laatste 7.0.18(app) is. hoe moeten wij dat dan testen?

**Comment by bjgajjar** [comment]
Hallo @iidroj 

Het lijkt erop dat u Docker gebruikt. We hebben momenteel geen bijgewerkte versie van Docker. Maar je krijgt binnenkort de nieuwste versie, we zijn er bijna om onze nieuwste versie uit te brengen.

**Comment by bjgajjar** [comment]
As this the issue of older version; I am closing this. Feel free to reopen it.
