### ISSUE TITLE
Files Interface is ignored in API Calls

### ISSUE THREAD

**Issue by autr** [directus/app#1828]
# Bug Report
 
Files Interface does not add anything to API call to Collection, whereas File Interface does

## Steps to Reproduce

** Define Collection **

1. Create new Collection
2. Add text input, ie. _test_new_text_input_
3. Add File input, ie. _test_new_file_
4. Add Files input, ie. _test_new_files_  (autogenerated with _directus_files_)

** Test Collection **

1. Create new item 
2. Test API endpoint
3. API endpoint returns text string and file id, but no files array

## Expected Behavior

API returns array of file ids

## Actual Behavior

API returns no array or object for the field

## Other Context & Screenshots

Permissions settings etc

<img width="664" alt="Screenshot 2019-07-08 at 15 23 08" src="https://user-images.githubusercontent.com/1035590/60813651-79128780-a194-11e9-9034-81a538dcdd99.png">
<img width="686" alt="Screenshot 2019-07-08 at 15 24 08" src="https://user-images.githubusercontent.com/1035590/60813658-79ab1e00-a194-11e9-8bcd-a0936cf12513.png">

## Technical Details

Device: Macbook
OS: macOS 10.13
Web Server: Apache/2.4.39
PHP Version: PHP 7.1
Database: 15.1
Install Method: wget && unzip

**Comment by rijkvanzanten** [comment]
`files` and `many-to-many` fields are – just like `o2m` – ALIAS type fields. They don't store any data themselves and rely on the relationship to return data. Therefore, the "root level" API request doesn't have any data for these fields, as they technically don't exist in the database. `file` however is a many to one style relationship which has an actual field that stores the id of the related file. Therefore, fetching the root level from the api will return the ID.

To fetch the relational items populated nested, use [the `fields` parameter](https://docs.directus.io/api/reference.html#fields-2).

`fields=file` will return only the file field, which will return `{ "file": 1 }` as it only stores the ID. If you want to get the file populated, you can use `fields=file.*` which fetches everything inside file 

`{ "file": { ...fileinfo... } }`

The same applies for relational fields:

`fields=*` will fetch everything on the "root" level, `fields=*.*` will fetch everything on both the root level and the first relational level. This will return the `files` in your case
