### ISSUE TITLE
Support for Custom Batch Actions

### ISSUE THREAD

**Issue by mvhirsch** [directus/app#1829]
# Feature Request

First: I :heart:  Directus! 
I think it's missing a very important feature, that might attract others, too: support for custom batch actions. I know there is a feature for custom actions, but I mean a smooth possibility to select some items in listing view and do something "custom" with them (e.g. sending a mail to a colleague or creating facebook posts, or you name it). Of course such logic must be implemented by myself, but I just want to select them and select which of the batch actions (delete, update, send per mail) I want to execute.

## What problem does this feature solve?

Simply adding new batch actions for custom business-logic is awesome :heart: 

## How do you think this should be implemented?

Like it's already done by using batch delete/update. Just select the items you wish and send them to a specified custom action. I think the only thing needed here, is sending IDs to a custom action and a pretty UI for it.

## Would you be willing to work on this?

Yes on backend. I'm not experienced in vue.js, so I might need help for frontend.

**Comment by rijkvanzanten** [comment]
I've heard requests for this a couple times earlier. Being able to add a custom button in the top right is something people want. I like the idea of being able to configure what buttons show up and what actions the perform. We need to think about what these settings should be. Thinking aloud, we probably need to able to set what URL to hit (eg custom endpoint) and what icon / label / color. We might also want to have some way to inject some custom front-end for this button so we can display things like modals or popups on success.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by mvhirsch** [comment]
@rijkvanzanten exactly! :-)
Is there a way to speed things up, e.g. get in touch with my company?

**Comment by benhaynes** [comment]
Yes, for sponsoring features/fixes you can reach out to RANGER or Directus:

info@rangerstudio.com
support@directus.io

**Comment by rijkvanzanten** [comment]
@mvhirsch The most important thing now is that we spec out exactly how it's supposed to work, including how to inject all the functionality we need (eg do we support sending data to third party services, how do we inject front-end, is this going to be a separate extension type etc etc). Once we have all of that documented, we can pinpoint exactly what needs to be implemented where to make it work 🙂

**Comment by gavinhewitt** [comment]
Laravel Nova has custom actions that I use a lot, so I can only agree that this would be a great feature to have!
