### ISSUE TITLE
Files interface cannot delete files

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1834]
Bug Report

## Steps to Reproduce
1、Creat collection ` blog `,fileds: `title`, `gallery`(files interface)
2、Add an entry (Gallery uploads 2 pictures)
3、Edit this entry,Delete the two pictures under gallery, click `Existing`, select the two pictures just uploaded, and click Save
4、Edit the entry again，Gallery turned into 4 pictures

## Expected Behavior
Files uploaded from the `files interface` can be deleted normally

## Actual Behavior
Unable to delete files uploaded from the files interface

## Other Context & Screenshots

https://streamable.com/360fk

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.2]
- APP Version: [7.6.2]
- Install Method: [cloned `master` branch]

**Comment by benhaynes** [comment]
@cdwmhcc — again, you'll need to include more details in these bug reports. Please follow the GitHub template in the future or we'll be removing these.

**Comment by cdwmhcc** [comment]
> @cdwmhcc — again, you'll need to include more details in these bug reports. Please follow the GitHub template in the future or we'll be removing these.

I think the problem video is easier to understand than the description, so I recorded the above video.

**Comment by benhaynes** [comment]
The video is great, and very helpful. But a text description, steps to reproduce, and expected results are all needed too. Not everyone can watch a video to understand the issue, it uses mobile bandwidth some don't have, and isn't searchable on GitHub.

**Comment by cdwmhcc** [comment]
> The video is great, and very helpful. But a text description, steps to reproduce, and expected results are all needed too. Not everyone can watch a video to understand the issue, it uses mobile bandwidth some don't have, and isn't searchable on GitHub.

I've been thinking about this question for a long time. I don't know how to describe it through translation. I try to describe it. You see, can you understand it?

**Comment by cdwmhcc** [comment]
> The video is great, and very helpful. But a text description, steps to reproduce, and expected results are all needed too. Not everyone can watch a video to understand the issue, it uses mobile bandwidth some don't have, and isn't searchable on GitHub.

Because this problem can only be reproduced after clicking and saving. I don't know how to describe the title correctly. I'm sorry.

**Comment by benhaynes** [comment]
Much better — thanks! 😄

**Comment by urvashithakar** [comment]
Hi @cdwmhcc ,
 I'm not able to reproduce the issue. Can you please update to latest build and try again?

**Comment by cdwmhcc** [comment]
> Hi @cdwmhcc ,
> I'm not able to reproduce the issue. Can you please update to latest build and try again?

I closed this issue many days ago, and I don't know why it reopened.
