### ISSUE TITLE
Can't upload image directly from device

### ISSUE THREAD

**Issue by TruptiKashid** [directus/app#1836]
Steps to  reproduce : 
1)Create collection, with field photo, with file interface
2)Create item in above collection --> try to upload image file from device

It is showing an error --> **Failed generating the sql query** 
While saving item it's showing an error --> **photo : This value should not be blank**

But file is getting uploaded in file library 
Next time when we select same image from file library, it's working fine. We can create item successfully.

**Comment by dev7ch** [comment]
Do you use the `file` or `files` interface?

(could be related thumbnail after upload request, had this several time, `chown -R <server-root-user>:<your-server-group> /var/www/api/` fixed it in the most cases )

**Comment by rijkvanzanten** [comment]
Seems to be working as expected on my end. Please let me know if you still have this issue and we can reopen.
