### ISSUE TITLE
Cannot add new fields

### ISSUE THREAD

**Issue by okayawright** [directus/app#1839]
Please bare with me if this issue is a duplicate but I couldn't find any exact match

One cannot add a new field in a new collection from the APP.

You get an invalid SQL query exception stating that the *id* field is NULL while trying an `INSERT INTO directus_fields`

Apparently it appeared only after 7e8246dd56a22581a78e0edafdf5464fce2fd437

Before that commit, the *id* field was explicitly removed from the list of fields to add, but then that operation disappeared from that commit

See the following GIF for the full description:
![6847618718](https://user-images.githubusercontent.com/1095407/61044069-1a3d5000-a3d8-11e9-94c1-1ab31b83deb8.gif)

**Comment by rijkvanzanten** [comment]
Do you have any custom code running? Is this on MySQL? I don't see this issue on my end or on the live demo(s)

**Comment by bjgajjar** [comment]
Not able to replicate it at my end too

**Comment by rijkvanzanten** [comment]
I'll close this for now. Please let us know if the problem still persists, and we can reopen
