### ISSUE TITLE
M2M relation with string primary keys can not be saved

### ISSUE THREAD

**Issue by vuchl** [directus/app#1840]
Hey Directus team!

I have 2 collections that have string primary keys that are provided through an external system.

When I try to create an M2M relationship in one of the two initial collections that combines the two collections in a junction collection I get an error thtat says: "Failed generating the SQL query."

When I then unhide the junction collection I get the same error trying to setup a manual M2M data row.

We had this in 7.2.0 and it worked. We since then upgraded to 7.6.0 and have this error.

Let me know if I can be of any other help!

**Comment by vuchl** [comment]
@rijkvanzanten is there an targeted release for this?

**Comment by rijkvanzanten** [comment]
Whenever the next version is released, this will be in it. Probably in like a week or two
