### ISSUE TITLE
What is the right item template when using Checkboxes Relational interface?

### ISSUE THREAD

**Issue by JbalTero** [directus/app#1841]
**Item collection**

![image](https://user-images.githubusercontent.com/3615746/61022700-9e440780-a3d9-11e9-94d3-5a0702f31881.png)

**Item template that I have tried**

![image](https://user-images.githubusercontent.com/3615746/61022798-f0852880-a3d9-11e9-937d-77f2bfdb13e6.png)

**This is what I get**

![image](https://user-images.githubusercontent.com/3615746/61022827-072b7f80-a3da-11e9-9b8b-48933b363a00.png)

**Project Members Collection**

![image](https://user-images.githubusercontent.com/3615746/61022729-bae03f80-a3d9-11e9-9e27-06f5539cbd11.png)

**Project Members collection items**

![image](https://user-images.githubusercontent.com/3615746/61022757-d0ee0000-a3d9-11e9-9eda-bae34483d363.png)

Thanks for this wonderful cms guys.

**Comment by shealavington** [comment]
The template doesn't contain the collection name, it will be the related collection's field names, so if I have a related collection of `members` and each member has a `first_name & last_name` then the template could be `{{ lastname_name }}, {{ first_name }}`

Could you let me know if that works?

**Comment by rijkvanzanten** [comment]
We can continue discussing here, but I'm closing the issue as it's not a problem in Directus itself 👍
