### ISSUE TITLE
Visual error when PK doesn't exist.

### ISSUE THREAD

**Issue by shealavington** [directus/app#1842]
# Feature Request
We should have a visual notification or error on-screen inside collections without a Primary-Key.

When you create a collection, if a primary-key doesn't exist, there's no warning that things might break as we've found... https://github.com/directus/api/issues/1102#issuecomment-510379333

## What problem does this feature solve?
Explains to users that things won't work without a PK as we need a reference to hook onto each item.

## How do you think this should be implemented?
if `field type -> primary key` doesn't exist in the collection then display error. 

Should be fairly tidy in Vue.

## Would you be willing to work on this?
Hands are mostly full, but if it's still around sometime when I'm picking for things to do, I can :)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
