### ISSUE TITLE
Repeater file cannot save the correct JSON after uploading the file

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1845]
Bug Report

## Steps to Reproduce
1、Creat collection ` soft`

![image](https://user-images.githubusercontent.com/8030134/61196386-ef693980-a700-11e9-8150-8d79cef5d460.png)

2、Add a soft

![image](https://user-images.githubusercontent.com/8030134/61196659-cd70b680-a702-11e9-8ff4-5a2e061d83b7.png)

3、Save

4、Edit this soft, See it

![image](https://user-images.githubusercontent.com/8030134/61196695-014bdc00-a703-11e9-8836-e2f08961f402.png)

## Expected Behavior

Let it work. ( I tried version 7.60 and it worked.Hope to be repaired)

## Actual Behavior

Repeater file cannot save the correct JSON after uploading the file，
I looked at the returned data and returned only the `file id`, but no other data.

![image](https://user-images.githubusercontent.com/8030134/61196848-00677a00-a704-11e9-9513-97abd88edac2.png)

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.2]
- APP Version: [7.6.2]
- Install Method: [cloned `master` branch]

**Comment by vuchl** [comment]
I am having the same issue.

I query the collection publicly and have read permissions on the `Files` collection
![image](https://user-images.githubusercontent.com/4921147/61861201-a74dd200-aecb-11e9-97c3-9e4b5645bb45.png)

even ecplicitly resolving the image data is not working like so:
`?fields=collection.repeater.image.*`

**Comment by MilanPalSingh** [comment]
similar issue https://github.com/directus/app/issues/1826

**Comment by brocgailit** [comment]
I can confirm this is still an issue on version 7.9.0 as well and application critical.

**Comment by rijkvanzanten** [comment]
The JSON-based repeater does not support relational interfaces. The commit above removes support for setting up relational fields in the repeater interface. While this is not a complete fix for the problem, it does prevent it from happening in the future. Meanwhile, we'll be focussing our efforts on creating a new relationship-based repeater field that has full support for all interfaces Directus has to offer.
