### ISSUE TITLE
Many-to-one, item select modal is not sorted

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1846]
# Feature Request

![image](https://user-images.githubusercontent.com/8030134/61196930-7b309500-a704-11e9-9f2f-8a4aeae74a08.png)

![image](https://user-images.githubusercontent.com/8030134/61196994-dc586880-a704-11e9-8740-4e7f226d4569.png)

## What problem does this feature solve?

Can let me quickly find the categories I need. (The version before May is OK. The new version revises it.)

## How do you think this should be implemented?

![image](https://user-images.githubusercontent.com/8030134/61196994-dc586880-a704-11e9-8740-4e7f226d4569.png)

**Comment by rijkvanzanten** [comment]
The Visible Fields option controls this:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/9141017/61222546-e79d9b00-a6e8-11e9-8fdb-ad98f33e3b43.png">

This will make the `sort` column show up in the modal.

**Comment by cdwmhcc** [comment]
> The Visible Fields option controls this:
> 
> <img alt="image" width="437" src="https://user-images.githubusercontent.com/9141017/61222546-e79d9b00-a6e8-11e9-8fdb-ad98f33e3b43.png">
> 
> This will make the `sort` column show up in the modal.

Thank you very much!
