### ISSUE TITLE
Automated Acceptance Test Suite

### ISSUE THREAD

**Issue by chintohere** [directus/app#1852]
# Feature Request
Open Source automated test suite for directus app and api combination.

## What problem does this feature solve?
Every time there has been a new release, we see the release fixed some important issues. But we have also some core features broken in the latest release. The situation has blocked us from upgrading since 7.2.0

e.g. https://github.com/directus/app/issues/1825

## How do you think this should be implemented?
We should have an automated acceptance test suite which would be run before each release is cut. If one exists internally already, open-source it so that others can contribute to it.

This will generally start lifting the quality of the stable releases.

## Would you be willing to work on this?
Yes

**Comment by benhaynes** [comment]
Thanks @chintohere — this is a great feature to add!

We have input/output tests being built now for the API (thanks @shealavington! ❤️) which will be a big help. As for the App, my understanding of the testing needed here makes me think we should wait a bit on this. 

We're about to make some pretty large structural changes to the App code/UI in the next few weeks/months... and I don't want to waste anyone's time by breaking the end-to-end testing.

Does that sound appropriate to you?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
