### ISSUE TITLE
Repeater does not work in a collection

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1861]
Bug Report

## Steps to Reproduce
1、Creat collection ` soft`
![image](https://user-images.githubusercontent.com/8030134/61196386-ef693980-a700-11e9-8150-8d79cef5d460.png)

2、Add a soft see it
![image](https://user-images.githubusercontent.com/8030134/61402878-9cf96a00-a906-11e9-98c9-632c50557119.png)

V7.6.0 is working

![image](https://user-images.githubusercontent.com/8030134/61402921-bef2ec80-a906-11e9-8627-79a4c5a9eb6e.png)

## Expected Behavior
Repeater does not work in a collection

## Actual Behavior
Fix it

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3]
- APP Version: [7.7]
- Install Method: [cloned `master` branch]

**Comment by Nitwel** [comment]
I've tested it in the public directus app and it all seems to work fine.
Can you give us more detail about what the error might be or how you configured the fields?

![grafik](https://user-images.githubusercontent.com/22577866/61441150-4d865e80-a945-11e9-8ac0-62b594c0296c.png)

**Comment by cdwmhcc** [comment]
> I've tested it in the public directus app and it all seems to work fine.
> Can you give us more detail about what the error might be or how you configured the fields?
> 
> ![grafik](https://user-images.githubusercontent.com/22577866/61441150-4d865e80-a945-11e9-8ac0-62b594c0296c.png)

It work!

**Comment by justrealmilk** [comment]
What did you do to fix it?

![image](https://user-images.githubusercontent.com/156681/61600892-6ad56880-ac76-11e9-893c-de14d3d30b83.png)
Image 1

![image](https://user-images.githubusercontent.com/156681/61600898-732da380-ac76-11e9-9ddd-5482ae6a9b11.png)
Image 2

Should Data Type be set to Object?

![image](https://user-images.githubusercontent.com/156681/61600931-8c365480-ac76-11e9-9d9b-375174df7fc4.png)
...
![image](https://user-images.githubusercontent.com/156681/61600936-96f0e980-ac76-11e9-8926-8fbd230062c5.png)
Image 3

Is it necessary to explicitly specify the Type value?

**Comment by justrealmilk** [comment]
The error in dev tools:

![image](https://user-images.githubusercontent.com/156681/61601228-de2baa00-ac77-11e9-926a-113def6808ad.png)

https://github.com/directus/app/blob/bd2ba381d230a5e99114e389cad9c1a347f8f61d/src/components/form/field.vue#L128

**Comment by cdwmhcc** [comment]
> The error in dev tools:
> 
> ![image](https://user-images.githubusercontent.com/156681/61601228-de2baa00-ac77-11e9-926a-113def6808ad.png)
> 
> https://github.com/directus/app/blob/bd2ba381d230a5e99114e389cad9c1a347f8f61d/src/components/form/field.vue#L128

I use app v7.7.0,https://github.com/directus/app/releases/tag/v7.7.0
It works.

**Comment by justrealmilk** [comment]
> > The error in dev tools:
> > ![image](https://user-images.githubusercontent.com/156681/61601228-de2baa00-ac77-11e9-926a-113def6808ad.png)
> > https://github.com/directus/app/blob/bd2ba381d230a5e99114e389cad9c1a347f8f61d/src/components/form/field.vue#L128
> 
> I use app v7.7.0,https://github.com/directus/app/releases/tag/v7.7.0
> It works.

I also use 7.7.0. It doesn't work. 😭

**Comment by cdwmhcc** [comment]
@Nitwel

**Comment by Nitwel** [comment]
Did you made sure that the type value (at th bottom of the repeater config) of your configuration is set properly?

**Comment by justrealmilk** [comment]
> Did you made sure that the type value (at th bottom of the repeater config) of your configuration is set properly?

![image](https://user-images.githubusercontent.com/156681/61625414-0211de80-acbe-11e9-9341-71c1f70059d4.png)

**Comment by cdwmhcc** [comment]
@justrealmilk 
> https://streamable.com/injha
What he wants to see is the settings in the video.

**Comment by Nitwel** [comment]
I meant the fields config in the section `options`. *

**Comment by justrealmilk** [comment]
They match what other interfaces set them to by default i.e. string, json, string, string respectively

**Comment by rijkvanzanten** [comment]
@justrealmilk do you have a relational field in the repeater?

**Comment by justrealmilk** [comment]
@rijkvanzanten a files selector

**Comment by justrealmilk** [comment]
here's the field as per directus_fields

```
{
  "dataType":"object",
  "limit":0,
  "buttonText":"Add block",
  "fields":{
     "markdown":{
        "field":"markdown",
        "interface":"markdown",
        "options":null,
        "type":"String",
        "preview":null,
        "index":null
     },
     "files":{
        "field":"files",
        "interface":"files",
        "options":null,
        "type":"O2M",
        "preview":null,
        "index":null
     },
     "code":{
        "field":"code",
        "interface":"code",
        "options":{
           "language":"text\/javascript"
        },
        "type":"String",
        "preview":null,
        "index":null
     },
     "github":{
        "field":"github",
        "interface":"text-input",
        "options":{
           "iconLeft":"code"
        },
        "type":"String",
        "preview":null,
        "index":null
     }
  }
}
```

**Comment by justrealmilk** [comment]
I don't want to get ahead of myself here, but is this at all to do with the fact that the Repeater hasn't allowed me to specify any relationships for the O2M field?

**Comment by rijkvanzanten** [comment]
> but is this at all to do with the fact that the Repeater hasn't allowed me to specify any relationships for the O2M field?

That's exactly right

**Comment by cdwmhcc** [comment]
> I don't want to get ahead of myself here, but is this at all to do with the fact that the Repeater hasn't allowed me to specify any relationships for the O2M field?

You can try 7.6.0.
https://github.com/directus/app/releases/tag/v7.6.0

**Comment by justrealmilk** [comment]
> > but is this at all to do with the fact that the Repeater hasn't allowed me to specify any relationships for the O2M field?
> 
> That's exactly right

Does this mean the Repeater interface doesn't support relationship-dependant interfaces yet?

**Comment by rijkvanzanten** [comment]
We need to add an additional field to the interface options of the repeater that allows you to set the relationship. So for now, you're right @justrealmilk

**Comment by rijkvanzanten** [comment]
The JSON-based repeater does not support relational interfaces. The commit above removes support for setting up relational fields in the repeater interface. While this is not a complete fix for the problem, it does prevent it from happening in the future. Meanwhile, we'll be focussing our efforts on creating a new relationship-based repeater field that has full support for all interfaces Directus has to offer.
