### ISSUE TITLE
It was not found in the File Library after successful video upload.

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1862]
Bug Report

## Steps to Reproduce
1、Go to File Library ` /#/files`
2、Upload a video
3、It cannot be found in the `File Library` after successful upload

## Expected Behavior

I use S3,It was not found in the file list after successful video upload.

## Actual Behavior
Fix it

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3]
- APP Version: [7.7]
- Install Method: [cloned `master` branch]

**Comment by benhaynes** [comment]
I just uploaded a file to the demo with no problems. This is either a configuration issue, or more details need to be added to the ticket so that it is reproducible.

**Comment by cdwmhcc** [comment]
> I just uploaded a file to the demo with no problems. This is either a configuration issue, or more details need to be added to the ticket so that it is reproducible.
> 
> https://directus.app/#/files

![image](https://user-images.githubusercontent.com/8030134/61535504-098a7b00-aa65-11e9-9e82-853f127ba367.png)

![image](https://user-images.githubusercontent.com/8030134/61535525-17400080-aa65-11e9-9f09-c21192196abc.png)

**Comment by cdwmhcc** [comment]
https://github.com/cdwmhcc/public/blob/master/123.mp4?raw=true
You can download and upload this MP4 for a try.

**Comment by rijkvanzanten** [comment]
Did you get any errors in the API logs or errors anywhere in general @cdwmhcc?

**Comment by cdwmhcc** [comment]
> Did you get any errors in the API logs or errors anywhere in general @cdwmhcc?

![image](https://user-images.githubusercontent.com/8030134/61542869-f8496a80-aa74-11e9-9920-d6ef004555eb.png)

https://github.com/cdwmhcc/public/blob/master/error.2019-07-19.log

**Comment by cdwmhcc** [comment]
> Did you get any errors in the API logs or errors anywhere in general @cdwmhcc?
@rijkvanzanten 

https://streamable.com/1fvex

https://github.com/cdwmhcc/public/blob/master/error.2019-07-19%20(1).log

**Comment by rijkvanzanten** [comment]
> [2019-07-19 23:13:11] api[_].ERROR: Directus\Filesystem\Exception\ForbiddenException: No permission to write: 4f3bb0d9-8cd3-5fae-b458-58f8982c5ab3.mp4 in /www/wwwroot/directus/src/core/Directus/Filesystem/Filesystem.php:56

I think you've made a mistake in your S3 configuration. It seems like whatever credentials you use in the config file in directus doesn't have write access to S3. Please check the IAM settings in AWS

**Comment by cdwmhcc** [comment]
> Did you get any errors in the API logs or errors anywhere in general @cdwmhcc?

When I upload MP4 less than 10M, it's OK.

https://streamable.com/c1230

**Comment by rijkvanzanten** [comment]
I'm afraid we can't help you any further with this, as it's a configuration problem on your specific S3 instance..
