### ISSUE TITLE
Markdown Editor Pastes Pictures Upload Automatically

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1863]
# Feature Request

Is it possible to paste pictures and upload them automatically like github?

## What problem does this feature solve?
When adding an article, you need to upload the picture first, then get the link of the picture, then copy it, and then enter the image insertion code of markdown, which is very troublesome.

## How do you think this should be implemented?
Is it possible to paste pictures and upload them automatically like github?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
