### ISSUE TITLE
O2M Select Existing Not working

### ISSUE THREAD

**Issue by bjgajjar** [directus/app#1865]
# Bug Report

I have a collection `sections` which have many `cards`. When I tried to select existing `cards`  for `section` the popup is not displaying the existing data of `cards` and console have some `Vue` error.

## Steps to Reproduce

1. Go to `O2M` collection
2. Click on 'Select Existing' for adding `O2M` field
3. Popup will not display the existing data and some `Vue` errors appear in the console.

## Expected Behavior

It must display the list of `M2O` data. 

## Actual Behavior
 Popup will not display the existing data and some `Vue` errors appear in the console.

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/19200178/61514890-bbeb1f80-aa1e-11e9-9efd-49f89246f9b1.png)

**Comment by rijkvanzanten** [comment]
I just tried this on the live demo with a new o2m field on the theaters collection (to kiosks) and everything seems to be working as expected.

**Comment by theharshin** [comment]
I can reproduce this issue. PR for the issue is on the way 🏎
