### ISSUE TITLE
M2M field is not visible for reverse relation.

### ISSUE THREAD

**Issue by bjgajjar** [directus/app#1866]
# Feature Request
`category` collection has `M2M` field for `files` collection. The listing API returns the `file` object for `category` collection, but will not return the `category` object for `files` collection.

## What problem does this feature solve?
`files` collection must have the `category` object too.

**Comment by rijkvanzanten** [comment]
The biggest difficulty is coming up with the generated name for the alias field on the related collection. For example, in a `category` collection, I would normally call the m2m field `categories`, as it's returning multiple items. However, the application won't be able to accurately generate these plural forms for collections.
