### ISSUE TITLE
SSO sessions are not persistent

### ISSUE THREAD

**Issue by ivansf** [directus/app#1867]
I'm trying to use SSO on my organization and while the configuration works and I'm able to authenticate, after a few minutes the app takes me back to the login screen without an error message.

**Behaviour:**
Using SSO the App takes me back to the login screen after a few minutes
Using SSO and hitting Refresh in the browser, the app logs the user out and is taken back to the login screen.

**Setup:**
SSO: Okta and Azure (we built a custom provider)
App: 7.6.2
API: 2.2.0

When I authenticate user X via user/password the app creates a `window.sessionStorage` object, which gets refreshed after the minutes specified under `tokenExpiryTime` in the App, but when I use SSO with the same user X (regardless of Azure or Okta) `window.sessionStorage` is empty:

```
Storage {length: 0}
length: 0__proto__: Storage
```

**Comment by benhaynes** [comment]
Thanks @ivansf — we'll look into this asap (this week).

**Comment by ivansf** [comment]
@benhaynes do you have an idea of when this will be worked?

Thanks again!

**Comment by benhaynes** [comment]
It's on the list. Some of our staff was off this week... hopefully next week we can get this resolved. Sound good @directus/app-team ?

**Comment by theharshin** [comment]
@rijkvanzanten  Looks like the SSO Login is not handled by SDK and hence the auto refreshing of the token is not implemented. Should we handle the SSO login within SDK?

Also I need to check with the API if the endpoint for refreshing SSO tokens is available or not. @bjgajjar can you confirm this?

**Comment by rijkvanzanten** [comment]
See https://github.com/directus/sdk-js/issues/100

**Comment by rijkvanzanten** [comment]
Also @theharshin, the SSO flow in the API ends with a regular API token, which can be refreshed using the regular refresh flow. The issue here is that the token that the SSO flow generates is being injected into the SDK by the app, which skips the SDKs methods for keeping the token alive

**Comment by theharshin** [comment]
@rijkvanzanten Okay, so should I update the SDK and send PR or we should wait as the new auth flow is being discussed?

**Comment by rijkvanzanten** [comment]
This has been resolved in v8
