### ISSUE TITLE
Prevent accidental dialog closes

### ISSUE THREAD

**Issue by justrealmilk** [directus/app#1869]
# Feature Request

Add confirmation dialog for closing interface modal

## What problem does this feature solve?

Accidentally closing the interface modal when you haven't had enough coffee and you're midway through configuring a complex repeater interface

## How do you think this should be implemented?

A confirmation dialog or disable the click outside the dialog to close dialog thing.

If implementing a confirmation dialog is too hard, you could always add an option to Settings instead that just disables the click outside dialog functionality altogether.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
