### ISSUE TITLE
Problem with avatar in list view

### ISSUE THREAD

**Issue by alrick** [directus/app#1871]
Directus versions : latest api and app as of 22 july 2019

When I browse a collection and the created_by or modified_by field is displayed, I'm flooded by error messages in the javascript console.

The message differs from browser to browser :
Firefox : `TypeError: "this.userInfo.avatar.data is undefined"`
Brave (Chrome) : `TypeError: Cannot read property 'thumbnails' of undefined`

More info :
When those fields are displayed, i can't remove them from the view via the menu "i" > "Fields", I get an error message and the fields are still there even if I reload the page and I have to disable the fields via the database "directus_collection_presets" table.

Let me know if you need more information.

**Comment by alrick** [comment]
As I see you set this as low priority, I just wanna add that it causes heavy latency and the admin is basically unusable for users with _created_by_ or _modified_by_ fields enabled in the list view.

**Comment by rijkvanzanten** [comment]
I think https://github.com/directus/app/pull/1868 should take care of the latency problem that that causes @alrick. Mind taking that PR for a spin to confirm?

**Comment by rijkvanzanten** [comment]
BTW, this error is not what specifically causes the latency, the latency is caused by the fact that the user is fetched + it's own relationships, causing the app to load a huge amount of data.

**Comment by alrick** [comment]
@rijkvanzanten it seems the js code is now chunked for the app, is that new ? Not sure how to easily test the PR on my server ?

**Comment by bjgajjar** [comment]
@rijkvanzanten 

I checked that. #1868 will resolve this issue. :)

**Comment by alrick** [comment]
@bjgajjar It seems the files are not the same on a production server unfortunately or am I missing something ?

**Comment by rijkvanzanten** [comment]
> Not sure how to easily test the PR on my server ?

I don't know how you set everything up, but you can clone the fork, checkout the PR branch, build the app `npm install && npm run build` and upload that.

However, @bjgajjar confirmed the changes, and I'm going to release a new patch version today, so you could also wait and update your instance normally 🙂

**Comment by alrick** [comment]
Thanks for the info !

Waiting for the new patch seems easier indeed 😄  I've roll-backed to a previous version in the meantime anyway.

**Comment by andrewksimon** [comment]
I've noticed the same issue in the Avatar view as well.

![image](https://user-images.githubusercontent.com/24998798/62666549-d9424800-b951-11e9-9537-0784cfbe8ecb.png)

![image](https://user-images.githubusercontent.com/24998798/62666619-232b2e00-b952-11e9-9711-e367a93727a0.png)

**Technical Details:**
- Device: [Chrome Desktop]
- OS: [Windows 10.1803]
- Web Server: [Nginx:1.10.3]
- PHP Version: [7.3.8]
- API Version: [2.3.1]
- APP Version: [7.8.0]

**Comment by benhaynes** [comment]
@andrewksimon — have you tried updating to the latest version? We've made a lot of fixes since yours...

**Comment by andrewksimon** [comment]
@benhaynes  - I had updated last night to 190807A; As soon as #1947 is figured out, I'll double check this later.
