### ISSUE TITLE
Search box suggests adding margin value

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1872]
# Feature Request
![image](https://user-images.githubusercontent.com/8030134/61651449-7d888580-ace8-11e9-89bc-7551f8012783.png)

![image](https://user-images.githubusercontent.com/8030134/61651483-8b3e0b00-ace8-11e9-81f5-28345aad4725.png)

## What problem does this feature solve?
Look better

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
