### ISSUE TITLE
Recommended to delete redundant scrollbars

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1873]
# Feature Request
![image](https://user-images.githubusercontent.com/8030134/61651627-d48e5a80-ace8-11e9-9a3d-cc83a711a5a0.png)

![image](https://user-images.githubusercontent.com/8030134/61651849-51213900-ace9-11e9-9ead-2e2623f53096.png)

## What problem does this feature solve?
Look better

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
