### ISSUE TITLE
The O2M collection is invalid after being saved

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1877]
Bug Report

## Steps to Reproduce
1、Creat collection ` soft`, `soft_necessary`

![image](https://user-images.githubusercontent.com/8030134/61780672-820e8480-ae35-11e9-8faa-9b57f0ea6b35.png)

2、Add some items to collection ` soft`, `soft_necessary`

3、Edit the item of the collection `soft_necessary`, and select softs

4、When saved, you will find that this item does not add any softs

## Expected Behavior
Items can be saved.
Optimizing preservation speed

## Actual Behavior

O2M no items were selected after saving
Preservation speed is very slow

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.0]
- APP Version: [7.7.0]
- Install Method: [cloned `master` branch]

**Comment by cdwmhcc** [comment]
I'm not sure if it's a BUG. I set it up according to the document.
I've tried to set the soft > necessity interface to number type, and it doesn't work either.
I asked the people I could ask, but I didn't respond.

**Comment by rijkvanzanten** [comment]
Closing this in favor of https://github.com/directus/app/issues/1899

**Comment by cdwmhcc** [comment]
@rijkvanzanten 

The speed is still very slow. If you select more than one, there will be Network Error.
I use `git clone -b develop https://github.com/directus/app`

https://streamable.com/rn84q

**Comment by benhaynes** [comment]
Hey @cdwmhcc — if these are new errors or performance issues you should create a new ticket and reference this one.

**Comment by cdwmhcc** [comment]
> Hey @cdwmhcc — if these are new errors or performance issues you should create a new ticket and reference this one.

I think it's still within the scope of this issue. Haha
