### ISSUE TITLE
After using the Autoenerate tool of the "Files" Field type Directus will show an Error

### ISSUE THREAD

**Issue by edenprojectde** [directus/app#1878]
![image](https://user-images.githubusercontent.com/6115966/61786759-b4f15200-ae0e-11e9-91a7-770d8cfff76b.png)

This Error completly breaks Directus for me.
I can connect to the backend with an alt-account but only after i refresh the page once. 
The error is shown after loging in with the alt-account but only on first page load. Refresh removes the error.

OS: Ubuntu
Browser: Chrome
Server Stack: NGINX / PHP 7.3
Directus: v7.7.0

**Steps to reproduce**:
Create a "Files" field, while doing so with the Auto-Generate Option.

---

To get out of the completly broken State:
Remove all traces of the relations, database and logs.
E.g.
```
UPDATE directus_users SET last_page='/settings' WHERE id=[YOURUSERID];
DROP TABLE [TABLENAME];
DROP TABLE [RELATEDTABLENAME];
DELETE FROM directus_fields WHERE collection='[TABLENAME]' OR collection='[RELATEDTABLENAME]';
DELETE FROM directus_collections WHERE collection='[TABLENAME]' OR collection='[RELATEDTABLENAME]';
DELETE FROM directus_activity WHERE id>=268;
```
Followed by:
`./bin/directus db:upgrade`
which should fix the issue. I hope i didnt miss any steps to fix, just go around the Database and really cleanly delete any traces of the Table relations. 
Should be easy with phpmyadmin, which i don't use. Hence why i am not 100% sure what fixed it, but db:update/db update from the site needs to be done after whatever fixed the problem.

The Error now randomly occurs even in other instances. I can't really pinpoint the Problem anymore.

**Comment by cdwmhcc** [comment]
I also have this problem.
When I changed the language, it appeared.
You need to refresh the page several times before you can enter, then switch the language back to en, and it works.

**Comment by rijkvanzanten** [comment]
This is fixed in https://github.com/directus/app/pull/1880
