### ISSUE TITLE
Add "Other" option to Dropdown Interfae

### ISSUE THREAD

**Issue by bjgajjar** [directus/app#1885]
We need an interface option "Other" for Dropdown that allows the user to type another value into a text input.

**Comment by benhaynes** [comment]
While we usually close Feature Requests — let's leave this open for a bit for visibility. We'll need to add this option in (shouldn't take more than 30m or so) so the API password feature is complete.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
The `v-select` core component that’s used by the dropdown interface already has an other prop that allows you to provide your own value. Adding support for allow-other in the interface would mean:
• Adding the option to the meta.json file of the dropdown interface
• Passing the value of that option to the v-select in the `input.vue` file of the dropdown interface ( `:other="options.allowOther"` )

**Comment by ozcanoguz** [comment]
Hello  @rijkvanzanten ,

I've tried to do it with your instructions but i think your comment is invalid here. Tried to achieve this via : 

Adapted "src\interfaces\dropdown\input.vue"
```
<v-select
    v-else
    :id="name"
    :value="value"
    :disabled="readonly"
    :options="choices"
    :placeholder="options.placeholder"
    :icon="options.icon"
    :other="options.allowOther"
    @input="$emit('input', $event)"
  ></v-select>
```
and
"src\interfaces\dropdown\meta.json"
```
"allow_other": {
      "name": "$t:allow_other",
      "comment": "$t:allow_other_comment",
      "interface": "toggle",
      "default": false
    }
```

Add options option has been shown in collection creation, but widget itself does not allow to add. Additionally i've found this SO entry that mentions v-select does not allow that option :
https://stackoverflow.com/questions/49323169/input-custom-text-into-v-select
Vue documentation offers to use "taggable" "multiple" 
https://vue-select.org/guide/values.html#tagging

**Comment by rijkvanzanten** [comment]
The problem here is that you use `options.allowOther` in `input.vue`, but `allow_other` in the meta.json 🙂 

Either rename `allow_other` in meta.json to `allowOther`, or use `options.allow_other` in `input.vue`.

**Comment by ozcanoguz** [comment]
Hello @rijkvanzanten , thanks for feedback! Bad typo :)

Step by step, i am achieving goal and understanding better, thanks for your support. But i have one more question, currently user can easily adapt free field for dropdown, but when user tries to check it to edit on collection page, value is shown empty...

on "src\interfaces\dropdown\display.vue" i've adapted that part to show values on collections:
```
    displayValue() {
      //console.warn("oguzdisplayvalue" + this.value);
      if (this.options.formatting) {
        if (this.choices[this.value]) {
          return this.choices[this.value];
        } else {
          return this.value;
        }
      }
      return this.value;
    }
```
Result is sucessfull, "field3" is shown correctly:
https://imgur.com/dxrDFRP
Let's try to edit that collection item, this time value is shown empty:
https://imgur.com/wBcBlJY

Available values:
https://imgur.com/97Vv1iX

Which part i am missing here ?
