### ISSUE TITLE
Column headers disappear and column widths unresponsive when adjusting colum witdh

### ISSUE THREAD

**Issue by usbpaul** [directus/app#1887]
Hi,

This appears to be identical to what was reported in [#1103 (Collection column sizes)](https://github.com/directus/app/issues/1103). Issue [#581](https://github.com/directus/app/issues/581) was going to be a solution for this but was closed.   

Dragging the separator between two column headers in order to change the width of a column causes the column header name to disappear and the column width cannot be altered anymore.

Device: Dell desktop pc (Precision Tower 3420)
Browser used: Chrome  75.0.3770.142
OS: Windows 10 Pro, version 1803.
Directus app: 7.0.0

![columnwidth-problem1](https://user-images.githubusercontent.com/512878/61864376-9dc76880-aed1-11e9-8b93-0ca11e506200.png)

The `view_options` field of `directus_collection_presets` afterwards contains:
```
{"tabular":{"widths":{"id":-1805,"status":-1604,"created_by":-1799,"created_on":-3887,"modified_by":200,"modified_on":-1841,"website":200,"name":200,"content":200,"page":200}}}
```

**Comment by rijkvanzanten** [comment]
> Directus app: 7.0.0

Can you reproduce this on the latest version (v7.7.0 at time of writing)

**Comment by usbpaul** [comment]
I'm running directus in a Docker container and I actually run version 7.0.18 of the app now, so sorry for the misinformation (I said 7.0.0).
When I look at the directus/app page on hub.docker.com, I see 7.0.18 as the latest version for directus/app. Can you advise on how to update to v7.7.0 please?

**Comment by benhaynes** [comment]
Our docker refactor is still in the works, @WoLfulus has said it will be ready at the end of this week. After that, we'll have it pulling the latest version again.

**Comment by usbpaul** [comment]
Looking at the [directus docker tags](https://hub.docker.com/r/directus/app/tags), I still see the 7.0.18 tag as the most recent one. Is there any new information on this?

**Comment by benhaynes** [comment]
Stay tuned... should be good to go in the next day or so. It might even be ready now! :)

We're working on them now!

**Comment by usbpaul** [comment]
There are some new [docker tags](https://hub.docker.com/r/directus/app/tags) now, but the base-apache-0 one does not seem to contain a directus app.  
Running it results in 

```
Attaching to locdirectusapp_app_1
app_1  | Application files not found.
app_1  | Updating ownership...
app_1  | stat: cannot stat '/var/www/public': No such file or directory
```


Looking at the [Dockerfile for base/app/apache](https://github.com/directus/docker/blob/master/images/base/app/apache/Dockerfile), it seems that something is should be copied to /var/www but there is only an empty html directory in the running container.  
Also, where the previous tags were about 10MB, this one seems to be a full apache server image of 199MB. Is this expected?
