### ISSUE TITLE
Displaying fields of sub-related collections for M2O interface

### ISSUE THREAD

**Issue by romaiiinnn** [directus/app#1894]
### Issue Description
In the **Many-to-One field interface**, it seems there is an issue to display fields of related collection that have also a Many-to-One interface.

In my example below, Match collection has a **M2O field Group**, and I would like to display in this interface something like : "round.name / name"
(where Round is a M2O interface in Group)
It is partially broken in the dropdown view, and doesn't show up at all in other views (listing or modal).

### See pictures

![Capture d’écran, le 2019-07-29 à 22 49 41](https://user-images.githubusercontent.com/45723322/62097739-e7a7aa00-b255-11e9-8136-548b77082d8d.png)

![Capture d’écran, le 2019-07-29 à 22 47 38](https://user-images.githubusercontent.com/45723322/62097750-efffe500-b255-11e9-9dbd-e8945dc94901.png)

![Capture d’écran, le 2019-07-29 à 22 49 00](https://user-images.githubusercontent.com/45723322/62097781-0c038680-b256-11e9-99e4-4e28e7116f42.png)

![Capture d’écran, le 2019-07-29 à 22 48 04](https://user-images.githubusercontent.com/45723322/62097794-158cee80-b256-11e9-8b54-8a3dfb837abd.png)

![Capture d’écran, le 2019-07-29 à 22 48 21](https://user-images.githubusercontent.com/45723322/62097798-1a51a280-b256-11e9-93f6-600a23e861e7.png)

### Technical details
Directus API 2.3.1
Directus App 7.8.0

**Comment by rijkvanzanten** [comment]
The M2O only fetches the related data on the root level, it doesn't support this style of showing the related data of a related item (yet). I'm converting this to a feature request to get this implemented instead

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
