### ISSUE TITLE
String Primary Keys throw Error on PATCH

### ISSUE THREAD

**Issue by jonBitgood** [directus/app#1897]
When a collection has a primary key and an entry in that collection is updated. The app doesn't  send the primary key with the patch request and since it's required it throws a validation error. 

`id: This value should not be blank.`

**Comment by bjgajjar** [comment]
@rijkvanzanten 

It's an `API` issue, not an `APP` one; which is resolved in https://github.com/directus/api/pull/1166. You can close this :)

**Comment by benhaynes** [comment]
Thank you @bjgajjar! 😄
