### ISSUE TITLE
Dynamic Images error 404

### ISSUE THREAD

**Issue by alextomas** [directus/app#1898]
Hi!

I upload an image to collection, but the thumb don't exist on url http://my_url/thumbnail/_/200/200/crop/good/image_example.jpg

Can you helpme?

**Comment by benhaynes** [comment]
Hey @alextomas — you'd need to be a bit more specific for us to help. Can you include your server details, Directus versions, and exact steps to reproduce the problem?

I'll close this in the meantime.
