### ISSUE TITLE
Keyboard input into date/time field is awkward

### ISSUE THREAD

**Issue by usbpaul** [directus/app#1904]
Hi,

Our content type newsitem has a field 'start' with Datetime interface.
When I change the date and time in a field that already has a date and time filled in, using the keyboard, typing in the date/time I want results in a different date/time in the control.

Expected result: having the value 12/15/2018 09:10:00 AM in the date field.
Actual result: the value is 08/01/2002 09:00:00 PM

Steps to reproduce:
(The field contains **09/01/2019 12:30:00 PM** to begin with (mm/dd/yyyy --:--:-- --).)
I want to enter a new date time **12/15/2018 09:10:00 AM**.
Click on 09 to start entering the month 12.
Result after this step: 02/01/2019 12:30:00 PM
Type the tab character to move to the day-of-month field and type in 15
Result after this step: 02/15/2019 12:30:00 PM
Type the tab character to move to the year field and type in 2018. This progressively alters the mm and dd fields too. Split into 4 sub steps the results of entering the year digits are:
02/02/2015 12:30:00 PM
02/02/0000 12:30:00 PM
01/02/2002 12:30:00 PM
08/01/2002 12:30:00 PM
Type the tab character to move to the hour field and type in 09
Type the tab character to move to the minutes field and type in 10
Result after this step: 08/01/2002 09:00:00 PM
Seconds and AM/PM work as expected

Using the up/down arrow keys to change each date field works as expected and using the datepicker too.

Device: Dell desktop pc (Precision Tower 3420)
Browser used: Chrome 75.0.3770.142
OS: Windows 10 Pro, version 1803.
Directus app: 7.0.18 (running in Docker)

**Comment by benhaynes** [comment]
Again, let's retest in a current version (7.0.18 is already 6 months old) to see if this is still happening.

**Comment by bjgajjar** [comment]
@usbpaul - This issue is not reproducible in the latest version; So I am closing this. Feel free to reopen it.

**Comment by benhaynes** [comment]
As of right now, this interface seems to just use a standard input. So there are no issues editing with the keyboard. Although I would like to see this have an option to be a masked field.

**Comment by rijkvanzanten** [comment]
It is a masked field?

**Comment by benhaynes** [comment]
Hmm, maybe it is actually. I'm not sure what the best input for date-time would be, tbh. I agree that editing an existing value is cumbersome here, and that it's annoying that arrow keys don't work for easy adjustments. Also, not being able to tab within this long value isn't great UX.

Thoughts on an ideal `datetime` interface?
* Masked Input (what we have now, maybe tweaked)
* Individual Inputs (probably 6-7, one for each value segment)
* Browser/System (we had this for a while)
* External Library or something else?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
The browser / system one was pretty horrendous too... I wouldn't mind splitting up the datetime into date + time

**Comment by benhaynes** [comment]
Cool — I agree. I guess the question would be how we want to split things... and if any of this should be options, or just... how it is.

```
[20-08-2019]  [18:44:00]
versus...
[20]-[08]-[2019]  [18]:[44]:[00]
[20]-[08]-[2019]  [06]:[44]:[00] [pm]
```

Either way, it would be nice to have some dynamic helper text below the interface that shows something more human-readable:
`August 20, 2019 @ 6:44p` with a hover tooltip as: `1 day ago`

**Comment by rijkvanzanten** [comment]
Individual inputs for every single will probably get super annoying too (having to tab after every character), also, this will be more annoying to deal with i18n wise too (having to render different inputs based on language)
