### ISSUE TITLE
Can't erase a datetime field

### ISSUE THREAD

**Issue by usbpaul** [directus/app#1905]
Hi,

When editing a content-item that has a datetime field populated, trying to erase the field and save that doesn't work. After emtpying all datetime parts and saving, the old value is persisted.

Device: Dell desktop pc (Precision Tower 3420)
Browser used: Chrome 75.0.3770.142
OS: Windows 10 Pro, version 1803.
Directus app: 7.0.18 (running in Docker)

**Comment by benhaynes** [comment]
How did you try to delete the value? We have a new "clear value" option for every field since 7.6ish. This issue might be caused by your version being so old... we're releasing an updated Docker in the next few days, could you try again with that to see if this is still an issue?
