### ISSUE TITLE
Issue with search in select modal?

### ISSUE THREAD

**Issue by WiersmaICT** [directus/app#1906]
Hi there!

It seems that we are having an issue with the search in the select modal. We have a child and want to add a mum and dad to this child using a O2M relation. So far, so good.

Now we want to select the dad from the list of "dads", but we always want to show the select modal, even if there is just one item in the list (in this example we have about 15 "dads"). Now, when we start searching (while typing quite fast) in the select modal characters typed are disappearing. It seams that the application is posting back during typing(?). The same thing happens when you try to remove characters using the backspace or delete keys.

We reproduced this on a Windows 10 PC with Chrome, Firefox and Edge and on a Mac using Chrome. We are currently using version 7.6.1 of Directus on a TransIP VPS using CentOS & NGNIX. Can you guys reproduce this problem? And, if so, do you have a solution?

Kind regards,
Johan
Wiersma ICT

**Comment by benhaynes** [comment]
Thanks Johan — we can look into this, but could you upgrade to the latest version and see if this is fixed? We've done some pretty big updates to the O2M and modal since 7.6.1.

**Comment by cdwmhcc** [comment]
@benhaynes This problem does exist.

As shown in the figure, in the process of entering "application" quickly,
The letter T is missing.

![](https://raw.githubusercontent.com/cdwmhcc/public/master/directus.gif)

**Comment by rijkvanzanten** [comment]
Funnily enough, the problem was that we were typing _too slow_. It was firing the search query while typing, which would override the used search query once it finished.
 I've increased the debounce time so it'll only post the search query after we're done typing 👍

**Comment by rijkvanzanten** [comment]
@WiersmaICT Groetjes uit NYC, Johan!

**Comment by WiersmaICT** [comment]
@rijkvanzanten Thanks for the quick response & action! 👍 Veel plezier daar! :-D
