### ISSUE TITLE
Deep linking a collection item does not work

### ISSUE THREAD

**Issue by Lapsus** [directus/app#1909]
Send a link to a item via email: for example https://somehost.com/_/collection/foobar/10

Upon calling the link from your email programm you get to the login page (which is expected and fine). But after successfull login you get to the "last_page" from directus_user collection instead of /_/collection/foobar/10.

**Comment by benhaynes** [comment]
The priority should be:

1. The page requested page
2. The user's last accessed page
3. The Collections page

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/app/pull/1940
