### ISSUE TITLE
In listing view, fields should be ordered as set in the collection settings

### ISSUE THREAD

**Issue by romaiiinnn** [directus/app#1910]
# Feature Request
In the listing view, display the fields in the same order as set in the collection settings.

## What problem does this feature solve?
Currently, the order defined in the settings is only respected by the details view. For the listing, we need to manually re-order the fields in the listing view using the (i) button on the top right.

## How do you think this should be implemented?
Grab the collection fields order and apply it on the listing view (same way as for the details view).

## Would you be willing to work on this?
Would love to, but didn't even opened the app code, so I'm not ready to work on features (yet) :)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
