### ISSUE TITLE
In the User Directory list, the user's avatar is not displayed

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1912]
Bug Report

![image](https://user-images.githubusercontent.com/8030134/62313516-8be25880-b4c3-11e9-941c-4de7589058b2.png)

## Expected Behavior
Show user avatar

## Actual Behavior

In the User Directory list,
When the user uploads the Avatar
It will not display

## Technical Details

- Device: [Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.1]
- APP Version: [7.8.0]

**Comment by bjgajjar** [comment]
Hey @cdwmhcc 

Not able to replicate this issue. May I have a screen recorder?

**Comment by shealavington** [comment]
Any browser console logs?

**Comment by cdwmhcc** [comment]
@bjgajjar @shealavington 

https://streamable.com/8mxx9

**Comment by cdwmhcc** [comment]
Maybe that's because of s3?

**Comment by christianrr** [comment]
Same issue here, latest Version. Seems to be a general bug in the cards view, since it also happens if I switch a table to cards view.

**Comment by benhaynes** [comment]
@christianrr — are you using local storage or the S3 adapter?

**Comment by christianrr** [comment]
@benhaynes local storage

**Comment by edenprojectde** [comment]
I just wanted to confirm this too. 
https://youtu.be/y_RaFKnwi-Q
This Problem seems to be older, i had it some while ago too when i first tried Directus in January/February.
The same Issue exists for me with the cards view itself on other tables.
![image](https://user-images.githubusercontent.com/6115966/62497877-90698280-b7dd-11e9-9845-a1fefa086df2.png)

Maybe this can help:
![image](https://user-images.githubusercontent.com/6115966/62498073-4b921b80-b7de-11e9-9c68-6f6b454965aa.png)

I use
nginx version: nginx/1.14.0 (Ubuntu)
mysql 5.7.26-0ubuntu0.18.04.1 (Ubuntu)
Directus 7.8.0 (Suite)
I also used Apache2 some months ago, i can remember this issue but didn't post about it as i haven't used Directus because of memory leakage(?); i came back to Directus about a month ago.

**Comment by cdwmhcc** [comment]
@edenprojectde 

No, this problem only exists in the list of users

**Comment by edenprojectde** [comment]
@cdwmhcc If it isn't related to this problem, i will open another Issue later on. Maybe it is the same issue and it's just happening under certain circumstances on the Cards view.

**Comment by rijkvanzanten** [comment]
Is the uploads folder publicly available and is the config set up to point to the right folder? I don't seem to have this problem

<img width="366" alt="image" src="https://user-images.githubusercontent.com/9141017/62578596-82644200-b86f-11e9-8c3b-a10c098aaceb.png">

**Comment by edenprojectde** [comment]
For me, Directus is running without any other relatable issues. Requests to the File API seem to work too. 
My Avatar is showing up in the lower left of the page, just on the cards view it isn't present. 🤔 
Pictures elsewhere are also showing up. (Like an User in a normal tableview and on my webpage via api call)
The uploadfolder is owned by www-data with RW allowed. Which is Nginx user.
Does the file type have anything to do with this maybe? 
Maybe casesensitivity or something along those lines? 
Maybe some Filetypes are missing to render it at all?
Maybe it's a caching or language issue?
Maybe this can help:
https://directus.benjamin-krippner.de/admin
id: test@test.de
pw: testcode

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cdwmhcc** [comment]
@rijkvanzanten 
![image](https://user-images.githubusercontent.com/8030134/62583362-80879680-b8e2-11e9-806f-29ddce70c7b5.png)
git clone -b develop No problem,
Reproducible in app 7.8.0

**Comment by andrewksimon** [comment]
I have the same issue after I did a ```git pull origin``` on my install today: I'm missing the thumbnail/user image cards as well. It isn't an issue with the thumbnailer, as I can run that manually (and it works). 

![image](https://user-images.githubusercontent.com/24998798/62666113-05f56000-b950-11e9-9f09-dd35692781b7.png)

![image](https://user-images.githubusercontent.com/24998798/62666153-31784a80-b950-11e9-9228-72ec66e5ec8e.png)


**Technical Details:**
- Device: [Chrome Desktop]
- OS: [Windows 10.1803]
- Web Server: [Nginx:1.10.3]
- PHP Version: [7.3.8]
- API Version: [2.3.1]
- APP Version: [7.8.0]

**Comment by cdwmhcc** [comment]
It working in v7.9.0
