### ISSUE TITLE
The console reports errors when editing items

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1913]
Bug Report

![image](https://user-images.githubusercontent.com/8030134/62314266-35761980-b4c5-11e9-9123-376da03455d0.png)

## Expected Behavior

Fix it

## Actual Behavior

There are m2m, o2m, files, files, repeaters in this collection

## Technical Details

- Device: [Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.1]
- APP Version: [7.8.0]

**Comment by rijkvanzanten** [comment]
Can you remove the interfaces from this collection one by one and report which one is causing the trouble? I can't reproduce this based on the information at hand

**Comment by cdwmhcc** [comment]
@rijkvanzanten 
Maybe there's something wrong with my database. My new installation doesn't reproduce this problem. I'll open it when I find out why.
