### ISSUE TITLE
"Files" interface is not passing validation when required and no items are changed

### ISSUE THREAD

**Issue by edenprojectde** [directus/app#1916]
When editing an Entry with a required 'Files' field, and not changing this required field. It says "'files field'- should not be empty" and can not be saved.

![image](https://user-images.githubusercontent.com/6115966/62070332-8d4d2000-b23a-11e9-8bb7-19d4735cffb1.png)

Directus v7.8.0
PHP Zend Engine v3.3.7 with Zend OPcache v7.3.7-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c)
Nginx Server
OS: Ubuntu

**Comment by rijkvanzanten** [comment]
@bjgajjar Even though the app shouldn't stage the changes, that shouldn't matter from the API side. If an empty array is passed to the API, it's not updating or creating any files, and should thus not return the error

**Comment by edenprojectde** [comment]
Seems to be fixed in 7.9.0

**Comment by rijkvanzanten** [comment]
Appreciate that @edenprojectde! ❤️ Doing what we can to make this the best CMS out there
