### ISSUE TITLE
“git clone -b develop”  Enter the collection list to report errors

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1921]
### 1、Enter the collection list to report errors
![image](https://user-images.githubusercontent.com/8030134/62418761-0964bf00-b6a4-11e9-8456-6f2961694a80.png)

/src/routes/items.vue

It's caused by 376 lines of code.

 `return _.find(this.fields, { primary_key: true }).field;`

After annotating this line of code, you can access the list of collections
But `create_on` and `modified_on` are missing

#### v 7.8.0 

![image](https://user-images.githubusercontent.com/8030134/62418829-79277980-b6a5-11e9-844e-9b0ba424539e.png)

#### git clone -b develop
![image](https://user-images.githubusercontent.com/8030134/62418827-6c0a8a80-b6a5-11e9-82ee-1f44f225d92a.png)

> Because it's a non-production environment problem. So I merged the two problems I found into this issue, so I didn't open a new issue alone.Detailed video I sent to @rijkvanzanten slack

## Technical Details

- Device: [Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.1]
- APP Version: [git clone -b develop https://github.com/directus/app]

**Comment by rijkvanzanten** [comment]
I don't see these issues on my end. Can you share a DB dump of a clean setup to reproduce this?

**Comment by cdwmhcc** [comment]
@rijkvanzanten 

Question 1:
I'll re-gitclone once, and you can enter the list, but create_on and modified_on are missing

![image](https://user-images.githubusercontent.com/8030134/62634293-3e089d00-b968-11e9-83fd-f4e6ce56515e.png)

Question 2:

The checkbox option does not load. This problem still exists.

I send my database to your slack
