### ISSUE TITLE
Project Switcher displays incorrect data on "Other"

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1925]
When logged into an "Other" API (eg: Cloud Projects) the dropdown incorrectly highlights a different project:

![Screen Shot 2019-08-05 at 3 38 16 PM](https://user-images.githubusercontent.com/522079/62490369-1f9f7780-b797-11e9-9ae6-e68df0fcd4bf.png)

![Screen Shot 2019-08-05 at 3 38 25 PM](https://user-images.githubusercontent.com/522079/62490375-2201d180-b797-11e9-9152-a1c8d26e5464.png)

Also, we should add a conditional for Cloud API endpoints (sorry OSS!) that prettifies the project name when using a Directus Cloud API. It should say `Directus Cloud` instead of `Api.directus.cloud`.

**Comment by rijkvanzanten** [comment]
As for your second point, the app should pull the project name from the api (`/` endpoint). The app config should ideally be an array of just URLs, which the app in turn then uses to pull the project names (and logo!) to render in the app.

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/app/issues/1525

**Comment by benhaynes** [comment]
Excellent! That' even better! :)

Does that mean we need to wait until the new login page (auth refactor) to get this? Or is it something the API can do relatively easily now?

**Comment by rijkvanzanten** [comment]
The API already returns this information, the application doesn't fetch it yet though. I was planning on implementing fetching the project name / logo from the API when implementing the new login screen / flow

**Comment by theharshin** [comment]
Can not reproduce the issue now as it should be fixed with this PR https://github.com/directus/app/pull/1941 
The PR fixes the issue where the Store object was keeping the reference to old project Store. The issue shows the same behavior. @benhaynes let me know if you can still reproduce the issue.

**Comment by benhaynes** [comment]
This seems to be working now! Thanks!
