### ISSUE TITLE
Can't create many to many relationships

### ISSUE THREAD

**Issue by Alexggp** [directus/app#1927]
Hello, 
I've been having problems creating many to many relationships. I recieve the following error message when I click in the "Create Field" menu option:

"Trouble processing request. Try again after refreshing the page."

I have refreshed the page, loged out and loged in, but still it doesn´t work.

![Captura](https://user-images.githubusercontent.com/1389054/62527393-54fda100-b83b-11e9-837a-477782177eba.JPG)

Thank you very much!

Keep being awesome! ;)

✨🐰✨

**Comment by bjgajjar** [comment]
Hey @Alexggp 

It seems like you have been using the old version of `APP`.  As currently, it is not reproduced at our end.

May I know which version you are using? If you can provide some technical details then it will be really appreciated :)

**Comment by Alexggp** [comment]
Hello, 
My current version is 7.6.0. Should I upgrade to 7.8.0 to avoid this disproblem? 

Thank you

**Comment by bjgajjar** [comment]
Can you please try once after upgrading your system?

**Comment by shealavington** [comment]
> now it seems it has a wrong "O2M" subtitle

Technically that's the correct subtitle, it's always been like that, as an M2M is just an O2M->M2O put together.

**Comment by Alexggp** [comment]
It seems that it only happends in one specific collection. In the other collections I can create M2M without any problem. 

I have removed the collection and created another with the same name and the error persists. 

So I have created a new one with a new name and works fine. 

I don't know what can be happening. 

Anyway thank you very much! Great support!

**Comment by rijkvanzanten** [comment]
It sounds like some records remained in `directus_relations` after deleting the collections. Could you take a peek at that table and clear out any records that are from the old attempt?

**Comment by Alexggp** [comment]
I have deleted all references to the old collection in directus_relations table, as you have said, and still happening
