### ISSUE TITLE
Media & Files: Service integration (Unsplash)

### ISSUE THREAD

**Issue by shealavington** [directus/app#1933]
# Feature Request

## Reduce friction: Allow media selection from services.

Currently my clients have to open an external service, browse that service to find an image they like, download the image they want to use, switch to Directus, upload the image they want to use, then remove the image from their computer.

I think we could improve this issue by enabling "Files/Media Extensions". This could potentially allow you to integrate custom services as extensions to the files interface, this should return a URL that the API can parse and download from.

I imagine: The user seeing their images, they don't like the images they have, so click the "Unsplash" button which switches the view to the "Unsplash Library" rather than "User Library"

**Enhanced user-flow:**
- Add new item to collection (New Blog)
- Image is required, click  `+ Add New` image,
- User sees they don't currently have an image they like uploaded
- Click load from service / something `(Unsplash, Pixabay, Pexels)`
- User searches for `"Puppies"`
- A grid of preview images about `"Puppies"` are returned (200x200px(?))
- User can click on the images they like which will preview full-screen
- User clicks confirm to use the image

At that point, the system should take-over, which will upload the selected image to Directus (as if it was uploaded manually), it will then select that image from the media-library for the user to use.

### Discuss Below

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
