### ISSUE TITLE
Items cannot select multiple

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1934]
app: v7.9
api: v2.4

Enter the collection list and check multiple items. See error

![image](https://user-images.githubusercontent.com/8030134/62716237-65c53700-ba34-11e9-84b8-6d02aba4d6ab.png)

**Comment by rijkvanzanten** [comment]
I don't see this issue on the live demo: 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/9141017/62727798-3ab4f600-b9e8-11e9-840c-6b085374d6bc.png">

I'll use the db dump you provided earlier to figure out what's going on here 👍

**Comment by rijkvanzanten** [comment]
This only seems to happen when `Hide on Browse` is turned on for the primary key field
