### ISSUE TITLE
API Link in Collection

### ISSUE THREAD

**Issue by edenprojectde** [directus/app#1950]
# Feature Request
Making the Title of the collection to the API Link, would be very useful to not have to look up some referencial Link. This could (in theory) later be extended with options in an extra UI in the future, where at first it could only feature placeholders for group,filter and depth of lookups.
![image](https://user-images.githubusercontent.com/6115966/62818598-b7131a80-bb49-11e9-95d9-eac2676bb5b5.png)

## What problem does this feature solve?
It will improve the workflow of Frontend Developers.

## How do you think this should be implemented?
Clicking on the Title of the collection should copy the base Link of the collection into the clipboard. (Later on it should be a full GUI if developed further.)

## Would you be willing to work on this?
Yes.

**Comment by bjgajjar** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
I like the idea of being able to match the current view into an API url (including params / filters!)

Lets make it admin only though; "regular" users (eg content editors) will most likely not need this functionality

**Comment by benhaynes** [comment]
I like it. This seems similar to my idea from a while ago:

https://github.com/directus/app/issues/741

I think you should be able to get/see the API queries for any App page... then it's almost like a GUI for creating API requests.

**Comment by rijkvanzanten** [comment]
Wanna consider this a duplicate @benhaynes ?

**Comment by benhaynes** [comment]
Yeah, I think so. It'll still be referenced in the other ticket.
