### ISSUE TITLE
TypeError: Cannot read property 'field' of undefined when batch deleting items

### ISSUE THREAD

**Issue by JbalTero** [directus/app#1951]
## Steps to Reproduce

* Using the directus demo
* Create a collection
* Add item to the collection
* Delete the item in the listing

## Expected Behavior

It should successfully deleted

## Actual Behavior

Not deleted. In the browser console it displays: `TypeError: Cannot read property 'field' of undefined`

## Other Context & Screenshots

[Screen recording](https://drive.google.com/file/d/1kzhaOJNvYpdwF8RoCUGlEOhwdXfhEm07/view?usp=sharing)

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.4.0 build
- Directus App: 7.9.0

**Comment by bjgajjar** [comment]
Fixed in #1953
