### ISSUE TITLE
Simplified datetime format

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1959]
# Feature Request

![image](https://user-images.githubusercontent.com/8030134/62985300-45004580-be69-11e9-9487-e1df5ba1478c.png)

![image](https://user-images.githubusercontent.com/8030134/62985501-28184200-be6a-11e9-939e-30da0d1a6f76.png)

## What problem does this feature solve?

I don't know how dates and times are displayed in other countries. 
The format we use in China is:
2019-08-13 20:05

Instead of: 2019年8月13日周二 下午8:05 GMT

## How do you think this should be implemented?

![image](https://user-images.githubusercontent.com/8030134/62985670-f358ba80-be6a-11e9-8b7b-f6f2c36304ba.png)

format('YYYY-MM-DD HH:mm')

## Would you be willing to work on this?

It doesn't need me.

**Comment by rijkvanzanten** [comment]
Does that field exist already and is it broken, or did you add it as an example? @cdwmhcc

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by cdwmhcc** [comment]
> Does that field exist already and is it broken, or did you add it as an example? @cdwmhcc

This is a suggestion.
