### ISSUE TITLE
I can't see some fields to add in table

### ISSUE THREAD

**Issue by alextomas** [directus/app#1962]
I need insert created_on and modify_on data in my table, but I can't see this fields in table options.
![Captura de pantalla 2019-08-14 a las 13 04 03](https://user-images.githubusercontent.com/2083214/63016536-3ed38e80-be94-11e9-8cab-051e6e77f360.jpg)
![Captura de pantalla 2019-08-14 a las 13 04 21](https://user-images.githubusercontent.com/2083214/63016537-3ed38e80-be94-11e9-92b1-471084d90408.jpg)

**Comment by shealavington** [comment]
Click on them on the collection administration page
Schema -> Advanced options -> Disable "Hidden" toggles.
