### ISSUE TITLE
Image not showing in repeater

### ISSUE THREAD

**Issue by lescinskiscom** [directus/app#1965]
A repeater with a file field that contains an image does not load the image after saving and reloading, but it saves correctly in the database.

`
[{"Image":{"id":16}}]
`

Recreate by creating a collection with a repeater that contains a file field and try saving and reloading the page.

App version 7.9.0
API version 2.4.0
PHP 7.3
MariaDB 10.3.11
Apache 2.4.29

**Comment by rijkvanzanten** [comment]
Relational interfaces (file, files, m2o, o2m, etc) don't work in the repeater. Ref https://github.com/directus/app/issues/1818

**Comment by rijkvanzanten** [comment]
The JSON-based repeater does not support relational interfaces. The commit above removes support for setting up relational fields in the repeater interface. While this is not a complete fix for the problem, it does prevent it from happening in the future. Meanwhile, we'll be focussing our efforts on creating a new relationship-based repeater field that has full support for all interfaces Directus has to offer.

**Comment by stouch** [comment]
Any news about this ? It's be so great to let user choose library files inside repeaters !

**Comment by benhaynes** [comment]
Nope. We post whenever there is news on tickets, but are heads down on a refactor still. The only way to prioritize tickets as of now is to sponsor/commission them.

https://docs.directus.io/getting-started/supporting-directus.html#commissioned-features

**Comment by rijkvanzanten** [comment]
Also keep an eye on #1996
