### ISSUE TITLE
Card layout displays [object Object] while table layout output is correct

### ISSUE THREAD

**Issue by lescinskiscom** [directus/app#1966]
When selecting cards layout and setting title or subtitle to an O2M field, the output is [object Object] while everything is displayed correctly in the table layout.

App version 7.9.0
API version 2.4.0
PHP 7.3
MariaDB 10.3.11
Apache 2.4.29

**Comment by rijkvanzanten** [comment]
The card component should rely on the display extension of interfaces, just like the tabular layout
