### ISSUE TITLE
Can't sort using translation field

### ISSUE THREAD

**Issue by avshelin** [directus/app#1968]
Hi,

I am trying to sort my data using a field located in a translation table:

http://cinema.equilateral.md/_/items/movies?lang=en&fields=*.*&sort=translations.movie_title

I get an error: "Invalid field \"translations.movie_title\" in \"movies\""

Is there any way I can do this?

Best regards,

Anton

**Comment by benhaynes** [comment]
Not as of now, unfortunately...

https://github.com/directus/api/issues/209
