### ISSUE TITLE
Layout picker is not fully clickable in Safari

### ISSUE THREAD

**Issue by webforte** [directus/app#1969]
### Problem

When I try to change the layout of a collection's table, in Safari the clickable area select covers only the upper third of the area. I removed the `opacity: 0;` property for the sake of demonstration:

![image](https://user-images.githubusercontent.com/5497140/63153257-25eee880-c00e-11e9-83f2-46131c7c7936.png)

---
### Specs
- Safari 12.1.2 (macOS)
- App version 7.9.0
- API version 2.4.0
- PHP 7.2.21
- MySQL 5.7.27
- nginx 1.17.0

**Comment by rijkvanzanten** [comment]
Adding `appearance: none` to the styling of this checkbox will cause safari to render it the same as in other browsers.
