### ISSUE TITLE
_ Is converted to black space in the note field

### ISSUE THREAD

**Issue by jbitsch** [directus/app#1978]
Create a field with a note which include _
For example:
![image](https://user-images.githubusercontent.com/1073322/63420271-a777b980-c406-11e9-9058-920bf280833a.png)

The full note is: _NEXT_LEVEL will be replaced with the next level, CURRENT_LEVEL will be replaced with the current level, REMAINING_COUNT will be replaced by the remaining count before achieving the next level._

When view the field in the UI it is coverted to:
![image](https://user-images.githubusercontent.com/1073322/63420391-d857ee80-c406-11e9-9a04-c908e66ff4c1.png)

So the _ are removed and the html looks like:
![image](https://user-images.githubusercontent.com/1073322/63420437-f1609f80-c406-11e9-98a5-7f5060b0e2bb.png)

**Comment by jbitsch** [comment]
Is using https://github.com/developit/snarkdown

**Comment by jbitsch** [comment]
Due to the code:
`<p class="note" v-html="$helpers.snarkdown(option.comment || '')" />`

And there is an issue related to it her: https://github.com/developit/snarkdown/issues/21. But is two years old....

**Comment by rijkvanzanten** [comment]
In case someone else runs into this: the Note field accepts Markdown. `_` characters can be used to make text italic: https://www.markdownguide.org/basic-syntax/#bold-and-italic
