### ISSUE TITLE
Setting Primary Key Field to "hidden on browse" breaks selecting multiple items

### ISSUE THREAD

**Issue by tobibode** [directus/app#1987]
Whats up everyone,
when I set the Primary Key field of a collection to "hidden on browse" and try to check multiple items of the collection, the following function in one of the items.vue fails:
```
primaryKeyField() {
      if (!this.fields) return null;
      return _.find(this.fields, { primary_key: true }).field;
},
```

it seems like "hidden on browse" prevents the primary key field from making it to the this.fields array, thus throwing the error: `TypeError: "_.find(...) is undefined"`

disabling "hidden on browse" and always keeping it on "true" is a solution, but I would have to disable my directus users from seeing the ID via role settings, which is more complicated than just "hiding on browse". 
Maybe you'll find another way to get the primary key field.

Kind regards,
Tobi

**Comment by urvashithakar** [comment]
Hey @tobibode,
I set the Primary Key field of a collection to "hidden on browse" and followed the steps you mentioned above but I didn't get any error. 

May I know that which version of APP you are using?

**Comment by rijkvanzanten** [comment]
I don't see this issue on my end. Closing this as the OP didn't respond either.
