### ISSUE TITLE
Clicking Add New on o2m field should not insert empty row

### ISSUE THREAD

**Issue by JbalTero** [directus/app#2003]
## Steps to reproduce

`artists` o2m with `artworks`

* Create artist item
* Click Add new on artworks o2m field
* Click cancel

## Expected

It should not add empty row

## Actual

An empty row is added

![image](https://user-images.githubusercontent.com/3615746/64007301-7ace4b00-cb46-11e9-9853-864a22feae15.png)

## Misc

[Screenrecording](https://drive.google.com/file/d/1CKnymQcHRFGz36_CPZdGkkXk7dNqyqOA/view?usp=sharing)

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.5.0 build
- Directus App: 7.10.0

**Comment by benhaynes** [comment]
Hmm, @rijkvanzanten seemingly closed this one a few weeks ago: https://github.com/directus/app/issues/1851

Maybe it snuck back in?

**Comment by rijkvanzanten** [comment]
@theharshin when you fixed this in https://github.com/directus/app/issues/1851, you only did it for the m2m. Could you apply the same fix to the o2m as well so we can close this issue for good?

**Comment by kaushal-im** [comment]
It will be fixed in #2020

**Comment by JbalTero** [comment]
This is fixed in my side too now.

**Comment by JbalTero** [comment]
thakns
