### ISSUE TITLE
Status interface broken

### ISSUE THREAD

**Issue by pikzelz** [directus/app#2004]
I recently updated my directus/app branch and noticed the status interface is no longer  displaying in Safari, Firefox & Chrome.

It does render the active label, but not the status buttons as expected. I do see this error in my console:
```
Error in render: "TypeError: this.$store.state.permissions[this.collection] is undefined"
```

All other interfaces I use work as expected.

**Comment by benhaynes** [comment]
Hmm, that seems odd... maybe a config issue? I just logged into our demo (on the latest version) and status interfaces appear to be working:

https://directus.app/#/collections/movies/442

**Comment by JbalTero** [comment]
No prob on my side also

**Comment by benhaynes** [comment]
Hey @pikzelz — we've done a bunch of testing and aren't getting this error. Maybe you could look into your status configuration/stack a bit and see if maybe there's an issue? Maybe something changed without you realizing it?

I'll close this for now, but if you can add more info to help us reproduce then we can re-open. Also, it'd be great if you could reproduce on our example/demo app. :)

**Comment by pikzelz** [comment]
Strange! I didn’t change anything just updated the core and it stopped working. All other interfaces work.

I guess I need to try to re-install

**Comment by benhaynes** [comment]
Man, re-installing seems like a bummer. But yeah, if nothing else changed and you just updated I can't think of why it would stop working. 

I am no dev expert, but this makes me think it's an issue with the vue.js store:
`this.$store.state.permissions[this.collection]`

Maybe try hard clearing browser cache, and logging in again? Maybe it's a cache issue... could save you from a full re-install!
