### ISSUE TITLE
Permissions Dropdown Missing Option

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2005]
Right now if you go to the Directus demo and edit the `intern` permissions for `movies`, you can not set anything except "All" or "None". The values saved show "My User" and "My Role", but these are no selectable from the dropdown...

![Screen Shot 2019-08-30 at 4 49 28 PM](https://user-images.githubusercontent.com/522079/64050534-5a05f580-cb46-11e9-9d3e-0cad68c0faf4.png)

**Comment by theharshin** [comment]
@benhaynes This is due to the **Movies** collection does not have `user_created` interface. If you add it, the dropdown contains all the permissions. Currently it shows a user/role specific values because it was saved when the `user_created` interface was present. Right now it is removed and values are as-it-is.

**Comment by benhaynes** [comment]
You're correct that the drop down does work if you add a `user_created` field. Can we update the Demo SQL so that either the permissions are correct, or so we have a `user_created` field when needed?

https://github.com/directus/demo-sql

Also, I saw the same issue on the permissions for Directus Core collections. **How can we correct these?**

![Screen Shot 2019-09-04 at 9 47 38 AM](https://user-images.githubusercontent.com/522079/64260545-0eae6700-cef9-11e9-8885-19fb79fdb76f.png)

**Comment by theharshin** [comment]
@bjgajjar You'll need to write migrations for these right?

**Comment by bjgajjar** [comment]
@rijkvanzanten - Added PR 

- User collection [Movies, Concessions] permissions : https://github.com/directus/demo-sql/pull/2
- Core table permissions :  https://github.com/directus/app/pull/2104

Don't know how but without merging the issues it's getting closed automatically. 
Reopening it again.
