### ISSUE TITLE
For status field, when creating a new item, deleted should be removed

### ISSUE THREAD

**Issue by JbalTero** [directus/app#2007]
When creating a new item, I suggest to remove the "deleted" input as it confuses users.

![image](https://user-images.githubusercontent.com/3615746/64058802-2cbb5500-cbe3-11e9-8c68-62dfcc165130.png)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
