### ISSUE TITLE
File preview is gone when closing a modal

### ISSUE THREAD

**Issue by JbalTero** [directus/app#2008]
## Steps to Reproduce

* Using directus demo
* `artworks` one-to-many with `art_images`
![image](https://user-images.githubusercontent.com/3615746/64059811-ea4f4380-cbf5-11e9-9c9a-ff0f2e399542.png)

* `art_images` contains file field
* Add new art_image via artwork, then click the save button(not the save artworks yet)
* Click the the new art_image again, the file preview is gone

[Screenrecording](https://drive.google.com/file/d/1rPBUZNS1b2qqM9ka_I92zgSXimM3AXBA/view?usp=sharing)

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.5.0 build
- Directus App: 7.10.0

**Comment by itsmerhp** [comment]
@JbalTero Can you please check this in latest APP build?
This issue has been resolved with #1920

**Comment by JbalTero** [comment]
@itsmerhp it is fixed in my side. thanks
