### ISSUE TITLE
directus_files Many to many have serious problems

### ISSUE THREAD

**Issue by pablotandil** [directus/app#2011]
In addition to the bug that I show in the attached image, I think it would be very useful to be able to create folders, it is practically impossible to select several images from thousands, for example to publish a photo gallery in a blog post

![2019-09-02_0643](https://user-images.githubusercontent.com/2906373/64105693-192bfd80-cd4d-11e9-8cab-b260ebde43a7.png)

**Comment by shealavington** [comment]
Folders is an existing feature request so that can be forgotten for now, however, I don't reall see the "serious problems" you mention, could you please describe the issue...

**Comment by pablotandil** [comment]
Hi Shealvington, 
Yes sure, I have to make more than 50 posts, each post has 20 images (carousel). If I load 1000 images as I associate the 20 images corresponding to each carousel?
The filter by label does not work, nor by any other way, would I have to look for 20 images corresponding to each post among the 1000? and don't see the title or another description and dont have multiple load (don't work)

**Comment by rijkvanzanten** [comment]
How did you set this up? What field interface did you use? What options did you use for this interface? 

It looks like you might have some config issues, so I'm gonna close this for now.

As for the support for folders, see https://github.com/directus/app/issues/228 and feel free to implement it and open a pull request.
