### ISSUE TITLE
Renaming `Public` role gives `unauthorized` error on API calls.

### ISSUE THREAD

**Issue by anelad** [directus/app#2017]
# Reproducing
1. Rename public role into something. e.g. anonymous
2. Using the API, request any collection / item that public role already has reading permission.
3. You will get `unauthorized` error.

- I think this problem occurs on the Directus App, not on the API. This is why I opened the issue here.
- The problem is reproducable on [directus.app](directus.app)
- Even it looks like a very minor issue, it blocks translatability. Especially when the users does not know English. So the `Public` role name should be editable without any consequences; or at least it should not be editable at all.

**Comment by benhaynes** [comment]
I'm not sure why renaming a role would cause an issue, since it should be using the `id` PK for all references. For that reason, I've added this as a bug... but if someone wants to explain why this is happening we can shift it to an enhancement only.

**Comment by anelad** [comment]
@benhaynes I really do not know, but as I said, it's reproducible. And once again as I said, it's a very minor issue. Explaining someone that doesn't know English what the "Public" is should not be a problem :)

**Comment by benhaynes** [comment]
Yeah, the multilingual reason is why I want to keep this as a bug for now (and because I'm confused why this would be an issue at all, since you're not changing the PK). We'll get it fixed for you!

**Comment by shealavington** [comment]
AuthenticationMiddleware.php

```
    /**
     * Gets the public role id if exists
     *
     * @return int|null
     */
    protected function getPublicRoleId()
    {
        $dbConnection = $this->container->get('database');
        $directusGroupsTableGateway = new TableGateway('directus_roles', $dbConnection);
        $publicRole = $directusGroupsTableGateway->select(['name' => 'public'])->current();

        $roleId = null;
        if ($publicRole) {
            $roleId = $publicRole['id'];
        }

        return $roleId;
    }
```

Seems to be trying to lookup the ID for public by using the name.

**Comment by anelad** [comment]
@shealavington has found the problem I suppose

**Comment by benhaynes** [comment]
Good find @shealavington!! 😄 

IMO, we should use the `id` PK, and treat `1` (Admin) and `2` (Public) as reserved IDs for `directus_roles`. Does everyone agree? @directus/api-team

**Comment by shealavington** [comment]
We seed the database that way so I would agree, 1 & 2 should be reserved — Maybe we could use a constant instead of '2' though, so anywhere we need to do `if(id == 'public')` instead of `if(id == 2)` we can do `if(id == PUBLIC)` ensuring we have one source of truth for it

**Comment by benhaynes** [comment]
Ooooh, I like that. Even cleaner!

**Comment by bjgajjar** [comment]
@benhaynes - Agree with @shealavington. We can add constants for roles and implement conditions on that.
