### ISSUE TITLE
Directus user role option to disable directus panel login

### ISSUE THREAD

**Issue by anelad** [directus/app#2018]
# Feature Request
User role option to disable directus app login. Its authentication should only work via the API.

## What problem does this feature solve?
Let's say we have 'comments' posted on a post. A comment should have a user one way or the other. This user might be a "reader" or a "directus user".

The current way used in [directus.app demo](directus.app) is creating a separate collection for "readers". For demo apps use-case it's ok. 

But an SQL based backend like Directus cannot handle my use-case easily. The demo app has only "members" and members and directus users do not cross. In my use case, I need to hold them in one field and it's only possible via JSON. But JSON on MySQL will restrict searchability etc.

## How do you think this should be implemented?
To solve the problem, I decided to create a role for "readers" just like the "Public" role. The only difference is this role can read any comments and update its comments. But since they have "a directus account" they will be able to log in to the panel. So adding a "can log in" toggler would be great.

**The whole feature request would be in vain due to this questions answer: Is my approach is safe?**

## Would you be willing to work on this?
My PHP knowledge is very limited. Also, do not know how Directus implemented. So, I cannot help you with the implementation of the feature. But if you ask me to handle something, I will do whatever I can. This is very important for me!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by anelad** [comment]
@benhaynes  Directus App's feature request link in settings still pointing here. It needs to be fixed then. Plus, should I do anything to add this FR to the board or you already did? I took a quick look and did not see this FR.

**Comment by benhaynes** [comment]
I think the link is still correct... and here is your ticket within the feature request board:

https://github.com/directus/app/projects/45#card-25968317
