### ISSUE TITLE
Collection page - column visibility default settings

### ISSUE THREAD

**Issue by 7jp** [directus/app#2019]
# Feature Request

## What problem does this feature solve?
Problem of consistency among views.
Currently, it looks that when new user opens collection page it contains all columns
that need adjustments as soon as collection has many fields.
Once it's personal page and you're trained and experienced, it's absolutely fine,
however when you present to client they could expect someting clean out of the box  :)

## How do you think this should be implemented?
Default view setting  in directus_collections_presets

## Would you be willing to work on this?
It depends

**Comment by benhaynes** [comment]
This actually exists in a way, you can set `directus_collection_presets.user` and `directus_collection_presets.role` to scope default layout views and bookmarks. Only *Bookmarks* has a way to update this from the Admin App interface — but as an DB admin you can set these defaults in the database until we get this added to the App.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
