### ISSUE TITLE
Ability to work with SQL views

### ISSUE THREAD

**Issue by sihingbenni** [directus/app#2024]
# Feature Request
Request that Directus gets the ability to render SQL views as a "collection"

***Not being able to edit/add any fields in this particular "collection"***

## What problem does this feature solve?

We would be able to join collections, not just two but as many as you'd like.
Being able to view SQL Views with directus.
Being able to sort/filter joined collections.

e.g.: I have two collections users and companies and have an many to one relationship from users to companies (each User has one Company) 

I can create a view like this: 
`create view users_companies as SELECT 'users'.*, 'companies'.*
    FROM 'users'
    , 'companies'
    WHERE 'companies'.'id' = 'users'.'company_id';`

And now I can easily filter all the users which work at Company A and have field B.
Because in Directus this view can be treated like an table.

## How do you think this should be implemented?
removing the multible occurring condition `'ST.TABLE_TYPE' => 'BASE TABLE' in MySQLShema.php` is the first step.

An additional reason why directus wont show the view, is that the SQL view has no primery key.
Which seems to be used to sort the collection. No sorting here for collections without a primary key could fix it.

In the meantime for views one should not be able to edit/add any fields. Searching, filtering or any other read operation may be allowed.

## Would you be willing to work on this?

It depends.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by r0b78** [comment]
This is exacly what i need to archive with my directus proyect !!, expect this feature can be done soon

**Comment by benhaynes** [comment]
It's a great option — but we won't be able to work on in (internally) until after the App/API refactors are complete (~2 months).
