### ISSUE TITLE
Validate visible_fields before using in relational interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#2025]
There's two fields one needs to fill out: `visible_fields` and `display_template`. One requires a CSV of fields, while the other requires a template string (eg `{{ name }} – ({{ age }})`)

It's very easy to accidentally add the curly braces in the first field too. We should show an error on page in the interface (eg `options setup incorrectly`) as it's now bricks the app completely.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
