### ISSUE TITLE
Copy wysiwyg-full field error: "field "caption" does not support length"

### ISSUE THREAD

**Issue by JbalTero** [directus/app#2027]
Copy wysiwyg-full field error: "field "caption" does not support length"

## Steps to reproduce

* Use directus demo
* [Screenrecording](https://drive.google.com/file/d/19T7sCx5UJWeUQTi1Gxa6ek7M323GihCQ/view?usp=sharing)

**Comment by benhaynes** [comment]
Hahahaha, that music!! #ironic

**Comment by JbalTero** [comment]
@benhaynes I didn't realize the music was recorded too. hahaha

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/app/pull/2034
