### ISSUE TITLE
Remember me at login

### ISSUE THREAD

**Issue by alperbalkaya** [directus/app#2036]
# Feature Request
Remember me option at login

## What problem does this feature solve?
At the moment you have to login every time when you open the app

## How do you think this should be implemented?
Remember me option at login

## Would you be willing to work on this?
Yes

**Comment by benhaynes** [comment]
Thanks @alperbalkaya — we're actually starting in on this today! We'll be posting more info on this ticket here:

https://github.com/directus/app/issues/1342
