### ISSUE TITLE
Allow autocomplete of API selector dropdown

### ISSUE THREAD

**Issue by steinarhovland** [directus/app#2038]
# Feature Request
Allow password managers to target the API selector dropdown on the login page.

## What problem does this feature solve?
Allow a password manager like Lastpass to autoselect API or the "other" option and fill in the API-URL in addition to the username / password. This way you can switch both API-url and fill in username and password in one operation when you have multiple client projects using Directus.

## How do you think this should be implemented?
Add id and name attributes to the select dropdown on the login page.

## Would you be willing to work on this?
Yes

**Comment by benhaynes** [comment]
Thanks @steinarhovland!! This one has been bugging me too... 😄

**Comment by steinarhovland** [comment]
Glad it helped someone else as well 😄
