### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by steinarhovland** [directus/app#2045]
# Feature Request
Norwegian translation

## What problem does this feature solve?
Possible to use Directus in Norwegian

## How do you think this should be implemented?
Translate the language files or App

## Would you be willing to work on this?
Yes, see PR.

**Comment by benhaynes** [comment]
Thanks @steinarhovland!!

Ref: https://github.com/directus/app/pull/2043

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
