### ISSUE TITLE
Password change not working

### ISSUE THREAD

**Issue by maettyhawk** [directus/app#2046]
1. Login Screen -> "Forgot PW"
2. Enter email address
3. Click reset password link of email received
4. Login using temporary password
5. Go to user's profile and change password
6. Log out
7. Try to login with new password
8. Login fails

Another phenomenon which kinda makes it impossible to use the account anymore:

1. Click the password reset link of a previous attempt
2. Email with another password is sent to you
2. Use OTP of the email just received to login
3. Login screen asks for OTP
At that point every attempt to login (even with a completely new OTP) fails.

I'm using the Shield — (190827A) version of Directus on a shared hosting environment (it's an Apache running with PHP 7.0.32 and MySQL 5.0.12 under-the-hood).

**Comment by maettyhawk** [comment]
Hey @benhaynes, it tried to give some more info.

**Comment by shealavington** [comment]
> with PHP 7.0.32 and MySQL 5.0.12 under-the-hood

I'm going to close this for now — Please ensure your server meets the requirements for Directus to work. After you've upgraded, please feel free to re-open this issue if the problem persists. 

https://docs.directus.io/advanced/requirements.html#sql

As mentioned in the linked guide, PHP `7.1+` and MySQL `5.7+` are required.

*Due to Directus being managed by a small team, we can't ensure that it will work all the way back to older versions of PHP, sorry about that!*

**Comment by maettyhawk** [comment]
OK, my infos were wrong. It's a MySQL 5.7.26 (Ubuntu) + PHP 7.2.19 combination.

It might also have to do with the lately introduced 2fa feature which I activated a few days ago and deactivated right after.

**Comment by bjgajjar** [comment]
> Could someone please check that 2FA can be enabled and disabled without it effecting the ability to change password and login.

Yes, It is not affecting at all. One another user facing this issue; I am communicating with him in slack private message. Will let you know if I found anything :)

**Comment by bjgajjar** [comment]
> One another user facing this issue; I am communicating with him in slack private message.

@maettyhawk - He got rid from this issue with a fresh installation of `Directus`.Can you please try it once?

**Comment by maettyhawk** [comment]
@bjgajjar Thank you, it works.
