### ISSUE TITLE
Editable `Datetime Created` and `Datetime Updated` interfaces

### ISSUE THREAD

**Issue by anelad** [directus/app#2048]
# Feature Request
Editable `Datetime Created` and `Datetime Updated` interfaces

## What problem does this feature solve?
Sometimes you might want to change these values.

## How do you think this should be implemented?
At least as a textview, but a date picker + time picker would much more user friendy

## Would you be willing to work on this?
If you need any help, I will do as much as I can. But you know my lack of vue and php knowledge.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
