### ISSUE TITLE
Sticky menu

### ISSUE THREAD

**Issue by WoLfulus** [directus/app#2050]
# Feature Request

Make the left bottom profile menu sticky.

## What problem does this feature solve?

I always keep hitting logout button or missing the action because menu expand/collapses on hover. 

## How do you think this should be implemented?

Make the menu expand on click "^" and collapse on click "V". It keeps its state

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
