### ISSUE TITLE
User related fields are broken

### ISSUE THREAD

**Issue by WoLfulus** [directus/app#2058]
As raised with the team, there's an issue displaying the user related data into table listing. Might be something related to avatar.

To reproduce the issue:

- Go to user profile
- Upload a profile picture
- Save
- Create a collection with created_by and modified_by and some fields
- Navigate to the collection
- Add a new entry
- Navigate to the collection again (at this point the table is already broken and can't be seen any data)

![image](https://user-images.githubusercontent.com/412397/64843599-e5b66200-d5db-11e9-9c66-1c480c3a0b32.png)

**Comment by bjgajjar** [comment]
The issue occurs as `APP` is fetching the single level relationship. Thus, the collection will get the user data. But the user has also relation with `file` interface. As `APP` requested single level; it will not return the whole object of `APP`.
 
We can achieve this in 2 different way. @rijkvanzanten Let's finalize this.
- Add `*.*` at `APP` side.
- Implement the condition that if `user_created`, `user_updated` or `user` type field was exist in particular collection; provide the `avtar` data.

Feel free to share other solution :)

**Comment by bjgajjar** [comment]
@rijkvanzanten - 🔔

**Comment by alrick** [comment]
Any news about that ?
I think that's the same problem I reported earlier :
https://github.com/directus/app/issues/1871

**Comment by benhaynes** [comment]
Rijk is currently heads-down on the new Auth Flow, but he'll be back on tickets in about a week. We'll get this resolved!

**Comment by rijkvanzanten** [comment]
@bjgajjar wasn't this the problem that the user interfaces didn't have the correct relational type or something? I remember talking through a solution where the two user types (`user_created` and `user_updated`) were both considered m2o types as well

**Comment by rijkvanzanten** [comment]
@urvashithakar lets not add random conditions everywhere for specific usages like this. The user fields should be a relational field like any other m2o, which means that the avatar should be returned when using the `fields` parameter, as the avatar is another m2o to directus_files.
