### ISSUE TITLE
Toggle Icons only toggle first Toggle Icon (v7.3.1)

### ISSUE THREAD

**Issue by jenniferneale** [directus/app#2061]
I'm not sure if you'll be able to replicate this since we're using a fork of v7.3.1, but we haven't touched the interfaces at all, and I thought it was worth a shot in case you might be able to help.

Our Marketing folks really like the Toggle Icons so we can add helpful color to the toggles, but when we have more than one Toggle Icon on a page, only the first one works. Eg, if you create two Toggle Icons on a Page, A and B, clicking B will jump the page to A, and A will have toggled instead of B.

Are you able to observe this also, and can it be fixed? For now we've changed all our Toggle Icons back to regular Toggles.

**Comment by benhaynes** [comment]
I know this is an older version, but let's check and make sure it's working in the latest before closing.

**Comment by rijkvanzanten** [comment]
Thanks for pointing this out @jenniferneale! I've updated it on the develop branch of this repo. It'll be released soon.

Please make sure to update your fork from upstream or implement https://github.com/directus/app/commit/72017387b82a64b9b523056d408afdb50030e9e0 manually

**Comment by jenniferneale** [comment]
Hurray! Thank you!
