### ISSUE TITLE
Query/filter state recall for collection lists

### ISSUE THREAD

**Issue by evrimoztamur** [directus/app#2066]
I have dug through the documentation for the app end of Directus. One feature that is either missing or not documented is being able to _save_ and later _recall_ the filters for collections.

Is this already available in the app? If not, which part of the code should I refer to for implementation.

**Comment by rijkvanzanten** [comment]
You're referring to Bookmarks. Whenever you have a set of filters active you'd like to recall later, you can click the Bookmark button:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/9141017/64994985-116d6c80-d8a8-11e9-8ba0-794a33dc85b5.png">

to save the current view (including filters and preferences) to recall it later.

[Screenrecording](https://rijks.space/screenrecordings/directus/add-bookmark.mov)
