### ISSUE TITLE
When typing the value of a Dropdown option, display gets corrupted if a new option starts with the name of a previous option

### ISSUE THREAD

**Issue by mpfrenette** [directus/app#2070]
When create a Drop Down item, if you create a new item which starts with the name of the previous item, the system will become confused, probably because the value of an item is the ID of the div.

How to replicate:

Field type drop down
Create 3 values:
1 ) Name: Text, value: text
2 ) Name: Image, value : image
3 ) Name : Text and Image, value: text_image

When you type text, it will break the display, trying to match it to above

You will discover that will now be editing the original item (Text) but with the label of Text and Image, thus overriding it.

Saving at that point will remove the first item.

But if you paste it, it works, because "text" isn't used in the new item.

**Comment by bjgajjar** [comment]
@rijkvanzanten -  It's the issue of a `repeater` interface. `Dropdown` consider the `repeater` interface for choices. So let's finalize https://github.com/directus/app/issues/1996 first and then start the work on it :)

**Comment by rijkvanzanten** [comment]
Setting the options in a dropdown uses the key-value interface in v8+, which solves the OPs problem.
