### ISSUE TITLE
Duplicating Advanced WYSIWIG fields causes the error: Trouble processing request. Try again after refreshing the page.

### ISSUE THREAD

**Issue by mpfrenette** [directus/app#2071]
I have indeed refreshed the page, but each time I try to create a field, I get the error:

Trouble processing request. Try again after refreshing the page.

And as such, the Create button keeps spinning forever.

This was on an Advanced WYSIWYG field, but it worked on other field types apparently.

**Comment by benhaynes** [comment]
Hmm, are you getting anything in your error logs?

**Comment by mpfrenette** [comment]
The Directus error log is as follows:

`[2019-09-17 16:50:40] api[_].ERROR: Directus\Database\Exception\FieldLengthNotSupportedException: field "content_es" does not support length in /home/[PATH]/src/core/Directus/Services/TablesService.php:1430
Stack trace:
#0 /home/[PATH]/src/core/Directus/Services/TablesService.php(534): Directus\Services\TablesService->validateFieldPayload
#1 /home/[PATH]/src/endpoints/Fields.php(54): Directus\Services\TablesService->addColumn
#2 [internal function]: Directus\Api\Routes\Fields->create
#3 /home/[PATH]/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#4 /home/[PATH]/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#5 /home/[PATH]/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#6 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#7 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#8 [internal function]: Slim\DeferredCallable->__invoke
#9 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#10 /home/[PATH]/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(120): Slim\Route->Slim\{closure}
#11 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#12 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /home/[PATH]/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#16 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#17 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#20 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#21 /home/[PATH]/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#22 /home/[PATH]/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#23 /home/[PATH]/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#24 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#25 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#26 [internal function]: Slim\DeferredCallable->__invoke
#27 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#28 /home/[PATH]/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#29 /home/[PATH]/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#30 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#31 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#34 /home/[PATH]/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#35 [internal function]: RKA\Middleware\IpAddress->__invoke
#36 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /home/[PATH]/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#40 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#41 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /home/[PATH]/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
#45 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#46 /home/[PATH]/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#47 [internal function]: Slim\DeferredCallable->__invoke
#48 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#49 /home/[PATH]/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#50 /home/[PATH]/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#51 /home/[PATH]/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#52 /home/[PATH]/src/core/Directus/Application/Application.php(161): Slim\App->run
#53 /home/[PATH]/public/index.php(5): Directus\Application\Application->run [] []
`

**Comment by mpfrenette** [comment]
It thus appear to indeed be a duplicate of the earlier issue...

**Comment by mpfrenette** [comment]
This is a duplicate of : https://github.com/directus/app/issues/2027

So I am closing it.
