### ISSUE TITLE
Auto draft save while editing the collection

### ISSUE THREAD

**Issue by anelad** [directus/app#2072]
Having a feature to save a draft automatically when the user editing the item would be great. 

But there are some problems exists. For example; what if the user did not enter a `required` data yet? The first idea I came with creating a `collection_name_draft` shadow database table without any required fields.

**Comment by benhaynes** [comment]
Hey @anelad — good idea! We actually have this feature request already... but with a slightly different solution: https://github.com/directus/app/issues/762

Instead of saving a draft item through the API (which has issues of required fields, and junking up the database), we opted to save all edits immediately in local storage for the app. That means that if your browser crashes, or anything else... your unsaved content is safe and will be there when you open the app again.

I guess I'll close this as a duplicate unless you think yours is a better solution.

**Comment by anelad** [comment]
Better solution? I do not know. To keep local data what will we use? JSON? It cannot answer any data structure changes easily. Also, there might be different "apps" connecting to the same API.

**Comment by benhaynes** [comment]
Yeah, it would be the same format as the Vue.js store (some JSON format), and everything would be scoped to the project. We might need to have this as an option that can be turned off (or delete on logout) to avoid security issues. Right @rijkvanzanten ?

**Comment by anelad** [comment]
I completely agree with you about the toggle thing. But do not know the Vue end. It's too away from me; to edit a fecking Calendar Interface a bit, I spent 6 hours today. Why didn't you use Angular  :'D

**Comment by benhaynes** [comment]
The local storage save is for emergencies/accidents... the other ticket (required fields based on status) would allow users to save draft items at work and continue at home. So I think those two existing feature requests would solve all these issues.

**Comment by anelad** [comment]
OK then. Even I still think my way is easier than the other to implement; you implemented the Directus, you know better than me, especially if the subject is Vue or PHP :D

**Comment by rijkvanzanten** [comment]
A separate table for drafts feels a bit overkill, but we can think about / discuss a setting that will automatically save every 30s or so if an item has the Draft status. That being said, it'll blow up the directus_activity / revisions tables very quickly if we do

**Comment by benhaynes** [comment]
We definitely wouldn't have a separate table for drafts in limbo. Also we would need to either keep ephemeral edits in the app's local storage, or not save them in Directus activity. I think local storage is better for auto save edits (like how GitHub does it).

**Comment by anelad** [comment]
You're the boss'. If you say so. but I need to implement this use case quickly somehow, you may advise me via PM?

**Comment by benhaynes** [comment]
I don't have any advice on a quicker solution — but maybe you can extend the App to write data to a temp table on an interval.
