### ISSUE TITLE
Saving draft ignoring the required fields

### ISSUE THREAD

**Issue by anelad** [directus/app#2073]
Draft means draft; the user might not want to enter any required fields yet. Possibly requires the same implementation with #2072

**Comment by benhaynes** [comment]
Another good one... but another duplicate 😉 

https://github.com/directus/api/issues/1237

**Comment by anelad** [comment]
What! I've searched the issues for half an hour before adding :/ OMG! BTW, welcome back.

**Comment by benhaynes** [comment]
Haha, no problem... with multiple repos it can be hard to track down. Also, all feature requests are closed and marked `enhancement`... if that helps find them in the future:

https://github.com/directus/api/issues?q=is%3Aissue+required+label%3Aenhancement

**Comment by anelad** [comment]
Yeha, I searched 'app' repo, but not 'api'. Actually, I'm a bit confused about relevance of issues. Whatever, I will track down there from now. BTW, what about #2072 ?
