### ISSUE TITLE
Numeric input is sanatized too angry

### ISSUE THREAD

**Issue by Tobsic** [directus/app#2076]
# Bug Report

## Steps to Reproduce

1. Go to http://directus.app/#/collections/movies/583
2. Click in Runtime input (this is an integer field, but is the same for decimal fields)

Typing:

3. Replace all
4. Try to type `100.00.` (notice the dot at the end)

Copying:

3. Select all
4. paste `100.00.`

Copy to clear input:

3. Select everything
4. Delete using backspace or delete
5. Paste `100.00.`
6. Press backspace to delete the last dot

## Expected Behavior

Typing: Input value should be `100.00.`
Copying: Input value should be `100.00.`
Copy to clear input: Input value should be `100`

## Actual Behavior

Typing in Firefox: Input is cleared when you type the second dot
Typing in Chrome: Input is cleared when you type the first dot
Copying: Input is cleared
Copy to clear input: Input value is `100`

## Technical Details

- Device: Desktop
- OS: Arch Linux
- Browsers:
  - Chromium 77.0.3865.75
  - Firefox 69.0 (64-bit)

**Comment by benhaynes** [comment]
Thanks @Tobsic — what's the reason for the dot at the end?

**Comment by Tobsic** [comment]
> Thanks @Tobsic — what's the reason for the dot at the end?

In the beginning it was from changing a german formatted number by removing the separators (comma and dots) truncated the zeroes. In chromium it was even worse.
A value that is invalid should never be just cleared out. So, no special reason to have a dot in the end, just a case that I found really confusing ;)
