### ISSUE TITLE
Number formatting in edit view

### ISSUE THREAD

**Issue by Tobsic** [directus/app#2077]
Formatted numbers are much more easy to read. That's why it would be helpful to format numbers in the edit view as well. At least when the input doesn't have the focus. If the number will be not formatted while editing, it would also be helpful to keep track of the desired cursor position while clicking into the input field.

Example:
Current input value is `4000000`, formatted as `4,000,000` and you click between "4" and ",", the result should be `4|000000`. If possible, `4|,000,000` would be even better, but keeping this formatting right while editing is hard and can easily lead to flimsy behavior.

**Comment by benhaynes** [comment]
I agree with this, and see two different options:

1. We could use a "masked" input to accomplish what you're describing (in the input itself)
2. We could add a formatted value beside/below the input that is tied to the value

Number 1 seems cleaner, but we'd need to make sure it works perfectly.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
