### ISSUE TITLE
SVG grafics have no preview

### ISSUE THREAD

**Issue by Tobsic** [directus/app#2078]
# Bug Report

## Steps to Reproduce

1. Go to https://directus.app/#/collections/movies/583
2. Drag'n'Drop an SVG file to the Poster area
3. Click on "Existing" button to select a new Poster file
4. See the SVG without preview

## Expected Behavior

Preview of the SVG grafic is shown in Choose One popup

## Actual Behavior

The SVG file is shown without preview in Choose One popup

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/4171703/65148093-cd9d7300-da1f-11e9-9e95-3e9fa90f1843.png)

## Technical Details

- Device: Desktop
- OS: Arch Linux
- Browsers:
  - Firefox 69.0 (64-bit)
  - Chromium 77.0.3865.75

**Comment by urvashithakar** [comment]
Hello @Tobsic,
As mentioned in directus [documentation](https://docs.directus.io/advanced/requirements.html#php-extensions), `imagick` php extension is required to create thumbnail for SVG.

**Comment by Tobsic** [comment]
Hi @urvashithakar
Sorry, didn't notice that one. Thanks a lot for pointing me there ! :)
