### ISSUE TITLE
A many-to-one interface with a sorted dropdown - How to commit?

### ISSUE THREAD

**Issue by petershaw** [directus/app#2084]
Hi, I want to have a dropdown for the `many-to-one` field that takes care of sorting. The list in the table is highly based on the sorting. Besides my personal must have, why is the dropdown not sorted anyway? Every list is sorted - if the sorting is turned on, but not the values in the dropdown. 

I figured out, that I can change this behaviour in `./src/interfaces/many-to-one/input.vue` 

```
      const params = {
        fields: "*.*",
        meta: "total_count",
        limit: this.options.threshold,
	// sort the results 
        sort: "sort" 
      };
```

But what is the best way to do it? 
I have directur-app in a submodule in my project git, because i want to have it as a separate, updatable git but inside my big deployment. 

Ok, what can I do? 

- Clone the code from “many-to-one” and write my custom interface? 
- Fix this behaviour in “many-to-one” and submit for a pull request? 
- Fix this inside the code and stick to the Version I’ve got? 
- Anything else? Can I overwrite a system interface with my own one? 
- Should I overwrite the file in my Dockerfile before i build the app?
- ... 

Thanks for any suggestion on how to handle changes in system interfaces without loosing updatability.

**Comment by benhaynes** [comment]
Hey! I think this was just an oversight. The best thing to do is:

> Fix this behaviour in “many-to-one” and submit for a pull request?

Thank you!! 😄

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
