### ISSUE TITLE
One to Many only one entry is saved and data gets overwritten

### ISSUE THREAD

**Issue by TheFudge** [directus/app#2086]
When I try to create a One To Many relation between two collections, something weird is happening.
I am using 2.0.18, I started with .16 and upgraded just now, but the error persists.

I created a collection with a string and a one to many relation to another collection that contains strings and integers.
When I try to select two entries it sometimes displays three entries and without a info text.
But even if two entries are shown in the list, after saving, the default_text column gets set to on eof the two entries. (e.g. on says button1 the other one button2, then after that both are called button2.)

Can you help me?

**Comment by benhaynes** [comment]
Hey @TheFudge — we'll need a little more info to successfully troubleshoot this one. Could  you include some screenshots, a schema, error logs, server/db details, etc?

**Comment by gianniskarmas** [comment]
I also had this problem with one2many and went through the demo app to find an example. Realised that there isn't any field in the demo using this relation. Without an example and getting the fields messed up whenever I tried it ended up only using many to many relations.

**Comment by benhaynes** [comment]
Interesting! We'll need to add a O2M into the demo... haha, I can't believe we don't have any! 

https://github.com/directus/demo-sql/issues/3

**Comment by rijkvanzanten** [comment]
Try updating to a newer version of Directus. The API is currently on 2.6.0.

**Comment by rijkvanzanten** [comment]
I'm not seeing this behavior. The OP was from a very outdated version, so I'm assuming this has been fixed in the meantime
