### ISSUE TITLE
Initial login page language form window.navigator.language

### ISSUE THREAD

**Issue by everyx** [directus/app#2087]
Hi, guys,

I am from China, and I can't find anyway to change the login page language, so can we use the default language from `window.navigator.language`? it's more flexible and friendly. :)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
This feature has been implemented in https://github.com/directus/app/pull/2113

**Comment by everyx** [comment]
@rijkvanzanten sorry about this, but it still don't use browser's default language as default language for login page when the user not logged in yet.

Can we use project `default_locale` or browser's default language from `window.navigator.language` as a default language when use is not logged at all?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
