### ISSUE TITLE
Cannot login to the app after upgrade

### ISSUE THREAD

**Issue by gurumark** [directus/app#2094]
Hi,
I upgraded to the latest version of app and api because I wanted to test the latest authentication flow and timeout issue fix.
Now, after logging in I get:
Server Error
Something is wrong with this instance’s server or database.
This error started happening after a successful login. It seems like instead of timeout and it goes into this error.
There is nothing wrong with the databases, I don't see any error with the previous versions. 
Thanks for the help in advance.

**Comment by bjgajjar** [comment]
> I wanted to test the latest authentication flow and timeout issue fix.

The new Auth flow will be in the next release. We don't have it in this one.

>Now, after logging in I get:
Server Error

That's not the case here actually. I tried with the fresh installation and able to log in as well as accessing the `APP` smoothly. Thus It will be great help if you provide some technical details. Like your PHP version, MySQL version etc.

**Comment by gurumark** [comment]
As I said in my email, this issue happened after I upgraded to 7.11 in app and 2.6 in Api. I simply did a git pull. I have 1 app and 2 apis running in two different subdomains. PHP 7.2 and MySQL is 5.7.

<a href="https://ibb.co/hfFKrtv"><img src="https://i.ibb.co/sH9FcMr/diserror.png" alt="diserror" border="0"></a>

**Comment by bjgajjar** [comment]
Let's connect over slack for the further discussion. [Here](https://directus.chat) is our slack channel.

**Comment by yarick2000** [comment]
@bjgajjar , I think its the same problem as here: https://github.com/directus/api/issues/1316

**Comment by gurumark** [comment]
I agree.
