### ISSUE TITLE
After successful installation no options ......

### ISSUE THREAD

**Issue by bikramtpa** [directus/app#2098]
I installed a latest version of Directus, and logging into admin is without option to create collections, .... neither any errors on js console. 
what is the issue ........
![1569585102073](https://user-images.githubusercontent.com/454848/65767532-cc162e00-e136-11e9-8c9d-4241bbefb771.png)

**Comment by benhaynes** [comment]
Did you hover over the user menu and go to settings? That's where you add/enable new collections.

**Comment by bjgajjar** [comment]
![image](https://user-images.githubusercontent.com/19200178/65768186-de4f9680-e14d-11e9-99e2-e02b6fcddd90.png)

On a hover of user name, you will find the Admin settings. From there you will able to find the collections :) 

If you need any help, or just have general `Directus` or `PHP` questions, we have a vibrant Slack
community that typically always has someone willing to help. You can connect in our slack [channel](https://directus.chat)

**Comment by bikramtpa** [comment]
aha!!!!!!!!!!!!! My eyes!!!!!!!
