### ISSUE TITLE
Sign in to different databases not working

### ISSUE THREAD

**Issue by alengodev** [directus/app#2101]
Signing in to the first database which is configured in api.php is working fine, but selecting a different database like api.2nd_database.php isn't working any more in 7.11.0.

The console log shows 401-errors and {code: 108, message: "User not authenticated"}

After a rollback to 7.10.0 all works fine.

![Bildschirmfoto 6](https://user-images.githubusercontent.com/25492962/65798913-30ef7980-e173-11e9-8abc-019a10b296f3.png)

**Comment by yarick2000** [comment]
I think this is also a duplicate of this one: https://github.com/directus/api/issues/1316

**Comment by alengodev** [comment]
I don't think so - the api is working great during the problems with the app.

**Comment by yarick2000** [comment]
Try to use public and secure key from the default project ('_') with the project that doesn't work for you. You may need temporarily to create a copy of the user from the default database in a problematic one. If after that things will work for you - then the issue is API related.

**Comment by yarick2000** [comment]
Another option - find a method getSecretKey in API code and replace the default value of the parameter ('_') with the name of your project and then see if starts to work for you

**Comment by alengodev** [comment]
> Try to use public and secure key from the default project ('_') with the project that doesn't work for you. You may need temporarily to create a copy of the user from the default database in a problematic one. If after that things will work for you - then the issue is API related.

hey yarick2000, that worked for me - thanks!
