### ISSUE TITLE
No option to clean up combo selection for non-required O2M field when value was previously set.

### ISSUE THREAD

**Issue by yarick2000** [directus/app#2102]
Hi guys, I've found that in case when O2M field is marked as non-required (the 'required' trigger is not set), there is still no way to reset the combo selection. The first item with a 'Select XXX' message is always disabled, though in this specific case it should be available for selection, so user will be allowed to write empty value to the field (meaning - remove related item in the junction table). There is probably a potential issue here in case when junction table has a Status field, but in case if Status field is not defined, then it definitely should be an option to cleanup combo selection... I understand that there is an alternate way for user to go directly to the junction table and remove item from there, but it will be much more convenient if he will be able to do this from the parent table interface. 
![image](https://user-images.githubusercontent.com/13006578/65799658-ae4ec600-e142-11e9-9ea7-250d81fcb8dc.png)

**Comment by benhaynes** [comment]
Hey @yarick2000 — I agree with this report, but did you try the field reset option? Clicking on the field label should expose a menu of options for resetting the value to `NULL`.

**Comment by yarick2000** [comment]
Ah, sorry, my bad, I didn't know about that functionality. Will try it out.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
I'll leave it open as a Feature Request (not a bug) since I agree it's intuitive to use the default placeholder option for `NULL` too. Thanks for following up!
