### ISSUE TITLE
JSON instead file preview in APP

### ISSUE THREAD

**Issue by makzimi** [directus/app#2112]
Installed Suite via cloning repository.
Created collection Pics with File and Text fields.
Uploaded images successfully.

In collection view instead of pic preview JSON content showed.

**Technical Details**
Ubuntu 16.04.1 LTS
Directus 7.11.0
Google Chrome Version 77.0.3865.90

<img width="536" alt="Screenshot 2019-10-05 at 11 34 35" src="https://user-images.githubusercontent.com/2886476/66252502-1e71d300-e765-11e9-90f5-8fc7f2ee7fdf.png">
<img width="691" alt="Screenshot 2019-10-05 at 11 34 24" src="https://user-images.githubusercontent.com/2886476/66252503-1e71d300-e765-11e9-9913-76195f1c6463.png">

**Comment by bjgajjar** [comment]
@makzimi - Not able to replicate it in the demo live site. 

![image](https://user-images.githubusercontent.com/19200178/66482046-ba7e4000-eabf-11e9-8a69-eeb515eb869a.png)

**Comment by rijkvanzanten** [comment]
@makzimi would you be able to create and send a database dump where this is happening for you?

**Comment by makzimi** [comment]
@rijkvanzanten can not reproduce it right now too. It began work fine after some refreshing browser. If I face that bug again I'll file here about it with dump.
