### ISSUE TITLE
Sorting by Status is alphabetical rather than using the sort order

### ISSUE THREAD

**Issue by mattgaspar** [directus/app#2117]
When sorting by the `Status` column shouldn't it be sorted based on the order that the statuses are setup in?  They are sorted in this order on the detail page but not on the list page.
Statuses are sorted alphabetically regardless whether the status field is set to just show the simple badge or show text.

![image](https://user-images.githubusercontent.com/811116/66530595-480c6080-eabd-11e9-881e-7552c71407a4.png)

**Comment by rijkvanzanten** [comment]
It's sorting by the saved value alphabetically now, but I do like the idea of keeping the sort order as set in the options here.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
