### ISSUE TITLE
Fields currently can not be hidden

### ISSUE THREAD

**Issue by edenprojectde** [directus/app#2119]
Fields can not be unchecked in the Permissions "On Creation"
The expected behaviour should be that they are hidden when unchecked, but use default Value when created.

![Screenshot_20191010_050110](https://user-images.githubusercontent.com/6115966/66535797-13c78d00-eb1b-11e9-9b6e-c6d70dbb8c4b.png)

Fields unchecked in the other groups(like Published etc) seem to only hide the Value, but not the field itself in the App.
The expected behaviour should be that they are hidden. And a required field needs to use the original Value so the form can still be sent.

**Update:**
After talking to Binal i made these 2 Videos trying to show what i am talking about:
https://youtu.be/KkrbX4fBUvM
https://youtu.be/5ej04il8AMs

My workaround for the time being was to remove this field and have a second Table Validate the publication status of my Blog entries. Not a direct fix i kinda thought i was using the Backend in someway wrong.

**Comment by edenprojectde** [comment]
If there is only read but not write permission on the field, the field is hidden on creation but not on edit.

I kind of found a way to enable what i wanted to accomplish so im closing this for now :')

**Comment by benhaynes** [comment]
Thanks @edenprojectde — goad you found a workaround in the meantime, but this is definitely a bug. Toggling the "Fields" for "On Creation" should hide the entire field... so I'm reopening this as a bug.

**Comment by edenprojectde** [comment]
Yeah i was kinda unsure at the end if it was something i did wrong. There is some weird behaviour going on as i later worked around with this for a bit.

Seems like there is also a State issue. Can't really put my finger on it though.
