### ISSUE TITLE
Multiple select inside collection listing page not working when permissions are set as ROLE-ONLY for UPDATE or DELETE

### ISSUE THREAD

**Issue by lucianospi** [directus/app#2123]
# Bug Report
This happens with APP 7.10.0 and API 2.6.0.

BULK SELECT or multiple select not working inside collection listing page when collection permissions are set as  ROLE-ONLY for UPDATE or DELETE.

# Steps to Reproduce
Using admin account create a simple collection "HELLOWORLD" (eg. with status and text interfaces). 
Then create a user role "ROLE01" and set permissions on "HELLOWORLD" as follow:
- CREATE: _all_
- READ: _role-only_
- UPDATE: _role-only_
- DELETE:  _role-only_
- COMMENT: _update_

Create a user "IAMUSER01" and associate it to "ROLE01". 

Log in as "USER01" and create some new items in the collection "HELLOWORLD". 

# Expected Behaviour
Logged in as "USER01", inside the listing page of collection "HELLOWORLD" I can BULK SELECT or select multiple collection items.

# Actual Behaviour
Logged in as "USER01", inside the listing page of collection "HELLOWORLD" when I click on the BULK SELECT checkbox or the check box to select individual items nothing happens. Items do not get selected.
# Other Context & Screenshots
The only condition to enable the bulk select is to change the collection permissions (for role "ROLE01") as:
- CREATE: _all_
- READ: _role-only_
- UPDATE: _all_
- DELETE:  _all_
- COMMENT: _update_
However this configuration expose possibility of accidentally update or delete collection items belonging to another ROLE by using the API.

**Comment by urvashithakar** [comment]
If the user has above mentioned permission(Role Only) and we hide the `user_created` field from the info sidebar of listing; this error will occur. Which is obvious. Let me provide more detail.

API will consider those fields which are selected in the info sidebar and to check the permission for update and delete based on the role while bulk selecting; the condition will be on the `user_created` field. Basically `user_created` field contains the id of the user. Without the `user_created` field we can not find the role. This issue persists for the `status` field too if the collection has `status` field.

@rijkvanzanten Let me know your thoughts.

**Comment by benhaynes** [comment]
It seems like this should work properly even if the `created_by` is not included. The API should always fetch/check those columns to validate permissions.

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/app/pull/2138
