### ISSUE TITLE
Status 'Default value' problems

### ISSUE THREAD

**Issue by alextomas** [directus/app#2124]
Hi everebody,
I've a problem with _default value_ in _field status_

I attach two images with the problem. 
I try explain it: 

1. I put default value '**draft**' in status field of _News collection_ and I save changes. 
2. After, I edit another time. Default value is 'raf'

Whats is the problem?
![Captura de pantalla 2019-10-10 a las 14 08 49](https://user-images.githubusercontent.com/2083214/66567734-24522480-eb68-11e9-847c-12b0e3ea08f6.jpg)
![Captura de pantalla 2019-10-10 a las 14 09 01](https://user-images.githubusercontent.com/2083214/66567735-24522480-eb68-11e9-8f27-9be88e876e27.jpg)

**Comment by JbalTero** [comment]
@alextomas Upgrade your MariaDB to 10.2, the `raf` issue happens when you use 10.1

**Comment by JbalTero** [comment]
This is a duplicate of https://github.com/directus/api/issues/1172#issuecomment-519856968
