### ISSUE TITLE
Preview is set as required by default and can't be changed

### ISSUE THREAD

**Issue by obruehl** [directus/app#2125]
The preview button is set to be required by default and it is deactivated so its not possible to change it:

![image](https://user-images.githubusercontent.com/417516/66634667-d09a1680-ec0d-11e9-8230-2b6dc4c5345e.png)

**Comment by bjgajjar** [comment]
The `required` will be disabled for `alias` type and `preview` is an alias type interface.

@rijkvanzanten - What should the next steps for this issue?

**Comment by obruehl** [comment]
I think the main issue is that the preview button is set as required by default. If the default would be not required the fact in this case the checkbox is disabled it's not a problem. For my understanding the preview button should never set required.

**Comment by bjgajjar** [comment]
> I think the main issue is that the preview button is set as required by default.

No. That's not the case actually. Preview is not required by default - Neither from backend nor from the frontend. Kindly correct me if I misunderstood something :) 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/19200178/66742669-cdb15700-ee95-11e9-94f2-3ab740c0173e.gif)

**Comment by benhaynes** [comment]
I have also tested this interface and saved an item without a "required warning". Perhaps it's another field in your setup causing the issue @obruehl. I'll close this since we can't replicate.

**Comment by obruehl** [comment]
Actually its the same type of field. In my case its set as required. Is it possible I am using a different version or is this configured globally where I can change it:

![Nis8yaldgO](https://user-images.githubusercontent.com/417516/66826405-a8335480-ef4c-11e9-807e-a0635cf44f41.gif)

**Comment by bjgajjar** [comment]
Yes - Please check your version. It seems like you are using the older one. So just upgrade it with the latest one. You'll get rid of this issue :)
