### ISSUE TITLE
Add default registered user Role

### ISSUE THREAD

**Issue by ssp-omsk** [directus/app#2128]
Add default registered user Role.
Now, when using Api at public projects Developers have to use filters to add new registered user a role to manage their access to collections. It would be very usefull to have default role for that. Same functionality seen in many other headless cms and used widely.

Thanks for your work)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
