### ISSUE TITLE
Implement a "path" field in meta.json so interface doesn't need to be at root

### ISSUE THREAD

**Issue by jkjustjoshing** [directus/app#2129]
# Problem 
When authoring a Vue extension (page, interface, etc), the `.vue` files need to be transpiled. A standard folder setup (including the one created with the [extension-toolkit](https://github.com/directus/extension-toolkit)) has a `./src` and a `./dist` folder, with the files to be loaded by the browser in the `./dist` folder.

Directus does not currently have a way to load extension files not at the root of the extension folder. 

# Proposed change

Add a new property to `meta.json` called `"path"` that has a relative path to the extension files. Defaults to `"./"`.

# How this helps

With a `"path"` property, the current [extension-toolkit](https://github.com/directus/extension-toolkit) setup will work. The only change required will be moving the `meta.json` file up a directory to the extension root, and adding `"path": "./dist"` to it.

**Comment by jkjustjoshing** [comment]
One potential solution: Modify the [loadExtensions()](https://github.com/directus/app/blob/master/src/helpers/load-extension.js) function to first load the `meta.json` file, find the `path` property, and add that to the URL it uses to request the JS/CSS files.

**Comment by jkjustjoshing** [comment]
Another potential solution: Load the `meta.json` file [here](https://github.com/directus/app/blob/master/src/components/extension/interface/display/display.vue#L152) (and equivalent for other extension types), and define the path passed to `loadExtensions()` including the `path` value from `meta.json`.

**Comment by jkjustjoshing** [comment]
I just spent some time digging into a potential solution for this, and I discovered that Directus infers a `path` property already, which is the location of the `meta.json` file itself. Directus adds this property to the `meta.json` data structure sent to the frontend with the `api.getInterfaces()` call.

Adding an incorrect `path` value to `meta.json` that includes a `./dist` subdirectory seems to not negatively impact the loading of the `meta.json` data, while tricking Directus into accessing the extension files from within the `./dist` subdirectory. 

This is a workaround that solves the issue I was trying to solve, but it's 100% undocumented behavior that could break at any time. So I'd still advocate for a true documented solution to this issue.

**Comment by benhaynes** [comment]
Thanks @jkjustjoshing — great explanation and research! 😄 

Thoughts on this approach, @rijkvanzanten @bjgajjar?

**Comment by jkjustjoshing** [comment]
While this still might be a useful feature, the primary use case I had for it has been addressed in [this issue](https://github.com/directus/extension-toolkit/issues/13). I have documented those suggestions in [this PR](https://github.com/directus/extension-toolkit/pull/16).

Feel free to close this ticket, or keep it open if you still view it as a useful suggestion.

**Comment by rijkvanzanten** [comment]
I don't think the added overhead is worth the flexibility here. As we've talked about before in the referenced issue, the idea is that you upload just the `dist` folder to your API in order to install the extension. Seeing that the files you upload are most likely generated, the format really shouldn't matter, as the user isn't expected to touch those files manually
