### ISSUE TITLE
User Menu disappears when turning off File Library permissions for a user role

### ISSUE THREAD

**Issue by iamjoshkendall** [directus/app#2135]
Hello, I wanted to disable the file library for a project and I thought disabling the permissions for it on a new user role would accomplish that. When I set the permissions to none the user menu completely disappears for that user role. I am using a fresh install of 7.11.0 running locally using the built-in PHP web server and MySQL 8.0.17 on OS X Catalina.

Lines 90 through 97 of the `user-menu.vue` component led me to believe that setting the permissions to none should only hide the file library link, not the entire menu.

```
if (this.permissions.directus_files.read !== "none") {
    links.push({
        path: "/files",
        name: this.$t("file_library"),
        target: "_self",
        icon: "collections"
    });
}
```
I changed the permissions back and the user menu returns. I tried setting only the read permission to none thinking perhaps if the entire collection was set to none that it's state data may not be available and therefore not have a `directus_files` object or a `read` property to check.

Admin User showing the user menu:
<img width="1392" alt="admin-role" src="https://user-images.githubusercontent.com/46183/66722564-4bfdf280-eddd-11e9-8b97-40a57787c04d.png">

User Role with File Library permissions set to none:
<img width="1392" alt="user-role-with-no-file-library-permissions" src="https://user-images.githubusercontent.com/46183/66722565-4bfdf280-eddd-11e9-8758-4a8631cfd910.png">

**To reproduce the issue:**

1. Install a fresh copy of 7.11.0
2. Create a user role with File Library permissions set to none
3. Add a user to that role
4. Sign in as that new user

**Comment by rijkvanzanten** [comment]
Your assumption is right. It should only hide the file library link from the menu, not the whole menu itself
