### ISSUE TITLE
WYSIWYG Value not showing up in Translation Interface

### ISSUE THREAD

**Issue by edenprojectde** [directus/app#2136]
When using the Translation Field with a Table containing a WYSIWYG, the value seems to be missing when Viewing the Entry as a single Item.

I could solve this by bruteforcing it using the o2m relation, into the field like this:

**input.vue in the translation interface**
```JavaScript
   created() {
    console.log(this.relation.field_many.field);
    console.log(this);
    console.log("Translation field created:", this.value);
    this.value.forEach((v,i)=>{
        // Loop over all field_many-translation values in database via the field_many duh
        Object.keys(v[this.relation.field_many.field][this.id.split("-")[1]][i]).forEach((v2)=>{
          console.log("Key:"+v2);
          // Take the values from the o2m field and have a look at it 
          console.log("After:",v[this.relation.field_many.field][this.id.split("-")[1]][i][v2]);
          // Look at value BEFORE change
          console.log("Before:",v[v2]);

          // Check that we dont override the field_many in our value
          if(v2!=this.relation.field_many.field)
          v[v2]= v[this.relation.field_many.field][this.id.split("-")[1]][i][v2] // Overwrite all Values to we get no null fields anymore
        })
    });
    console.log("Translation field created 2:", this.value);
    this.fetchLanguages();
  },
```

I assume it is the same thing as https://github.com/directus/app/issues/1778 i also posted this solution to the problem there. I dont exactly know if it is the same issue.

**Comment by urvashithakar** [comment]
Hello @edenprojectde
Kindly provide your APP and API version.
And I am not able to replicate this issue in Directus Demo APP. So please provide some more information.

**Comment by edenprojectde** [comment]
Directus is v7.11, and the API is the current API i can pull with the Suite.

http://directus.benjamin-krippner.de/admin/
-u ext@ext.uk
-p extuk
This is the unmodified Suite with the latest it pull.

**Comment by urvashithakar** [comment]
Hello @edenprojectde 
Don't know the reason behind the difference between the behaviours of your server and our live demo server. But it seems like the same code works as expected at our end but not worked at your server.

[i] Directus APP behaviour
    If you check then; it's returning the `content` in parent level as well as child level

    
![image](https://user-images.githubusercontent.com/50007336/66903326-e5b4e200-f01f-11e9-9ccf-061a10862ac2.png)

[ii] Your server's behaviour
   Here, the parent does not contain the `body` but the child contain it

![image](https://user-images.githubusercontent.com/50007336/66903621-712e7300-f020-11e9-9f91-cd68ab5aa660.png)

**Comment by edenprojectde** [comment]
You seem to be right, something is wrong with my App, this does not happen on a pure new install.

It's weird because git tells me my Suite install is latest on both server instances; on one of them it seems to work, on the other one for some reason it does not. If i find the cause of this i will post it here. But otherwise i will close this for the time being as this could be a server setup issue.

**Comment by edenprojectde** [comment]
So i will follow up as promised.
I tried some things and finally got it working, not the specific table, but it was a test anyways.

The Problem could've been 1 of 2 things:
- The collation of the table was wrong. (it was set to latin1)
  - I got this hint from the troubleshooting section in the docs that the collation should be utf8mb4
  - Look below for a Guide to fix this in an unrecommended way. / I don't know anyother way so don't ask me for the edgecases i just know it breaks stuff.
- I needed to install the API seperately for some reason.

-----

# Guide ...

to set the collation of a database to a different one, i have to say though i DONT recommend this except for experimental reasons or you KNOW what you are doing. You can definetly make a lot of data broken if your Database uses collations which can not be converted correctly!
- First set the default Database Collation to utf9mb4 with this in your mysql CLI:
```SQL
ALTER DATABASE directus CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
- Second generate single Queries via this to convert all tables to utf8mb4(**change {directus} to your directus database**):
```SQL
SELECT CONCAT("ALTER TABLE ",TABLE_SCHEMA,".",TABLE_NAME," CHARACTER SET utf8mb4;   ",
    "ALTER TABLE ",TABLE_SCHEMA,".",TABLE_NAME," CONVERT TO CHARACTER SET utf8mb4;  ") 
    AS alter_sql
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = "{directus}";
```
- Third execute ALL these Queries

----
## Little hint: Your old table will NOT work, you will need to recreate the table incl. the content-table.
