### ISSUE TITLE
Only One Custom Page Displaying in Sidebar

### ISSUE THREAD

**Issue by RafaelRueda** [directus/app#2137]
Hi everyone,

Just wanted to know if there is a feature to make a custom page private for some users specifically.

![image](https://user-images.githubusercontent.com/10001883/66728341-90f44a00-ee1a-11e9-9eea-04f20eb66ec8.png)

This would be my custom page, and also how do I do to create a second custom page?
because the actual folder of my pages are these, and the second page is not recognized

![image](https://user-images.githubusercontent.com/10001883/66728368-c5680600-ee1a-11e9-8730-9d7580db042f.png)

Thanks a lot, 

I'm using the latest version of Directus Suite

**Comment by benhaynes** [comment]
For the Module Page permissions, you can set the "Nav Override" for a role, deciding if they can see it or not. Not sure about the second page not being recognized... @rijkvanzanten ?

**Comment by RafaelRueda** [comment]
> For the Module Page permissions, you can set the "Nav Override" for a role, deciding if they can see it or not. Not sure about the second page not being recognized... @rijkvanzanten ?
> 
> https://docs.directus.io/guides/roles.html#nav-override

Thanks Ben, about the Nav override, it helped me for another thing. But i didn't ask you correctly, 
Let's say i want to display on a custom page 3 collections but only some users will be able to see the content of the first and third collections and others only the second collection. would that be possible just by using the "roles and permissions functions"? 

Thanks for your time.

**Comment by RafaelRueda** [comment]
> Ah, gotcha. You should be able to read the permissions of those collections (based on the user), and conditionally show things within your extension code. Does that seem correct

Thanks for answering. Just left the question about why it doesn't show the second custom page on the left.

Thanks

**Comment by rijkvanzanten** [comment]
It's reading the meta.json files to determine the IDs / names of the pages. Did you update those to be unique?

**Comment by RafaelRueda** [comment]
> It's reading the meta.json files to determine the IDs / names of the pages. Did you update those to be unique?

I excecute on these steps

"directus-extensions create page helloWorld”
“cd helloWorld” 
“directus-extensions build”

Until here, i refreshed Directus and nothing happens, until i copy the created folder called "dist" on HelloWorld folder (C:\wamp64\www\directus\public\extensions\custom\pages\helloWorld) to the previos folder, 
“C:\wamp64\www\Directus\public\extensions\custom\pages”.  

I will show you the page folder
![image](https://user-images.githubusercontent.com/10001883/67152760-748d5d00-f2b3-11e9-87ee-5b7cf0df0510.png)

![image](https://user-images.githubusercontent.com/10001883/67152770-95ee4900-f2b3-11e9-9870-9e1954674414.png)


as you said, i would need to add the secondPage on the meta.json file which is this one
![image](https://user-images.githubusercontent.com/10001883/67152769-8ff86800-f2b3-11e9-9211-8b35f7bcb589.png)

but once i add the second on the json file, it only overlaps the first page.

**Comment by rijkvanzanten** [comment]
If you compare the `meta.json` files from the `helloWorld` folder and your new `dist` folder, are they the same?

The app will read these `meta.json` files in order to determine the name and URL for these custom pages, so if they're the same, the app will see them as 1

**Comment by RafaelRueda** [comment]
> If you compare the `meta.json` files from the `helloWorld` folder and your new `dist` folder, are they the same?
> 
> The app will read these `meta.json` files in order to determine the name and URL for these custom pages, so if they're the same, the app will see them as 1

On HelloWolrd folder i got some files which are the same to the dis folder on custom page as i copy and replace it there...
But in case I want to add a second custom page that in this case would be "SecondTest", how do I do that? sorry but I don't get it.
These two are my meta.json

![image](https://user-images.githubusercontent.com/10001883/67257320-cbd13000-f461-11e9-83b8-21660a07dd4c.png)

or do i need to mix something before running "directus-extensions build"

Thanks for your time,

**Comment by rijkvanzanten** [comment]
Ah I see, the files in the nested `dist` folders of both new extensions are supposed to be the root level

`/pages/helloWorld/meta.json` instead of `/pages/helloWorld/dist/meta.json`

**Comment by RafaelRueda** [comment]
ohhh now i see what the problem was. The thing is that every time that you run "directus-extensions build" it creates a new folder "dist" inside the custom page and i thought it was the correct...
Now i know that i have to move the "meta.json" to "/pages/helloWorld" 
is there a way to modidy the script "directus-extensions build" to create it on the correct folder?

Thanks a lot!.
Rafael

**Comment by rijkvanzanten** [comment]
The build / watch commands support an `--output` flag you can use to have it build to any destination. I personally like to work in a repo / folder right next to my `/api` folder and have it build to the correct folder using `directus-extensions watch --output ../api/public/extensions/custom/pages/helloWorld`
