### ISSUE TITLE
M2M: Collections with nested M2M does not display proper values

### ISSUE THREAD

**Issue by eudora-fabia** [directus/app#2139]
## Steps to Reproduce

- Create these collections:
	- `schedules`
	- `venues`
	- `getting_there`
- Create these relationships:
	- `schedules` many-to-many `venues`
	- `venues` many-to-many `getting_there`
- Create `schedule` item with:
	- venues item
	- getting_there item
- View created `schedule` item
- Click the 1 `venue` item

## Expected Behavior

The `getting_there` should display the `title`

## Actual Behavior

The `getting_there` should displays empty `title`

## Other Context & Screenshots

But when viewing the `getting_there` from `venue`, it displays the proper `title`, not empty.

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.4.0 build
- Directus App: 7.9.0

**Comment by onlinelessons** [comment]
When will this bug be fixed? We need a fix for this problem as soon as possible...

**Comment by eudora-fabia** [comment]
I have fixed this by manually compiling directus app to support `*.*.*.*`

**Comment by benhaynes** [comment]
This software is open-source, so there is no definite timeline for fixes unless someone submits a PR or financially sponsors the fix. We're working as fast as we can, but there are a _lot_ of things to do... and everyone has different priorities as to what should come first. 

All I can say is that we aim to have all (current) bugs resolved by the end of the year.

The `*.*.*.*` patch might work for some, but for others it will make the pages load extremely slow. It all depends on what data is in the collection.
