### ISSUE TITLE
Cell remains blank until page is saved

### ISSUE THREAD

**Issue by natetharp** [directus/app#2145]
After creating a new item, the "type" that is chosen from the select options is not visible in the table cell until after the page is saved.

This is how the content area appears before an item is added.
![1-no-content-items-created](https://user-images.githubusercontent.com/882331/67131754-b9819880-f1ba-11e9-9325-9eedbb89f35c.png)

After selecting "+ Add New", in the modal that appears, I select the type of item I'm adding.
![2-selecting-type-from-dropdown](https://user-images.githubusercontent.com/882331/67131805-f5b4f900-f1ba-11e9-9989-d2e98f499b83.png)

Then enter a text description.
![3-creating-item-form](https://user-images.githubusercontent.com/882331/67131804-f5b4f900-f1ba-11e9-8a78-e74922934403.png)

After selecting the "Save" button the modal closes and the item is added to the list, but the "Type" field is blank, even though one was selected.
![4-selected-type-doesnt-appear](https://user-images.githubusercontent.com/882331/67131744-b71f3e80-f1ba-11e9-926c-3cea48e54726.png)

But after saving the entire page, the "Type" that was selected then appears in the table.
![5-after-save-type-is-visible](https://user-images.githubusercontent.com/882331/67131743-b71f3e80-f1ba-11e9-8708-0c440d73af0e.png)

This ZIP has a `.mov` file that shows the process the screenshots attempt to represent.
[cell-remains-blank.zip](https://github.com/directus/app/files/3745859/cell-remains-blank.zip)

## Technical Details
Device: [Laptop]
OS: [Mac 10.13.6]
Browser: [Chrome 75.0.3770.142]
Directus: [7.7]
PHP Version: [7.1]

**Comment by urvashithakar** [comment]
Hi @natetharp,
I'm not able to reproduce the issue on[ Directus APP](https://directus.app). It seems like you are using the old version and the current version of the Directus is 7.11. 
So please update it to the latest version and try again.

**Comment by rijkvanzanten** [comment]
Please let us know if updating to the latest version solved the problem for you. We can reopen if not.

**Comment by natetharp** [comment]
Wanted to confirm that we've recently updated Directus to version 8.5.4 and this issue is no longer reproducible.
