### ISSUE TITLE
Custom page not showing data

### ISSUE THREAD

**Issue by RafaelRueda** [directus/app#2151]
Hi there,

I'm using custom pages with the lastest version of Directus Suite on Windows10 and hosted 
 with WampServer. 

 My custom page looks like this,
![image](https://user-images.githubusercontent.com/10001883/67254375-0a132300-f453-11e9-8a8e-ebf2f99f4280.png)

I'm trying to show the users data that I'm getting from the SDK js, on json format. which I verify that i have it and show it on the console  but i can't show it on the custom page table.

What am I missing or doing wrong? or what do i need to do in order to display the json data on the table?

This would be my code on the custom page

```
<template>
  <div>
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <div class="container mt-4" id="app">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Status</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="user in users" :key="user.id">
            <td>{{user.id}}</td>
            <td>{{user.status}}</td>
            <td>{{user.name}}</td>
          </tr>
        </tbody>
      </table>
    </div>
</template>

<script>
import DirectusSDK from "@directus/sdk-js";
import Vue from "vue";
window.Vue = Vue;
Vue.config.devtools = true;

const client = new DirectusSDK({
  url: "http://localhost/directus/public/",
  project: "_",
  token: "rafael"
});

export default {
  data: function() {
    users: []
  },

  //stars automatically once launched
  mounted() {
    client
      .getItems("users")
      .then(data => {
        this.users = data;
        console.log(this.users );
      })
      .catch(error => console.error(error));
  },

  methods: {
    showData: function() {
      client
        .getItems("users")
        .then(data => {
          this.users = data;
          return data;
        })
        .catch(error => console.error(error));
    },

    message: function() {
      return "User Data Table";
    }
  }
};
</script>

```

The console shows that the data is there 
![image](https://user-images.githubusercontent.com/10001883/67255256-7d1e9880-f457-11e9-93b9-446129220cc6.png)

also on network shows that it was requested and received

![image](https://user-images.githubusercontent.com/10001883/67255277-a3443880-f457-11e9-9fd9-232fb0b2c1f7.png)

Thanks a lot for your time,
Rafael

**Comment by rijkvanzanten** [comment]
In this bit:

```js
   client
      .getItems("users")
      .then(data => {
        this.users = data;
      })
```

`data`  that's returned in the `.then` is the response object, that in turn contains the `data` key. After this line, `this.users` will be `{ data: [...] }`, while your template is expecting `[...]`.

To make it work, refactor your getItems calls to:

```js
   client
      .getItems("users")
      .then(response => {
        this.users = response.data;
      })
```

**Comment by RafaelRueda** [comment]
> In this bit:
> 
> ```js
>    client
>       .getItems("users")
>       .then(data => {
>         this.users = data;
>       })
> ```
> 
> `data` that's returned in the `.then` is the response object, that in turn contains the `data` key. After this line, `this.users` will be `{ data: [...] }`, while your template is expecting `[...]`.
> 
> To make it work, refactor your getItems calls to:
> 
> ```js
>    client
>       .getItems("users")
>       .then(response => {
>         this.users = response.data;
>       })
> ```

Hi Rij,
Thanks for your time, 

I did what you said, and i got the data from the array but, i'm still getting "nothing" on the screen. 

this would be the code on the template to show it 

```
<div class="container mt-4" id="app">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Status</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="user in this.users" :key="user">
            <td>{{user.id}}</td>
            <td>{{user.status}}</td>
            <td>{{user.name}}</td>
          </tr>
        </tbody>
      </table>
    </div>
```

and this would be the script

```
export default {
  data: function() {
    users: []
  },

  //stars automatically once launched
  mounted() {
    client
      .getItems("users")
      .then(response => {
        this.users = response.data;
        console.log(this.users);
      })
      .catch(error => console.error(error));
  },
```

Still getting this empty table , but i can print evertyhing on the console.

![image](https://user-images.githubusercontent.com/10001883/67311443-fc52b180-f4d5-11e9-8925-947f5629317f.png)

**Comment by rijkvanzanten** [comment]
In Vue, you don't use `this` in templates, as everything is scoped:


```vue
<tr v-for="user in this.users" :key="user">
```

Should be 

```vue
<tr v-for="user in users" :key="user">
```

**Comment by RafaelRueda** [comment]
> In Vue, you don't use `this` in templates, as everything is scoped:
> 
> ```
> <tr v-for="user in this.users" :key="user">
> ```
> 
> Should be
> 
> ```
> <tr v-for="user in users" :key="user">
> ```

oh yes. Forgot to take away that from the template but it still the same problem.

**Comment by RafaelRueda** [comment]
Solved!

the problem was in this structure

```
export default {
  data: function() {
    users: []
  },
```


and it should be like this
```

export default {
  data() {
    return{
    users: []
     }
  },

```

**Comment by benhaynes** [comment]
Hey @RafaelRueda — was this a problem with the Docs, or just an accident on your side? I want to make sure our example are all accurate! Thanks for reporting back. :)

**Comment by RafaelRueda** [comment]
> Hey @RafaelRueda — was this a problem with the Docs, or just an accident on your side? I want to make sure our example are all accurate! Thanks for reporting back. :)

It was a problem on my side but it would be useful for others if you add some more information about the SDK I think.

Best regards,
Rafael.
