### ISSUE TITLE
Hover on collection names (long names)

### ISSUE THREAD

**Issue by lluishi93** [directus/app#2159]
# Feature Request

## What problem does this feature solve?

If a collection name is too long, it gets cut by the sidebar max width. With a hover effect that displays the full name, it would be a lot easier to navigate through the collections.

![image](https://user-images.githubusercontent.com/14786440/67515498-0bd12680-f69f-11e9-8d90-e39dda2fbfd8.png)

![image](https://user-images.githubusercontent.com/14786440/67515509-168bbb80-f69f-11e9-99cb-3b0d3039f07f.png)

## How do you think this should be implemented?

With a hover displaying a tooltip with the collection's full name

## Would you be willing to work on this?

I don't have time for that, I'm sorry.

**Comment by benhaynes** [comment]
We should plan to use our core tooltip library for this, positioning the tooltip in the below position (I think), and increasing the delay time a bit so they don't pop-up too much when unwanted.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
