### ISSUE TITLE
m2m issue on display

### ISSUE THREAD

**Issue by eudora-fabia** [directus/app#2165]
Using the Directus Demo, I created `artworks` m2m with `venues`.

[Here is the recording of the issue](https://drive.google.com/file/d/17LY5OsajVyNmfa__3uG9H2WV7HK1uNd8/view?usp=sharing)

**Comment by urvashithakar** [comment]
Hello @eudora-fabia ,
It seems like it is a duplicate of  #2139

**Comment by benhaynes** [comment]
I'll close this as a duplicate — @eudora-fabia, let us know if this is a separate issue.
