### ISSUE TITLE
Creating M2O — Missing Field

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2168]
When creating a M2O field, during setup the "This Collection — Field" is not shown. It should show the field name of the _current_ field.

![Screen Shot 2019-10-28 at 10 00 43 AM](https://user-images.githubusercontent.com/522079/67684944-7e295b80-f96a-11e9-9914-26ac1d10c1b6.png)

**Comment by rijkvanzanten** [comment]
Fixed in a0e55235
