### ISSUE TITLE
Creating O2M — Incorrect Fields

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2169]
When creating a new O2M field, the relation info is incorrect:

1. "This Collection -> Field" should not be set to `id`, it should be _this_ field's name
2. "Related Collection -> Field" is not showing the PK of the related collection as an option

![Screen Shot 2019-10-28 at 10 16 25 AM](https://user-images.githubusercontent.com/522079/67685808-20960e80-f96c-11e9-87ed-16910e49c91b.png)

**Comment by rijkvanzanten** [comment]
This is how it's supposed to work!

**Comment by benhaynes** [comment]
Oh my... confused M2O with O2M 

![Ugh](https://media.giphy.com/media/cJBY6cGpla8So1Pv1u/giphy.gif)
