### ISSUE TITLE
Translations — Easier Setup

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2170]
We could add a `directus_locales` system table on install (could include only English, or top 30 languages, etc). This would give us defaults for the `translation` interface, and let us hide those interface options within "Advanced Options" — making setup _much_ easier.

```
CREATE TABLE `directus_locales` (
  `code` varchar(20) NOT NULL DEFAULT 'en-US',
  `name` varchar(20) NOT NULL DEFAULT 'English',
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Rijk also mentioned that this could use a "Checkboxes" interface instead of a dedicated table. This is even cleaner, but might not work for some user's setups... and wouldn't be backwards compatible.

Right now our interface is called `translation`... we could create a new (optimized) one called `translations` (note the `s`) and deprecate the old one in the future.

Thoughts @bjgajjar @rijkvanzanten?

**Comment by rijkvanzanten** [comment]
I like it. I don't think we need a dedicated collection for it though. The list of languages shouldn't change, and by using a autocomplete tags style interface it's rather easy to set up from options too. By defaulting to the `en-US` format everywhere, we can ensure that things like the `lang` parameter work correctly too

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
