### ISSUE TITLE
Custom Layout Extension won't show items

### ISSUE THREAD

**Issue by SEGVeenstra** [directus/app#2179]
I 'm creating a layout extension. (Directus App 7.11.0)
I've used the extension-toolkit to generate the files which got me the following layout:
```
<template>
  <div>
    {{ items }}
  </div>
</template>

<script>
  import mixin from "@directus/extension-toolkit/mixins/interface";

  export default {
    mixins: [mixin]
  }
</script>

<style lang="scss" scoped>
div {
  background-color: var(--red-300);
}
</style>
```

Then I'm using:
```
   npm run build --input ./src --output /path/to/directus/public/extensions/custom/interfaces/my-first-interface
```
to build and add it to my project.

I can select it as the layout, but it shows nothing.
If I just hardcode some text in there I can see it but it seems that I'm not getting any data from the `mixin`.

**Comment by rijkvanzanten** [comment]
Your PR in directus/extension-toolkit should take care of this right?

**Comment by SEGVeenstra** [comment]
Yes that's correct!
