### ISSUE TITLE
Repeater Many to One : no relationship selection possible

### ISSUE THREAD

**Issue by LandazuriPaul** [directus/app#2185]
## Bug report

Since it's possible to create a **Repeater** field for a collection with the **Many to One** interface, I wanted to build an item with a field being an extendable list of relationships to another collection entries.

Here is my specific use-case:
- A collection of _translation-pairs_: each entry represents a tuple of (from, to) languages, the languages being references to another simple collection with codes and names. So for example, an entry of the _translation-pairs_ collection could be (en, de).
- A collection of _translators_ having several accreditations each. Here is where I would like to use the repeater, so we can easily add/remove accreditations to a translator.

### Behaviour expected

After the M2O interface selection in the Repeater options, I would expect to have the possibility to choose which Collection I want to link with the repeater, and the fields used for such a relationship. Like the relation tab on the usual M2O field creation.

Instead, this is the options we get when selecting the M2O interface type in the Repeater:

![Repeater options in case of a M2O interface](https://user-images.githubusercontent.com/5787964/68401606-f5809b80-0171-11ea-83bb-546f14e70665.png)

### Reproduction

I've tried to implement such a relationship with the demo app. I created a new collection: [viewings](https://directus.app/#/settings/collections/viewings).

---
Maybe I get the repeater interface options wrong and that's why I can't set my collection the way I thought in the first place. If this is the case, I'm sorry to bother but any suggestion would be greatly appreciated! 😀

**Comment by grandsilence** [comment]
the same issue, latest version

**Comment by rijkvanzanten** [comment]
The JSON-based repeater does not support relational interfaces. The commit above removes support for setting up relational fields in the repeater interface. While this is not a complete fix for the problem, it does prevent it from happening in the future. Meanwhile, we'll be focussing our efforts on creating a new relationship-based repeater field that has full support for all interfaces Directus has to offer.
