### ISSUE TITLE
Missing cancel button in "file" modal

### ISSUE THREAD

**Issue by onlinelessons** [directus/app#2186]
I have a collection with a field type "file". If i click on "new file" everything works fine. If i click on "select existing" there is no cancel button and no close icon in the following modal!

**Comment by bjgajjar** [comment]
@rijkvanzanten  - `cancel` button and `close` icon both are only visible if any action is not required.

When user tried to `Select Existing` file - the action is required and that's the reason these buttons are missing the `Select Existing` model. 

Is that okay to remove this condition to resolve this issue?

**Comment by rijkvanzanten** [comment]
It's very likely that action is required because there is no cancel (/undo) flow for it (yet). Make sure to test properly when removing that prop
