### ISSUE TITLE
Reduce columns in field type "file" in tabular view type doesn't work

### ISSUE THREAD

**Issue by onlinelessons** [directus/app#2187]
I have a field "download" which has type "file". I just want to display pdfs in tabular view. 
So used "tabular" in "view type" which works but i get too many columns displayed which doesn't fit in the modal (storage, filename, title, type). So after a long google search (there is no documentation on "view query" and "filters") i found out how to reduce the columns with the "view query". I used the following code in "view query":

```json
{
    "fields": [
        "title",
        "filename"
    ]
}
```

After that change everything looks fine but i can't select any checkbox. In the console i get the following error: `RangeError: Invalid time value  at ge._localizeDateTime`

**Comment by rijkvanzanten** [comment]
What version are you using?

**Comment by rijkvanzanten** [comment]
The `view_query`, `filters`, and `view_options` fields mirror what's normally saved in in the same named columns in `directus_collection_presets`. The idea was that you could setup a layout exactly the way you like it, and then use those values to setup the modals as well.

In your example, you can use:

`view_query`

```json
{
  "fields": [
    "title",
    "filename"
  ]
}
```

`view_options`

```json
{
  "widths": {
    "title": 100,
    "filename_disk": 400
  }
}
```

which will make the modal render as

![image](https://user-images.githubusercontent.com/9141017/70170840-81b3af00-169b-11ea-8293-f6b188ba5869.png)

**Comment by rijkvanzanten** [comment]
Updating the `file` interface (+ combining it with file-preview) and it's options are very high up our to-do list. We'll make sure that setting up the options here will be a little more user friendly too.
