### ISSUE TITLE
Allow deselecting a file in "file" modal

### ISSUE THREAD

**Issue by onlinelessons** [directus/app#2188]
If i have a field with field type "file" and click on "existing", I can't deselect a file anymore. As reported in #2186 there is also no cancel and close button, so I have no other possibility to discard my changes then using browser history back.

**Comment by benhaynes** [comment]
I agree that this should be possible from the File Selection modal (enhancement), but it can also be done in a few ways now:

* Below the file card there are three dots, click those and you can "Remove" or "Delete" the current file.
* Clicking on any field label gives you a context menu that lets you clear the field.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
