### ISSUE TITLE
Spanish translation is not working in Admin APP

### ISSUE THREAD

**Issue by carlosjac** [directus/app#2192]
I've installed directus /directus.  It is working well.  However, I have a problem.
Spanish translation is not working.  In my user's profile I set Spanish but directus shows texts in English.

**Comment by sebj54** [comment]
Hi Directus devs :)

I noticed that it works in French but not in Spanish. In database, the `locale` field is set to `fr` for French but `es-ES` for Spanish, maybe that's what is causing the issue.

**Comment by benhaynes** [comment]
Thanks @sebj54 — this helps a lot! Especially since our Core team is all super busy getting ready for v8 next week! 😉 If you find a good solution, feel free to send over a PR!
