### ISSUE TITLE
Promise.allSettled() needs a polyfill

### ISSUE THREAD

**Issue by nstCactus** [directus/app#2197]
Using the latest commit (41fd0b64f9c35d10c7abec5fb661eed876e59986) of the develop branch, the app is broken in some browsers including Firefox. 

The reason is that the `Promise.allSettled()` function used [here](https://github.com/directus/app/blob/develop/src/store/actions.js#L221) isn't yet [supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) (although Firefox is listed as supporting it, the current 70 version doesn't).

Fortunately there are some polyfills available: https://www.npmjs.com/search?q=promise.allsettled

Error in Firefox 70 JS console:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/353843/68676707-dc556180-055a-11ea-9065-c7e3f7d995ce.png">

**Comment by rijkvanzanten** [comment]
Good catch! Thanks
