### ISSUE TITLE
Checkboxes won't preselect defaults anymore

### ISSUE THREAD

**Issue by mvhirsch** [directus/app#2204]
Hi folks,

We recently updated our App from v7.0.8 to v7.11.0 and noticed that _checkboxes_ interface won't preselect their defaults anymore, while e.g. _dropdown_ still does.

## Steps to reproduce

1. Create a new collection "acme"
2. Create field "options" (_checkboxes_ interface)
3. Set *default* in "Schema" to `value1,value2`
4. Check *required* in "Schema" to be true

## Actual Behaviour

Now go to your collection, add a new item and just click save.
Since "options" is a required field and there are no preselected values, it will fail to save.

## Expected Behaviour

Expected defaults to be preselected and saving just works.

## Additional Information

I'm not sure, but it might be related to this bugfix: https://github.com/directus/app/pull/2111

My APPs version is v7.11.0
My APIs version is v2.6.0

**Comment by Owlree** [comment]
I'd like to take this.

**Comment by rijkvanzanten** [comment]
It's all yours @Owlree! Let me know if you need any pointers

**Comment by rijkvanzanten** [comment]
Hey @Owlree, I just found the cause of this issue and patched it up so it would make it into the v8 release.
