### ISSUE TITLE
User Invitation Modals for Setup

### ISSUE THREAD

**Issue by benhaynes** [directus/app#221]
If a user has been invited to Directus, we need to show a Welcome/User Setup modal for them to complete their profile (we only have their email from the invite).

If they were setup already (by an admin) then they should only see the Welcome modal.

![screen shot 2018-04-20 at 12 12 58 pm](https://user-images.githubusercontent.com/522079/39062004-32f8b91c-4494-11e8-9a72-043bb22153f5.png)

**Comment by rijkvanzanten** [comment]
Two parts:

1. They came from an email password
  We need to have them setup on first load, so they have all the required information
2. The admin set them up in the database
  We need to flag the first login, so we can render some sort of welcome message / onboarding

**Comment by rijkvanzanten** [comment]
We should track in the DB for which version they got the welcome message too, so we could potentially show "what's new" in future versions

**Comment by benhaynes** [comment]
We need this if we want to support User Invites (which we do). This was an important feature in v6 that was lost... we need it back!

**Comment by benhaynes** [comment]
Ref: Invite is ready! https://github.com/directus/api/issues/356#event-2055108246

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
