### ISSUE TITLE
WYSIWYG File/Image Manipulation

### ISSUE THREAD

**Issue by jacobrienstra** [directus/app#2210]
Thought I'd put this as a feature request for safe keeping: It'd be great to be able to upload a new file or choose an existing file to put inside the (TinyMCE) wysiwyg, from the built in image toolbar button. It'd also be great to have those resize handles appear.

My users often want to include images in their content and most often they're new images, so it's a pain to have them upload them separately then choose them from existing. And they're seldom the right size, and guessing at a size by dimension isn't very helpful.

I don't think it'd be too crazy to implement, the image resize handles are built into tinymce imagetools, but I think some UI CSS isn't loading or something, I haven't been able to figure it out. Skins?

As for files, if we just trigger a file input field inside a modal, and call that from TinyMCE, I think that should do the trick. I also played around with this but I couldn't figure out how to properly set up the input to feed back the url data to TinyMCE.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by inta** [comment]
I think this is a great proposal, we need some more image manipulation, but this may be too much freedom for the editor sometimes. Maybe we could have an alternative/additional way. I think it could be great to select some of the thumbnail sizes (from the global settings) for images inside the wysiwyg editor.

I think it is not really desired to deliver the original image (like it is now?) to the client and that way we already have generated thumbnails with the right size (or at least the definition for them).
