### ISSUE TITLE
Color Interface is broken

### ISSUE THREAD

**Issue by SeanDylanGoff** [directus/app#2211]
The color interface seems to be full of bugs. Range inputs in RGB mode are broken, and value ranges in HSL mode are incorrect, too.
https://github.com/luz-alphacode/vue-ps-colorpicker
Would be a ready-to-go replacement that is also superior in my opinion. I'll do a PR if it's not fixed until I get to it.

<img width="767" alt="directus_color" src="https://user-images.githubusercontent.com/6235675/69054908-e53bac80-0a0c-11ea-85cb-9a06a1118993.png">

Really awesome project! The way interfaces are implemented is just AWESOME!

**Comment by benhaynes** [comment]
Ahh, good catch @SeanDylanGoff! I've been going over _all_ the interfaces for the upcoming v8 release. It's just hard to test each set of options (there re so many) like RGBA within the `color` interface. I'll get this one polished up today.

**Comment by benhaynes** [comment]
Question: Should we switch the RGB, CMYK, HSL to be text inputs instead of sliders? The sliders are a nice visual, but I wonder which is easier to view/enter. Also, inputs are a bit more standardized in the form layouts.

@rijkvanzanten 🔔

**Comment by rijkvanzanten** [comment]
Totally depends on what kind of data entry your doing. If you know the values already, inputs are way more convenient. That being said, if you're a user that's trying to come up with a new color, a visual representation is more useful

**Comment by benhaynes** [comment]
Agree. Eventually we could add options for this, but I think we should keep things simple for now. @rijkvanzanten , there are issues I can't figure out with the sliders... I'll leave it up to you to fix the sliders or convert to text inputs.
