### ISSUE TITLE
Collection list empty for existing database table

### ISSUE THREAD

**Issue by Mohamed-Hamed** [directus/app#2216]
I installed the latest version of directus suite using git, and configured it for an existing database.
Collection listings are working fine except for one that is showing nothing.

I see the following error in the console:
Cannot read property 'toLowerCase' of null

TypeError: Cannot read property 'toLowerCase' of null
    at table.vue?79d7:9
    at c.Ga [as _l] (vue.runtime.esm.js:2630)
    at c.$e (table.vue?79d7:1)
    at c.e._render (vue.runtime.esm.js:3542)
    at c.n (vue.runtime.esm.js:4060)
    at an.get (vue.runtime.esm.js:4473)
    at new an (vue.runtime.esm.js:4462)
    at Fi (vue.runtime.esm.js:4067)
    at c.Sn.$mount (vue.runtime.esm.js:8409)
    at init (vue.runtime.esm.js:3118)

How can I solve this issue?

**Comment by rijkvanzanten** [comment]
What version is this on? What is the database called? Are you able to share a dump of the database so we can reproduce this? Are there any fields in this collection that don't have an interface setup?

**Comment by rijkvanzanten** [comment]
I think ea877b2 fixed this issue. I think one of the fields in your collection either didn't have a `directus_fields` row associated with it, or didn't have a `type` set in directus_fields. If that was the case, ea877b2 should fix it for you. Please let me know @Mohamed-Hamed

**Comment by Mohamed-Hamed** [comment]
I Confirm that this commit fixed the issue.
Thank you very much.
