### ISSUE TITLE
Title sits weird when using custom nav override

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#2217]
![image](https://user-images.githubusercontent.com/9141017/69165060-f6dd8c80-0abe-11ea-8189-0e9744c93b72.png)

Nav titles only show up when using custom nav overrides

**Comment by benhaynes** [comment]
The styling is fixed, but we need to figure out how we want to handle titles in the nav override. Right now titles don't seem to show up for Collections or Bookmarks. Also: https://github.com/directus/app/issues/2227 https://github.com/directus/app/issues/2226

**Comment by rijkvanzanten** [comment]
Titles for collections and bookmarks are showing up since 7a1722ff
