### ISSUE TITLE
Creating new O2M leaves related field blank until saved

### ISSUE THREAD

**Issue by awbranch** [directus/app#2218]
App Version: 7.11.0

Create 3 collections of Person, Membership and Team where membership represents the different teams people can be on and the role they play on that team.

## Person
- ID
- Name: Text Input: e.g. "John"
- Teams: O2M -> Membership

## Membership
- Person ID: M2O -> Person
- Team ID: M2O -> Team
- Role: Text Input e.g. "Quarterback"

## Team
- ID
- Name: Text Input e.g. "Football"

Inside the Person collection, I want to add John to the Baseball team and set his role as outfielder.

Once added, the Team name is blank in the Person.Teams field until John is saved. I would expect it to see the team name I selected.

## "Add New" Clicked on the Person Record

<img width="767" alt="Screen Shot 2019-11-19 at 5 08 02 PM" src="https://user-images.githubusercontent.com/108669/69190869-52277300-0aef-11ea-998a-58f00bb554b9.png">

## Resulting Screen Missing Team Name

<img width="763" alt="Screen Shot 2019-11-19 at 5 03 16 PM" src="https://user-images.githubusercontent.com/108669/69190686-ec3aeb80-0aee-11ea-8225-bbcbf567a83f.png">

**Comment by awbranch** [comment]
Any chance this will get fixed in the next release? We just migrated to Directus7 and have lots of M2M relationships like this. 

**I will send the fixer a large pizza!!!**

**Comment by rijkvanzanten** [comment]
The problem here is that the many to one interface that's used in the modal stages a single value (primary key) to save. The display component of the M2O (used in the table in the O2M) doesn't know how to render just the primary key, as it expects the full related object to be passed in in order to render the values. I'm updating the m2o display component to asynchronously fetch the data if only the primary key is passed.

**Comment by rijkvanzanten** [comment]
Problem 2 is that the one to many interface doesn't pass on what the nested display components are related to, so the m2o display doesn't necessarily know where to fetch the item from

**Comment by rijkvanzanten** [comment]
Fornino is a pretty good pizza place around here @awbranch 😉 🍕
