### ISSUE TITLE
Imporve performance for large collections

### ISSUE THREAD

**Issue by dur41d** [directus/app#2230]
I noticed that the table interface for large collections (more than 1000 items) is noticeably slow when resizing the table columns. My collections had thumbnails. I noticed that the performance improved when I removed the thumbnails from the list view. However resizing is still slow. 

Please consider improving the user experience.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
