### ISSUE TITLE
Add translation to an object doesn't work anymore on 8.0.0-rc.2 (and develop)

### ISSUE THREAD

**Issue by hufon** [directus/app#2232]
## Steps to Reproduce

1. Create a collection : test_translation
2. Create a collection : test with a translation field
3. Try to create a new test object with a translation -> Works. 
4. Try to edit the created object

## Expected Behavior

You should add / remove  a translation

## Actual Behavior

Empty field appear

## Other Context & Screenshots
![Sélection_164](https://user-images.githubusercontent.com/1788150/69542854-918d0e00-0f8c-11ea-966f-284857960eeb.png)

**Comment by hufon** [comment]
For information, the language code column is named "language".
If i rename it to language_code it works...

**Comment by rijkvanzanten** [comment]
@urvashithakar 🔔

**Comment by hufon** [comment]
https://github.com/directus/app/pull/2239
