### ISSUE TITLE
Firefox with  Directus (8.0.0-rc2): Mouse interaction with text inputs impossible

### ISSUE THREAD

**Issue by Phylax-Aranatis** [directus/app#2233]
Hi everyone,

I've just installed the all-new version 8.0.0-rc2 on a shared hosting space and while the interface has improved significantly since the last version (7.x) I know, I've found the text input fields to behave a little strange in Firefox (70.0.1, ubuntu 18.04). Once there is text within a field no mouse interaction with it is possible, i.e. I cannot use the mouse to position the cursor or select text.

Note that I'm talking as much about the inputs configured for the individual collections as about the “hard coded” ones. I first noticed the problem during installation when the Super-admin password was presented to me an I couldn't select it for copying… I had to retype it. So the whole new interface seems to be concerned.

I have since found that the problem does not occur in Chrome (78.0.3904.108), so it is no dealbreaker, but maybe still worth considering since some clients may want to use Firefox/Gecko…

All the best

Oliver

**Comment by rijkvanzanten** [comment]
We started making things non-selectable to make the app feel a little more app like (no selecting icons etc), but we took it a bit too far!

Pushing a fix in 3...2...1........

**Comment by Phylax-Aranatis** [comment]
Hey, you guys are quick! Personally I'd prefer even “dead” text to be selectable and copyable to communicate about the interface more easily… but that's a matter of taste.
In any case: I think you're doing a great job and Directus would deserve a lot more attention!

Greetings

Oliver

**Comment by rijkvanzanten** [comment]
Yeah, we're still experimenting with what feels right and what doesn't 🙂 If you run into anything that you feel like should definitely be selectable, please open an issue and we'll discuss and tweak!

**Comment by benhaynes** [comment]
Yeah, I agree.... it's an experiment as of now, and definitely subjective. We're 100% down to discuss too (maybe over Slack)... but our reasoning is to get things feeling more like a native App. For those that don't like this direction, it should be a one liner to get things back to being selectable with a CSS override:

```
* {
    user-select: auto;
}
```
