### ISSUE TITLE
Relational interfaces should be nullable (if have not set as required)

### ISSUE THREAD

**Issue by anelad** [directus/app#2240]
If we select an item on relational interfaces like M2O, we cannot deselect it. The only way is deleting and re-creating the item but if we have many relations exists on that item, the problem becomes a headache.

![Screen Recording 2019-11-26 at 18 30 23](https://user-images.githubusercontent.com/5767654/69647731-1191a180-107b-11ea-853f-98cad92d4bae.gif)

**Comment by fa-briz-io** [comment]
![Screenshot 2019-11-26 at 16 39 31](https://user-images.githubusercontent.com/7761958/69648348-6b8a6b00-106b-11ea-90c4-f1a94a72be39.png)
It's a little bit annoying yes, but i found that when you hover over the label you get a little "triangle down" icon that you can click to open a sub-menu and clear input.

**Comment by anelad** [comment]
Yes @fa-briz-io, this is a way. You know it, I know it. But if any user does not know it? It's actually very hard to find for people not know much about software and tech. The selection should be nullable.

**Comment by fa-briz-io** [comment]
Ah, because you mention deleting and recreating I was not sure you were aware. But you're right, the first options should be null

**Comment by anelad** [comment]
I was trying to express what my client said :)

**Comment by benhaynes** [comment]
It seems that we want the ability to select the first (blank) item in the M2O dropdown, right? I agree this would be a more UX friendly approach than the label menu to reset. I'll add this as a Feature Request, and we'll get to it... unless someone wants to tackle it sooner. :)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
