### ISSUE TITLE
v8 - add capacity to login a project directly without select from dropdown options

### ISSUE THREAD

**Issue by everyx** [directus/app#2245]
Hi, 

If we have a lot of projects, each project user must find the name of the project from dropdown list, It's a little bit annoying, we don't have a way (such as a bookmark) to login a certain project directly, without selection, just only input email and password to login. If we can get a certain project login by some url construction, it's much better nice to user. :)

**Comment by benhaynes** [comment]
Hey @everyx — You can add the `project` query parameter in the URL to pre-select a project in the API. It even works when the projects themselves are private (by prepending the config file name with `private.`).

`https://example.com/admin/#/login?project=my-project`
