### ISSUE TITLE
Directus 8: Multiple Apps connecting to one API

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/app#2253]
Currently, using Directus 7, I have multiple apps (just the admin app) running and pointing to one api instance (with associated projects configured). Is this still possible to do?

I don't want my customers to see and select from a list of all projects im running.

In Directus 7, the admin app could be configured to accept "all apis" and let the user enter the api name.
That would be a sufficient solution for me. But I think this is also not possible anymore?

Thank you for your extraordinary work on this project!

**Comment by rijkvanzanten** [comment]
It works the first load on my end. Could it be your server logic converting the subdomain into the full path?

**Comment by rijkvanzanten** [comment]
I'll close this now as the OP question has been answered.

We can open a new bug issue when the issue still arises
