### ISSUE TITLE
Add ability to enter JSON in repeater fields

### ISSUE THREAD

**Issue by MrKyHn1** [directus/app#2254]
Hi everyone,

I would like to suggest a feature, or if it already exists, i would like you to show me how to use it:
I want to add a country list(in a dropdown interface from directus)
 (FR, US as value and France , United States as name for example) or any other long dropdowns with 100+ values with JSON(currently, checkboxes are configurable that way), right now it is only available manually (set list name and value one-by-one).

# Feature Request
JSON configuration in dropdown fields

## What problem does this feature solve?
Avoiding errors when manually entering long list of options in dropdowns
and also gaining time in this process

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/app/issues/2083
