### ISSUE TITLE
Allow table sorting by Id, created date, modified date

### ISSUE THREAD

**Issue by dur41d** [directus/app#2265]
Currently there is no way to sort a tabular view of a collection by id, created date, modified date. I think it's good to allow sorting be these fields.

**Comment by benhaynes** [comment]
Hmm, not sure what you mean. You can turn on created-on/modified-on in the info sidebar... and then click the column header to sort by them. the primary key (`id`) is the default sort order, and you can add that to the browse page by disabling the "Hidden on Browse" in the field settings.

**Comment by dur41d** [comment]
You're right. I had these fields in `Hidden On Browse` option set to true which is the default setting. This is not a bug.
