### ISSUE TITLE
Allow ordering of bookmarks

### ISSUE THREAD

**Issue by dur41d** [directus/app#2266]
Currently the interface does not allow ordering of the bookmarks. I think it's good idea to allow this to make it possible to customize the interface.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
Hmm, I'm not sure about this. We have three types of bookmarks: user, role, and global. SO it would be difficult to find a consistent way to reorder these. I think alphabetically (how it works now) is the best for 90% of use cases. Happy to discuss though!
