### ISSUE TITLE
current develop branch - File interface - TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by everyx** [directus/app#2269]
version: current develop branch (Latest commit 7909a4d)

file interface could not display image.

![file-interface-bug](https://user-images.githubusercontent.com/1665522/70033718-fc70c180-15ea-11ea-8230-e7e9b32d4ff3.gif)

![image](https://user-images.githubusercontent.com/1665522/70033303-1f4ea600-15ea-11ea-9326-ae6d2e433984.png)

**Comment by rijkvanzanten** [comment]
Oh I thought https://github.com/directus/app/commit/da76b03823dab7fca9efa5d365ac04d91326ff2d fixed that

**Comment by everyx** [comment]
> Oh I thought [1a8c166](https://github.com/directus/app/commit/1a8c1667b2ae1de627f585b9b1d156222f5369ca) / [da76b03](https://github.com/directus/app/commit/da76b03823dab7fca9efa5d365ac04d91326ff2d) fixed that

Thanks, I'll test it :)

**Comment by everyx** [comment]
I build with my dockerfile, it sounds like that i build with a cached staged image, and don't pull the latest branch to build, it's ok now, sorry about that. :)
