### ISSUE TITLE
Status based permissions fail when status field is hidden on browse

### ISSUE THREAD

**Issue by LandazuriPaul** [directus/app#2277]
# Bug report

Using the latest directus version (8.0.0), a user with user creation authorization doesn't see the "plus" button in the users' view (`project-name/users/`). Actually, I am sure the connected user is authorized to perform a user creation because if I manually enter the `project-name/users/+` URL, I get to the corresponding form and can successfully create a new user. So it's a purely UI bug it seems.

## Behaviour expected

A user having the ability to create a user should see the "plus" button.

---
Directus version 8.0.0

**Comment by rijkvanzanten** [comment]
What are your permission settings for this user role? I just setup a new role with create permission to directus_users, and the `+` button does show up for me

![image](https://user-images.githubusercontent.com/9141017/70159159-76a25400-1686-11ea-8433-9785ca90739f.png)


<img width="713" alt="Screen Shot 2019-12-04 at 11 07 23 AM" src="https://user-images.githubusercontent.com/9141017/70159063-4e1a5a00-1686-11ea-9ab0-9a67281c20a1.png">

**Comment by LandazuriPaul** [comment]
Well, I've tried with different settings:

1. The setting I would like to stick to for this role:
![Capture d’écran 2019-12-04 à 16 19 02](https://user-images.githubusercontent.com/5787964/70160258-1de8b080-16b2-11ea-83ad-71d5c7a6e678.png)

2. An almost identical setting to yours:
![Capture d’écran 2019-12-04 à 16 19 58](https://user-images.githubusercontent.com/5787964/70160308-33f67100-16b2-11ea-99b2-03ecbc885a8c.png)

With both these settings, I don't have the plus button.

Then I thought that maybe the problem was coming from the fact that I limit the fields the role can write.

But even letting it have full access to writable fields, I still don't have the plus button:

![Capture d’écran 2019-12-04 à 16 23 59](https://user-images.githubusercontent.com/5787964/70160521-8e8fcd00-16b2-11ea-8b1f-c46c48de2470.png)

So now it's even weirder as I have the same role settings as you but still don't have the plus button :/

Also, I don't know if it can be related to this issue, but in previous Directus versions, I could custom the directus_users fields and add some with specific interfaces. But now it seems that it's not the case anymore. So I still have some extra fields from my database, and there are shown in any user profile. But they all have the basic Text Input interface. Is it supposed to be this way? Is there any chance we get the ability to tweak the users' table again?

**Comment by rijkvanzanten** [comment]
I know this is an obvious one, but better safe than sorry; can you confirm that your user is in this exact role?

If possible, could you send over a dump of a dummy user and exact rows in your `directus_permissions` table either here or [on Slack](https://directus.chat) so I can try reproducing it on my end?

As for your missing setup for custom fields in `directus_users`, we didn't officially support this before either. We had to reset the `directus_fields` config for all `directus_*` collections in preparation of officially supporting this feature in the near future 🙂You'll be able to go into Settings > Collection & Fields to start modifying custom fields in directus_* collections hopefully soon!
If you go into the `directus_fields` table directly you should still be able to set it up as before.

**Comment by LandazuriPaul** [comment]
> I know this is an obvious one, but better safe than sorry; can you confirm that your user is in this exact role?

You're right, better safe than sorry. But yes, the user is actually in this role.

> As for your missing setup for custom fields in `directus_users`, we didn't officially support this before either. We had to reset the `directus_fields` config for all `directus_*` collections in preparation of officially supporting this feature in the near future 🙂You'll be able to go into Settings > Collection & Fields to start modifying custom fields in `directus_*` collections hopefully soon!
If you go into the `directus_fields` table directly you should still be able to set it up as before.

You're right. I've been able to tweak the `directus_users` and `directus_fields` table directly from the database. Thank you!

> If possible, could you send over a dump of a dummy user and exact rows in your `directus_permissions` table either here or on Slack so I can try reproducing it on my end?

I'll send you both dumps (`directus_permissions` and the dummy user `directus_users`) on a direct message via Slack. Thank you for your help!

**Comment by LandazuriPaul** [comment]
For anyone landing on this issue, my problem was coming from the fact that I had set the `hidden_browse` property to `true` for the `status` field in the `directus_fields` table.

Unsetting it back to its original value (`false`) did the trick.
