### ISSUE TITLE
Add Arabic to Locale List

### ISSUE THREAD

**Issue by mosamna** [directus/app#2278]
Hello,

I am unable to see Arabic Language in user's locale list.
I have updated the Directus app to the latest version pull request No <7a0ddbd38>

let me know if I am missing something here.

thank you for your support.

regards,
Abdulmajeed

**Comment by rijkvanzanten** [comment]
I'm seeing it in the user's `locale` settings:

![image](https://user-images.githubusercontent.com/9141017/70168251-7d38c780-1696-11ea-80e6-2e6d0469b92d.png)

and in general settings.

Where are you looking?

**Comment by mosamna** [comment]
In User's Settings:

![‏لقطة الشاشة 2019-12-04 في 21 19 37](https://user-images.githubusercontent.com/29823808/70169450-e2fb7280-16db-11ea-8dc8-855bb831a173.png)

My directus version is 7.6.1

**Comment by mosamna** [comment]
I need to migrate to version 8
I will close the issue.

sorry to disturb you.

**Comment by rijkvanzanten** [comment]
Ah! You said _“I have updated the Directus app to the latest version pull request No <7a0ddbd38>‘]”_ before which is in fact Directus v8.0.0 🙂

**Comment by mosamna** [comment]
I have pulled the latest changes prior to migration
My bad.
