### ISSUE TITLE
Add folder support to File Library

### ISSUE THREAD

**Issue by benhaynes** [directus/app#228]
1. Folders should always be displayed at the top, BEFORE files.

2. We need to add the header bar to this listing page (same height as tabular). This would show the folder breadcrumb and a "Add Folder" button.

3. Folders should have the ability to be renamed – maybe they have a edit button on the card/tile for now (we can add right-click context menus later).

4. When dragging a file/folder onto it, it should switch to the OPEN folder icon.

![directus 7 file library](https://user-images.githubusercontent.com/522079/46292266-74aea380-c55e-11e8-8007-d32d5fc6a403.png)

**Comment by dur41d** [comment]
Any update on this?

**Comment by benhaynes** [comment]
It's on the roadmap as a priority but there's no ETA set. We'd love a PR from the community, otherwise we'll probably have it in late December or January.

**Comment by nstCactus** [comment]
It would also be nice to have an option to the single file & multiple files interfaces to restrict it to a specific folder.

**Comment by benhaynes** [comment]
Ohh, I like that @nstCactus! Perhaps two options:

`default folder` — Root by default, but can be updated to others
`change folder` — `true` by default, but can be turned off to "lock" the interface to the default folder

**Comment by andriipol** [comment]
Hello, everybody, any updates on this issue?

**Comment by benhaynes** [comment]
The API already supports this — so that main thing we're missing is: supporting drag-and-drop on the Tiles Layout (needed to drag files/folders into folders). We have a bit of a feature-freeze (internally)while we do some refactors, ports, and stability improvements... so this would need to be a community PR to get it done in the next few months.

We like this library for supporting dragging: http://interactjs.io/ ... maybe someone wants to take a stab at this? We have designs but need someone who can get a clean implementation here:

https://github.com/directus/app/tree/master/src/layouts/cards

**Comment by benhaynes** [comment]
Just adding this here as it might be useful for the file/folder drag-and-drop:

http://interactjs.io/

**Comment by justrealmilk** [comment]
I was about to open an issue for exactly this! Then thought I should check for others as it's not exactly a crazy new idea.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Nitwel** [comment]
Hey, when this is supported by the api side already, lets get things started!
I'm 💯 % looking into adding this feature and would like to work on it.

**Comment by rijkvanzanten** [comment]
Hey @nitwel

There already exists a directus_folders collection so all the work that needs to be done to support this is in the application. Each file would point to a folder in directus_folders. Another question right now is: should every (user) collection support folders? @benhaynes thoughts?

**Comment by benhaynes** [comment]
I think that this feature of grouping/nesting should be allowed for _any_ collection, but that only `directus_files` should be using `directus_folders`.

However, if you wanted to add groups to other collections that should be possible too with the following configuration:

* `grouping collection` — the collection that is used for grouping, eg `directus_folders`
* `grouping parent field` — the FK field in the grouping collection, eg `directus_folders.parent`
* `grouping key field` — the FK field in the target collection, eg `directus_files.folder`

### Folders for Custom Collections
By creating `projects` and `project_folders` collections you should be able to group things deeply nested just like Files.

### M2O Grouping
These folders are basically M2Os, so that should work too. To group a `projects` collection by an existing `clients` collection by choosing the `clients` collection and the field that stores the foreign key: `projects.client`. Additionally, you should be able to include a `clients.parent` field that lets you nest sub-projects (same as nested File Folders).

### Self-Referential
Again, just another example of the same thing. If you had a collection that could refer to itself you could configure it to allow nesting. For example you might have `labels` with `labels.parent`. Given this model you could relate an item to itself... but we'd need a way to differentiate clicking on the item to open its Item Detail vs clicking an item to open its nested grouping. This is not important and can come later.

**Comment by vospascal** [comment]
any update on this feature implementation?

**Comment by benhaynes** [comment]
Will probably happen in January, not too difficult, but we have a lot of important refactor work to do first. The work includes:

* Add relational drag/drop support to Card and Tabular layouts
    * This would be agnostic, so it works for any containers/grouping, not just files/folders
* Update M2O for Files -> Folders
* Add M2O for Folders -> Folders
* Update routes to reflect Browse (Layout) nested depth
* Update breadcrumb to reflect nested depth

**Comment by gbrlmza** [comment]
Hi, I was just thinking on this feature and found this feature request. There is any news about this?

**Comment by benhaynes** [comment]
Coming in v9 in a few weeks.

**Comment by vospascal** [comment]
Any news on this @benhaynes ? 
I got alot of images love to be able to orginize them in folders using directus ui.

**Comment by benhaynes** [comment]
It's been added in version 9, and there's an alpha for it out now on the `next` repo
