### ISSUE TITLE
Files Interface - Allow Card View

### ISSUE THREAD

**Issue by UnderscoreDesign** [directus/app#2283]
I would like to see the **Files** interface (which has a default view of tabular) allow for a **card** view. This is how the file interface currently works and would be consistent with that.

A card view would allow the files interface to be more useful and manageable for image galleries, etc. Also, a **sortable** card (or tabular) view would be helpful to set the image order.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
