### ISSUE TITLE
Files Interface: Can't upload multiple files

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/app#2284]
In the latest v8 release, I can't upload multiple files in the files interface. 

For example: I drag and drop 5 images into the upload area. The first one gets uploaded and nothing more happens. The interface hangs. (And I can see only one network request being made)
Up to 3 images work (not hitting the max file size limit).

In v7 this worked without problems.

I tried this on different instances on different machines. The behaviour is the same.

**Comment by benhaynes** [comment]
Thanks @pgegenfurtner — we've replicated this and are working on a fix.
