### ISSUE TITLE
Group template of fields

### ISSUE THREAD

**Issue by marcocala90** [directus/app#2293]
Hi at all! Congrats for the products, it's amazing! But we have a question. 
In every webpage I need to be able to manage meta tags. There is a way to create a template of fields that can be linked to each collection. In this way I could manage the meta tags always with the same structure for each collection. Thanks!

**Comment by benhaynes** [comment]
You can create a dedicated `metadata` collection that stores the data, with a collection dropdown, O2M, or M2M connecting it to each other collection (depends on desired schema).
