### ISSUE TITLE
Failed to install when database is no password

### ISSUE THREAD

**Issue by King-GO** [directus/app#2296]
In MySQL, by default, the username is root and there's no password.

![directus](https://user-images.githubusercontent.com/54804407/70373270-a8374b80-1922-11ea-8ae3-615c9c0e0596.png)

**Comment by benhaynes** [comment]
Thoughts @rijkvanzanten? Should we take the validation off this field?

**Comment by rijkvanzanten** [comment]
Ehh I'm a bit torn, I suppose we should as MySQL can technically be used without a password, but

You absolutely should not use mysql without a password, especially as root

**Comment by benhaynes** [comment]
True, but I assume this is for testing/local purposes only.
