### ISSUE TITLE
v8.1.0 double horizontal scroll bar when click more info.

### ISSUE THREAD

**Issue by everyx** [directus/app#2298]
See below.

![collection-list-bug](https://user-images.githubusercontent.com/1665522/70390509-af378a00-1a06-11ea-8b09-207172f509cf.gif)

**Comment by rijkvanzanten** [comment]
Similar to, yet different from https://github.com/directus/app/issues/2237

**Comment by everyx** [comment]
Looks like this issue fixed in 8.6.1, can we close it? @rijkvanzanten
