### ISSUE TITLE
All date related interface should store UTC datetime to API only

### ISSUE THREAD

**Issue by everyx** [directus/app#2299]
Hi, 

When after https://github.com/directus/api/pull/1447 commit, we should also let APP interface store UTC datetime to API, and display as localization date of user's timezone.

If we have multiple users with different timezone, current date interface is ugly for them, so this change will get every date related interface get work correctly.

Thanks.

**Comment by benhaynes** [comment]
This gets a bit tricky, since some users want to store dates in a specific timezone and we shouldn't assume they want UTC. It seems that we should allow this to be a per-field setting that Admin's can control (with a big warning about changing it after initial setup).

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by everyx** [comment]
> It seems that we should allow this to be a per-field setting that Admin's can control (with a big warning about changing it after initial setup).

Yes, we can just make this change default for new install, and disable from upgrade of old instance. just add a a per-field setting like `date_utc` to `true` or `false`, and we should make this setting invisible (It is set by directus itself from install/upgrade), and let interface handle datetime process according this setting.

> since some users want to store dates in a specific timezone and we shouldn't assume they want UTC. 

In my opinion, store a specific time with timezone info is more robustness, we store a date string now but without timezone information, and we allow user change timezone by themself, so the date in database does not have a determined time zone, if a item have a date but don't associated with the user, we lose the timezone information forever, it's terrible.

**Comment by everyx** [comment]
something related https://github.com/directus/api/issues/751
