### ISSUE TITLE
All the small things...

### ISSUE THREAD

**Issue by benhaynes** [directus/app#23]
- [x] Global selection color, like 5% of primary color
- [x] Breadcrumb is 13px from left... could this be 20px?
- [x] Optical vertical alignment of breadcrumb. It seems like 1-2px too high because of descenders
- [x] Smaller Directus logo. Match 6.x
- [x] Loading blocker (smoke) should be 100% opacity and then fade in with global elements (header, etc). If you're fancy we can add an animation to the blocker :)
- [x] Breadcrumb separator (and active crumb) should have "normal" cursor (not text select)
- [x] Sidebar borders should be lightEST gray

_Update: remove sidebar nav_

**Comment by rijkvanzanten** [comment]
> Add basic left-sidebar navigation
This is going to be a separate feature branch. (I don't consider it a small tweak ;) )
