### ISSUE TITLE
m2m field issue with directus 7.0.19

### ISSUE THREAD

**Issue by paolodedomini** [directus/app#2300]
Ok so i deleted the m2m field in a collection and then i was not able to add any new m2m field to the same collection again.
I tried also to erase and recreate the collection but with no luck.
in the console i got  a "Cannot read property 'fields' of undefined"

to notice: If i try to add the field to a brand new collection then i can add an m2m field with no problem at all

need some help no doubt...

**Comment by rijkvanzanten** [comment]
7.0.19 is very outdated. Please try updating to the latest version (v8.1), or at least the latest version of v7 (v7.11) if you don't want to upgrade to v8.

**Comment by paolodedomini** [comment]
many thanks for the answer but, currently, on your repository there's no 7.11 version to download.
As far as i concern there's no documentation for extensions in version 8 (i tried to use directus-extensions but i just can't make it work as i exprect in directus 7) so i installed the last version of directus  7 that anyone can find in github. 
On the branch master there is a gap between 7.0.19 and 8.
am i wrong?
And again can  you confim there's no documentation for extensions in directus 8?
Thanks a lot.

**Comment by benhaynes** [comment]
When the App/API were decoupled, there was a different suite version naming system. You can see 7.11 on our releases page... and here is the release:

https://github.com/directus/directus/releases/tag/190927A
https://github.com/directus/directus/releases

Extensions didn't change in v8 (other than where they are located) so the docs should be the same. We'll be working on tweaking the docs for v8 this week, but bear with us as we have a lot going on.

**Comment by rijkvanzanten** [comment]
All the releases are here:

https://github.com/directus/directus/releases

Extensions work the same in v8 as they did in v7.

**Comment by paolodedomini** [comment]
thanks a lot, directus is an amazing product and we are going to use it in production for a lot of coming soon website. (gatsby and jekyll driven frontend).

...Maybe is for another issue but, regarding extensions, what you suggest here is just not working on 8:
https://docs.directus.io/extensions/pages.html#files-structure
 Thanks again

**Comment by rijkvanzanten** [comment]
`pages` were renamed to `modules` in v8. I've updated the docs to reflect this change 👍

**Comment by paolodedomini** [comment]
Thanks a lot, you are great...
