### ISSUE TITLE
v8.2.0 radio button interface broken

### ISSUE THREAD

**Issue by everyx** [directus/app#2306]
We can not display radio button interface correct as below video.

![collection-list-bug](https://user-images.githubusercontent.com/1665522/70502758-a2c54580-1b5c-11ea-851a-0f7d7c0c9e03.gif)

**Comment by HashemKhalifa** [comment]
I'm facing
<img width="676" alt="Screenshot 2019-12-11 at 17 17 11" src="https://user-images.githubusercontent.com/3355748/70639116-489ab200-1c3a-11ea-8d41-28c3a245ed6e.png">
 the same issue as well
