### ISSUE TITLE
Get the translated collection name

### ISSUE THREAD

**Issue by damienroche** [directus/app#2307]
Hello Guys,
I would like to use directus with gridsome (a gatsby equivalent for vuejs)
And I would like to translate my content, but also my routes.
I can do this by using parameters when fetching data for directus API.

From my directus backend, I have a Collections named "Projects" which has two translations for the back-office part :
- English : "Projects"
- French : "Projets"

On my gridsome project i would like to generate two routes for a published project :
 
```
/en/projects/en-project-name 
/fr/projets/fr-nom-du-projet

route pattern : **':language/:translated_collection/:slug'**
```

I have managed to get the language and the translated slug for the project by using the translations system, but the missing part is the **translated_collection**.
I think there is a simple way to do that, by using the meta object when fetching collections.

My question is :
Can we imagine that meta object contains also the translated name of the Collection when passing the **lang** parameters on the request ?

example  :

`curl "http://content.localhost/test/items/projects?lang=fr&fields=*.*&meta=*" \
     -H 'Authorization: Bearer .....' \
     -H 'Content-Type: application/json; charset=utf-8' \'`

response : 
`
meta : { ...., translated_type: "Projets" }
`

**Comment by rijkvanzanten** [comment]
The translations of a collection are stored on the collection level, not the item level. You should be able to fetch the translations for a collection name from the `/collections` endpoint
