### ISSUE TITLE
v8.2.0 Files interface broken

### ISSUE THREAD

**Issue by bjgajjar** [directus/app#2308]
# Bug Report
`files` interface store the images but not mapped in the payload, as well as image, is not getting display.
## Steps to Reproduce

1. Add `files` interface to a collection.
2. Click on 'Add New'
3. Files will be successfully uploaded [You can check it in Files Library]
4. `files` interface will not display the image or title.
5. Still, when tried to store the collection it's throwing required validation.

## Other Context & Screenshots

The given screen recording is from Live Demo.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/70525692-e8d6d500-1b6d-11ea-9753-5626d5539d90.gif)

## Technical Details

- Install Method: [eg: cloned `master` branch]

**Comment by gianniskarmas** [comment]
In 8.3.1 the problem still exists.
> This item is not available
after uploading a file and no way to delete or change

**Comment by gianniskarmas** [comment]
I mistakenly added this here.
It is a different problem that has to do with the files interface inside collections and not the main files interface.
Please close and I will open a new bug report.
