### ISSUE TITLE
V8.2.0 Missing status when batch editing

### ISSUE THREAD

**Issue by gustavossilva** [directus/app#2309]
**Bug report:**
When I batch collections, the status field cannot be change.
![image](https://user-images.githubusercontent.com/9094827/70541416-bca75e00-1b45-11ea-90a9-88c24bccf406.png)

**Steps to reproduce**
1. Open some collection
2. Select multiple rows
3. Press batch to edit all selected rows
4. Status cannot be change.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/pull/2310
