### ISSUE TITLE
User Last Access

### ISSUE THREAD

**Issue by benhaynes** [directus/app#232]
The app should set the following whenever a user logs in or does something:

* directus_users.last_login
* directus_users.last_page
* directus_users.last_access
* directus_users.last_ip

Once we have that, we can add a "Online" dot to all Avatars/Usernames system-wide.

These values should not be editable in the User Detail page... and should probably just be hidden there (they are mostly for the app).

**Comment by rijkvanzanten** [comment]
> whenever a user logs in or does something

Define _does something_?

**Comment by benhaynes** [comment]
I would like it to happen as often as possible... so I'll let YOU define it. ;)

The way it used to work was:
* Update on login and any page change
* Update async every 2 minutes

That way we can search for users `WHERE directus_users.last_access > NOW() - 3 MINUTE` to get "logged in users" so we can show who's online.
