### ISSUE TITLE
Use standardized "subgrid" in interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#2323]
There's a couple interfaces that display things in a grid. These individual grids aren't using a predefined set of rules, resulting in a bit of a mess when combined:

![image](https://user-images.githubusercontent.com/9141017/70649377-fdbd7200-1c1a-11ea-8d3b-a178e273bee5.png)

The grid should probably be a 4-up in `full` / 2-up in `half`

**Comment by rijkvanzanten** [comment]
Using 134px for columns + 32px for gaps makes it align nicely with the bigger form grid which has 300px columns + 32px gaps

```
[300         ][32][300         ] 
[134][32][134][32][134][32][134]
```

**Comment by rijkvanzanten** [comment]
Crisis averted

![image](https://user-images.githubusercontent.com/9141017/70730311-bf838980-1cd2-11ea-9d0b-18cf7c566d54.png)

**Comment by benhaynes** [comment]
No text wrapping, and ellipsis?
