### ISSUE TITLE
Add ability to duplicate collections

### ISSUE THREAD

**Issue by gianpesto** [directus/app#2330]
Is it possible to duplicate a collection? Let's say i am creating a new collection B and want to have the same fields that are in collection A.

------

What i am trying to cover is the following scenario:
I have an app "A" that feeds from collection "cA1", "cA2" & "cA3". User "u1" has permissions to edit any of these collections. So far so good.

All the sudden i wake up at night and have an idea for an App "B", that works the same as App "A", but i want to have a user "u2" that only sees and has permissions for the content regarding App "B". 

So in my understanding i would copy all collections and set the permissions for the user as wished.

Is this the way normal ppl work? Or am i overthinking it?

**Comment by rijkvanzanten** [comment]
There's no dedicated way to do this through the app or api at the moment. As for the workflow, you could also create a new project for this second App to keep everything sandboxed, but that's preference and based on your exact needs

**Comment by benhaynes** [comment]
Another option would be to use the _same_ collection for both projects, but to use permissions to limit users to only edit THEIR items... or items created within their ROLE.

Duplicating entire collections would be difficult since it's not clear if/how we'd want to duplicate content, junction collections, related collections, etc.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
