### ISSUE TITLE
Allow Create option on Many To One Interface

### ISSUE THREAD

**Issue by EPMatt** [directus/app#2331]
It would be awesome to have the ability to add a new item directly when selecting an item from the dropdown or from the modal in the Many To One interface, just like in Many To Many and One To Many interfaces.

 That's an amazing feature in my opinion, it saves a lot of time when you need to add both a tuple in the referenced table and in the referencing one.

**Comment by rijkvanzanten** [comment]
Lets also consider editing the chosen / existing item 🙂

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
I agree — all relational interfaces should have the same options available (and each can be toggled). Edit, Create New, Choose Existing, Delete vs Deselect, etc.

@rijkvanzanten you cool to move this to `accepted`?

**Comment by fnicastri** [comment]
Hi @benhaynes , any news on this request?

**Comment by rijkvanzanten** [comment]
@fnicastri added in v9 👍

**Comment by benhaynes** [comment]
This has been accepted, and is integrated into the v9 release. The node stack of v9 is in Alpha, and will be in production in about a month or two.

**Comment by fnicastri** [comment]
@benhaynes @rijkvanzanten Thanks for the reply.

So the v9 will be based on node? Why that?
I remember a request about it but I was hoping to not see a total migration...
Any chance to back port the new App to the "old" php API? Or the are breaking changes?

**Comment by rijkvanzanten** [comment]
> So the v9 will be based on node?

We'll have an API in both NodeJS _and_ PHP (so you can pick your poison). The app is decoupled so will be shared in both.

> Why that?

Because NodeJS is a super popular back-end target now, supports things that are impossible in PHP (because it has a constantly running process), is easier to build and maintain long term because it uses the same stack as the front-end app, is easier to install, has less variations in dependencies, etc.

> I remember a request about it but I was hoping to not see a total migration...

... which is exactly why a PHP API is in the works too 🙂

> total migration...

What do you mean by _total migration_ exactly?

> Any chance to back port the new App to the "old" php API?

No, the "old" PHP API is very much due for an upgrade and will be replaced by the two new APIs.

**Comment by fnicastri** [comment]
@rijkvanzanten 

Very happy to know that we won't lose the php API, I use Directus on some cheap PHP hosting plans too and it's perfect!
This is what I meant by "total migration to node", to have Directus in node only.

> No, the "old" PHP API is very much due for an upgrade and will be replaced by the two new APIs.

Fair enough!

>Because NodeJS is a super popular back-end target now, supports things that are impossible in PHP (because it has a constantly running process), is easier to build and maintain long term because it uses the same stack as the front-end app, is easier to install, has less variations in dependencies, etc.

My take on this is a bit different, TBH, sure node is good but the whole JS ecosystem is a mess, low quality code, low quality libs and many of them unsupported, etc...
But it is good to have choices!

Do you think I should use the alpha version for this new project? It is supposed to go in production at some point in September.

**Comment by rijkvanzanten** [comment]
> TBH, sure node is good but the whole JS ecosystem is a mess, low quality code, low quality libs and many of them unsupported, etc...

Agreed! It's pretty difficult to find your way through the thousands of poor libraries to find the couple that are worth including in a project like this. Unfortunately, the same can also be said of PHP libraries, which is also a huge part of the reason why we're forced into a big upgrade like this right now.. (The current API heavily relies on Zend, which is abandoned..)

**Comment by fnicastri** [comment]
@rijkvanzanten 
Thanks for the feedback!
I'll take a look for sure!
