### ISSUE TITLE
Slug interface should not regenerate slug if it already generated when mirrored field changes

### ISSUE THREAD

**Issue by everyx** [directus/app#2335]
Hi,

Slug interface is usually used to generate url and mirrored `title` field for a website, if a title is changed, the site url should keep same as before the first generated, so can we disable regenerating for slug interface when mirrored field changes, or add a configuration option.

**Comment by everyx** [comment]
@rijkvanzanten I found that the slug is disabled as excepted in v8.6.2, but when I edit a exist item, change and save the mirrored field value, reopen this item, the slug is still regenerated based the mirrored filed.

We should reopen this issue.

![bug](https://user-images.githubusercontent.com/1665522/78913939-56632580-7abc-11ea-865d-9111e78966a1.gif)

**Comment by rijkvanzanten** [comment]
@everyx instead of re-opening this one, lets open a new one on the API repo, as this is a bug in the API, not the app..
