### ISSUE TITLE
Add a maximum item limit option for O2M/M2M related interface

### ISSUE THREAD

**Issue by everyx** [directus/app#2336]
It's would be nice if we can set a maximum item limit like repeater interface, so we can able to limit the number of files the user would selected or other related to many items.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
