### ISSUE TITLE
Show translations on overview page

### ISSUE THREAD

**Issue by inta** [directus/app#2337]
I am not sure if this feature already exists, but it is not documented and I could not find any info about it, so here we go:

I have some data structure where all properties which identify a dataset are saved as translations. The problem is, now every row looks like the other:

![Screenshot from 2019-12-13 11-34-58](https://user-images.githubusercontent.com/150137/70794304-a8f63480-1d9d-11ea-8078-e0f450c8b873.png)

I am not able to see which categories show up, although the data has obviously been loaded, as I can filter it by values from the translation table.

The best solution that comes to my mind would be to:
- make all fields of the translation table selectable (as if they were in the same table)
- displays the values that correspond to the language of the logged-on user
- fall back to the default language
- keep the number of available translations somehow (maybe add a label, bubble or something similar)

**Comment by rijkvanzanten** [comment]
> although the data has obviously been loaded,

It has not. The reason why filtering works is because it queries the filter to the API fresh. The reason it shows 2 Items instead of the actual items is because the data has in fact not been loaded.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by inta** [comment]
Ok, thank you for the explanation.

As this is quite critical for me to be able to use the CMS: Is there anything I can do to help you with this?

**Comment by rijkvanzanten** [comment]
I'm actually working on the translations interface and this part as we speak 🙂 I'm hoping to have some good news for you in a couple hours.

**Comment by arndissler** [comment]
Hi Rijk,

just want to clarify: this is only valid for the overview, correct? I stumbled into this issue here since I was looking why my dropdown in a M2O relation is empty, as it refers to a collection whose data is stored in the corresponding translations table.

If this is still an issue then it would be totally fine for me to open a PR by myself.

Thanks for the good work on this issue here, it improved the usability for this use case a lot! 

Best,
       arnd.
