### ISSUE TITLE
Multi-tenancy at the project level

### ISSUE THREAD

**Issue by SharadKumar** [directus/app#2342]
Firstly, I am a new user of directus and it is proving out to be awesome!

## Why
Directus offers a great single-app, multi-api, multi-database architecture that works for most cases. But when we need to develop a service or MVP for, say, a multi-tenanted service with dashboard-type experience with directus, there is no easy way to have data partitioning at the project level.

I created my project, created various collections, and configured various roles and permissions. Some of my collections are master/metadata entities at the project/app level while most of the other collections are to be multi-tenanted. Each tenant can have multiple users, each user with one of the roles available at the project level. I can do everything with v8.x except the ability to partition or scope the data per tenant/subscriber.

It is a pretty common use case for SaaS MVPs to have multi-tenanted subscription-based dashboards.

## What

My need on the current (and upcoming) project is that I should be able to configure my collections and roles and also scope some collections as multi-

- Ability to define tenants (think of them as a group of users, like a role). Often a business entity represents a tenant. The tenant has an owner or admin. It can be a system collection (see the screenshot example below).
- Ability to configure tenant permissions for a collection, similar to `Role only` or `Mine only` (see the screenshot example below). So that tenant subscribers (users scoped for a tenant) can create, view, edit, delete their tenant-scope data only.

I looked at the open/closed issues in the App and API repo but couldn't find anything relevant to my proposed case.

## How

One of the proposed ideas could be as below. Please note `Tenant only` permission and `Tenants` system collection. The benefit I see fo this pattern would be that it would not require admins to do much except deciding which collections are multi-tenanted through permissions. 

![image](https://user-images.githubusercontent.com/5488144/70835543-8887b200-1e51-11ea-8a0f-0b169ad65306.png)

For now, I am trying to hack my way by using Role as a tenant. Assign users to that Tenant (role). It means I have to create a Role for each subscribing tenant until I have a solution. By using `Role only` I should be able to scope or partition by data visibility for subscriber users of a tenant to their tenant data only.

**Comment by rijkvanzanten** [comment]
I'm a bit confused as to what the difference is between a role and a tenant in this case. As I understand it now, a tenant is a group of user for whom you can control the permissions, isn't that the same as a role?

**Comment by SharadKumar** [comment]
User can have only one Role AND needs a Tenant. So that for a Tenant-scoped data, that user plays a certain Role.

For example, I have an app that enterprise users are to subscribe and perform a role in various collections set up on the app. I can do everything in directus except I can't scope/group the users (per company ie tenant). 

Specifically, the company that subscribes this app is a tenant, the users within that company are scoped for the tenant, the data they create/read/update/delete is limited to their tenant (unless some master collections are setup by admin to be permissions at app-level and available to all tenants to drive app behaviour). These users of a tenant, have each a Role ie `product owner`, `project manager` etc.

Hope that clarifies @rijkvanzanten.
A quite common use case for multi-tenant SaaS apps, I think.

**Comment by benhaynes** [comment]
Hey @SharadKumar — I only partially understand your specific use case, but I blame that on my Friday brain-drain. However my opinion on this is such:

There will always be a lot of use cases that we can't cover, and adding individual features to support them will quickly make the codebase bloated and complex to maintain. For the specific architecture that you're trying to create, I think a more high-level and customizable solution is best. Please take a look at the feature request I've outlined below:

https://github.com/directus/api/issues/511

It gives _complete_ flexibility for all the permission configurations that anyone would ever need. The main issue is that it's a decent sized refactor of the API ACL (and we need to understand the performance implications). I have high hopes that we'll integrate this soon, but timelines are hard to promise in an open source project without financial sponsors.

I'd love to hear if you think my concepts will solve your issue, let me know.

**Comment by yarick2000** [comment]
I guess what's @SharadKumar wants is to introduce another level of security between roles and users, called tenants (or groups, or organizations), and so users who belongs to specific group they will have a limited permissions for their roles, defined by the scope of their group.

**Comment by SharadKumar** [comment]
Thanks guys, I am truly appreciative of the effort and contributions. I recognise that this is open source. I am keen to work within the constraints and find a solution to my use case because I believe Directus is a high-quality and well thought out product. 

Tenants (or company, or organisation, or groups, or subscriber) is a pretty common case for every other SaaS app online. For example, a user signs up to use a Project; subscribes to a plan X for his company (as a tenant); invites other users via email to join the Project for use for the company-scoped data that they would create using the Directus. 

It translates to the following:
1. Ability to create a tenant collection (system collection or admin created). A tenant has an Owner user.
2. Each user (other than Admin) will belong to a tenant and will have a Role assigned ie Owner (of the tenant) and Manager. In other words, we have Person belonging to an Organisation (tenant).
3. Admin should be able to create some collections for at the Global level (visible to all users, all tenants) and some permissioned to the Tenant users only. It is common use case if we intend to use Directus for SaaS where the audience is enterprise/team-based customers. Multiple users are grouped together as a tenant to CRUD access their data pool only, and common collections are simply to drive SaaS use case.

I am trying to get my head around the concept of dynamic rules https://github.com/directus/api/issues/511

All in all, it is simply an ability to create a multi-tenant app while using Directus backend. Currently, directus seems to be designed for single-tenant use cases only.

**Comment by SharadKumar** [comment]
Alternatively...

If there was a way to have my multi-project installation of directus meet the following:
1. A default project that no tenant uses. It is used to configure my app/saas.
2. I create a project per tenant (multi-tenancy by database ie database/project per tenant).
3. A way to synchronise all collections (not data) configuration and roles from the `default` project. So that app is configured once and all tenants can use the same functionality while keeping their partitioned data within their directus project. Each tenant can modify their logo, allowed settings etc. I can make minor customisations of introducing interfaces, layouts for my build/deployment.

With above I can aptly utilise the permissions/roles framework quite nicely and it will meet all or most requirements since data partitioning will be achieved at project-level for the tenant. But I don't know how to make projects stay synchronised from master default project.

So conceptually there are perhaps two possibilities for multi-tenancy... database-per-tenant OR tenancy-by-single-project. Not sure how either is feasible yet :)

**Comment by benhaynes** [comment]
Hey @SharadKumar — the second way you described is how we intended multi-tenancy to work within Directus.  Each tenant would be a project database, that way they can configure the App to look the way they want (logo, styling, etc). Separate projects can be used for the "master" database with no tenant access.

As for keeping your schemas in sync across each tenant, this would be done outside of Directus (as of now). We're looking at ways to manage schema/data import/export, but the schema side is probably not going to happen in the next month or two. The advantage of Directus is that it mirrors pure SQL... so you can write external scripts to generate new projects and keep their schemas up to date with separate migration files.

Obviously it'd be cool if Directus could just handle everything out of the box, but we need to keep our [80/20 rule](https://docs.directus.io/getting-started/contributing.html#_80-20-rule) in mind so that things don't get too bloated.

**Comment by benhaynes** [comment]
So, after talking with the Core team a bit more, I don't think this tenant setup will pass our 80/20 rule. If building a SaaS in Directus, the preferred method would be to setup tenants as projects (see above comments). In the (hopefully near) future, our Dynamic Permissions should support any other advanced ACL setup.
