### ISSUE TITLE
Unauthorized request when trying to get item

### ISSUE THREAD

**Issue by jasonfx13** [directus/app#2345]
I just installed the latest version of directus (v 8.3)

I created a collection called "articles" with the following fields:
title (text field)
content (WYSIWYG field)

In Settings -> Roles & Permissions -> Public -> enabled read access for all.

I am getting an unauthorized request when trying to get item:
{
  "error": {
    "code": 3,
    "message": "Unauthorized request",
    "class": "Directus\\Exception\\UnauthorizedException",
    "file": "\/var\/www\/html\/directus\/src\/helpers\/app.php",
    "line": 286
  }
}
I even enabled all the check boxes including the Directus System Collections, and still get Unauthorized Request. 

I can confirm that everything is getting set in the directus_permsissions table.

I didn't have any issues getting my collections to work in the previous version of directus (v 7xx something). 

Thanks!

**Comment by BernhardMt** [comment]
Had the same problem, turns out that Directus 8 removed the mapping of "_" to the default project. In my case i just had to replace the _ with the actual project name in the request to the api and it was working again.

**Comment by jasonfx13** [comment]
Excellent BernhardMt, thank you! That fixed my issue.

**Comment by jasonfx13** [comment]
> Had the same problem, turns out that Directus 8 removed the mapping of "_" to the default project. In my case i just had to replace the _ with the actual project name in the request to the api and it was working again.

Excellent, thanks! That fixed my issue.

**Comment by Antoineeee** [comment]
Hi guys, I have exactly the same problem but I don't understand your solution properly. Where should I replace the "_" thing ? When instanciating the directus client ?
And what should be the project name ? I tried to put my JS project name but it still does'nt work.

Thanks

**Comment by rijkvanzanten** [comment]
In v7, Directus would alias `/config/api.php` to `/_/` as "default" project. That's no longer the case. In v8+, the config name matches the project in the API at all times. So `/config/api.php` is `/api/`. 

Make sure your config file in the `/config` folder matches the project you're using in the SDK / AP

**Comment by Antoineeee** [comment]
Thanks ! I replaced the project alias from "_" to "/api/" and that specific issue is now gone. I have another one but I think it solved this problem at least :)

**Comment by jasonfx13** [comment]
> Hi guys, I have exactly the same problem but I don't understand your solution properly. Where should I replace the "_" thing ? When instanciating the directus client ?
> And what should be the project name ? I tried to put my JS project name but it still does'nt work.
> 
> Thanks

You replace the "_" in your api url endpoint.

You can find the project name in Settings -> Global Settings.

**Comment by Antoineeee** [comment]
I just implemented a persistant authentication replacing "_" to "/api/" as project value, witout touching the endpoints or Directus config files and it works now :

new DirectusSDK({
    url: "..........",
    **project: "/api/"**,
    user: "..........",
    password: ".........."
  })

**Comment by Fusseldieb** [comment]
I know it's a little bit unrelated, but my problem was that my project name was `Projectname` and I was trying to access the API with `http://URL/Projectname/auth/authenticate`, but it didn't work.
Turns out, it's lowercase, **it matters**!

Using `http://URL/projectname/auth/authenticate` did the trick!
