### ISSUE TITLE
Multi-select UI seems broken in 8.3.0 

### ISSUE THREAD

**Issue by lbrpdx** [directus/app#2357]
Directus version 8.3.0 (migrated DB from 7.x.x and I haven't had the same issue with 7.11.0)

I tried to create a multi-select field with the following options:
<img width="684" alt="Screen Shot 2019-12-20 at 1 30 58 PM" src="https://user-images.githubusercontent.com/21372356/71295101-6dc0ac00-232f-11ea-8e4e-681cd7cbedf4.png">

But when I go on my collection, it displays like this:
<img width="657" alt="Screen Shot 2019-12-20 at 1 31 24 PM" src="https://user-images.githubusercontent.com/21372356/71295116-80d37c00-232f-11ea-85c6-17d0b99a3640.png">

When I connect to the MySQL DB, I can see that the multi-select field can be correctly updated as I can see a `,0,1,` value when I update it from the collection UI, with the expected value.  But the display of the options is wrong, and not updated (no value selected).

**Comment by rijkvanzanten** [comment]
The interface should use the key value pair interface instead of the repeater with two fields.

**Comment by samis-dv** [comment]
Hey @rijkvanzanten was just wondering what the progress on this bug? If there was some sort of fix already available?
