### ISSUE TITLE
Feature: allow filter in many-to-one

### ISSUE THREAD

**Issue by dur41d** [directus/app#2358]
Sometimes it is useful to hide some items from the M2O relations drop-down/dialog. For example to hide archived items that you don't want to delete. I suggest adding a view query or filter option to the interface where the user can specify a custom filter.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
