### ISSUE TITLE
V8.3.1 code interface template is only worked with JSON language.

### ISSUE THREAD

**Issue by everyx** [directus/app#2365]
1. Version of Directus: v8.3.1.
2. Error message: no any error message.
3. Steps to reproduce
![bug](https://user-images.githubusercontent.com/1665522/71454007-77cc2a00-27c9-11ea-95f4-5e2c5160a538.gif)

**Comment by rijkvanzanten** [comment]
Looks like the template option is using JSON as language itself, making it impossible to add anything else but JSON.

**Comment by rijkvanzanten** [comment]
Here's our culprit:

https://github.com/directus/app/blob/a95f97b722e435b8193affb0292bdcefda651d9d/src/interfaces/code/meta.json#L25-L32

This should be using the `code` interface instead of the `json` interface

**Comment by everyx** [comment]
update: still exist in 8.6.1

**Comment by rijkvanzanten** [comment]
This was fixed in https://github.com/directus/app/pull/2641
