### ISSUE TITLE
v8.3.1 collection translate not applied on detail page.

### ISSUE THREAD

**Issue by everyx** [directus/app#2366]
1. Version of Directus: v8.3.1.
2. Error message: nothing.
3. Steps to reproduce.
![bug](https://user-images.githubusercontent.com/1665522/71454098-fcb74380-27c9-11ea-8d61-588613cfa72e.gif)

**Comment by rijkvanzanten** [comment]
This

https://github.com/directus/app/blob/a95f97b722e435b8193affb0292bdcefda651d9d/src/routes/item.vue#L384

should be

https://github.com/directus/app/blob/a95f97b722e435b8193affb0292bdcefda651d9d/src/routes/item.vue#L405
