### ISSUE TITLE
Repeater does not display name

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#2372]
After I upgrade 8.3.1, repeater does not display name.It works in 7.11.0

![image](https://user-images.githubusercontent.com/8030134/71561455-9d02b600-2ab1-11ea-9d0d-6c7d88aacc5b.png)

![image](https://user-images.githubusercontent.com/8030134/71561489-ebb05000-2ab1-11ea-9564-027574c4d5cc.png)

**Comment by rijkvanzanten** [comment]
What are the options you used for the repeater?

**Comment by rijkvanzanten** [comment]
Can you reproduce this on the demo?

**Comment by cdwmhcc** [comment]
> Can you reproduce this on the demo?

Slack send you

**Comment by rijkvanzanten** [comment]
I'm on a different computer right now that doesn't have my slack installed ^^

Is this something that you can reproduce on the demo or does it only happen on your end? What settings do you use for the repeater?

**Comment by cdwmhcc** [comment]
> I'm on a different computer right now that doesn't have my slack installed ^^
> 
> Is this something that you can reproduce on the demo or does it only happen on your end? What settings do you use for the repeater?

I sent my account to your slack.😛

**Comment by rijkvanzanten** [comment]
I believe this is caused by the fact that you're using a non-supported interface inside the repeater (`photo` field: `file` interface). Once I manually set a value in that field the preview updates as well.

**Comment by cdwmhcc** [comment]
> I believe this is caused by the fact that you're using a non-supported interface inside the repeater (`photo` field: `file` interface). Once I manually set a value in that field the preview updates as well.

I checked it carefully, it should not be caused by the reason you said.

I moved checkbox from top to bottom and edit diplay template {{name}} - {{password}} to {{name}}

it worked.
