### ISSUE TITLE
One to Many makes saving very slow！

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#2374]
I use the latest version of DIrectus, https://github.com/directus/directus

![image](https://user-images.githubusercontent.com/8030134/71577014-8732d680-2b2d-11ea-8ca3-b403aa71bd3a.png)

As shown in the picture, when I add more and more versions and update records to the software, the saving is getting slower and slower, it will take more than 1 minute, and most cases will fail. (Not more than 10)

It worked in 7.11.0.

**Comment by rijkvanzanten** [comment]
Can you provide a sql dump of a minimal reproduction of this?
