### ISSUE TITLE
ID field appears empty on relation field

### ISSUE THREAD

**Issue by ventouris** [directus/app#2375]
I created a many to one relationship field where the primary key of one table maps to the primary key of another table. I added in bulk some data directly from the database and both the table and the details of the collection with the many to one rlt appears empty. In details view, when I click on the empty dropdown I get the right entry of the other table preselected.

**Comment by rijkvanzanten** [comment]
Could you provide a SQL dump with a minimal reproduction of this issue?

**Comment by ventouris** [comment]
Sorry. I realised that I did some manual changes in the db a few days ago and I messed up the relationship field. It is working as it should now
