### ISSUE TITLE
Optional Seconds in Time Interface

### ISSUE THREAD

**Issue by pachiraDIG** [directus/app#2377]
Hi, guys! Just found Directus and I LOVE it.

I'd like to request a quick option be created in the Time Interface to remove seconds from the formatting. This will be extra clean for my clients with their "Events" collection needs.

( Minutes could be optional as well, but I can't think of a good use case. Your judgment! )

Thanks : )

**Comment by benhaynes** [comment]
I like it! I think SQL would still save the time with `:00` for empty seconds, but that's fine. Also, we could maybe include `string` as a data type for these time interfaces too... since some users don't need actual dates/times, just a way of formatting/entering a datetime string.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
