### ISSUE TITLE
File Preview should use un-cropped image by default

### ISSUE THREAD

**Issue by hiepsaxo** [directus/app#2379]
The image preview in version 8 is not good, but it's very nice in version 7, you can see my attached files.
What's wrong?

![file_v7](https://user-images.githubusercontent.com/14315857/71656816-8093a180-2d6f-11ea-97ca-59f4a882487a.JPG)
![file_v8](https://user-images.githubusercontent.com/14315857/71656817-838e9200-2d6f-11ea-903c-fef44ec282de.JPG)

**Comment by rijkvanzanten** [comment]
The file interface has an option `crop_preview` that controls whether or not the preview will be cropped. Disabling that option makes it look like v7
