### ISSUE TITLE
Wrong placeholder for user-roles interface

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2380]
I found a component select bug not correctly showing label in v8.3.1, because I upgraded from v8.2.0.

Select Role 
**Directus 8.2.0**
![image](https://user-images.githubusercontent.com/19521054/71692456-ea17ae00-2d77-11ea-8f1e-fc13e3621c61.png)

**Directus 8.3.1**
![image](https://user-images.githubusercontent.com/19521054/71692615-6ad6aa00-2d78-11ea-97c5-3c774408292a.png)

• Version of Directus: 8.3.1
• Steps to reproduce
http://{{SERVER_API}}/admin/#/{{PROJECT}}/users/+

**Comment by rijkvanzanten** [comment]
I'm pretty sure 

`interfaces.user.roles-choose_role` 

should be

`interfaces.user-roles.choose_role`
