### ISSUE TITLE
Is there a problem with the permission design in the rule?

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#2388]
![image](https://user-images.githubusercontent.com/8030134/71840496-64d62580-30f8-11ea-9594-04acea83e132.png)

![image](https://user-images.githubusercontent.com/8030134/71840347-20e32080-30f8-11ea-8d52-3e735dc2dcf9.png)

If relationships are used in a collection(ex:o2m,m2o,m2m), you must enable viewing rights for relationships.Otherwise, the public endpoint cannot be used for operations such as create and update

I don't know the logic, but I think it's strange

**Comment by cdwmhcc** [comment]
I use update to operate, and always prompt Code: 3, message: "unauthorized request". I tried for a long time to find out the reason

**Comment by rijkvanzanten** [comment]
Yes you're right. It is needed for public reads of relationships, as the user needs to be able to read relationships in order for the API to figure out what to fetch. It's the same as the situation where you need read access to `directus_files` if you want to read files relationally.

https://github.com/directus/app/issues/2346 should alleviate this unexpected behavior

**Comment by cdwmhcc** [comment]
> Yes you're right. It is needed for public reads of relationships, as the user needs to be able to read relationships in order for the API to figure out what to fetch. It's the same as the situation where you need read access to `directus_files` if you want to read files relationally.
> 
> #2346 should alleviate this unexpected behavior

I think it is correct that `directus_files` and `directus_users` are not public by default, because this is well understood, and only needs to be adjusted in the APP to solve it.

`directus_relations` is not public, it will not affect the viewing permissions of other relationship collections, but it will affect `update / create / delete`.It is not easy to understand. I think this is caused by the unreasonable API design.
