### ISSUE TITLE
can't find module if located in src/modules/my-module

### ISSUE THREAD

**Issue by lhapaipai** [directus/app#2395]
Hi,
I created a new module with `directus-extensions create module my-module`.
if I build my module with `directus-extensions build --input src/ --output dist/`  and copy the result into : `public/extensions/custom/modules/my-module`, there is no problem.

 but if I want to build my own directus-app from the source `git clone https://github.com/directus/app.git`, copy my `meta.json` and `module.vue` into `src/modules/my-module` and run `npm run build`, I obtain this error if I wanted to access this url : `/admin/#/[my-project]/ext/my-module`

error message from console :
```
[Vue warn]: Failed to resolve async component: function () {
        return {
          component: component,
          error: _module_fallback_vue__WEBPACK_IMPORTED_MODULE_4__["default"],
          loading: _module_loading_vue__WEBPACK_IMPORTED_MODULE_5__["default"]
        };
      }
Reason: Error: Cannot find module './my-moduleinput.vue'
```

module.vue :
```vue
<template>
  <div class="my-module">
  	<h1 class="type-title">My Custom Module</h1>
  </div>
</template>

<script>
	export default {
		name: 'MyModule'
	}
</script>

<style lang="scss" scoped>
.my-module {
	padding: var(--page-padding);
}
</style>
```

meta.json :
```json
{
  "name": "module-test",
  "version": "1.0.0",
  "icon": "person",
  "types": ["string"],
  "options": {}
}

```

version of Directus : 8.3.1

**Comment by rijkvanzanten** [comment]
Putting custom modules inside the source code itself, and building it as a whole is not supported yet.

**Comment by rijkvanzanten** [comment]
I'm going to close this as it's not something that's intended to work in the (current version of) the codebase. I'm actively working on migrating the _pages_ over to be individual modules. Part of that transition is starting to use the modules folder at which point the feature mentioned in the OP will start working as well.
