### ISSUE TITLE
Allow to link M-M fields to a pre-set filter when in list view

### ISSUE THREAD

**Issue by mpfrenette** [directus/app#2396]
I am currently using Directus 8.0.0 but Rijk confirms that this is not fixed yet.

So, the idea is that when you have a M-M (or M-1/1-M) field, you can see it in the Directus list view listed as "456 items"

What we would like is that if you click on "456 items", it opens that collection with a filter pre-set to list the 456 items.

Imagine a collection called Categories.

And a rows:

Tables    456 items

Clicking on 456 Items will open the Products collection, with the 456 items that belong to the Tables categories.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
