### ISSUE TITLE
How to update field values dynamically

### ISSUE THREAD

**Issue by MathiRa** [directus/app#2400]
When updating an Input using this.values.input_name = 'some value' from a child component or change by javascript in the child custom component, the new value is displayed correctly in the input on the parent, but not updated on save. If values are changed manually, everything works as expected.

Is there a way to call an onchange event for inputs on the parent component, from the child?
Could you help me?.
Thanks.

**Comment by benhaynes** [comment]
@rijkvanzanten — should this be moved to the Docs? Does this work as of now if updated through the store?

**Comment by rijkvanzanten** [comment]
@MathiRa I'm assuming you're either making a custom interface or modifying the source code of Directus. Either way, you can stage a new value for any field on page to be saved to the API by using

```js
this.$store.dispatch('stageValue', { field: '', value: '' });
```

**Comment by benhaynes** [comment]
@rijkvanzanten — I'm not sure where it would go, but let's plan on adding this to the Docs today!

**Comment by MathiRa** [comment]
@rijkvanzanten thank you for your code. I'm working on a custom interface and your code is what I needed, 

@benhaynes Thanks for your support, I think it's a good idea to add this to the docs.

Thank you both!
