### ISSUE TITLE
WYSIWYG - Style Update

### ISSUE THREAD

**Issue by philleepflorence** [directus/app#2404]
The CSS override is a big hit with end-users, but the one issue is the inability to change the font of the WYSIWYG Interface.

It would be nice to have a CSS override for the WYSIWYG Interface so that the Interface can be made to look like other Interfaces or close to the actual application consuming the data.

Right now the interface is only in a Serif font when most of the Application is San Serif.

**Comment by benhaynes** [comment]
The way it's passing in that CSS is pretty hacky/manual right now... not sure how possible this is, but hopefully someone can find a better solution. We could try to add a sans serif option, but serifs are better for legibility in long form text (the reason I chose it).

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
I think the easiest / most flexible way is to add an advanced interface option that allows you to inject any custom CSS into the tinymce instance. That allows you to override the fonts, but also allows you to make it look and feel a little closer to where your content is actually going to be rendered, making the wysiwyg more.. wysiwyg.
