### ISSUE TITLE
Question: API Path URL (change?)

### ISSUE THREAD

**Issue by SinoBoeckmann** [directus/app#2406]
Hey there!
First, thank you! Very nice work!

Second, should it be possible to access (public) endpoints within a "wildcard" project name?
Like, I can currently access my API within the following URLs

- GET http://localhost:8080/_/items/category
- GET http://localhost:8080/____________/items/category
- GET http://localhost:8080/whatEverIWant/items/category
- GET http://localhost:8080/NotEvenISawThatComing/items/category

Would it be possible to rename the whole thing to something like we can set up ourself? 
Maybe there is something and I don't know, so please let me know! Or at least to limit it to _ as it is mentioned in the documentation?

Thank you very much!

Best
Sino

**Comment by rijkvanzanten** [comment]
I'm not a 100% sure what you mean, but the first path in the page is the name of the project you're targeting, which enables the ootb multi-tenancy of Directus. Every different name in that first path corresponds to a different project, and therefore a different database.

Most paths of the API, except for the global `/server/` ones, are `/:project/endpoint`

**Comment by SinoBoeckmann** [comment]
Thats whats written in the documentation and makes absolute sense.

My "problem" is more that all of this routes are right and link to the same project (if there is just one) and so I get always the same result.

- GET http://localhost:8080/_/items/category
- GET http://localhost:8080/____________/items/category
- GET http://localhost:8080/whatEverIWant/items/category
- GET http://localhost:8080/NotEvenISawThatComing/items/category

BUT shouldn't just one route just work? And all the others are not because there is _no_ project when there is no name like that?

**Comment by rijkvanzanten** [comment]
Oh! That doesn't sound right! It should throw an unauthorized error for unknown projects
