### ISSUE TITLE
Feature request: centralized content languages list

### ISSUE THREAD

**Issue by EOtrade** [directus/app#2407]
Hey! It will be nice to see a list of languages that can be bound to the Translations field. Or even a possibility to create a custom collection of languages and select what field is responsible for locale id and what field for the name of a language. Now it is hard to create again and again the same list of 24 languages for each of 35 collections.

**Comment by rijkvanzanten** [comment]
I think https://github.com/directus/app/issues/2083 will already greatly improve that flow. Having the same config in multiple places could get quite confusing too

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by lluishi93** [comment]
Hi @rijkvanzanten ,

How is the centralized languages collection/setting/whatever going? Is it going to be ready for the next release? It is making managing our languages quite difficult, since we have to be modifying every component (and we have A LOT) every time we add a language to the site.

Best regards

**Comment by rijkvanzanten** [comment]
No updates yet. It's not a very often requested feature, and there's a couple high priority bugs that need addressing first, so I don't think I'll be able to work on this that soon (for the next release). A PR is always welcome of course.
