### ISSUE TITLE
make WYSIWYG interface resizeable

### ISSUE THREAD

**Issue by Wendenburg** [directus/app#2408]
# Feature Request
make WYSIWYG interface resizeable

## What problem does this feature solve?
The interface's dimensions are far too smal if you add more content. You quickly loose the overview...

## How do you think this should be implemented?
there is a div with the classes "tox tox-tinymce". Just add to the css "resize:both"

## Would you be willing to work on this?
does not make sense for a small property like this...

**Comment by rijkvanzanten** [comment]
> does not make sense for a small property like this...

I would argue that makes it an even better candidate for a PR 😉

**Comment by rijkvanzanten** [comment]
TinyMCE is configured to autoresize with a max height of 1000:

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Another option might be to allow the user to configure the max height / disable it all together

**Comment by Wendenburg** [comment]
> I would argue that makes it an even better candidate for a PR 😉

true, true... at some point i will dive into that vue.js setup ;)
