### ISSUE TITLE
ctx-menu open in wrong position

### ISSUE THREAD

**Issue by gianpesto** [directus/app#2411]
# Bug Report
When i click the field-label in order to reset a value, the ctx menu is opening in a wrong position.

## Steps to Reproduce

1. set up a collection with lots of fields and dividers
2. Click on a field label way down

## Expected Behavior
the ctx manu opens in the same position of the field-label

## Actual Behavior
the ctx menu opens in a wrong position, possibly out of the viewport as well.

## Other Context & Screenshots
![grafik](https://user-images.githubusercontent.com/12595753/72355647-25a36800-36e8-11ea-8ff2-f7f5babce7cf.png)

## Technical Details

- Device: Desktop
- Directus Release Version: 8.3.1
- Install Method: cloned

**Comment by rijkvanzanten** [comment]
@gianpesto on what browser / os does this occur?

**Comment by gianpesto** [comment]
@rijkvanzanten 
![grafik](https://user-images.githubusercontent.com/12595753/72424121-c1cf7c80-3785-11ea-9469-ce759f2cfaa8.png)

sry for ze poor testing, ja

**Comment by gianpesto** [comment]
@rijkvanzanten same happens in chrome.
probably in IE 6-11 too.

**Comment by rijkvanzanten** [comment]
> probably in IE 6-11 too.

Ha wouldn't doubt it. 

---

Does this only happen when being scrolled down?

![image](https://user-images.githubusercontent.com/9141017/72630900-528e8f80-3921-11ea-917e-2f2e6350dc07.png)

I can't seem to reproduce it on my end..

**Comment by gianpesto** [comment]
@rijkvanzanten it seems to happen after the first divider with dividerStyle == 'Small'.
all fields before that work nice.

**Comment by rijkvanzanten** [comment]
That's very odd. Lets see if that's something caused by Directus or if we should open an issue on the repo for `v-popover`

**Comment by gianpesto** [comment]
@rijkvanzanten i could figure out why this happens:
body and html have a height of 100%, that casts to the height of the viewport. #app never grows out of that height, so if you'll have a colelction with enough fields that will cause the #app container to be higher than the relative heght of body, than the vue-popover opens in a wrong position, that is the bottom most coordinate of #app:

![grafik](https://user-images.githubusercontent.com/12595753/73271199-733bcc80-41e0-11ea-9c86-b942076622ae.png)

change html, body "height: 100%;" to "min-height: 100%;"

**Comment by rijkvanzanten** [comment]
Yeah! [Changing the ctx menu to use window as boundaries element instead of the body](https://github.com/directus/app/pull/2433/files) (that is not the full height) works too 🙂
