### ISSUE TITLE
File Preview is showing "This item is not available"

### ISSUE THREAD

**Issue by gianpesto** [directus/app#2412]
# Bug Report
I hav euploaded a pdf in a file-field, i saved the collection, reopened it, and WHAM! the preview said "This item is not available" 😭

## Steps to Reproduce

1. set up a translated collection with lots of fields and dividers and a file-field
2. upload a pdf in that file-field
3. save the collection
4. click back into the collection
5. see the broken file preview

## Expected Behavior
see the file preview

## Actual Behavior
shows "This item is not available"

## Other Context & Screenshots

![grafik](https://user-images.githubusercontent.com/12595753/72356044-d9a4f300-36e8-11ea-8c55-dfeaf39be59a.png)

## Technical Details

- Device: Desktop
- Directus Release Version: 8.3.1
- Install Method: cloned

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/pull/2560
