### ISSUE TITLE
Style table broken on updated 8.4.0

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2419]
• Version of Directus
  8.4.0

• Error message (if any)

Updated Directus 8.4.0 
I notice damage to the table style by over-adjusting text

**Directus 8.2.0**
![Directus 8.2.0](https://user-images.githubusercontent.com/19521054/72479162-a3877200-37c1-11ea-8e23-82c7cd4c1cdf.png)

**Directus 8.4.0**
![image](https://user-images.githubusercontent.com/19521054/72479299-18f34280-37c2-11ea-9d04-e58725aeec03.png)

• Steps to reproduce
- http://{{baseURL}}/admin/#/{{projectURL}}/settings/collections/{{collectionName}}

**Comment by benhaynes** [comment]
Let's just have the first column overflow hide with ellipses... and make sure there's a tool-tip so you can see the whole name.

**Comment by andgar2010** [comment]
> Let's just have the first column overflow hide with ellipses... and make sure there's a tool-tip so you can see the whole name.

![56lRZiWQWK](https://user-images.githubusercontent.com/19521054/72628198-d6de1400-391b-11ea-9b0b-5871baeb41a0.png)
