### ISSUE TITLE
Mirror slug content on create only, not modify.

### ISSUE THREAD

**Issue by blob100** [directus/app#2421]
Slugs can be used to create website filenames from the Page Title.
But if the Page Title is later modified then the slug (filename) also updates and the old reference to the filename changes. This is a problem for search engine indexing and for anyone who has linked to the old url.

Is it possible to add a feature so the slug only updates from the mirrored field on creating an item, not on modifying it?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
