### ISSUE TITLE
Limiting relationship selection to subset of items

### ISSUE THREAD

**Issue by GMTA** [directus/app#2423]
I'm wondering how to implement a very common use case in database relationships in Directus. Consider the following model:

```
director:
- id
- name
- directed_movies (O2M)

movie:
- id
- name
- director (M2O)
```

Let's say I want to ask every director what their favorite movie that they themselves directed is. So I add a new relationship:

```
director:
- id
- name
- directed_movies (O2M)
- favorite_directed_movie (M2O)

movie:
- id
- name
- director (M2O)
```

When editing a director item, this new `favorite_directed_movie` field's options should be limited to the movies present in the `directed_movies` field of that director. How do I go about this?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by GMTA** [comment]
Thanks @benhaynes !

> first, that would be a M2O, since multiple directors can like the same movie

No, the use case in my example would be the favorite movie that they directed, not all movies.

**Comment by benhaynes** [comment]
Ahh, true! However I still think the data structure would be the same (we don't have a o2o). Also, maybe a single movie could have multiple directors? Eg: Coens or Wachowskis 

But I digress... 😉

**Comment by cbix** [comment]
I second this feature request. Three ideas how to approach this from a user's perspective:

Option A. In the O2M definition, next to the "Allow Select" toggle, provide a dropdown of [Collection Presets](https://docs.directus.io/api/collection-presets.html) that gets applied to the selection, with "All items" being the default. However, this wouldn't allow complex filters like director = movie.director as proposed by @GMTA.
Option B. Use basically the same view of the collection listing in the selection window, including search/filters/presets.
Option C (more complex). Provide means of custom and more complex filters like director = movie.director.
