### ISSUE TITLE
Onboarding: "Create Collection" Button for New Installs

### ISSUE THREAD

**Issue by Zyles** [directus/app#2424]
# Feature Request

I always judge software usability by the first encounter.

First impressions - great! I am impressed.

However. I had to go read the docs on how to create a new collection.

Why is there no "Add new collection" button in the collections menu for example?

Or an "Edit collection" button on the collection itself?

Why do I have to navigate to the settings page?

That is my only complaint so far.

Thanks.

## What problem does this feature solve?

Usability.

## How do you think this should be implemented?

Adding buttons where they are most logical to be found.

## Would you be willing to work on this?

No.

**Comment by benhaynes** [comment]
Yes. I have been wanting this for a while — it's very jarring to get dropped into the platform with no onboarding. I'd like to have this button at the very least... but also some tooltip style onboarding to show new users around.

**Comment by Zyles** [comment]
Not only new installs.

I suggest adding a plus icon here or something similar:

![image](https://user-images.githubusercontent.com/1741593/72559744-cbe89c80-38a5-11ea-9af6-818f28475fca.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
