### ISSUE TITLE
How to obtain translation for Text divider

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2426]
• Version of Directus 8.4.0

I tried me but couldn't change for language

**Settings Divider:**
![image](https://user-images.githubusercontent.com/19521054/72629652-bd8a9700-391e-11ea-9f55-95365c5da244.png)

**Form collection:**

![image](https://user-images.githubusercontent.com/19521054/72629729-e01cb000-391e-11ea-82b0-811325cce5fc.png)

And Remove Divider text and added language for Divider

**Settings Divider changed:**
![image](https://user-images.githubusercontent.com/19521054/72630021-794bc680-391f-11ea-9e82-de9472a50906.png)

but no show label
**Form collection updated:**
![image](https://user-images.githubusercontent.com/19521054/72630049-89fc3c80-391f-11ea-8a60-b77d712dbe31.png)

**Comment by rijkvanzanten** [comment]
The translations in the field configuration are the translations for the alias column in Directus itself, not the settings of the divider interface.

I'll consider this a feature request to make the settings of the divider interface translatable.

@benhaynes this will most likely pop up more often; should we think of a way to standardize how we translate (certain) interface options? (placeholder / labels like this)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
I think having a catch-all translations "dump" in settings + the ability to enter `$t:` prefixed values in fields like this might be a good way of handling edge cases like this. For example, in settings, you can add:

```
{
  "en-US": {
    "my-custom-group": {
      "my-custom-value": "My Custom Value"
   },
  "es-419": { ... }
}
```

and then as a value for the divider setting use 

`$t:my-custom-group.my-custom-value`

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
