### ISSUE TITLE
Add translations to the calendar interface

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2427]
• Version of Directus 8.4.0

I can't change months name by user language. Where do you set up languages?

![image](https://user-images.githubusercontent.com/19521054/72632293-fb3dee80-3923-11ea-82b0-6f6248a1827a.png)

**Comment by benhaynes** [comment]
I assume this is an `enhancement`, right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
We're using `vue-flatpickr-component` (https://github.com/ankurk91/vue-flatpickr-component) for the calendar interface. It looks like they have support for localization as well. That being said, it might be a good idea to create our own calendar base component, so we can integrate it a little easier with Directus and our own translations (for example, we'll re-use the days of the week in many more places).

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
