### ISSUE TITLE
Automatic Project route after login

### ISSUE THREAD

**Issue by WebShapedBiz** [directus/app#2431]
Hi.
I believe that many devs would like for their clients not to be able to see how many other tenants are hosted on the same Directus and what are their names.
Maybe the Project selector could be displayed after a successful login, and only if there's more than one Project that holds that particular user's email. 

Anyhow, thank you for your time and effort in developing such a great product.

Cheers.

**Comment by vanling** [comment]
This would be nice! I was looking for a way to hide the drop down and 'select' the project in the background with mod rewrite. something like `customer.directus.host.com`.

**Comment by benhaynes** [comment]
I agree that we should be able to disable the "dropdown" of the project chooser... so it basically just a label for the current project and latency indicator if there's only _one_ available/public project. 

I don't think this will be based on the current user's email... since there's no way to know if that email exists in the other databases. But I'll leave that up to @rijkvanzanten.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by ozcanoguz** [comment]
Hello @benhaynes,

Does it mean that new issue should be created under board "Feature Request" or you've already created that ?

If so, would be beneficial to share its id for keeping track of the case.

**Comment by benhaynes** [comment]
This _is_ the ticket that's tracked on the Feature Request Board:

https://github.com/directus/app/projects/45#card-31889161

All tickets start off in the "Proposed" category, and then we shift it into "Accepted" the team thinks it's a good idea and it passes our 80/20 rule.
