### ISSUE TITLE
When creating a field that has to be "Required" - it fails

### ISSUE THREAD

**Issue by aliemba** [directus/app#2435]
Upgraded from 8.3.1 to 8.4.0.

When creating any filed that has to be "Required" like this;

![aonhfbmkpakncadb](https://user-images.githubusercontent.com/44196248/72798459-6ef13b80-3c43-11ea-950d-21980de390b4.png)

It fails like this;

![dabfcngfkdjbjbma](https://user-images.githubusercontent.com/44196248/72798490-803a4800-3c43-11ea-853e-2b4f1c03a6ef.png)

The result is;

![jnlkgobklinhmchp](https://user-images.githubusercontent.com/44196248/72798500-892b1980-3c43-11ea-886e-11c7ff7bf69e.png)

If you "Manage" and then set "Required" is ok.

**Comment by bjgajjar** [comment]
Maybe it's related to https://github.com/directus/api/issues/1660

**Comment by rijkvanzanten** [comment]
Duplicate of directus/api#1660
