### ISSUE TITLE
Bug Button Group?

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2437]
Version Directus: 8.4.0

Hi Team Directus,
I find that a button interface does not display correctly because I set parameters. It is not bug or misconfigured? 

![image](https://user-images.githubusercontent.com/19521054/72826784-7adefc80-3c47-11ea-859a-af167c7dbba7.png)

![image](https://user-images.githubusercontent.com/19521054/72826696-51be6c00-3c47-11ea-9f18-d3d713019e4a.png)

![image](https://user-images.githubusercontent.com/19521054/72826762-70246780-3c47-11ea-859c-34f80a26d121.png)

**Comment by lluishi93** [comment]
When is this bug going to be released? @rijkvanzanten thank you

**Comment by rijkvanzanten** [comment]
The bug itself was already released, the fix will be released in the next release, which is most likely around the end of this week 🙂
