### ISSUE TITLE
Files Interface triggers "Unsaved Changes" notification even when no changes have been made. 

### ISSUE THREAD

**Issue by goggi** [directus/app#2456]
# Bug Report

## Steps to Reproduce

1. Add a Files interface to your collection. 
2. Go to collection and open an Item inside the collection
3. Press on back without making any change. 
4. Unsaved Changes notification will appear 

## Expected Behavior

When following the steps above (1-3) I dont expect the Unsaved Changes notification to appear as I didn't make any change. 

## Actual Behavior

Unsaved Changes notification will appear 

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/1946339/72939840-fb981880-3d6d-11ea-9dde-221a3bb754eb.png)

Request Payload if I press save without making a change. "Images" is a Files interface
![image](https://user-images.githubusercontent.com/1946339/72940110-8416b900-3d6e-11ea-83a6-f3a7c9ca0a12.png)

Rijk was made aware on Slack. 

## Technical Details

- Device: [eg: Desktop]
- Directus Release Version: [eg: v8.4]

**Comment by goggi** [comment]
Commit didnt solve it for me.
Maybe try adjusting: 
![image](https://user-images.githubusercontent.com/1946339/72946998-e4aef180-3d80-11ea-9ad3-09d892ec5f77.png)
set items to null?

**Comment by rijkvanzanten** [comment]
It did on my end.. how did you text the specific commit? Do you have a running dev build?

**Comment by goggi** [comment]
Yeah, I have a dev build running. The suggestion I gave did solve it for me.
