### ISSUE TITLE
Allow the date created / modified fields to automatically convert that UTC value into the local datetime

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2463]
Version Directus: 8.4.0

Hello,
I don't know if this number has duplicated, because I looked for the discussions, but I didn't find any clarification or I don't know what I did wrong.
How to do correct time zone configuration for UI and API output.

Because I configure profile time zone is GMT-5, but I find UI and API shows GMT.

Settings User
![msedge_Xce7FBClEn](https://user-images.githubusercontent.com/19521054/73011852-1a84c200-3de3-11ea-964f-249ea349fe75.png)

UI
![msedge_MXaw19henr](https://user-images.githubusercontent.com/19521054/73011834-10fb5a00-3de3-11ea-95ab-9987b913ef27.png)

API
![WRbt8c94yP](https://user-images.githubusercontent.com/19521054/73011866-1f497600-3de3-11ea-825c-0f623c5159c5.png)

**Comment by philleepflorence** [comment]
In your API Configuration PHP File, you can add the following: 
```
date_default_timezone_set("<timezone>");
```

**Comment by andgar2010** [comment]
> In your API Configuration PHP File, you can add the following:
> 
> ```
> date_default_timezone_set("<timezone>");
> ```

Hello @philleepflorence, Thank you for your response. 
I was a little confused because you explained it, but I put a line of code in the project configuration file.
It shows no change in the time zone format. I had the server restart and it continues to replicate. 
Please clear me correctly setup steps. 
Thank you very much for your help. I'm waiting for your answer.

![image](https://user-images.githubusercontent.com/19521054/73270971-c5afc580-41ad-11ea-8645-b5c6944fe4ba.png)

**Comment by philleepflorence** [comment]
Can you try to add this to any API File:
```
die(date_default_timezone_get());
```
That should tell you if the timezone actually set.

The directus API core web file has the following code:
```
// =============================================================================
// Timezone
// =============================================================================
date_default_timezone_set(\Directus\get_default_timezone());
```

Also, what is the timezone used when interacting with the DB via the API (e.g. using Postman)?

This can tell you if it is the App sending the incorrect timezone or if the API is using the GMT default.

**Comment by andgar2010** [comment]
> Can you try to add this to any API File:
> 
> ```
> die(date_default_timezone_get());
> ```
> 
> That should tell you if the timezone actually set.
> 
> The directus API core web file has the following code:
> 
> ```
> // =============================================================================
> // Timezone
> // =============================================================================
> date_default_timezone_set(\Directus\get_default_timezone());
> ```
> 
> Also, what is the timezone used when interacting with the DB via the API (e.g. using Postman)?
> 
> This can tell you if it is the App sending the incorrect timezone or if the API is using the GMT default.

I had configuration change time zone in mysql. correct display changed.
![BGnQ0DFHVq](https://user-images.githubusercontent.com/19521054/73297938-77fd8200-41da-11ea-90d7-982b73df6beb.png)


I tried that you explained to put line in api configuration leaves by POSTMAN
`die(date_default_timezone_get());` : **America/New_York**

And set:
`date_default_timezone_set(\Directus\get_default_timezone());`

I did a test add an item via api show not changed time zone GMT
![image](https://user-images.githubusercontent.com/19521054/73297730-16d5ae80-41da-11ea-8e46-0dbb28ab9a99.png)

**Comment by rijkvanzanten** [comment]
The directus internal system date values are always saved as UTC. We can consider this a feature request to allow the date created / modified fields to automatically convert that UTC value into the local datetime. I would not recommend overriding the timezone in PHP like mentioned above, as that can cause many other unexpected issues to arise

**Comment by andgar2010** [comment]
@rijkvanzanten Can I request a new feature _"allow the date created / modified fields to automatically convert that UTC value into the local datetime."_ for this case or another new issue?

**Comment by rijkvanzanten** [comment]
We can keep it in this issue 👍

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
