### ISSUE TITLE
Resize columns interface M2M on 8.4.0

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2464]
Version Directus 8.4.0

Implemented with M2M interfaces is working, but cannot adjust column size. Is there any configuration possible?

![msedge_co8S5rjr72](https://user-images.githubusercontent.com/19521054/73012022-6df71000-3de3-11ea-8193-c8f4caca16ff.png)

**Comment by benhaynes** [comment]
Not as of now, but @rijkvanzanten is literally working on adding that feature this afternoon.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
