### ISSUE TITLE
Default Value of an Field is not getting persisted.

### ISSUE THREAD

**Issue by ithiru** [directus/app#2467]
*Version* - 8.4.0
*Current Behaviour* - Default Value of an Field is not getting persisted.
*Expected Behaviour* - Default value should be persisted, assume it would default when Adding new Row

Steps
- Visit https://demo.directus.io and login
- Edit any collection/Field
- Set Default Value as some value, for eg., I modified Customer Collection and Set default value of the Title as 'Mr'.
- Click on 'Save'
- Open the Title Field again, the default value is missing - looks like it is not persisting.
- When adding new row also the value is not getting defaulted.

**Comment by benhaynes** [comment]
@bjgajjar — check this one out... might be API and not App?

**Comment by ithiru** [comment]
This might be related to https://github.com/directus/api/issues/1668. Also I am using Maria DB v10.3

**Comment by rijkvanzanten** [comment]
This is a duplicate of https://github.com/directus/api/issues/1668
