### ISSUE TITLE
File preview giving 500 Internal Server Error

### ISSUE THREAD

**Issue by ashvin27** [directus/app#2473]
Directs Version: 8.3.1
Error: File preview giving 500 Internal Server Error
PHP Version: 7.2.10
MySQL version: 5.5.5-10.2.12-MariaDB

When I have move my DirectUS setup to cloud then the file preview is not working it is giving **500 Internal Server Error**, but it does not printing any error in error logs

Please help.

**Comment by rijkvanzanten** [comment]
Does your server meet all the requirements? Does Directus have read access to the correct folders? Are all the php extensions present?

Also, MySQL version 5.5.5 is technically not supported so that might cause issues
