### ISSUE TITLE
File Interface - Filters Format

### ISSUE THREAD

**Issue by philleepflorence** [directus/app#2475]
Currently unable to add filters successfully to the File Interface.

![image](https://user-images.githubusercontent.com/2633551/73191402-71490f00-40f5-11ea-80ce-23aacd20061a.png)

What is the correct format for entering filters in the File Interface - it is expecting an array of filter objects but all variations I enter throw a `422 (Unprocessable Entity)` or `TypeError: Invalid attempt to spread non-iterable instance`.

Adding filters as an object does not seem to work.

Please advise!

**Comment by philleepflorence** [comment]
Confirmed the following worked:

```
[
  {
    field: 'field-name',
    operator: 'eq',
    value: 'value'
  }
]
```

Tested in the Demo Settings for About Us using:

```
[
  {
    "field": "title",
    "operator": "contains",
    "value": "Thumper"
  }
]
```

**Comment by philleepflorence** [comment]
I think I figured out the issue:

In this file - `https://github.com/directus/app/blob/master/src/interfaces/many-to-one/input.vue`
You can pass the filter parameter to the `<v-item-select/>` component, I was using the same format that the Files Interface uses in a custom interface and it did not work.

What is the format the `<v-item-select/>` - `:filters="[]"` expects?
It seems the filters object is being pre-processed somewhere?
Is it a JSON String or Object?

The files endpoint with filter looks like:
 `/files?meta=total_count%2Cresult_count&limit=200&offset=0&sort=-id&fields=*.*&filter[title][contains]=Thumper`

However using the same logic in a custom interface with filter looks like this:
`/app/items/app_icons?fields=*.*&meta=total_count&limit=0&filter[0][field]=icon&filter[0][operator]=contains&filter[0][value]=account`

This is where the error is thrown.

**Comment by rijkvanzanten** [comment]
There's a difference between the syntax that's used internally and the one that is in the API parameters.

In the API, the format is `?filter[field][operator]=value`, using axios (or the sdk), that can be written as 

```js
{
  filter: {
    [field]: {
      [operator]: value
    }
  }
}
```

However, Directus system internals handle the format you listed above:

```
[
  {
    "field": "title",
    "operator": "contains",
    "value": "Thumper"
  }
]
```

as that's way easier to parse. If you're using any system internal components like that, you can expect filters to use the second syntax.

**Comment by philleepflorence** [comment]
I think I see the issue...

In the following helper:
```
https://github.com/directus/app/blob/master/src/helpers/format-filters.js
```

The following code:
```
export default function formatFilters(filters) {
	const parsedFilters = {};

	filters.forEach(filter => {
		parsedFilters[`filter[${filter.field}][${filter.operator}]`] = filter.value;
	});

	return parsedFilters;
}
```
yields `filters[filter[name][contains]]=account` in the URL.

But when I change it to:
```
export default function formatFilters(filters) {
	const parsedFilters = {};

	filters.forEach(filter => {
		parsedFilters[filter.field] = {};
                parsedFilters[filter.field][filter.operator] = filter.value;
	});

	return parsedFilters;
}
```
I then get `filter[name][contains]=account` in the URL, which works as expected.

Is there an update somewhere for the `<v-item-select/>` or can you confirm the `<v-item-select/>` is processing filters properly?

I was able to get it to work by duplicating and reworking `<v-item-select/>`.

Thanks!

**Comment by rijkvanzanten** [comment]
v-item-select is most likely going to be refactored soon, so I would suggest sticking with your custom duplicate for the time being to prevent having to migrate over when that refactor happens.
