### ISSUE TITLE
Add ability to subscribe to collection presets

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#248]
We can maybe base this on the combination of directus_activity and the user's last-access value. The only thing we'd need is a collection that tracks which user is "watching" what collection, so the application can fetch all the updates and display them somehow.

**Comment by benhaynes** [comment]
I like this. We should decide if it makes more sense to subscribe to a Collection Preset, or individual Items (like GitHub).

When you're subscribed to something and it changes, what happens? An email? An update in your notifications?

We also need to track `seen` for this. If you log in but don't look at your notifications you shouldn't "lose" those notifications.

This is a broad system... let's discuss how we want it to work!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
