### ISSUE TITLE
Allow <script> tag in WYSIWYG

### ISSUE THREAD

**Issue by BenjaminVega** [directus/app#2485]
Hi,
I have the version 8.3.1.
I would like to add ads tags in the WYSIWYG editor. I open the html code editor and add the <script> tags but after clicking on "accept" button, the changes are discarded.

I have been checking if there is any option to disable that behavior with no luck.

Could you help me with this?

Thanks,
Ben

**Comment by benhaynes** [comment]
Hmm, sounds like a sanitize/whitelist feature of TinyMCE. @rijkvanzanten , did you come across this during dev? Any way to make this an interface option?

**Comment by rijkvanzanten** [comment]
TinyMCE seems to strip out unsafe tags automatically. Seeing that wysiwygs render the content as preview, adding ads in there would also cause your ad to be rendered inside of the wysiwyg preview. Depending on what output you're using, I would personally recommend using a special syntax that you swap out for the real ad code in build time / run time @BenjaminVega.

**Comment by BenjaminVega** [comment]
Hi @rijkvanzanten I guess I can do that. 
I had the hope that a hidden option sort that out.
Thanks anyway!

**Comment by rijkvanzanten** [comment]
We'll still add the option 🙂 Just saying that I personally wouldn't use it in this case

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
I'm a little conflicted on this. Allowing script tags inside the wysiwyg opens up a huge attack vector for XSS. You're already able to add iframes (therefore widgets like soundcloud / youtube / disqus etc). Script tags will execute in the preview window too, so even for use with ad-trackers like mentioned above it will be hard to make sure you're not running the ad tracker in Directus, but only on your site.
