### ISSUE TITLE
Field note strips "_"

### ISSUE THREAD

**Issue by gianpesto** [directus/app#2490]
# The field notes seem to strip underscores from the string.

Directus Version 8.4

## steps to reproduce
- create a collection
- add (ie) a WYSIWYG - field
- add a note to it that contains a "_" (underscore)
- open the collection
- the _ is GÖNE! 😱

**Comment by rijkvanzanten** [comment]
The field note supports markdown, so the first \__makes the rest italic_ 🙂 

You can escape the `_` character by prefixing it with a `\`
