### ISSUE TITLE
Don't asynchronously load core interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#2495]
The core interfaces are reused in a lot of places. Seeing that they're shared across projects, we can easily load those upfront instead of when they're used.

**Comment by benhaynes** [comment]
Another thought I had (maybe worth discussing) is: could we start start asynchronously loading all the JS, CSS, and other files, directly after the login page initially loads?

I feel like there will always be at least three to five seconds after the login page loads but before the user finishes authenticating. Isn't that a non-obtrusive time we could asnc load the rest of the data?

Is it wrong in some way to load data before someone commits to logging in?

**Comment by rijkvanzanten** [comment]
That's what I was thinking when opening the original issue, didn't put it in enough words though 😁 

The thinking is:

* We don't want to include every interface in the main bundle, as that would increase the size of the JS exponentially (eg no need to load markdown interface in order to open the login page)
* Currently we asynchronously load interfaces when they are used, causing spinners and jumps on the edit page.

I want to move to an in between:

* Fetch the interfaces asynchronously right when the main bundle is loaded and executed, this would download them during the window that the user is logging in (like @benhaynes mentioned above)

**Comment by rijkvanzanten** [comment]
Closing this in favor of https://github.com/directus/app-next/
