### ISSUE TITLE
Add skeleton loader component

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#2496]
Relational interfaces take some more time to load, as they have to fetch related data. It would be nice if we can use a more interface appropriate loader than a spinner. Right now, you'll see a couple spinners on page, and the page will jump around when the interfaces are done loading. A skeleton loader could prevent this by rendering a gray outline of the element that will be rendered once it's done loading.

Examples:

![image](https://user-images.githubusercontent.com/9141017/73483724-ef174f80-436d-11ea-8073-0f435b1607d3.png)

![image](https://user-images.githubusercontent.com/9141017/73483728-f179a980-436d-11ea-92cd-e7401e257442.png)

![image](https://user-images.githubusercontent.com/9141017/73483735-f3dc0380-436d-11ea-9f2c-3de0a3b74ecb.png)

![image](https://user-images.githubusercontent.com/9141017/73483742-f6d6f400-436d-11ea-8f98-a48d8f0d48d7.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by andgar2010** [comment]
Could be [Skeleton ](https://quasar.dev/vue-components/skeleton)example of Vue.JS, but different framework

**Comment by rijkvanzanten** [comment]
Yeah! Most frameworks have a skeleton loaders 🙂 

another one: https://vuetifyjs.com/en/components/skeleton-loaders
