### ISSUE TITLE
Remove Delete button from file interface

### ISSUE THREAD

**Issue by simonking76** [directus/app#2497]
I would like to make a feature request to remove the Delete button from the file interface.

If the same file has also been added to other items or items in other collections, those items will break.

![directus-01](https://user-images.githubusercontent.com/2388352/73488279-8e553a80-43a0-11ea-8447-e717d1c021fd.png)

"Deselect" is sufficient to remove the file from an item and a file can be deleted from the Files section if required.

Thanks
Simon

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
