### ISSUE TITLE
Embeds in file library

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#250]
We need to figure out how to handle external video / image services

**Comment by rijkvanzanten** [comment]
The idea being is that you can view and manage used youtube videos in the same way as local files

**Comment by rijkvanzanten** [comment]
We only need to support YouTube/Vimeo for now... this code should already be in the API, so the global file upload modal (or whatever we end up with) should have the ability to input this.

**Comment by benhaynes** [comment]
Huge! This is another v6 feature that we lost... and it was used a lot (and clients ask about it now). The API already supports this so we need to get it in again.

**Comment by rijkvanzanten** [comment]
> The API already supports this

Any docs for it?

**Comment by benhaynes** [comment]
@WellingGuzman ?

**Comment by WellingGuzman** [comment]
No docs for this. as far as I am concern.

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/docs/issues/75

**Comment by WellingGuzman** [comment]
Ref: https://github.com/directus/docs/blob/master/api/reference.md#using-supported-embedded-urls

**Comment by benhaynes** [comment]
@rijkvanzanten — isn't this one done?

**Comment by rijkvanzanten** [comment]
Yup!
