### ISSUE TITLE
Feature request: allow tiny_mce plugin options

### ISSUE THREAD

**Issue by dur41d** [directus/app#2504]
TinyMCE allows setting plugin options like `paste_data_images` or `directionality: "rtl"`. Currently there is no way to set these options in the wysiwyg interface. I suggest adding a `plugin_options` json text area in the interface options tab to allow the user to specify these options in json. I already have PR for this.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
This was added in https://github.com/directus/app/pull/2506
