### ISSUE TITLE
Displays incorrect field data (date datatype) in table

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2510]
• Version of Directus
8.4.0

• Error message (if any)
![image](https://user-images.githubusercontent.com/19521054/73625148-97007780-4611-11ea-9f50-8f954405a04d.png)

• Steps to reproduce
**Saved data:**
![msedge_YMQUtK5lMW](https://user-images.githubusercontent.com/19521054/73625052-4ab53780-4611-11ea-939d-fc35ab96bdef.png)

**Comment by rijkvanzanten** [comment]
@andgar2010 What did you use for settings for the calendar?

**Comment by andgar2010** [comment]
> @andgar2010 What did you use for settings for the calendar?

![image](https://user-images.githubusercontent.com/19521054/73681843-2ac35980-468d-11ea-891b-e814a975097b.png)

**Comment by rijkvanzanten** [comment]
I meant inside the `options` tab in this modal 🙂

**Comment by andgar2010** [comment]
> I meant inside the tab in this modal 🙂`options`

![image](https://user-images.githubusercontent.com/19521054/73685835-d7550980-4694-11ea-808c-bf19cbf9c82a.png)
