### ISSUE TITLE
Sorting of Files not possible anymore?

### ISSUE THREAD

**Issue by peXed** [directus/app#2511]
Hello!

I'm using Directus: v8.4.0

Is the sorting of the files interface not possible anymore? I found an issue/feature request and I'm pretty certain the sorting worked at some point (https://github.com/directus/app/issues/1253). Is in the newer version of Directus the sorting of files not possible anymore?

The interface I'm getting now, is a normal list view, without sorting.
Is it something I can fix or should I add a new feature request?

Thank you very much!

**Comment by rijkvanzanten** [comment]
Does your junction table have a `sort` type column?

**Comment by peXed** [comment]
Ahh. Of cause. That is fixing the issue.

I let Directus autocreate the junction table and it did not add the sort. Thank you very much!
