### ISSUE TITLE
Allow filter in calendar

### ISSUE THREAD

**Issue by aliemba** [directus/app#2513]
8.4.0

When using the calendar "view" of a "collection" it seems to not update the calendar part after filtering

![image](https://user-images.githubusercontent.com/44196248/73656186-e2f20180-468f-11ea-9d80-f848c6fca9ea.png)

**Comment by Nitwel** [comment]
The reason why this is so, is that the calendar ignores the given items from directus and fetches the items by itself, which currently ignores any filters set in the search. I have to talk to @rijkvanzanten if this is just an easy implementation or not. Rijk toughts?

**Comment by aliemba** [comment]
Great!

And if it not functioning with filters, then the UI should not display the filter part when selecting the calendar view option - so that it is logical.

**Comment by rijkvanzanten** [comment]
@Nitwel I'm actually reworking the way the page chrome interacts with the layouts as a whole. We'll take this "offline" on Slack @Nitwel :)

**Comment by aliemba** [comment]
But just to be clear; it would be a very good feature to have in the calendar... The calendar isn't really that usable without.

**Comment by rijkvanzanten** [comment]
@Nitwel and I are actively working on this for the next major version 🙂

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
