### ISSUE TITLE
Ajust align vertical on Calendar on 8.4.0

### ISSUE THREAD

**Issue by andgar2010** [directus/app#2516]
• Version of Directus
8.4.0

![SharedScreenshot](https://user-images.githubusercontent.com/19521054/73661549-410aee80-4668-11ea-9caa-6f56c4dc8781.jpg)

This is not a big deal. Just set the correct aesthetic style

**Comment by benhaynes** [comment]
Haha, this is MY KIND OF TICKET! I love OCD design issues... thank you!

This would be a good one for a PR if anyone in the community is interested. ❤️
