### ISSUE TITLE
Collection view "checkbox" OCD

### ISSUE THREAD

**Issue by aliemba** [directus/app#2525]
Hi,

Great with the 8.5.0 release.

This issue was instant, (in compact mode)

![image](https://user-images.githubusercontent.com/44196248/73725480-b987b300-472d-11ea-8b69-5c3ba973562e.png)

**Comment by benhaynes** [comment]
Thanks @aliemba — we're in the process of completely overhauling all of our base components in the App. The "icon" was one of these, so we expected a few random alignment problems. We'll get this fixed asap and it'll be resolved in the next release (likely later this week).

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/pull/2530
