### ISSUE TITLE
Field "Date" configured as "relative" should not show "hours"

### ISSUE THREAD

**Issue by aliemba** [directus/app#2526]
8.4.0

If you configure a "Date" (ie. not "Datetime" where it is correct) field and set

![image](https://user-images.githubusercontent.com/44196248/73737621-40935600-4743-11ea-9aa4-ff74cad86a3d.png)

It should only show "days,weeks ect." and not go down to details as "hours"

![image](https://user-images.githubusercontent.com/44196248/73737686-628cd880-4743-11ea-8e58-3caaad9035be.png)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
