### ISSUE TITLE
Single & Hidden toggle button missing in admin area.

### ISSUE THREAD

**Issue by sjoerdkoelewijn** [directus/app#2533]
Hi there,

First of all, great work! I really like Directus :)

I ran into a problem trying to set a collection to single.

It seems that the hidden & single toggle buttons in the admin area are missing in v8.5.1.

When I go to Admin Settings > Collection and Fields > _my collection_  the toggles to make a collection single or hidden are not showing. (See screenshot 1)

**Screenshot 1 - How it looks in v8.5.1** 

![screenshot-1](https://user-images.githubusercontent.com/945223/73764840-e8c11300-4773-11ea-81c2-ce421d2bbfed.JPG)

**Screenshot 2 - The dropdown**
I only see a dropdown, (screenshot 2) where I can reset the value to default or clear the value, but I can't actually set the value. 

![screenshot-2](https://user-images.githubusercontent.com/945223/73764839-e8c11300-4773-11ea-953f-dd39eff7b65f.JPG)

When I look at the videos in the documentation it is clear that these toggle buttons where there in previous versions. (screenshot 3)

**Screenshot 3 - The buttons in a older version**
![screenshot-3](https://user-images.githubusercontent.com/945223/73764841-e959a980-4773-11ea-9da2-79e2fd76bb0b.JPG)

I'm new to Directus, so maybe I just don't understand how these buttons work?

I'm using the latest version v8.5.1 (I cloned the repo https://github.com/directus/directus.git) and tested with Firefox dev edition 73.0b12 (64-bit) & Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by rijkvanzanten** [comment]
Hoi sjoerd! Is this on a new installation or an upgrade from an existing (older) version?

**Comment by rijkvanzanten** [comment]
Seems like the seeder doesn't match the upgrade migrations. 

A temporary workaround is to remove the `RenameToggle` row in `directus_migrations`.

**Comment by sjoerdkoelewijn** [comment]
> 
> 
> Hoi sjoerd! Is this on a new installation or an upgrade from an existing (older) version?

Hoi Rijk, I did a fresh install of v8.5.0 which had this problem. After which I upgraded to v8.5.1 to make sure it wasn't fixed in the latest version before I filed the bug report.
