### ISSUE TITLE
datetime interface : error the date is not correctly parsed when modifying

### ISSUE THREAD

**Issue by lhapaipai** [directus/app#2538]
Hi there !
After upgrading from 8.4 to 8.5.3, I have a problem when modifying an item with the datetime interface.

```json
{"format":"ymd","localized":true}
```

step to reproduce :
the item is saved in correct format in the datebase : 2020-02-05 19:45:00
the item appear correctly in calendar layout.
edit this item if you want to change the date from the datetime interface.

instead of :
YYYY-mm-dd HH:MM:SS
2020-02-05 19:45:00
I've got :
mmHH-MM-SS
0219-45-00
 
![editing-datetime](https://user-images.githubusercontent.com/1088155/73792423-87fdfe80-47a4-11ea-82cb-cb3986ba6537.gif)

**Comment by rijkvanzanten** [comment]
This is most likely caused by the same problem as #2537.
