### ISSUE TITLE
Console error for M20 and O2M interface

### ISSUE THREAD

**Issue by Kinzi** [directus/app#2539]
Just updated directus to 8.5.3 and I now get some console errors for the M20 and O2M interface. Seems like some lodash stuff is not imported:

<img width="567" alt="Bildschirmfoto 2020-02-05 um 11 00 21" src="https://user-images.githubusercontent.com/6689405/73809731-b57b9400-4806-11ea-996a-eda806d7f63a.png">
<img width="559" alt="Bildschirmfoto 2020-02-05 um 11 00 31" src="https://user-images.githubusercontent.com/6689405/73809740-bad8de80-4806-11ea-8f9c-19d02fab6162.png">

**Comment by Kinzi** [comment]
Just saw this has kinda been fixed already in the app repo - can you push this to directus too?

Probably a typo "orderBy" in: 
https://github.com/directus/app/blob/f1065397d1c85c67af8a4cd2a7975405f8445438/src/interfaces/one-to-many/input.vue#L154

**Comment by adamkobor** [comment]
Same problem here. It looks like that it has been fixed in 8.5.3 and has been released as well, but the error is still here
<img width="481" alt="Screenshot 2020-02-05 at 10 38 30" src="https://user-images.githubusercontent.com/28044849/73829698-b232d900-4803-11ea-8d8a-51e969067348.png">

**Comment by adamkobor** [comment]
Okay, it turned out that this is the missing piece: https://github.com/directus/app/commit/f1065397d1c85c67af8a4cd2a7975405f8445438

**Comment by christianrr** [comment]
Still get the issue of missing orderBy in one-to-many interface...

**Comment by everyx** [comment]
`ReferenceError: orderBy is not defined` when add user to a role, maybe the same problem.

```javascript
vue.runtime.esm.js:1888 ReferenceError: orderBy is not defined
    at c.get (input.vue:287)
    at an.get (vue.runtime.esm.js:4479)
    at an.evaluate (vue.runtime.esm.js:4584)
    at c.itemsSorted (vue.runtime.esm.js:4836)
    at c.n (input.vue?e4f7:1)
    at vue-composition-api.module.js:604
    at ae (vue-composition-api.module.js:565)
    at c.a.render (vue-composition-api.module.js:604)
    at c.e._render (vue.runtime.esm.js:3548)
    at c.n (vue.runtime.esm.js:4066)
```
