### ISSUE TITLE
O2M file preview bug

### ISSUE THREAD

**Issue by alengodev** [directus/app#2547]
Hi,
there is a bug in file preview in O2M v8.5.4
![Bildschirmfoto 7](https://user-images.githubusercontent.com/25492962/73882372-37e57180-4862-11ea-9d86-f953cf607a50.png)

but working in preview listing
![Bildschirmfoto 8](https://user-images.githubusercontent.com/25492962/73882408-4a5fab00-4862-11ea-82c5-5cd0f628a52b.png)

THX

**Comment by alengodev** [comment]
404 Error when loading file preview ...
<img width="785" alt="Bildschirmfoto 9" src="https://user-images.githubusercontent.com/25492962/73882686-c9ed7a00-4862-11ea-8ac7-5fd8a281b67a.png">

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/pull/2560
