### ISSUE TITLE
Edit Color Interface starts "empty"

### ISSUE THREAD

**Issue by aliemba** [directus/app#2556]
v 8.5.4

Non critical - visual

Create a Color Picker

![image](https://user-images.githubusercontent.com/44196248/73949641-f94fc580-48fa-11ea-8820-d6e89b01b4cb.png)

Press to edit field latter

![image](https://user-images.githubusercontent.com/44196248/73949596-e9d07c80-48fa-11ea-945c-87e1a7d133c9.png)

It should show "options" as the other fields.

**Comment by rijkvanzanten** [comment]
The color picker interface doesn't have any options, so the tab not existing is expected behavior. That being said, the field-setup modal should open the `schema` tab if the `options` tab doesn't exist

**Comment by rijkvanzanten** [comment]
.. actually every interface does have the `interface width` option, so the tab should be there regardless

**Comment by benhaynes** [comment]
True, but will be removing the layout drop-down from interface options, hopefully soon, when we shift to the fields interface handling layout (width and sort order). This will greatly improve visualizing the form.
