### ISSUE TITLE
v8.5.4: repeater interface too slowly and crash

### ISSUE THREAD

**Issue by everyx** [directus/app#2588]
* Version of Directus: v8.5.4
* Error message (if any):
![image](https://user-images.githubusercontent.com/1665522/74098775-d9b4d900-4b56-11ea-80b4-c8ae0c99316b.png)
* Steps to reproduce
![bug](https://user-images.githubusercontent.com/1665522/74098986-55b02080-4b59-11ea-806a-d44b48dba18c.gif)

looks like open repeater interface more than once will use a lot of memory of browser, and browser will crash/slowly.

**Comment by rijkvanzanten** [comment]
It might be the use of the repeater within the modal that's causing the memory leak 🤔 

Are you able to reproduce this when using a repeater on a regular edit page @everyx ?

**Comment by everyx** [comment]
> It might be the use of the repeater within the modal that's causing the memory leak 
> 
> Are you able to reproduce this when using a repeater on a regular edit page @everyx ?

edit page is OK, collection meta edit page is slowly at my chrome and edge chromium with 8G ram windows 10 PC

**Comment by everyx** [comment]
Looks like v8.3.1 is much smoother than 8.5.x

**Comment by nicolas-t** [comment]
Hello,

I think it's related to the icons, each time `interface-icon` is called, 1000 icons are rendered.
It's rendered twice (left and right) for each repeater rows, so it quickly adds up.

If I replace the template of this file : 
https://github.com/directus/app/blob/master/src/interfaces/icon/input.vue

Like this : 
```vue
<template>
	<div class="interface-icon">
		Icons
	</div>
</template>
```

It fixes the slow rendering for me.

While we are there, I find these "icon pickers" very annoying, they take a lot of space, and are a pain to scroll around when I want to reach the bottom of the row.

I think they should be collapsed by default, using v-if to prevent thousand of components rendering.
Maybe we could also make `v-icon` a functional component to improve perfs, but I don't know how it works with the composition API.

**Comment by rijkvanzanten** [comment]
@nicolas-t good catch. Having it collapsed by default sounds like a good idea. We can also look into rendering the list virtualized to prevent the overhead.

I don't think we can make `v-icon` functional, as it has to calculate a couple values, and handle the click events properly:

https://github.com/directus/app-next/blob/dba5329d3136b2eb83f917380d52bdf20594f0e9/src/components/v-icon/v-icon.vue#L46-L69

**Comment by nicolas-t** [comment]
Hello,

I've created a small PR fixing this bug: https://github.com/directus/app/pull/2645

> We can also look into rendering the list virtualized to prevent the overhead.

Good idea but it might be tricky since you have your icon groups in rows, and depending on the context rows may have different widths (?)
