### ISSUE TITLE
Issue with files interface

### ISSUE THREAD

**Issue by zheng4uga** [directus/app#2597]
Having an issue with the file's interface where I used the cards view and select the "select existing" button will duplicate every item into the junction table which causes duplication on every file. I am using Directus 7.0.19. Please help

**Comment by benhaynes** [comment]
There have been _many_ updates since 7.0.19 ... and our small team can't troubleshoot installs that old. The first step would be to upgrade to the latest version: 8.5.4

https://github.com/directus/directus/releases
