### ISSUE TITLE
Add "Preview" button on Directus Activity

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2601]
We should be able to use the templated string "preview" button interface to include a button to the item that was edited... `/collections/{{collection}}/{{item}}` ... right? This would be really nice, since you would be able to navigate to the referenced item more easily.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
