### ISSUE TITLE
Discuss adding "Status" placard to Card view

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2603]
This can be accomplished using the text fields below, but since status is a relatively system thing, it might be nice to discuss more integrated ways to show a non-published item on a card listing. The same would apply to Calendar/Timeline/Map...

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
