### ISSUE TITLE
Merge Parent Child API

### ISSUE THREAD

**Issue by ghezeli** [directus/app#2616]
Hi
I need to show the relationship as a subset in the api output
 And I need to get this information with just one request
I have to make a few requests right now
----------
** child **
{
    "data": [
        {
            "id": 1,
            "title": "test",
            "category": 1
        }
    ],
}
--------------
** parent ** many to one
{
    "data": [
        {
            "id": 1,
            "title": "cat1",
        }
    ],
}
-----------------
**  Files need many request
{
    "data": [
        {
            "id": 1,
            "announcement_id": 1,
            "files_id": 2
        },
        {
            "id": 6,
            "announcement_id": 1,
            "files_id": 3
        }
    ]
}

**Comment by benhaynes** [comment]
Did you read the documentation about the fields parameter?

**Comment by saeid1** [comment]
I have the some Problem.
In documentation have a not founded 
for example: 
Company 1 -> n Products
or
Produkt n -> 1 Produkt_Category

**Comment by ghezeli** [comment]
> Did you read the documentation about the fields parameter?

Yes i read all document about this
but i can't find anything to solve this

**Comment by benhaynes** [comment]
OK — well it's not completely clear what you're specifically trying to accomplish here, but if your relationships are setup properly then you can use `?fields=*.*.*` to get relational data nested three levels deep in one call.

I've confirmed that this is working, so if you're still having issues then it would be best to open a Bug Report with more specific info (including your stack).

**Comment by ghezeli** [comment]
tank you
