### ISSUE TITLE
Signup with API

### ISSUE THREAD

**Issue by ghezeli** [directus/app#2624]
Hi
I need to signup with api
but i can't find in Document
https://docs.directus.io/api/authentication.html

**Comment by benhaynes** [comment]
You can create a user using this endpoint:

https://docs.directus.io/api/users.html#create-a-user

**Comment by ghezeli** [comment]
tank you
i gave this error
"Creating item to \"directus_users\" collection was denied"

i need, anonymous user can signup as a specified role, and they would can't signup as admin 
this user must be active

tnx
