### ISSUE TITLE
Life Time Token

### ISSUE THREAD

**Issue by ghezeli** [directus/app#2627]
hi 
i use directus to serve Mobile APP
i need using token to authenticate , but token expire at 20 min
i want set expire time to unlimited 

tnx

**Comment by benhaynes** [comment]
Please submit questions to StackOverflow — GitHub issues are for Bug Reports and Feature Requests.

**Comment by benhaynes** [comment]
Also, please read the docs first... this is one of the first sections of the API authentication page:

https://docs.directus.io/api/authentication.html#static-token
