### ISSUE TITLE
Get Item revision with nested field data

### ISSUE THREAD

**Issue by Tails** [directus/app#2628]
## situation 
- I have a collection "Container" that contains a reference to an item "Nested". 
- Now I adjust the field values of the nested item a few times. 
- Then I save the Container. 
- I expect that a few revisions of the Container now exist due to changing the value of Nested.
- I adjust the Public role to serve both Container and Nested collections.
- Then, I query a revision of the Container using https://demo.directus.io/thumper/items/container/1/revisions/2?fields=data.*.*

## issue
Now how do I get the Container item state with the nested data from the revision at the time when I was changing the Nested item? It seems only the first level of the Container item state is returned. Are changes to nested field values not committed to parent revision objects?

**Comment by benhaynes** [comment]
Did you save the parent item between changes on the nested item? 

When you change data through a parent item, all those changes are _staged_, but nothing actually happens (revisions included) until you save the parent. Otherwise there would be no way to "cancel" the whole operation.
