### ISSUE TITLE
Mindmap View

### ISSUE THREAD

**Issue by dgram** [directus/app#2629]
Hey,

we work heavily with directus and one of the things i always notice is that it will help much do have an mindmap view for the collection. Something like zenkits mindmap tool (https://www.youtube.com/watch?v=wICBOV2ZLmM).

It will also be very usefull if you have hierachical entries. We manage a bis marketing campaign database with directus and the view makes it super easy to have an perfect overview for this.

It would also make brainstorm super efficient with directus and an mindmap view.

What do you think about this feature?

regards

**Comment by rijkvanzanten** [comment]
That's really awesome. We would have to figure out a couple things though:

* Would this manage one collection, or have connections between collections?
* What kind of fields should we support in each node?
* If you click on a node, should we open a modal with the full edit form of that node?
* If this is all within one collection, what type of relationship would this be? (I assume each line is a m2m)

Do you have an example of how we could set this up in a SQL database so we could make it work in Directus @dgram ?

**Comment by dgram** [comment]
hey,

**Would this manage one collection, or have connections between collections?**
I think one collection handle most use cases, zenkit for example need an hierachical field to work with mindmaps (categories like parent/child field)

**What kind of fields should we support in each node?**
If nodes can be added/removed by the mind-map gui directly it would be helpful to support all fields (i.e. by a modal)

**If you click on a node, should we open a modal with the full edit form of that node?**
Yeah as described above, i think it's the best way for usability

**If this is all within one collection, what type of relationship would this be? (I assume each line is a m2m)**
In our use cases we handle all with many to one (save the parent id), we use them i.e. to work with 
- blog posts (make hierachical posts)
- marketing campaigns (main campaign with sub campaigns)

Theres an other example you can check out by zenkit (https://www.youtube.com/watch?v=_GiQFggI7Qo). On the description video you see an "Wiki-View" (which where also an perfect view-extend for directus). I think the many-to-one will (save parent node-ids) will makes it most easily to integrate and makes it most easily implement and makes it most easily to extend i.e. by more view-features (as described the wiki-view).

**Do you have an example of how we could set this up in a SQL database so we could make it work in Directus**
As described above i think the many-to-one will be an good case. The only "problem" on sql-storage site will be the node positions which we should discuss a bit closer i think.

Because of your relationship suggestion (m2m) i think this will make the implementation a little bit hard because of the multiple parent nodes, what do you think?

**Features whats have been an must have (as i think) are:**
- Filtering Nodes (for example make filtered out nodes readonly/not clickable or with lighter color)
- Add/Remove nodes via gui directly
- Drag & Dropable nodes (save nodes on dragged places)
- Edit node data/fields directly (by modal?) - this will be nice to be a long-term features, but for start it will be more than helpful to have an mind-map view, makes the work much easier.

**Features which are nice to have are:**
- Export mindmap to standard formats (i.e. freemind) etc.

regards, daniel

**Comment by rijkvanzanten** [comment]
I totally forgot about saving the coordinates of the individual nodes! Thanks for bringing that up. I guess we can require a "location" field that will save a `[x, y]` position of `px` based on the canvas of the node 🤔 

Another thing that would be nice is the ability to export the mindmap as PNG or PDF, but I'm not sure we can do that without some sort of back-end logic

**Comment by dgram** [comment]
Eventually there is an open source js library to handle the export cases (png, png), i research a while ago about the mindmap feature and search for some mindmap js libraries, there are some libraries to handle the maps.

For pdf generation, eventually it can be done directly on the client side? Or eventually by https://www.php.net/manual/de/class.v8js.php

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
