### ISSUE TITLE
Look into typescript

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#263]
Type definitions prevent bugs, but might increase code complexity too much.

**Comment by honzabilek4** [comment]
Hi, 
have you considered using [Flow ](https://flow.org/) instead? It's pretty straightforward and doesn't add that much complexity. It also integrates as a Babel plugin, which is already there. Depends, if the static type checking is what you're after.

**Comment by rijkvanzanten** [comment]
Good idea! Do you think the benefits of type checking outweigh the extra code “complexity” for developers not familiar with type checking?

**Comment by honzabilek4** [comment]
I think you can only benefit from the static type checking like this. There are no real disadvantages, since you don't have to use it everywhere. It's very flexible and allows you to incorporate the changes incrementally. Moreover the syntax is very simple and almost self explanatory.

**Comment by rijkvanzanten** [comment]
> Moreover the syntax is very simple and almost self explanatory.

This is the most important for me personally right now. I don't want to scare away potential contributors by introducing new and hard-to-learn syntax 😄

**Comment by rijkvanzanten** [comment]
I don't think the added code difficulty is worth the benefits.

**Comment by jooola** [comment]
@rijkvanzanten Have you changed your mind on this ? What about a slow/smooth migration to Typescript ?

I saw this introduction, and I have to say, Typescript + Vue + Decorators, is really sexy.
https://www.sitepoint.com/class-based-vue-js-typescript/

Also the transition can be made progressively.

**Comment by honzabilek4** [comment]
We've actually started using Typescript in some larger projects since that time and it makes much sense :) Also, it can be  adopted incrementally. (But not with decorators, the class syntax is going to be deprecated)

**Comment by rijkvanzanten** [comment]
I am waiting for Vue 3 to release at which point we'll be looking into migration over. The current object based structure in vue is just not great together with typescript, and does add a lot of overhead

**Comment by rijkvanzanten** [comment]
Class based components are a good in between solution, but I think relying on Vue's composition API will  be ideal moving forward

**Comment by jooola** [comment]
It has been a long time I didn't really dive in VueJs. So that is the class component that will be removed. Haha bad luck, I didn't discovered it.

Anyway, this might be a way to optimise the frontend.

Le 10 janvier 2020 14:30:37 GMT+01:00, "Jan Bílek" <notifications@github.com> a écrit :
>We've actually started using Typescript in some larger projects since
>that time and it makes much sense :) Also, it can be  adopted
>incrementally. (But not with decorators, the class syntax is going to
>be deprecated)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/directus/app/issues/263#issuecomment-573035817

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
