### ISSUE TITLE
Wiki View

### ISSUE THREAD

**Issue by dgram** [directus/app#2630]
As described in #2629 it would also be a game changer to have an wiki-view for directus.

At https://www.youtube.com/watch?v=_GiQFggI7Qo you have an idea what that could look like. It would be nice to use them i.e. for a blog-post collection with parent & child posts with the direct "description" view.

The sql-implementation could be done with an many-to-one relation and save the parent-id + by a sort field. For the view, we could add an selectable field (from the collections-field) to choose and show the description.

**Must have features:**
- Live View of the description field

**Nice to have features could be:**
- Live content edit on view
- Drag & Dropable sort (directly in view)

What do you think about the feature?

regards, daniel

**Comment by rijkvanzanten** [comment]
Interesting idea, little harder to execute though. The power here is that you basically have a rich page-builder inside a WYSIWYG that's able to inject any related item from any other collection. We'd have to figure out a way to support that. We could have a custom "snippet" syntax in Directus that allows you to include items in a wysiwyg context `[articles:15]`, but then there's no way that's being returned correctly by the API.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dgram** [comment]
i think in the first version it would be very helpful if theres an standard implementation (without directly edit the content in the view).

the main advantage for this in my opinion is, that you have an similar view like an blog (without to implement/develop an blog)
