### ISSUE TITLE
Create new item in one to many (O2M) relation

### ISSUE THREAD

**Issue by r0b78** [directus/app#2649]
This is a feature request, to have a create item button in the o2m relation

![image](https://user-images.githubusercontent.com/22716876/76063386-38e6ed00-5f4d-11ea-9e26-6b113f5d13f5.png)

**Comment by benhaynes** [comment]
Any reason why w wouldn't keep and just use the "Create New Item" that is below each interface? The current implementation removes an unnecessary click for users adding a new item.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Yeah, I agree with @benhaynes here. I don't see the reason why we would duplicate that button in here again
