### ISSUE TITLE
Permission issues after updating v7 -> v8

### ISSUE THREAD

**Issue by Kinzi** [directus/app#2651]
# Bug Report
I started updating my D7 project today. No I have trouble using the app. 

I did a fresh installation of 8.6.1 and plugged the D7 database in. 
I applied the changes from here: https://github.com/directus/directus/releases/tag/v8.0.0

The API seems to work via `curl`.  The app also finds the database and the initial login (`/authenticate` call) is working. However straight after I get `Unauthorized request` on this API call:

`http://directus8-via:8888/dev/users/me?fields[0]=id&fields[1]=avatar.*&fields[2]=email&fields[3]=first_name&fields[4]=last_name&fields[5]=locale&fields[6]=role.*&fields[7]=last_page&fields[8]=theme`

## Steps to Reproduce

1. Fresh install von latest D8
2. Plug in Database from D7 and update api.php
3. Login in and wait for redirect

## Expected Behavior
Login to see my collections

## Actual Behavior
Error Screen

## Other Context & Screenshots
<img width="1440" alt="Bildschirmfoto 2020-03-06 um 15 45 55" src="https://user-images.githubusercontent.com/6689405/76067207-961c8600-5fc1-11ea-8680-7a6333f53b67.png">

## Technical Details

- Device: Mac with MAMP
- Web Server: MAMP
- PHP Version: 7.2.x
- Database: MySQL
- Directus Release Version: latest
- Install Method: git clone

## Error Log:

<details>
<summary>API Error trace</summary>
<pre>
[2020-03-06 15:55:45] api[dev].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /directus8/src/core/Directus/Permissions/Acl.php:991
Stack trace:
#0 /directus8/src/core/Directus/Database/TableGateway/BaseTableGateway.php(1141): Directus\Permissions\Acl->enforceReadOnce
directus/directus#1 /directus8/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1151): Directus\Database\TableGateway\BaseTableGateway->enforceReadPermission
directus/directus#2 /directus8/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(1287): Directus\Database\TableGateway\RelationalTableGateway->fetchItems
directus/directus#3 /directus8/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(856): Directus\Database\TableGateway\RelationalTableGateway->fetchData
directus/directus#4 [internal function]: Directus\Database\TableGateway\RelationalTableGateway->getItems
directus/directus#5 /directus8/src/core/Directus/Services/AbstractService.php(347): call_user_func_array
directus/directus#6 /directus8/src/core/Directus/Services/AbstractService.php(289): Directus\Services\AbstractService->getDataAndSetResponseCacheTags
directus/directus#7 /directus8/src/core/Directus/Services/ItemsService.php(82): Directus\Services\AbstractService->getItemsAndSetResponseCacheTags
directus/directus#8 /directus8/src/endpoints/Items.php(43): Directus\Services\ItemsService->findAll
directus/directus#9 [internal function]: Directus\Api\Routes\Items->all
directus/directus#10 /directus8/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
directus/directus#11 /directus8/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
directus/directus#12 /directus8/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
directus/directus#13 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/directus#14 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#15 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#16 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#17 /directus8/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
directus/directus#18 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
directus/directus#19 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#20 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#21 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#22 /directus8/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
directus/directus#23 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
directus/directus#24 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#25 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#26 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#27 /directus8/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
directus/directus#28 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
directus/directus#29 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#30 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#31 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#32 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
directus/directus#33 /directus8/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus/directus#34 /directus8/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus/directus#35 /directus8/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
directus/directus#36 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/directus#37 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#38 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#39 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#40 /directus8/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
directus/directus#41 /directus8/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
directus/directus#42 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
directus/directus#43 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#44 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#45 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#46 /directus8/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
directus/directus#47 [internal function]: RKA\Middleware\IpAddress->__invoke
directus/directus#48 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#49 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#50 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#51 /directus8/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
directus/directus#52 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus/directus#53 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#54 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#55 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#56 /directus8/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(63): Slim\App->Slim\{closure}
directus/directus#57 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
directus/directus#58 /directus8/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#59 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#60 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#61 /directus8/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus/directus#62 /directus8/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus/directus#63 /directus8/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus/directus#64 /directus8/src/core/Directus/Application/Application.php(161): Slim\App->run
directus/directus#65 /directus8/public/index.php(5): Directus\Application\Application->run [] []
</pre>
</details>

**Comment by rijkvanzanten** [comment]
Is this an admin user you're trying to log in to?

Do you use any extensions that might block / clear cookies a little aggressively?

**Comment by Kinzi** [comment]
@rijkvanzanten Yes admin user.

I don't think I have any aggressive extensions. Also I tried different browsers with same result.

A phpsession cookie is set btw - if that was the question ;)

<img width="1439" alt="Bildschirmfoto 2020-03-10 um 09 12 19" src="https://user-images.githubusercontent.com/6689405/76272978-41258c00-62af-11ea-82a6-3636a8e26fdc.png">

**Comment by rijkvanzanten** [comment]
Could you verify the auto sign out value in directus settings?

I remember a case before where the expiry date of the cookies was _now_ which would make it disappear from the browser straight away

**Comment by Kinzi** [comment]
@rijkvanzanten sure if you tell me how? where is it in the db? what is it supposed to be?

**Comment by benhaynes** [comment]
`directus_settings ... auto_sign_out`

Should be... `10080`

**Comment by Kinzi** [comment]
@rijkvanzanten @benhaynes Nice this was it - Thanks guys!
