### ISSUE TITLE
Thumbnails aren't rendered properly when using API in nested folder

### ISSUE THREAD

**Issue by ErwinLiemburg** [directus/app#2652]
Hi there!

There seems to be going something wrong with retrieving the assets for the File Library (card view).

Assets are not shown due to incorrectly loading. Actually they are loaded from the wrong location.

For bugs, please include:
• Version of Directus: 8.6.1, tested this in MAMP Pro
• Error message: none
• Steps to reproduce: upload a file in File Library, thumbnail shows error icon

Directus tries to load the assets from:
[domain]/_/assets/d18y5efvj1w8w84g?key=directus-medium-crop

but this, I guess, should be:
[domain]/directus/public/_/assets/d18y5efvj1w8w84g?key=directus-medium-crop

As it seems, the correct path is missing.

This error probably originates in /src/layouts/cards/layouts.vue (src is loaded with the location, src method, line 77) and is handled by /src/components/card/card.vue (src is loaded in an image, line 42).

Hopefully this bug can be fixed soon.

**Comment by rijkvanzanten** [comment]
What does your configuration for storage look like in the api config file?

**Comment by ErwinLiemburg** [comment]
It has the default settings:

    'storage' => [
        'adapter' => 'local',
        'root' => 'public/uploads/test/originals',
        'root_url' => '/uploads/test/originals',
        'thumb_root' => 'public/uploads/test/generated',
        // 'key' => '',
        // 'secret' => '',
        // 'region' => '',
        // 'version' => '',
        // 'bucket' => '',
        // 'options' => '',
        // 'endpoint' => '',
        // 'proxy_downloads' => '',
    ],

**Comment by ErwinLiemburg** [comment]
src(item) function in layout.vue returns `/${this.currentProjectKey}/assets/${sourcePath}?key=directus-medium-${fit}\` (written to src) and card.vue uses this in `<img v-if="src && !error" :alt="title" :src="src" @error="onImageError" />`

**Comment by rijkvanzanten** [comment]
We should be able to re-use the api root url from `api.js` and prefix the thumbnail path with that:

https://github.com/directus/app/blob/992f2873023bf3a90724dda855d0d3eb7c321a41/src/api.js#L6
