### ISSUE TITLE
Time based API authorization (question)

### ISSUE THREAD

**Issue by nkcr** [directus/app#2655]
Say that I want to serve podcasts to my users but only the 10 most recent ones. After that the podcast should not be accessible to users anymore. Is there yet a way to do that without having to manually update or delete the older entries?

**Comment by benhaynes** [comment]
You can do this in the logic of your Application (server-side API token limits access private data) by only displaying the most recent 10. Or you could create a custom API endpoint to expose this data publicly.

**Comment by benhaynes** [comment]
I see this is on the `app` repo.. so if you are trying to do that within the App you would need to create a custom layout extension that creates this artificial limit.

**Comment by nkcr** [comment]
Thank you for the answer, I'm gonna try this out. 
Thanks for your amazing job, keep going!  👍
