### ISSUE TITLE
Customize header dropdown

### ISSUE THREAD

**Issue by nathannau** [directus/app#2661]
Hello,

On some collection, I want customize the dropdown menu on the right of header toolbar (Edit/VHeader/VHeaderButton/VContextualMenu).

Do you have an idea to do this properly?

Example of use case :
 - Direct print some selected items.
 - Send current item by mail.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
