### ISSUE TITLE
Description field type for File Editor view was changed to WYSIWYG

### ISSUE THREAD

**Issue by justrealmilk** [directus/app#2668]
I updated a client's version of Directus to a more recent version and where they were once using Markdown, new field values are now filled with HTML. They have hundreds of entries described in Markdown and now I don't know what to do...

I really don't want to need to fork Directus just to revert this surprise change lol

**Comment by rijkvanzanten** [comment]
What version where they on previously?

**Comment by justrealmilk** [comment]
7.4

**Comment by rijkvanzanten** [comment]
ahh ok. You should be able to change the interface in the DB directly without it causing any problems 🙂

**Comment by rijkvanzanten** [comment]
ahh ok. You should be able to change the interface in the DB directly without it causing any problems 🙂

**Comment by justrealmilk** [comment]
Incredible - fixed! Thanks a lot!
