### ISSUE TITLE
Add relational tags interface (w/ autocomplete)

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2669]
# Feature Request
I find the implementation of Tags in Directus too loose, even when compared to what WordPress does (!).
Tags are currently a list field where the user may input whatever they want. In fact, tags are generally understood as a **controlled taxonomy**, sometimes even **hierarchical**.

## What problem does this feature solve?
- users may input whatever they want in a Tag field. That lack of control will end up as **search noise**.
- there is no help for users when inputting tags

## How do you think this should be implemented?
By creating a centralized table of tags and establish a many to many relationship with the table.
Of course, I can implement that data structure by myself using:

- either a Multi-Select field (if the choice of tags is limited)
- or a Many to Many field + a tag table

But for non-developer users, it would make more sense to have it implemented upfront.

## Would you be willing to work on this?
By giving you advice, yes (I am a Thesaurus specialist)

**Comment by rijkvanzanten** [comment]
Good call. You can theoretically already use a m2m for tags, but I agree that it would be nice to have a combination of the tags interface's UI with the logic / validation of a m2m relational setup

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by asitemade4u** [comment]
Which I do, but the interface is much better with tags than in m2m fields.

**Comment by benhaynes** [comment]
I agree, which I why I added this ticket years ago (ahh, open-source timelines!). 😄 

Duplicate: https://github.com/directus/app/issues/749

However, this ticket already has more useful information, so I will remove the other from the Feature Request list in favor of this one.
