### ISSUE TITLE
Show total count in results

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#267]
Right now it says `200 Items`, but that's the _result_ count. It would be better if it said something along the lines of `Showing 200 out of 1913 items`

**Comment by rijkvanzanten** [comment]
Thoughts about the exact copy mr @benhaynes?

**Comment by benhaynes** [comment]
Having the TOTAL item count is hard... getting that number in large tables is expensive. But we can say:

`200 items displayed` page max
`16 filtered items` showing all filtered results
`200 filtered items displayed` page max for filtered results
`67 total items` when you can see all items

**Comment by rijkvanzanten** [comment]
I already have to fetch that info to differentiate between `no results` and `no items`
