### ISSUE TITLE
Manual Selection in Collection Lists

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2671]
# Feature Request
It would be practical (and a standard behavior among applications) to be able to select several lines of a Collection list by checking the checkbox of the first line, then check the ch3eckbox of the last line while holding the `SHIFT` key.

## What problem does this feature solve?
Being able to manually select several contiguous records in a Collection list

**Comment by rijkvanzanten** [comment]
I wish I could give this more than 1 👍 hah

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
I agree — I've mentioned it elsewhere, but I think we'll want to do a "keyboard sprint" (to include accessibility) to review and cover all of these good use-cases.

**Comment by rijkvanzanten** [comment]
❤️ , 👍 , tomato, potato
