### ISSUE TITLE
Access the application log from the Web interface

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2672]
# Feature Request

I have noticed that many wrong actions (I am testing Directus...) end up giving confusing messages to the developer.
For example:

1.   I add a wrong keyword in the list of displayed columns in the Files field Option page -- the field is called Gallery
1.    When I access a record in the collection, here is what the Gallery field displays (there are files in the Gallery field):

![Screenshot-20200320-160337](https://user-images.githubusercontent.com/11460106/77203061-f503f400-6ac5-11ea-92a3-975730974b8c.png)

Instead, it would help to have an error displayed on screen and recorded in the Activity area.

## What problem does this feature solve?
The error messages are somewhat obscure

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
Yes, I really think this is a big one. We can think of the best way to expose this info (to the devs, and less so to the users). Perhaps a friendly error notification comes up in the App that directs more technical users to review the `console.log`? Then we can push details to the log for proper debugging.

@rijkvanzanten maybe you already are, but this should be baked into the foundation of App-Next in a single/global way (catching, handling configuration issues, etc). Do you agree?

**Comment by rijkvanzanten** [comment]
There can't be a global way to catch _all_ errors, configuration issues, and all other things. We have a global "Whoopsie a JS error happened" handler, but config issues in the individual interfaces should be handled on the interface itself (eg check if all options are set in o2m before trying to render)

**Comment by benhaynes** [comment]
Right — I meant more of a single place to output that experience, that all the different places can use to create the notification and log in the same way.
