### ISSUE TITLE
Create Groups of Collections

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2673]
# Feature Request
At one point, now that I have chosen Directus, I will have approx. 40 Collections managed in Directus.
Having them all, ordered in alphabetical order, in the left sidebar is good but not very usable.
It would help to have a **two level sidebar**, with groups and individual collections at the first level, then only collections at the second level, accessible through a **menu**.
In the same spirit (Strapi does this), it would be helpful to **add a color to each Collection** > would color the icon in the sidebar and also give color accents to the main Collection list and display.

## What problem does this feature solve?
Too many Collections in the Sidebar

## Would you be willing to work on this?
To write the doc, both in English and French

**Comment by asitemade4u** [comment]
WOW, outstanding feature.

Should be more visible in the doc!

**Comment by benhaynes** [comment]
Not sure about color accents natively, but that's what custom modules and CSS overrides are for. _Maybe_ a simple color dot beside the name.

However I would be open to having an accordion option for nav link groups! That seems like it would solve things in longer custom headers. Thoughts?

Rijk, you have that beautiful accordion component ready to go?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
