### ISSUE TITLE
Shadow SQL Views in a similar way you do with SQL Tables

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2678]
I am aware Directus wants to stick to its motto "Database first" but some *light* discrepancy with the standard SQL management would be of a great help.

## Context
It is IMO simpler to manage a database using pure SQL code, a dedicated scripting language as Liquibase, or a SQL client (Datagrip, DBeaver) than using Directus.
I understand Directus more like an end-user interface, a data aggregator, coming **after** the database has been engineered.

## Current situation
I am aware you are working on an import module, but even with the module developed, mirroring data from an SQL database to Directus is cumbersome in these situations:
- the SQL database in use is not MySQL/MariaDB: it is my case, as I use PostgreSQL for its geospatial capabilities (I am aware of your plan to extend the SQL databases, but there is no ETA on that)
- data in the SQL database are split between related tables. Currently, it is not possible in Directus to perform a related import, as Airtable actually does: re-link records by foreign key by using the final value of the linked record.

### Shadowing Views
One of the great tools in SQL are **Views**, that allow, among other things, to select and sort records, to display related records from other tables, to perform transforms, etc.
If Directus was able to shadow Views as it does with Tables, a lot of shortcomings would be solved and the dynamic link between Directus and the original database would never have to be broken, as most treatments would occur in the SQL database.
### Limitations
Of course, the solution would be *read-only* in Directus, as it is impossible to retro-engineer in Directus the processes that have given the results in the View.
### Advantages
But for people like me who use Directus partially to aggregate immutable database information before publication, I think it would:
- limit the number of Collections needed in Directus (meaning: related tables), and therefore limit the complexity of the data structure in Directus
- be practical for Reference tables and allow for much simpler inter-table referencing.
- Besides, it would allow users to go on using **specialized tools** upstream: I, for example, use Digikam as an asset management application. Every treatment is performed in Digikam and its database. There is no need for Directus to manage asset data whatsoever. Same idea with the bibliographic reference I manage using Zotero.
### Requirements
- Collection would be read-only.
- Create a Primary Key in each View-Collection: would allow relations to and from other Collections.
- *Optional*: add input fields to the View-Collection. Not mandatory though as, using a Primary Key, one can link the View-Collection 1-1 with another standard Table-Collection.

**Comment by benhaynes** [comment]
Absolutely! This is pretty high up on our API list.

I'll add this reference, but close this as a duplicate: https://github.com/directus/api/issues/1800
