### ISSUE TITLE
api[my-project].ERROR: InvalidArgumentException: There was a problem connecting to the database: SQLSTATE[HY000] [1203]

### ISSUE THREAD

**Issue by DoubleFacess** [directus/app#2680]
Hi,
finally, with Version 8, i installed Directus and begin to populate it. But its very difficult to connect; when this appens (try and retry, cleaning browser cache and so on),  i found this in the app page. 
The correct connection is a bit random, if i can say.
I controlled the log and this is the stack trace. Im asking if there is some var to change in the core of the app, because i think that i cannot change something in the shared apache server config (or maybe i don't know). 
Thanks a lot. (I apologyze if the thread is similar to other opened, resolved and closed).

![immagine](https://user-images.githubusercontent.com/53007001/77330887-414a7080-6d20-11ea-977a-e783fe9970eb.png)

+++++++++++++++++++++++++

[2020-03-23 15:12:46] api[my-project].ERROR: InvalidArgumentException: There was a problem connecting to the database: SQLSTATE[HY000] [1203] User exampleuser already has more than 'max_user_connections' active connections in /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php:115
Stack trace:
#0 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(103): Phinx\Db\Adapter\MysqlAdapter->connect
#1 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(145): Phinx\Db\Adapter\PdoAdapter->getConnection
#2 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(164): Phinx\Db\Adapter\PdoAdapter->query
#3 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(250): Phinx\Db\Adapter\PdoAdapter->fetchAll
#4 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(227): Phinx\Db\Adapter\PdoAdapter->getVersionLog
#5 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(219): Phinx\Db\Adapter\PdoAdapter->getVersions
#6 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(264): Phinx\Db\Adapter\AdapterWrapper->getVersions
#7 /home/mhd-01/exampledir/htdocs/directus/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(307): Phinx\Migration\Manager\Environment->getVersions
#8 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Util/Installation/InstallerUtils.php(235): Phinx\Migration\Manager->migrate
#9 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Util/Installation/InstallerUtils.php(222): Directus\Util\Installation\InstallerUtils::runMigrationAndSeeder
#10 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(13): Directus\Util\Installation\InstallerUtils::updateTables
#11 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#12 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#16 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#17 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#18 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#19 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#20 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /home/mhd-01/exampledir/htdocs/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#24 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#25 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#26 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#29 /home/mhd-01/exampledir/htdocs/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#30 [internal function]: RKA\Middleware\IpAddress->__invoke
#31 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#34 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#35 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#36 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(63): Slim\App->Slim\{closure}
#40 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#41 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#45 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#46 /home/mhd-01/exampledir/htdocs/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#47 /home/mhd-01/exampledir/htdocs/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#48 /home/mhd-01/exampledir/htdocs/directus/public/index.php(5): Directus\Application\Application->run [] []

**Comment by rijkvanzanten** [comment]
The error 

> SQLSTATE[HY000] [1203] User exampleuser already has more than 'max_user_connections' active connections

indicates to me that you have a problem in the server configuration regarding the connections to the database
