### ISSUE TITLE
Support file interface as repeatre field

### ISSUE THREAD

**Issue by everyx** [directus/app#2690]
Hi,

The file interface only stored the directus_field id, so it's easy to add it in repeater interface? so we can store files and texts in the one repeater field.

**Comment by benhaynes** [comment]
This will be supported in the Relational Repeater — but the current repeater interface does not handle any relational data. Single File _could_ be an exception since it doesn't require relational setup... but our current flow doesn't support that.

**Comment by rijkvanzanten** [comment]
> Single File could be an exception since it doesn't require relational setup... but our current flow doesn't support that.

That's false. Even if we could store the ID on the client side, there's no way for the API to return the correct nested data, as the repeater doesn't contain any "real" fields or relationships
