### ISSUE TITLE
Add YAML to the list of supported languages in Code fields

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2694]
# Feature Request
Please add YAML in the list of languages supported by `code` fields

## What problem does this feature solve?
Useful to aggregate YAML to markdown texts into fully formed Web pages

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
CodeMirror actually supports a bunch more languages than the ones we expose. We should asynchronously try loading the language based on the config in runtime, instead of build time. That way, we can expose all codemirror's supported languages, without blowing up the bundle size
