### ISSUE TITLE
Change column sizes in Collection lists

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2695]
# Feature Request
It would be nice (and fairly usual) to be able to change column sized in Collection lists.
Also, a global optimized size change using, for example, double click on a column separator.

## What problem does this feature solve?
Column width may hide relevant information.

## How do you think this should be implemented?
Asx in every list based GUI out there: Excel, LibreOffice, etc.

**Comment by benhaynes** [comment]
I agree — this is good _icing on the cake_ stuff that we will definitely dive into once we're out of "stability" mode.

As for implementation, I actually always right-clicked and manually typed in a column "resize" in pixels... I didn't even know about double clicking the border! I agree that that seems like the ideal way to reset the column width from user saved to default. @rijkvanzanten — can we reliably capture the double-click event?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Yeah, that's no problem. There's a native `dblclick` event in JS :)
