### ISSUE TITLE
Browse view doesn't display more than 4 columns

### ISSUE THREAD

**Issue by Vadorequest** [directus/app#2709]
The Browse view doesn't display more than 4 columns, even if there is plenty of space available.

I'd prefer to have the ability to scroll horizontally to see other columns, it shouldn't be hardcoded.

![image](https://user-images.githubusercontent.com/3807458/78462785-ab2a2900-76d5-11ea-849b-ff2f3a6179e4.png)

![image](https://user-images.githubusercontent.com/3807458/78462807-f04e5b00-76d5-11ea-8fdc-e5cfa68452b0.png)

**Comment by rijkvanzanten** [comment]
Click the (i) in the top to manage the settings for this view, in there, you can chose what fields to display and in what order.

**Comment by Vadorequest** [comment]
![image](https://user-images.githubusercontent.com/3807458/78465019-e0904000-76f0-11ea-9c73-93d601180459.png)

Thanks... How did I miss that.

**Comment by benhaynes** [comment]
Just means we need to improve the UX a bit so it's easier to find! 

@rijkvanzanten — what about adding a "+" icon to the right of all column headers on the tabular layout... when clicked, it just opens the sidebar fields component? If you like that I can add it to the v9 designs.

**Comment by Vadorequest** [comment]
That, or a "Edit layout" icon/button on the right of the Collection's name? (header)

Avoids taking space in small devices, avoids repetition. The idea is similar (we look at something there, not on the right panel), it's just a matter of UX/UI.

**Comment by benhaynes** [comment]
The header space is very valuable (filtering, and conditional action buttons), so it wouldn't go there. A small icon in the table header MIGHT work, but the goal is to help users understand that these options are all in the info sidebar... so we don't duplicate buttons throughout the UI.

In other words, I'd rather have an onboarding tutorial for users than busy up the App.

**Comment by rijkvanzanten** [comment]
> In other words, I'd rather have an onboarding tutorial for users than busy up the App.

I agree with this. Telling you to click the `(i)` to manage the layout in this case would've been enough

**Comment by Vadorequest** [comment]
Yeah, that's what one may think at first. But I actually clicked the (i) when I got started and saw that menu, and closed it because I was just looking around and didn't need it. But when I actually needed it I couldn't find it again. 😅 

Maybe that's just me

**Comment by rijkvanzanten** [comment]
Yeah, cause you didn't have the knowledge of what to expect to find in that section. If you would've known that that's where you'd find configuration options for the current view, you'd be more likely to look in there for options regarding the table view 🙂

**Comment by Vadorequest** [comment]
Yup, be both agree that once you know it's there then it's not a problem anymore.
