### ISSUE TITLE
How to display/hide a collection, per role?

### ISSUE THREAD

**Issue by Vadorequest** [directus/app#2712]
Is there a way **not to display** a Translation collection for a user, while still allowing him to see it from the related Collection?

I have a "Customers" collection and a "Customer Translations" collections. i’d like my end users to only see the Customers collection, and manipulate the translations from there (because it doesn’t make sense to duplicate this, UX wise)

I tried to remove read access from “Customer Translations” for this role but this also blocks reading from the Customers collection.

I guess what I truly want is more a display-related feature rather than an API-related feature.

**Comment by rijkvanzanten** [comment]
You can go into the collection settings and enable the "Hidden" option. This will hide it from the navigation sidebar.

**Comment by Vadorequest** [comment]
@rijkvanzanten This "Hidden" option applies to all users, it's not customisable per user/role. 

 It doesn't exactly answer my question, but it's a workaround that does the job.

**Comment by Vadorequest** [comment]
Ah, found it. It's named Collection Listing.

https://docs.directus.io/guides/roles.html#collection-listing
