### ISSUE TITLE
Feature request - Nested roles

### ISSUE THREAD

**Issue by Vadorequest** [directus/app#2714]
# Current limitations

The way roles and permissions are currently implemented allows for great flexibility.

Especially, the `allow mine` and `allow role` provide some great workarounds for complex role requirements.

But it's still not flexible enough for many use-cases, such as when:
- having multiple users from the same organisation that must only access their organisation’s data, and may have different roles (org admin, org project leader, org translator, etc.) (Multi-tenancy within the same project)

# Potential solutions/designs

Nested roles are meant to solve those use-cases, for instance:
- “C1 - Admin”
- “C1 - Project Leader”
- “C1 - Translator”
- “C2 - Admin”

> Where `C1` means "Customer 1"

For instance, by allowing a pattern (regex, etc.) as a new option when selecting who has access (e.g: `C1 -*`), we could match all C1 roles and allow them all at once. Also, this would automatically apply to new roles that match the pattern

A few considerations, though:
- just gotta make sure we have a solid way of merging permissions, eg making sure that all child roles "start off with" the permissions set on the parent level, and extend from that
- also making sure the child role can't be granted "more" permissions than the parent level, cause that's an accidental vector for problems

> We're also toying around with the idea to base permissions on conditions instead of toggles for read/update/write etc, so instead of saying "READ: none / mine / role / all", you'd be able to say "READ: when role field (e.g: CA - Admin) contains X" - Rijk
>
>You would save the "role" or "owner" on the item itself, and then base the permissions on the value of that field

# Status

The design isn't defined and is still WIP.

It may be related with https://github.com/directus/app/issues/763 (based on some common features)

**Comment by benhaynes** [comment]
Thank you for outlining this, @Vadorequest.

I don't think we'll be going the "nested roles" route... we've been discussing this for months and the team all seems to think that Dynamic Permissions is the way to go... and lets you do pretty much anything you need.

https://github.com/directus/api/issues/511

**Comment by Vadorequest** [comment]
Thanks, I've read your specs and it seems to cover a larger use cases indeed!
