### ISSUE TITLE
RFC - Interface request - AND/OR/NOT nested conditional JSON builder

### ISSUE THREAD

**Issue by Vadorequest** [directus/app#2715]
# Functional specifications

The interface’s goal is to:
- visually (in a friendly way) allow to build the JSON containing a deep-nested AND/OR/NOT combination (similar to GraphQL filters implementation)
- be included as a core interface
- > Having a re-usable filter component could be very useful (if not just for internal system use) - Rijk

- The generated JSON may follow https://github.com/UnlyEd/conditions-matcher#function-prototype specifications (MIT, very flexible/extendable). 

<img width="1366" alt="Capture d’écran 2020-04-05 à 13 56 32" src="https://user-images.githubusercontent.com/3807458/78512193-d0389d80-77a2-11ea-99c8-bd90766c17c6.png">

![image](https://user-images.githubusercontent.com/3807458/78512202-e3e40400-77a2-11ea-8131-75c0b7156a5d.png)
(zoom)

The goal is to have a configurable interface where 
- The related field is configurable (e.g: User.age, Campus.id, program.id, etc.)
- The condition is configurable (e.g: equals, not equals, higher than, lower than, in, etc.)
- The matching value is configurable (e.g: int, string, relationship)
- All the fields would be Directus fields (either core or created)

Something similar is in-progress for conditional fields, and may be re-used:
![image (7)](https://user-images.githubusercontent.com/3807458/78466170-6b2b6c00-76fe-11ea-9873-c17cb50f6ee6.png)

# Concerns

- if that relies on a proprietary format than we have to think through if it's worth adding as a core interface
    - It's MIT
    - This is a good simple example of how flexible it is: https://github.com/UnlyEd/conditions-matcher/blob/master/examples/simple-match/index.js
    - It basically uses dynamic object keys as field names and match them against a given context
    - https://github.com/UnlyEd/conditions-matcher/blob/master/examples/array-match/index.js bit more complex example
- > Just gotta think through if we'd ever want to support alternate output structure's, or if there should be options to set like the divider character ( I see you use __ ) etc etc etc - Rijk
    - It would be possible if necessary

# Community

This is a community RFC, please share your thoughts and use cases! 😉

**Comment by Vadorequest** [comment]
@rijkvanzanten I've updated the description with a newer screenshot regarding the UI

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Vadorequest** [comment]
@rijkvanzanten @benhaynes Do you have any thoughts about this becoming a Core component?

@rijkvanzanten you told me you were building something similar right now, what are your plans? Could it be re-used? I'd like to know where I'm headed if I'm meant to develop this in a reusable way for everyone.

**Comment by benhaynes** [comment]
I defer to Rijk on that — it seems like it could be useful in the system, but we'd need to make sure the UI is intuitive for non-technical users.

**Comment by Vadorequest** [comment]
We're designing it for non-technical users, that's the biggest part of the challenge.

**Comment by EugenioSantos** [comment]
@benhaynes  good morning, is this feature still in progress?

**Comment by rijkvanzanten** [comment]
@EugenioSantos Yeah! This is the design direction we're going with as of right now:

![CleanShot 2020-09-14 at 09 39 04](https://user-images.githubusercontent.com/9141017/93092984-26710d00-f66e-11ea-8139-6211c9be936d.png)
