### ISSUE TITLE
Create a output file of the current configuration (config snapshot)

### ISSUE THREAD

**Issue by Vadorequest** [directus/app#2719]
I'd like the ability to build an output file which lists all of the project's configuration.

This output could be text, markdown, etc. 

The goal is to visually print the current configuration, to be able to compare different configurations. It's not meant to be importable or anything like that, but could be used with a diff tool to easily find differences between two configurations.

Additionally, this could be generated every time a change is made to the structure, similar to a git commit log.

It could be very useful for debugging purposes, or support.

It could also be used in tutorials, by providing a clear and testable configuration that should be matched to follow the tutorial (e.g: "do this and that and you should end up with such output")

**Comment by benhaynes** [comment]
Could you be more specific about what you mean by "project configuration"? We're including a server detail page in v9 that will have the project config file output, but you can see/compare that right in the config file. It will also include the server info though, so that will help.

**Comment by Vadorequest** [comment]
Basically:

- List all collections
- For each collection 
    - list all configuration (name, note, hidden, single, etc.)
    - list all fields
    - for each field
        - list all configuration (interface, schema (name, default value, note, required, readonly, etc.), options (field width, monospace, et.))

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
