### ISSUE TITLE
[Feature-Request] Adding custom icons to directus

### ISSUE THREAD

**Issue by r0b78** [directus/app#2726]
Many Times you need to add customs icons to a collection or to a collection preset
![image](https://user-images.githubusercontent.com/22716876/78666145-26d1d480-7894-11ea-96fe-121eace27cdd.png)

**Comment by rijkvanzanten** [comment]
By custom, you mean totally custom SVGs, or the ability to pick out of the available icons in the icon library that we use? (material icons in this case)

**Comment by r0b78** [comment]
I think the right way is to add the custom SVG to the available icons and then can be selected for the bookmarks and colections

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
