### ISSUE TITLE
token expired soon

### ISSUE THREAD

**Issue by ghezeli** [directus/app#2729]
Hi
i need set expire time for user token  to 30 days
i set auto sign out but not working
![image](https://user-images.githubusercontent.com/5620958/78756041-5f0a0d80-798f-11ea-9d95-359823fa6aca.png)
please help me

**Comment by benhaynes** [comment]
Auto-sign out is for the Application, not the user tokens in the API (I believe). This is a question for @rijkvanzanten ...

**Comment by rijkvanzanten** [comment]
Yup. A new option will be introduced to allow configured the TTL of the JWTs soon. See https://github.com/directus/api/pull/1798, https://github.com/directus/api/pull/1843
