### ISSUE TITLE
Update item error 500

### ISSUE THREAD

**Issue by ghezeli** [directus/app#2730]
hello everybody
i want to update an item
but i get error 500
i flow this tutorial
https://docs.directus.io/api/items.html#update-an-item

but not working
other routes working good
just patch route not working
tanks

**Comment by benhaynes** [comment]
Hey @ghezeli — apologies, but I'll have to close this one unless you can provide more information. A 500 error could be just about anything, so you'll need to check you logs (apache, php, mysql, directus, etc) so you can add more context to this ticket. I will re-open once the right info is in here. Also, please don't just dump all of your logs in here for us to look through... these tickets are for bugs, not helping resolve server/configuration issues.

Thanks!
