### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by mblind** [directus/app#2732]
Hi Guys,

A Tab would be great, if i have many items and categories, my fingers are burning from scrolling :)

**Comment by benhaynes** [comment]
Hey @mblind — could you add a bit more info here? A "tab" is kinda ambiguous...

**Comment by mblind** [comment]
Yes, of course. Take a look to my picture. The Tabs will change the Content. So its easier to Categorize the Content Fields Group. The Dividier is a good Tool, but its better (for me) to see the important stuff a head.

[https://freeimage.host/i/Jo8vNp](https://freeimage.host/i/Jo8vNp)

**Comment by benhaynes** [comment]
Ahh, gotcha... thanks!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
