### ISSUE TITLE
"info" is shown only to admin users

### ISSUE THREAD

**Issue by zghib** [directus/app#2735]
Hey everybody, 
I'm trying to configure directus as a team collaboration tool.
So I have 
 1. writer role - who can create/edit owns items
 2. reviewer role  - who can accept or reject

In my case,  when the writer finished his work he writes in 'Leave comment window...' Something like
'@user_1 Please review my work'.

The problem here is that this comment isn't shown to reviewer or writer anymore.
Only the admin role can see this comment. 

Step to reproduce:
1. Create two custom roles
  -writer with permisions- all (draft status) 
  - reviewer  with permision - (change only status field)
2. login with a writer user, write something in  Info/"Leave comment info..."
3. observe that this text disappear on next refresh
4. login as admin role- see that everything is in place

Expected result:
 on refreshing or next login as a writer I want to see everything that I've written in comment window

**Comment by rijkvanzanten** [comment]
Can you check if those user roles have read access to the Directus Activity table?

**Comment by zghib** [comment]
@rijkvanzanten thanks a lot it works :) 
Just change permissions for Activity table to ALL solve the problem.
Case closed :)
