### ISSUE TITLE
Primary keys ignore hidden_browse flag

### ISSUE THREAD

**Issue by Fabian-G** [directus/app#2739]
Version: 8.6.1

# Expected Behaviour

Setting a "Hidden on Browse" to false for a primary key results in the PK being shown on the browse page.

# Actual Behaviour

The primary key value for each item is not visible on the browse page. One has to navigate manually to the info sidebar and enable the id column.

# Steps to reproduce

1. Create a new Collection.
2. Set "Hidden on Browse" for the automatically created Primary Key to false.
3. Create a new item in the collection
=> The created item is listed without primary key on browse page

**Comment by rijkvanzanten** [comment]
The tabular layout defaults to the first 5 columns after the primary key for it's default display. This is by design (@benhaynes )

**Comment by benhaynes** [comment]
Yup! We could be clearer and call that option "disable on browse" or "remove from browse"... but I don't mind "hidden". I think once you understand how to turn fields on/off for the Item Browse page, this all makes sense. Many collections have 10+ fields, so showing them ALL in the table by default would make it too busy (IMO).

**Comment by Fabian-G** [comment]
@benhaynes May I ask what the reason is to explicitly exclude the primary key from first 5 columns for the default table view? Wouldn't you get the exact same behavior if you would instead display the "first five columns without hidden on browse set", since if you create a collection via the directus/app "hidden on browse" is set for PKs by default anyway. Also this would enable people to use non surrogate primary keys, which are displayed by default.

If I do understand "hidden on browse" correctly this option has no effect on PKs in the current implementation, correct?

**Comment by benhaynes** [comment]
I agree, and very good point! Here's how I think this should be updated to solve what you're describing:

We do not set the PK to be "hidden on browse", but when setting the initial tabular fields to be shown, we skip the PK and show the next 5 fields. That way users can easily turn on the PK in the sidebar, but it's not shown by default on initial tabular views.

Yeehaw?

**Comment by Fabian-G** [comment]
Maybe the other way around? Stay with enabling "hidden on browse" for PKs by default and remove the special treatment for PKs in the tabular views (therefore show the first five *not*-hidden on browse columns). 

Maybe my use case for clarification: I have a simple 2 columns key/value collection (one row per key/value-pair not the directus data type), created directly through the API. Naturally the key is the PK of the collection. Currently, if a user would view this collection inside directus/app he would see just the list of values without the associated keys until he activates the key column in he sidebar, which might be confusing to the user. We worked around this by adding an additional surrogate primary key and setting the key "unique", but thats not a good solution imho.

**Comment by benhaynes** [comment]
I'm not sure I understand what you're proposing. "Hidden on Browse" is meant to not display that field on the browse page at all — not in the layout, and not as an option to be turned on from the sidebar either.

If you want to set project-wide defaults for all user's layouts (eg: which fields they see, the order, sort, etc) you can use Global Collection Presets for that.

**Comment by Fabian-G** [comment]
Thanks. I believe Collection Presets is what I was looking for. I thought those were always on a per user basis.
Anyway, I try to describe my suggestion a little better: 
Currently if I create a new collection the primary key has "hidden on browse" enabled and is (of course) therefore not shown in the browse view.
As a user I would expect that if go to the collection settings and turn "hidden on browse" off for the primary key and did not create any collection presets beforehand, that the primary key will be included in the default browse view. But its not, due to the "first five columns after primary key"-policy that rijkvanzanten mentioned.
My suggestion is to replace this policy with just "first five columns". This way, if a user creates a collection the "hidden on browse" for the primary key ist still enabled and therefore the primary key is not shown, in the browse view. On the other hand if the PK should be displayed by default you can go to the collection settings and disable "hidden on browse" for the PK. Afterwards the PK will be shown by default in the overview without any additional enabling required.

Note that since I believe that I can do what I wanted to achieve with the global collection presets you mentioned this becomes a very minor issue. This is just about user expectation.

**Comment by benhaynes** [comment]
OK, glad you have a work around. We'll consider what you've mentioned, but the primary goal of the Directus App is to provide a non-technical interface for users — and the PKs usually aren't a good default for them. And it only takes a moment for more technical users to add it into the list.

As I said, we WILL remove the "hidden on browse" for the PK though... it should be easier to select in the normal browse process.

Thanks!
