### ISSUE TITLE
Block system when API connection goes offline

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#275]
I believe there is a window event for connectivity changes. Seeing the files of the app get cached in a serviceworker, we need to take into account what happens when the user is offline and tries to log in.

**Comment by rijkvanzanten** [comment]
We could probably use `v-offline`:

https://alligator.io/vuejs/vue-detect-online-offline/

Seems like the most elegant way to render a blocking modal with a connectivity issue message

**Comment by benhaynes** [comment]
Do we actually want to do this since many developers might be working on Directus offline (locally)? Technically there are no external dependencies if the database/storage is all on the local machine.

@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Keep in mind that `locally` !== `offline`

Think of it like "Block the system when the connection _with the API_ is broken"

**Comment by benhaynes** [comment]
Ahh, API connection... yeah, that definitely needs to happen

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
