### ISSUE TITLE
DAM & Files: Add to cart button & cart management

### ISSUE THREAD

**Issue by arsene-glanum** [directus/app#2752]
Hello,

# Files: "Add to cart" button

It would be great to have an "Add to cart" button next to the Edit, Delete and Create buttons on the top right corner.

**Comment by benhaynes** [comment]
You'll have to add some context here... Directus isn't an e-com platform, so I don't know what you mean by "Add to Cart". I'll close this until it's clear what you're looking for.

**Comment by arsene-glanum** [comment]
Thanks for your quick replies!

The "cart" is the kind of "basket" feature documented here: https://university.mediabeacon.com/Documentation/MediaBeacon_Legacy_Doumentation/Widget_Manual_8.6/Action_Widgets/Carts

It does not need to be so complete at first. However we'd love to save, name & share different carts.

It's being rebranded "cart" even outside the e-com context for being a similar feature and conceived similarly by the average user. It can be more accurate about the feature _in a way_ since for example "Basket" can share its meaning with "Trash".

You can checkout free items. But I agree that it could be misleading though.

What do you think about that?

Regards

**Comment by arsene-glanum** [comment]
> Am I right in understanding that this is similar to marking something as "favorite"?

I can't find the "Favorite" feature you are talking about within the demo if it ever exists.

This _could be_ a kind of favorite. But the idea is that the referenced collection of item within the "Favorites" or the "Cart" be "batch-enabled" for actions such as editing (basically), sharing (access), or downloading (assets cf.: #2753 ).

I think it's closer to a Cart but Favorite seems to suit better a "directus-wide" feature. E.g. available on other modules than the file/DAM module. That would make the feature less specific, more usable / desirable.

Is that what you had in mind?

**Comment by benhaynes** [comment]
Not sure about this. We already have multi-select items and batch edit, and will be adding a new export feature soon. I think that takes care of what you're requesting. We could also add a "favorite" feature... but that's TBD.

**Comment by rijkvanzanten** [comment]
Yeah it sounds like selection for batch already tackles that use case mostly

**Comment by arsene-glanum** [comment]
Thanks for caring! May you change your labels?

**Comment by benhaynes** [comment]
It's open-source, so you can override whatever you want.

**Comment by rijkvanzanten** [comment]
@benhaynes I think they mean the labels on this issue? 🙂
