### ISSUE TITLE
DAM & Files: Download button & archive management

### ISSUE THREAD

**Issue by arsene-glanum** [directus/app#2753]
Hello,

# Files: "Download" button

It would be great to have an "Download" button next to the Edit, Delete and Create buttons on the top right corner.

With the batch feature it would allow to create a compressed archive of the given files.

_May be linked with #2359 which I didn't find at a first glance._

**Comment by benhaynes** [comment]
I like it... I think we could add `Download` action button to File Browse when 1+ items are selected. Also add a "Download" and "Preview" (open in lightbox or new tab?) button to the File Detail page header.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
