### ISSUE TITLE
DAM & Files: search & search filters as a faceted search enhancement

### ISSUE THREAD

**Issue by arsene-glanum** [directus/app#2754]
Hello,

# Files: Display search & search filters in the right column/pane

This is a GUI enhancement suggestion. It would be great that the search & search filters be in the right column, above or under the Info pane/tab.  It would work the way "Info > Sort" works

Having he ability to have all the filters deployed by default or to configure which to choose from being deployed from the Admin settings would be nice too.

Ideally, a the top of the right column, pane, you would have:

* Layout: which is the "View as" feature extracted from Info
* Filter: which is the search & search filters moved to there (this feature request)
* Sort: which is the Info tab/pane renamed, without the "View as" feature (extracted above)

Tab titles would have a "badge" indicating the number of active settings (number of filters for examples), and/or filters/active settings would appear as tags in a header of the list view.

Regards

**Comment by benhaynes** [comment]
Thanks! This is actually already in-place within v9 (coming soon). I'll close this, and you can monitor the App-Next repo for updates on exact release timing.

![Screen Shot 2020-04-22 at 9 06 51 AM](https://user-images.githubusercontent.com/522079/79985469-a658c980-8478-11ea-8d1a-372ec426e11b.png)

**Comment by arsene-glanum** [comment]
Fantastic! May you add this to the roadmap? I know, it's lot of work to keep a site up-to-date anyways.
