### ISSUE TITLE
Is it possible to change the column order of the collection Browse view after creation? 

### ISSUE THREAD

**Issue by tke849** [directus/app#2757]
So upon creating a collection the table view is set based on the order of the initial creation. If I add a new value to that collection, that I want to be the first in the Browse columns, changing its order in the Detail view does not change the order in the Browse view. (I am using a cloud hosted instance)

**Comment by rijkvanzanten** [comment]
You can change the visible fields and order in which they're displayed by clicking on the `(i)` icon in the top rigth
