### ISSUE TITLE
Pre-defined tokens

### ISSUE THREAD

**Issue by fairbairn** [directus/app#2760]
We'd like to leverage your system in a stateless manner from our server-side implementation.  Our direct clients will talk to our server and we'll talk to your API.

In leveraging other platforms like Stripe, Shopify, and Contentful, it's customary to be able to use a pre-defined "access_token" or key, that's tied to the "API account" (or role).

Using that then allows API calls to remain stateless, yet secure.

Currently your model is to perform an auth (based on user credentials), to retrieve a jwt, and then provide that for future calls but it expires, which requires us to maintain that awareness and refresh the token.

This setup is non-ideal for typical stateless API interfaces using token-based security.

Could you implement something of this nature, where under Settings, there's a section for API Keys, and keys are created there, and then leveraged as the Authorization: bearer (token) over https.  That would allow the system to remain stateless and not concern ourselves with specific auth cases and token refresh semantics.

**Comment by rijkvanzanten** [comment]
This already exists:

https://docs.directus.io/api/authentication.html#static-token

**Comment by fairbairn** [comment]
I appreciate you clearing up that it's possible.

It still doesn't address the UX component.  We'd like to be able to manage them from the dashboard, per user - not going to direct to tables in the database.

**Comment by benhaynes** [comment]
Version 9 (coming in 4-6 weeks) will have a way to edit the token within the App. It was kept out previously out of an abundance of caution/security.
