### ISSUE TITLE
[question] User role hierarchy

### ISSUE THREAD

**Issue by erkage** [directus/app#2765]
Is there a way to achive the following User role operation in a collection:
User - Sees own items only
Manager - Sees assigned Users' items and own items
Admin - sees every item

Thanks in advance!

**Comment by benhaynes** [comment]
* User — Yes, you just set the permission to `mine`
* Manager — You can use the `role` permission, but that restricts to the manager role (not the user role)
* Admin — Yes, the admin role already sees all items

The new "dynamic permissions" we're working on will solve the manager use-case and more. But there's no ETA on that yet.

**Comment by erkage** [comment]
So if i have the following settings:
Users:
- User 1 ( id:1 )
- Manager 1 ( id:2 )

Roles:
- Users (id: 1) (User 1 is here) 
- Managers (id: 2) (Manager 1 is here)

Collection item:
created_by: 2
owned: 1

Permissmion:
User 1: mine
Manager 1: role

Then "Manager 1" and "User 1" are both can view that collection item?

**Comment by benhaynes** [comment]
Hmm, no, because both of those permissions use the same `owner` field. `created_by` is not used by permissions AFAIK

**Comment by erkage** [comment]
Than i think i don't understand the Role permission ("role - Can only view items created by members of this role") 🙂 . 
It's the user-role interface? So all members of the role can see all items which is set to that role id?

**Comment by benhaynes** [comment]
For "role", members can see any items created by members of that role... so the field still stores an owner id/key.
