### ISSUE TITLE
Minimal auto sign out value

### ISSUE THREAD

**Issue by Mario-Amos** [directus/app#2775]
Hey there,
I tried to set auto sign out value on 120, then I tried to access to any other page. It disconnected me and when I try to login, I have the following error in the console:

Directus version : 8.6.2
PHP Version       : 7.4
No more information cause it's hosted by Infomaniak

```
xhr.js:172 POST https://xxx.xx/project/auth/authenticate 404

xhr.js:172 GET https://xxx.xx/project/interfaces 401
hydrate.js:56 Error: User not authenticated
    at new t (API.js:39)
    at API.js:253
    at async Promise.all (/admin/index 0)
    at async Promise.all (/admin/index 1)

xhr.js:172 GET https://xxx.xx/modules 401
xhr.js:172 GET https://xxx.xx/xxx/collections 401
xhr.js:172 GET https://xxx.xx/xxx/settings 401
xhr.js:172 GET https://xxx.xx/layouts 401
xhr.js:172 GET https://xxx.xx/xxx/users/me?fields=*.* 401

xhr.js:172 GET https://xxx.xx/xxx/users?fields[0]=id&fields[1]=first_name&fields[2]=last_name&fields[3]=title&fields[4]=status&fields[5]=timezone&fields[6]=role.*&fields[7]=avatar.*&fields[8]=company 401

xhr.js:172 GET https://xxx.xx/xxx/relations?limit=-1 401

xhr.js:172 GET https://xxx.xx/xxx/users/me?fields[0]=id&fields[1]=avatar.*&fields[2]=email&fields[3]=first_name&fields[4]=last_name&fields[5]=locale&fields[6]=role.*&fields[7]=last_page&fields[8]=theme 401

hydrate.js:56 Error: Unauthorized request
    at new t (API.js:39)
    at API.js:253
    at async Promise.all (/admin/index 1)
```

It's not really a problem for me but I don't know if it's a bug so I just wanna report it ^^

Thanks!

**Comment by rijkvanzanten** [comment]
The `/auth/authenticate 404` indicates to me that the initial login didn't go through at all 🤔 

Auto sign out is in minutes, so 120 shouldn't mess with logging into the app

**Comment by Mario-Amos** [comment]
Actually I think it's for values below 121 (not included). It makes the login impossible to login. I tried on local and on a hosted server.

**Comment by rijkvanzanten** [comment]
I believe this might be related to https://github.com/directus/api/issues/1882

@Mario-Amos Could you check the timezone configuration on your server and report your findings on that issue? 

I'll close this in favor of that one on the api, as they seem to be the same problem

**Comment by Mario-Amos** [comment]
Oh yes sorry for that late answer,
Actually, it was strange because on  the 01 May, the problem solved himself. My server configuration was on the right timezone, couldn't say why it happened and how it got fixed.

**Comment by rijkvanzanten** [comment]
woa that's strange!
