### ISSUE TITLE
Table 'directus.directus_settings' doesn't exist

### ISSUE THREAD

**Issue by Monte47** [directus/app#2782]
I am currently running a deployment of the latest version of directus using kubernetes/docker. When I go to the index / sign in page I get "Something is wrong with this project":

> Statement could not be executed (42S02 - 1146 - Table 'directus.directus_settings' doesn't exist)

I can't find anything in the documentation about a directus_settings table or any mandatory tables for that matter so I don't know what should be in there.

![image](https://user-images.githubusercontent.com/21068946/80992744-d431fc80-8dee-11ea-8e96-1a933dbfcc13.png)

**Comment by rijkvanzanten** [comment]
See https://github.com/directus/directus/discussions/2695
