### ISSUE TITLE
Create DigitalOcean droplet from a snapshot - "Failed to connect to Database" 

### ISSUE THREAD

**Issue by willcommit** [directus/app#2801]
I have a DigitalOcean droplet with an attached storage volume. Directus 8.6.1 on Ubuntu 18.04.

After creating a new Droplet from a snapshot image of the old Droplet. The droplet works as long as the old droplet is powered off, but when the old droplet is powered on the connection to the database is lost in the new droplet. Also tested the API with same result.

Following error in the logs:
api[furuno_cms].ERROR: Directus\Database\Exception\ConnectionFailedException: Failed to connect to the database in /var/directus/src/core/Directus/Application/CoreServicesProvider.php:723

And in the app:

![image](https://user-images.githubusercontent.com/44772545/81908412-7e690b80-95c9-11ea-9f1b-705a573c0759.png)

When logging in to the new droplet, all tables are there in the Directus DB. 

Makes me think the new droplet is somehow connected to the old droplets database...

I have tried creating the droplet with and without attached storage from start. As well as attaching a copy of old storage volume to the new droplet. Same error.

**Comment by rijkvanzanten** [comment]
Can you confirm the db server is actually running after this restart? Can you confirm it's trying to access the correct database by checking the config file?

**Comment by willcommit** [comment]
> Can you confirm the db server is actually running after this restart? Can you confirm it's trying to access the correct database by checking the config file?

The Droplet was created from DigitalOceans 1 click app. The db is on the same server as the app. I have restarted Apache several times. If that was what you meant?

I have checked the config file in /var/directus/config. They are identical, which they should be - it's a snapshot image...

![Screenshot from 2020-05-14 20-52-48](https://user-images.githubusercontent.com/44772545/81974138-6cb55180-9625-11ea-8a90-caa4cffa409f.png)

**Comment by willcommit** [comment]
I have migrated the db to a new DigitalOcean LAMP-stack droplet with a Git installed Directus suite. When making snapshot images and subsequent droplets from these images, it works perfectly! 

This makes me believe that the issue is related to the attached storage volume. I can't recommend anyone to create a DigitalOcean 1 click app atm, especially with an attached storage on creation.

**Comment by rijkvanzanten** [comment]
The DO one click is literally the same as what you setup now manually (LAMP + Directus through git), so it must be addition of the attached storage volume that's causing issues with snapshots. Closing this as it doesn't seem like something we can fix in Directus itself.
