### ISSUE TITLE
User theme switch doesn't work

### ISSUE THREAD

**Issue by lucaswerner90** [directus/app#2815]
It's not possible to switch between light and dark scheme color using the latest Docker image:

• Version of Directus: `directus/directus:v8-apache` .
• Using `docker-compose.yml` from simple example in the Docker repo.
• No error messages

Steps to reproduce:

1. Access as the default Admin user.
2. Go to your User Settings.
3. Switch the value of the "Theme" selector to "Light" (the default is "Dark")
4. Save the changes.
5. No difference in the UI.

No errors in the UI when saving. The network tab send the correct payload. I've also tried to logout and login again but still nothing.

I suspect something may be wrong in the frontend app.

🐰

**Comment by benhaynes** [comment]
Just tested on the demo and it works as expected. I can't imagine this is a Docker specific issue either... are you on the latest version of 8.7?

https://demo.directus.io/admin/

**Comment by lucaswerner90** [comment]
I am using `directus/directus:v8-apache` image. I can reproduce it constantly till I hard-refresh the browser. I don't think it's a priority anyway.

**Comment by kenston** [comment]
Using fresh install of 8.8.1, I can confirm the same observation above. Changing user theme and logging out and logging in produces no result until I force refresh the browser.
