### ISSUE TITLE
Modified On field no longer displays data

### ISSUE THREAD

**Issue by lriggle-strib** [directus/app#2818]
## Description
Ever since the release of 8.7.1 on the cloud platform, the Modified On field no longer displays when displayed on the browse pages.

Here is a screenshot of the issue as I'm seeing it:

<img width="1294" alt="Screen Shot 2020-05-20 at 1 12 07 PM" src="https://user-images.githubusercontent.com/7051012/82481878-a067ff80-9a9b-11ea-86c4-955e1e3f1564.png">

This may be related to an issue I opened last week, https://github.com/directus/api/issues/1888

**Comment by bereikme** [comment]
![modified](https://user-images.githubusercontent.com/65550009/82486016-8ef31780-9adc-11ea-9672-b8af0d0f7c95.png)
I can confirm having the same issue.

**Comment by rijkvanzanten** [comment]
There's a format mismatch between what the API returns and the app expects:

https://github.com/directus/app/blob/f35b7a7a7b6142e261282d264d4c47d27e01d6d6/src/interfaces/datetime-created/display.vue#L27
