### ISSUE TITLE
API doesn't respond

### ISSUE THREAD

**Issue by clementvtrd** [directus/app#2822]
• **Version of Directus**: latest (just clone from GitHub repo)
• **Server, OS & Database Details**:
    - Host : ni-host.com
    - Apache: v2.4.43
    - PHP: v7.2.30
    - SQL: MariaDB v10.2.31
    - OS: linux x86_64 (no more information)
• **Error message** in console logs: `TypeError: m.data.error is undefined`
• **Steps to Reproduce**: the only steps I did is to clone the repository as indicated in docs and push it to the server via SFTP.

When I go the URI for the first time, I'm just getting the loading circle indefinitely (wait about ~ 10 minutes before leave).. And as said above the only logs I get (JS and PHP combined) is the message in the Firefox's console (none in `directus/logs`.

I'm sure the Rewrite mod is enable with Apache 'cause another website just work fine with this feature required.

If you have any idea of what happened, please considered to help me...

**Comment by rijkvanzanten** [comment]
@ClementVtrd Could you verify what happens when you go the endpoint(s) of the API directly? Does `/server/ping` work for example? It sounds to me like the app is trying to read an error the API returns, while the API doesn't actually return anything

**Comment by ClementVtrd** [comment]
@rijkvanzanten i've already tried to reach this endpoint, and it return nothing...

**Comment by rijkvanzanten** [comment]
That indicates to me that mod_rewrite isn't setup / working correctly..

It sounds like the app is attempting to reach the API, which doesn't respond at the expected path

**Comment by ClementVtrd** [comment]
I'll check this by my own. 

Usually I do not have to do it myself, but I have to add a .htaccess file. Do you know where I need to put it? 

Thanks for your advise, best regards
