### ISSUE TITLE
Not possible to add a collection

### ISSUE THREAD

**Issue by tomexx** [directus/app#2826]
Hello,

I'm not able to add a collection after a fresh installation of the latest version (v8.7.1). There is no button for adding a collection. Or am I missing something important?

Thank you

**Comment by rijkvanzanten** [comment]
Heya! Under Settings (the ⚙️ in the left dark bar) > Collections and Fields there's a plus (➕) in the top right 🙂 

This is on the live demo right now:

![CleanShot 2020-05-26 at 15 25 43](https://user-images.githubusercontent.com/9141017/82941938-3a7ceb80-9f65-11ea-9461-aab5d7bfc75c.png)
