### ISSUE TITLE
Repeater Field Child Fields Name not sanitized on save

### ISSUE THREAD

**Issue by altezza04** [directus/app#2828]
Repeater Field Child Fields Name not Auto sanitized on save

<img width="651" alt="Screenshot 2020-05-27 at 5 43 36 PM" src="https://user-images.githubusercontent.com/59946405/83004427-4094ca00-a042-11ea-9698-2f263b9f9772.png">

API Ouptut
<img width="464" alt="Screenshot 2020-05-27 at 5 46 35 PM" src="https://user-images.githubusercontent.com/59946405/83004438-42f72400-a042-11ea-9b5e-eb1e09b36f35.png">

• Version of Directus (must be the latest)
8.7.1
• Steps to Reproduce
Create a new Repeater Field and new Fields with name in space and capital letter and in the API output with not sanitized

**Comment by rijkvanzanten** [comment]
This is expected behavior, as it just saves those straight to JSON

While it looks a little strange, 

```json
{
  "Section Title": "TEst"
}
```

is technically valid JSON
