### ISSUE TITLE
Clone data from one directus installation to another

### ISSUE THREAD

**Issue by siauderman** [directus/app#2829]
There should be an easy way to migrate all data and files from one directus installation to another, a 1-click solution preferably.

**Comment by benhaynes** [comment]
Duplicate of: https://github.com/directus/api/issues/31

Requires the API endpoints...

**Comment by rijkvanzanten** [comment]
@siauderman Copying the whole installation + a dump of the DB is all it takes to make a full identical copy

**Comment by Bloc67** [comment]
> @siauderman Copying the whole installation + a dump of the DB is all it takes to make a full identical copy

Does that mean all installation files, even configurations for database etc?

**Comment by rijkvanzanten** [comment]
The database schema information is stored in the database as well @Bloc67 :)
