### ISSUE TITLE
Add unique identifier to edit form fields

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#283]
There can be multiple edit-forms on the same edit view (for example: adding a many-to-one item from within the edit view or watching the rollback preview). All the labels and fields now use an ID based on just the field-name. This adds an interesting (HTML) bug:

If you have inputs
```html
<!-- field.name === 'category' -->

<label for="category">...</label>
<input id="category" />

<v-modal>
  <label for="category">...</label>
  <input id="category" />
</v-modal>
```

Clicking on the label _in the modal_ actually focusses the _first input on the page_.

Just one of those small things, ammiright 🤦‍♂️

**Comment by benhaynes** [comment]
Excellent – and of course! A lot of things are up in the air right now, so please let us know if you run into any issues!

### API Dev Setup
https://docs.directus.io/api/contributor-guide/install-dev.html

### App Dev Setup
https://docs.directus.io/app/contributor-guide/install-dev.html

**Comment by James-N-M** [comment]
Very cool thanks @benhaynes !

**Comment by James-N-M** [comment]
I cant get API to install but ... im gonna try the app still and give that a go with the online demo

**Comment by benhaynes** [comment]
We're working on finishing up the schema changes and improving the Docs. If you had specific issues let us know and we'll make sure they get fixed.

**Comment by James-N-M** [comment]
@benhaynes I'll try again tonight but, I believe my issue had to do with the config file, There maybe should be a step that tells a first timer to make sure there mysql user/pw stuff matches the config file as well as the name of the config file in the docs matching the one in the repo.

**Comment by benhaynes** [comment]
I agree... our Docs are open-source too if you have any recommendations there!

https://docs.directus.io/api/admin-guide/configure-manually.html

**Comment by srjrol** [comment]
Here is a possible solution for modal within modal using vue js.  https://vuejsexamples.com/vue-modals-with-a-single-component/
