### ISSUE TITLE
Modal selector for relation items crashes with uncaught exception

### ISSUE THREAD

**Issue by jroxendal** [directus/app#2830]
To reproduce:
1. Start Directus using Docker (examples/simple). 
2. Create a collection. 
[place.json.zip](https://github.com/directus/api/files/4688405/place.json.zip)
3. Add more than 20 items to collection. 
4. Add some other collection with an M2O field pointing to place.id (with null values works fine).
5. Hit + in new collection and try to set relation. The modal pops up, crashing with a:
```
TypeError: Cannot read property 'length' of null
    at a.Aa (item-select.vue?057b:6)
    at vue-composition-api.module.js:604
    ...
```

Dropdown works fine, though, before adding too many items beyond the threshold.

**Comment by jroxendal** [comment]
Just some thoughts on this bug:

https://github.com/directus/app/blob/f35b7a7a7b6142e261282d264d4c47d27e01d6d6/src/components/item-select/item-select.vue#L52

if i comment out this icon from the item-select component, the bug goes away. the `value` property is null for me, and so it crashes on `value.length`. Not sure if it's allowed to be null or if some logic in the input component is the culprit:
https://github.com/directus/app/blob/f35b7a7a7b6142e261282d264d4c47d27e01d6d6/src/interfaces/many-to-one/input.vue#L42

**Comment by rijkvanzanten** [comment]
@jroxendal Thanks for the detailed report 🙂 

The `value` prop defaults to `null`, so it's safe to say we should expect it to be `null` sometimes.

**Comment by rijkvanzanten** [comment]
@arboehme guess we missed a case when merging in https://github.com/directus/app/pull/2777 👀

**Comment by jroxendal** [comment]
Thanks for the quick response, and keep up the good work!
