### ISSUE TITLE
Incorrect datetime value for column 'created_on' when editing translations inline

### ISSUE THREAD

**Issue by darioseidl** [directus/app#2834]
We've updated Directus with Docker from v8.6.2 to v8.7.1 to get the fix for this bug https://github.com/directus/app/issues/2589 (it's fixed now, thanks!)

However, now, when editing a translation for a collection item "inline", I'm getting 

```Failed generating the SQL query. Statement could not be executed (22007 - 1292 - Incorrect datetime value: '2020-05-12T15:01:53+00:00' for column 'created_on' at row 1)```

Our translation tables have the default audit fields, `owner`, `modified_by`, `created_on`, and `modified_on`.

```
| company_translations | CREATE TABLE `company_translations` (
  `id` int(15) unsigned NOT NULL AUTO_INCREMENT,
  `owner` int(10) unsigned DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `modified_by` int(10) unsigned DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `company` int(10) unsigned NOT NULL,
  `language` varchar(10) NOT NULL,
  `content` text,
  `title` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 |
```

It's only a problem with the `created_on` field (`modified_on` doesn't have the same problem apparently). When I delete the `created_on` field from the translation table, editing works again.

It seems to me the datetime value that is to be updated in the query is in ISO8601 format (with timezone offset) instead of the correct MySQL datetime format. Also, I think, the `created_on` would not need to be updated at all?

We don't really need the audit fields on the translations, so this isn't urgent for us, but it would be nice to have the audit fields on all tables for consistency and traceability.

**Comment by rijkvanzanten** [comment]
I _think_ it's because the translations interface might stage the entire item when updating a value instead of just the changed records. That combined with the fact that the API doesn't expect it's own output currently explains why this would occur

**Comment by jroxendal** [comment]
I got around this by deleting created_on prior to staging here:
https://github.com/directus/app/blob/fdad9c9b210d47b9ea10de2372a14efc50de8fd1/src/routes/item.vue#L596

It's not exactly bullet proof but it should keep me afloat until the root cause has been fixed. 

Just replace stageValue() with this:
```
stageValue({ field, value }) {
	for (let val of value) {
		if (val.created_on) {
			delete val.created_on;
		}
	}
	this.$store.dispatch('stageValue', { field, value });
},
```

**Comment by ni-binada** [comment]
This seems to still be an issue in 8.8.1. When updating an item belonging to a collection with translations, I get the following error message:
```
PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2020-10-27T11:11:11+00:00' for column 'created_on' at row 1 in /var/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
```
Was this fix somehow reversed recently?
