### ISSUE TITLE
Many-to-one relation interface broken when creating new item

### ISSUE THREAD

**Issue by mathielen** [directus/app#2840]
**Version:** 8.7.2 (also found at demo which is at 8.7.0)
**Error Messages:** TypeError: Cannot read property 'length' of null

The bug is reproducible on your current demo (which seems to be on 8.7.0) as following:

0. login at https://demo.directus.io/admin/#/
1. goto "Customers" collection
2. create new
3. click on dropdown-field "owner"
4. popup shows loading circle forever
4b. js error shows up in console: TypeError: Cannot read property 'length' of null

Thank you

**Comment by rijkvanzanten** [comment]
Are you sure you're on 8.7.2 and not 8.7.1? I'm pretty sure https://github.com/directus/app/pull/2837 was the fix for that

**Comment by mathielen** [comment]
You might be right. I updated to 8.7.2 just after I saw the bug and maybe I didnt clear the cache.
Seems to work now.

Thanks
