### ISSUE TITLE
Couldn't reach API error after upgrading

### ISSUE THREAD

**Issue by siauderman** [directus/app#2845]
After upgrading with a git pull, I am now unable to login to directus and am getting a "Couldn't reach API" error. However, logging the HTTP calls shows that the status codes are all 200 OK.

![bildo](https://user-images.githubusercontent.com/14951259/83283509-e9dbeb80-a20d-11ea-9fe7-994a98837f77.png)

**Comment by siauderman** [comment]
In fact I just tried doing a clean install and I'm still getting the "Couldn't Reach API" error and am unable to login. This is quite scary because if I am to use this in production I can't afford to have such things happen to me.

**Comment by rijkvanzanten** [comment]
How are you running it locally? Browsers started updating their cookie policies regarding same site origins and HTTPS requirements. We recently added SameSite=None + Secure to the cookies used for authentication to make sure browsers won't stop supporting cookie authentication with the Directus API, but that might affect your localhost setup

**Comment by siauderman** [comment]
Sorry for the trouble! Indeed it was https. I do hope that you can put up a warning in the documentation that https is now required.
