### ISSUE TITLE
Error assigning M2M relationship

### ISSUE THREAD

**Issue by Youca** [directus/app#2850]
**Steps to reproduce**
1. Create a new M2M field
2. Auto-Generate Junction Collection
2. Assign Item by selecting existing Item
3. Save

**Expected Behavior**
Should save the item.

**Actual Behavior**
Item can't be saved.

**Version of Directus**
8.7.1

**Error Messages**
![error_m2m](https://user-images.githubusercontent.com/9433548/83384421-87d6de00-a3e7-11ea-80a5-0306cd1decad.jpg)

**Comment by benhaynes** [comment]
Can you post a screenshot of your relationship setup?

**Comment by Youca** [comment]
<img width="658" alt="Bildschirmfoto 2020-06-02 um 09 43 42" src="https://user-images.githubusercontent.com/9433548/83493829-a9060000-a4b5-11ea-9722-c72cce766513.png">
<img width="691" alt="Bildschirmfoto 2020-06-02 um 09 40 54" src="https://user-images.githubusercontent.com/9433548/83493835-ac00f080-a4b5-11ea-8512-c031c21ca4c6.png">

**Comment by benhaynes** [comment]
Did you create part of this schema directly int he database? It looks like those fields are not yet managed, which is likely your issue. Click "Manage" on all collections/fields that you want to be included in Directus.
