### ISSUE TITLE
Empty tags

### ISSUE THREAD

**Issue by tomexx** [directus/app#2853]
Hi,

I'd like to report a wrong behaviour when trying to add tags to an item.

- In the UI, the tags seems OK
![image](https://user-images.githubusercontent.com/2822756/83430462-02c6e580-a436-11ea-982e-907f603dc667.png)

- In DB, there are leading and trailing colons
![image](https://user-images.githubusercontent.com/2822756/83430506-140ff200-a436-11ea-8395-e0ac57c9fec2.png)

- In REST API response, there empty items
![image](https://user-images.githubusercontent.com/2822756/83430562-29851c00-a436-11ea-807c-9b9fd209fcfb.png)

**Comment by rijkvanzanten** [comment]
Do you have the _Wrap with Delimiter_ option turned on?

**Comment by tomexx** [comment]
Yes, it was turned on, what is the purpose of that?

**Comment by rijkvanzanten** [comment]
To wrap the tags in an extra delimiter (eg `,`) 😁 

It allows you to do an exact search in SQL with `%LIKE%` by searching for `,<term>,` instead of just `<term>`.
