### ISSUE TITLE
File/files interfaces not working as expected

### ISSUE THREAD

**Issue by umiodrag** [directus/app#2911]
# Bug report
Cannot upload new files using file/files interfaces

## Steps to reproduce
1. add file/files interface to collection
2. set file as required  **(optional)**
3. create new collection's item
4. try to upload file using those interfaces
5. try to save the item
6. try to manually choose file(s) in both cases
7. and save again **(optional)**

## Expected behavior
Upload/choose file using file/files interface and save the item

## Actual behavior
1. When trying to upload new file (both **"embed"** and **"select form device"**), with file/files interfaces, those cannot be chosen as part of collection's item, but existing (already uploaded) files can. The desired file is actually uploaded in the background, but it is not selected (and metadata isn't shown). After problematic upload the same item can be selected from file library and the problem with metadata is no more.

2. When trying to save collection's item got those **error messages**: 
 `fajl: This value should not be blank.`   _(in this case file item is required)_
 `filename_disk: This value should not be blank. uploaded on: This value should not be blank. filename_download: This value should not be blank.`
 and those are fired in console, too. Item can be saved after selecting files from library, but for files interface error is fired in console again.

- **Remark:** _tried both windows and linux machines_

## Screenshots
Selecting the file:
- **file interface** _(without errors in console)_
![image](https://user-images.githubusercontent.com/47249114/87153541-f2691c80-c2b7-11ea-9f8e-731d58353552.png)

- **files interface**
_upload:_
 ![image](https://user-images.githubusercontent.com/47249114/87150198-e8dcb600-c2b1-11ea-99bb-718aa733e89d.png) 
_select:_ 
![image](https://user-images.githubusercontent.com/47249114/87150115-c64a9d00-c2b1-11ea-8ea0-2a74f8b9a328.png) 
_result:_ **(the same file!)**
![image](https://user-images.githubusercontent.com/47249114/87151677-93ee6f00-c2b4-11ea-9c78-75c25555c52a.png) 

## Other notices
- Maybe this issue has something to do with #2308
- The similar metadata issue found there [#1869](https://github.com/directus/api/issues/1869)
- This wasn't issue in previous Directus version 8.7.x but that version has had problems with custom user roles, so that was the main reason to change to the newest.

## Technical details
- **Directus version 8.8.0**
- **Comercial SSD linux servers** (different providers)
- **MySQL db**
- **PHP 7.3**
- **Installed with manually uploaded zip file.**

**Comment by lemankk** [comment]
I got similar case to this one. When an image uploaded, it doesnt change to preview screen and cannot submit.

<img width="959" alt="Screenshot 2020-07-19 at 10 03 30 AM" src="https://user-images.githubusercontent.com/519692/87865384-430f0280-c9a7-11ea-817e-c47eb4fca30a.png">

**Comment by umiodrag** [comment]
@rijkvanzanten - so if I've understood well this one should be fixed now? :)

**Comment by lemankk** [comment]
Should be fixed. "undefined" was reported when try to access data.id and/or data.type in response payload. It was pointed into response.data.data that just contain "url", "width", "height"

**Comment by umiodrag** [comment]
Thanks @lemankk ! Will test it soon.

**Comment by umiodrag** [comment]
@lemankk - it's working well now 👍 (sorry but forgot to comment earlier)

**Comment by arboehme** [comment]
@lemankk  Sorry, but the fix #2919 makes the issue #2308 open again. This issue was fixed by @rijkvanzanten in  https://github.com/directus/app/pull/2334/commits/3b4d4aafebee436332e4352c6e2aa6b0b4703c86. 

Can you please check it and adjust your fix? Thank you!
