### ISSUE TITLE
field display name

### ISSUE THREAD

**Issue by rbarszcz** [directus/app#2913]
would be nice to have a way to setup the label of the field that will be displayed in the UI.. today the only option is the 'formatted' column name:
  'defined label' or 'default column name' 
  [ input item ]

another UI request: in the 'add item' form of a collection, the left icon in the inputs are all gray (same color as the border, dark theme) but the dropdown.. wich is white..

**Comment by rijkvanzanten** [comment]
@rbarszcz You can use translations in field options to setup any field name in any language for use in the app. 

Feel free to open a new issue for any ui issues you encounter
