### ISSUE TITLE
Translations not working after v.8.6.2

### ISSUE THREAD

**Issue by pzehle** [directus/app#2916]
In v8.6.2, you can create translations for content as described [here](https://docs.directus.io/guides/relationships.html#translations). All works just fine.

After upgrading Directus to any of the newer versions, translations in the same way stop working. You can add one element for the first Language, but after trying to add any other language, you get `Failed generating the SQL query`.

From the console I can see that the script is trying to `PATCH`, instead of `POST` to create a new element in the translations table.

Is there a new way to setup translations in the newer versions?

Thanks in advance.

**Comment by clemence-morillot** [comment]
I've just seen your issue, I encountered the same problem, and opened this issue : https://github.com/directus/app/issues/2921.

**Comment by rijkvanzanten** [comment]
While this is the original, I'll close this one as the duplicate, as #2921 is more detailed and includes a full reproduction 👍
