### ISSUE TITLE
/INSTALL - Why not create the databse

### ISSUE THREAD

**Issue by noelthoelen** [directus/app#2926]
A great feature of Directus is that it supports multi-tenancy. Adding a new project is as simple as browsing to #/INSTALL and entering the necesarry info for adding the project. The app takes care adding a new config and the new project shows up in the environment.

The only prerequisit at this moment is that you have created the database first. 

**Why this could be helpfull?**
If have a use case where we have a react app for a a specific project. However, we have several projects all using the same schema but the contents for every project is different.  Also, we do not want to mix content between the different projects.

**What is it we suggest to change?**
In the API (as also in he INSTALL wizard) add an option to create the database. If this can be done on the same server is OK. If this can be combined by starting from a predefined schema like described in this feature request [(861)](https://github.com/directus/app/issues/861) would be even better.

**Comment by benhaynes** [comment]
This whole flow will change a bit in Directus 9... we'll wait until that's out (a few days for beta, then a few weeks for prod) to discuss more. But I agree with this concept!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
