### ISSUE TITLE
Filtering on boolean field doesn't seem to work

### ISSUE THREAD

**Issue by ViktorSarkozi** [directus/app#2928]
Hi,

As I wrote in the title I tried to filter for my latest element in my collection by
`collection?filter[latest]=true` and it responses with an empty data.
After I switched this` 'switch' field` into `text-area` and typed in `'true' `it was starting to work.

Did I miss something or the filtering doesn't work on boolean field at all?

**Comment by rijkvanzanten** [comment]
Booleans are saved as `1` / `0` in MySQL. Try filtering by `1` or `0` respectively :)

**Comment by ViktorSarkozi** [comment]
> Booleans are saved as `1` / `0` in MySQL. Try filtering by `1` or `0` respectively :)

Awesome! Thank you very much. This one helped me out. This was not evident for me.

Besides this is not a bug anymore, still I would recommend to add an example for this case into documentation.
Would be really helpful.
