### ISSUE TITLE
Feature Request - Files field - add extra fields

### ISSUE THREAD

**Issue by moldedjelly** [directus/app#2949]
Would be great if it's possible to define extra fields for the items within a Files field. I'm looking to use Directus to develop a site for an art gallery, and the Files field looks promising to make it easy for the client to upload multiple images. It would be great after uploading several images, to then be able to go into each image and set some extra field data on each file like "year", "medium", "dimensions" etc. I've tried to add fields on the generated Junction table, but can't see how I can get those fields to show up in the File popup for each file. The only way I'm thinking I could get the extra fields to work is to create a collection for artworks, but means that the client would need to upload artworks individually.

**Comment by benhaynes** [comment]
This is something we have built into Directus 9, yes. The system collections will be extensible just like all others — but the existing system fields within are locked.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Also, in v9, fields added to the junction table will show up in the edit modal for the related item

**Comment by moldedjelly** [comment]
@benhaynes @rijkvanzanten awesome thanks, looking forward to v9! I'm really liking the system you've built. Very nicely done visually too.
