### ISSUE TITLE
Need WYSIWYG Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#296]
Simple (Medium) and Full (see link below) would be ideal. Let me know if there are other WYSIWYG libraries that might be better!

http://hifarer.github.io/vueditor/

**Comment by rijkvanzanten** [comment]
Directus 7 will be using [Quill](https://quilljs.com/) for the full WYSIWYG, and [medium-editor](https://github.com/yabwe/medium-editor) for the Medium-style editor

**Comment by rijkvanzanten** [comment]
These have been added in https://github.com/directus/extensions

**Comment by walcovanloon** [comment]
> These have been added in https://github.com/directus/extensions

This link seems stale? What would be the replacement?

**Comment by benhaynes** [comment]
We no longer have one repo for this, an example interface is here:

https://github.com/directus/example-interface-stock

Once extensions are "installable" we will likely move them all back into one repo.

**Comment by rijkvanzanten** [comment]
@walcovanloon The interfaces live here: https://github.com/directus/app/tree/master/src/interfaces

**Comment by walcovanloon** [comment]
Thanks @benhaynes and @rijkvanzanten for the fast and helpful response!
