### ISSUE TITLE
Split VModal into dedicated components

### ISSUE THREAD

**Issue by benhaynes** [directus/app#298]
To have proper modal options, we should split this ONE component into FOUR (or at least support options to have three designs):

* Alert
* Confirm
* Prompt
* Modal (or Dialog)

**Comment by rijkvanzanten** [comment]
Modals in use:
- [ ] Logout (confirm)
- [ ] Navigation with changes (confirm)
- [ ] Project switcher (modal)
- [ ] Batch delete (confirm)
