### ISSUE TITLE
Directus on a shared hosting

### ISSUE THREAD

**Issue by YamiteruXYZ** [directus/app#2985]
I've downloaded the latest Directus and put it on a shared hosting via ftp. When I want to access it I see a spinning wheel and it seems like project list cannot be loaded. Here is a testing url: https://admin.dilnasestak.cz/public.

I think there is something wrong with htaccess, but I'm not sure. It works on my local machine using MAMP PRO without a problem. The shared hosting meets all requirements stated in the docs.

**Comment by YamiteruXYZ** [comment]
So it looks like there were three problems.
1. Directus doesn't work on a shared hosting which uses NGINX only for SSL and Apache for everything else
2. We have to do composer install first and then copy files via FTP
3. We have to add .htaccess file to / and alter the one in /public

/.htaccess
```
RewriteEngine on
RewriteCond %{REQUEST_URI} !^/public
RewriteRule ^(.*)$ /public/$1 [NC,L]
```

/public/.htaccess
Add `RewriteBase /` under `RewriteEngine On`.

So after I changed a hosting provider, did composer install and added and edited .htaccess it works. 
BTW It took me 4 days to find this all out. Please update the docs.

**Comment by rijkvanzanten** [comment]
> BTW It took me 4 days to find this all out. Please update the docs.

Feel free to open a PR to the docs outlining this if you think it'll help others
