### ISSUE TITLE
Repeater field "File" interface missing

### ISSUE THREAD

**Issue by sarensabertooth** [directus/app#2989]
I had used a one-to-many interface to have content blocks of texts & images. Of course that creates a rather unappealing representation of the content in the editor. So, I learned about repeater fields - Unfortunately, I get various options, even file size, but none for adding images/files. The same issue exists in the directus demo on the website.

![Screenshot 2020-10-07 at 14 13 24](https://user-images.githubusercontent.com/9402883/95329997-26001680-08a8-11eb-8b1d-3b4b124f5696.png)

**Comment by thagxt** [comment]
Yep, I've just noticed that too. Any updates on this?

**Comment by rijkvanzanten** [comment]
The repeater interface doesn't support relational interfaces, and therefore doesn't support the `file` / `files` interfaces
