### ISSUE TITLE
Show "no collections setup"

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#301]
If directus_collections is empty, show a notice in the sidebar / main page area

**Comment by benhaynes** [comment]
We should also add a simple version of this:

https://github.com/directus/directus/tree/master/.github

**Comment by rijkvanzanten** [comment]
I don't think that has anything to do with this ticket @benhaynes haha

**Comment by rijkvanzanten** [comment]
I've added that to #365 👍
