### ISSUE TITLE
Access-Control via relations

### ISSUE THREAD

**Issue by nils4cosee** [directus/app#3011]
I am currently evaluating how well we could have used directus in our last project and whether we should consider using it in future projects. I have seen a lot of features that would have saved use a lot of time. I can give you more detailed feedback about some flaws I have discoverd, if you like to. But first I am trying to find out how to model the permission model that we have used. It seems not to be that easy. Maybe you can give some hints on how this could be done. Maybe this is a scenario that is not in the scope of directus...

We have the following collections: "exhibitors" and "products"
We have an admin user (which we use ourselves) and a "subadmin" that is able to edit most of the data, except from collection schemas and interfaces.

We also have multiple exhibitor-users that are assigned to an exhibitor in order to edit its data (but not create new ones). Each exhibitor can have multiple users that are can edit it.

1) The admin user creates and "exhibitor" entity and a "user" that is allowed to edit the exhibitor-data.
2) The user can edit the assigned exhibitor, but is not allowed to create new ones.
3) The user can create further users that are allowed to access the same exhibitor, but not other exhibitors

![cms-perm-request](https://user-images.githubusercontent.com/54022132/97718659-7e50bf80-1ac6-11eb-9e58-58724ace1207.png)

Somehow, the "mine" access does not fit here. And I don't see a way to make the exhibitor-user  an owner of "exhibitor 1" after the "subadmin" has created it. I don't see a way to assign multiple owners to the exhibitor.

In my eyes, the correct way would be to create a relation between exhibitor-users and exhibitors and use that relation to determine access-rights. Is this possible?

**Comment by rijkvanzanten** [comment]
I would highly highly recommend taking a look at the upcoming v9 version here: https://github.com/directus/next

We've redesigned the permissions system to work on a rule based system, which from the sounds of it is exactly what you're looking for. The new permissions system let you set permissions based on rules like "where owner field contains current user's ID" (and has support for and/or + nested relational fields)
