### ISSUE TITLE
Initial Responsive Tweaks

### ISSUE THREAD

**Issue by benhaynes** [directus/app#33]
* [x] Drag/Move on black smoke beside nav should close it
* [x] Smoke up to 80% opacity
* [ ] ~No pinch to zoom on mobile~
* [x] Android system header color should match our header, black not blue
* [x] Fix sidebar right border, looks weird with dark smoke (maybe hide that border?)
* [x] User menu doesn't close when clicking on Avatar (should be able to click anywhere on avatar/name/three dots)
* [x] Changing page should close menu

**Comment by rijkvanzanten** [comment]
> No pinch to zoom on mobile

[We can't control this reliably anymore](https://wouterdeschuyter.be/blog/how-to-disable-viewport-scaling-in-ios-10-you-dont) and even if we could, we [really _really_ should not](https://github.com/w3c/html/issues/602).

**Comment by rijkvanzanten** [comment]
> <meta name="viewport" content="width=device-width, initial-scale=1">

This doesn't prevent zooming, it's the `user-scalable=0` tag. Even then, there is no way to prevent zooming on iOS.

I agree on the statement on this potentially being a native app at some point, but even electron supports native zooming (try cmd+ / cmd-). Seeing this kind of reference pixel enlargement zooming isn't available on mobile, and we're working with a lot of small touch targets, I still feel like we should leave native zooming as is

**Comment by rijkvanzanten** [comment]
>  FavIcon/Native Icon: Solid white logo on black or blue circle (follow Android styleguide)

Ref: update manifest.json in `/static/manifest.json`
