### ISSUE TITLE
WYSIWYG Full: SVG Icons Missing

### ISSUE THREAD

**Issue by benhaynes** [directus/app#356]
![screen shot 2018-05-02 at 12 08 13 pm](https://user-images.githubusercontent.com/522079/39535301-8726f60e-4e01-11e8-9b96-f047985e3910.png)

`List` is one that is missing... but it still works when you click where it SHOULD be

**Comment by rijkvanzanten** [comment]
I suspect it's because I'm not using the correct nested format for the toolbar buttons:

https://quilljs.com/docs/modules/toolbar/#container

Weirdly enough, the buttons themselves seem to work as expected.

**Comment by rijkvanzanten** [comment]
We fixed this by switching from custom options to the user providing JSON
