### ISSUE TITLE
Allow for Item Reordering on Listing Page

### ISSUE THREAD

**Issue by benhaynes** [directus/app#366]
If there is a field with a `sort` interface, then the Item Listing page should show handles and allow for drag and drop reordering.

Dragging is enabled by sorting the items by the SORT field/ASC (so you always start with the existing saved order).

There should be a drag handle (like 6.x) that can be used.

New items should always go to the END of the list (NULL should sort after values).

NEED SOLUTION: If the page is only showing partial data (lazy-load) we need to figure out how to send/update order. I do **not** want to do any fancy decimal ordering – but we could do something like:

```
item 1 (visible)
<----- NEW POSITION
item 2 (visible)
item 3 (visible) *DRAG ITEM*
item 4 (visible)
item 5 (not loaded yet)
item 6 (not loaded yet)
item 7 (not loaded yet)
item 8 (not loaded yet)
item 9 (not loaded yet)
```

Item 3 gets moved, but we only have items 1-4 visible (lazy-loaded on page). We could add sort values for 1-4 (Sort: `1,3,4,2`) and then just increment sort values for any NON-loaded items (Sort: `5,6,7,8,9...`). These would be based on the user's column sort preferences on the Listing Page.

I'm tired. Does this make any sense?

**Comment by rijkvanzanten** [comment]
> I'm tired. Does this make any sense?

Same, and probably because of that: no.

This is an interesting problem to solve.

**Comment by rijkvanzanten** [comment]
Only allowed if amount of items < page count

**Comment by benhaynes** [comment]
MVP: If no preferences, the extension should only show the first 4 fields (but not the primary key field)

**Comment by benhaynes** [comment]
Not sure why we didn't think of this before, but tabular sorting should not be an issue:

On the Collection page, if you load items 1-50 out of 4,000... we can still just have SORT (drag and drop) work normally. We can safely reorder the first items because we know they always come _before_ the rest anyway. There's no way (currently) to only see/sort items 50-100 (not including the first ones).

We just don't touch the other (later) items and things will work as expected
