### ISSUE TITLE
Translation Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#367]
This _kinda_ goes within "relational", but we need to add a translation interface (or datatype). This can function as it does in 6.x, but perhaps we allow it to be ordered anywhere on the page? It could be contained within a field group by default to make this more clear.

**Comment by rijkvanzanten** [comment]
Translations interface has been added in https://github.com/directus/api/commit/f3ed35e702484f7055696e4edc6c6a5f20ebf840
