### ISSUE TITLE
Change status from Listing

### ISSUE THREAD

**Issue by benhaynes** [directus/app#370]
When selecting one or more items on the Listing page, the filter menu should hide and the Delete button and "Status" dropdown should appear (only dropdown if contains status field). Delete is always available (based on permissions)... if there's no status it hard deletes, if there is a status soft-delete then it update that.

The dropdown shows all status options the user has permission to use but REMOVES any soft-delete option since that is accessed from the Delete button instead.

Core Listing view types should all support a way to select 1+ items. eg: tile view should look like this:

![screen shot 2018-05-09 at 6 45 20 pm](https://user-images.githubusercontent.com/522079/39843462-24962272-53b9-11e8-8965-c0d184a747ab.png)

And another screen for the hover state only:
![screen shot 2018-05-09 at 6 46 00 pm](https://user-images.githubusercontent.com/522079/39843487-4306cc8e-53b9-11e8-9c7e-6f01e0bf074e.png)

**Comment by rijkvanzanten** [comment]
> Core Listing view types should all support a way to select 1+ items. eg: tile view should look like this:

This sounds like a new issue ( ° ͜ʖ °)

**Comment by benhaynes** [comment]
Do we want to keep this v6 feature or should we just use Batch Edit? Batch is many more steps...

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
> Batch is many more steps...

It's one more click haha

I think batch already solves this

**Comment by benhaynes** [comment]
OK, we'll use batch edit for this! K.I.S.S.
