### ISSUE TITLE
Interface: Show supported thumbnails below File Preview

### ISSUE THREAD

**Issue by benhaynes** [directus/app#373]
Does not need to be for 7.0, but we should show all supported (whitelisted) thumbnails on the File Detail page. We can either show the sizes (as text links) or the actual images. I see this as part of the "System File Display" interface... the same one that shows the full sized image at the top of the file detail page (along with all the file details currently in the File Info Sidebar in 6.x).

**Comment by benhaynes** [comment]
Doesn't the API return this? The file preview interface could show these below the main preview

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
