### ISSUE TITLE
Replace Existing File

### ISSUE THREAD

**Issue by benhaynes** [directus/app#375]
Doesn't need to be in 7.0, but we should have the ability to replace an existing file with a new one (so that any relationships are maintained). Should be as easy as allowing the file interface to accept uploads on the File Detail page.

**Comment by benhaynes** [comment]
Also needs to keep filename the same so links aren't broken!

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman — is this App or API? Does the App have everything it needs to do this already?

**Comment by rijkvanzanten** [comment]
Not sure if the API is all good to go. The app doesn't support it yet

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
