### ISSUE TITLE
Discuss Public App Access

### ISSUE THREAD

**Issue by benhaynes** [directus/app#390]
We have a public user that determines what data is available to CRUDE in the API... why couldn't that "user" also allow access to the *App*? We could have a Global Setting to toggle this feature on/off. When on, there could be a button on the login page for "Public Access" or an endpoint (eg: `/public` that auto-logs into the public group.

Potential Use-Cases:
* Crowd-source data-entry
* Easy data display (think: Public IoT data)
* Public Demo

**Comment by benhaynes** [comment]
Similar but different from the SSO flow. Thoughts?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
