### ISSUE TITLE
Discuss: How to send app links when API isn't known

### ISSUE THREAD

**Issue by benhaynes** [directus/app#400]
If you send a link to a page: eg: https://directus.app/collections/members

We have no way of knowing which API to use. This is a similar problem to the one we'd like to solve for Directus Cloud. We need a way to send users to a specific API (or set of APIs) in the URL.

**Comment by rijkvanzanten** [comment]
If you open that link, it stores the reference and redirects you to the login view. As soon as you login, you continue navigating to that route. Depending on your setup, the login view knows the API to use.

Do we want to go _full_ URL mode `https://directus.app/collections/members?api=https://demo-api.directus.app`, or use the predefined possible APIs in config.js? `https://directus.app/collections/members?api=1`

**Comment by rijkvanzanten** [comment]
We do need the full URL to know where it is, what the env is, and if it's http or https.....

The only way we could obfuscate it is by doing something like base64 the full URL:

```
instead of 
?api=https://rijks.website

use:
?api=aHR0cHM6Ly9yaWprcy53ZWJzaXRl
```

however, it does increase the size of the URL in the query string exponentially, we very well could end up with:

```
https://directus.app?ref=/collections/projects/5&api=aHR0cHM6Ly9yaWprdmFuemFudGVuLmRpcmVjdHVzLmNsb3VkL21hcnRpbnNjbGFyaW5ldGNvbGxlY3Rpb24vcHJvZHVjdGlvbi8=
```

**Comment by benhaynes** [comment]
I like both ways – one is more human readable, the other seems cleaner (albeit longer). Any preference?

Also, I wonder if there's a way to support multiple without getting crazy?

**Comment by rijkvanzanten** [comment]
Multiples..? At a certain point, you probably reach some sort of url character limit I think

**Comment by benhaynes** [comment]
Worth some divergent thinking – we could pass a url to a CSV/config file even. It'd be nice to avoid a proprietary direction (eg: passing a Directus Cloud user ID).

**Comment by benhaynes** [comment]
Well, for Cloud we'll want to pass it a SET of API URLs since a Directus Cloud user may have access to many different instances within their account. But yes, we can add this as a custom script on `directus.app` (the app for Cloud) if needed.

**Comment by benhaynes** [comment]
Do we have a good way to do this for Cloud? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
We should probably include a `ca` query param that can point to the id of a cloud api and connect to it

**Comment by benhaynes** [comment]
This would be especially nice since we could then fill the login project drop-down with **all** their APIs.

**Comment by rijkvanzanten** [comment]
This is now implemented as follows:

By adding the `project` query parameter to the login page containing a base64 encoded URL of the API you want to use, the application will automatically select "Other" and pre-fill the API url
