### ISSUE TITLE
Handle old/bad collection_presets

### ISSUE THREAD

**Issue by benhaynes** [directus/app#402]
When accessing a page with stale/old/outdated collection presets, the page dies – showing no items. We should instead use the default or no preset as a fallback and let the user know _their_ preset was corrupt.

**Comment by rijkvanzanten** [comment]
The API returns a 400 bad request error, which might potentially be caused by something else too. We should consider showing an error with a button to reset the listing preferences.

What about when a group listing preference is wrong, or the global one?

**Comment by benhaynes** [comment]
I agree with being able to reset your preferences – I thought we had a ticket for that actually.

Even if all preferences are broken we should always be able to fallback to the default (no preferences).

**Comment by rijkvanzanten** [comment]
> I agree with being able to reset your preferences – I thought we had a ticket for that actually.

Yeah yeah, the functionality and button already exist in the bottom of the sidebar, but if the query fails, it should be shown front end center
