### ISSUE TITLE
Facebook SSO icon broken

### ISSUE THREAD

**Issue by benhaynes** [directus/app#404]
![screen shot 2018-05-17 at 10 32 56 am](https://user-images.githubusercontent.com/522079/40184227-b2e12b58-59bd-11e8-92d7-48415f7ab46b.png)

**Comment by rijkvanzanten** [comment]
This is technically an API issue, seeing that these icons live in that repo (in the auth providers). We have to update the icons there.

**Comment by rijkvanzanten** [comment]
https://github.com/directus/api/pull/147
