### ISSUE TITLE
Remove ugly yellow from Chrome autocomplete

### ISSUE THREAD

**Issue by benhaynes** [directus/app#406]
We can keep _some_ styling if you'd like (lightest blue?) or just remove it altogether.

https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by benhaynes** [comment]
Actually – I think you're right. I wonder why I was seeing it? Maybe it was the old version?

**Comment by rijkvanzanten** [comment]
I don't know.. I know browser vendors keep changing the way that works too to prevent.. well changing the styling of it 🙃
