### ISSUE TITLE
Issue on second login attempt

### ISSUE THREAD

**Issue by benhaynes** [directus/app#409]
If you log in and get "Bad creds" message, the page doesn't reset to allow you to try again... the spinner keeps spinning and you have to refresh the page.

**Comment by rijkvanzanten** [comment]
> Look, if you had one shot, one opportunity 
To seize everything you ever wanted 
One moment 
Would you capture it or just let it slip?

**Comment by benhaynes** [comment]
Hahah... slip, I guess!
