### ISSUE TITLE
Add global translations function

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#421]
A lot of different (user) objects have a `translation` key, for example the status mapping:

```js
{
  "active": {
    "name": "$t:active",
    "translation": {
      "en-US": {
        "active": "Active"
      }
    }
  }
}
```

There needs to be a single function that takes the values from the `translation` and replaces the `$t:<val>` with the appropriate translations.

There is already a similar function in the store actions for extensions, this one can be extracted into it's own helper.

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Not needed anymore
