### ISSUE TITLE
Implement translations for collection and field names

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#422]
When fields are used, a generated `name` key should be added that uses the translation for the current locale, or fallback to the `formatTitle()` helper if a translation key doesn't exist.

**Comment by benhaynes** [comment]
@rijkvanzanten don't we have this with `directus_fields.translation`?

**Comment by rijkvanzanten** [comment]
We have the API infrastructure in place, but it isn't used in the app yet.

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
no news

**Comment by rijkvanzanten** [comment]
Thats exactly the idea @binary-koan! We want to have a translation interface that will save to this particular json structure.  Once we have that, we can "open up" this field and start using the translations everywhere 😄

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
