### ISSUE TITLE
Design better infinite scroll flow

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#433]
Right now, fetching items happens from parent to child. EG the page fetches the items, and passes the items to the child listing.

To change the dataset, the listing changes _it's options_, eg the `sort` flag, which triggers the parent component (page) to redownload the dataset and update the listing's `items` prop. 

This poses a problem when needing to lazy-load items. In that case, the listing itself cannot update it's options to `offset=20`, because that would remove the first loaded set (that would be pagination).

Right now, I solved this by supporting a `next-page` event, which causes the upper most parent to fetch new records and _adding_ them to the list of existing items. This will _extent_ the set of the child listing.

I'm not sure if this is the cleanest method of solving this problem, so if anyone has bright ideas on how to make this a little cleaner, please let me know!

**Comment by honzabilek4** [comment]
Let me think about this one 🙂

**Comment by rijkvanzanten** [comment]
I think it works fine as is as of right now. Please let me know if you come up with something else @honzabilek4 🙂
