### ISSUE TITLE
Item Detail – Field option dropdown

### ISSUE THREAD

**Issue by benhaynes** [directus/app#436]
A small dropdown icon right of the field name (label). The whole field name becomes a dropdown with additional options:

* Submit NULL
* Reset to current value
* Reset to default value
* Cancel Edit (Batch edit only)

![screen shot 2018-05-23 at 6 09 01 pm](https://user-images.githubusercontent.com/522079/40453813-6ae7d4a4-5eb4-11e8-8017-5a36540cd86f.png)

**Comment by benhaynes** [comment]
Yes please!!!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
