### ISSUE TITLE
Update Login Page Design

### ISSUE THREAD

**Issue by benhaynes** [directus/app#447]
Should be `var(--lightest-gray)`.

I would, but I literally can't figure out how to get the background to be full height.

**Comment by honzabilek4** [comment]
Hi,
It doesn't work because the body is shifted from top due to the collapsing margins. You can prevent it many ways, but quick fix could be changing:
```
.login {
  height: 100%;
}
```
to 
```
.login {
  height: 100vh;
  overflow: auto; //prevents margin collapse
  background-color: var(--lightest-gray);
}
```

**Comment by rijkvanzanten** [comment]
@honzabilek4 height: 100vh has the nasty side effect of not truly being 100% high on iOS decides..

**Comment by honzabilek4** [comment]
Yeah, forgot about that one. It's the glitch with the browser navigation bar, right?

**Comment by rijkvanzanten** [comment]
Yeah.... I think they see it more as a "feature" than a glitch, but yeah 😄

**Comment by rijkvanzanten** [comment]
Technical difficulties aside, are we sure we want `lightest-gray`? It's a big hit on the contrast in the form (see screenshot) and it's the only place in the interface where this color gray is used as background. 
<img width="331" alt="screen shot 2018-06-07 at 3 41 22 pm" src="https://user-images.githubusercontent.com/9141017/41122422-876c5134-6a69-11e8-9a0c-7cac3f4015f1.png">

**Comment by benhaynes** [comment]
As a reminder – we're going to combine all Directus Sign-In experiences to match the upcoming Cloud design. This overlay will "block" the page and fade out to reveal the content once auth is successful. Icon and Project name will change as the API  is selected (similar to SSO).
