### ISSUE TITLE
WebApp Preview

### ISSUE THREAD

**Issue by benhaynes** [directus/app#459]
If a template value has been entered into `directus_collections.preview_url` then a button should appear in the Item Detail info sidebar for that collection. Clicking that button opens a new browser tab with the rendered URL.

**Comment by benhaynes** [comment]
Change of plans. This will be an interface. Maybe even with an iFrame preview if we can figure out the auth part.

**Comment by rijkvanzanten** [comment]
In that case, I'll close this issue. Let's move it to the interfaces spreadsheet
