### ISSUE TITLE
Move edits out of store

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#468]
It was there to enable soft save and auto-redirect to the page in edit. This is too finicky as of right now. I think we're better of cleaning it up and keeping it tightly organized in the codebase until we figure out how to get it working perfectly.

**Comment by benhaynes** [comment]
😞

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
¯\\_(ツ)\_/¯

**Comment by rijkvanzanten** [comment]
We recently came up with the idea of having URLs match the nested level of edits you're working on, eg `/movies/5/directors/+`. This also means that we need a centralized place to keep track of the edits, as multiple routes will be all making changes to the edits. Therefore it's likely that they stay in the store after all!
