### ISSUE TITLE
Rename all the things

### ISSUE THREAD

**Issue by benhaynes** [directus/app#470]
* edit !== update
* view/create !== edit
* matches better with `item-listing.vue`

**Comment by benhaynes** [comment]
Thinking about this, another naming convention could be:

* `collections` (currently `collections`)
* `collection` (currently `item-listing`)
* `item` (currently `edit`)

**Comment by rijkvanzanten** [comment]
🤔 I think I like option 2 better. @honzabilek4 thoughts?

**Comment by benhaynes** [comment]
Do we like `collections`? or does something like `project`, `instance`, `schema`, or `database` work better? It'd be nice if the three terms were different so as not to confuse.

**Comment by benhaynes** [comment]
I say that because if we use `collections` (plural) for the collection listing... then by the same convention we would use `items` (plural) for item listing (`collection`). So I want to be clear and consistent at all three levels.

**Comment by rijkvanzanten** [comment]
We've been sticking to `collections`, `items`, and `fields` this whole time, so lets not change that. The question here is it the "item listing" a list of `items` or a view of the `collection`

**Comment by benhaynes** [comment]
True! Any preference between `items`, `item_listing`, or `collection`? Probably NOT `item_listing`... which means we should probably change the extension category _from_ `listings` to whatever we choose too.

**Comment by rijkvanzanten** [comment]
> Probably NOT item_listing... 

Why?

Collections (list of collections)
Item Listing (list of items)
Item _______ (single item)

**Comment by benhaynes** [comment]
It just seems like a different naming convention, but we _can_...

**Comment by honzabilek4** [comment]
Hi, 
this is really a matter of taste, but I personally would go for:
- `collections`
- `collection` 
- `item`
I think this is the most straightforward, since we have some `collections`, each being a  `collection` of items (collection in short) and then an `item`.

**Comment by benhaynes** [comment]
This seems to make the most sense...

We'll want to change the name of `listings` extensions to `collection`. But that should be fine.

Do we all agree with the shift to `collections`, `collection`, and `item`? We'll want to use/update this language globally (code, docs, etc)

**Comment by benhaynes** [comment]
The only slightly confusing thing is what the new `collection` extensions would be referred to as... 

We have `storage adapters`, `interfaces` and used to have `listings` (all plural). But is it confusing to call these `collections` vs `collection`? Hmm...

**Comment by rijkvanzanten** [comment]
+1 in the collection name being confusing for extensions

**Comment by benhaynes** [comment]
OK, how about this:

* `instance` – API containing a set of of databases on a server
* `collections` – Page displaying a listing of of collections within an instance
* `collection` – Page displaying a listing of of items within a collection
* `item` – Page displaying an interface for each field within an item
* `field` – A database column or _alias_ within a collection
* `interface` – App component for interfacing with a field
* `listing` – App component for listing items with a collection

That's the best I can come up with! The _only_ thing I don't like is that I imagine many "listings" will be charts, data-viz, messages, etc... in other words, not all listings. So I'd love if we could find a better word that means: _a display or presentation of items (or just their values) in a collection_

**Comment by rijkvanzanten** [comment]
instance, environment, project, collections, items, layout, item, form, field & groups, interface, input & display

**Comment by benhaynes** [comment]
Since we're moving from `edit-form` to `form`, we should think about renaming `login-form` to just `login`. Also, what do we think about these:

`header-bar` -> `header`
`search-filter` -> `filter`

`activity-overview` -> `activity` or `activity-sidebar` or `item-activity`
_Also, should the `activity-sidebar` component go inside the `sidebars` directory (next to `info-sidebar`)? It seems to make more sense there since it's always displayed in the Item Sidebar._

Should `permissions-widget` move into the `extensions` directory? Perhaps within a new `/extensions/system` sub-directory?

`components/field-setup.vue` seems like it should be organized within some sort of system subdirectory too. The other root components are pretty global... but not this one.

Is there a `label.vue` somewhere? If so, we should rename `invisible-label` to `label-invisible` and put it next to it.

We could also clarify each component with a single sentence comment at the top of each file. I know we discussed a `readme.md` in each directory, but not all components are in directories.

**Comment by rijkvanzanten** [comment]
> Should permissions-widget move into the extensions directory? Perhaps within a new /extensions/system sub-directory?

There's no extensions directory. This is the app, not the api 😉

**Comment by benhaynes** [comment]
Excusez-moi?

https://github.com/directus/app/tree/master/src/components/extensions

**Comment by rijkvanzanten** [comment]
ohhh that one haha. That folder contains the HoC for working with extensions, no actual extensions themselves. The permission widget wouldn't fit
