### ISSUE TITLE
Use search fields based on datatype

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#487]
In the search bar when adding filters. It should use interfaces that fit the datatype (eg numeric for numbers) instead managing everything in a text field.

Ref #455

**Comment by benhaynes** [comment]
I think the only one that _really_ matters for now is date/time. How difficult would it be to add this one @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
I would have to make a map of datatypes to preferred interfaces and then use those. It shouldn't take _too_ long to implement

**Comment by benhaynes** [comment]
Again, the only types that matter for now are `datetime`, `date`, and `time`

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
