### ISSUE TITLE
Confirm delete of collection/field with "Type that name:"

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#495]

**Comment by benhaynes** [comment]
This is an important safety feature — especially given how much data is lost during a field/collection delete.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
