### ISSUE TITLE
Auto-add directus_fields row when changing "non-managed" field

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#504]
Right now, the API crashes if you try to modify a field that doesn't have a record in directus_fields.

To solve this, the "unmanaged" field should be grayed out and be "activated" by the user to provide this initial row in directus_fields

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
This has been solved in the api since
