### ISSUE TITLE
Support edit field grid

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#506]
Field Grid: Units (1, 2, 3, 4)? Percentage (25%)?, Include "Full"
Maybe we separate "FLOAT" as a separate variable from "WIDTH"?

Only thirds? Only Halves?

```
1-1-1-1
1-1 - 2
2  -  2
4     -
FUUUUUUUUUUULL (0?)
```

**Comment by rijkvanzanten** [comment]
(Don't forget about the side-by-side spacing)

**Comment by benhaynes** [comment]
Duplicate of: https://github.com/directus/app/issues/773
