### ISSUE TITLE
Cap lazyloading at n number of items

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#507]
Otherwise, the browser will freak out with the amount of elements

**Comment by rijkvanzanten** [comment]
On second thought, this is very very hard to decide for every user. A 2018 MacBook Pro can handle way way way more items than a 2010 smartphone. There's basically no middle ground seeing the range of devices is so big

**Comment by benhaynes** [comment]
Global variable?

Or... I think a hard 1k is a safe bet, no?
