### ISSUE TITLE
Status Mapping Incorrect

### ISSUE THREAD

**Issue by benhaynes** [directus/app#512]
Right now, individual `status` fields are not showing the mapping in their own options. Also, the FULL mapping should be used... with subdue on listing, colors, soft-delete, etc.

**Comment by rijkvanzanten** [comment]
What do you mean?

Please use the provided bug report template

**Comment by benhaynes** [comment]
https://next.directus.app/collections/kiosks/1

The status on this page reads:
![screen shot 2018-07-03 at 8 20 05 am](https://user-images.githubusercontent.com/522079/42219428-ed35996e-7e99-11e8-97b1-64dba0190b5c.png)

But in the database, the `kiosks.status` in `directus_fields` has:
![screen shot 2018-07-03 at 8 21 50 am](https://user-images.githubusercontent.com/522079/42219514-285fcbfe-7e9a-11e8-99a6-feacfdc7ac51.png)

**Comment by rijkvanzanten** [comment]
The status interface looks for the option with the name `statusMapping`, so this option is ignored and it's using the fallback global status mapping. This is in fact a configuration error.
