### ISSUE TITLE
Interface Debugger

### ISSUE THREAD

**Issue by benhaynes** [directus/app#525]
**Validation**
A way to add validation string or a way to force invalid so you can see how the interface reacts. Interfaces should have a documented way to know/test when they're invalid so they can add additional styling as needed.

**Dummy Field Name and Note**
We should include a dummy field name and note so you can see spacing. Also, this should show the "star" when required is set to true.

**Notes**
Each options in the debugger should have a note explaining what it does (even if obvious)

**Other Ideas**
Would be nice if the debugger checked for non-variabled hex colors and warned developer.

Would be nice if debugger checked value format against a datatype to make sure it's valid and warned if not.

In fact, ANY additional checks, test, warnings would be helpful :)

Would be cool if the interface section was FIXED on the page, so as you scrolled to adjust you could still see it. This could be disabled if the browser height was too small. Better yet, there could be a "Pin" toggle in the top right of the page so this could be manually controlled.

**Fixes**
The checkboxes should be side by side, the text inputs should have a max-length, and the `type` dropdown should use the styled `v-dropdown` interface (not system) and the length field can go beside it.

![screen shot 2018-07-11 at 1 47 01 pm](https://user-images.githubusercontent.com/522079/42590136-f86fc67e-8510-11e8-82a1-938c42509e20.png)

**Comment by rijkvanzanten** [comment]
The interface debugger will soon be replaced by Storybook. These improvements won't be implemented on the existing interface debugger
