### ISSUE TITLE
Interfaces should never "escape" the field/viewport bounds

### ISSUE THREAD

**Issue by benhaynes** [directus/app#541]
**Describe the bug**
Interfaces that don't have a max-width can outgrow their field boundaries. This results in overlapping interfaces when there are multiple interfaces next to each other, or interfaces that require the user to scroll for miles and miles horizontally.

**To Reproduce**
1. On the live demo, checkout `about`
2. Scroll down halfway the page
3. See the out-of-bounds interface

**Expected behavior**
All interfaces should have a max-width. Interfaces that don't should be cut off by the parent element.

**Screenshots**
![image](https://user-images.githubusercontent.com/9141017/43100548-aae80e7a-8e93-11e8-90a9-cd1d6271473f.png)

**Comment by rijkvanzanten** [comment]
This has already been fixed. The width is hard-limited by the edit form, the height still is flexible and should be set on the interface level
