### ISSUE TITLE
Global System User Tooltips

### ISSUE THREAD

**Issue by benhaynes** [directus/app#543]
Any user names or avatars in the system should automatically (data attr?) have a hover tooltip with more info, and a modal with all info (a global Item Detail modal?)

**Comment by benhaynes** [comment]
Some thoughts:

* Hovering any user-name or avatar should display a User Detail tooltip (see below)
* Should be easy to include
* Should have a dot badge for online (`success`) or offline (`lighter-gray`)
* Should show above/below/left/right so that it fits on the screen
* Should clicking on the user go to the User Detail page (if you have permissions)?
* We could also include the click on the tooltip itself — then we'd need to make sure you can move your cursor to the tooltip without it closing (timer?)
* Ideally a global setting for what info should be shown in the user tooltip (`title`, `location` shown here)

![Directus 8 – Activity](https://user-images.githubusercontent.com/522079/57198390-28867000-6f40-11e9-89f6-ea581eef4f03.png)

**Comment by rijkvanzanten** [comment]
We should also think about what happens / what is supposed to happen when the user doesn't have read access for directus_users.. (Also @bjgajjar could we verify what happens if the user doesn't have read access to directus_users? The user should always be able to read it's own user I suppose 🤔

**Comment by benhaynes** [comment]
Right, but if this is only shown as a tooltip for a username/Avatar then the issue is actually broader (since you wouldn't see the username or Avatar without access).

I'm fine with restricting certain user fields, or hiding the User Directory, but I question being able to disable user read access altogether. I assume the system needs this info for activity, revisions, etc

**Comment by rijkvanzanten** [comment]
We do need the ID of the user to check permissions etc, but we might not need all the other (personal) information

**Comment by benhaynes** [comment]
True, but then we should go back through the entire application/API and make sure we check permissions and only show/return what's allowed. For instance, we'll need to show a user ID on the activity page/sidebar.

**Comment by benhaynes** [comment]
Thinking about this again, this user tooltip logic would all be in one place, so it wouldn't be difficult to include a permissions check and either hide certain info, or the window altogether.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
