### ISSUE TITLE
Should be able to edit Allowed Statuses from parent

### ISSUE THREAD

**Issue by benhaynes** [directus/app#547]
In permissions, you should be able to change the Allowed Statuses of the parent (not just within Workflow). Right now it only shows `--`:

![screen shot 2018-07-23 at 8 41 54 pm](https://user-images.githubusercontent.com/522079/43110286-14d9eaf4-8eb9-11e8-8b84-bc701bfe3589.png)

**Comment by benhaynes** [comment]
They should show `All` or `Mixed` or `None`

**Comment by benhaynes** [comment]
Important one @rijkvanzanten!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
