### ISSUE TITLE
"Managed" field should be hidden or toggle on Settings>Collections>Editing

### ISSUE THREAD

**Issue by benhaynes** [directus/app#552]
Last field should not be shown or should be converted to a *Toggle*.

![screen shot 2018-07-23 at 9 36 01 pm](https://user-images.githubusercontent.com/522079/43111720-718837e0-8ec0-11e8-8105-73e359253467.png)

**Comment by rijkvanzanten** [comment]
Note: update the record in directus_fields in the database should be enough

**Comment by benhaynes** [comment]
I checked the schema and I think this actually IS set to a toggle... is there a reason that this is not converting to a toggle when the `demo` resets?

https://github.com/directus/api/blob/master/migrations/db/seeds/FieldsSeeder.php#L133

@rijkvanzanten @WellingGuzman ?

**Comment by rijkvanzanten** [comment]
@benhaynes You're looking at the seeder, not the [demo.sql file](https://sql.directus.app/demo.sql) that's used to reset the DB

**Comment by rijkvanzanten** [comment]
Changed in the DB 👍
