### ISSUE TITLE
Relational values disappear on save and stay

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#556]
**Describe the bug**
When the app saves and stays, it saves the values and overwrites the local values with the saved values as returned by the API. These returned values don't included the nested relations however, as they're being returned as if `fields` were set to `*` (1 level deep).

**To Reproduce**
1. Go to any item with a relational interface
2. Hit save and stay
3. See error

**Expected behavior**
The app should fetch the related data 3 levels deep on save (just like the edit view on load itself), so it can populate the fields correctly.

**Additional context**
The JS SDK doesn't support parameters for POST yet, so we have to update the SDK first to be able to send `fields: *.*.*` on as a param on save. Next to that, we need to verify if the api actually supports that parameter on save.

**Comment by rijkvanzanten** [comment]
@WellingGuzman Does the api support the `fields` parameter on `PATCH` to `/items/:collection/:pk`?

**Comment by benhaynes** [comment]
@rijkvanzanten — was this fixed with the "flashing values" update?

**Comment by rijkvanzanten** [comment]
I think this was caused by something else. Lemme confirm that

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten — was this fixed with the "flashing values" update?
 
Yes.
