### ISSUE TITLE
Edit form flashes savedValues for brief second on save

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#557]
When hitting save, the edit form shows the savedValues for a brief second. This is due to the fact that the edit form uses a reactive combination of the defaultvalues, savedvalues and edits (kept in the store) to render the values in the edit form. As soon as the save is done, the edits are being cleared from the store before the promise is resolved. The moment the edit form triggers the next step in the promise chain, the edits have already been cleared, causing the reactive values to revert to the edit-less state for the period of time between the edits being cleared and whatever the edit page does (f.e. navigating away). To fix this, we either have to find a way to clear the edits from the store _after_ the edit form is done with handling the cleanup / navigation of the page, or we should "lock" the values used on the edit form as soon as saving commences. I think the second way is easier to do, seeing I wouldn't have a clue how to cleanly "go back up" the promise chain.

**Comment by benhaynes** [comment]
For Save and stay, like on single collections, the old values reappear after saving which makes this more of a high priority ticket

**Comment by rijkvanzanten** [comment]
I think that's an unrelated yet important issue @benhaynes
