### ISSUE TITLE
Restore revision is not working

### ISSUE THREAD

**Issue by benhaynes** [directus/app#565]
Some aren't showing the button, the ones that DO show the button don't do anything:

![screen shot 2018-07-27 at 3 33 52 pm](https://user-images.githubusercontent.com/522079/43342958-7ea1fd5e-91b2-11e8-9927-ae06a251aede.png)

**Comment by benhaynes** [comment]
OK, the button isn't showing up on the first since you can't revert to the current state... BUT the button still doesn't work. :)

**Comment by rijkvanzanten** [comment]
Closed by #583
