### ISSUE TITLE
Lazy Load Issue

### ISSUE THREAD

**Issue by benhaynes** [directus/app#572]
Local: I went to my Activity page and kept scrolling to the bottom (I have `605` items in compact more) and it keeps trying to load more, but there are no more. So it just keeps flickering the spinner.

**Comment by rijkvanzanten** [comment]
I'm not able to reproduce this.. Do you have a way to reproduce the issue?

**Comment by benhaynes** [comment]
I went through every table and checked this... can't reproduce either. Will re-open if it comes up again.
