### ISSUE TITLE
Progress spinner on M2O modal

### ISSUE THREAD

**Issue by benhaynes** [directus/app#577]
When opening a M2O "choose" modal, we need to have a loading indicator. This should exist on all modals that load data if that makes it easier.

**Comment by benhaynes** [comment]
![screen shot 2018-07-28 at 4 36 44 pm](https://user-images.githubusercontent.com/522079/43360513-78901b44-9284-11e8-8a32-e527dd1443cb.png)

**Comment by rijkvanzanten** [comment]
We don't wait for the fields to load anymore so the layout will be rendered right away
