### ISSUE TITLE
Add loading state to relational interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#578]

**Comment by benhaynes** [comment]
It shows the tabular headers, but I can't see any movement or progress indicator. On a slow connection you would still think this is just an empty modal.

![screen shot 2018-08-11 at 3 09 05 pm](https://user-images.githubusercontent.com/522079/43995251-a4081228-9d78-11e8-99e3-c0e1b14cfb14.png)

**Comment by rijkvanzanten** [comment]
That's not related (pun intended) to relational interfaces 🙂 It's the table / tabular layout itself that doesn't have a loading state. I've created a new ticket for that here: https://github.com/directus/app/issues/628
