### ISSUE TITLE
Support dynamically calculated base widths for table columns

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#581]
Instead of using the default 200, read it from the auto layout css and save that instead.

**Comment by benhaynes** [comment]
Not really sure how we do it, but these column widths should be smarter. Could be a default, min, max, width in the interface's meta.json or something else. For example: the Status Badge on tabular shows a huge gap to the right for now reason. That should have a default width of like 30px.

**Comment by benhaynes** [comment]
That is true — but I wonder how things will work when we have a title (important) and 2 other longer text fields (less important). Would it prioritize the longer text or split them evenly? Maybe it doesn't matter if users can change widths.

I'm totally fine with auto setting initial and then manual after that — we just need to try it out and see how well it works! Let's plan on ignore min/max/recommended for now until we have an auto column width demo. :)

**Comment by rijkvanzanten** [comment]
We could still set a default min and max width on the columns inside a tabular view, as long as it's not tied to the interface 🙂

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
