### ISSUE TITLE
Implement unread / read activity

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#589]
Useful for showing the user a little notification when they have unread mentions in comments. There's already a directus_activity_read collection to use

**Comment by benhaynes** [comment]
We need to decide if/how we'll merge activity and notifications (including errors) and [subscriptions](https://github.com/directus/app/issues/248).

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
