### ISSUE TITLE
Support noDisplay option in interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#599]
This will allow interfaces (/ fields) to be removed from layouts. For interfaces that don't display any actual data (like groups or dividers).

**Comment by benhaynes** [comment]
@rijkvanzanten didn't we implement this? I don't see it in any interface `meta.json`, but we just discussed this the other day...

**Comment by rijkvanzanten** [comment]
That was `noLabel` 😉 @benhaynes

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
