### ISSUE TITLE
Remove "readonly" option/styling

### ISSUE THREAD

**Issue by benhaynes** [directus/app#603]
We are using `readonly` and `disabled` interchangeably... we should stick to disabled and remove Core/Extension code/styling for readonly.

**Comment by benhaynes** [comment]
@rijkvanzanten I know you just worked on this, where did we land? I feel like we should pass one param, and the interface/component always works by applying both (or whichever is applicable to the element).

**Comment by rijkvanzanten** [comment]
We use `readonly` in terms of "Directus Terminology", but not every HTML element plays nicely with just `readonly`. So at some times, we will end up with using `disabled`. To make dev life a little bit easier most components support both
