### ISSUE TITLE
Reset Collection Filters Button

### ISSUE THREAD

**Issue by benhaynes** [directus/app#62]
A button that deleted your custom collection preset (not bookmarks) so that your view reverts back to the default. Would go in the Listing sidebar, I assume.

**Comment by rijkvanzanten** [comment]
Filters are setup in the header, does it make sense to have this button in the sidebar?

**Comment by benhaynes** [comment]
duplicate of #138

**Comment by rijkvanzanten** [comment]
@benhaynes it's not a duplicate. This is _reverting all your view settings to the default_, the cross button in #138 is only for _clearing all filters_.

**Comment by benhaynes** [comment]
Good catch! Absolutely right...
