### ISSUE TITLE
Change app to relative URLs

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#634]
**Is your feature request related to a problem? Please describe.**
Right now, every path to static files in the `index.html` get build as absolute paths. This results in the application being broken if it's being hosted in a folder.

**Describe the solution you'd like**
The application should be using relative paths, so it can be hosted everywhere.

**Describe alternatives you've considered**
Alternatively, there could be a way where the user can download a pre-bundled version tailored to their path, similar to how [Caddy](https://caddyserver.com/) lets you make bundles

**Comment by benhaynes** [comment]
If Welling's htaccess fix works, then this is done... right?

**Comment by rijkvanzanten** [comment]
This is technically already done! The htaccess fix is specifically for putting the app _inside_ the API
