### ISSUE TITLE
Merge file-library.vue and items.vue

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#636]
They're too similar to warrant the duplicate code and maintenance hell

**Comment by c-ciobanu** [comment]
Hey, i would like to take this one.

**Comment by rijkvanzanten** [comment]
Sounds good @c-ciobanu! I gotta be honest, it's a little bit 🍝 code. Sorry 'bout that!

**Comment by c-ciobanu** [comment]
np, I was thinking about passing a prop to the /files route and then merge based on that.

**Comment by benhaynes** [comment]
Thanks @c-ciobanu!!! This will make both pages more powerful and streamlined.

@rijkvanzanten is User Directory still using the core `items.vue` file?

**Comment by rijkvanzanten** [comment]
As a matter of fact, with the feature requests for dropping on this page, combined with the other exceptions that files have (other title, custom new-item functionality), it might be better to keep them separated after all

**Comment by benhaynes** [comment]
I'm down to discuss, but my thinking for "global drag and drop" was that _anywhere_ on the platform will accept files — but you determine the scope based on where you drag it. eg: drag on interface uploads and relationally adds to that field... drag onto random page and it just uploads to File Library.
