### ISSUE TITLE
Dashboard Homepage

### ISSUE THREAD

**Issue by benhaynes** [directus/app#646]
This would be a built-in extension, a great example of _Extension Pages_, and an optional start-page for users (as opposed to "Last Page"). The idea here is that you create a masonry grid of Cards each containing helpful information or insight. Additional card options would be added over time, but we could start with 2-3 of the simple yet flexible options below.

## Global Options
* **Title**: The title shown in the card's header
* **Description**: The description shown in the card's header
* **Width**: The width of the card, based on Directus standard widths
* **Height**: The height of the card, based on Directus standard widths
* **Sort**: The general order for the responsive cards, or:
    * **Row**: The horizontal row the card is in (Do we want this? It's not responsive)
    * **Column**: The vertical column the card is in (Do we want this? It's not responsive)

## Dynamic Metric
_Load items from a collection preset, perform an operation on a specific field, format that value within a template._

### Options
* **Collection Preset**: The collection preset to pull data from
* **Field**: The field within the dataset to work with
* **Operator**: The operation performed on the field's value, eg: `SUM`, `AVG`, `COUNT`, `MIN`, `MAX`
* **Value Template**: Micromustache template for value formatting, eg: `${{value}}`, `{{value}}kWh`

### Examples
* **Weekly Revenue** = `SUM(field)` (`datetime` in the last 7 days)
* **Total Customers** = `COUNT(field)` (preset limits to a specific collection)
* **Most Sales** = `CEIL(field)` (`datetime` in the last month)

## Dynamic Items
_Using collection presets, these cards would show dynamic collections such as:_

### Options
* **Collection Preset**: The collection preset to pull data from

### Examples
  * Recent Comments
  * Content that Requires Approval (based on roles)
  * Recently updated/published content
  * Recently uploaded files
  * *Top Salesperson* = (preset orders by sales field, limit 1)
  * etc

## Dynamic Line-Chart
_Using collection presets, this card would show a line chart of data from two fields (x/y) such as:_

### Options
* **Collection Preset**: The collection preset to pull data from, also limits the X axis
* **Field X**: The field used for the x-axis (eg: `datetime`)
* **Field Y**: The field used for the y-axis (eg: `sales`
* **Operator Y**: The operator used on Field Y (eg: `SUM`)

### Examples
* Total sales each day for the last month
* New customers each month for the last year
* Highest pipe pressure per minute over the last hour

## Example Mock

![directus 7 dashboard extension](https://user-images.githubusercontent.com/522079/44242938-55200f00-a19a-11e8-8954-c16a5bebcbb3.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
