### ISSUE TITLE
Possibility to remove an icon (left or right) from a field

### ISSUE THREAD

**Issue by Zielgestalt** [directus/app#648]
I created a new field in a collection and accidentally added an icon right in the advanced options of the options tab. Now I want to remove this icon, but I can't find a way to do this.

**Comment by benhaynes** [comment]
I just realized that this actually already works! If you click on the icon again it toggles off (the icon down in the list, not the one in the search bar). Tested and confirmed to be a solution. 

This, combined with the fact that we're adding a [field-level option to nullify values](https://github.com/directus/app/issues/436) should do the trick.
