### ISSUE TITLE
Can't add checkbox field

### ISSUE THREAD

**Issue by Zielgestalt** [directus/app#650]
I tried to add a checkbox field to a collection. If I chose 'Checkboxes' in the create field wizzard I first get a red error "There was a problem loading the extension". I can go on, but when I finally want to save the field it loads forever and I get an error in the dev console: '{code: 401, message: "Unknown data type: CSV"}'

**Comment by rijkvanzanten** [comment]
Closed by https://github.com/directus/api/commit/09af0706c
