### ISSUE TITLE
Single file upload: missing length

### ISSUE THREAD

**Issue by Zielgestalt** [directus/app#651]
When adding a single file upload field to a collection and just use the default settings, I get an error in the console at saving: code: 12, message: "Missing length for: image". As this is hidden in the advanced options there should be a default value.

If I add a length manually it works. But if I edit the field again, the input for length is empty again (and I get the error again, too).

**Comment by rijkvanzanten** [comment]
https://github.com/directus/api/blob/633a1ae2004e0d846db9f88f48aa7233840a46bf/extensions/core/interfaces/single-file/meta.json#L5

This `null` should be changed to `11`.
