### ISSUE TITLE
Users detail pages are blank

### ISSUE THREAD

**Issue by Zielgestalt** [directus/app#652]
When opening the detail page of a user it is blank. Same with the 'My Profile' page. 
Error in console: '[Vue warn]: Error in render: "TypeError: Cannot read property 'includes' of undefined"
found in
---> <VForm> at src/components/form/form.vue
       <Edit> at src/routes/item.vue
         <Directus> at src/app.vue
           <Root>

Tested locally, on https://directus.app (Stable API) and on https://next.directus.app (latest API)

**Comment by rijkvanzanten** [comment]
This is due to a wrong `type` value for the `status` row in `directus_fields` in the DB. I've updated the demo SQL file (and @WellingGuzman fixed the install flow) to use the right type 😄
