### ISSUE TITLE
Collapse Consecutive Revisions in Activity Sidebar

### ISSUE THREAD

**Issue by benhaynes** [directus/app#654]
I think the Item Detail page activity log would be more useful if you had a collapsed bird's eye view initially, with sections that expand when needed. For example:

```
[ Comment Input...     ]
• 13 Revisions
• [ "Hey, this is another comment!"]
• 5 Revisions
• [ "Oh, a comment!"]
• 23 Revisions 
• Item Created
```

In the example above, you could click on any of the `X Revisions` to expand it to the full list. Those expanded lists have no way to re-collapse... until you go back to that page a different time.

**Comment by benhaynes** [comment]
Still want this one!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
