### ISSUE TITLE
Directus Fields > Validation Message

### ISSUE THREAD

**Issue by benhaynes** [directus/app#657]
We have RegEx validation for fields, but as of now all info to guide users must be added into the Field Note. I propose we add a `validation_message` field that contains a custom message when you try to save an invalid field. This would be an API addition too.

Invalid Notification:

```
[Field Name] Invalid
[Custom Message]
```

Example:

```
Password Invalid
Please ensure that you use at least one number and one special character: #@!$%^&*
```

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by AstralProgrammer** [comment]
I see in the board that this feature is still not yet in progress BUT I can see this feature in https://docs.directus.io/guides/fields.html#adding-fields?

**Comment by benhaynes** [comment]
It's all set on the API side (that's when we wrote the docs) but the app isn't displaying it on save yet... just the standard error. 

We've been super busy closing bugs, but would love a PR if someone's interested! 😊
