### ISSUE TITLE
Add Sort Option to Card Layout

### ISSUE THREAD

**Issue by benhaynes** [directus/app#658]
We should add two sidebar options for sorting the Card Layout view:

`sort_by` (field name)
`sort_direction` (ASC or DESC)

**Comment by rijkvanzanten** [comment]
Is this going in to the sidebar, or in a header bar?

**Comment by benhaynes** [comment]
OK, I agree with that logic!

**Comment by rijkvanzanten** [comment]
This was added in https://github.com/directus/api/commit/0a63c33ba9ae8bab77b2fd039fe44d84bd6f2adb
