### ISSUE TITLE
Settings > Report Bug

### ISSUE THREAD

**Issue by benhaynes** [directus/app#662]
Icon: `bug_report`
Title: `Report Issue`
Description: `Open on GitHub`

Would open a New GitHub issue with the template and **helpful browser/instance info** dynamically added into the issue's body:

Open link in new tab:
https://github.com/directus/app/issues/new?body=%23%23%20Describe%20the%20Bug%0AA%20clear%20and%20concise%20description%20of%20the%20bug%0A%0A%23%23%20Steps%20to%20Reproduce%0ASteps%20to%20reproduce%20the%20behavior%3A%0A1.%20Go%20to%20%27...%27%0A2.%20Click%20on%20%27....%27%0A3.%20Scroll%20down%20to%20%27...%27%0A4.%20See%20error%0A%0A%23%23%20Expected%20Behavior%0AA%20clear%20and%20concise%20description%20of%20what%20you%20expect%20to%20happen%0A%0A%23%23%20Screenshots%0AIf%20applicable%2C%20add%20screenshots%20to%20help%20explain%20your%20problem%0A%0A%23%23%20Additional%20Context%0AAny%20other%20context%20about%20the%20problem%0A%0A%23%23%20Technical%20Details%0A-%20Device%3A%20Desktop%0A-%20OS%3A%20Mac%0A-%20Browser%3A%20Chrome%20v45.0.0.0%0A-%20Directus%20App%3A%207.0.0%0A-%20Directus%20API%3A%202.0.0

_Opens a ticket with the following body:_

```
## Describe the Bug
A clear and concise description of the bug

## Steps to Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '...'
4. See error

## Expected Behavior
A clear and concise description of what you expect to happen

## Screenshots
If applicable, add screenshots to help explain your problem

## Additional Context
Any other context about the problem

## Technical Details
- Device: Desktop
- OS: Mac
- Browser: Chrome v45.0.0.0
- Directus App: 7.0.0
- Directus API: 2.0.0
```

**Comment by rijkvanzanten** [comment]
Woa! I didn't even know you could start an issue like that 🙂

Sounds very useful
