### ISSUE TITLE
Use configured icon in nav sidebar

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#670]
**Is your feature request related to a problem? Please describe.**
The collections have an option to chose an icon, however, this isn't used in the system yet.

**Describe the solution you'd like**
Use the icon as saved in directus_collections and fallback to the 'box' when it's not configured.

**Comment by rijkvanzanten** [comment]
mmmmmmmm so nice

![image](https://user-images.githubusercontent.com/9141017/44540730-c6e5e480-a6d5-11e8-8770-fe34e3bfe764.png)

**Comment by benhaynes** [comment]
We can also use this icon instead of the collection name in the responsive breadcrumb. It would save space and still make it accessible.
