### ISSUE TITLE
Responsive: Collapse breadcrumb to active crumb only

### ISSUE THREAD

**Issue by benhaynes** [directus/app#671]
Breadcrumb should never wrap.

Collections should be the custom "Box" icon, then we should show the active page (the white one). Alternatively, we could always show a BACK ARROW icon to take you back/up one level.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
