### ISSUE TITLE
Responsive: Nav Spacing

### ISSUE THREAD

**Issue by benhaynes** [directus/app#676]
Categories and nav items in the nav sidebar should be larger and slightly more spaced out on mobile so they are easier to touch.

**Comment by benhaynes** [comment]
@rijkvanzanten – perhaps it would be better to adjust all of the body font-size together instead of doing individual components?

**Comment by rijkvanzanten** [comment]
I like that, yeah. Although it might cause some spacing unnecessary large text in for example the breadcrumb

**Comment by benhaynes** [comment]
True. I think we should look at this when we look at all styles so that type scales appropriately. We should be able to scale body text without all of our headings changing.

**Comment by benhaynes** [comment]
This one is on @rachelsun59! I have a new branch that addresses this, but we'll see if it's up to @rijkvanzanten standards though...

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
