### ISSUE TITLE
Limit max width of fields on form.vue

### ISSUE THREAD

**Issue by benhaynes** [directus/app#679]
This is also part of the Field Grid ticket, but responsively we should update all cols to full width... and MAYBE have the col-1 be 50% (fit two side-by-side).

This will keep the Item Detail page clean and never x-scrolling.

**Comment by rijkvanzanten** [comment]
Doesn't it do that for you?


![image](https://user-images.githubusercontent.com/9141017/44588409-a4aaa000-a783-11e8-8df4-06498899bc03.png)


![image](https://user-images.githubusercontent.com/9141017/44588403-a1171900-a783-11e8-8892-5a5cb0684f96.png)

**Comment by benhaynes** [comment]
Well, the fields in your screenshot aren't 100%/50% ... but I guess that's ok since they are the standard width still. But certain fields (status) are expanding beyond what they should be able to. This can't be an interface thing... since one poorly written extension would break the app scrolling. It must be managed by the App field containers.

![screenshot_20180824-095924](https://user-images.githubusercontent.com/522079/44588716-78dbea00-a784-11e8-92e5-ed3ab094d458.png)

**Comment by rijkvanzanten** [comment]
Ah gotcha

**Comment by rijkvanzanten** [comment]
Ref #773

**Comment by benhaynes** [comment]
This is basically the field grid ticket, I will close this and add a note to that ticket...
