### ISSUE TITLE
Responsive: Notifications

### ISSUE THREAD

**Issue by benhaynes** [directus/app#680]
This could be part of the new notifications library, but responsive notifications should be full width (with 10/20px margin on sides and bottom) across the bottom of the app. Right now they squeeze on the right.

**Comment by benhaynes** [comment]
@honzabilek4 – thoughts?

**Comment by honzabilek4** [comment]
Hi, 
I'm going to fix this 🙂

**Comment by benhaynes** [comment]
That'd be great!!
