### ISSUE TITLE
Responsive: Modals

### ISSUE THREAD

**Issue by benhaynes** [directus/app#681]
The modals have an odd gap on the right and bottom now... the smoke should be 100% and modals should always (in responsive mode) fill 100% width/height with a 20/40px margin equally around all sides (the smoke).

**Comment by benhaynes** [comment]
That certainly doesn't look like it's on a phone... (_responsive_) ;)

**Comment by rijkvanzanten** [comment]
Galaxy Note 8? 😅

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/44588105-d53e0a00-a782-11e8-8730-bfd0767d1890.png)

?

**Comment by benhaynes** [comment]
![screenshot_20180824-094752](https://user-images.githubusercontent.com/522079/44588153-fb63aa00-a782-11e8-8b01-df4a9e5c9823.png)
![screenshot_20180824-094824](https://user-images.githubusercontent.com/522079/44588154-fb63aa00-a782-11e8-8725-9a6670f198eb.png)


!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
