### ISSUE TITLE
Settings > Collections&Fields

### ISSUE THREAD

**Issue by benhaynes** [directus/app#684]
* [ ] All fields on this page should have a Note, notes should link to Docs on that feature
* [x] Fields interface should have lines between each row (normal table style)
* [x] Fields interface should show `*` next to required column names
* [x] Fields should show `[DATATYPE] ([LENGTH]) – Default: [DEFAULT]` tooltip on hover
* [x] If we're not using `Item Name Template` anywhere, let's remove it for now
* [x] Remove `Preview URL`
* [ ] Translation should use `code` interface with good placeholder
* [x] Icon: use `icon` selector interface

**Comment by rijkvanzanten** [comment]
The remaining 4 should be fixed in the database seeder / demo.sql

**Comment by benhaynes** [comment]
Last two are duplicates, and those individual tickets have better descriptions:

https://github.com/directus/app/issues/895
https://github.com/directus/app/issues/422
