### ISSUE TITLE
Settings > Roles & Permissions

### ISSUE THREAD

**Issue by benhaynes** [directus/app#686]
Breadcrumb should be `Settings > Roles & Permissions`

All fields should have Notes, notes should link to Docs about the feature

On detail page, the `name` should go above permissions (like the Collections page)

Description, IP Whitelist, and Nav Blacklist should be half as tall

**Comment by benhaynes** [comment]
Let's just update the breadcrumb and close this @rijkvanzanten

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Vadorequest** [comment]
@benhaynes This seems simple and could be a good first-issue for me. I believe there is just some component moving around (UI) and nothing complicated.

Can I get started?

I haven't touched PHP for 6y, so I'd love as many useful resources as you've got regarding contribution guidelines. I've already read https://docs.directus.io/getting-started/contributing.html#repositories and submitted my first docs PR, but actual PHP dev is gonna be much harder. I don't even have PHP installed I believe 😅

**Comment by benhaynes** [comment]
While we'd love the help, we're actually removing the breadcrumb in v9... and that will be released in a few weeks. So I'd say we can ignore this one...

The most helpful contribution would be to pull/test the `app-next` repo, so we can get that as tested/polished as possible. BUT, the repo won't be ready for pulling/testing for another week or so still. We can coordinate on Slack.

**Comment by benhaynes** [comment]
I should mention, the OTHER parts of this feature request (notes, etc) will still happen... but again, it only makes sense to do those in the NEW repo, not the current one (since that will be overwritten in a few weeks).
