### ISSUE TITLE
Allowed Statuses -> Status Blacklist

### ISSUE THREAD

**Issue by benhaynes** [directus/app#687]
I believe this has been updated on the API, but it needs to be updated on the App

**Comment by rijkvanzanten** [comment]
What do you mean with `updated on the app`?

**Comment by benhaynes** [comment]
We should use the same language consistently... not reversing the logic. Right?

![screen shot 2018-08-24 at 9 43 35 am](https://user-images.githubusercontent.com/522079/44587860-31ecf500-a782-11e8-826d-2bce19a008dd.png)

**Comment by rijkvanzanten** [comment]
We also use it as "allowed fields" if you open the field toggle!

**Comment by rijkvanzanten** [comment]
We made that design decision because we thought it would be a little more user friendly to have an active checkbox match "field on" instead of the other way around. Therefore, by default, all statuses are checked, because the _blacklist_ is empty

**Comment by benhaynes** [comment]
Well, that is confusing too... it says `Read Blacklist` for fields and they are all selected. We need to be consistent with the naming of all this. 

To me it makes sense to keep the presentation the same as the store (eg: both a blacklist)... but I'm down to discuss.

**Comment by benhaynes** [comment]
![screen shot 2018-08-24 at 9 53 22 am](https://user-images.githubusercontent.com/522079/44588375-8cd31c00-a783-11e8-86c0-77b0d78fb608.png)

**Comment by benhaynes** [comment]
Also, we need to be consistent with the modals here, and they one-offs? They have no cancel, the smoke doesn't close it, and the action button is on the left instead of the right side.

**Comment by rijkvanzanten** [comment]
They're not one offs; they have the action-required attribute, cause you're required to save it.

The checkboxes map 1-1 to the state, so the confirm button doesn't actually save anything or do anything; it dismisses the modal. Therefore, a cancel button / clicking the smoke wouldn't actually cancel, but dismiss the modal without undoing your changes. That's why we chose (back when) to make this a non-cancellable modal

**Comment by benhaynes** [comment]
OK. Action button must move to the right then (always).

We still need to figure out the language here... we can't say something's a blacklist and then have fields selected as a whitelist.
