### ISSUE TITLE
Single File Upload attempt to write array

### ISSUE THREAD

**Issue by Zielgestalt** [directus/app#688]
Whe uploading an image to a single file upload field (in a collection or 'My Profile') and want to save the collection I can't and get an error:

'We're having some trouble processing your request.. Please try again by refreshing this page. If the problem persists, please contact your system administrator.'
In console: 'Attempting to write an array as the value for column `test`.`image.'

The file itself is uploaded and availably in the file library. I just can't save the item.

Tested locally and on next.directus.app with both APIs.

**Comment by rijkvanzanten** [comment]
@WellingGuzman Remember that issue where the API couldn't accept `datetime` values in the format it returned? Can we update the API so it accepts an object for `file` type fields and extracts the ID from it? This should work the same as any other `m2o`

**Comment by WellingGuzman** [comment]
It should allows you to accept an object for a `file` type if it has a relationship set.

Either way I will take a look at this and see where is the problem.

**Comment by rijkvanzanten** [comment]
Ahh, I think `single-file` might still use `INT` as it's default datatype. That might explain why this error is thrown too!

**Comment by benhaynes** [comment]
Since our directus files PK is an `INT` doesn't that make sense?

I noticed that the Single File interface allows you to upload multiple files at once (it shouldn't)... maybe that's part of the problem?

**Comment by rijkvanzanten** [comment]
No, it uploads the file and stages the response of the API after upload as value for the field. It does this so it can render the image preview based on the source that is in that object. However, it also means that it's trying to save the object into the single-file field INT, which causes the 'Attempting to write an array as the value for column' error.

> I noticed that the Single File interface allows you to upload multiple files at once (it shouldn't)... maybe that's part of the problem?
No, that's unrelated..

**Comment by rijkvanzanten** [comment]
Since this bug is related to the datatypes, I'm gonna wait on https://github.com/directus/api/issues/360 before looking into this.

**Comment by rijkvanzanten** [comment]
> It should allows you to accept an object for a file type if it has a relationship set.
> Either way I will take a look at this and see where is the problem.

@WellingGuzman With https://github.com/directus/api/issues/429 fixed, shouldn't this have been fixed?

**Comment by WellingGuzman** [comment]
This should've be fixed by (https://github.com/directus/api/commit/b918bb1b9579452eaf28dc2e065bc1c14cf41625). It removes `data` from the payload when the value is not a string.

**Comment by rijkvanzanten** [comment]
This is working now 👍
