### ISSUE TITLE
Interface: File – Add max_images option

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#689]
whoops

**Comment by benhaynes** [comment]
I think this interface should be renamed `files` and work as single and multiple ... using a `max_images` option that can set it to ONE or X images.

**Comment by rijkvanzanten** [comment]
Multiple files is a relational interface, the regular file interface is "just" 1 file per cell. Therefore, it's incredibly hard to support both a single and multiple files in the same interface.

**Comment by rijkvanzanten** [comment]
Added a new feature request for a multiple files interface https://github.com/directus/app/issues/956
