### ISSUE TITLE
Move API fetching logic to store

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#691]
Right now, all across the platform, data is loaded first, and put into the store after like follows:

```js
this.$api.getItems("members")
  .then(res => res.data)
  .then(members => {
    this.$store.dispatch("addMembers", members);
  });
```

We could "reverse" this and make the store responsible for keeping the local state up to date with the API. In that case, `this.$store.dispatch("getMembers")` would take care of everything.

We didn't use to rely on the store so much before, so it didn't make sense to have the fetching logic in there. But seeing that we keep more and more of the not-so-often-changing information, like the schema info, in the store, we might as well fetch the info in there too.

**Comment by rijkvanzanten** [comment]
Bonus: we could even abstract away the update vs create logic in things like relations:

```js
this.$store.dispatch("saveRelation", relation);
```

could under the hood have a check for the existence of a primary key and call `createRelation` or `updateRelation` respectively.

**Comment by benhaynes** [comment]
@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
We either move all the API modifications into the store, or move everything out of it. Right now it's this half in between which makes it confusing to work with

**Comment by benhaynes** [comment]
Which do you prefer?

**Comment by rijkvanzanten** [comment]
Doesn't apply to the current structure of the codebase anymore
