### ISSUE TITLE
Disable field name when editing

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#692]
## Describe the Bug
You can't rename a field after it has been created. However, the field name `input` is active when you're editing a field. Changing this value causes an issue when saving

## Steps to Reproduce
1. Go to Collections & Fields setting for a collection
2. Edit a field
3. Change the name
4. See the error

## Expected Behavior
The name input should be disabled.

**Comment by mateoholman** [comment]
Hello, I'd like to take on this bug for hacktoberfest if nobody is currently working on it?!

**Comment by benhaynes** [comment]
All yours @mateoholman!

**Comment by rijkvanzanten** [comment]
This was closed in https://github.com/directus/app/pull/832
