### ISSUE TITLE
Button loader has wrong color

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#693]
## Describe the Bug
We changed the default color of v-button to be darkest-gray, but the spinner in the `loading` state of the button is still bright blue.

## Steps to Reproduce
1. Hit save on any modal that has a loading state (creating / editing fields, deleting items)

## Expected Behavior
This styling should be matching the color of the button

## Screenshots
![image](https://user-images.githubusercontent.com/9141017/44608458-d2aed500-a7c1-11e8-95a4-d1d476404f13.png)

## Additional Context
The spinner with the wrong color can be found here:
https://github.com/directus/app/blob/2f9092a215e79d4b0809a1753a7aa15a1429df0b/src/components/form-inputs/button.vue#L11-L17

**Comment by benhaynes** [comment]
There is no way in the 🌎 that this couldn't have been fixed in _less_ time than it took to create the ticket.
