### ISSUE TITLE
Item Name Template

### ISSUE THREAD

**Issue by benhaynes** [directus/app#696]
Are we using `Item Name Template`? Do we want to keep it or remove it?

**Comment by WellingGuzman** [comment]
All I can say it's that we are not using this field in the API.

**Comment by benhaynes** [comment]
OK, I'm pretty sure Rijk isn't using it either. 

Let's remove this field from the schema @WellingGuzman

**Comment by rijkvanzanten** [comment]
I'm reopening this so I don't forget to remove it from the app too!

**Comment by rijkvanzanten** [comment]
Removed from the SQL demo file (and thus from the app).

**Comment by benhaynes** [comment]
What about migration files and the install code that injects the initial data? I thought there were 3 places that all of this schema info had to be updated?

@WellingGuzman?

**Comment by rijkvanzanten** [comment]
Based on @WellingGuzman 's commit https://github.com/directus/api/commit/a979b82667b54df0d75be1b87891f1bb4d488352 those have been updated!

**Comment by benhaynes** [comment]
👍
