### ISSUE TITLE
Error when attempting to view a collection

### ISSUE THREAD

**Issue by chrisgame** [directus/app#698]
When attempting to view a collection that has been created with only the default fields the following two errors are shown....

![image](https://user-images.githubusercontent.com/766429/44853217-3cfdc480-ac5d-11e8-9edb-eda3cda497fc.png)

If additional fields are added when creating the collection they are also not visible when the collection is viewed.

## Steps to Reproduce
Steps to reproduce the behaviour:
1. Go to the admin settings
2. Click on 'Collections & Fields'
3. Click the blue '+' in the top right corner 
4. Enter a collection name
5. Click 'Create'
6. Reload the page to see the collection appear in the side bar (the fact a reload is required could be another bug).
7. Click on the name of the collection you created in the steps above.
8. No fields are shown on screen and errors appear in the console as shown in the screenshot above.

## Expected Behavior
When the collection is selected it should render correctly

## Additional Context
The original conversation that led to the creation of this issue is available [here](https://rangerstudio.slack.com/archives/C08UKHB9C/p1535469426000100)

## Technical Details
- Device: MacBookPro
- OS: MacOS 10.13.6
- Browser: Chrome 68.0.3440.106
- Directus App: 9f8c3d5dbe832bf9b16ad6e40621aaedb72eaeb4
- Directus API: 39e0d0db7960424bf02aa8aa8b7713f964aeb37c

**Comment by rijkvanzanten** [comment]
As soon as I create a collection, it shows up in the sidebar. I do in fact see the same error!

**Comment by chrisgame** [comment]
👍 Do you think it will be easy to fix?

**Comment by rijkvanzanten** [comment]
Yeah! Just figured out what causes it 🙂 

When retrieving the collections, I nest the `fields` using a `o2m` relationship, and store the result (including fields) in the Vuex store.

However, when creating a new collection, I'm storing the result of the API on POST, but I forgot to ask for the nested `fields` there. Therefore, a newly created collection in store (before refresh) has no `fields` key in it. The application tries using that `fields` key and 💥

**Comment by chrisgame** [comment]
Ah I see, but a refresh still didn't fix the issue for me. The collection wouldn't render even when I selected the collection in the sidebar and refreshed, see the steps described in 7 and 8 above.

**Comment by rijkvanzanten** [comment]
Hmm, that might've been caused by something else.. Did that give the same error?

**Comment by rijkvanzanten** [comment]
After a refresh, it's showing the expected thing for me:

![image](https://user-images.githubusercontent.com/9141017/45776677-9dab6c00-bc21-11e8-891d-18c4f8316220.png)

**Comment by chrisgame** [comment]
I think it was the same error, maybe thats been fixed separately. Are you using master of both API and UI?

**Comment by rijkvanzanten** [comment]
Yeah, this is all `master`

**Comment by rijkvanzanten** [comment]
The above steps are working for me as expected now, so I'll consider this done. Lemme know if it did it for you too 🙂 If not, we'll keep investigating 🕵️

**Comment by chrisgame** [comment]
Hey @rijkvanzanten, thanks for the fix it certainly gets me a bit further along but i'm still unable to add items to a collection that was created with only the default fields. I have created https://github.com/directus/app/issues/833 to cover it.

**Comment by Mu9tafa-Online** [comment]
Still facing the issue, I'm using the latest version of APP/API
