### ISSUE TITLE
Make sure non-admin users can't delete role-level bookmarks

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#701]
It's mentioned in the docs, but I can't remember if it's actually implemented that way

**Comment by benhaynes** [comment]
Same applies to _global-level_ bookmarks. Only Admins can delete (and create) those.

**Comment by WellingGuzman** [comment]
This must be enforced by the API.

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman – thoughts?

**Comment by benhaynes** [comment]
Technically this is done (on the API side). We can re-open this later if we want to make a fancier App conditional that blocks users _before_ they try.

ref: https://github.com/directus/api/issues/355
