### ISSUE TITLE
Primary Key interface doesn't render for string based primary keys

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#705]
## Describe the Bug
Normally the ID interface is hidden on new items (because it's auto generated). However, when the PK is a string type, it should in fact render the interface (as a required field).

## Steps to Reproduce
1. Change a primary key field to a string based type
2. Create a new item

## Expected Behavior
The primary key field should render

## Screenshots
![image](https://user-images.githubusercontent.com/9141017/45190872-28499f80-b20e-11e8-895f-92f386c37954.png)

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/api/issues/361

**Comment by rijkvanzanten** [comment]
This has been _kinda_ fixed in 97b8bb2. However, it now returns the primary key field, even if you have primary key with auto increment. The API doesn't return the auto-increment state (yet), so that's not something that can be fixed right now..

**Comment by benhaynes** [comment]
bump

**Comment by rijkvanzanten** [comment]
Directus doesn't support setting auto_increment yet. If you have an integer field marked as a primary key, it's expected behavior for it to render, as you need to have a primary key in order to save the record.

**Comment by rijkvanzanten** [comment]
The field renders for a string primary key just fine, so this issue is considered invalid. I'll open a new one for a feature request to add support for auto_increment

**Comment by benhaynes** [comment]
Already have it: https://github.com/directus/app/issues/831
