### ISSUE TITLE
Group collection options in relation settings

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#707]
**Is your feature request related to a problem? Please describe.**
When you choose a collection in your relation, the user's collections are mixed with the Directus system collections. It's actually useful to have the directus collections available there, but they should be visually separated from the user's collections.

**Describe the solution you'd like**
The options in the `<select>` should be grouped using the [`<optgroup>`](http://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) element.

**Describe alternatives you've considered**
We could hide the directus collections by default, and only show them after the user has toggled them on somewhere somehow.

**Additional context**
_Currently_  
![image](https://user-images.githubusercontent.com/9141017/45228318-dd24a080-b290-11e8-96fc-58ddaef123bb.png)

_Proposed_  
![image](https://user-images.githubusercontent.com/9141017/45228354-fc233280-b290-11e8-8775-761725a755b4.png)

These options are being rendered in `/src/components/field-setup.vue`:

https://github.com/directus/app/blob/0de61a9c1520eb002029d17b29ae571195841254/src/components/field-setup.vue#L116-L121

**Comment by benhaynes** [comment]
Seems easy enough...
