### ISSUE TITLE
Interface: Radio Buttons (M2O)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#709]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Interface: Radio Buttons (M2O)
### :+1: = 16
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Another input/interface for the Many-to-one relational UI

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
