### ISSUE TITLE
Data Export (eg: JSON, SQL, CSV...)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#711]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Export Items From App (eg: CSV)
### :+1: = 12
*Created 1 year ago by @diegogurpegui*
 

-----
### @diegogurpegui – (1 year ago)
Ability to export records from a table to some standard format like CSV.

Additional features: - export based on filters applied to the table - export only selected columns

 

-----
### @Zilus – (1 year ago)
Waiting for this to happen.

 

-----
### @lehha – (1 year ago)
Table-based CMS without import/export - its a sadly...

**Comment by benhaynes** [comment]
Some output options:

* `CSV`
* `JSON`
* `SQL`
* `XML`

Could be an option for viewing directly (in browser), copying to clipboard, or downloading a file. These options could be enabled/disabled based on requested Item Count. It would be nice to also optionally incorporate the current filters, sort, etc into the dataset.

**Comment by yarick2000** [comment]
It will be also really cool if XLIFF export/import (1.2/2.x) will be added for translations.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
