### ISSUE TITLE
M2X/Matrix/Replicator Field Type

### ISSUE THREAD

**Issue by benhaynes** [directus/app#712]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Matrix/Replicator Field Type
### :+1: = 17
*Created 1 year ago by @bcartier*
 

-----
### @bcartier – (1 year ago)
A field type similar to Statamic's Replicator (https://docs.statamic.com/fieldtypes/replicator) or the Craft CMS Matrix Field (https://craftcms.com/docs/matrix-fields) that would allow you to build an entry from various blocks (other fields). Add a WYSIWYG block, then a relationship field pulling from other tables, then another WYSIWYG, then and image block etc... This allows you to keep the WYSIWYG field simpler (without having to embed everything inside it), while having editorial freedom well-structured content.

 

-----
### @benhaynes – :+1: (1 year ago)
Same as current M2M UI, except: 1. Junction table also stores the related table 2. UI is editable inline instead of each item opening in an overlay

Below is one direction, but you could just as easily store data in the junction table itself instead of multiple related tables.

Example of schema:

THIS TABLE - matrix_column (ALIAS) Like a M2M but also stores the related table...

JUNCTION TABLE - id - sort - matrixid - relatedtable (NEW!) - related_id

RELATED TABLE VARCHAR - id - title (VARCHAR)

RELATED TABLE TEXT - id - text (TEXT)

RELATED TABLE INT - id - image (INT)

Example of what junction table stores:

{ id: 1, sort: 1, parentid: 1, related_table: 'varchar', related_id: 1, data: { title: "My Matrix Title" } }, { id: 2, sort: 2, parent_id: 1, related_table: 'text', relatedid: 1, data: { text: "Lorem ipsum dolor et..." } }, { id: 3, sort: 3, parentid: 1, relatedtable: 'image', related_id: 1, data: { image: 1, data: { url: "my-file.jpg" } } }

 

-----
### @luminarious – (1 year ago)
This and Postgres support were the two reasons we didn't go with Directus for a medium-sized content site (couple of hundred pages in 3 languages) at my current organization, despite the really good overall developer experience

 

-----
### @Elvanos – :+1: (6 days ago)
Lack of this single feature is the sole reason I am incapable of replacing WordPress with your great CMS... please add it, we really need it!

**Comment by benhaynes** [comment]
The API will support this in API 2.0... but we need to build out the interface for 7.0 still. That hard part is done!

It will be called `m2mm` (many-to-many-many) and will be the same as a `m2m` but use the UUID primary key to link items from different collections.

**Comment by cesasol** [comment]
There is any work towards achieving this feature? I may be needing it soon and I could lend some help or even start working on this.

**Comment by benhaynes** [comment]
It's on the roadmap, but there is no active development as of now. I do know that _many_ users would be super grateful if this was expedited though. ;)

We'd love any help with this if you're willing. The next step is getting the X2M (M2MM) relationship working. Then it should be pretty easy to build the interface.

We can keep discussing on Slack if you'd like... https://slack.getdirectus.com/

**Comment by rijkvanzanten** [comment]
# Dynamic Content

Define and create repeatable content components to allow for dynamic page layouts without breaking design guidelines. 

This would be incredibly useful in blog type content, or the ability to create and manage multiple landing pages within a single install.

## How it Works

Create a single Dynamic Content field that can contain multiple children fields such as image, text, or wysiwig fields. You would be able to define and create multiple Dynamic Content fields for each collection. When entering a single item you would be able to add Dynamic Content fields from a dropdown in the item, thus creating a unique layout for that item.

Dynamic Content Field
* Text Child Field
* Image Child Field
* Dropdown Child Field

## References

[Advanced Custom Fields](https://www.advancedcustomfields.com/resources/flexible-content/)
[Prismic.io](https://prismic.io/feature/dynamic-layout-content-components)

**Comment by benhaynes** [comment]
https://docs.directus.io/guides/relationships.html#many-to-any

**Comment by justrealmilk** [comment]
Is there anything I can help with?

**Comment by rijkvanzanten** [comment]
Hey @justrealmilk! The most important thing to have right now is documentation on how this should exactly work, including relationships and possibly UI. That would help out tremendously 😄

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by X-Tender** [comment]
OMG Just searched for this Feature. Any News on the Progress? :)

**Comment by rijkvanzanten** [comment]
We've figured out a way in which this can work without having to rely on any special UUID type for primary keys. It's yet to be implemented though. I can't make any promises on a timeline.

**Comment by herrbomm** [comment]
Can we accelerate the process quickly by paid work? 
I just dropped and email to ranger-studios ...

**Comment by benhaynes** [comment]
Yes, we'll follow up over email. Thanks!

**Comment by herrbomm** [comment]
@benhaynes  - any updates on this? I contacted Kaushal via slack a while ago regarding this. Its a bit urgent, cause the decision for Directus in our current projects depends on that feature. 

What do i have to do to receive a rough quote/cost and timeline for that interface? Cause depending on those factors the decision might be obsolete already ... thanks in advance 🙏

**Comment by benhaynes** [comment]
Just emailed you...

**Comment by Zielgestalt** [comment]
Any news on this? Or anything I can help with this?

**Comment by herrbomm** [comment]
Well, we had an urgent project where we needed that. @benhaynes made a really good offer for customized work on this. But i was afraid if the timeline could be held which would have made us run into problems with the customer. That's all news i can share ;)

**Comment by Zielgestalt** [comment]
@herrbomm Thanks for the quick reply!
@benhaynes are there any plans to realize this feature? Or perhaps any hint or advise how to realize this with a m2any relation?

I really really really want to switch from Cockpit to Directus 😁, but this feature holds me back.

**Comment by herrbomm** [comment]
@Zielgestalt , no prob. 
I heard API-wise it's already possible to realize such calls. But the interface in the backend is not yet implemented.

**Comment by benhaynes** [comment]
Yes, this will happen.
No, we don't have an estimate for when.

This is free and open-source software, so we can't plan/budget our time like a normal project. This feature will get done when one of the following happens:

A: We finish closing bugs on the App/API/Suite/Cloud to a point where we feel things are "stable"
B: An external contributor submits a Pull Request to add this into the framework
C: An external organization/person "sponsors" this feature by covering the cost of its development time.

**Comment by nicam** [comment]
@benhaynes do you have a rough estimate on the cost of the development time?

**Comment by benhaynes** [comment]
Thanks @nicam —our devs think this would be about two weeks of work. That's 10 working days, at our standard $125/hour that's $10k. Pricey, I know. But that's why it hasn't been prioritized yet. We _will_ get to it for "free", but probably not until Q1/Q2 of next year. Hopefully that helps!

**Comment by Adeolamorren** [comment]
any updates on this?

**Comment by rijkvanzanten** [comment]
@Adeolamorren see above https://github.com/directus/app/issues/712#issuecomment-533919206

**Comment by nitishxp** [comment]
@rijkvanzanten any other alternative way to achieve this?

**Comment by rijkvanzanten** [comment]
A o2m is the closest to a relational repeater we have right now. A multi-collection relationship doesn't exist yet

**Comment by nitishxp** [comment]
@rijkvanzanten then how to proceed my whole cms is dependant on this relation :(

**Comment by rijkvanzanten** [comment]
What is you use case? It's a little hard for me to give any pointers without knowing what you're trying to achieve exactly 🙂

**Comment by nitishxp** [comment]
@rijkvanzanten I have a model say an X and various entities like A, B, C. I kind of achieved this using Django Content-Type which provides the generic foreign key relation. since all my entities are associated with X in some way

**Comment by Zielgestalt** [comment]
My use case is exactly the same as mentioned above: https://github.com/directus/app/issues/712#issuecomment-448331691

**Comment by rijkvanzanten** [comment]
The only way to do that in Directus right now is to make a single _sections_ collection, and use a o2m to create the different sections. By adding a sort type field to the related collection, you'll be able to sort them in an order. The only downside of that is that every section has the same fields, so you'll have to have a couple fields in there that aren't used for every section.

The intent-to-implement solution here is to have multiple collections for each "section type", and have a o2m style interface that can link to multiple collections. We want to make this possible by adding support for a "source collection" column to a junction table. Until that's a thing in the API, the one-to-many route is the best alternative

**Comment by carlobeltrame** [comment]
I wanted to try and implement this, so I gave the topic some thought and looked at the information here, in directus/api#8 and directus/docs#40. The frontend seems relatively clearly defined to me, basing it on the M2M interface should work out fine I think. But API-wise, is the functionality that is promised in the docs already somewhere on a branch? To test an implementation would require an API that supports this first.

**Comment by benhaynes** [comment]
Hey! The current API doesn't support this yet, but we're working on a full Laravel refactor that will add this...

**Comment by carlobeltrame** [comment]
That sounds very promising, thanks for the heads up!
