### ISSUE TITLE
Interface: Checkboxes (M2M)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#713]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Interface: Checkboxes (M2M)
### :+1: = 9
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
It would be nice to have an additional, simplified UI for handle MTM fields: simple checkboxes.

Let's say I have a People table and a Roles table which are related MTM.

Now when editing an user instead of having a list of roles of this users to which I can add or remove items it would be nice to have just a few checkboxes like

[x] Administrator - [ ] Editor - [x] QA

which I can check or uncheck in order to assign roles - without the ability to create new roles and without showing any details on the roles.

In cases like this in which there are only a few possible items on one end of the relationship this would provide a simpler and more compact work flow.

 

-----
### @benhaynes – (1 year ago)
And using the Checkbox UI with the SET column type

edit I think It's rather the "Multi Select" UI I am talking about.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
