### ISSUE TITLE
Directus App URLs Return JSON

### ISSUE THREAD

**Issue by benhaynes** [directus/app#714]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Directus App URLs Return JSON
### :+1: = 7
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Would it be possible to have any Directus App URL (eg: Items Browse) path return JSON by simply adding ".json" to the end? We could then have parameters for how deep (relationally) you want to fetch information. I wonder how this compares to our current way of serving up data (/api/1/xxx..)

So: `http://directus.com/users/1.json` would return the user's info in JSON

 

-----
### @rijkvanzanten – :-1: (10 months ago)
That would drop the version from the URL which makes it quite hard to update things without introducing breaking changes for the user..

**Comment by rijkvanzanten** [comment]
I can't think of a reason why this is useful to have to be honest. Happy to discuss this further if anyone can give me a good example why the application should return the API output directly under a different "endpoint"

**Comment by benhaynes** [comment]
I see it as an alternative way to export data. I will close this and add `JSON` as an export option to the ticket below. Basically we are going to eventually add an Data Export feature to Directus... I'm simply proposing one way to accomplish this: *Adding the supported extension to the _Browse Items_ page in the App*. This could have a helper button in the app too... 

https://github.com/directus/app/issues/711
