### ISSUE TITLE
Auto-Submit Directus Errors

### ISSUE THREAD

**Issue by benhaynes** [directus/app#715]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Auto-Submit Directus Errors
### :+1: = 5
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Directus could have a global opt-in option during setup that (if on) would securely submit any errors/issues anonymously and without private info. This would help the Core developers identify and diagnose problems earlier and with more information.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
