### ISSUE TITLE
Warn if multiple users are editing the same page

### ISSUE THREAD

**Issue by benhaynes** [directus/app#716]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Warn if multiple users are editing the same page
### :+1: = 5
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
This was in Directus 5, but was not added into 6. We should warn users if they access an edit page (item or setting) that another user is currently on. Here is the alert from v5:

Another user (XXXX) is currently editing this item – we advise you wait until they are finished to avoid conflicts.

 

-----
### @Hainesy – (1 year ago)
This only works when using the Directus GUI. Many users will be using the API. It would be great to solve conflicts in a cross-cutting way with optimistic concurrency control.

**Comment by rijkvanzanten** [comment]
Closed in #270
