### ISSUE TITLE
Add focal point coordinates to images

### ISSUE THREAD

**Issue by benhaynes** [directus/app#718]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Add focal point coordinates to images
### :+1: = 8
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
A simple tool for clicking on a Directus image asset and saving the X/Y pixel coordinates for a point of interest (focal point). This would be useful in many situations, especially dynamic thumbnail cropping.

**Comment by benhaynes** [comment]
Keeping this since it was highly voted on the last site...

**Comment by rijkvanzanten** [comment]
We don't feel like this is relevant for the majority of users
