### ISSUE TITLE
Interface: Content-Tree Categories

### ISSUE THREAD

**Issue by benhaynes** [directus/app#719]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Interface: Content-Tree Categories
### :+1: = 6
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
A new UI to show a selectable branch of the tree and supports a schema similar to:

```
items
    id
    category_id

category
    id
    parent_category (allows nesting of categories)
```

 or just nested items:

```
items
    id
    parent_id
    ...
```

-----
### @laszlokorte – (4 months ago)
You should consider storing parent/child relationship in a separate table (ie closure table, eg https://coderwall.com/p/lixing/closure-tables-for-browsing-trees-in-sql)

**Comment by svallory** [comment]
I would really love this! I'm using directus as a CRUD app builder. Personal finances in my case. It's the best option I've found so far and with a few tweks/features could really become a full-fledge app builder

**Comment by benhaynes** [comment]
We agree! We should have more time soon for this "icing on the cake" work... but for the next few weeks we're focused on bugs and a small refactor. PRs are welcome though! 😄

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
