### ISSUE TITLE
Ability to link to fields

### ISSUE THREAD

**Issue by benhaynes** [directus/app#720]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Ability to link to page sections
### :+1: = 2
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
For edit pages, each column/field should have an ID so it's linkable in the URL (with smooth scroll on load)

**Comment by rijkvanzanten** [comment]
Every field has an ID

**Comment by benhaynes** [comment]
Then we need to write some custom code to account for the fixed header:

`/collections/movies/2#rating` ... you can't see the field.

Also, we could add a link to the field label dropdown (not implemented yet) to "Copy link to field" with the anchor icon. (?)

**Comment by rijkvanzanten** [comment]
> Also, we could add a link to the field label dropdown (not implemented yet) to "Copy link to field" with the anchor icon.

We could, but I don't really see why we would. What's the point of having a link to a field?

Keep in mind that fields might be hidden in groups (or tabs) too

**Comment by benhaynes** [comment]
True! Just some divergent thinking ;)

**Comment by benhaynes** [comment]
Rijk doesn't like my ideas...
