### ISSUE TITLE
Layout: Inline/Spreadsheet Items

### ISSUE THREAD

**Issue by benhaynes** [directus/app#723]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Ajax edit cell in row
### :+1: = 3
*Created 1 year ago by @lehha*
 

-----
### @lehha – (1 year ago)
Allow to edit cell in view of data. Just click on cell, ajax loads content (text-field, list, radio-buttons). Hit Enter to save, Escape (or lose focus) to cancel.

**Comment by benhaynes** [comment]
Here are rough designs for both. I think they are similar and maybe could be combined... the difference is if we show/adjust the **RAW** value (always plaintext) or a formatted one using the inline interface. Plaintext/spreadsheet is easier so we should start there!

![directus 7 inline view](https://user-images.githubusercontent.com/522079/49912325-cffeeb00-fe57-11e8-9a95-42fa60f6c6ed.png)
![directus 7 spreadsheet view](https://user-images.githubusercontent.com/522079/49912329-d2f9db80-fe57-11e8-850e-fe3d887cd221.png)

**Comment by srjrol** [comment]
From a duplicate feature request I made... the idea is to edit a full row (or more) by utilizing the existing interface for selecting items and editing.  When a single row is selected and you choose edit it allows you to items from the entire row on the same page.

![image](https://user-images.githubusercontent.com/34398302/55417454-5853e980-5536-11e9-8261-661cec37afb1.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
