### ISSUE TITLE
Choose Storage Adapter

### ISSUE THREAD

**Issue by benhaynes** [directus/app#724]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Single/Multiple File Saving Paths
### :+1: = 4
*Created 1 year ago by @doughnet*
 

-----
### @doughnet – (1 year ago)
It would be great if each Single/Multiple File fields could specify a default saving path OR select a new/full path to a different location.

 

-----
### @benhaynes – (1 year ago)
It seems that this is possible – and I think it's a great idea. We'll look into adding in the next version.

**Comment by benhaynes** [comment]
It seems like an interface option to choose the Storage Adapter would solve this.

**Comment by benhaynes** [comment]
What do we need to accomplish this @rijkvanzanten @WellingGuzman ?

**Comment by benhaynes** [comment]
Global config option with interface level overrides... or dropdown in global upload modal.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
