### ISSUE TITLE
Auto-add M2O when creating a O2M relationship

### ISSUE THREAD

**Issue by benhaynes** [directus/app#725]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Auto-add M2O when creating a O2M relationship
### :+1: = 2
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
When you create a M2O UI relationship you end up with an INT column on the related table showing the ID. It seems like it would be ideal to automatically create the reciprocal O2M UI so this ID becomes a usable interface for choosing/changing the relationship in the other direction.

**Comment by rijkvanzanten** [comment]
The relation now is both ways in the DB. We don't create the field on the other side, but as soon as you create the alias field on the related collection, the relation itself will already be setup.
