### ISSUE TITLE
Show Visual Diff of Text Updates

### ISSUE THREAD

**Issue by benhaynes** [directus/app#726]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Track changes in TEXT UIs visually
### :+1: = 2
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
This looks like a great (open source) tool, or at least example, of how we could track/show changes and revisions to TEXT content.

http://nytimes.github.io/ice/demo/

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
