### ISSUE TITLE
Allowed File Types Option for Files Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#727]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Multiple Files Add Allowed Filetypes
### :+1: = 1
*Created 1 year ago by @RabbitMC*
 

-----
### @RabbitMC – (1 year ago)
For a multiple files field in a table add a "Add Allowed Filetypes" option like in a Single File option.

In my Case I need a Field, which represents the ability to represent a gallery of images and a gallery of pdfs, but I won't a "mix" of filetypes in an field

**Comment by benhaynes** [comment]
@rijkvanzanten @c-ciobanu — is this easy to do (similar to the file-size warning/limit?

**Comment by rijkvanzanten** [comment]
It is slightly more involved. The upload component first needs to have a property that allows to set this validation. Then the `file` and `files` interfaces need to have this option added in the meta.json file and pass it on to the upload component.

Not super hard to do, but not as easy as the file size warning either :)

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/api/pull/747
