### ISSUE TITLE
Settings: Server Info Page

### ISSUE THREAD

**Issue by benhaynes** [directus/app#728]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# PHPINFO() and other useful insight for Admins
### :+1: = 2
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
In settings, we should add a page that gives the admins a way to see important server/db/config info...

**Comment by benhaynes** [comment]
Let's get this in @rijkvanzanten — even if it's just SUPER basic info. Let's choose a few useful values and either print them to the screen or add them into disabled interfaces.

MaxFileSize, PHP version, MySQL version, API Version, App Version, Server type... those would be a good start!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
