### ISSUE TITLE
Show fallback icons for files

### ISSUE THREAD

**Issue by benhaynes** [directus/app#729]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Show generic PDF thumbnail if no ImageMagick
### :+1: = 1
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Right now, without Imagemagick, PDFs upload with a broken thumbnail

**Comment by benhaynes** [comment]
All non-image/video assets should show the extension instead of a thumbnail (unless we can generate a thumb of the PDF)

**Comment by benhaynes** [comment]
So the conditional is this:

1. **image type**: Show Thumbnail (jpg, png, gif, etc)
1. **image not loading**: Show `broken_image` icon
1. **all other files**: Show file icon `insert_drive_file `

**Comment by benhaynes** [comment]
This seems like a super easy one to finish/close, all we need is:

* Show thumbnail if there is one (images, or embeds that have thumbnail)
* Show the extension otherwise (eg: `PDF`)
* Edge-cases (eg: users) should show the user icon if no thumb exists

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
