### ISSUE TITLE
Interface: Directus Collection/Field Template

### ISSUE THREAD

**Issue by benhaynes** [directus/app#730]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# UI: Directus Table/Column Template
### :+1: = 1
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
A UI to provide auto-complete, styling, and validation for adding template strings:

{{first_name}} {{last_name}} – {{bio}}

It would give a dropdown below the input after {{ and check that all columns exist before submit).

We could use contentEditable so that we can use a div instead of an input – then we can style the text (regex) also.

**Comment by benhaynes** [comment]
Is someone working on this one @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Isn't this what you added @shealavington?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
