### ISSUE TITLE
Add a "Tour" overlay for new users

### ISSUE THREAD

**Issue by benhaynes** [directus/app#736]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Add a "Tour" overlay for new users
### :+1: = 1
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Very simple. An overlay that shows where things are and what names mean.

Only appears the first time you log in (if you click skip or complete)

Should be skippable

**Comment by benhaynes** [comment]
To keep this simple and make it happen... let's make this an "Introduction" modal instead of a whole tour. We just need something that opens the first time a user logs in that points them to:

* Welcome Title
* Welcome message, maybe with a friendly emoji
* User Guide (Docs)
* Configuration (If Admin, Docs)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
