### ISSUE TITLE
Allow for editing fields of system collections in Settings

### ISSUE THREAD

**Issue by benhaynes** [directus/app#738]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Allow for editing of system tables in Settings
### :+1: = 1
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
If users add custom columns to system tables (eg: favorite to directus_files) there is no way to choose/setup an interface because we don't allow editing of those tables. We should update this.

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/app/issues/830
