### ISSUE TITLE
Interface: A/B Testing

### ISSUE THREAD

**Issue by benhaynes** [directus/app#740]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Multivariate Testing UI Support
### :+1: = 1
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Gives alternate (M2M) options for fields that also store/show impressions versus clicks. This would allow A/B testing titles, etc.

**Comment by benhaynes** [comment]
I have a design/concept for this...

**Comment by benhaynes** [comment]
![directus 7 item edit ab testing](https://user-images.githubusercontent.com/522079/45256011-635ae880-b35e-11e8-8444-3dbbfafd56fe.png)

### Details

The `ab` interface is essentially an enhanced `m2m` with two extra custom API endpoints. It stores versions in the related collection, but also has a _second_ related collection for version metrics.

* The Control is the primary item (majority %)
* The Variant is an item to test against (minor %)
* This interface would be paired with Extension Endpoints:
    * GET: Serves A/B content based on ratio set in interface options. For example, Constant Item (A) might get sent 95% of the time, while the Variant Item (B) would be sent the remaining 5%.
    * SET: This endpoint accepts metrics on the success of each Item (A vs B)

#### Metric Collection

This is a related collection that stores data about how well each related item performed. It is used to determine which performed better... so you can then send more traffic to that item. All of this data is shown in a simple chart below the interface (datetime/metric)

* `id` (INT)
* `datetime` (DATETIME) When the metric took place
* `metric` (TINYINT) The metric for the item tested (eg: `1`, `0`, `123`, etc) ... Other metric fields could be added as needed
* `item` (INT) Revision `id` for the Constant/Variant tested

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
