### ISSUE TITLE
View API/SDK Endpoint for Pages

### ISSUE THREAD

**Issue by benhaynes** [directus/app#741]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Export/Code From data listings
### :+1: = 1
*Created 11 months ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
A button on each dataset in Directus (eg: Items Browse) that you could click and it opens up a modal to show the API/SDK endpoint for accessing it (filters, sort, collection, etc):

You click the button, choose `curl` or `JS` in the modal, and then it shows you the code in a textarea that you can copy. The button would only appear for admins, and the same modal could also be used for the EXPORT data as JSON or CSV

**Comment by edenprojectde** [comment]
Is this already added to the Feature Requests? Can't see it in there.

**Comment by benhaynes** [comment]
There was another (similar) ticket, but I just added this to the Feature Request board.
