### ISSUE TITLE
Setting: Start Page

### ISSUE THREAD

**Issue by benhaynes** [directus/app#742]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Option for Start Page
### :+1: = 1
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Add a user-level (or global-level) option to return to their last known position, or a specific page (/tables/projects) of their choice on each login.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
