### ISSUE TITLE
Prefill Bookmark Titles

### ISSUE THREAD

**Issue by benhaynes** [directus/app#744]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Prefill Bookmark Titles
### :+1: = 0
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
When creating a bookmark title, instead of starting blank it should start with:

status page_name: csv_of_filters

Examples:

"Active Offices: America" "Inactive Products: Red" "People: Male" (When status=all, don't show)

**Comment by benhaynes** [comment]
Resurrected!

![Resurrected!](https://giphy.com/gifs/3oEjHZAyClxwawVtFC/html5)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
