### ISSUE TITLE
Column name validation

### ISSUE THREAD

**Issue by benhaynes** [directus/app#747]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Column name validation
### :+1: = 0
*Created 1 year ago by @diegogurpegui*
 

-----
### @diegogurpegui – (1 year ago)
It would be nice if the Admin UI validates that the name of a new field/column is valid. For example, prevent spaces. That will help prevent errors

**Comment by rijkvanzanten** [comment]
This has been implemented in v7
