### ISSUE TITLE
Interface: Relational Tags (m2m)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#749]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# UI: Tags (M2M)
### :+1: = 0
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
We have a tags UI, but it would be good to have a UI with the same interface that is relational (M2M)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Removed from feature requests in favor of https://github.com/directus/app/issues/2669
