### ISSUE TITLE
Bypass Field Requirements Based on Item Status

### ISSUE THREAD

**Issue by benhaynes** [directus/app#750]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Bypass Field Requirements Based on Item Status
### :+1: = 0
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
The thinking here is that you should be able to turn off field requirements for certain item statuses. For instance, if I am saving a DRAFT/INACTIVE item, I should be able to do so without filling in all requirements.

The problem is, that we then need to do a check that all requirements are present before users can switch from DRAFT/INACTIVE to PUBLISHED/LIVE. This might be too much overhead. Let's discuss first.

**Comment by benhaynes** [comment]
@rijkvanzanten and @WellingGuzman  It seems that this would be another flag in the Status Mapping... do we need to add this before launch so it's not a breaking change? Or could we add it later?

This could be added later... but the reverse logic could not. Right?
```
ignore_requirements = true
```

**Comment by rijkvanzanten** [comment]
I'm not sure if this is actually a global status mapping thing. I would imagine that you ideally want to set  the required state of the fields on a _per status_ level, just like you can set the field whitelist per status.

I don't think it'll be a breaking change to figure something out in terms of permissions and introducing this later

**Comment by benhaynes** [comment]
It could go that way too... just thinking it's less confusing and easier to set up if it's a flag on the status mapping. Either way, shouldn't be a breaking change later.

**Comment by benhaynes** [comment]
I still think this should be a `ignore_requirements = true` in the status mapping. Shouldn't be too hard to implement, right?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Maybe this can be a part of the conditional fields @benhaynes

**Comment by benhaynes** [comment]
Hmm, I don't think so. I see this as: `x`, `y` and `x` fields must be completed for production content... but you should be able to save an incomplete "draft" (status) that is missing some of those.
