### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by benhaynes** [directus/app#751]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# add RTL support
### :+1: = 2
*Created 1 year ago by @hadifarnoud*
 

-----
### @hadifarnoud – (1 year ago)
languages such as Hebrew, Arabic, Persian, etc. are Right To Left (RTL). please add RTL support to the UI

 

-----
### @AnisBerbary – :+1: (1 month ago)
any plans for supporting RTL?

**Comment by rijkvanzanten** [comment]
I personally don't have a clue what it takes to implement RTL. If anyone has any pointers or wants to help out, please let me know 😄

**Comment by dur41d** [comment]
I think I can help with this. Implementing rtl is easy in html using the css direction: rtl property value. 

There 2 use cases:

1. Uni-lingual that is RTL (arabic, persian, hebrew): In this case the whole admin interface is RTL oriented. The user can configure this via a global setting in the admin menu.

2. A multi-lingual site where only some of the content is RTL. In this case only the detail page needs to be switched to RTL. I suggest adding a switch widget to the detail page that switches the direction of the detail page on demand so the user can choose to add RTL or LTR content as he wish. Also, I suggest adding an RTL setting to the collection so that the collection can be designated to be RTL. 

So there are 3 RTL settings:

1. Global: The whole site is RTL.
1. Collection: Only the collection is RTL.
1. Per item by adding a switch to the detail page.

This way we cover all use cases. 

Please note that RTL support is only relevant to the user interface as the content in the database is direction agnostic.

**Comment by rijkvanzanten** [comment]
@dur41d Should the RTL be automatically enabled based on the selected language? Or should it be a separate toggle?

Does it also mean that the whole interface would basically be "mirrored"? Eg sidebar on the right instead of the left, save button in the top left instead of the right

**Comment by dur41d** [comment]
@rijkvanzanten The RTL can be associated with the language too so if the user chooses Arabic as the interface language then RTL should be enabled by default. 

But to support multi-lingual sites the user should be able to override this in the settings mentioned above.

**Comment by rijkvanzanten** [comment]
Couple more questions:

* If you are editing Arabic content in an English interface, should the content be LTR or RTL?
* If you are editing English content in an Arabic interface, should the content be LTR or RTL?
* Do the sidebars go to the other side as well?

**Comment by rijkvanzanten** [comment]
> Do the sidebars go to the other side as well?

F.e. like this

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/9141017/49319114-49e2bc00-f4c9-11e8-8de3-621baa30d28f.png">

**Comment by dur41d** [comment]
Yes if editing Arabic then the content should be RTL and vice versa. However the side bar does not have to switch. For example, the user can choose that the interface remains English but when adding an Arabic item he can switch the content but not the sidebar nor the header.

**Comment by dur41d** [comment]
I was able to switch the interface to RTL by changing the following styles. Of course this is not complete but just to give you an idea:

@media (min-width:800px) {
    body {
        padding-right: var(--nav-sidebar-width);
        direction: rtl;
    }
}

aside[data-v-49bd2f10] {
    position: fixed;
    top: 0;
    right: 0;
    height: 100%;
    z-index: 30;
    width: 100%;
    max-width: 80%;
    background-color: var(--white);
    transform: translateX(-100%);
    visibility: hidden;
    transition: transform var(--slow) var(--transition-out), visibility 0ms var(--transition-out) var(--slow);
}

@media (min-width:800px) {
    .v-header[data-v-07bc1b15] {
        padding-right: calc(var(--nav-sidebar-width) + 20px);
    }
}

**Comment by dur41d** [comment]
Also, for RTL mode in LTR interface (Arabic input in English inteface) I suggest only switching the text input (input, textarea, .etc) to RTL and leaving the rest. Because if the user chooses English as his interface language that mean he want's the interface to be from left-to-right and only RTL when adding arabic text as you see in the screenshot below. This is true also for English input in Arabic interface where the all interface is RTL but text input is LTR.

Here are the styles I changed: 

.v-input input[data-v-fa1028f8] {
    width: 100%;
    border: var(--input-border-width) solid var(--lighter-gray);
    border-radius: var(--border-radius);
    color: var(--gray);
    padding: 10px;
    font-size: 1rem;
    font-weight: 500;
    line-height: 1.5;
    text-transform: none;
    transition: var(--fast) var(--transition);
    transition-property: color, border-color, padding;
    height: var(--input-height);
    direction: rtl;
}


.v-input span[data-v-fa1028f8] {
    position: absolute;
    left: 10px;
    top: 50%;
    transform: translateY(-50%);
    opacity: 0;
    transition: var(--fast) var(--transition);
    color: var(--light-gray);
}

.textarea[data-v-e19f3b] {
    width: 100%;
    max-width: var(--width-x-large);
    direction: rtl;
}

![image](https://user-images.githubusercontent.com/1318592/49330041-fae36800-f556-11e8-9dce-486e3c1c2ea6.png)

**Comment by llmuculusll** [comment]
In which version this feature may complete?

**Comment by benhaynes** [comment]
Probably not until 7.1 (in a month or two) unless someone wants to submit a PR.

**Comment by llmuculusll** [comment]
+1  
7.1 released, we can wait for resolving this issue.

**Comment by benhaynes** [comment]
An unexpected new feature was released that pushed us to `7.1` early... so no RTL support yet.  Still probably a few months out for our Core team to look into this.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by llmuculusll** [comment]
Is there any chance to have this feature in V8?

**Comment by benhaynes** [comment]
As of now, RTL is pretty low on our list since it's a new feature, requires a lot of work to get correct, and will likely break many things. So it probably won't be added for a while unless it gets sponsored or we get an external PR. Unfortunate, but that's the reality of OSS.

**Comment by rijkvanzanten** [comment]
For future reference, the locales that will benefit from this are:

* Arabic
* Aramaic
* Azeri
* Dhivehi/Maldivian
* Hebrew
* Kurdish (Sorani)
* Persian/Farsi
* Urdu

**Comment by colorao** [comment]
Hi all
Me, as many people working in Middle East related projects, really consider RTL support as an essential desired feature.
Despite loving Directus, we cannot deliver a CMS without such feature for arabic clients.

Most arabic Interactive projects must be developed in both English and Arabic languages.
Arabic clients are english spoken, so Arabic interface is not essential, but translations are.

Text is direction agnostic in the database, and once in the front end, I can display it properly.
But at the CMS side, proper direction is essential, as Arabic text in LTR direction cannot be readed, edited or corrected  by translators.

I've configured Directus for my project  by using the translation feature (which is really great and I love it)
What I really need is just to change the  translatable fields css when arabic language is selected in the translation dropdown.
Ain't an event (change) or hook or similar we could subscribe to ?

Maybe this feature (change fields direction on dropdown change)  is not a hard one and could be implemented in the next release?

Best

**Comment by benhaynes** [comment]
Good point — @colorao... we can start with RTL support in the `translations` interface, since that will be far easier than the whole app.  However it will likely still be rudimentary (text inputs/areas) since we'd have to research how to handle more complicated interfaces like checkbox arrays, etc.

**Comment by colorao** [comment]
> Good point — @colorao... we can start with RTL support in the `translations` interface, since that will be far easier than the whole app. However it will likely still be rudimentary (text inputs/areas) since we'd have to research how to handle more complicated interfaces like checkbox arrays, etc.

Thanks soooo much @benhaynes 
I agree that texts fields and areas are enough for a first step.
Lots of developers (me included) really appreciate it.

**Comment by colorao** [comment]
Hi Ben
Maybe the simplest an more flexible way could be to add a checkbox or a small icon to every text field, and let the user to change the directionality of that specific field.
When selected, just apply a new direction css to that field.

Something like this.
![directionality_by_field](https://user-images.githubusercontent.com/10981734/80550152-743af080-89bf-11ea-8e27-cf27c90302ab.jpg)

This way lots of languages could be improved in a simple and flexible manner.
(it's just an idea)

Best

**Comment by benhaynes** [comment]
Thanks! That's an interesting approach, but I worry about making the UI far more complex for a small percentage of users. Also, this is a lot of work for RTL users... clicking each interface. I think we can automate this CSS based on the language selected in the translation interface though... I'll add that to our v9 list!

**Comment by colorao** [comment]
Hi Ben
I  agree with you in keeping interface simple.

But translations interface is not “language-related” but "label-related".
I can set a language “code” (en, ar) and a language label (Arabic, English) , but it is not really a language and is not related with any directionality by itself.
those are just tags.

Maybe a checkbox is needed when defining the new language
Something like this?
![directionality](https://user-images.githubusercontent.com/10981734/80594561-88183e00-8a23-11ea-837b-5fca4299e9a0.jpg)

Or even redefine the translations interface and assign it to "REAL" languages...

Any idea on when v9 is available? 

Thanks for your attention and your great work with Directus.

**Comment by benhaynes** [comment]
True! Adding that to the language settings seems like the way to go. 👍
