### ISSUE TITLE
Datatypes Must Match for Relationships

### ISSUE THREAD

**Issue by benhaynes** [directus/app#752]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Datatypes Must Match for Relationships
### :+1: = 0
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Only allow tables to be related by columns with the same datatype (int vs varchar) so they match. Also, match length when it's required.

**Comment by rijkvanzanten** [comment]
To clarify:

When setting up a relationship (eg many to one), you can choose any other collection. You can technically select a collection in which the primary key is of a different type than the field you're currently creating. This results in the field to be created successfully, but the relationship not working as the datatypes don't match.

The application should show some sort of warning or should disable collections of which the primary key type doesn't match the current field.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
