### ISSUE TITLE
Interface: Currency

### ISSUE THREAD

**Issue by benhaynes** [directus/app#753]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# UI: Currency
### :+1: = 1
*Created 1 year ago by @WellingGuzman*
 

-----
### @WellingGuzman – (1 year ago)
An UI that handles currency values.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
