### ISSUE TITLE
Interface Column Width: Min/Max/Default (Items Browse)

### ISSUE THREAD

**Issue by benhaynes** [directus/app#754]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Interface Listing View Column Width
### :+1: = 1
*Created 11 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (11 months ago)
An option to set the MIN/MAX/DEFAULT width for a column on the listing page. For example: We could say the color interface (a circle) is ALWAYS set to 30px column width... or a text area never is less than 10px, or more than 200px.

**Comment by rijkvanzanten** [comment]
Not sure if this is something that we necessarily _want_ to implement. The columns on the listing view can be resized at will and interfaces should ideally be able to render their value in any context, not just the table layout. Adding an option to the interfaces to override it just for the table layout doesn't feel right to me.

**Comment by benhaynes** [comment]
I see what you're saying, but the tabular layout is our default and fall back so I don't think it's absurd to include it in the interface metadata. 

We don't necessarily need minimum and maximum but the default might be a good option.
