### ISSUE TITLE
Custom column display names

### ISSUE THREAD

**Issue by benhaynes** [directus/app#755]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Custom column display names
### :+1: = 3
*Created 11 months ago by @felubra*
 

-----
### @felubra – (11 months ago)
Allow direct editing of the display name of a column; e.g. a column is named 'description' in the DB, but displayed as 'descrição' in the UI. Currently, Directus derives the display name from the name in the database but in foreign languages this is not pratical.

 

-----
### @diegogurpegui – :+1: (6 months ago)
Related to: https://request.getdirectus.com/r/145

**Comment by benhaynes** [comment]
This is now possible in v7! You can change the name... and do any number of translations for column/table names.

**Comment by dougludlow** [comment]
I'm not able to edit the display name, is that by design or am I experiencing some sort of regression?

**Comment by rijkvanzanten** [comment]
@dougludlow This was planned for v7 but was taken out last minute. Keep an eye on #422 for this feature

**Comment by dougludlow** [comment]
@rijkvanzanten kk, will do. I'm specifically looking to change the display name, however, not add a translation for it, does that still fall within #422's scope?

**Comment by benhaynes** [comment]
It does — we'll use the same method for both. And "English" (or whatever native language) translation is basically a re-name.
