### ISSUE TITLE
Tabs / Collapse for a section break

### ISSUE THREAD

**Issue by benhaynes** [directus/app#757]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Tabs / Collapse for a section break
### :+1: = 2
*Created 11 months ago by @MartinMekhaiel*
 

-----
### @MartinMekhaiel – (11 months ago)
meaning every column under a section break is showed under the specific tab on the entry page?

e.g

Section 1 Name Description Section 2 Rating Price

|tab (Section 1)| name description

|tab (Section2)| rating price

**Comment by benhaynes** [comment]
Would this be a [global feature](https://github.com/directus/app/issues/773) or an option of the `grid` interface? @rijkvanzanten @rachelsun59

**Comment by rijkvanzanten** [comment]
Closed in favor of #759
