### ISSUE TITLE
Directus Files in WYSIWYG

### ISSUE THREAD

**Issue by benhaynes** [directus/app#758]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Directus Files in WYSIWYG
### :+1: = 13
*Created 11 months ago by @textoo*
 

-----
### @textoo – (11 months ago)
A Directus Files manager to insert images in the WYSIWYG editor is a must have.

 

-----
### @jedimonkey – (8 months ago)
I've made a real super basic one (for now). Started looking at doing something a bit more fancy, but that will take time. If https://github.com/directus/directus/pull/2002 gets merged, then it's better than nothing!

 

-----
### @mdbarr73 – :+1: (5 months ago)
The current ability to add files through Directus Files is an acceptable alternative, but it's definitely a better end-user experience to have drag-drop capabilities for inserting images.

**Comment by benhaynes** [comment]
@rijkvanzanten — did today's PR close this one?

**Comment by rijkvanzanten** [comment]
When it's merged, yeah 😉
