### ISSUE TITLE
Add ability to setup groups in settings

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#759]
**Is your feature request related to a problem? Please describe.**
The application supports group-type interfaces, but there's no way to currently set them up in the settings interface.

**Describe the solution you'd like**
We have to redesign and refactor the field settings interface to support nesting fields inside of other fields.

**Comment by benhaynes** [comment]
Just a note that groups should be collapsable/expandable...

**Comment by ceruulean** [comment]
Since "groups" is a field, can you add the desired fields to this group in "options?"

**Comment by ceruulean** [comment]
To clarify what I mean: the groups are set in the interface rather than on the settings page
![image](https://user-images.githubusercontent.com/41603229/52980988-8fb17100-33a2-11e9-9cf1-a933abda5975.png)

**Comment by rijkvanzanten** [comment]
> the groups are set in the interface rather than on the settings page (at least for now)

I don't think it's that easy to implement unfortunately: each field needs to save it's parent group, so a group field has a O2M relation to directus_fields. Setting up a group means updating all the fields that are in said group

**Comment by benhaynes** [comment]
Do we all agree that we want to use "fields" for groups? It seems like an elegant solution, but I want to make sure we don't need something that's a bit more "system-level".

I know most users will want _as much control and flexibility as possible_, but I think we want to reign in things to keep the UX clean. Two points on that:

* I think that Groups should always be full-width (since they will be collapsible)
* I don't think that Groups should be nest-able (this seems like it will be a UX nightmare and destroy the grid)

**Comment by rijkvanzanten** [comment]
We should use directus_fields for groups. It gives us the flexibility to have options and sorting etc etc out of the box

**Comment by benhaynes** [comment]
When you say `directus_fields`... do you mean something like `directus_fields.group`? Or would these be ALIAS fields stored in `directus_fields`? Where would we store any options for these?

**Comment by rijkvanzanten** [comment]
Each group is a row in directus_fields with the `group` field type.

Each of the rows in directus_fields already has a `group` column which is a M2O to another row in the same directus_fields collection.

**Comment by rijkvanzanten** [comment]
Each group is a row in directus_fields with the `group` field type.

Each of the rows in directus_fields already has a `group` column which is a M2O to another row in the same directus_fields collection.

**Comment by benhaynes** [comment]
Soo.... we're keeping it the same? 😉

**Comment by ceruulean** [comment]
So implement a recursive interface like [fiddle](https://jsfiddle.net/mikeapr4/pxk2rf0z/)?

**Comment by rijkvanzanten** [comment]
I was thinking about something like that for the field setup @ceruulean, yeah 🙂 
@benhaynes thoughts?

**Comment by ceruulean** [comment]
@benhaynes @rijkvanzanten Thoughts on collapse/expand? What would be the best way to toggle it?
![image](https://user-images.githubusercontent.com/41603229/53272724-b1b73600-36b7-11e9-91ff-f6d562fdda6e.png)

**Comment by rijkvanzanten** [comment]
I like the idea of having it expand inline over there. However, we should also consider how this would work in conjunction with the field grid system

**Comment by ceruulean** [comment]
![image](https://user-images.githubusercontent.com/41603229/53532332-190c2600-3abc-11e9-822a-5d161d13f36e.png)
- Currently highlighting the group highlights all the fields nested inside, not sure if that's a huge concern
- Every time the fields change positions, it sorts the children too, so it might be slow. Should the changes be cached first?

Any ideas about the grid system? I guess could squish the divs to appear in the same manner as the grid layout, and if the viewport shrinks beyond minimum width then the fields are listed like flex columns.

**Comment by benhaynes** [comment]
### Deep Nesting
While this architecture would support deeply nested groups, I still think we want to keep this to only one level (no groups inside groups).

### Accordion Group Settings
I don't think we need to expand/collapse the groups within Settings. I think we should keep all fields visible at all times. We _should_ have the groups expand/collapse on the Item Detail (form) page though!

### Field Order
I'm not sure about the best way to sort these fields. We could keep it how it is and have the App send new sort values to all grouped fields move together (unless you drag field order _within_ a group). Or we could use containers to drag the whole group as _one element_. @rijkvanzanten thoughts?

### Settings Style
I think the "blockquote" style is on the right track for showing that fields are grouped. I'll try to experiment with some other options too!

**Comment by ceruulean** [comment]
Will the group field be re-added? The implementation I currently have relies on the group field.

**Comment by rijkvanzanten** [comment]
Once we have a UI to set it up in settings, groups will be officially added as well.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by mikebilling** [comment]
I know this a bit old now and that this has been added to Feature Requests so somethings probably going to come out eventually, but I went ahead and built a very simple interface that creates a tab block.

To use it, you create a "Tab" interface, then in "Options" you start creating tabs via a repeater. Each tab has a "Label" (self explanatory), and "Items". You just enter an array of interface keys that you want to be listed under this tab (similar to how you use the mirror field in slugs). 

I know it's not as intuitive as some would like by having to fill out an array of keys instead of a drag and drop system, but hey, it works.

I haven't dealt with the mobile layout yet (as tabs get pretty clogged up if you have a lot of tabs), but I'll take a look into it once I get a chance.

[tabs.zip](https://github.com/directus/app/files/3732308/tabs.zip)

**Comment by mikebilling** [comment]
No probs @benhaynes — that's exactly what it was meant to be. Just a temporary option until the real deal is released. This one just replicates the tabs used elsewhere in the admin and it was only scratched together overnight. It also only works one level deep at the moment. Though, it could be made to go additional levels (i.e. tabs within tabs) with a little bit of tweaking.

FYI... what you guys have done with Directus is amazing and I love how easy you've made it to add our own extensions.
