### ISSUE TITLE
Interface: Allow creation of items from M2O

### ISSUE THREAD

**Issue by benhaynes** [directus/app#760]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# UI: Allow creation of M2O like one for M2M exists
### :+1: = 1
*Created 11 months ago by @meezaan*
 

-----
### @meezaan – (11 months ago)
If I'm creating an item in a table which has an M2M relation, I can create a related item on the go. This not possible for an M2O relationship as we have to go the table that contains the O item and create the entry there so it appears in the dropdown.

For example, I have 10 publishers. Many books can be published by 1 publisher. When I'm adding a book from a publisher I don't have in the publisher table. It would be great if this was possible.

**Comment by kaitaylor** [comment]
@benhaynes - Hi, just curious if this was postponed to another release? I saw that you mentioned in [1104](https://github.com/directus/app/issues/1104) that you added this to the 7.0.15 board. Although I notice it's not in the current 7.0.18 release. Is this feature planned for another release?

**Comment by rijkvanzanten** [comment]
Hey @kaitaylor! I've been busy fixing bugs most of the time.. It was on the backlog for 7.0.15 but didn't make it in unfortunately.

I've added it on my todos for 7.0.19. Keep an eye on https://github.com/directus/app/projects/39 for what makes it in to 7.0.19 🙂

**Comment by kaitaylor** [comment]
@rijkvanzanten Thanks for let me know buddy. Really appreciate all the work being put into this. Directus API & App are such great products, am definitely looking forward to seeing them progress and grow stronger.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
