### ISSUE TITLE
Draft edits on published record

### ISSUE THREAD

**Issue by benhaynes** [directus/app#762]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Draft edits on published record
### :+1: = 4
*Created 10 months ago by @john-kurkowski*
 

-----
### @john-kurkowski – :+1: (10 months ago)
Iterating on content, without having to get it perfectly right on the first save, is critical to modern digital writing. Other headless CMSes like Contentful and Prismic let writers accumulate updates to a published record, without inflicting it on customers immediately. Prismic in particular lets you group multiple record changes, which can be scheduled. When the writer gets everything right, when they're ready, then they can commit their draft atop the published version. In the base Directus install, draft records are mutually exclusive with published records. If a record is published, further changes are published immediately, without time to review or preview. Allow drafting further edits to a published record, without publishing it.

 

-----
### @diegogurpegui – :+1: (6 months ago)
That would be great in terms of functionality. This might be also related to the possibility of keeping track of revisions and restore them eventually (https://request.getdirectus.com/r/117)

**Comment by KKAries** [comment]
I think when a published item is edited, it should not be just replaced with the updated one. User can choose to publish the new edited item immediately (which will replace the old published version) or just save as a updated version. Thus, there should be at least two versions of item that user could retrieve by the api - updated and published.  This could be very helpful for testing. E.g. the test env can get the updated version through api but there will always be a published version for prod env.

**Comment by benhaynes** [comment]
The UI would be easy to figure out, but we need a solid way to handle this without making assumptions about the Status Mapping. Here's how I see this working (more data flow, not UI):

## User/Data Flow

1. User makes updates and chooses "Save Revision"
2. Directus adds a `directus_revisions` record for change but does not update actual database item
3. This update is shown in the Revision sidebar in the future — with the current database item highlighted to show what is currently "active" (not to be confused with the "published" status).
4. User goes back to view item and sees the **most current** version (pulled from revisions, not the database item). There would need to be an obvious indicator that you're looking at a revision, not the active item, with a way to toggle.
5. User makes more updates and chooses "Save" (or "Save Master")
6. Directus saves the item as usual, updating the database item and adding a activity/revision record

## Updates Required

* App needs additional save "Save Revision" button
* App button "Save as Revision" needs to send Revisions without updating the item
* App needs sidebar to show _future_ revisions, with current database item selected as "Active"
* App needs indicator for when looking at inactive revisions (click to toggle to active)

## Status Mapping

`status` is just another field, so as I see it we can not use that for this purpose. The status defines permissions and if the item itself is published. Saving an item as "draft" would _remove_ the item from the public API and therefore project-app. Therefore we need a separate system for managing revisions while keeping the item public.

That's why I think we should avoid the term "draft" and instead use something like "revision". Hopefully this clarifies things for the user:

* `status` — a field on the item itself that determines if/when the actual database item is available
* `revision` — a record within `directus_revisions` to store updates (that may also include status field changes)

Does this make sense? @rijkvanzanten can you submit `directus_revisions` through the API without updating the actual item or do we need to extend the API?

**Comment by rijkvanzanten** [comment]
@benhaynes we would have to extend the API, but that should be a trivial endpoint to make, as it's "just" adding a single row to an existing table.

A lot of people compare this kind of revision keeping with git, where the live version of the item is `master` and the revision being another "branch" which can be "merged" into the live version.

**Comment by benhaynes** [comment]
Exactly, we would add a `POST /revisions` — https://docs.directus.io/api/reference.html#revisions

Glad we have all this figured out, but it's still on the back-burner until v7 is a bit further along. If anyone in the community wants to take this on let us know!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by mkmanuel** [comment]
I want to give this feature a shoutout as it would mean that users changing some things in the data would not need to work on live data.

As for implementation: There already is a history with a rollback function. How about extending this into the 'future': This way, when the user accesses an item, the UI can show the data from the DB (=old data) with all 'future' changes (=new data) applied. On publish, the UI stores the changes into the DB proper.

**Comment by benhaynes** [comment]
This is on our short-list for v9!

**Comment by jkjustjoshing** [comment]
Sounds like it's unlikely to get into v9 https://rangerstudio.slack.com/archives/CUTN7RWVA/p1600370784008900

The more up-to-date discussion:
https://github.com/directus/next/discussions/318

**Comment by benhaynes** [comment]
Hey @jkjustjoshing — I think you took my message out of context. 😄 

This feature will _very_ much be in v9... but probably not `9.0.0` (in a few weeks). My guess is that it will be added into v9 in 1-3 months (after the initial 9.0.0 production release). Also, if someone "sponsors" the feature it could be in sooner.
