### ISSUE TITLE
Conditional interface fields

### ISSUE THREAD

**Issue by benhaynes** [directus/app#763]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Conditional interface fields
### :+1: = 5
*Created 10 months ago by @rijkvanzanten*
 

-----
### @rijkvanzanten – :+1: (10 months ago)
It could be very useful to be able to hide/show fields based on the value of another field.

**Comment by rijkvanzanten** [comment]
We don't have support for the conditions yet unfortunately.

However, we do have a pretty solid idea of how it could work:

The search filter uses a JSON structure for the selected filters, which looks like follows:

```json
[{
  field: "title",
  operator: "contains",
  value: "directus"
}]
```

we could use this same structure as the value of a "show when" column in `directus_fields`.

**Comment by benhaynes** [comment]
I like that! But we should think about allowing multiple filters... Since you might want to do more complex conditionals.

**Comment by rijkvanzanten** [comment]
That's why it's an array 😉 

```js
[
  {
    field: "title",
    operator: "contains",
    value: "directus"
  },
  {
    field: "author.first_name",
    operator: "eq",
    value: "Rijk"
  }
]
```

**Comment by rijkvanzanten** [comment]
We should probably add an `action` flag to the object, so we can choose whether to hide or disable a field:

```js
[
  {
    field: "type",
    operator: "eq",
    value: "url",
    action: "hide"
  }
]
```

**Comment by wondergryphon** [comment]
There's a plugin for WordPress called Advanced Custom Fields. They handle it quite elegantly, and leave the `operator` logic up to the user and assume that they will make a choice that matches the field they're dealing with. Example:

![conditional_logic](https://user-images.githubusercontent.com/936966/53145819-64996e00-35aa-11e9-89d3-0ff9a72d4c87.jpg)

It works really well, and prevents having to come up with every possible operator option, and rather provide the user with a choice of standard operators that would handle all situations.

**Comment by benhaynes** [comment]
I like that a lot, thanks @wondergryphon!

**Comment by JonathanAlumbaugh** [comment]
That's fantastic, and would go a long way towards building interfaces that get the right input!

**Comment by ivanmayes** [comment]
+1 for conditional fields here as well.  Let us know if there is something that the community can help with against this feature.

**Comment by benhaynes** [comment]
@rijkvanzanten — is there anything short of the refactor work that the community could help with?

**Comment by felicoz** [comment]
hey @benhaynes, just exploring the directus CMS. Want to suggest to make this conditional field feature as higher priority. without the conditional fields, the interface becomes messy on larger-field-collection and not user friendly...

**Comment by shealavington** [comment]
> Want to suggest to make this conditional field feature as higher priority

**My opinion:**
Features like this aren't nessessary to the core functionality of Directus.

This feature could be created and contributed by yourself or community. You could also sponsor the development of this feature to move the development along as a 'priority', unfortunately, other than that, it's unlikely this feature will be marked as a priority for now as there are plenty of other priority tasks that need to be done.

**Comment by benhaynes** [comment]
I agree with both of you!

I think the conditional fields are super important, and I'm very excited to implement them. Though @rijkvanzanten has said that _technically_ this is already supported... but there's no fancy app interface for setting it up. You'd have to create a custom interface and have it manually turn on/off other field visibility.

To Shea's point... this is unfortunately lower down on the list because we need to focus on stability, docs, and code refactor first (all of which are long overdue). We'll keep this ticket alive though!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by RauppRafael** [comment]
Hey @rijkvanzanten i'm a vue developer, maybe i can help with the front-end implementation of this feature

**Comment by benhaynes** [comment]
I know I speak for Rijk when saying: _We would absolutely love the help!_

I'll let Rijk give more details on how we want to accomplish this, but any help would be greatly appreciated, @RauppRafael . Also you can more easily chat with us on our Slack:

https://directus.chat

**Comment by Owlree** [comment]
For the record, this would be of great help to our organization. I'm looking forward to contributing with anything necessary.

I have a GraphQL API issue that I'll be working on for the next few days, but after that I could begin work on this one, if it fits your priorities.

**Comment by lucasfrey** [comment]
Heya team,

I created a conditional fields module base on the table structure, just hiding and showing fields with javascript from a custom interface you add to the collection.

https://github.com/lucasfrey/directus-conditional-fields

I would love to spend more time on it to improve it, PR are more than welcome :)

**Comment by rijkvanzanten** [comment]
That's really cool @lucasfrey!

**Comment by benhaynes** [comment]
I agree — this is awesome @lucasfrey... thanks for sharing!

**Comment by benhaynes** [comment]
So to memorialize a conversation that @rijkvanzanten and I had regarding this. You could create conditional fields with the following Collection-Level setting:

![Screen Shot 2019-12-10 at 3 45 48 PM](https://user-images.githubusercontent.com/522079/70568379-bde88300-1b65-11ea-930f-3c3da54b2e23.png)

1. Add a helpful name for easy reference
2. Add any number of filters that all (`AND`) need to be matched
    * Entering a filter auto-adds a new row for the next
3. Choose the fields to hide from an array of Field checkboxes
    * This could have an additional array of fields for "ReadOnly Fields" if we wanted
    * Making a field hidden would _not_ change its _required_ state. This would need to be considered when building forms.

Each condition is sortable, and runs in order. So you should be able to create `OR` groupings or more complex conditions.

**Comment by rijkvanzanten** [comment]
Just so we don't forget: `Fields to Hide` should probably be `Visible Fields` (turn them _off_ to hide them) and we should have checks for readonly

**Comment by benhaynes** [comment]
We would need to decide on _"hiding only"_ vs _"set state"_. I was thinking that all fields are on by default (as is currently the case)... and you can set which fields would become hidden based on conditions. That's different from setting the actual state (make hidden or make visible). One is "additive" and allows several conditionals to be serialized together... the other would override everything each time and would make having multiple conditions per collection impossible.

**Comment by rijkvanzanten** [comment]
Yeah, all I'm saying is a name change. Instead of saying "Hidden: true" we should say "Show: true" as it fits better with a on=active=shown paradigm.

**Comment by benhaynes** [comment]
Correct, and I agree... but the "action" would be _hiding_, right? If all fields are normally visible, these conditionals would decide which fields get _hidden_.

**Comment by rijkvanzanten** [comment]
All the checkboxes would be on by default, so you _disable_ a field by _disabling_ the checkbox :slig

**Comment by lucasfrey** [comment]
I guess we'll need to be super precise on the documentation on that one

**Comment by rijkvanzanten** [comment]
As of right now, the plan is to:

* Add a `conditions` column to `directus_fields`
* Save the following JSON structure into that column:
```json
{
  "conditions": [
    {
      "field": "category",
      "operator": "equals",
      "value": "sweaters"
    }
  ],
  "effect": {
    "hidden_detail": false,
    "options": {
      "choices": {
        "l": "Large",
        "m": "Medium",
        "s": "Small"
      }
    }
  }
}
```
* Have a `conditions` tab in the field configuration modal

**Comment by Kematia** [comment]
Ciao guys! Is there a branch/pr on this? It's something I need to implement for a use case so I might work on this a bit...

**Comment by benhaynes** [comment]
I don't think there's a dedicated branch, but we have the new `app-next` repo for v9/v10. I mention that because conditional fields will probably be a deeper integration, so adding it over there makes more sense.

@rijkvanzanten , do you agree?

**Comment by rijkvanzanten** [comment]
The more difficult question is how to handle this on the API side. Hiding / showing fields on the front end is doable enough, but we have to figure out how to match the same condition on the api side (eg set required based on another fields value)

**Comment by Kematia** [comment]
Ok, I'll work on a custom implementation for the time being then!
I'm glad that it's being worked on, can't wait to see the official implementation :)

I'll work only on the app side for now, I don't mind the fields existing in the API (as NULL I guess). It would be nice to have in the future though.

**Comment by dgram** [comment]
hey,

because of our use case, we are actually think also about the conditional fields.

Our use case is, we have multiple types of marketing messages. i.e.
- social-media: facebook post
- newsletter
- offline mailing

all of the marketing messages have the same main fields but every type have additional fields. in our case we only need to search in the main fields, the additional fields will only be a data-saver (to display them later).

we have decide to handle this case by a main-collection "marketing_message" with an field-interface "repeater" and limit them by 1 item.

To handle the interface we actually have an "type" field wheres the marketing-message type will be selected and depents on the type we hide/show the repeater-fields (actually by js/css).

I think it would be nice to handle this case also by the conditional interface fields, what do you think? @Kematia @benhaynes @rijkvanzanten 

regards, daniel

**Comment by rijkvanzanten** [comment]
Yeah I agree. Combining a relational repeater with conditional fields should give you all the flexibility you're looking for

**Comment by Kematia** [comment]
> Yeah I agree. Combining a relational repeater with conditional fields should give you all the flexibility you're looking for

Is there a relational repeater? I can't see it - I was looking at #1996 but I can't understand if it was implemented.

**Comment by rijkvanzanten** [comment]
Not yet, but it will be very similar to the repeater we already have, except for the fact that it will pull it's field configuration from a related table (and save it's rows into that table)

**Comment by dgram** [comment]
is the issue work in progress? if yes, is there a branch or fork to see the state? i'm interested in helping implementing the feature.

**Comment by rijkvanzanten** [comment]
There's no coding done as of yet @dgram

**Comment by tspvivek** [comment]
Just for people who want to use before the relational fields is added in v9/v10, I have created a new interface in below repo.
[https://github.com/tspvivek/directus-conditional-fields]("https://github.com/tspvivek/directus-conditional-fields")
