### ISSUE TITLE
Interface: Validation settings for Numeric

### ISSUE THREAD

**Issue by benhaynes** [directus/app#766]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Add additional validation settings to numeric interface
### :+1: = 1
*Created 10 months ago by @rijkvanzanten*
 

-----
### @rijkvanzanten – :+1: (10 months ago)
Min, max, step, decimal number ... for instance

**Comment by benhaynes** [comment]
Could probably just be the global field regex... but we should have that regex be a dropdown/input with common options before we close this. OR we could add additional validation to the interface options... either way.

**Comment by benhaynes** [comment]
This should NOT be field-level validation, these should be interface options.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
