### ISSUE TITLE
Interface: Map / Address

### ISSUE THREAD

**Issue by benhaynes** [directus/app#769]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Add a new map / address interface
### :+1: = 2
*Created 9 months ago by @rijkvanzanten*
 

-----
### @rijkvanzanten – :+1: (9 months ago)
Currently if you want to have an address in Directus we show several fields sequentially, like this:

```
-----------------
[Address]
-----------------
[Address 2]
-----------------
[City]
-----------------
[State]
-----------------
[zip]
-----------------
[country]
-----------------
```

This is functional, but certainly could be optimized from a UX perspective. It's also a common field-set making this improvement a "big deal". Ideally we would want something like this in a single Interface:

```
-----------------
[Address]
[Address 2]
[City] [State] [zip]
[country]
-----------------
```

But the problem is that Directus has a 1:1 mapping with the database – so the intention of an interface is to save to a (single) column. So while we could save the entire address concat'd into a TEXT column, that seems icky.

If we could we create an address interface that "maps" to other columns – we would have a huge improvement! Let's use this ticket to brainstorm how best to handle this (and similar optimizations)... and hopefully get a new Interface out of it!

This has moved over from GitHub issue #1385

**Comment by rijkvanzanten** [comment]
Interfaces can set the value of another interface by using the `setfield` event:

```js
this.$emit("setfield", { field: "another-field-name", value: "the new value" });
```

**Comment by benhaynes** [comment]
Duplicate of: https://github.com/directus/app/issues/821

Also, 90% of this ticket can be resolved with the new grid layout: https://github.com/directus/app/issues/773
