### ISSUE TITLE
Add dot notation for Visible Columns in M2M / M2O relations

### ISSUE THREAD

**Issue by benhaynes** [directus/app#770]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Add dot notation for Visible Columns in M2M / M2O relations
### :+1: = 4
*Created 9 months ago by @rijkvanzanten*
 

-----
### @rijkvanzanten – :+1: (9 months ago)
Expected Behavior
Showing specific properties of a related table with dot notation eg. airport_departure.name

Actual Behavior
when adding the visible columns in a m2m relationship there is no way to access the properties within the related column, to show them in the m2m table, always the id gets shown

Steps to Reproduce
add a m2m relationship
set the visible column to a specific property of the related table
see the error, as we can only access properties within the main table right now.
bildschirmfoto 2017-09-17 um 22 27 23

 

-----
### @rijkvanzanten – :+1: (9 months ago)
Original GH issue: https://github.com/directus/directus/issues/1827

 

-----
### @drewknab – :+1: (7 months ago)
This seems pretty vital, all things considered.

 

-----
### @daniel-upzzle – (6 months ago)
I've changed this to see 2nd degree relational fields value as desired: https://github.com/daniel-upzzle/directus/pull/1/files

**Comment by rijkvanzanten** [comment]
This has been implemented in the `fields` param!
