### ISSUE TITLE
Show users editing current item

### ISSUE THREAD

**Issue by benhaynes** [directus/app#771]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Show users editing current item
### :+1: = 2
*Created 9 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (9 months ago)
Optional section in right info-pane on Item Detail page. IF there are multiple people editing the same item it throws the alert and then shows this section listing all users on this page.

**Comment by rijkvanzanten** [comment]
This has been implemented in v7 🎉

**Comment by benhaynes** [comment]
Do we want a persistent message? I'm thinking more about the Google Docs avatars that show how many people (and who) are editing with you.

**Comment by benhaynes** [comment]
Let's add a list of "Users on this page" to the top of the Item Detail Info Sidebar.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
