### ISSUE TITLE
Page: API Data Ingestor

### ISSUE THREAD

**Issue by benhaynes** [directus/app#772]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# API Data Ingestor
### :+1: = 2
*Created 9 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (9 months ago)
An extension that provides an easy way to dynamically pull in external data (primarily through third-party APIs) with an intuitive GUI. Each ingestion point would have the following options:

* Title
* Frequency (30s, 2h, 1d, etc)
* Date column
* API endpoint
* Data Mapping (response to column)

### Example
You could have Directus pull in GitHub stars from a public repo every day (stored in the database).

**Comment by rijkvanzanten** [comment]
This would mean that the interface has a hook that has to fire from a CRON job. I'm not sure what the application can do to make this happen..

@benhaynes ?

**Comment by benhaynes** [comment]
I was not thinking this would be an interface but maybe a Page or some sort of hook? I think we have a ticket somewhere for setting up tasks to run from a Cron job... And this seems like it would be related.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
