### ISSUE TITLE
Slug should check for uniqueness

### ISSUE THREAD

**Issue by benhaynes** [directus/app#774]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Check if value exist and add +1 in slug
### :+1: = 2
*Created 9 months ago by @RudolfFussek*
 

-----
### @RudolfFussek – (9 months ago)
Hey,

I have a problem. When I generate a article and the slug is setting by the title and I have two articles white the same title the slug don't see it?

Exaple:

Title => Hello boys! Slug => hello-boys

Another Exaple:

Title => Hello boys! Slug => Hello-boys-1 <= The 1 because it already gives the article with the Slug.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
