### ISSUE TITLE
Shorter user names

### ISSUE THREAD

**Issue by benhaynes** [directus/app#775]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Shorter user names
### :+1: = 1
*Created 9 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (9 months ago)
Check across all user's names and display the shortest unique version in the app:

eg: `Ben` or `Ben H.` or `Ben Haynes`

**Comment by rijkvanzanten** [comment]
Do we always want to show the shortest version?

I think we should have a name-shortener function (like [`short-name`](https://www.npmjs.com/package/short-name), but more extended) that supports multiple "shortening types".

It could work like this:

```js
shortenName("Rijk van Zanten", "first-name"); // "Rijk"
shortenName("Rijk van Zanten", "medium"); // "Rijk v.Z."
```

Or maybe it could work based on a "preferred length":

```js
shortenName("Rijk van Zanten", 5); // Rijk
shortenName("Rijk van Zanten", 10); // Rijk v.Z.
```

_Yeah, Dutch names that use a ["tussenvoegsel"](https://en.wikipedia.org/wiki/Tussenvoegsel) are going to suck to implement_ 🙃

**Comment by benhaynes** [comment]
Yeah, I agree it should be a global option... but when on I think it would be dynamic. If there are two Bens... then it uses `Ben H.` and `Ben P.`... if they have the same last name letter then it goes to the full name. Could even handle complete duplicate names somehow.

I don't think we want to format all as "First Name" though... the dynamic option handles that, but updates as your team grows too. I'd say: Full Name or Dynamic Short Name are the two options (toggle).
