### ISSUE TITLE
Custom logo on login screen

### ISSUE THREAD

**Issue by benhaynes** [directus/app#777]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Custom logo for login screen
### :+1: = 3
*Created 8 months ago by @vtmx*
 

-----
### @vtmx – :+1: (8 months ago)

It would be nice to have the custom logo shown on the login page

**Comment by rijkvanzanten** [comment]
We can add a `loginImagePath` (or some other name) key to the `config.js` file that the user can use to provide the URL for the login image. The config file is loaded before the application is, so we can use that value to render another logo on the login page.

**Comment by rijkvanzanten** [comment]
The logo is here:

https://github.com/directus/app/blob/1e936361878ed4c39b3579be8b4e79ee2b6d902d/src/routes/login.vue#L8

We would add that option to the config file in here:

https://github.com/directus/app/blob/1e936361878ed4c39b3579be8b4e79ee2b6d902d/public/config_example.js#L3

And use it by getting the value out of:

```js
window.__DirectusConfig__
```

**Comment by benhaynes** [comment]
Wouldn't it be better to include this in the API so it's consistent across the instance no matter which app you log in from?

I see it working like SSO... it fetches and updates when you select an API.

**Comment by benhaynes** [comment]
I think the best way to approach custom logos (in terms of design and supporting using them in the most places) is to keep them **square**. Most apps/services these days use a square logo, and this make it easier to use in "landscape" or "portrait" modes.

Do we want to define these as raster or vector? Background or transparent? White, Darkest-Gray, or anything? I think that white vector would be ideal... but is requiring vector acceptable for most clients/projects?

Also, square works better with the prototype v8 design:

![directus 8](https://user-images.githubusercontent.com/522079/50564506-5427ee00-0cf3-11e9-98da-baf62a148e4e.png)

Ref: https://github.com/directus/app/issues/1225

**Comment by rijkvanzanten** [comment]
> I think that white vector would be ideal

Also, in your example, a white vector fits on the dark gray bar. This bar however could be any color. 

The login screen background color should match the color of the gray sidebar so the logo fits no matter what.

**Comment by benhaynes** [comment]
That's why I like vector... we could write some CSS to convert paths to different colors (although then we need them inline). I don't mind having the login logo being contained inside a darkest-gray rounded square if needed. So I still think the global asset should be white.

**Comment by rijkvanzanten** [comment]
> we could write some CSS to convert paths to different colors (although then we need them inline)

That's very hard if it's a separate file hosted somewhere.

> I don't mind having the login logo being contained inside a darkest-gray rounded square if needed. So I still think the global asset should be white.

The nice thing here is that it's the user who configures the theme _and_ the custom logo. EG if the sidebar is changed to white, the user can upload a logo that's dark. We still know that the logo will only show up on the same color (sidebar bg)

**Comment by rijkvanzanten** [comment]
Closed in favor of #1525
