### ISSUE TITLE
Layout: Audio Player Listing

### ISSUE THREAD

**Issue by benhaynes** [directus/app#778]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Audio Player Listing
### :+1: = 1
*Created 8 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (8 months ago)
A custom Item Listing layout view that is basically a table listing view with a few tweaks:

* There's a fixed player control bar at the bottom of the page
* It comes with an ALIAS interface for playing audio files (pauses any other playing files)
* It has options to map fields for: album art, track title, artist name, thumbs up/down, etc

**Comment by rijkvanzanten** [comment]
😍

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
