### ISSUE TITLE
Table and field name translations

### ISSUE THREAD

**Issue by benhaynes** [directus/app#779]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Table and field name translations
### :+1: = 1
*Created 7 months ago by @MarcinKuder*
 

-----
### @MarcinKuder – :+1: (7 months ago)
Please add an ability to translate table names and field names. This would make it consistent with other UI translations.

 

-----
### @diegogurpegui – (6 months ago)
Related to: https://request.getdirectus.com/r/116

**Comment by benhaynes** [comment]
This is possible in v7! schema names (column/table) can now be renamed or translated

**Comment by rijkvanzanten** [comment]
Ref #422

**Comment by Chris533** [comment]
Hi, how to translate the table name and field name in v7? Rename is working, but I can't translate them, searched and tried more than 3 hours, could you show the detailed step?  Thanks.  @benhaynes

**Comment by benhaynes** [comment]
I believe it's as easy as `directus_fields.translations` and `directus_collections.translations` ... then having a user's `locale` set to one of the supported languages you add:

```json
{
  "en-US": "My Collection",
  "nl-NL": "Mijn Collectie"
}
```

I have added this to the upcoming Docs rebuild... let me know if it's NOT working and we'll look into it!

**Comment by iidroj** [comment]
> I believe it's as easy as `directus_fields.translations` and `directus_collections.translations` ... then having a user's `locale` set to one of the supported languages you add:
> 
> ```json
> {
>   "en-US": "My Collection",
>   "nl-NL": "Mijn Collectie"
> }
> ```
> 
> I have added this to the upcoming Docs rebuild... let me know if it's NOT working and we'll look into it!

I just added a translation to the collections and that seems to work.
But i tried the same with some fields but that doesn't seems to work

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/app/issues/422
