### ISSUE TITLE
Interface: Timeline

### ISSUE THREAD

**Issue by benhaynes** [directus/app#782]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Timeline Interface
### :+1: = 2
*Created 7 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (7 months ago)
An interface with customizable nodes on a line. Each node can be labeled. The Value determines where in the timeline is activated... with completed nodes in the Primary color and incomplete nodes in gray. By default this would be a read-only interface but this could be overridden.

### EXAMPLE:

```
  ⬤=======⬤==========⬤---------◯
Sent    Delivered    Opened    Clicked
```

**Comment by benhaynes** [comment]
There should also be an option to make this vertical.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
