### ISSUE TITLE
Interface: DATETIME save as UTC

### ISSUE THREAD

**Issue by benhaynes** [directus/app#784]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# UI: DATETIME save as UTC
### :+1: = 4
*Created 7 months ago by @rijkvanzanten*
 

-----
### @rijkvanzanten – :+1: (7 months ago)
Right now, the DATETIME interface saves whatever value is passed, without keeping the user's timezone in mind. It would be very convenient if the interface could automatically save the value in UTC and show it in the user's timezone

**Comment by rijkvanzanten** [comment]
@WellingGuzman Doesn't the API do this right now?

**Comment by rijkvanzanten** [comment]
This should be an option for the datetime interface.

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman — can we get some closure on this issue? What else needs to happen for this to be wrapped up?

**Comment by benhaynes** [comment]
All set...

https://github.com/directus/api/blob/master/extensions/core/interfaces/datetime/meta.json#L41-L46
