### ISSUE TITLE
Select/deselect all in white-/blacklisting permissions

### ISSUE THREAD

**Issue by benhaynes** [directus/app#785]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Select/deselect all in white-/blacklisting permissions
### :+1: = 1
*Created 6 months ago by @rijkvanzanten*
 

-----
### @rijkvanzanten – :+1: (6 months ago)
I have a couple of tables containing 50+ columns. To restrict access to some users (e.g. restful consumers), it would be very convenient to have an option to 'deselect all' (or 'select all') fields in the group's rights settings page. - For both: whitelisting and blacklisting.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
