### ISSUE TITLE
Layout: Kanban View

### ISSUE THREAD

**Issue by benhaynes** [directus/app#786]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Kanban style Listing View
### :+1: = 2
*Created 6 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (6 months ago)
7.0 baby!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
