### ISSUE TITLE
Layout: Gantt View

### ISSUE THREAD

**Issue by benhaynes** [directus/app#787]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Gantt Style Listing View
### :+1: = 1
*Created 6 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (6 months ago)
7.0 baby!

**Comment by rijkvanzanten** [comment]
For others landing here not knowing what Gantt is, it's one of these:

![Gantt chart](https://cacoo.com/assets/site/img/templates/inner/schedule.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
