### ISSUE TITLE
Public User Registration

### ISSUE THREAD

**Issue by benhaynes** [directus/app#788]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# anonymous register user
### :+1: = 1
*Created 5 months ago by @lastlink*
 

-----
### @lastlink – :+1: (5 months ago)
ability to enable disable public registering of users with a default permission grouped assigned to them.

**Comment by benhaynes** [comment]
I don't mind this idea (though it's not the purpose of Directus). It seems like this would be based on the public group permissions for `directus_users` CREATE

**Comment by PurpleEdge2214** [comment]
Is it really just a question of where public user information is kept? I don't particularly like the Wordpress system where public users get lumped into the same data files as Administrators and contributors.

I doubt Directus public users will ever have access to the Directus App?

So providing storage of public user info in the Directus users files just confuses the intention of the Directus App, in my opinion.

**Comment by lastlink** [comment]
@benhaynes I've heard many say this isn't "the purpose of Directus" before. I thought Directus supposed to be a decoupled cms and "Pure, decoupled content". What do you think when you think of the purpose of Directus. Thanks!

**Comment by PurpleEdge2214** [comment]
@lastlink I was/am confused by the purpose of the Directus App.

As a total newcomer, the App seems to be intended for Developers to develop the database rules, and for site Admins and contributors to provide content for a site. i.e. Public contributors are managed by the front-end and database API.

But I'm still open-minded if I'm wrong.

**Comment by benhaynes** [comment]
That's true @lastlink  – I can't say Directus is truly unopinionated and then turn around and say something goes against its purpose. 

I see `directus_users` as the users of Directus (😉), which would have certain access to the API and the Admin App (this could be argued). I would assume that other _external_ apps would create their own `users`, `members`, `clients`, etc tables for their own needs. However, I recognize that many Admins see `directus_users` as a good place for their users since it already has auth, permissions, and all the other setup.

One direction would be to add an option to *Disable App Access* for certain roles. Then you could use the core users for more global purposes. But as @PurpleEdge2214 mentioned, this seems to mix internal/external data more than I'd like. But... no assumptions! :)

Another option would be to make it easier to replicate the `directus_users` schema/functionality quickly... so Admins can setup their own (isolated) users with the same benefits. But I don't know how this would work with permissions (which are tied to internal users/roles now).

Thoughts?

**Comment by lastlink** [comment]
Are there use cases where people have actually used separate user tables for clients separate from directus_users?

**Comment by benhaynes** [comment]
We (RANGER Studio) have built many applications like this. All on v6, but the principle is the same. Sometimes a client wants/needs a different type of auth, but usually it's a matter of separation of concerns.

**Comment by PurpleEdge2214** [comment]
@lastlink - I'm trying to build a business directory now where external users create their own page for their business and manage it. I wasn't sure whether Directus intended, or allowed, this to be done in the backend. The existing Wordpress system used an external frontend editor for this content, but all users get added to the Wordpress users table which is an admin nightmare when you have a couple of hundred/thousand users.

**Comment by rijkvanzanten** [comment]
> but all users get added to the Wordpress users table which is an admin nightmare when you have a couple of hundred/thousand users.

But it _does_ mean it takes care of the auth flow and permissions for you 🤔

What's the worst part about having those users intertwined with the "regular" users? Directus luckily doesn't have the dumpsterfire of a DB structure as WP so that might alleviate part of the problem already?

**Comment by PurpleEdge2214** [comment]
Yeah, I'm open minded about it. My objection is precisely as you say - Wordpress is a big ugly dog, that runs super slow and the database, as you say is a sophisticated design that is nigh on impossible to navigate without using the Wordpress methods.

The nice thing about Directus is that we have the option of keeping external users - external. Albeit with the need to add our own management. I don't know enough about Directus yet, I was planning to go external, maybe using the directus_users table is worth considering.

**Comment by benhaynes** [comment]
I'm going to keep this alive since it's been brought up quite a bit in community discussions. We already have a Registration page (from Cloud) designed and coded... but we would need to take the time to integrate this into Directus Core. 

Some things to consider:

* Do we want email validation?
* Do we want to allow this registration with SSO too?
* Do we want to tie this to the Public role's  `CREATE directus_users`? If we do then that might remove the ability to validate email, etc

**Comment by rijkvanzanten** [comment]
Another idea @benhaynes:

* Only accept emails based on a validation (eg only accept `@rngr.org` emails)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by westhouseit** [comment]
@benhaynes any chance you could create a feature branch and include any existing code for this so I can contribute?

**Comment by westhouseit** [comment]
Actually, I've just realized that I'm posting in the wrong project since this is for the App and the functionality would need to be properly in place in the API first.

**Comment by benhaynes** [comment]
Hey @westhouseit — we don't have any code for this, but the new v8 (coming in a few days) does take this into consideration. So a PR on the `develop` branch would be the best way to move forward with these changes. Below is the rough design we have... that should be pretty easy to implement in the new v8 codebase (on the front-end, at least).

![Directus 8 – Register](https://user-images.githubusercontent.com/522079/69448806-5e961080-0d27-11ea-8fe1-5baad2ddb9bf.png)

Some notes: We may or may not want to include the project dropdown on this form. Not sure. We would need to add an admin option for the default User Role and default Status for new users.

Open to discuss further!

**Comment by rijkvanzanten** [comment]
> We would need to add an admin option for the default User Role and default Status for new users.

This is crucial to have for this to work. The API should also validate this when creating new users from the public role. Currently, if you open up `create` to the public role people can register themselves as admin which is no good of course

**Comment by rnwzd** [comment]
Hi,
this feature would be essential for my purposes. I would like to know if and when it will implemented and if there is any way to contribute

**Comment by benhaynes** [comment]
There are a bunch of options available, from PRs to financially commissioning the feature:

https://docs.directus.io/getting-started/supporting-directus.html#financial-support

**Comment by mariorojas** [comment]
Hi @benhaynes ! I wonder if it would be a good practice to use Directus only as a data manager for my own `users` & `roles` tables, and a Java API secured with OAuth for that users requests.

![image](https://user-images.githubusercontent.com/386966/75635447-b8865c00-5bdb-11ea-8067-e9fea84cbb1a.png)

**Comment by benhaynes** [comment]
You can (and it should work just fine) — but it hasn't been designed for that (yet), so it's a bit "proceed at your own risk".

**Comment by mariorojas** [comment]
So what would be a good way to use that custom tables

> You can (and it should work just fine) — but it hasn't been designed for that (yet), so it's a bit "proceed at your own risk".

So what would be a good way to use that custom users & roles tables with Directus API? I mean, taking advantage of restrictions.

**Comment by rijkvanzanten** [comment]
>  taking advantage of ootb restrictions.

Directus uses directus_users and directus_roles (/ permissions) for its API ACL and restrictions. If you want to use the ootb restrictions, you'll have to use those collections to manage your users.

**Comment by kauaicreative** [comment]
I really wanted to use Directus. But I could not find a clear path for registering and logging in users via api. Ended up using Strapi which is clearly designed for this.

**Comment by rijkvanzanten** [comment]
> But I could not find a clear path for registering and logging in users via api

@kauaicreative You mean _Create a User_

https://docs.directus.io/api/users.html#create-a-user

and _Authenticate_

https://docs.directus.io/api/authentication.html#retrieve-a-temporary-access-token

?

**Comment by vkathirvel** [comment]
@rijkvanzanten I guess what @kauaicreative meant was the lack of a public API path to register as a user.

Strapi equivalent: https://strapi.io/documentation/v3.x/plugins/users-permissions.html#registration

I suppose, in Directus, https://docs.directus.io/api/users.html#create-a-user you've got to run this using a secure API token and not exposed publicly? If so, I understand the reasoning - I wouldn't want a public endpoint that bots can hit and load my database with fake users.

**Comment by rijkvanzanten** [comment]
As far as I can tell, that's a public endpoint to create a new user right? AFAIK, you can achieve the same thing by allowing the public role to create users + setting a default role for new users

**Comment by benhaynes** [comment]
In any event, "Public User Registration" via a dedicated endpoint/feature is coming in v9!

**Comment by vkathirvel** [comment]
Thanks @benhaynes 

I think that'll be a game changer. Like I said, I understand why it probably was not part of Directus in the past. Such an endpoint will require some level of SPAM block to prevent bots from creating fake accounts.

**Comment by kauaicreative** [comment]
@benhaynes that's great! I will keep a lookout.
Strapi includes a secondary user system, the "Users & Permissions" plugin, which is separate from the admin panel user system. It's pretty turn key.

![image](https://user-images.githubusercontent.com/127033/93786298-25575700-fbfd-11ea-938c-8df4bada6312.png)

**Comment by benhaynes** [comment]
Awesome, thank you both! Here's the v9 discussion:

https://github.com/directus/next/discussions/335
