### ISSUE TITLE
Hooks for adding custom code to app for design customisation

### ISSUE THREAD

**Issue by benhaynes** [directus/app#789]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Hooks for adding custom code to app for design customisation
### :+1: = 1
*Created 5 months ago by @treechime*
 

-----
### @treechime – :+1: (5 months ago)
Similar to WordPress' enqueue system for CSS and scripts, would allow for adding code to the header and footer of the template to override the default styles of the app.

I see remnants of this in the current code base (6.x) like getCusomFooterHTML() & getCSSFilePath() in index.php but they don't seem fully implemented.

**Comment by rijkvanzanten** [comment]
That's in there!

There's a `script.js` and `style.css` file that's being loaded that the user can use to override.. anything really

**Comment by benhaynes** [comment]
Is this documented? If not, we need to keep it open...

**Comment by rijkvanzanten** [comment]
@benhaynes https://github.com/directus/docs-v7/issues/8 😉

**Comment by benhaynes** [comment]
Thanks! It's good to at least keep a trail from here to the end docs for those who search for this within closed ticket. 👍
