### ISSUE TITLE
Two Factor Auth Option

### ISSUE THREAD

**Issue by benhaynes** [directus/app#790]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Two Factor Auth Option
### :+1: = 1
*Created 5 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (5 months ago)
In 7.x

**Comment by rijkvanzanten** [comment]
Moved to https://github.com/directus/api/issues/404

_hehe, 404_
