### ISSUE TITLE
Interface: OSM-option for map

### ISSUE THREAD

**Issue by benhaynes** [directus/app#792]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# OSM-option for map interface
### :+1: = 2
*Created 4 months ago by @aiomaster*
 

-----
### @aiomaster – :+1: (4 months ago)
I just need an interface to select a point on a map. The current map interface does this, but you need a Google API key and not everyone likes this. Besides I want to show the marker on an Openstreetmap in the frontend and it would be good to see the same map in the backend.

It would be cool to have an option switch to OSM. One could use leaflet for the map JS http://leafletjs.com/ and if needed nominatim for geocoding https://nominatim.org/ We should separate these two things and have the possibility to use a self hosted geocoder.

**Comment by rijkvanzanten** [comment]
The map interface uses `leaflet`!
