### ISSUE TITLE
Make junction tables & relational data interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#795]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Make junction tables & relational data interface
### :+1: = 1
*Created 3 months ago by @ColinMcNeil*
 

-----
### @ColinMcNeil – :+1: (3 months ago)
Currently, the only way to add associative data to a junction table (M2M) is to memorize the IDs of both rows and find the proper associated row in the junction table. There needs to be a way to input associative data in a junction table when you create the data. For example, we have a projects and people that are M2M related. There should be a way to specify a person's role on each project in the junction table as soon as we link them.

**Comment by benhaynes** [comment]
@rijkvanzanten I don't think we have any relational interfaces that require you to know the ID anymore... you can always see a title-format from related fields. Right?

**Comment by rijkvanzanten** [comment]
> There should be a way to specify a person's role on each project in the junction table as soon as we link them.

I don't think that's the core issue here. I feel like where talking about adding a field to the junction table in the M2M interface

**Comment by ColinMcNeil** [comment]
That is possible, but in the M2M junction table the only displayed fields are IDs. It's non-starter for my clients to memorize which ID is which.

**Comment by benhaynes** [comment]
Couldn't two `m2o` interfaces be added to the junction table's `person` and `project` fields to solve this? That would give you the ability to decide which relational data is shown on the junction table.

Right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
That sounds about right @benhaynes
