### ISSUE TITLE
Project Auto-Docs

### ISSUE THREAD

**Issue by benhaynes** [directus/app#797]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Project Auto-Docs
### :+1: = 1
*Created 2 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (2 months ago)
An App page that provides dynamic API Docs for the current project schema. Could be provided to employees as an instant way to share actual API Reference.

Basically this would be the same as our current API Reference... but would dynamically generate the ACTUAL endpoints based on the schema. Could be an extension or a page within Settings.

**Comment by benhaynes** [comment]
1. We create a "Docs Template" in markdown that uses `{{value}}` to inject dynamic names
1. The "Auto-Docs" module uses:
    * project URL
    * collections (name and description)
    * fields
    * items (for examples)
    * custom endpoints (?)
1. Generates all endpoints as markdown
1. Displays formatted version on page

-----

_Get Items_
## **GET** `/_/collections/articles`

Get an array of {{collection_name}}. {{collection_description}}

```
http://api.example.com/_/collections/articles?token=123456789
```

[See Examples](#)

### Authentication

✓ Auth Protected — [Read more](#)

### Parameters

| param  | type  | default | required |
|--------|---------|---------|----------|
| [fields](#) | csv     |         |          |
| [limit](#)  | integer | 200     |          |
| [meta](#)   | integer |         |          |
| [offset](#) | integer | 0       |          |
| [single](#) | bool    | 0       |          |
| [sort](#)   | csv     | id      |          |
| [status](#) | csv     |         |          |
| [filter](#) | array   |         |          |
| [lang](#)   | csv     |         |          |
| [q](#)      | string  |         |          |
| [groups](#) | csv     |         |          |

### Response (JSON)

`200` — ...

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
