### ISSUE TITLE
Sequential Fields – Item Creation Option

### ISSUE THREAD

**Issue by benhaynes** [directus/app#798]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Sequential Item Creation Option
### :+1: = 1
*Created 2 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (2 months ago)
A collection option that forces users to complete inputs sequentially. Once a field passes validation, it shows/enables the next field. Save is only enabled once all fields are complete.

This only happens on CREATE, not UPDATE... unless there are missing/required fields.

**Comment by rijkvanzanten** [comment]
This can be setup using conditional fields #737 #763

**Comment by benhaynes** [comment]
It could, but that would require EVERY interface to have a conditional option. Are we planning on implementing field conditions globally or at the interface option level?

If the latter, I recommend moving this request to a global (collection-level) feature.

**Comment by rijkvanzanten** [comment]
Field conditions are going to be a per-field setting (not tied to the interfaces)

**Comment by benhaynes** [comment]
duplicate of https://github.com/directus/app/issues/763
