### ISSUE TITLE
Data Migration Tool

### ISSUE THREAD

**Issue by benhaynes** [directus/app#799]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Data Migration Tool
### :+1: = 1
*Created 4 weeks ago by @dynamikapps*
 

-----
### @dynamikapps – :+1: (4 weeks ago)
If the person managing the client app does not have the technical background to migrate a DB and would like to move data from a table/collection/item from let say a staging envr to a prod envr then it would help to have that feature. Or even if they would like to move just the schema structure (ei. person table - name, address, age, postal etc...) from one envr to another would be nice as well.

Including general Import/Export and different formats (JSON, SQL, XML, CSV, etc)

Thanks

**Comment by rijkvanzanten** [comment]
Duplicate #711 #765
