### ISSUE TITLE
Print Media CSS

### ISSUE THREAD

**Issue by benhaynes** [directus/app#800]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Print Media CSS
### :+1: = 1
*Created 3 weeks ago by @benhaynes*
 

-----
### @benhaynes – :+1: (3 weeks ago)
On Tabular Items and Item Detail page. Hides sidebars/header and adjust colors/spacing.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
