### ISSUE TITLE
Interface: M2M item list names

### ISSUE THREAD

**Issue by benhaynes** [directus/app#801]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# M2M item list names
### :+1: = 0
*Created 5 days ago by @Elvanos*
 

-----
### @Elvanos – (5 days ago)
I suggest adding a possibility to display one field (or more) of all items in the M2M relation when on the list of items in a table. Right now you only see the amount of them and their count (example: 1 item).

It would be very helpful to be able to see what is actually in the list - for example, if I have 10 actors and 20 plays and they are paired criss-cross. I will get to see that an actor belongs to 10 items, but I dont know which plays unless I click on it. It would be incredibly helpful to have this available.

EDIT: I made a very quick and dirty band-aid change to minified UI js file to showcase what I had in mind:

https://pastebin.com/4ZSBn2pp

It basically runs through all instances of items in the JS object and checks if a field called "name" exists and it does it populates the output string with the values. If such a file doesnt exist, it goes back to the standard 'X-items' pattern.

I would personally suggest for this field to either be manually pickable through UI or be hard-set as one of the selectable options when creating a new table (system_title, maybe?).

**Comment by rijkvanzanten** [comment]
This can be implemented pretty gracefully by adding a `displayTemplate` option that allows the user to enter a display template string that is used to render the value previews on hover of the item in the list

**Comment by benhaynes** [comment]
I think this is to adjust what is shown on the Layout (eg: tabular) page for relational items. Which currently just says: `4 Items`

**Comment by Elvanos** [comment]
@benhaynes Yes, this is exactly what I meant.

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/45256122-fe07f700-b35f-11e8-900d-d4f38e99827b.png)

This is what I came up with @Elvanos. Lemme know what you think 🙂

Closed in https://github.com/directus/api/commit/b6e6622870deac847bc437bda652931eec63af61

**Comment by Elvanos** [comment]
@rijkvanzanten This is exactly what I had in mind.

Just one question though: Will there be a setting/option to choose if these should show on a dropdown or directly, without hovering over?
Yea I am aware that could theoretically take A LOT more space, but sometimes space < quick info.

**Comment by benhaynes** [comment]
Hey @Elvanos – that could look pretty crazy, and I don't think we'd want to implement that in the Core codebase. You could update the interface to show that for your application though!

**Comment by Elvanos** [comment]
@benhaynes Pff.. I could try - it is the "build" script in the app's SRC files, right?

**Comment by benhaynes** [comment]
You would update the M2M interface (duplicate and make your own version). The docs for that are here: 

https://docs.directus.io/app/contributor-guide/interfaces.html#introduction

**Comment by Elvanos** [comment]
I will look at that, thanks!
