### ISSUE TITLE
Problem loading extensions

### ISSUE THREAD

**Issue by dshimkoski** [directus/app#804]
## Describe the Bug

If I run the prebuilt version of the app, I receive errors when attempting to load a collection. There are a bunch of messages saying "There was a problem loading the extension."

## Steps to Reproduce
1. Login to http://phpstack-67872-604914.cloudwaysapps.com (admin@example.com / password)
2. Go to Admin User > Admin Settings > Collections & Fields > Article
3. See error messages

I also tried to run the app locally using the latest from git via `npm run dev`, but upon logging in I received the message "No Extensions Found - Make sure you have the system extensions installed."

## Technical Details
- Device: Desktop
- OS: MacOS 10.13.6
- Browser: Chrome 68.0.3440.106

**Comment by rijkvanzanten** [comment]
Hey @dshimkoski! The "No Extensions Found" is expected, as you have to build the extensions from source as well. 

Did these errors pop up when using the demo SQL or the installer empty sequel?

**Comment by rijkvanzanten** [comment]
It seems like there aren't any extensions installed. In version 7.0.0-rc.3 and higher this will cause the application to deny service. I'm assuming this is because you've installed by building it from source, but forgot to build the extensions. Please checkout these docs for all the install steps 🙂

**Comment by rijkvanzanten** [comment]
Lemme know if that fixed it for you. If not, we'll reopen and continue investigating 🕵️

**Comment by jjoe64** [comment]
@rijkvanzanten which extensions are you talking about? I installed the php extensions mentioned in the doc, but it does not help:

`
docker-php-ext-install pdo pdo_mysql curl gd fileinfo mbstring
`

**Comment by jjoe64** [comment]
related to #849

**Comment by benhaynes** [comment]
Ahh, I see the confusion. @jjoe64 – you are referencing PHP Extensions, but @rijkvanzanten is talking about Directus Extensions (Interfaces, Layouts, etc).

https://docs.directus.io/api/contributor-guide/install-dev.html#_3-install-the-npm-dependencies-of-and-build-the-extensions

This is indeed a Documentation issue, since not all Docs are properly linked yet – but it won't be an issue when we have the "build" version ... hopefully later today.
