### ISSUE TITLE
API Selector Broken

### ISSUE THREAD

**Issue by benhaynes** [directus/app#805]
The API Selector (project switcher) is broken, it shows the correct API in the text, but the dropdown is incorrect.

![screen shot 2018-09-10 at 3 09 55 pm](https://user-images.githubusercontent.com/522079/45318666-9e4e4f00-b50b-11e8-81db-0a9883736c36.png)
![screen shot 2018-09-10 at 3 10 02 pm](https://user-images.githubusercontent.com/522079/45318674-a0b0a900-b50b-11e8-858e-aa5eb33fa310.png)

**Comment by rijkvanzanten** [comment]
It's working on my end as expected. Are there any more detailed steps to reproduce?

<img width="440" alt="image" src="https://user-images.githubusercontent.com/9141017/45323766-2e939080-b51a-11e8-9568-01defe0c8445.png">

<img width="175" alt="image" src="https://user-images.githubusercontent.com/9141017/45323767-305d5400-b51a-11e8-90dd-02ae4d3fc74d.png">

**Comment by benhaynes** [comment]
Of course now I can't reproduce it. 

If there's anything I hate more than bugs it's intermittent bugs. I didn't pull or change anything, so clearly there's an issue somewhere when you take some specific steps. I just don't know what they are.

Something between the App project switcher, the login project switcher, and the dropdown... maybe something to do with the local storage variable expiring or something totally different. I'll re-open if it happens again.

Ugh.

**Comment by rijkvanzanten** [comment]
Turns out the api key refresh made the `env` reset to `_`, which in turn removed the `env` from the URL tried in the project switcher, which caused the HTML to get a wrong value, which resulted in the select defaulting to the first item. Wonders of the web ✨
