### ISSUE TITLE
Interface Debugger Option Comments Not Working

### ISSUE THREAD

**Issue by benhaynes** [directus/app#815]
The comments for interface options are not showing up in the interface debugger.

![screen shot 2018-09-11 at 5 59 55 pm](https://user-images.githubusercontent.com/522079/45390242-81d61380-b5ec-11e8-9d36-8259e5da4a14.png)

**Comment by rijkvanzanten** [comment]
Existential question: if they were never added before, they're technically not broken. Does that make this an enhancement? 🤔

**Comment by benhaynes** [comment]
Ugh...

**Comment by rijkvanzanten** [comment]
The interface debugger will be phased out in favor of Storybook soon. This won't be fixed
