### ISSUE TITLE
Interface: Datetime – Split inputs

### ISSUE THREAD

**Issue by benhaynes** [directus/app#817]
We should split the single datetime input into two beside each other. There are odd things happening when changing dates/times (arrow keys) and it would look much better:

![screen shot 2018-09-12 at 3 46 34 pm](https://user-images.githubusercontent.com/522079/45449403-1b5ffc80-b6a3-11e8-92ad-2302f02b13e6.png)

**Comment by alex-gorovyi** [comment]
Does it make sense to combine existing Time and DateTime interfaces
and provide aggregated `DateTimePicker` interface?
What do you think?

**Comment by benhaynes** [comment]
I think we should combine the `date`, `time`, and `datetime` interfaces into one, and then use two inputs (date and time) that can be conditionally turned on/off depending on the datatype.

We should plan to use a 3rd party picker (unfortunately) since some major browsers don't yet support the HTML5 date picker.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
