### ISSUE TITLE
Interface: Map – Geocode to address fields

### ISSUE THREAD

**Issue by benhaynes** [directus/app#821]
**Center Value**: Button to center current value on map (`Center`) should be just left of `Clear` button and only visible when there is a value.

**Field Mapping**: There should be options for which fields to map the lat/log too, and also address geocoding if we ever add that.

**Comment by benhaynes** [comment]
[The Map interface is working](https://github.com/directus/api/tree/master/extensions/core/interfaces/map) but I'll keep this open so we remember to add an option to geo-code an address and insert it into other fields. This will likely require an API key from some pay service, but ideally we can find some open source option. 

If there's no good OSS option then we can close this as complete.

**Comment by FrikanRw** [comment]
@benhaynes I would like to make this my first pull request for hacktober. I found OpenStreetMap`s Nominatim can be used to geocode an address [Nominatim wiki](https://wiki.openstreetmap.org/wiki/Nominatim) Is this what you intended?

**Comment by benhaynes** [comment]
Hey @FrikanRw – this seems like a perfect solution! And we would be very grateful to be your first hacktober PR. 😄 

@rijkvanzanten are you good with this library?

**Comment by rijkvanzanten** [comment]
LGTM!

**Comment by benhaynes** [comment]
Haha, I always thought you were saying: `Let's get this merged`... which doesn't make sense in this context.

**Comment by FrikanRw** [comment]
Still busy WIP, plan to finish it ASAP.

**Comment by benhaynes** [comment]
No problem, thanks for the update!

**Comment by FrikanRw** [comment]
@benhaynes  @rijkvanzanten 
I have a working API call on this [branch](https://github.com/FrikanRw/app/blob/Geocode-to-address-fields-%23821/src/geocode.js).

Not sure where to put it for you and if you want the data in a different format?

**Comment by FrikanRw** [comment]
@benhaynes  That makes more sense, I assumed that because the issue is on the app repo the feature should be added here. I will move the branch to a fork of the API repo and reference the pull request here.
