### ISSUE TITLE
Allow users to edit directus_* collection's fields

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#830]
This will allow the user to add / remove fields to/from directus_users for example.

Make sure to visually distinguish fields that are `locked` from fields that are editable.

**Comment by benhaynes** [comment]
Important!

**Comment by benhaynes** [comment]
This is also important for Cloud... otherwise there will be no way to extend these collections.

**Comment by denveloperj** [comment]
Is this still in the works?

**Comment by benhaynes** [comment]
Not actively, but once we have things stable we'll be back to adding new features like this.

**Comment by rijkvanzanten** [comment]
Important to note that the app will render the fields just fine if you add them to the db directly.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
