### ISSUE TITLE
Allow modifying auto increment

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#831]
It should only work for integer fields, and should be enabled by default for primary keys.

**Comment by benhaynes** [comment]
We just added "signed/unsigned"... let's add one more! @rijkvanzanten

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
