### ISSUE TITLE
Error when attempting to add an item to a collection

### ISSUE THREAD

**Issue by chrisgame** [directus/app#833]
## Describe the Bug
Once a collection is created with only default fields I am unable to add items to it.

## Steps to Reproduce
1. Create a new collection
2. Click on the collection in the sidebar
3. Click on the plus in the top right to add an item to the collection
4. See error in screenshot below

![image](https://user-images.githubusercontent.com/766429/45813904-d4d65780-bccb-11e8-9395-3146ae4fc924.png)

## Expected Behavior
I should be able to create a collection and add items to it.

## Screen Capture
![directus-collection-errors](https://user-images.githubusercontent.com/766429/45812864-f2ee8880-bcc8-11e8-8d36-516efdde9097.gif)

## Additional Context
This is occurring when attempting the same operation as https://github.com/directus/app/issues/698. Since this has been fixed I can get slightly further in the flow but i'm still unable to add an item to a collection.

If there is a way around this by editing data or code somewhere i'm happy to do that. I really want to test adding an extension of my own for a custom field type but so far I have been unable to get to the screen to add items to a collection.

## Technical Details
- Device: MacBookPro
- OS: MacOS 10.13.6
- Browser: 69.0.3497.92
- Directus App: 55e8339f0b70e9119d3e58b68cb9ed55e2f21370
- Directus API: 866dc7ef539a495698111e8ce35599c172c7283f

**Comment by Mu9tafa-Online** [comment]
Same issue here 😭😭
