### ISSUE TITLE
Item Detail Validation

### ISSUE THREAD

**Issue by benhaynes** [directus/app#834]
When you don't include a value in a required field, it should give a validation error and turn the field label `--danger`. Currently I just get:

```
We're having some trouble processing your request.. Please try again by refreshing this page. If the problem persists, please contact your system administrator.
```

And, that error should not have a double period 😉

**Comment by benhaynes** [comment]
Bonus points if the page scrolls to the first invalid field on the form! 🎁

**Comment by rijkvanzanten** [comment]
The app renders the actual error as returned by the API. The actual client side form validation is a new feature that will be added in the coming minor version (7.1.0)

**Comment by AntiCZ** [comment]
@rijkvanzanten Hello, I am not sure about rendering. I have tried the actual demo and error does not rise up if the field is required.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
