### ISSUE TITLE
Make Field Regex/Validation Available to Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#836]
When developing an interface, you may want to confirm the regex on the client side and perform a specific styling of the interface. Also, there should be a way for the interface to say "this is not valid" and force the form not to save.

EG: Password/Confirm do not match in `password` interface, we want to mark the field as invalid (before trying to save) and disable the save button.

**Comment by benhaynes** [comment]
Need this.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
