### ISSUE TITLE
Input max/min width/height

### ISSUE THREAD

**Issue by benhaynes** [directus/app#85]
Inputs should have min/max widths/heights. Example: An interface might enforce a max width so it's not "unusably" long.

![screen shot 2018-04-03 at 5 59 59 pm](https://user-images.githubusercontent.com/522079/38278244-43099fe8-3769-11e8-9722-30579bb8a4d2.png)

**Comment by rijkvanzanten** [comment]
Do we (either):

A. Let the interface enforce max-widths (no min-widths, needs to fit in filters too)
B. Have an edit-view wide max-width, so each interface within is forced to that max width (if it's set to 100% width to begin with, seeing it could also be 1/4, 1/2, or 3/4 of the width

**Comment by rijkvanzanten** [comment]
This has been implemented in #107
