### ISSUE TITLE
App logs back in after refresh at logout

### ISSUE THREAD

**Issue by benhaynes** [directus/app#856]
If you are logged in to 2+ browser tabs, and log out of one... you are not logged out of the other. In fact, if you refresh the one you you logged out of (showing the login screen) then it automatically logs you back in.

When you log out of one tab, it should log you out of all instances of that project.

Also, how would this work with two tabs open with two different connected APIs?

**Comment by rijkvanzanten** [comment]
> When you log out of one tab, it should log you out of all instances of that project.

This is not something we have support for right now. The API doesn't contain a list of blacklisted access tokens. As far as the API is concerned, as user isn't "logged in" (it's _stateless_), but instead has a valid key.

**Comment by benhaynes** [comment]
If they are each stateless, then why does it log me _back in_ when I refresh the one that logged me out? It seems as though each browser login/tab is not decoupled.

**Comment by rijkvanzanten** [comment]
That's where the `bug` label comes in 😅

**Comment by Nitwel** [comment]
Well, I tested it and for me, it does not happen anymore, so is this issue up to date?

**Comment by rijkvanzanten** [comment]
This has been fixed by #1139
