### ISSUE TITLE
Allow installing multiple API projects

### ISSUE THREAD

**Issue by benhaynes** [directus/app#857]
The App took me through the install process for the _first_ config below, but not for the second (once I already had a default set up). We need to add a way to add more projects (if the API allows it through the `/projects` endpoint.

```
'http://whatever.com/_/': 'Default',
'http://whatever.com/fresh/': 'Fresh Install'
```

**Comment by benhaynes** [comment]
Need this.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
