### ISSUE TITLE
Settings: Field Interface Options

### ISSUE THREAD

**Issue by benhaynes** [directus/app#858]
Right now all interfaces are stacked, no matter what. We should have these 2-up (two columns) to save space. Can we use a default Interface width for this? More are `2` wide, but some might need to be a full `4`.

![screen shot 2018-09-26 at 12 20 15 pm](https://user-images.githubusercontent.com/522079/46093890-8d960e00-c186-11e8-86f5-7753d19ae0b6.png)

**Comment by benhaynes** [comment]
Good improvement.

**Comment by rijkvanzanten** [comment]
How do you want to lay them out @benhaynes?

**Comment by benhaynes** [comment]
If we can avoid the full-width, then we can just grid them all in two flex columns. Code and WYSIWYG are the only ones I can think of that would benefit from the extra width. BUT those interfaces would both benefit from a "full-screen" option (WYSIWYG already has it)... so maybe two columns will work?

**Comment by benhaynes** [comment]
This seems very subordinate to the new 7.1 grid, let's close this and track things here:

https://github.com/directus/app/issues/1236
