### ISSUE TITLE
Install: Show Requirements

### ISSUE THREAD

**Issue by benhaynes** [directus/app#860]
Right now I had to check the Directus API Logs and do some digging/debugging/asking to see what was wrong... we need to present install requirements to the user like this:

![directus 7 installation requirements](https://user-images.githubusercontent.com/522079/46094686-938cee80-c188-11e8-9490-be274a0c37a9.png)

If all requirements pass, then we skip this screen/tab.

**Comment by benhaynes** [comment]
Do we have the API info needed to make this happen @rijkvanzanten @WellingGuzman ?

**Comment by benhaynes** [comment]
https://github.com/directus/directus/issues/2269#issuecomment-449659942

**Comment by benhaynes** [comment]
Also, this step of the install would _only_ show if all the requirements are **not** met. Otherwise it skips this step.

**Comment by shealavington** [comment]
I made this a few days ago as it was helping me, I've not integrated it into any interface (yet?) bbut if anyone else wants to use it (/ parts of it), feel free: 

https://gist.github.com/shealavington/92f95265d34286110d3f8fd850c9b1b9

**Each item will return true/false if it is or isn't working as it should.**
```
"logs": {
    "status": true,
    "title": "Logs Directory",
    "description": "The logs directory should have write permission"
},
```

**Comment by rijkvanzanten** [comment]
Wooo nice @shealavington! Can we use this to create the missing check endpoint @josephgagliardi?

**Comment by shealavington** [comment]
The only thing I'm not doing in my code is returning the versions of things as per the design; where it tell you that you're on php7 or on Apache, mine just says true or false haha.

It works when added as a custom endpoint, might be great to document it as a core endpoint so if you're not using the installer you could also visit /troubleshoot endpoint to see what's missing 🙌🏻

**Comment by rijkvanzanten** [comment]
Absolutely! I would love to see this as a core endpoint that the application can use to show a missing-requirements list before trying to install (and fail)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
