### ISSUE TITLE
Install: Choose Schema

### ISSUE THREAD

**Issue by benhaynes** [directus/app#861]
When you are done installing the API project, you should be taken to a tab for choosing a starter schema (if any). Blank would be default, but there should be at least 1-2 options for boilerplate schema data available. 

For now this demo data can be included in the Core code, but eventually we'll want this to live on the centralized Marketplace server so it's modular and searchable.

![directus 7 installation schema](https://user-images.githubusercontent.com/522079/46094818-f3839500-c188-11e8-979d-11e20f9a108b.png)

These demo projects would have the following (could be one/different files):

1. `schema.sql` – All the tables and columns in pure SQL or JSON
2. `data.sql` – All the demo data for the collections and fields
3. `settings.sql` – All the directus_fields info needed
4. `[files]` – Any files/images that need to be added for the File Library
5. `meta.json` – The details about the project (name, icon, description, tags, etc)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
