### ISSUE TITLE
Interface options resetting

### ISSUE THREAD

**Issue by benhaynes** [directus/app#864]
WYSIWYG interface options (buttons) resetting when you try to change them:

![screen shot 2018-09-26 at 4 52 27 pm](https://user-images.githubusercontent.com/522079/46108674-9ac5f380-c1ac-11e8-843d-d93887707181.png)

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/api/commit/ba220adf389950a13ca347668f8c553549a536f5
