### ISSUE TITLE
Remove ability to select primary key in O2M relationships

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#872]
**Is your feature request related to a problem? Please describe.**
Right now, it's possible to select a child's primary key field as O2M target. This isn't logistically possible in the API and will always cause an internal server error. To prevent this from happening, the user shouldn't be able to select a child's primary key as target.

**Describe the solution you'd like**
Remove the primary key field from the dropdown of O2M targets

**Describe alternatives you've considered**
We could still show it, but make it disabled to show the user that the field is there, but unavailable.

**Additional context**
See https://github.com/directus/app/issues/851

**Comment by benhaynes** [comment]
We could also add some tooltips to the inputs to clarify there purpose directly in the App (without needing to reference the Docs)

**Comment by benhaynes** [comment]
Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Makes sense. You shouldn't be able to select a field in the relationship setup that we know will never work

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
