### ISSUE TITLE
Timezone troubles

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#874]
## Describe the Bug
Somewhere somehow timezones go wrong. Uploaded on in files says "in about 4 hours" which indicates that it's using the UTC time instead of the local timezone

**Comment by benhaynes** [comment]
If I upload a file, it is showing the raw UTC datetime I think... maybe this is just an interface option (localize?) but we can't set this through Settings since the system collections aren't available to edit.

**Comment by rijkvanzanten** [comment]
Closed by https://github.com/directus/api/commit/d5868c4bf912bc0c147bf9dc615cf42e02854179
