### ISSUE TITLE
Disable Demo Page Extension

### ISSUE THREAD

**Issue by benhaynes** [directus/app#876]
It's good to have the demo Page Extension in the core codebase, but it should not be visible on fresh installs. Solutions include:

* Disable extensions that are prepended with `_` and add that to the demo
* Add it tot he nav blacklist (I don't think this is working yet)
* Delete it from the core codebase and add to the Docs (I'd prefer to keep it in the core codebase if possible)

**Comment by rijkvanzanten** [comment]
Lets go with the `_` and handle this from the API

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/api/issues/463
