### ISSUE TITLE
Pass field width to interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#879]
Interfaces need to be "responsive" but that isn't based on the viewport, it's based on the container and/or field width. We should pass the field grid size to the interface (`small`, `medium`, `large`, `x-large`).

We should also update the debugger to have a dropdown with the field width sizes instead of hardcoding a size.

**Comment by benhaynes** [comment]
Let's not worry about the debugger for now, but we should pass a container width to the interface so it can actually use responsive breakpoints. I assume this all needs to be done with the variables and not actual pixel dimensions? Is there a way to target containers with `@media`?

**Comment by rijkvanzanten** [comment]
Fields are responsive as of 7.2.0

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
I'm fine with https://github.com/directus/app/issues/1493 being closed, but this one is different and not done. I'd like to have the App pass data to the interface so that JS/CSS updates can be made based on form layout/size. We should pass:

* Field Layout — Each interface should be aware of if it is a `half`, `full`, or `fill`
* Container Width — The interface can't reliably be responsive (eg: `@media`) since it's in a container. So we should pass in some dimensions like: container width and maybe form width. With that, the interface could have JS conditionals for when to show/hide certain elements.

Is there anything else we can pass to give developers more control over presentation?
