### ISSUE TITLE
Settings>Permissions: Toggles not working

### ISSUE THREAD

**Issue by benhaynes** [directus/app#883]
"Mixed" toggles are not showing up correctly:

![screen shot 2018-09-29 at 12 25 15 pm](https://user-images.githubusercontent.com/522079/46248097-d6e29980-c3e2-11e8-9d1d-80aaaceeb165.png)

And the toggle are not showing all the options:

![screen shot 2018-09-29 at 12 27 35 pm](https://user-images.githubusercontent.com/522079/46248117-114c3680-c3e3-11e8-8690-8b898e3bf38c.png)

**Comment by rijkvanzanten** [comment]
This has been fixed by fixing the empty values in the DB

**Comment by benhaynes** [comment]
Only None/All is shown because the collection didn't have `created_on` and `created_by` interfaces/fields
