### ISSUE TITLE
App changed project after hard refresh

### ISSUE THREAD

**Issue by benhaynes** [directus/app#885]
![screen shot 2018-09-29 at 8 04 22 pm](https://user-images.githubusercontent.com/522079/46251532-eeda0d80-c422-11e8-800e-221efba78777.png)

I refreshed the app and it totally switched projects on me (back to the default). :/

The API in the tooltip does not match the label name.

**Comment by benhaynes** [comment]
This is reproducible, if you log in to api.example.com/project/ then hard refresh, it switches me to api.example.com/_/. Same API instance, different configs.

**Comment by benhaynes** [comment]
### ALSO
When the app logs out due to inactivity, it resets to the default project... it should stay on the last used project.

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this ever since, so I'll close it for now. We can re-open if needed.

**Comment by benhaynes** [comment]
Sneaky! I'm trying to keep this open till you duplicate!

https://media.giphy.com/media/Tb2i75AlI926I/giphy.gif

**Comment by benhaynes** [comment]
1. Install Combined build
2. Create a second API
    a. `api.php` — `_`
    b. `api.whatever.php` — `whatever`
3. Update App config to:
```
api: {
    "../_/": "Directus API",
    "../whatever/": "Whatever"
}
```
4. Log in to Whatever in App
5. Hard Refresh
6. **ERRRRORRRRRR**
