### ISSUE TITLE
Interfaces: updated_on and updated_by

### ISSUE THREAD

**Issue by benhaynes** [directus/app#886]
In order to actually use the `mine` and `role` permissions, we need to have interfaces that allow a user to set those field types.

**Comment by rijkvanzanten** [comment]
The `user` interface can be used for both by setting the type to user created:

![image](https://user-images.githubusercontent.com/9141017/46546581-6ed6fc00-c897-11e8-94c9-cb3919fc130c.png)

**Comment by benhaynes** [comment]
Does this work for the date time field as well?

**Comment by rijkvanzanten** [comment]
Now it does!
