### ISSUE TITLE
Settings>Field Modal: Unique

### ISSUE THREAD

**Issue by benhaynes** [directus/app#889]
Can this be changed? I assume it would add an index to the database? When we create a new collection it auto-adds an ID PK... this must be unique, yet the modal does not have that checked.

@WellingGuzman How does unique work? Can it be changed through the API?

**Comment by benhaynes** [comment]
@WellingGuzman 🔔

**Comment by WellingGuzman** [comment]
I don't understand this ticket. but the uniqueness on settings are a combination of `scope` and `key` column, it cannot be two records with the same value on `scope` and `key`, no matter the primary key value.

**Comment by rijkvanzanten** [comment]
@WellingGuzman This is about `unique` values in general, not specifically `directus_settings`. @benhaynes is asking how `unique` values work, and if we can change it in the API endpoints

**Comment by WellingGuzman** [comment]
Yes, we can change unique values. `user.token` is a unique field and we can change it or set it to `null` (_when it allows null_)

**Comment by benhaynes** [comment]
@WellingGuzman – ok, let me ask a different way:

Can we set a field/column TO BE _unique_ through the API. Can we set a _unique_ field/column to NOT BE unique through the API?

**Comment by WellingGuzman** [comment]
You can set fields to be `unique` through the API, but you can't stop a field from being unique.

It has the same issue that `primary_key` has (https://github.com/directus/api/issues/430)

**Comment by benhaynes** [comment]
OK, @rijkvanzanten ... let's disable this toggle on edit. 

@WellingGuzman I'll open a ticket to fix this.

**Comment by benhaynes** [comment]
@rijkvanzanten ... we need this! ;)

**Comment by rijkvanzanten** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/9141017/50709950-827d3480-1037-11e9-8cd8-4e5266e598ad.png">

We have it!
