### ISSUE TITLE
Duplicate Field

### ISSUE THREAD

**Issue by benhaynes** [directus/app#891]
Settings>Collections and Fields

It would be nice to have an option (within a three dot icon) to "Duplicate" a field. This would duplicate the whole thing but ask for a new column/field name (in an "alert").

**Comment by benhaynes** [comment]
Here's a quick mock of the prompt:

![directus 7 duplicate field prompt](https://user-images.githubusercontent.com/522079/47618881-98f29700-daae-11e8-8dbf-bc4d5abcf0b6.png)

**Comment by benhaynes** [comment]
Some of these styles are old, but that's generally what I'm thinking for the "three dots" menu for _duplicate_. It would replace the "X", which would then be an option within the menu too.

![screen shot 2018-10-28 at 12 45 41 pm](https://user-images.githubusercontent.com/522079/47618985-a5c3ba80-daaf-11e8-952e-55f3bc898d2c.png)

**Comment by benhaynes** [comment]
We should probably have a blacklist of `field types` that can't be duplicated:
```
Primary Key
Sort
Status
M2M
O2M (M2O is ok to duplicate I think)
```

**Comment by shealavington** [comment]
Added in #1056  😃
