### ISSUE TITLE
First input focus on pages/tabs

### ISSUE THREAD

**Issue by benhaynes** [directus/app#892]
I know there might be a reason to not do this globally, but here are some instances where it would help a lot:

**Create/Edit Field**
* Second tab: Focus on "Database column name" input
* Interface options: focus on first option

**Create Collection Dialog**
Should focus in input (probably true for all dialogs)

**Comment by benhaynes** [comment]
We should do a quick pass and make sure that the Item Detail page and modals have their first field focused on load.

**Comment by rijkvanzanten** [comment]
This was implemented a week or so ago on modals and tabs
