### ISSUE TITLE
Interface default schema values

### ISSUE THREAD

**Issue by benhaynes** [directus/app#893]
Since many schema fields are under "advanced options" and can easily be missed, it would be nice if an interface could define their default values.

## Length
Currently if you create a WYSIWYG it defaults to VARCHAR(255) ... which won't hold more than a sentence or two with formatting. We could change the `string` default to TEXT but that's overkill for many text inputs.

One solution would be to include a `recommended_length` option in the interface meta.json file. This could be used to choose an ideal SQL datatype without needing a complex list for each SQL vendor. This way we should be able to have the WYSIWYG default to TEXT and Text Input default to VARCHAR(255).

## Default
Status for example, it would be good to have `draft` set as the _default_ default. That way newly created items have a status that matches the interface option default mapping.

## Regex
An "email" interface could set a default regex

## Unique
A "slug" interface could set the field to be unique by default

**Comment by rijkvanzanten** [comment]
The `status` has been changed in https://github.com/directus/app/commit/db10650fa38a3d579abc606f7e1192d203cb0765
