### ISSUE TITLE
Settings>Field Modal: Delete single character after underscore

### ISSUE THREAD

**Issue by benhaynes** [directus/app#894]
If you have a field name such as `whatever_1` and hit the delete/backspace key... 

You expect to have `whatever_`... but you get `whatever`. It must do something with converting underscores to whitespace and trim.  Either way, this can easy save the wrong field name (which can't be changed).

**Comment by mclintprojects** [comment]
What file can I look at to begin with fixing this bug @benhaynes?

**Comment by rijkvanzanten** [comment]
This bit is doing the fieldname cleanup @mclintprojects 🙂 

https://github.com/directus/app/blob/8672b1bcc49502b70e09ebcab767c7208161e80a/src/components/modals/prompt.vue#L81-L94
