### ISSUE TITLE
Settings>Fields: Incorrect order

### ISSUE THREAD

**Issue by benhaynes** [directus/app#899]
I created four fields and then saved the collection (updated a note). When I went back to the page, the fields were in the wrong order.

The database column order is correct (the order I created them in).

The `directus_fields.sort` values are all `NULL`.

But they display like this (not sure where this order comes from):

![screen shot 2018-09-30 at 11 41 16 am](https://user-images.githubusercontent.com/522079/46259306-d828ca80-c4a5-11e8-9d69-bf5218435616.png)

I never dragged these to a new order... if I do that I'm sure they would save a `sort` value and be fine. But if you _create_ fields in order, they should stay in that order.

**Comment by benhaynes** [comment]
Correct order was: ID (already there), Status, Sort, Client, Statement.

**Comment by benhaynes** [comment]
After dragging/dropping, they DID get a `sort` order in the database... but then after making new fields (which get sort set to `NULL`)... when you go to the collection the NULLs show up _before_ the ordered fields.

NULLs should show up after, and ideally in the same order (based on schema order)

**Comment by benhaynes** [comment]
The App should just assign a `sort` order to all columns as they're created and submit them. Basically "faking" as if the user dragged and dropped a field during setup.

**Comment by rijkvanzanten** [comment]
This was closed in https://github.com/directus/api/commit/8569b40feb7a6453bc2012c5fd7fe502e6a0c421
