### ISSUE TITLE
Settings>Field Modal: Tags in Options

### ISSUE THREAD

**Issue by benhaynes** [directus/app#901]
If you create a field using the `tags` interface, and go to the options at the end, clicking the three toggles is doing weird stuff:

1. I had to click `delimiter` twice to deactivate it
1. Then I clicked `lowercase` and it turned `delimiter` back on
1. Then I turned both off again
1. Finally I clicked the first toggle and it turned on both of the next two!

![screen shot 2018-09-30 at 11 58 36 am](https://user-images.githubusercontent.com/522079/46259493-3191f900-c4a8-11e8-856f-e04a19a3d3a3.png)

**Comment by benhaynes** [comment]
After a toggle has been clicked the first time it doesn't seem to cause any further issues... this seems to be another "instantiation" issue with initial interfaces in the options.

**Comment by rijkvanzanten** [comment]
~This is our machine learning based artificial intelligence algorithm helping the user setting the ultimate combination of settings for this interface.~

🐛

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/commit/db10650fa38a3d579abc606f7e1192d203cb0765
