### ISSUE TITLE
Auto Created Primary Key should be hidden_input true

### ISSUE THREAD

**Issue by benhaynes** [directus/app#906]
98% of the time users will not want a PK field at the top of their edit form. When we auto create this, let's make sure it gets `hidden_input` set to `true`

**Comment by rijkvanzanten** [comment]
Hey @mclintprojects! The code that creates the field is here: https://github.com/directus/app/blob/master/src/routes/settings/collections.vue#L132

Adding hidden_input here and further down the file again (where the same field structure is mentioned should do the trick. 🙂

**Comment by benhaynes** [comment]
Important to note that `hidden_input` was changed to `hidden_detail` yesterday!

@mclintprojects @rijkvanzanten
