### ISSUE TITLE
API Column Updates

### ISSUE THREAD

**Issue by benhaynes** [directus/app#907]
`directus_fields.hidden_input` (should become `hidden_detail`)
`directus_fields.hidden_list` (should become `hidden_browse`)
`directus_fields.view_width` (should become `width`)
`directus_files.storage_adapter` (should become `storage`)

**Comment by James-N-M** [comment]
I think I can handle this one to start 🎃 👻

**Comment by benhaynes** [comment]
@James-N-M ... Almost!! That one was fixed earlier today, we're just waiting on @rijkvanzanten to approve the PR. 😬 

Luckily there are ~300 other issues to choose from! 😉

**Comment by mclintprojects** [comment]
@benhaynes i've setup the config.js for the directus app but it requires me to login to the demo api. how do i sign up for the demo api?

**Comment by rijkvanzanten** [comment]
Hey @mclintprojects you can either set up a local instance of the API as well, or use our demo credentials: 

```
admin@example.com
password
```
