### ISSUE TITLE
Link to How to Contribute in ReadMe

### ISSUE THREAD

**Issue by jbull328** [directus/app#910]
**Is your feature request related to a problem? Please describe.**
It took me a while to find the instructions for setting up a development environment.

**Describe the solution you'd like**
Add a link to the documentation on how to set up a local environment. This page in the documentation shows how to get things set up in a simple way to start contributing.
https://docs.directus.io/app/contributor-guide/install-dev.html

**Describe alternatives you've considered**
These instructions are linked on the directus/api repo ReadMe but I think they would be helpful to have linked in the directus/app ReadMe as well.

**Additional context**
Not exactly a feature or a bug, more of a nice to have since it took a bit of digging to find.

**Comment by rijkvanzanten** [comment]
I'm considering this a bug in the README!

**Comment by benhaynes** [comment]
The App and API READMEs have been updated with a new style/format and I've included these direct links. We'll also add this to directus/directus when we release v7. 

Thank you @jbull328 – lot's going on and it's easy to miss important things like this!

* https://github.com/directus/app#contributing
* https://github.com/directus/api#contributing
