### ISSUE TITLE
Status Mapping: Subdue on Browse

### ISSUE THREAD

**Issue by benhaynes** [directus/app#915]
When an item has this set, all of the content of that item's row should be 50% opacity in the tabular layout.

**Comment by benhaynes** [comment]
Is this one useful? Thoughts @rijkvanzanten @rachelsun59? It would definitely help make draft (or any similar status options) less noticeable and more distinguishable... or we can keep things simple with just the badges.

**Comment by rijkvanzanten** [comment]
I think I prefer keeping it simple with just the badges + filtering if you don't want to see draft

**Comment by benhaynes** [comment]
OK! I guess we have two months to see if anyone disagrees! 😉
