### ISSUE TITLE
provide a docker container for the directus api

### ISSUE THREAD

**Issue by cocodrino** [directus/app#916]
Hi guys, would be great if you could provide a docker container for the api and not just the app, I'd check some vuejs app bugs for the hacktoberfest but it's a pain in the $%# need install php,mysql (I've postgresql) and all those stuff...and I'm not a guru writing docker-compose files...maybe there are other guys with the same trouble...

thank you...best regard!!

**Comment by rijkvanzanten** [comment]
There is a docker compose file right there! 😄 

https://github.com/directus/api/blob/master/docker-compose.yml

**Comment by benhaynes** [comment]
Thanks @cocodrino ! Hopefully we'll see you in the pull request section! 😉

**Comment by cocodrino** [comment]
thank you guys...this weekend I'm going to check all those issues ;D...
