### ISSUE TITLE
Field disappears after changing options

### ISSUE THREAD

**Issue by benhaynes** [directus/app#917]
_Found locally, but with demo/next schema_

1. Go to `movies` detail – you will see `cast` field
1. Go to Settings > Collections > Movies > Cast
1. Go to "Options" tab and update `rows` (eg: from `14` to `15`)
1. Hit save for modal
1. Click on `movies` in navigation and then click on an item
1. **The `cast` field is now completely missing**

**Comment by rijkvanzanten** [comment]
I don't see it disappearing, but I _do_ see that the `sort` changes.

I feel like the sort made the field move to another location which gave the impression that it disappeared

**Comment by rijkvanzanten** [comment]
The app is putting fields with `sort=null` last. The API used to return a merge of mysql column order and the sort values which is being refactored to just return the `directus_fields.sort` value which resolves the shift in sorting
