### ISSUE TITLE
Sort interface isn't adding browse handles

### ISSUE THREAD

**Issue by benhaynes** [directus/app#920]
When a collection has a field with the `sort` interface, it should always show drag handles on browse (and tile eventually). Right now this isn't working.

Demo: /collections/concessions

![screen shot 2018-10-04 at 1 18 31 pm](https://user-images.githubusercontent.com/522079/46491236-286e9800-c7d8-11e8-9718-354df818637e.png)

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/commit/96d43af0073b38c123548b0fad42b03c35f36a1b
