### ISSUE TITLE
Average Latency Indicator

### ISSUE THREAD

**Issue by benhaynes** [directus/app#93]
Let's poll every 5 seconds, but average the last 30 seconds to show... that way it doesn't "bounce" around too much. Also, this helper should have a param to return a text version instead of an icon (for the latency card) and the icon should have a hover for exact latency:

`56ms Latency`

**Comment by rijkvanzanten** [comment]
> that way it doesn't "bounce" around too much

On the other hand, you would want the icon to reflect the most current state..? If you just got onto a subway, it shouldn't take over half a minute for the icon to reflect this.

**Comment by rijkvanzanten** [comment]
I think the underlying problem of the bouncing icon is the fact that I set the value thresholds too strict. (Aka the amount of latency that sets the signal strength level to 1-4)

**Comment by benhaynes** [comment]
That is also a solution. Basically I just don't want that icon to be a distraction by always popping from max to min with each little hiccup in the latency.

**Comment by rijkvanzanten** [comment]
True. We should tweak the values of the latency thresholds. 

As of right now, this is the function that sets the strength (which directly controls the signal indicator)

https://github.com/directus/app/blob/f5a9553d2889b23d96b844e32e107d1800c425a8/src/store/getters.js#L1-L27

These are the values in use that need to be shifted:

| Latency         | Strength |
|--------------|----------|
| 0 - 100ms     | 4             |
| 100 - 150ms | 3             |
| 150 - 200ms | 2             |
| 200+ms        | 1              |
| --                    | 0           |

**Comment by benhaynes** [comment]
Coolio. Maybe something more like this? I know these seem high, but we have "decent" internet connections and in a lot of places half a second of latency might not be uncommon.

| Latency         | Strength |
|--------------|----------|
| 0 - 200ms     | 4             |
| 200 - 500ms | 3             |
| 500 - 1,000ms | 2             |
| 1,000+ms        | 1              |
| --                    | 0           |

**Comment by benhaynes** [comment]
We might want to update this to a 10s poll (instead of 5s)

Also, we should use the wifi icon with the "!" for anything over what we consider a Timeout... perhaps 10s+?

**Comment by benhaynes** [comment]
This seems to be working well now, no need for averages... the new values work.

**Comment by rijkvanzanten** [comment]
Cool! 🎉
