### ISSUE TITLE
Add .htaccess for apache support out-of-the-box

### ISSUE THREAD

**Issue by benhaynes** [directus/app#938]
We can keep the router defaulting to `hash`, but it would be nice to include an `.htaccess` file in the App root so that Apache users can easily use the app in `history` mode. We can also add the nginx equivalent if there is one (I don't think that would live in the repo though).

**Comment by rijkvanzanten** [comment]
For the app, the htaccess should be rewrite every request to `index.html`. I'm not too familiar with the `.htaccess` format, so if anyone likes to take a shot, please do!
