### ISSUE TITLE
Interface: Divider>Options

### ISSUE THREAD

**Issue by benhaynes** [directus/app#940]
The size option is not saving... no matter what it's staying as `small`.

**Comment by rijkvanzanten** [comment]
The `divider` interface is using the `dropdown` interface for this setting:

https://github.com/directus/api/blob/3bd595cb308c024ddad18c8d7c7a2974f422e55b/extensions/core/interfaces/divider/meta.json#L12

which makes me thing that there might be a 🐛 in the `dropdown` interface which causes it to not stage the value correctly.

**Comment by rijkvanzanten** [comment]
This has been fixed when we updated the field options to always save
