### ISSUE TITLE
Interface Options are not reliably saving

### ISSUE THREAD

**Issue by benhaynes** [directus/app#942]
Every time I try to create or change any interface options, they very rarely work. Usually they don't save, occasionally they do. Also, I need to refresh the App to see most changes on the detail page (ideally I should just see changes).

### Example

If I save the available buttons for the WYSIWYG, they don't save to the DB.

**Comment by benhaynes** [comment]
Also, sometimes it saves in the database but still shows the old/default values in the settings. This is even more annoying, because it makes it hard to edit without messing up your previous options... and doesn't even show an accurate representation of the settings.

**Comment by rijkvanzanten** [comment]
> Also, sometimes it saves in the database but still shows the old/default values in the settings. This is even more annoying

Yeah I've updated it to always save all settings, but apparently it doesn't use the saved values when re-opening.. Odd!

It's using this function to generate the options object

https://github.com/directus/app/blob/7fd4df8bbbf1b70676ccd8bc181aadbda54fca8d/src/components/field-setup.vue#L433

Something must be wrong in populating the `this.options` data state.
