### ISSUE TITLE
Edit Field Datatype

### ISSUE THREAD

**Issue by benhaynes** [directus/app#943]
Dropdown shows `text` but is set to `varchar`...

![screen shot 2018-10-08 at 4 28 39 pm](https://user-images.githubusercontent.com/522079/46632076-6c82d500-cb17-11e8-8c4b-498493eac679.png)

![screen shot 2018-10-08 at 4 30 12 pm](https://user-images.githubusercontent.com/522079/46632084-74427980-cb17-11e8-967a-b7478805c6de.png)

But is saved in the DB as `text`:

![screen shot 2018-10-08 at 4 31 50 pm](https://user-images.githubusercontent.com/522079/46632159-ae138000-cb17-11e8-8814-90ec87868457.png)

**Comment by rijkvanzanten** [comment]
Yikes.. 

The select interface uses the selected element as value to display, and fallsback to the actual database value if that doesn't exist (no item selected):

https://github.com/directus/app/blob/7fd4df8bbbf1b70676ccd8bc181aadbda54fca8d/src/components/form-inputs/simple-select.vue#L43-L47

It looks like that bit is not playing nicely

(Also, let's change 

```js
mounted: function() {}
```

to 

```js
mounted() {}
```

while we're at it, to make it consistent with the rest of the codebase)
