### ISSUE TITLE
Card Layout: Don't show empty "body content"

### ISSUE THREAD

**Issue by benhaynes** [directus/app#950]
When using a card view, there is a "(Don't Show)" option for the different field, but they are not honored. If I turn off "Body Content" I still see `--` there... it should be hidden completely.

![screen shot 2018-10-08 at 8 32 58 pm](https://user-images.githubusercontent.com/522079/46640338-5ede4700-cb39-11e8-8ab0-4c49764f2efc.png)

**Comment by benhaynes** [comment]
Hey @N1ck – thank so much for looking into this! You can find this in the app when you're on a tile view (like file library or user directory) and you click the info button in the header. That will open the layout's options sidebar. 

You can use the tile view for any collection, but it's best suited for image based content. Ideally the tiles adapt to whatever content is assigned, and if a slot is set to not show it should disappear instead of showing placeholder `--`.

**Comment by benhaynes** [comment]
I'm on the latest build and still see this happening. If I select `(Don't Show)` I still see the `--` and the dropdown goes back to `Select a Field`.

**Comment by rijkvanzanten** [comment]
Closed by https://github.com/directus/api/commit/cf4b6e9137c7b8eebd585c2efee56cce3b6e8377
