### ISSUE TITLE
Missing field on relational setup

### ISSUE THREAD

**Issue by benhaynes** [directus/app#959]
When setting up a M2O field there is a blank input for "THIS FIELD" on the relations tab:

![screen shot 2018-10-11 at 11 11 38 am](https://user-images.githubusercontent.com/522079/46814395-9cfc8600-cd46-11e8-87da-b4739a543e2d.png)

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/46876073-62a8ec80-ce0b-11e8-8369-decd80c9f037.png)

Seems to be working for me!
