### ISSUE TITLE
Cleanup codebase

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#962]
Over the last couple months, a lot of things have been implemented or fixed as quickly as possible. During this work, the codebase has gotten a bit messy.

At the least, we should make sure that the codebase adheres to [the Vue Styleguide](https://vuejs.org/v2/style-guide)

**Comment by honzabilek4** [comment]
I think that the recommendations in the style guide are minor compared to what the codebase really needs to be more clean and readable.  I've also read the issue with global interfaces described in #640 and I strongly agree. Though personally, the biggest code smell in the codebase is that some of the components/pages got really huge over the time. See [routes/item.vue](https://github.com/directus/app/blob/master/src/routes/item.vue) for example. This file has over 1000 lines and contains all different types of logic which makes it harder to read and understand. Splitting up the functionalities to some smaller self-contained units would be a great first step to clean everything up in my opinion.

**Comment by rijkvanzanten** [comment]
This is an ongoing optimization that doesn't have a single 'goal' to fix
