### ISSUE TITLE
Install: Project Name

### ISSUE THREAD

**Issue by benhaynes** [directus/app#965]
After installing the API through the App, the App config should be configured so that the project name is used in the project switcher. Weird, because this is what is in my App config:

`"../_/": "API"`

![screen shot 2018-10-12 at 2 47 27 pm](https://user-images.githubusercontent.com/522079/46888243-e96ec100-ce2d-11e8-83f3-8ddd430c7371.png)

**Comment by rijkvanzanten** [comment]
The issue here is that it's trying to match the literal full URL (`https://example.com/_/`) to the relative url (`../_/`). It can't find it, so it falls back to the domain name of the API.
