### ISSUE TITLE
Interface: WYSIWYG displaying "null"

### ISSUE THREAD

**Issue by benhaynes** [directus/app#966]
It should be empty...

![screen shot 2018-10-12 at 2 58 58 pm](https://user-images.githubusercontent.com/522079/46888981-1f14a980-ce30-11e8-95ba-7d519d20cb86.png)

**Comment by ccalamos** [comment]
Is this referencing the textarea in the form-inputs?

**Comment by benhaynes** [comment]
We actually just figured it out @ccalamos – the textarea interface was rending the "hard" value of the placeholder... so an empty string became `null`. This will be the last fix before we release v7!

**Comment by rijkvanzanten** [comment]
Yeah it was closed in 96f3d37dcf45e41247aa369fe71257d07e4a47ed
