### ISSUE TITLE
User Role Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#970]
This is a bug, not an enhancement.

We need a way to assign roles to users. For now this should be a dropdown (settings a single role), but in the future we can make this save multiple (for merging permissions).

Unfortunately this will need to save in the junction table since our schema is prepared for the merging already.

**Comment by Mu9tafa-Online** [comment]
How to "assign roles to users" now? do we need to do it manually from DB ?

**Comment by benhaynes** [comment]
Yes, until we push a hotfix this can be done by manually adding records to the `directus_user_roles` table in the database. Since merging permissions isn't done yet, be sure to only add one role per user.

**Comment by rijkvanzanten** [comment]
This has been fixed in https://github.com/directus/api/commit/8757ec937f8a23f041cdb459999e1d6659faa1c2

**Comment by Mu9tafa-Online** [comment]
I can't see it yet!

**Comment by benhaynes** [comment]
@Mu9tafa-Online – it's probably best to reinstall since there are changes in the initial DB too
