### ISSUE TITLE
Settings>Permissions: Notes

### ISSUE THREAD

**Issue by benhaynes** [directus/app#971]
The permissions interface needs to show `This project does not have any collections yet` in light-gray text when there are no collections.

Similarly, the Admin role needs a note at the top explaining that they always have all permissions (so people don't wonder). `Administrators always have full permissions`

Without these notes it is easy to mistake this lack of info as a bug.

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/47586949-800fa780-d92f-11e8-9b3d-460992307f4d.png)

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/47587272-60c54a00-d930-11e8-9521-c4a7fa084753.png)
