### ISSUE TITLE
Tile Layout: Exit selection mode after batch delete

### ISSUE THREAD

**Issue by benhaynes** [directus/app#973]
After you delete an item(s) from the Tile layout (eg: File Library) you are still in selection mode (with the checkbox circles in the corner). We should exit this mode and return to the normal view.

**Comment by ShadowRonin** [comment]
I'll take a stab at this if you don't mind.

**Comment by benhaynes** [comment]
Don't mind at all, that would be awesome @ShadowRonin ! ❤️

**Comment by rijkvanzanten** [comment]
Thanks for helping out @ShadowRonin!

This is where the card is set to selection-mode: https://github.com/directus/api/blob/b01767b166a709ba905a4da3c62df8c8878b618c/extensions/core/layouts/cards/layout.vue#L14

Apparently, after the delete is done, the selection isn't cleared fully..

The selection itself is (all the way) up here:

https://github.com/directus/app/blob/95c78f38052846c3cc655f847c5cc8497262ef41/src/routes/items.vue#L133 (we should probably move the selection to the store too at one point)

This is where the selection is (supposed to be) set to `[]` on remove:

https://github.com/directus/app/blob/95c78f38052846c3cc655f847c5cc8497262ef41/src/routes/items.vue#L508
