### ISSUE TITLE
Use of Datetime field

### ISSUE THREAD

**Issue by maettyhawk** [directus/app#975]
Version: Directus 7.0.1

It's almost impossible to use the datetime field. Tried to enter 08.12.2018 17:00, but it starts changing the whole entry when i'm trying to type in the minutes.

https://youtu.be/kI44RV6hUVU

**Comment by benhaynes** [comment]
Upon further inspection, I don't think this is related to localization... I think it has to do with the converting between SQL and ISO time formats. Still looking into this.

https://github.com/directus/api/blob/master/extensions/core/interfaces/datetime/input.vue#L40

**Comment by maettyhawk** [comment]
I had look on the whole thing yesterday, but I didn't even find out that it might be an API problem rather than a bug within the app part. 🤦‍♂️

**Comment by benhaynes** [comment]
Haha, yeah...

I just fixed ONE issue locally... the month was off because the input is `1` based and getMonth() is `0` based. So now the value and input match (updated to `this.date.getMonth()+1`)... but it's still acting really weird when changing date/time in the input.

**Comment by maettyhawk** [comment]
It might be better to use a datetime vue package than to rely on input[type="datetime-local"] - browser support seems to be really bad and also the behaviour is beyond predictable.

**Comment by benhaynes** [comment]
OK, so now that the indexed month is fixed, the remaining problem is a locale/timezone one. The `updateValue` method is converting the saved value with the `dateToSql` helper:

`new Date(value)` == `Fri Oct 12 2018 01:00:00 GMT-0400 (Eastern Daylight Time)`
`this.$helpers.date.dateToSql(new Date(value))` == `2018-10-12 05:00:00`

So every keypress or onChange of the input pushes the time 4h (the timezone diff) into the future.

https://docs.directus.io/app/contributor-guide/helpers.html#date
https://github.com/directus/app/blob/master/src/helpers/date.js

**Comment by benhaynes** [comment]
I think you might be right @maettyhawk – especially since the system input doesn't even register the value until you enter a time too. Any good Vue options you know of?

**Comment by benhaynes** [comment]
https://www.npmjs.com/package/vue-datetime
https://www.npmjs.com/package/vuejs-datetimepicker
https://www.npmjs.com/package/vue-vanilla-datetime-picker

**Comment by maettyhawk** [comment]
Unfortunetely i don't have experience with any of these... I'd give vue-datetime a try since it comes with i18n. On the other hand it's a lot of bloat, actually this whole calendar thing is not really needed. How about a different approach? Why not using a simple input[type="text"] with some kind of mask? (https://vuejs-tips.github.io/vue-the-mask/)

**Comment by rijkvanzanten** [comment]
That sounds like the most foolproof and easy-to-implement solution @maettyhawk!
