### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by Nitwel** [directus/app#978]
## Describe the Bug
When trying to reset the password, the error message "Unknown Error..." occurs.
Also, if this function is not programmed yet, im sorry to corrupt you.

## API mail config

`'mail' => [
        'default' => [
            'transport' => 'sendmail',
            'from' => 'admin@example.de'
        ],
],`

## Technical Details
- PHP Version: 7.2.7
- Directus App: 7.0.1
- Directus API: 2.0.1

**Comment by rijkvanzanten** [comment]
Hey @Nitwel! This should work 👀

It seems that the app is trying `//auth/password/request` instead of `/auth/password/request` (two `//`) which makes it 404, which in turn causes the error.

Good catch 🙂

**Comment by rijkvanzanten** [comment]
Ref: 

https://github.com/directus/app/blob/20182d55de33d73e6bab94f18c626e5d4e55a5e1/src/routes/login.vue#L285-L287

I think removing `/` from this line should fix it on the app side.

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/api/issues/488
