### ISSUE TITLE
Visual scrollbar bug

### ISSUE THREAD

**Issue by Nitwel** [directus/app#980]
## Describe the Bug
![grafik](https://user-images.githubusercontent.com/22577866/46967539-20a0d480-d0b1-11e8-8f36-db279a6f9487.png)

As seen on the image, these scrollbars should be hidden.

## Technical Details
- operating system: Windows
- Browser: Firefox (latest version)
- Directus 7.0.1
- Directus API: 2.0.1

**Comment by rijkvanzanten** [comment]
ay, cons of working on a Mac.

If anyone has any solid recommendations on how to hide these properly for Windows based clients, please let me know! 😄

**Comment by Nitwel** [comment]
![grafik](https://user-images.githubusercontent.com/22577866/46969103-4c25be00-d0b5-11e8-8a28-f2106356f84d.png)

change overflow from **scroll** to **auto**.
Or if you only want Y(Up/Donw)-scrolling, user y-overflow: auto and x-overflow: hidden.

**Comment by rijkvanzanten** [comment]
Wow it's that simple? Perfect!

**Comment by rijkvanzanten** [comment]
> Macs are weird in hiding these things

Or Windows is weird for not hiding non-movable scroll bars 😜 

jk, lets not get a mac v windows discussion started in here haha

**Comment by Nitwel** [comment]
Well, "overflow: scroll" is used to force the scrollbars, so in this point Firefox wins ^^
https://developer.mozilla.org/en/docs/Web/CSS/overflow#Syntax

**Comment by benhaynes** [comment]
I submitted a PR for this, hopefully it fixes it... but I'll follow protocol and let Rijk review it before merging. 😉

**Comment by Nitwel** [comment]
Found another place where its broken:
![grafik](https://user-images.githubusercontent.com/22577866/48090388-0ae18380-e207-11e8-9a99-c0fa3f62f01d.png)

I suggest doing a full file scan to search for any "overflow: scroll" and replacing it with "auto"

**Comment by Nitwel** [comment]
or in this example, you have to remove the "overflow: auto" to "hidden" on the marked element like on the image below.
![grafik](https://user-images.githubusercontent.com/22577866/48090691-f18d0700-e207-11e8-8853-b239ed8c039f.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
