### ISSUE TITLE
Decimal and Double not Working

### ISSUE THREAD

**Issue by Nitwel** [directus/app#981]
## Describe the Bug
Using Double or Decimal, the input fileds will show up red when entering a double with , / . and the in/decrease arrows will always jump in 1 steps.

## Input fields:
![grafik](https://user-images.githubusercontent.com/22577866/46968951-eb968100-d0b4-11e8-8836-18fbafd6437a.png)

## Table setup:
![grafik](https://user-images.githubusercontent.com/22577866/46968988-023cd800-d0b5-11e8-82b9-3c91d124e6ad.png)

- Directus App: 7.0.1
- Directus API: 2.0.1

**Comment by Nitwel** [comment]
Also, when entering a 1, saving and repoening it, this happens:
![grafik](https://user-images.githubusercontent.com/22577866/46970575-ca845f00-d0b9-11e8-8fe7-ef3b528d48ff.png)

**Comment by rijkvanzanten** [comment]
> and the in/decrease arrows will always jump in 1 steps.

@Nitwel What do you think the ideal step size would be for a double? Should it be an option?

**Comment by Nitwel** [comment]
I would recomend using 0.1 or 0.01 steps, because u normaly only use 1 / 2 spots after the comma.

**Comment by rijkvanzanten** [comment]
> I would recomend using 0.1 or 0.01 steps, because u normaly only use 1 / 2 spots after the comma.

I based the `step` on the configured length value. Eg if you have your length set to `10,2`, the step is going to be `0.01`.
