### ISSUE TITLE
Click on "Show Directus System Collections" throws error

### ISSUE THREAD

**Issue by WellingGuzman** [directus/app#985]
When I click on the "Show Directus System Collection" after creating a new role I get the following error:

 ```
TypeError: Cannot read property 'toLowerCase' of null
```

<img width="552" alt="screen shot 2018-10-15 at 5 10 09 pm" src="https://user-images.githubusercontent.com/1531291/46978680-9438e680-d09d-11e8-965e-37fa095d5fc2.png">

**Comment by rijkvanzanten** [comment]
I think this was fixed in https://github.com/directus/app/commit/dcd4df0d1c03f5dc70e70f67b8b2e1c20e6f66ea
