### ISSUE TITLE
"required" - switch issue

### ISSUE THREAD

**Issue by Nitwel** [directus/app#988]
### the issue
You can toggle the "required" - switch on the divider, wich results in not being able to add content.

![grafik](https://user-images.githubusercontent.com/22577866/47028855-83a27200-d16a-11e8-9f0d-e73a825f1469.png)

### to solve this issue:
remove this toggle option on filedtypes, where theres no need for input.
Heres a list of possible fieldtypes:
- divider
- user --> user_created / user_updated
- group --> user_created / user_updated
- preview
- file-size
- file-preview
- datetime -> created at / updated at

### Versions
- Directus: 7.0.1

**Comment by benhaynes** [comment]
Thanks @Nitwel – hopefully not too many admins will make their dividers required. 😄 

We have added "recommended" values for interfaces, but it would be good to also allow them to disable certain settings too. 

@rijkvanzanten – one helpful update we could add in the meantime might be not allowing required based on the field type: eg: ALIAS
