### ISSUE TITLE
Interface not updating

### ISSUE THREAD

**Issue by Nitwel** [directus/app#989]
When changing the interface of a collection, the fieldtype in the advanced options does not update.
As seen on the image, the interface has changed from switch to numeric which results in the selection not updating from boolen to Integer or Decimal.

![grafik](https://user-images.githubusercontent.com/22577866/47030159-720e9980-d16d-11e8-8baa-a54034959bdb.png)

**Comment by rijkvanzanten** [comment]
Ref "feldtyp" in German is called "Interface" in the English translation.
