### ISSUE TITLE
tags: This value should be of type array.

### ISSUE THREAD

**Issue by srjrol** [directus/app#990]
## Describe the Bug
tags: This value should be of type array.

## Steps to Reproduce
1. Upload file
2. Open in File Library
3. Add tag

## Expected Behavior
Add tag and save.

## Screenshots
![image](https://user-images.githubusercontent.com/34398302/47047517-631feb00-d15d-11e8-9304-665972eb3597.png)
![image](https://user-images.githubusercontent.com/34398302/47047522-66b37200-d15d-11e8-95dc-c4c3a2cd8aee.png)

**Comment by rijkvanzanten** [comment]
Hey @srjrol! You’re right, this is a bug in the tags interface. Directus uses it’s own abstraction of data types under the hood. The tags interface uses the `array` type, which expects a JSON array `[]` to be send. Apparently, the value is staged as a string 🤔
