### ISSUE TITLE
Non-admins can't create items in a collection

### ISSUE THREAD

**Issue by ransoing** [directus/app#991]
## Describe the Bug
Non-admin users can't create new items in a collection using the Directus app.

## Steps to Reproduce on the Directus Latest demo
1. Create a new user role and assign all permissions to it (in all custom collections as well as all Directus System Collections)
1. Create a new user with that role
1. Log in with the new user
1. Click on something like "Concessions", then the blue + button in the corner to add a new item
1. All fields are greyed out and there is no checkmark button in the corner

## Expected Behavior
Non-admins should be able to create new items as their permissions allow.

## Technical Details
- Device: Mac OSX 10.10.4, Chrome latest
- Directus App: Live demo site
- Directus API: Directus Latest deployment

**Comment by tthompson899** [comment]
I can work on this.

**Comment by benhaynes** [comment]
That'd be great @tthompson899! We'll need to merge it into the 7.0.2 release tomorrow at 2p EST... so hopefully you can find a fix before then. If not, we'll try to get it fixed!

Thank you!!! 😄

**Comment by tthompson899** [comment]
@benhaynes Unfortunately I'm not going to have this done in time for release. 
Currently unable to reproduce this bug - I'm thinking it has something to do with the fact my database isn't connected so I'm not able to save anything through the app.
