### ISSUE TITLE
Can't re-enable "Fields" checkboxes in permissions

### ISSUE THREAD

**Issue by ransoing** [directus/app#992]
## Describe the Bug
I can uncheck Readable/writable field permissions for some collections, but I can't always re-check them.

## Steps to Reproduce
Steps to reproduce the behavior in the Directus Latest demo:
1. Log in as the admin user
2. Edit the 'interns' role
3. Click in the 'Fields' column for something like the 'Showtimes' collection
4. Deselect any checkbox, i.e. "Closed Caption Enabled" under the "Writable Fields" section
5. Click the checkbox in the corner to save the changes
6. Click 'interns' again to edit the role
7. Repeat step 3
8. Try to check the checkbox which you previously unchecked

## Expected Behavior
I should be able to re-enable the permissions.

## Technical Details
- Device: Mac OSX 10.10.4, Chrome latest
- Directus App: Live demo site
- Directus API: Directus Latest deployment

**Comment by benhaynes** [comment]
Thanks @ransoing – we'll look into this asap!

**Comment by rijkvanzanten** [comment]
Thanks for your detailed issues @ransoing! Really helps out to quickly resolve these issues 😄

**Comment by benhaynes** [comment]
I'll second that... the replication steps are very clear and helpful! Thank you so much!
