### ISSUE TITLE
Custom interface extensions not loading

### ISSUE THREAD

**Issue by k15a** [directus/app#994]
## Describe the Bug
When I duplicate a core interface extension and change the name and move it to the custom directory it's not showing up in directus.

## Steps to Reproduce
1. Install directus from the build-v7 branch with docker
2. Copy one interface extensions (e.g. text-input) to custom and rename it to something else
3. Change the name in meta.json to something else
4. Go to the directus admin page and the interface doesn't appear in the interfaces section

## Expected Behavior
The custom interface should load

## Technical Details
- Device: Desktop
- OS: MacOS 10.14
- Directus App: 7.0.1
- Directus API: 2.0.0

Also is there a guide how to setup the build pipeline for custom extensions. I tried to build my extension with webpack and parcel and both show me the error and is it supported to symlink the extension to the core / custom folder. It seems that directus is not following symlink.

![screenshot 2018-10-17 at 16 54 16](https://user-images.githubusercontent.com/20357450/47095335-579bf500-d22d-11e8-9ad8-f17deb1f7a03.png)

**Comment by rijkvanzanten** [comment]
This is caused by https://github.com/directus/api/issues/500

**Comment by rijkvanzanten** [comment]
> Also is there a guide how to setup the build pipeline for custom extensions. I tried to build my extension with webpack and parcel and both show me the error and is it supported to symlink the extension to the core / custom folder. It seems that directus is not following symlink.

We don't have a guide for that yet.. The plan is to extract the build setup used in `/extensions` to it's own npm package so you can use that and make sure the extensions are build the same way as the core ones. Until that's done, the best thing I can recommend is to copy the `package.json` file present in the `/extensions` folder in the `api` repo.

**Comment by k15a** [comment]
Seems that you fixed that already. Thank you very much.
