### ISSUE TITLE
"Value should not be blank" error for required fields with default values

### ISSUE THREAD

**Issue by ransoing** [directus/app#995]
## Describe the Bug
When adding a new item in a collection, if the item has a required field, and that required field has a default value, I cannot save the item until I edit the required field's value.

## Steps to Reproduce
Steps to reproduce the behavior in the Directus Latest demo on directus.app:
1. Log in as admin user
1. Click on "Admin Settings" in the lower-left corner
1. Click on "Collections & Fields"
1. Click on "Concessions"
1. Click on "Price" in the list of Fields
1. Set a default value, i.e. `5.99`, and turn the "Required" slider on. Click through to save the changes
1. Click on the Concessions collection on the left side of the page
1. Click the blue + button in the upper-right corner
1. Enter a name and a category. Leave the default value as it is.
1. Hit the blue checkbox in the corner to save the item.
1. An error pops up: "price: This value should not be blank.", even though the field is not blank.

You can save the item if you edit the 'price' field, i.e. deleting one of the 9's and adding it back in.
This also happens for other field types, like checkboxes or sliders. If the slider value is required, and it has a default value, the user must toggle it at least once before being able to save the item.

## Expected Behavior
The default value for required items should not be considered blank

## Technical Details
- Device: Mac OSX 10.10.4, Chrome latest
- Directus App: Live demo site, https://directus.app
- Directus API: Directus Latest deployment

**Comment by rijkvanzanten** [comment]
The fix in #1003 causes the app to nearly always stage a value on the edit view, which means that you'll get a "Are you sure you want to leave modal" no matter what happens.

**Comment by benhaynes** [comment]
Here's how I'd like to see this work:

1. Creating an Item
2. App creates for, with defaults added
    * _Initial checkbox sate is determined by default value, inputs are pre-filled with any default strings, etc_
3A. The App tracks any _changes_ manually made to the form, such as a user changing a checkbox, or sliding a slider. And only warns about "lost changes" if there are traced changes.
3B: Alternatively, we can keep things the same as now, but when a user tries to save, we remove any values that match the default from the staged changes. 

1. Editing an Item
2. App loads all data based on database values only (no defaults)
3. We do whatever we're doing now... track changes as they're made, or compare to the original data on save.

Does that work @rijkvanzanten ? Any preference between 3A and 3B?

**Comment by rijkvanzanten** [comment]
The API now uses the default when a value isn't passed in
