### ISSUE TITLE
Checkboxes don't work in the "many to one" dialog

### ISSUE THREAD

**Issue by ransoing** [directus/app#996]
## Describe the Bug
Checkboxes aren't toggle-able when editing a many-to-one field for an item.

## Steps to Reproduce
Steps to reproduce the behavior with the Directus Latest demo on directus.app:
1. Log in as admin user
1. Click on the Showtimes collection on the left
1. Click the blue + button in the upper-right corner
1. Click on the Theater input field - a dialog pops up, listing many theaters
1. Try to click on any of the checkboxes. They don't become selected, but the "Save" button becomes enabled. Attempting to click "Save" causes a javascript error:

```
vue.runtime.esm.js:1737
Error: Invalid notNull value: null
Argument Name: primaryKey
```

Additionally, the dialog box is a scrollable window within a scrollable window, causing a double vertical scrollbar, one of which is initially hidden due to the horizontal scrollbar.

## Expected Behavior
Users should be able to select an item to populate the field

## Technical Details
- Device: Mac OSX 10.10.4, Chrome latest
- Directus App: Live demo site, https://directus.app
- Directus API: Directus Latest deployment

**Comment by ransoing** [comment]
This might be the same issue as #844

**Comment by benhaynes** [comment]
Even if it's a duplicate, you've included steps to reproduce... which is extremely helpful for us getting these closed quickly. Thank you @ransoing !

**Comment by logos914** [comment]
## Describe the Bug
I have the same problem in my self-hosted instance, but I tried to reproduce it on your demo server and the bug persists

I hope this may helpful, sorry for my bad english
Thanks for the effort and for this great project


## Steps to Reproduce
1. Go to https://directus.app/collections/tickets/
2. Click on + (New)
3. try to select a Showtime
4. Cannot select a item, the save button freeze in loading


## Screenshots
https://daxel.logos.net.ar/directus001.jpg
https://daxel.logos.net.ar/directus002.jpg


## Additional Context
```
vue.runtime.esm.js:1737 Error: Invalid notNull value: null
Argument Name: primaryKey
    at Object.notNull (argument-validator.js:41)
    at Object.getItem (remote.cjs.js:784)
    at o.populateDropdown (input.js:4)
    at o.t (vue.runtime.esm.js:2023)
    at o.Pt.e.$emit (vue.runtime.esm.js:2534)
    at click (modal.vue?1af6:1)
    at o.t (vue.runtime.esm.js:2023)
    at o.Pt.e.$emit (vue.runtime.esm.js:2534)
    at click (button.vue?1dd4:1)
    at t (vue.runtime.esm.js:2023)

```
## Technical Details
- Device: Desktop
- OS: Windows 10 64bits
- Browser: Versión 69.0.3497.100 (Build oficial) (64 bits)
- Directus App: https://directus.app/
- Directus API: https://directus.app/
