### ISSUE TITLE
What is the demo username and login - it's not listed anywhere

### ISSUE THREAD

**Issue by mypark** [directus/app#998]
## Describe the Bug
A clear and concise description of the bug

## Steps to Reproduce
3. Scroll down to '...'

## Expected Behavior
A clear and concise description of what you expect to happen

## Screenshots
If applicable, add screenshots to help explain your problem

## Additional Context
Any other context about the problem

## Technical Details
- Device: [e.g. Desktop, iPhone6, etc]
- OS: [e.g. MacOS 10.13.6, Windows 10.1803]
- Browser: [e.g. Chrome 68.0.3440.106]
- Directus App: [e.g. 7.0.0]
- Directus API: [e.g. 2.0.0]

**Comment by Nitwel** [comment]
User: admin@example.com
Pw: password
But should be listed somewhere.

**Comment by benhaynes** [comment]
Where did you look? This is a common request, and until we can get it listed on demo itself I want to know where people are looking so we can add it...

https://docs.directus.io/install.html#logging-in
https://docs.directus.io/api/admin-guide/configure-manually.html#system-schema

![screen shot 2018-10-18 at 2 15 52 pm](https://user-images.githubusercontent.com/522079/47175127-5e377480-d2e0-11e8-9e5c-512ebaa9f64e.png)

![screen shot 2018-10-18 at 2 29 17 pm](https://user-images.githubusercontent.com/522079/47175871-39440100-d2e2-11e8-8df2-55102a19c62c.png)

**Comment by mypark** [comment]
I looked on your github readme where it gives a linke to the demo but no password.  
https://github.com/directus/app

**Comment by benhaynes** [comment]
Thanks! I've updated all three READMEs to include the demo creds

https://github.com/directus/app

**Comment by mmakarios** [comment]
I also wasted some time looking for the demo credentials. I think a good place to add it as well would be in the environment setup instructions: https://docs.directus.io/app/contributor-guide/install-dev.html

**Comment by benhaynes** [comment]
Thanks @mmakarios! We've added it here as well...

**Comment by stevenalanstark** [comment]
It's missing on the docker readme:

https://github.com/directus/docker
